### ISSUE TITLE
No syntax detection for .bashrc

### ISSUE THREAD

**Issue by michaelmior** [sharkdp/bat#100]
`.bashrc` et al. are listed as recognized filetypes, but have no colouring with `bat` when run without any options. That is, I expect that if I run `bat ~/.bashrc` that syntax highlighting would be enabled, but it isn't.

**Comment by sharkdp** [comment]
Thank you for your feedback!

I noticed the same thing recently with `.gitconfig` files. I think this is a bug / missing feature in `syntect` which I believe should be easy to fix. I will look into this.

**Comment by michaelmior** [comment]
Thanks! On a somewhat related note, it seems like `zsh` support is there, but `.zshrc` wasn't listed among the supported extensions.

**Comment by sharkdp** [comment]
Hm, `bat ~/.zshrc` does not work for me.

Btw, note that you can always use the `--language`/`-l` option:
``` bash
bat -l sh ~/.bashrc
```

**Comment by michaelmior** [comment]
That was my point, that `bat ~/.zshrc` doesn't work. But it seems like it should since `.bashrc` is supported :) But I guess this a "bug" with syntect and not bat.

**Comment by sharkdp** [comment]
See https://github.com/trishume/syntect/pull/163

**Comment by michaelmior** [comment]
Thanks @sharkdp!

**Comment by sharkdp** [comment]
My PR has been merged in syntect, so this should work now.

`.zshrc` does not work, as it is not part of the known file extensions / names.

**Comment by michaelmior** [comment]
Thanks! I'm guessing I should raise the `.zshr` issue with syntect?

**Comment by sharkdp** [comment]
syntect is probably not the right place to ask. We would need a `.sublime-syntax` file for `.zshrc` (or `.zsh`) files and add it here: https://github.com/sharkdp/bat/tree/master/assets/syntaxes

One potential problem with that is that the Bash syntax actually adds `.zsh` as a file extension (but not `.zshrc`).

**Comment by sharkdp** [comment]
Another option is to add a mode-line to the top of your `.zshrc` file:

```
# -*- mode: shell-script -*-
```

**Comment by sharkdp** [comment]
Fixed in v0.4
