### ISSUE TITLE
Error when installing bat and other Rust packages at the same time (/usr/.crates2.json)

### ISSUE THREAD

**Issue by kuntau** [sharkdp/bat#1007]
```sh
Preparing to unpack .../bat_0.12.1-1build1_amd64.deb ...
Unpacking bat (0.12.1-1build1) ...
dpkg: error processing archive /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package ripgrep 11.0.2-1build1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/bat_0.12.1-1build1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I'm on Ubuntu 20.04

**Comment by sharkdp** [comment]
Please see #938

**Comment by mikesigs** [comment]
I am having this issue and the linked issue above seems to have been moved/deleted. The link no longer works. Is there a fix for this?

**Comment by sharkdp** [comment]
> I am having this issue and the linked issue above seems to have been moved/deleted

That is unfortunate. I have no idea how that happened :frowning_face:. It was a lengthy discussion with feedback from multiple users and the maintainer of the Debian/Ubuntu package for `bat`. @eth-p Do you have any idea what could have happened? Maybe one of us accidentally deleted it? Or @SamuelMarks who was the original author?

Fortunately, there is a cached version of the page here:
https://webcache.googleusercontent.com/search?q=cache:PB93G5FPqCAJ:https://github.com/sharkdp/bat/issues/938+&cd=1&hl=de&ct=clnk&gl=de&client=ubuntu

I don't think that was the latest state, but it's better than nothing.

Here is a screenshot, in case the link above should expire at some point:
![image](https://user-images.githubusercontent.com/4209276/85329426-cd606580-b4d2-11ea-9b0a-214b144dd04d.png)

I'm going to notify everyone involved in the original discussion here - sorry in case you had already unsubscribed from that ticket: @manaskarekar, @qstrahl, @MarcelGerber, @paride

**Comment by mikesigs** [comment]
Thanks for pouncing on this one so quickly.

**Comment by MarcelGerber** [comment]
Probably the most important link in the now-deleted issue was the link to [Ubuntu Bug #1868517: Stray /usr/.crates2.json file](https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517).

Also, a few days ago user @psicho2000 posted a workaround that worked fine for me:
> As a workaround, you can use
> `sudo apt install -o Dpkg::Options::="--force-overwrite" bat ripgrep`
> (taken from https://askubuntu.com/questions/176121/dpkg-error-trying-to-overwrite-file-which-is-also-in/176132#176132).

**Comment by eth-p** [comment]
> That is unfortunate. I have no idea how that happened :frowning_face:. It was a lengthy discussion with feedback from multiple users and the maintainer of the Debian/Ubuntu package for `bat`. @eth-p Do you have any idea what could have happened? Maybe one of us accidentally deleted it? Or @SamuelMarks who was the original author?

That is really unfortunate, #938 had some pretty important discussion.

I don't think that I accidentally deleted issue? I mostly use the mobile app when I'm reading or commenting on issues, and it doesn't look like it's possible to delete an issue from it accidentally (or even intentionally).

I think something might have happened to @SamuelMarks' account. His profile page 404s, and it seems like his comments and issues on other projects are gone too, which [isn't something that is supposed to happen when you delete an account](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/deleting-your-user-account).

**Comment by sharkdp** [comment]
> I do think something might have happened to @SamuelMarks' account, though. His profile page 404s, and it seems like his comments and issues on other projects are gone too, which [isn't something that is supposed to happen when you delete an account](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/deleting-your-user-account).

Ah, that's possible - thanks for looking into it! Strangely, that acoount page was still available yesterday. Anyway, I think we have the important information stored in this ticket now.

**Comment by SamuelMarks** [comment]
Hi all, there was a disagreement with GitHub which has since been resolved.

During this disagreement, all my contributions—including PRs and comments—disappeared from public view.

It now all active again. Apologies for the confusion

**Comment by SamuelMarks** [comment]
Hi all, there was a disagreement with GitHub which has since been resolved.

During this disagreement, all my contributions—including PRs and comments—disappeared from public view.

It is now all active again. Apologies for the confusion

**Comment by sharkdp** [comment]
@SamuelMarks Thank you - I'll close this in favor of #938 then.
