### ISSUE TITLE
Add Dockerfile syntax

### ISSUE THREAD

**Issue by AlexArgoAi** [sharkdp/bat#101]
Docker does not need introducing anymore, and Dockerfiles are quite common now, with a relatively simple syntax. Having coloration for these would be great.

**Comment by sharkdp** [comment]
Sounds good.

Whenever we add support for a new syntax, we need a matching `.sublime-syntax` file (preferably with a source repository that we can simply [add here](https://github.com/sharkdp/bat/blob/cb7b158172a8336778dc860795a1f2cdc0180356/assets/create.sh#L28)). Also, it would be good to have a small example file that we can use to double-check if the syntax file works correctly.
