### ISSUE TITLE
Color difference over ssh

### ISSUE THREAD

**Issue by mjlbach** [sharkdp/bat#1011]
**What version of `bat` are you using?**
bat 0.15.1

**Describe the bug you encountered:**
The colorscheme appears different depending on if I'm connected via ssh (even localhost)

A subtle difference:
![Screenshot from 2020-05-23 22-50-37](https://user-images.githubusercontent.com/13316262/82746717-d6311080-9d47-11ea-94ca-b91ad43787a2.png)

A more obvious difference when using delta with the TwoDark colorscheme:
![Screenshot from 2020-05-23 22-29-03](https://user-images.githubusercontent.com/13316262/82746789-8f8fe600-9d48-11ea-82b2-7b3446588388.png)
![Screenshot from 2020-05-23 22-28-59](https://user-images.githubusercontent.com/13316262/82746791-9159a980-9d48-11ea-937a-2cb8817130f6.png)

I think my colors are set appropriately, since these test seem to work fine over ssh

![Screenshot from 2020-05-23 22-53-35](https://user-images.githubusercontent.com/13316262/82746763-4d66a480-9d48-11ea-8cec-fa63fc89a10e.png)

**Describe what you expected to happen?**
The colorscheme matches.

**How did you install `bat`?**
apt-get, homebrew, GitHub release, etc.
nixpkgs

---

[paste the output of `info.sh` here]

```
 ~                                                      
❯ bash info.sh 
system
------

**$ uname -srm**
Linux 5.6.13-300.fc32.x86_64 x86_64  

bat
---

**$ bat --version**
bat 0.15.1  

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 551 (POSIX regular expressions)  
```

**Comment by sharkdp** [comment]
This is most likely related to the `COLORTERM` environment variable which is probably not set on the remote machine? In this case, `bat` will fall back to 8bit colors instead of 24bit colors. See https://github.com/sharkdp/bat#troubleshooting

**Comment by mjlbach** [comment]
That was it! I can't believe I missed that section, thank you!

**Comment by sharkdp** [comment]
You're welcome. Let us know if you think that the documentation could be improved.
