### ISSUE TITLE
Can bat replace less?

### ISSUE THREAD

**Issue by rajeshisnepali** [sharkdp/bat#1018]
I'm just curious. 

I just can not calculate the times in both (bat & less). I kinda feel the same through the output.

I want to know does hitting `bat` command works like `less` by loading the only content user sees on their screen & show more content as the user scrolls the page OR it loads all the content for the first time & shows the content by scroll?

**Comment by sharkdp** [comment]
Not entirely sure if I understand all your questions, but note that `bat` calls `less`. `bat` is like a preprocessor of the content before `less` is called. In this sense, you should be able to use `bat` in places where you previously used `less`.

> I want to know does hitting `bat` command works like `less` by loading the only content user sees on their screen & show more content as the user scrolls the page OR it loads all the content for the first time & shows the content by scroll?

With `bat`, you would load all the content first. The output is then piped to `less`.

Are you sure that `less` works this way (only loading the content that the user sees on the screen)?

**Comment by rajeshisnepali** [comment]
> Are you sure that less works this way (only loading the content that the user sees on the screen)?

Sorry, I've no idea about that.
