### ISSUE TITLE
Add syntax mappings to 'bat --list-languages' output

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#1024]
We should think about showing the explicit syntax mappings (the builtin ones and the user provided `--map-syntax=…` ones) to the `bat --list-languages` output, next to the other file extensions. For example:
```
SSH Config                    ssh_config, **/.ssh/config
Bourne Again Shell (bash)     sh, bash, […], /etc/profile, **/bat/config
```

I think we can skip the `MapToUnknown` mappings

**Comment by alexnovak** [comment]
Took a stab at this! Will have a PR up later tonight.
