### ISSUE TITLE
Solarized themes are missing from 0.15.3

### ISSUE THREAD

**Issue by adamtabrams** [sharkdp/bat#1027]
**What version of `bat` are you using?**
bat 0.15.3

**Describe the bug you encountered:**
`bat --list-themes` does show any Solarized themes.
And using bat with a Solarized theme set in the bat.conf gives this error:
`[bat warning]: Unknown theme 'Solarized (dark)', using default.`

**Describe what you expected to happen?**
I expected to see both light and dark variants of the Solarized theme using `bat --list-themes`.
And I expected my bat.conf that uses the Solarized (dark) theme to continue working.

**How did you install `bat`?**
homebrew

**Comment by lukehsiao** [comment]
This is also true for when I installed `bat` using `cargo`.

**Comment by sharkdp** [comment]
Fixed in #1029. I added a test to make sure this does not happen again.

**Comment by sharkdp** [comment]
Fix released in [v0.15.4](https://github.com/sharkdp/bat/releases/tag/v0.15.4)

**Comment by ralphee** [comment]
> Fix released in [v0.15.4](https://github.com/sharkdp/bat/releases/tag/v0.15.4)

experiencing this issue [v 0.18.0](https://archlinux.org/packages/community/x86_64/bat/)
`[bat warning]: Unknown theme 'Solarized', using default`
`export BAT_THEME="Solarized"` .zshenv 
[bat --list-themes](http://ix.io/2TJI)

**Comment by lukehsiao** [comment]
You need to specify light or dark. For example,

```
export BAT_THEME="Solarized (dark)"
```
