### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by BrainMaestro** [sharkdp/bat#103]
Hey, there should be a way to test the output of `bat` to make future style related changes easier. Right now, it's not easy to see how all the different style options interact with each other. I thought of using snapshot based testing which would look something like what [jest](https://facebook.github.io/jest/docs/en/snapshot-testing.html) does. Basically, we just generate snapshot text files with the different options, and commit them to the repo. Then write an integration test that checks if the output is still the same with the changes introduced in a PR. I'm pretty far along with it already, but let me know what you think

**Comment by sharkdp** [comment]
That sounds fantastic and is something that was on my personal to-do list as well. I think `bat` could also use a few more unit tests here and there but using this snapshot-based integration testing sounds perfect for some of our functionality.

**Comment by sharkdp** [comment]
closed via #105
