### ISSUE TITLE
How to turn off left sidebar with line numbers?

### ISSUE THREAD

**Issue by garyo** [sharkdp/bat#1048]
Most of the time I don't need line numbering, and it takes up valuable horizontal space. I'd like to disable those by default in my config file, but leave the style for everything else at "auto" rather than hard-coding things. Is there an option I missed to disable line numbering? I see that `-n` always _enables_ line numbers, but no option to disable.

I'm running bat 0.15.4 on Linux Ubuntu 18.04/WSL.

**Comment by sharkdp** [comment]
Check out the `--style` option

**Comment by garyo** [comment]
OK -- once #1032 is done I'll try it.
