### ISSUE TITLE
Any way to call Vim from Bat?

### ISSUE THREAD

**Issue by rr0ss0rr** [sharkdp/bat#1050]
I have `VISUAL=/Users/richard/bin/pager` defined where pager consists of
`[[ "$(ps -o comm= $PPID)" == "less" ]] && command mvim -f "$@" || command less "$@"`
This will initially view the file read only but have the ability to edit as well.
I'd like to replace less with bat, but this only works if I have a way to get to vim from bat.

Thanks

**Comment by eth-p** [comment]
This was surprisingly tricky, but it's possible with `LESSOPEN` and `LESSCLOSE`. Unfortunately, it also shows you a warning whenever you press `V`, though.

**.bash_profile**
```bash
export LESSOPEN="$HOME/.bin/less-preprocessor-bat.sh open \"%s\""
export LESSCLOSE="$HOME/.bin/less-preprocessor-bat.sh close \"%s\" \"%s\""
export LESS="-R"
```

**~/.bin/less-preprocessor-bat.sh**
```bash
#!/usr/bin/env bash
set -e
SOURCEFILE="$2"
TEMPFILE="${3:-$(mktemp)}"
case "$1" in
    open) {
        bat --paging=always --color=always --terminal-width=$(tput cols) "$SOURCEFILE" &> "$TEMPFILE"
        echo "$TEMPFILE"
    } ;;

    close) {
        rm "$TEMPFILE"
    } ;;
esac
```

**Comment by rr0ss0rr** [comment]
I appreciate the help but I couldn't seem to get this to work ... It took a minute that the changes were to "less" calling bat,  but when I execute this and type 'v', I receive "WARNING: This file was viewed via LESSOPEN (press Return)" then return back to bat.  If I type 'V', I receive "less 551 (press Return)"

**Comment by rr0ss0rr** [comment]
@eth-p  ... Thanks, I got it working.  I'll open this up as an enhancement request

**Comment by hacker-DOM** [comment]
> This was surprisingly tricky, but it's possible with `LESSOPEN` and `LESSCLOSE`. Unfortunately, it also shows you a warning whenever you press `V`, though.
> 
> **.bash_profile**
> 
> ```shell
> export LESSOPEN="$HOME/.bin/less-preprocessor-bat.sh open \"%s\""
> export LESSCLOSE="$HOME/.bin/less-preprocessor-bat.sh close \"%s\" \"%s\""
> export LESS="-R"
> ```
> 
> **~/.bin/less-preprocessor-bat.sh**
> 
> ```shell
> #!/usr/bin/env bash
> set -e
> SOURCEFILE="$2"
> TEMPFILE="${3:-$(mktemp)}"
> case "$1" in
>     open) {
>         bat --decorations=always --color=always --terminal-width=$(tput cols) "$SOURCEFILE" &> "$TEMPFILE"
>         echo "$TEMPFILE"
>     } ;;
> 
>     close) {
>         rm "$TEMPFILE"
>     } ;;
> esac
> ```

So I spent a few weeks with this solution; it's a neat solution. But I found it's a _little_ too intrusive. Sharing my current workflow instead:

```
# alias cat=bat
# alias e=nvim
cat file.ext # opens less with stdin
# browse
g
!e [kitty_mod+p>f; select file]
# done!
```

this uses the [hints](https://sw.kovidgoyal.net/kitty/kittens/hints) kitten of Kitty
