### ISSUE TITLE
Have the ability to open a vim session from bat (like less)

### ISSUE THREAD

**Issue by rr0ss0rr** [sharkdp/bat#1051]
@eth-p game me a work-around, but was hoping to have the ability added to bat to easily edit the file being viewed by bat.  Utilizing a variable to define  the editor `BAT_EDITOR` and entering a "v" to go into edit mode.

Thanks.

**Comment by eth-p** [comment]
It's not really possible to add this feature, unfortunately. We use `less` for paging, and once it starts printing its output, it's out of our control.

**Comment by rr0ss0rr** [comment]
oh darn.  Thanks again for the help

**Comment by eth-p** [comment]
Glad to help! If we ever end up including a custom pager, I'd be happy to add this feature though.

**Comment by sharkdp** [comment]
See also: #358, #464, #528, #697

> If we ever end up including a custom pager, I'd be happy to add this feature in the future.

I have actually started some work on this :smile:. The possibility to open an editor via keypress would be one of the immediate benefits, yes. Let's discuss this in #1053.
