### ISSUE TITLE
Bat wrap flag

### ISSUE THREAD

**Issue by kuntau** [sharkdp/bat#1052]
**What version of `bat` are you using?**
bat 0.15.4  

**Describe the bug you encountered:**
Bat wrap long lines when flag `--wrap never` was supplied.

[![asciicast](https://asciinema.org/a/czXjbIjoUZQV25qx57IiQqjMy.svg)](https://asciinema.org/a/czXjbIjoUZQV25qx57IiQqjMy)

**Describe what you expected to happen?**
No wrapping

**How did you install `bat`?**
Homebrew

---

system
------

**$ uname -srm**
Darwin 18.7.0 x86_64  

**$ sw_vers**
ProductName:	Mac OS X  
ProductVersion:	10.14.6  
BuildVersion:	18G5033  

bat
---

**$ bat --version**
bat 0.15.4  

**$ env**
PAGER=bat -p  
BAT_STYLE=plain  
BAT_THEME=Monokai Extended  

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)

**Comment by sharkdp** [comment]
`--wrap never` means that wrapping is left to the terminal emulator and/or the pager. 

If you really want horizontal scrolling instead, or cropped lines, you would have to use `--wrap never` and configure the terminal emulator / pager appropriately.

**Comment by kuntau** [comment]
Just figured out I need to specify $BAT_PAGER with `less -RSF`

That's mean bat didn't  do the paging itself but pass to default pager if not specified :/

**Comment by sharkdp** [comment]
Let us know if you think the documentation could be improved.
