### ISSUE TITLE
Can't quit normally after ctrl-end

### ISSUE THREAD

**Issue by Geobert** [sharkdp/bat#1055]
**What version of `bat` are you using?**
bat 0.15.4
In Ubuntu 20.04 installed in a hyper-V VM on Windows 1909 host.
From Windows Terminal 1.0.

**Describe the bug you encountered:**
Opening a file longer than the height of the term, I press Ctlr-End to reach the end of the file. Once at the end of the file, I have the message `Waiting for data... (interrupt to abort)` and can't quit normally. 

When I interrupt, the display seems normal but when I hit a key, the screen blink back to prompt before the call to `bat`

**Describe what you expected to happen?**
I should be able to quit normally

**How did you install `bat`?**
dpkg -i 

---

system
------

**$ uname -srm**
Linux 5.4.0-33-generic x86_64

**$ lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

bat
---

**$ bat --version**
bat 0.15.4

**$ env**
BAT_THEME=Monokai Extended

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 551 (GNU regular expressions)

**Comment by sharkdp** [comment]
>  I press Ctlr-End to reach the end of the file

Just press `End`. `Ctrl-End` is something else. I think it's like `F` ("forward forever") which waits for additional input.

**Comment by Geobert** [comment]
Thank you for your answer!

For some reason, it doesn't work in my Linux VM, neither from Windows Terminal 1.0 nor the old console (cmd.exe then ssh to the VM).

It works on Windows Terminal 1.0 PowerShell on Windows though

**Comment by sharkdp** [comment]
what exactly "doesn't work"?

**Comment by Geobert** [comment]
It doesn't do anything at all :)

**Comment by sharkdp** [comment]
Okay, so you use Windows Terminal with the ancient `cmd.exe` to SSH into a Linux VM, running another shell, to use `bat` which opens `less` ... and you are expecting all key presses to be delivered accurately? :smile: 

I'm sorry, but I cannot reproduce this easily and - honestly - I don't think it's related to `bat`. You would probably see a similar problem when using `less` directly (with `-RF`)?

**Comment by Geobert** [comment]
Nope, I'm using Windows Terminal running ssh to the Linux VM, no cmd involved in my main scenario.

I tested in the old console with cmd as well to check the behaviour :)
