### ISSUE TITLE
Minor: allow specifying character for "space" in `-A` mode

### ISSUE THREAD

**Issue by garyo** [sharkdp/bat#1056]
Right now, spaces are visualized as heavy dots:
![image](https://user-images.githubusercontent.com/139975/84426483-5208d500-abf1-11ea-89ac-5b353860bf79.png)
which is fine, but sometimes I'd prefer something a bit less overwhelming, while still being able to count my YAML indent.
It would be a nice addition to allow specifying the unicode char and/or color to use for the space-replacement char.

**Comment by LordFlashmeow** [comment]
I've been poking about in the code, and picking a character is pretty straightforward . The syntax coloring is currently linked to the heavy dot character, which I haven't been able to fix (yet).

The syntax is something like: `bat -A --space-char="*" somefile`, which isn't terrible.

However, it adds another parameter to `preprocessor::replace_nonprintable`, so it'll conflict with #1066 (until that's merged) and it feels a little clunky.

This feature adds only a little bloat but sets a precedent for heavy customizations. I think the feature is useful, but I'm not sure if it should be added. 

@sharkdp, is this something that should be added?

**Comment by sharkdp** [comment]
Thank you for reporting this.

TBH, I'd rather not add a new command-line option for this. There would be so many other things to configure/control on the same level. Maybe we should rather try to improve the default option? I agree that the current display of the space character and the color are maybe a bit too much. How about trying to use a less vibrant color? I'm also fine with a less heavy central-dot character.

**Comment by LordFlashmeow** [comment]
Maybe switch to "·" (U+00B7) [Middle Dot](https://www.compart.com/en/unicode/U+00B7) from "•" (U+2022) [Bullet](https://www.compart.com/en/unicode/U+2022)?

I couldn't make the colors work after 10 seconds of fiddling, but here's the difference:

| Before                                                                                                                                                                   | After                                                                                                                                                                    |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="670" alt="Screen Shot 2020-07-02 at 12 27 49 AM" src="https://user-images.githubusercontent.com/33206210/86330100-064bb900-bbfc-11ea-8200-37f5b25d03c2.png"> | <img width="670" alt="Screen Shot 2020-07-02 at 12 26 36 AM" src="https://user-images.githubusercontent.com/33206210/86330102-08157c80-bbfc-11ea-8a94-60a5f8869d94.png"> |

**Comment by sharkdp** [comment]
> Maybe switch to "·" (U+00B7) [Middle Dot](https://www.compart.com/en/unicode/U+00B7) from "•" (U+2022) [Bullet](https://www.compart.com/en/unicode/U+2022)?

Sounds good to me



> I couldn't make the colors work after 10 seconds of fiddling, but here's the difference:

You need to adapt `assets/syntaxes/02_Extra/show-nonprintable.sublime-syntax` if you change the character. This file also needs to be modified if we want to change the color. Note that you have to run `bash assets/create.sh` and rebuild `bat` after making a change to that file.

**Comment by LordFlashmeow** [comment]
> Note that you have to run bash assets/create.sh and rebuild bat after making a change to that file.

Aha! That's what I was missing. Is that documented anywhere, or passed on by word of mouth?

**Comment by sharkdp** [comment]
Changed in [v0.16.0](https://github.com/sharkdp/bat/releases/tag/v0.16.0).
