### ISSUE TITLE
Question about '--map-syntax'.

### ISSUE THREAD

**Issue by Rabidsquirrel728** [sharkdp/bat#1057]
I'm sorry if this is a dumb question or if it has been asked or addressed in another question but i cant figure out how to map my zsh config files to the Bourne Again Shell (Bash) syntax. Also I used apt to install if that helps at all.

My bat config file is set up like so:
### ~/.config/bat/config
```
# Set the theme
##--theme='TwoDark'
##--theme='OneHalfLight'
--theme='zenburn'

# Add mouse scrolling support in less
--pager='less-FR'

# Use "gitignor" highlighting for ".ignore" files
--map-syntax .ignore:.gitignore

# Use "bash" highlighting for "zsh" config files
--map-syntax .zsh_extras:bash
--map-syntax .zsh_aliases:bash
```
I was also hoping i might be able to do something like `--map-syntax .zsh_*:bash`.

I know when i use `bat -l zsh .zsh_extras` it works fine but because I make changes to those files so often and need to refer to those files so often it would be nice to just type `bat .zsh_extras`.

**Comment by sharkdp** [comment]
> I was also hoping i might be able to do something like `--map-syntax .zsh_*:bash`.

You need to use the *full name of the syntax* on the right hand side:
```bash
--map-syntax '.zsh_*:Bourne Again Shell (bash)'
```
Do you think we could improve the documentation / `--help` text to make this more clear?

> # Add mouse scrolling support in less
> --pager='less-FR'

This looks wrong (there is no space between `less` and `-FR`. This line should not be needed anymore with recent versions of `bat`.

**Comment by sharkdp** [comment]
Actually.. which version of `bat` are you using? You should get an error message in recent versions.

**Comment by Rabidsquirrel728** [comment]
sorry for late response but running `bat --version` returned `bat 0.15.4`.
