### ISSUE TITLE
Syntax detection for vimrc 

### ISSUE THREAD

**Issue by alaymari** [sharkdp/bat#106]
vimrc is not on the list of languages supported. I think it is more of an issue with syntect, rather than bat. This is a feature request for vimrc syntax to be recognised :-)

I hope I can raise another request here itself. The output of bat --list-languages is difficult to read. Can the output be sorted on the entries in the first column, so that searching for a particular type is easier?

**Comment by sharkdp** [comment]
> vimrc is not on the list of languages supported. I think it is more of an issue with syntect, rather than bat. This is a feature request for vimrc syntax to be recognised :-)

Sounds good. This is not an issue with syntect - we can add this here in `bat`.

Whenever we add support for a new syntax, we need a matching `.sublime-syntax` file (preferably with a source repository that we can simply [add here](https://github.com/sharkdp/bat/blob/cb7b158172a8336778dc860795a1f2cdc0180356/assets/create.sh#L28)). Also, it would be good to have a small example file that we can use to double-check if the syntax file works correctly.

> I hope I can raise another request here itself. The output of bat --list-languages is difficult to read. Can the output be sorted on the entries in the first column, so that searching for a particular type is easier?

Yes, we should do this. Could you please open a new ticket for this request?

**Comment by sharkdp** [comment]
There is this: https://github.com/SalGnt/Sublime-VimL

However, there is no `.sublime-syntax` file, only a `.tmLanguage` file.
