### ISSUE TITLE
Feature request: Mouse scroll

### ISSUE THREAD

**Issue by w4nderlust** [sharkdp/bat#1062]
Love bat, just discovered it and made my day!
I wish I was able to use the mousewheel to scroll both up and down through files too, like the micro editor does https://micro-editor.github.io/

**Comment by eth-p** [comment]
You can already do that, actually. Either set `export BAT_PAGER='less -R'` in your bash profile, or change the config file at `bat --config-file` and add `--pager='less -R'` to it.

**Comment by w4nderlust** [comment]
Lovely, thank you!
