### ISSUE TITLE
Incorrect syntax highlighting in Vim file

### ISSUE THREAD

**Issue by FranklinYu** [sharkdp/bat#1064]
**Describe the bug you encountered:**

File:

```vim
set runtimepath=~/foo/bar
```

`/foo/` is incorrectly considered Regular Expression:

![screenshot](https://user-images.githubusercontent.com/52205/85144036-9828ee80-b218-11ea-9771-0c0fcab382b8.png)

**Describe what you expected to happen?**

`/foo/` should have the same color as `bar` following it.

**How did you install `bat`?**

MacPorts

<details><summary>diagnostics information</summary>

system
------

**$ uname -srm**
Darwin 19.5.0 x86_64

**$ sw_vers**
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

bat
---

**$ bat --version**
bat 0.13.0

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)
</details>

**Comment by sharkdp** [comment]
Thank you for reporting this.

This needs to be fixed in https://github.com/SalGnt/Sublime-VimL

**Comment by sharkdp** [comment]
Fixed by @esensar in https://github.com/SalGnt/Sublime-VimL/pull/12 and #1450.
