### ISSUE TITLE
Proofread Russian version of README

### ISSUE THREAD

**Issue by gsomix** [sharkdp/bat#1067]
There are some flaws in Russian translation of README (mostly grammar and punctuation errors), we need to correct it.

**Comment by sharkdp** [comment]
Feel free to do that. Maybe you could get in touch with @DuckerMan kindly provided the initial version.

**Comment by DuckerMan** [comment]
Hi there! Will fix in 2 days, thanks!

**Comment by DuckerMan** [comment]
By the way, it'd be cool if you said some grammar errors you've found
