### ISSUE TITLE
bat_0.15.4_amd64.deb does nothing on ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by francogp** [sharkdp/bat#1068]
**What version of `bat` are you using?**
0.15.4

**Describe the bug you encountered:**
installed the .deb file on ubuntu LTS 18.04, but no batcat files are installed or usable

**Describe what you expected to happen?**
install the program

**How did you install `bat`?**
downloaded the bat_0.15.4_amd64.deb file

**Comment by sharkdp** [comment]
If you get a binary from the release page of this repo, the binary is called `bat`, not `batcat`. See README for details on that issue.

**Comment by francogp** [comment]
> If you get a binary from the release page of this repo, the binary is called `bat`, not `batcat`. See README for details on that issue: https://github.com/sharkdp/bat#on-ubuntu-using-apt

I already know. No bat or batcat files or commands work on Ubuntu 18.04, after installing the named .deb

**Comment by eth-p** [comment]
The deb file on the releases page should have installed `bat` to `/usr/bin`.

Can you let us know the output of the following commands:

```
sudo dpkg -l bat
sudo dpkg -p bat
sudo dpkg -i bat_0.15.4_amd64.deb
```

**Comment by francogp** [comment]
> The deb file on the releases page should have installed `bat` to `/usr/bin`.
> 
> Can you let us know the output of the following commands:
> 
> ```
> sudo dpkg -l bat
> sudo dpkg -p bat
> sudo dpkg -i bat_0.15.4_amd64.deb
> ```

```
❯  sudo dpkg -i bat_0.15.4_amd64.deb                                                       
(Leyendo la base de datos ... 263330 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar bat_0.15.4_amd64.deb ...
Desempaquetando bat (0.15.4) sobre (0.15.4) ...
Configurando bat (0.15.4) ...
Procesando disparadores para man-db (2.8.3-2ubuntu0.1) ...
```
```
❯ sudo dpkg -p bat                                                                       
dpkg-query: ell paquete `bat' no está disponible.
Utilice dpkg --info (= dpkg-deb --info) para examinar archivos,
y dpkg --contents (= dpkg-deb --contents) para listar su contenido.
```
```
❯ sudo dpkg -l bat                                                                      
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre                Versión         Arquitectura    Descripción
+++-=====================-===============-===============-================================================
ii  bat                   0.15.4          amd64           A cat(1) clone with wings.
```

```
❯ batcat README.md                                                                    
Orden «batcat» no encontrada. Quizá quiso decir:
  la orden «fatcat» del paquete deb «fatcat»
Pruebe con: sudo apt install <nombre del paquete deb>
```

**Comment by francogp** [comment]
False alarm, it was an alias problem from zsh. Sorry
