### ISSUE TITLE
ANSI color is not working on Windows

### ISSUE THREAD

**Issue by MPThLee** [sharkdp/bat#107]
![image](https://user-images.githubusercontent.com/26970092/39963246-7114767c-56a1-11e8-9fe0-8bb4b1a9d3ae.png)
Left is ConEmu(that support ansi color), Right is CMD.

Maybe need to turn on Ansi VT? (Works after Win10 TH2) https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

From other project. https://github.com/ogham/rust-ansi-term/blob/master/src/windows.rs

Edit: It seems bat use `ansi-term` but color is not working on my machine.

**Comment by sharkdp** [comment]
Thank you for your feedback.

> Edit: It seems bat use ansi-term but color is not working on my machine.

Yes, we need to call [enable_ansi_support](https://docs.rs/ansi_term/0.11.0/i686-pc-windows-msvc/ansi_term/fn.enable_ansi_support.html). I hope that #109 should fix this.

**Comment by MPThLee** [comment]
I'm sorry but i think you are forgot to use `use` or `super::ansi_term`.

```
   Compiling bat v0.3.0 (https://github.com/sharkdp/bat#b9c780c8)
error[E0433]: failed to resolve. Use of undeclared type or module `ansi_term`
  --> src\app.rs:19:56
   |
19 |         let interactive_output = interactive_output && ansi_term::enable_ansi_support().is_ok();
   |                                                        ^^^^^^^^^ Use of undeclared type or module `ansi_term`

error: aborting due to previous error
```

**Comment by Aankhen** [comment]
Sorry for the necro, but I thought this may be related. I installed `bat` today and tried it in Cmder, the Cmder installation of ConEmu, PowerShell, and the regular Command Prompt. The first two gave me this:

![White-on-grey text everywhere except the filename](https://user-images.githubusercontent.com/978992/44955053-8acb3480-aeca-11e8-8fbd-ab3bd744af1f.png)

PowerShell gave me this (presumably just different default terminal colours; please excuse the crude black censor bar):

![White-on-pink text everywhere except the filename](https://user-images.githubusercontent.com/978992/44955069-d1209380-aeca-11e8-9033-73f1c1aec1d8.png)

Command Prompt gave me this, like the first two:

![White-on-grey text everywhere except the filename](https://user-images.githubusercontent.com/978992/44955084-075e1300-aecb-11e8-9d58-18934c823718.png)

`bat` looks really exciting and I’m eager to use it, so I hope this is just a misconfiguration on my end! FWIW, I get the same results without a `BAT_THEME` and with a `BAT_THEME` of `Monokai Extended Bright`.

**Comment by sharkdp** [comment]
@Aankhen Could you please open a new ticket (just copy over your comment)? I think I might have an idea of what's causing this.

**Comment by Aankhen** [comment]
Done.
