### ISSUE TITLE
Could a binary release for Cygwin be added?

### ISSUE THREAD

**Issue by psprint** [sharkdp/bat#1071]
Currently, fd doesn't understand the paths like `/usr/local` from Cygwin. A binary linked with `cygwin1.dll` would be needed. Could one be added?

**Comment by sharkdp** [comment]
I guess you mean `bat`. What's the actual error message? Would a similar workaround like https://github.com/sharkdp/fd/issues/153#issuecomment-353263132 work here as well?

**Comment by sharkdp** [comment]
Wait, everything is already explained here: https://github.com/sharkdp/bat#cygwin

**Comment by sharkdp** [comment]
@psprint any comment on this?

**Comment by medina7** [comment]
Well thw shell function does seem to resolve the problem, thanks.
