### ISSUE TITLE
`/etc/crypttab` "as an alias to" `-lfstab`

### ISSUE THREAD

**Issue by stdedos** [sharkdp/bat#1073]
With the exception for the spurious red in `1024`, I think formatting/output looks overall better

![image](https://user-images.githubusercontent.com/133706/85722047-97052f00-b6fa-11ea-9fb0-b5c9c076f021.png)

**Comment by sharkdp** [comment]
Thank you for the feedback. Sounds good!

This would be a simple addition in `Fstab.sublime-syntax`. In the meantime, you can add
```
--map-syntax='/etc/crypttab:fstab'
```
to your `bat` config file.

Not sure if the `1024` highlighting is intended. @eth-p ?

**Comment by stdedos** [comment]
Well, pedantically speaking, the format is _somewhat_ similar, but not 1-for-1 similar (or, by more strictly defining `/etc/fstab`, `/etc/cryptswap` can also be supported). 

But, as shown, one-liner merge _now_ is better than a complicated fix much later / never. 

Given that batrc change is easy, lgtm either way.

**Comment by eth-p** [comment]
> Not sure if the `1024` highlighting is intended. @eth-p ?

When I made the syntax, I wasn't really selective about the highlighting on that part of the fstab format.

The syntax will just highlight the values in the `key=value` pairs without any consideration to whether or not they're actually valid options.

**Comment by sharkdp** [comment]
This is now supported in [v0.16.0](https://github.com/sharkdp/bat/releases/tag/v0.16.0).
