### ISSUE TITLE
Short flag for --paging=never?

### ISSUE THREAD

**Issue by LordFlashmeow** [sharkdp/bat#1075]
Sometimes, when I'm working with files larger than my screen, I find it more frustrating to with deal with `less` than use iTerm's scrollback, so I can come back to it later. `less` is great for looking at the first n lines of the file, but after that it's a pain.

The auto setting works fine for everything else, the only time I need to use the paging flag is for `--paging=never`, so it feels very long for an effectively "true/false" flag. Would it be possible to add a single letter alias for `--paging=never`? (Maybe `-P`?)

**Comment by windwp** [comment]
You can create a bash alias for it

**Comment by sharkdp** [comment]
Thank you for your request.

Note that you can already use `--plain`/`-p` twice to disable paging (and reduce the style to "plain"):
```
bat -pp …
```

**Comment by LordFlashmeow** [comment]
Hmm. True, but then a lot of the decorations are missing. It looks like it's only a couple of lines to add — one if statement in `config()`, and a couple of lines to add the argument. I can make a PR with my proposed changes, unless you think it's a bad idea (it's your project, after all!)

**Comment by sharkdp** [comment]
Sounds good to me. @eth-p, what do you think?

**Comment by eth-p** [comment]
Short flags are at a bit of a premium, but this seems like a good reason to use one. 👍

**Comment by sharkdp** [comment]
Closed via #1082

**Comment by sharkdp** [comment]
Released in [v0.16.0](https://github.com/sharkdp/bat/releases/tag/v0.16.0).
