### ISSUE TITLE
Open file scrolled to the end

### ISSUE THREAD

**Issue by rajeshisnepali** [sharkdp/bat#1077]
cat (alias as bat) prints from the beginning of the file. 

My pager is `less -RF`

**Comment by sharkdp** [comment]
what does that mean? open file from the end?

do you want to read the lines of the file in reverse (if so, use `tac` and pipe into `bat`)? Or each character, but in reverse (why)?

**Comment by rajeshisnepali** [comment]
Using `tac` is good but I want something different.

Let's assume we're viewing a file & we press `j` or `Down Arrow` to move down
![image](https://user-images.githubusercontent.com/23610013/86317422-1640b880-bc4f-11ea-926d-83c637ba1952.png)

What I wanted is to view a file from the end. So that I can press `k` or `Up Arrow` to move up & see the content. 
![image](https://user-images.githubusercontent.com/23610013/86317497-45efc080-bc4f-11ea-93a9-9ef7ad712ad9.png)

> I can do the same thing by `cat filename` and then pressing `G`. But is there any kind of option to do in a single step?

**Comment by sharkdp** [comment]
`bat` uses `less` as a pager. And `less` has such a feature: https://unix.stackexchange.com/a/373465

So you can do the following:
```bash
bat --pager="less -FR +G" filename
```

If you want to enable this for every file, you can add `--pager="…"` do your config file. If you only want that for some files, maybe use a shell alias?
