### ISSUE TITLE
A mode to skip binary data

### ISSUE THREAD

**Issue by dtantsur** [sharkdp/bat#1078]
I have a long log file that has some garbage in the very beginning. Currently I cannot use bat to view it: the default mode just outputs `<BINARY>`, `-A` makes it unreadable since it replaces all spaces with "dots" (note: the file is 99.9% text). I'd be quite happy with a flag that just throws away all non-printable non-space characters.

**Comment by sharkdp** [comment]
Thank you for your request.

I think that would rather be left to a specialized program: `strings`. With some luck, you can pipe the output of `strings` into `bat -l language` to get syntax highlighting.

**Comment by sharkdp** [comment]
Closing as there is no further feedback.
