### ISSUE TITLE
Option --indent=0

### ISSUE THREAD

**Issue by sarnobat** [sharkdp/bat#1083]
bat is excellent. The one thing missing from making me never use cat again is that bat automatically indents all contents by one level.

I get why it exists, and is sometimes useful but for a lot of times I don't want this behavior. If there is no option to turn this off it would be great if you could introduce one.

**Comment by LordFlashmeow** [comment]
When does it do that? I'm not seeing it indenting by one level

**Comment by sarnobat** [comment]
Screenshot attached
<img width="1401" alt="Screen Shot 2020-07-01 at 11 30 13 AM" src="https://user-images.githubusercontent.com/2905777/86279101-54c26e80-bb8e-11ea-9263-069c7bb89a85.png">

**Comment by sarnobat** [comment]
Ah, I only just noticed that this there were line numbers being included (I didn't notice that in my dark background).

# solution
```
bat myfile.txt --plain
```

**Comment by LordFlashmeow** [comment]
You also have the `-p` flag to disable the line numbers and some decorations while keeping the syntax highlighting

**Comment by sarnobat** [comment]
Thanks for the info. Even --plain retains the syntax highlighting as far as I can tell.

**Comment by sharkdp** [comment]
You can also use `--style=…` to enable/disable the "UI" components that you want. See README for details.
