### ISSUE TITLE
Automatic color mode detection does not work

### ISSUE THREAD

**Issue by tnemeth** [sharkdp/bat#1094]
**What version of `bat` are you using?**
`bat 0.12.1`

**Describe the bug you encountered:**
When I use a monochrome terminal, bat, with `--color=auto` (default value) still displays a colored
output. The environment variables are:

```
$ echo $TERM
xterm-mono
$ echo $COLORTERM
$
```

**Describe what you expected to happen?**
I expected it to display its output as monochrome :) It was colored (the terminal, `konsole` supports colored output but it's configured as mono.

**How did you install `bat`?**
apt-get

system
------

**$ uname -srm**
Linux 5.7.0-1-amd64 x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID: Debian  
Description:    Debian GNU/Linux bullseye/sid  
Release:        testing  
Codename:       bullseye  

bat
---

**$ batcat --version**
bat 0.12.1  

**$ env**
./info.sh: line 61: bat: command not found

bat_config
----------

**$ cat /home/thomas/.config/bat/config**
```

# Use italic text on the terminal (not supported on all terminals)
--italic-text=always

```

bat_wrapper
-----------

No wrapper script for 'bat'.

No wrapper script for 'batcat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

No wrapper function for 'batcat'.

tool
----

**$ less --version**
less 551 (GNU regular expressions)

**Comment by tnemeth** [comment]
>  ./info.sh: line 61: bat: command not found

Replacing `bat` with `batcat` in the script at that line, or directly using the `--cache-dir` option on the CLI gives nothing.

**Comment by eth-p** [comment]
I don't believe there's currently any code for using the `TERM` environment variable to turn colors off.

It should be pretty simple to add, but we first need to figure out how it interacts with `--color=always`. Should that option take priority, or should the terminal type take priority, since that's reporting the maximum capabilities of the terminal?

@sharkdp, your thoughts?

Also, thanks for letting us know about the problem with the shell script. I'll need to fix that.

**Comment by sharkdp** [comment]
To clarify for @tnemeth : the `auto` option only turns off colors when the output of `bat` goes to a pipe. It's not meant to auto-detect the terminals color capabilities.

I'm not sure if the capability detection of terminals would work without any problems. I would be afraid that we might turn off colors for some users accidentally.

@tnemeth Is this an actual use case that you have? After all, using `bat` without colors is not really all that great of an experience :smile:. If someone really wants to do that, it should be easy enough to add `--color=never` to the config file. Or make sure that `NO_COLOR` is set.

**Comment by tnemeth** [comment]
> I don't believe there's currently any code for using the `TERM` environment variable to turn colors off.

    That should explain :)


> It should be pretty simple to add, but we first need to figure out how it interacts with `--color=always`. 
> Should that option take priority, or should the terminal type take priority, since that's reporting the
> maximum capabilities of the terminal?

    IMHO "hardware" (in this case emulated hardware since that's what are x-terminals) should
    take precedence over what the user wants. For a car a user may want to speed up to Mach 3
    but his car won't be able to ;)


> Also, thanks for letting us know about the problem with the shell script. I'll need to fix that.

sed -is 's/bat --cache-dir/$BAT --cache-dir/' info.sh

**Comment by tnemeth** [comment]
> To clarify for @tnemeth : the `auto` option only turns off colors when the output of `bat` goes to a pipe.  It's not meant to auto-detect the terminals color capabilities.

    Ok. So it was just a misunderstanding on my part.


> @tnemeth Is this an actual use case that you have? After all, using `bat` without colors is not really all that great of an experience smile. If someone really wants to do that, it should be easy enough to add `--color=never` to the config file. Or make sure that `NO_COLOR` is set.

    This is an actual use case (I have several opened terminals using different profiles to differenciate
    their use : some *with* colors some *monochrome* (with different colors). Even though I discovered
    `bat` about 1 year ago, I only put it into use recently (that's why you can see my tickets now ;). Up to
    now I was, as you can guess, using `less`. So to ease the transition, I aliased : `alias less='batcat'`.
    But I can adapt ;)

    Indeed `bat` is less useful in a colorless environment. However its decoration and lines numbering out
    of the box make its useful even in these conditions.

    There is still one last missing feature (due to its use of less underneath) : open the displayed file with
    a $VISUAL or $EDITOR as less can do with the `v` command.

**Comment by rr0ss0rr** [comment]
For your last missing feature, check out [https://github.com/sharkdp/bat/issues/1050]

**Comment by tnemeth** [comment]
> For your last missing feature, check out #1050

Nice ! Thanks.

**Comment by sharkdp** [comment]
Is there something left to do here? An update of the documentation?

**Comment by tnemeth** [comment]
Maybe just what you said previously :

>  the `auto` option only turns off colors when the output of `bat` goes to a pipe. It's not meant to auto-detect the terminals color capabilities.

**Comment by sharkdp** [comment]
> `sed -is 's/bat --cache-dir/$BAT --cache-dir/' info.sh`

fixed.

> Maybe just what you said previously :
> 
> > the `auto` option only turns off colors when the output of `bat` goes to a pipe. It's not meant to auto-detect the terminals color capabilities.

I updated the `--help` text.
