### ISSUE TITLE
Easy toggling of --plain

### ISSUE THREAD

**Issue by rajeshisnepali** [sharkdp/bat#1106]
![image](https://user-images.githubusercontent.com/23610013/87106701-bd3fd880-c27d-11ea-85bc-6727b3531bca.png)

First of all, paging looks great for me. But I've always a situation where I want to copy lines from a file. For now, what I can do is quit and again open a file like `bat -p ~/.zshrc`. But that's not a very good idea. 

What I want is is to toggle this option without re-opening a file. 
Thanks.

**Comment by sharkdp** [comment]
Unfortunately, that's not possible with the current architecture. Please see #1053 for details. It includes this feature request (Disable style components via keypress).
