### ISSUE TITLE
add a decorations alias

### ISSUE THREAD

**Issue by lyndell** [sharkdp/bat#1108]
An alias for `--decorations always` so I can pipe the decorations when doing something like `bat FILE | gview -`.  …but without the `^M`'s.

**Comment by sharkdp** [comment]
Sounds good to me. Which flag would you suggest? You also want colors to be enabled, right? (not just grid, line numbers, changes).

**Comment by lyndell** [comment]
`-d` appears available.  Colors could be a problem in `gview` or `text/plain` MIME type,  though it might be nice for someone dumping to monospace HTML.  Maybe use `-h` or `--html` for an HTML dump with colors.  Grid and line numbers would be fine for a pretty-print `cat` or `head` alternative.  `bat FILE | gview -` is the use-case  time **I** would use.

**Comment by sharkdp** [comment]
>  Colors could be a problem in `gview` or `text/plain` MIME type, though it might be nice for someone dumping to monospace HTML. Maybe use `-h` or `--html` for an HTML dump with colors.

How is this related to the feature in question here? We are not planning to add a HTML output feature to `bat`. Note that there are thing like `ansi2html`.

Maybe I don't yet understand your use case. What do you use `… | giew -` for? Is `bat`s paging option not working for you?

**Comment by lyndell** [comment]
`gview`is an excellent file viewer, especially when I want to break out of the Terminal window.  Concatenating the files with `bat` decorations makes the distinct file and line numbers clear.  One example is viewing Kubernetes with `bat pod.yaml deployment.yaml service.yaml | gview -`.  There are times I'd rather use that in stead of `-o` or -O` on `gview`.  It makes the search and navigation easier.

**Comment by alexanderkarlis** [comment]
I was hoping to give this issue a shot. But I noticed that there already is an alias flag for -d (diff). Would it be a good idea to add it as `-D` instead of `-d`? @sharkdp

**Comment by lyndell** [comment]
Sounds good to me.

**Comment by sharkdp** [comment]
If this enables `--color=always` and `--decorations=always`, we could also use `-c`, as the major thing (for me) would be the colorized output, not the decorations.

**Comment by sharkdp** [comment]
Closed via #1141 by @alexanderkarlis

**Comment by sharkdp** [comment]
Released in [v0.16.0](https://github.com/sharkdp/bat/releases/tag/v0.16.0).
