### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by rajeshisnepali** [sharkdp/bat#1130]
I've added a pager to my command. So is there any option to search any string `case-insensitive`?

**Comment by cedric-sun** [comment]
Then it really depends on your pager. See `-i` and `-I` options in `man 1 less` for `less`. Otherwise you should search the docs of your pager.

**Comment by archongum** [comment]
I think what @rajeshisnepali wanted is more like `less -i`. For exmaple, `cat somefile.txt | less -i`.
`bat` can't do this trick.

**Comment by rajeshisnepali** [comment]
@archongum `bat somefile.txt` and typing `-i` didn't work for me. 

Here's a quick screencast.
https://www.dropbox.com/s/8jqgwbbe9fow84y/bat_case_insensitive_not_working.webm?dl=0

**Comment by archongum** [comment]
> Here's a quick screencast.
> https://www.dropbox.com/s/8jqgwbbe9fow84y/bat_case_insensitive_not_working.webm?dl=0

@rajeshisnepali I think ignore case mode only effected when searching with pure lower case string. If the searching string contains both lower and upper cases, ignore case mode won't work anymore.
These two pictures below are searching in ignore case mode.
![image](https://user-images.githubusercontent.com/20929338/90086429-fd96e880-dd4c-11ea-8278-9355e3831c31.png)
![image](https://user-images.githubusercontent.com/20929338/90086473-11dae580-dd4d-11ea-962a-f7934c52d931.png)

**Comment by sharkdp** [comment]
You can also use the `--pager` option in the config file to always pass `-i` to less (see README for details).

**Comment by rajeshisnepali** [comment]
Oh yes, for `bat 0.15.4` I believe the default pager is set as of `less`.  I've aliased both `cat` & `less` to `bat` to perform accordingly.

**Comment by mxmilkiib** [comment]
I'm just trying this now (on Arch); with `export PAGER="/usr/bin/less -RFI"` then `bat /some/file`, it doesn't work, but if I do `bat --pager "less -RFI" /usr/share/mixxx/controllers/Reloop\ Beatmix\ 2-4.midi.xml` it does work. I'm quite confused by this.

**Comment by sharkdp** [comment]
`PAGER` will be overwritten by `BAT_PAGER` (have you set this?), which will be overwritten by `--pager=…` settings in the config file or the command line.

**Comment by mxmilkiib** [comment]
I don't have a `bat` config nor `BAT_PAGER` set, but setting `BAT_PAGER` resolved this, thanks :)

**Comment by sharkdp** [comment]
> I don't have a `bat` config nor `BAT_PAGER` set, but setting `BAT_PAGER` resolved this, thanks :)

Oh - right. If we detect `less` in `PAGER`, we actually overwrite the command line options (to make sure `-R` is included). So using `BAT_PAGER` or the config file is the only option here.

**Comment by sharkdp** [comment]
It would be great if someone could add this to the README.
