### ISSUE TITLE
How can i make comments cursive on file preview?

### ISSUE THREAD

**Issue by zhorzh** [sharkdp/bat#1139]
In .vimrc i can make comments cursive by setting this:

`highlight Comment cterm=italic gui=italic`

Is there a way to make it looks similar in bat?

**Comment by zhorzh** [comment]
My terminal supports italic, and bat can show italic font, but not the comments.

**Comment by sharkdp** [comment]
That depends on the theme you use (check out `bat --list-themes`) and whether or not you have enabled support for italics (see [README](https://github.com/sharkdp/bat#format))

**Comment by zhorzh** [comment]
I'm using the base16 theme, and italics is enabled. The thing is base16 doesn't make the comments cursive. Is there a way i can modify built-in base16 theme?

**Comment by sharkdp** [comment]
Yes, check out this section: https://github.com/sharkdp/bat#adding-new-themes

**Comment by sharkdp** [comment]
Instead of cloning a new theme, just copy the base16 theme from the bat repo and modify it.

**Comment by sharkdp** [comment]
Closing as there is no further feedback.
