### ISSUE TITLE
Arc repo, AUR repo(?) and Manjaro repository does not contain fish completion file?

### ISSUE THREAD

**Issue by chshbh** [sharkdp/bat#1143]
The output of the info.sh at the bottom if need be.

+ [Arch repo](https://www.archlinux.org/packages/?q=bat) has one [bat](https://www.archlinux.org/packages/community/x86_64/bat/) package and it does not seem to be generating completion.fish file. 
+ [AUR repo](https://aur.archlinux.org/packages/bat-cat-git/) is out of date(feb) and from the look of it, fish shell completion was added in March 20' from [vendor POV](https://github.com/sharkdp/bat/issues/651). 
+ I use manjaro linux and have been using bat for months(without auto-completion). I was looking into fd and found that it automatically generates(?) fish file and move it into `vendor_completions.d/ folder`. 

Content of the vendor completion folder.
```
 Name
alacritty.fish
curl.fish
docker.fish
exa.fish
fd.fish
flatpak.fish
lf.fish
pass.fish
pip.fish
pip2.fish
rg.fish
rustup.fish
yay.fish
youtube-dl.fish
```
I had to copy the completion fish file from [here](https://github.com/sharkdp/bat/releases/download/v0.15.4/bat-v0.15.4-aarch64-unknown-linux-gnu.tar.gz). Is this the normal way? 

info.sh output
```
system
------

**$ uname -srm**
Linux 5.7.9-1-MANJARO x86_64  

**$ lsb_release -a**
LSB Version:	n/a  
Distributor ID:	ManjaroLinux  
Description:	Manjaro Linux  
Release:	20.1  
Codename:	Mikah  

bat
---

**$ bat --version**
bat 0.15.4  

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 551 (PCRE regular expressions)  

```

**Comment by sharkdp** [comment]
Thank you for reporting this, but I think this needs to be fixed in the Arch package, which is not maintained here. 

It's probably best to file a report here: https://www.archlinux.org/packages/community/x86_64/bat/

**Comment by chshbh** [comment]
I will try to report it there, if possible. But as I said, even the official Manjaro repository has the same problem with the packaging. I will leave the issue open, just in case.

**Comment by sharkdp** [comment]
Ok, please report this in the Arch issue tracker. Nothing is going to happen here in this repo. Thank you.
