### ISSUE TITLE
Style=snip vs style=plain

### ISSUE THREAD

**Issue by patrickf3139** [sharkdp/bat#1146]
Hi, thanks for making and maintaining bat! I've been playing around with the style options and can't figure out what the difference between snip and plain is. Could you explain the difference, please?

**Comment by eth-p** [comment]
The `snip` style is a component (like `numbers` or `grid`) that shows up between the text printed for each printed `--line-range`. It was added to help break up the line ranges and make it more clear that you're looking at noncontiguous output.

The `plain` style is just every component being turned off.

**Comment by patrickf3139** [comment]
Thanks so much Ethan! That's very helpful. I will definitely be turning on snip when I use ranges.
Btw, it took me a long time to figure out which each style option did and I couldn't find any documentation around it. I'd recommend explaining them in the readme. Just a thought. Thanks again!

**Comment by xeruf** [comment]
So apparently this is part of `--help` but not of the man page now :/
