### ISSUE TITLE
Auto-generate shell-completion files via clap

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#115]
Completion files for bash, zsh, fish and PowerShell can be auto-generated via `clap` (see related changes in `fd`: https://github.com/sharkdp/fd/pull/66/files, https://github.com/sharkdp/fd/blob/master/build.rs)

**Comment by davideGiovannini** [comment]
Hi @sharkdp, if this issue is still open I would like to work on it

**Comment by sharkdp** [comment]
@davideGiovannini sounds great!

**Comment by sharkdp** [comment]
Closed via #327
