### ISSUE TITLE
Support pager 'less -SN'

### ISSUE THREAD

**Issue by alienzj** [sharkdp/bat#1150]
When I run:
```bat --pager "less -SN" test_profile.tsv```

I got:
![image](https://user-images.githubusercontent.com/8847420/90976099-dcb06d80-e56c-11ea-82f0-4e4cdb8c3ed3.png)

Does `bat` currently not support pager `less -SN`?

Thanks~

**Comment by sharkdp** [comment]
`bat` already wraps long lines. If you really want `less`s "chop long lines" feature, use
```
bat --pager="less -SR" --wrap=never …
```

**Comment by alienzj** [comment]
Yes, it work. Thanks~
