### ISSUE TITLE
Reverse order and compressed files

### ISSUE THREAD

**Issue by gsmitheidw** [sharkdp/bat#1151]
For viewing log files, it would be nice to have an option to reverse the order of of the lines (ie: newest lines at the bottom) to be able to reverse browse/search a file. This would be effectively "tab" as cat is to tac. 

Secondly (again handy with log files), it would be useful to transparently open compressed files and non-compressed on a wildcard such as: bat syslog*

**Comment by ssokolow** [comment]
Generally, it's better to file two feature requests for this, so they can be tracked and closed separately, but I'll agree with the compressed file support.

**Comment by sharkdp** [comment]
Thank you for the feedback.

> For viewing log files, it would be nice to have an option to reverse the order of of the lines (ie: newest lines at the bottom) to be able to reverse browse/search a file. This would be effectively "tab" as cat is to tac.

You can `tac` into `bat`:
```
tac logfile | bat
tac logfile | bat -l log
```

> Secondly (again handy with log files), it would be useful to transparently open compressed files and non-compressed on a wildcard such as: bat syslog*

This has been requested a few times, please search the issue tracker.

**Comment by sharkdp** [comment]
Closing as there is no further feedback.
