### ISSUE TITLE
Are the licenses conjunctive or disjunctive?

### ISSUE THREAD

**Issue by apotheon** [sharkdp/bat#1154]
The licensing situation seems unclear.  Is this a typical (disjunctive) dual-license situation, where the recipient gets to choose under which license to accept the software, presumably to offer the simplicity of the MIT License for those who want it while also including the patent litigation protection of the Apache License 2.0?  Is it instead an atypical (conjunctive) situation where any recipients must abide by the restrictions of *both* licenses for some reason (I'm guessing because some code is non-relicensable AL2 code in such a case)?

Please clarify, not just here but in the README and/or the License files.

**Comment by sharkdp** [comment]
>  Is this a typical (disjunctive) dual-license situation, where the recipient gets to choose under which license to accept the software

yes.

> Please clarify, not just here but in the README and/or the License files.

Yes, this should be clarified. Maybe with something as simple as what we did for `hexyl`: https://github.com/sharkdp/hexyl/#license

**Comment by apotheon** [comment]
The hexyl README approach would indeed improve the situation, as it really clarifies the relationship of the licenses upon examining the README.

**Comment by apotheon** [comment]
I created [pull request #1155](https://github.com/sharkdp/bat/pull/1155) as a low-hanging-fruit means of addressing this, based on your response, in case you want to take that approach.

**Comment by apotheon** [comment]
Based on this discussion, bat has been added to a list of copyfree works.

http://copyfree.org/resources/works#bat

Please let me know if there are any inaccuracies to be corrected or
improvements to be made in the listing.
