### ISSUE TITLE
Use bat to view directory

### ISSUE THREAD

**Issue by KSXGitHub** [sharkdp/bat#1156]
## Problem

When using terminal, I have a habit of pressing <kdb>UP</kbd> arrow and edit the previous command.

Currently, I have to use 2 different commands to view directory and file. It is very cumbersome when I have to change "ls" part of the previous command to "bat" to view a file.

So I think that it would be very helpful if `bat` can just display content of a directory.

## Suggestion

Add a flag called `--dir-viewer` that takes a command. For example:

```sh
bat --dir-viewer='ls -A --color=always' file1 file2 dir1 dir2 file3 dir3
```

The above command would:
1. Display content of `file1`.
2. Display content of `file2`.
3. Execute `ls -A --color=always dir1` and display output that fits within decoration frame as if it was content of a file.
4. Execute `ls -A --color=always dir2` and display output that fits within decoration frame as if it was content of a file.
5. Display content of `file3`.
6. Execute `ls -A --color=always dir3` and display output that fits within decoration frame as if it was content of a file.

**Comment by eggbean** [comment]
You could write a bash function if you really want this unusual behaviour.

**Comment by KSXGitHub** [comment]
@eggbean `bat`'s output has decoration.

**Comment by sharkdp** [comment]
@KSXGitHub Thank you for your feedback, but this is probably not going to happen. As @eggbean suggest, I think this would be a good fit for a wrapper script / shell function.

**Comment by superpupervlad** [comment]
If someone want ready-to-use bash script please check [this issue](https://github.com/sharkdp/bat/issues/971#issuecomment-626128861).
