### ISSUE TITLE
Can vim syntax highlighting files be ported over to bat?

### ISSUE THREAD

**Issue by davisRoman** [sharkdp/bat#1157]
Hello,

I work with build systems, specifically the yocto project, and they use metadata files called bitbake recipes that have '.bb' extensions. There is a .bb specific syntax highlighting file available for [vim](https://github.com/kergoth/vim-bitbake/blob/master/syntax/bitbake.vim) but it would be really great if I could somehow bring this over to bat.

I'm interested in using bat as the preview program for [fzf](https://github.com/junegunn/fzf) but I'm missing those nice colors that I currently only have in vim.

Any ideas would be greatly appreciated.

Thank you,

Davis

**Comment by eth-p** [comment]
I don't believe there are any tools that can convert the syntax highlighting from vim to Sublime (what bat uses) automatically, but it's certainly possible to do it by hand.

As long as you understand regex, it's not too difficult to create a custom syntax. For a starting point, we have some of our own relatively simple syntaxes (e.g. fstab) in this repo that you can look at.

**Comment by sharkdp** [comment]
@davisRoman Have you tried this already? https://github.com/Driim/bitbake-syntax

**Comment by sharkdp** [comment]
Closing as there is no further feedback.
