### ISSUE TITLE
Mention how to add themes in terminal help

### ISSUE THREAD

**Issue by ssokolow** [sharkdp/bat#1162]
I tried bat about a year ago and I remember checking the available themes, seeing no evidence that they could be changed without making a custom build, and giving up on using it because, with my urxvt setup, every theme was either too intense, too pale, or, in the case of `ansi-dark` and `base16`, they didn't have the tweak to dark blue that I'd applied to other things to make it more readable.

(I can't just change the terminal's definition of dark blue because that throws off the contrast ratio for things which want to use it as a background.)

A brief mention of where to find more information on adding custom themes in either `--help` or `--list-themes` (or at least a mention that it *can* be done) would have prevented me from assuming that bat was unfit for my needs.

**Comment by eth-p** [comment]
I just looked through the manpage as well, and I think it could also benefit from a dedicated section about customizing themes and syntaxes.

**Comment by sharkdp** [comment]
Agreed - thank you for the feedback. Any help would be greatly appreciated.

**Comment by sharkdp** [comment]
closed via #1207

**Comment by sharkdp** [comment]
> A brief mention of where to find more information on adding custom themes in either `--help` or `--list-themes` (or at least a mention that it _can_ be done) would have prevented me from assuming that bat was unfit for my needs.

Reopening because it would be great if we could add this.
