### ISSUE TITLE
Use bat as input processor to less

### ISSUE THREAD

**Issue by knutwannheden** [sharkdp/bat#1175]
I am used to working with `less` and have in the past often used it in combination with ripgrep and `xargs` (as in e.g. `rg 'blah' -g '*.foo' -l | xargs less`). I was quite thrilled to discover `bat` 🎉 and now often use it for paging instead of directly using `less`.

One feature I am missing when paging multiple files using `bat` and `less` as the pager (e.g. `bat a b c`) is the fact that I can no longer use the `less` commands to change to the next and previous files (i.e. using `:n` and `:p` respectively). And, of course, when I go back to using `less` I don't have the syntax highlighting provided by `bat`.

I am not sure if what I am asking for is possible, but I was wondering if `bat` could have an option which would allow it to be used as an input processor to `less` (i.e. using `LESSOPEN`) to achieve this.

**Comment by sersorrel** [comment]
fwiw, I have this working with this at `~/.lessfilter`:

```sh
#!/bin/sh

if command -v bat >/dev/null 2>&1; then
        # we don't just do this because then the other lessfilters never have a chance to run
        # bat --paging never --color always --style plain "$1"
        # exit 0
        for ext in $(bat -L | cut -d: -f2 | tr ',' ' '); do
                trimmed="${1%$ext}"
                # If the file *has an extension* and that extension matches, or if the *entire* filename matches, highlight it.
                # This avoids cases where the filename ends with "d", but not with ".d", for instance.
                if [ "$trimmed" = "${1%.*}." ] || [ "$trimmed" = "" ]; then
                        bat --paging never --color always --style plain --language "$ext" <"$1"
                        exit 0
                fi
        done
fi

exit 1
```

The only issue I commonly run into is that it won't use bat for files without an extension – ofc you can just unconditionally run all files through bat, like the comment points out, but that breaks all other filters (like the one that shows the contents of zips).

**Comment by knutwannheden** [comment]
Interesting. Using `export LESSOPEN="|~/.lessfilter %s"` I can then again use `less` to page files (instead of through `bat`) and get the syntax highlighting.

**Comment by sharkdp** [comment]
Not sure if there is anything left to do here, so I'm closing this for now.
