### ISSUE TITLE
Add -t, --title <title> for manual setting of input filename

### ISSUE THREAD

**Issue by paxsali** [sharkdp/bat#1176]
Hi all,

for scripting and other stuff it would be nice if bat could display a _custom chosen_ title, instead of a generic "**STDIN**".

e.g.:
`$ env | bat`

Shows **STDIN** in title line. Obviously, since it reads from stdin, it cannot know what it is that you're looking at.
That's fine of course.

_However_, it would be cool & easy to implement (don't look at me, I don't know Rust, ... yet), if you could do this:

`$ env | bat --title "Environment variables"`

With bat displaying "**Environment variables**" now in it's title line.

Obviously with such option, the possibilities are endless. I just gave one example from the top of my head.

I checked the man page. Neither "-t" nor "--title" exist yet, so there is no conflict with other options at the moment.

Feel free to comment.

Thank you.

**Comment by mouse07410** [comment]
I think it's a good idea.

**Comment by sharkdp** [comment]
Have you seen the `--file-name <name>…` option?
```
        --file-name <name>...
            Specify the name to display for a file. Useful when piping
            data to bat from STDIN when bat does not otherwise know the
            filename.
```

It prints "File: …" in addition. But apart from that it seems to do what you want.

**Comment by paxsali** [comment]
> Have you seen the `--file-name <name>…` option?
> 
> ```
>         --file-name <name>...
>             Specify the name to display for a file. Useful when piping
>             data to bat from STDIN when bat does not otherwise know the
>             filename.
> ```
> 
> It prints "File: …" in addition. But apart from that it seems to do what you want.

Sorry about that. No, I haven't seen this, obviously.

I'm running on Ubuntu 20.04 and it's batcat version is this:

```
$ batcat --version
bat 0.12.1
```

This version has no ```--file-name <name>```. So if it's already there, then obviously we can close the request.

Thanks for pointing out.

**Comment by shilch** [comment]
The `--file-name` option is missing on the manual pages.

**Comment by eth-p** [comment]
> The `--file-name` option is missing on the manual pages.

Thanks for the heads up! If nobody else tackles this by the time I'm done with finals, I'll make sure to fix that.

**Comment by keith-hall** [comment]
If someone can spare a minute to walk me through how the manpage is generated (or link to some tutorial) , I would be willing to give it a go.

**Comment by shilch** [comment]
@keith-hall The manpage is generated from a template file: https://github.com/sharkdp/bat/blob/master/assets/manual/bat.1.in  

Seeing that the output of `--help` and `man bat` is almost the same, but both are separate sources that both have to be maintained, maybe it makes sense to generate the manpage from the `--help` completely or at least have a pipeline that checks for inconsistencies between the two?

**Comment by keith-hall** [comment]
If I understand correctly, I can use `groff` to convert from the `in` file to the formatted manpage for testing https://linux.die.net/man/7/man

**Comment by keith-hall** [comment]
> Seeing that the output of `--help` and `man bat` is almost the same

I was always under the impression that the man page should be more comprehensive than the help, so maybe we should work on expanding that rather than unifying them, what do others think? Otherwise, I agree it makes sense to keep them in sync.

**Comment by sharkdp** [comment]
> If I understand correctly, I can use `groff` to convert from the `in` file to the formatted manpage for testing https://linux.die.net/man/7/man

I typically use `man -l <file>`, which works fine on Linux.

> > Seeing that the output of `--help` and `man bat` is almost the same
> 
> I was always under the impression that the man page should be more comprehensive than the help, so maybe we should work on expanding that rather than unifying them, what do others think? Otherwise, I agree it makes sense to keep them in sync.

Ideally yes. In my point of view, the ideal situation looks like this:

* `cmd -h` only shows a concise overview of the most-often used command-line options.
* `cmd --help` shows all command-line options (except for those that are explicitly hidden, like deprecated aliases etc.) with very detailed information for each of them.
* The man page includes everything from `cmd --help` and extends the documenation beyond that with examples, explanations and sections on things like config files, etc.
* The repository README includes everything from the man page and extends beyond that with instructions on how to install `bat`, how to contribute, etc.

For the description of the command-line options, I'd actually want all of the details to be present in `cmd --help` as well. Even if they are examples. An example from my `hyperfine` program:
```
    -P, --parameter-scan <VAR> <MIN> <MAX>
            Perform benchmark runs for each value in the range MIN..MAX.
            Replaces the string '{VAR}' in each command by the current
            parameter value.
            
              Example:  hyperfine -P threads 1 8 'make -j {threads}'
            
            This performs benchmarks for 'make -j 1', 'make -j 2', …, 'make -j 8'.
```

The problem is always how to keep all of this in sync. For another project of mine (https://github.com/sharkdp/insect), I'm actually generating the man page and the README from a set of markdown files with `pandoc` (https://github.com/sharkdp/insect/blob/master/docs/generate.sh).

For `bat`, we haven't really spent much time to clean everything up. The project has simply grown too fast. This is something I'd like to work on (see #1211).

Ideas on how to improve the situation are welcome! Also, I'd like to hear other viewpoints on how the documentation should be structured.

**Comment by keith-hall** [comment]
> The problem is always how to keep all of this in sync. For another project of mine ([sharkdp/insect](https://github.com/sharkdp/insect)), I'm actually generating the man page and the README from a set of markdown files with `pandoc` ([https://github.com/sharkdp/insect/blob/master/docs/generate.sh](https://github.com/sharkdp/insect/blob/master/docs/generate.sh?rgh-link-date=2020-12-13T12%3A12%3A53Z)).

FWIW, I like that approach, it seems quite clean from a glance. How do you feel using this in practice? Any pain points with it? :)


> Another option is to autogenerate (part of) the man page from the `--help` text via `clap`. Unfortunately, this feature has not yet been implemented (but will be part of clap 3, I believe).

I would say that a reasonable option would be to wait until that feature has been implemented, and deal with the manual work of keeping the man page in sync with the readme and help for now.

**Comment by sharkdp** [comment]
> > The problem is always how to keep all of this in sync. For another project of mine ([sharkdp/insect](https://github.com/sharkdp/insect)), I'm actually generating the man page and the README from a set of markdown files with `pandoc` ([https://github.com/sharkdp/insect/blob/master/docs/generate.sh](https://github.com/sharkdp/insect/blob/master/docs/generate.sh?rgh-link-date=2020-12-13T12%3A12%3A53Z)).
> 
> FWIW, I like that approach, it seems quite clean from a glance. How do you feel using this in practice? Any pain points with it? :)

Everyone (including myself) forgets about the fact that `README.md` is autogenerated (even though there is a large `<!-- … -->` banner on top of it) and makes changes to it without updating the sources.

And you have to teach every contributor on how to run the update process (unless that could be done as a GitHub Action).

> > Another option is to autogenerate (part of) the man page from the `--help` text via `clap`. Unfortunately, this feature has not yet been implemented (but will be part of clap 3, I believe).
> 
> I would say that a reasonable option would be to wait until that feature has been implemented, and deal with the manual work of keeping the man page in sync with the readme and help for now.

Yes, I think that's the best approach.
