### ISSUE TITLE
Match of line numbers outputed by bat when doing text search on pager

### ISSUE THREAD

**Issue by Kienyew** [sharkdp/bat#1183]
![image](https://user-images.githubusercontent.com/31496021/92384348-7fa6e100-f142-11ea-97e7-0b17ba464e2c.png)

The image above showing a running `bat` that piped his output to pager `less`, which I was search for the occurence of text `10` in a long file. As we can see, it's matching all the `10..` from line `1000` to `1099` beside  from the content of file itself and user might get frustrated while scrolling down 🙁. I doubt we can do anything on it if still want the line numbers from `bat`.

**Comment by sharkdp** [comment]
That is unfortunate, yes. I'm not sure if there is anyway around this. It could be solved via #1053 though.

As a hack, you could search for matches on the right side of the side-bar separation character by using something like `│.*10`. I know, it's not pretty.

**Comment by sharkdp** [comment]
I'm closing this for now. Please feel free to comment in case it should be re-opened.
