### ISSUE TITLE
Add a more terminal-friendly command layout

### ISSUE THREAD

**Issue by stdedos** [sharkdp/bat#1187]
I have been trying to use bat as a drop-in replacement to cat, and routinely I fall into various small problems.
Today, I want to talk about line numbers.

Sometimes I want, while seeing a file, to copy a portion of it.
At the same time, I find line numbers useful.

The above give me an impass:
- Copying part of a file to some other place, with the leading line numbers is usually not okay (except if I copy to an intermediate Sublime /w multicursors)
- Temporarily having no line numbers is not "that straightforward":
	- I don't remember the flag for it
 	- no tab-completion for bash
	- Will either incur a re-execution, or
	- using `less`' line numbers will add a +3 offset (separator, filename, separator)
	- bat cannot, by itself, on-demand add/remove numbers during interaction (as usually it's job is most likely already done before I see anything)

With all the aforementioned, I propose a new layout theme, that starts with the file, and leads with whatever else (separator, filename, separator). With that, using `less`' `-N` becomes a trivial solution to this issue.

Or implement `less` in `bat` 😜

**Comment by sharkdp** [comment]
Thank you  for the detailed feedback.

> Sometimes I want, while seeing a file, to copy a portion of it.
> At the same time, I find line numbers useful.

That hat been discussed multiple times. See e.g. #549, #296, #467, #1177, #939

> With all the aforementioned, I propose a new layout theme, that starts with the file, and leads with whatever else (separator, filename, separator).

I don't understand?

> Or implement `less` in `bat` :stuck_out_tongue_winking_eye:

See #1053

**Comment by stdedos** [comment]
> > Sometimes I want, while seeing a file, to copy a portion of it.
> > At the same time, I find line numbers useful.
> 
> That hat been discussed multiple times. See e.g. #549, #296, #467, #1177, #939

Oh, I missed the "toggle" keyword 😕 

> > With all the aforementioned, I propose a new layout theme, that starts with the file, and leads with whatever else (separator, filename, separator).
> 
> I don't understand?

Basically the reverse of this, without the sidebar
![img](https://camo.githubusercontent.com/9d3d89364f2cc83ace8f29646a6236bc15ea1da0/68747470733a2f2f696d6775722e636f6d2f724773646e44652e706e67)
```md
# Markdown example

...

----
File:
----
```

(I'm sorry I don't have access to a textual bat output right now)

It looks weird, prohibits git-markers, but it would be a minimal solution to this (not considering the already-mentioned tickets ofc)

**Comment by sharkdp** [comment]
You can already do this by adding
```
--style=header,grid,snip
```
to your config file.

**Comment by stdedos** [comment]
I meant:

```
bat$ (master u=) bat examples/cat.rs 
/// A very simple colorized `cat` clone, using `bat` as a library.
/// See `src/bin/bat` for the full `bat` application.
use bat::PrettyPrinter;

fn main() {
    PrettyPrinter::new()
        .header(true)
        .grid(true)
        .line_numbers(true)
        .input_files(std::env::args_os().skip(1))
        .print()
        .unwrap();
}
────────────────────────────────────────────────────────────────────
 File: examples/cat.rs
────────────────────────────────────────────────────────────────────
bat$ (master u=)
```

which `less -N` can number accurately

**Comment by sharkdp** [comment]
If it's going to work for a single file only, why not leave out the header part completely?

**Comment by stdedos** [comment]
True dat. I didn't think of it.

**Comment by sharkdp** [comment]
I take this to mean that this can be closed?

**Comment by stdedos** [comment]
Well, I don't know what would help more, given that bundled pager is already in planning and since my idea of header-becoming-footer is not getting traction... 

I am now using the new configuration, and I feel that "the bat I know" is no longer there. 
Maybe I need to add a bat alias with the default configuration, and let non-aliased innovations take the "only coloring" execution path.

**Comment by sharkdp** [comment]
Hm. I'm not really sure how we could help with that?
