### ISSUE TITLE
No highlight for Weechat ".conf" files 

### ISSUE THREAD

**Issue by Bumbadawg** [sharkdp/bat#1189]
Hi,
Is it normal that i have to force INI language for .conf files ?

**Comment by sharkdp** [comment]
I don't think every possible `.conf` file will have INI syntax, so I don't think we should add a mapping like this. If you want, you can add
```
--map-syntax '*.conf:INI'
```
to the bat config file, and it should work.

**Comment by Bumbadawg** [comment]
Thanks that's perfect.

**Comment by sharkdp** [comment]
I think this would be a great example for the README page (in a new section that explains `--map-syntax`), if someone wants to add this.

**Comment by henil** [comment]
@sharkdp I can do that. Is it still pending?

**Comment by sharkdp** [comment]
@henil yes :+1:

**Comment by sharkdp** [comment]
Closing via #1212 by @henil.
