### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by jraulhernandezi** [sharkdp/bat#119]
Would you like a logo and a nice banner to go along with it for your project?

Maybe a bat with some coding elements, I can make a draft for today if you want. 

Cheers.

**Comment by sharkdp** [comment]
Thank you for your message!

I am not actively looking for a logo but I have to say I am curious :smile:!

**Comment by jraulhernandezi** [comment]
![sin titulo-1](https://user-images.githubusercontent.com/35578070/40199227-cf484d3e-59e6-11e8-92af-d3bb76ae5d83.jpg)
Here is an idea, as you can see I tried to combine a bat shape using "<>" characters. 

Let me know what do you think, are you interested in some banner ideas with this logo?

**Comment by jraulhernandezi** [comment]
![bat pr](https://user-images.githubusercontent.com/35578070/40263007-c5d6a3be-5ada-11e8-987e-fae185519121.jpg)
Here the final logo vectorized, what do you think about the height?
Let me know if I can make a pull request with this one, or if you need any modification.

**Comment by sharkdp** [comment]
The height looks good, thank you!

I believe the font weight could be a little higher, but apart from that, it looks great. A PR would be great.

**Comment by sharkdp** [comment]
The logo is now live, thank you very much @jraulhernandezi!
