### ISSUE TITLE
Feature Request: svelte syntax highlighting support

### ISSUE THREAD

**Issue by daxxog** [sharkdp/bat#1194]
Having out of the box syntax highlighting support for `.svelte` files in `bat` would be great.

https://svelte.dev/

Should be pretty easy to implement as the syntax highlighting would be very similar to HTML/CSS/JS

**Comment by sharkdp** [comment]
Thank you for your request.

Can you please re-open this with the "syntax request" template?

FYI: https://packagecontrol.io/packages/Svelte

**Comment by sharkdp** [comment]
Also, please read: https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions
