### ISSUE TITLE
Q/FR: Display Configuration-related Help Options?

### ISSUE THREAD

**Issue by danieldjewell** [sharkdp/bat#1198]
Hiya!

Before I fired off a PR from nowhere, I was wondering what the thought would be on turning on the help for configuration options related to configuration files? (see below)

Note: As I wrote this, it morphed into a bit larger of a thing than I originally thought:

1. Help Text for Config-related Options
2. Document env variables somewhere accessible at runtime
3. [the bigger issue] Consider comprehensive documentation (e.g. man page)

## 1. Help Text for Config-related Options
The major rationale for this is that I actually had to open ```clap_app.rs``` to figure out the config paths, etc. (I had kinda guessed that it would be in ```$XDG_CONFIG_DIR => ~/.config/``` but wasn't sure if ```bat``` created a directory, or a file, etc. ) Further, there are several references in the help text to the "configuration file" without any further information on where it is. 

https://github.com/sharkdp/bat/blob/e4df5643dc86ae5c2d2f89bcd9c7359a761f92e3/src/bin/bat/clap_app.rs#L442-L474

## 2. Document env variables somewhere accessible at runtime

Also, I can't find any info in the help regarding ```BAT_CONFIG_PATH``` -- it's in the readme (but the README isn't necessarily available quickly if you just have the ```bat``` binary... which kinda leads to # 3) 

https://github.com/sharkdp/bat/blob/e4df5643dc86ae5c2d2f89bcd9c7359a761f92e3/src/bin/bat/config.rs#L10

## 3. [the bigger issue] Consider comprehensive documentation (e.g. man page)
```bat``` is a great tool - I use it a lot. I generally don't use a GUI - so having good terminal apps is a must for me. I use bat on x86_64/Linux, aarch64/Android-Termux... (and I even cross compiled it for mips/Linux so I could use it on mips Linux routers :grin:) The one major thing missing from ```bat``` is a man page - I think that for utilities like ```bat``` man pages are hands-down a *must* (After all, ```cat``` is in GNU ```coreutils``` or is an OS-included program if you're running *BSD/*NIX.)

That said, to my dismay, the rust community seems at a semi?-impasse on implementing some way for ```cargo``` to install man pages: see https://github.com/rust-lang/cargo/issues/2729 - some other projects (referenced in that cargo issue) have, in the interim, used alternate methods: https://github.com/softdevteam/snare/pull/35 ... (I suppose one other way would be to actually put the installation of the man page into the source of rust programs themselves and use an option like ```--write-man``` to write the file ... not ideal but....)

Creating the actual man source would be relatively straightforward -- could use the output of ```bat --help``` as a start. 

Thoughts on a direction? I don't want to randomly start something and it not be the way you/you all (--the plural you--- euch) want to go. (Wie die Deutschen sagen:  Gut geplant ist halb gewonnen!)

I know this got a little long but it sort of became a deeper thing as I dug into it more...

PS: Vielen vielen dank, dass Sie https://www.github.com/sharkdp/insect geschrieben haben. (Ich muss herausfinden, ob man ```insect``` (u. Purescript) auf aarch64/Termux-Android ausführen kann oder nicht ... Purescript/Haskell sind ... problematisch ... bei aarch64/android.  :grin:)

**Comment by eth-p** [comment]
We actually already have a manpage for bat :)

https://www.github.com/sharkdp/bat/tree/master/assets%2Fmanual%2Fbat.1.in

I'm not entirely sure if cargo has any process for installing extra assets via `cargo install`, but I know that a lot of the distro packages come bundled with it at least.

**Comment by sharkdp** [comment]
> `bat` is a great tool - I use it a lot. I generally don't use a GUI - so having good terminal apps is a must for me. I use bat on x86_64/Linux, aarch64/Android-Termux... (and I even cross compiled it for mips/Linux so I could use it on mips Linux routers grin)

Thank you for the feedback!

> That said, to my dismay, the rust community seems at a semi?-impasse on implementing some way for `cargo` to install man pages: see [rust-lang/cargo#2729](https://github.com/rust-lang/cargo/issues/2729) - some other projects (referenced in that cargo issue) have, in the interim, used alternate methods: [softdevteam/snare#35](https://github.com/softdevteam/snare/pull/35) ... (I suppose one other way would be to actually put the installation of the man page into the source of rust programs themselves and use an option like `--write-man` to write the file ... not ideal but....)

Yes, that's a problem. The `bat` man page is actually created at `cargo build` time. So it should be available in the `target` folder if you build it yourself. If you want proper installation (also for things like shell completions), please use one of the distribution installation options, as mentioned by @eth-p. I have added a comment to the README.

I'm going to close this as we have addressed all points (I believe). Otherwise, I'm happy to re-open if there is something left to do.
