### ISSUE TITLE
Add more Git features

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#12]
Just a few ideas:

* ~Add a `--staged` option to show staged changes.~ => this would require us to read the file from the Git index.
* Add a `--context N` option to only show the lines associated with changes
* (Add a way to specify a git commit/tag/branch to show the file contents from the git index.)

**Comment by jasonleonhard** [comment]
I've been looking around for a `bat --staged` option and this is the first spot I see it crossed out which is a little sad bc this project is very cool and `--staged` is a very important flag for `git`. 

I've even been looking in other projects like bat-extras hoping this feature is somewhere:
https://github.com/eth-p/bat-extras/issues/91

Any chance I'm missing something and can be directed towards how to use something like `bat --diff --staged`?

**Comment by jasonleonhard** [comment]
I did see the progress on `batdiff` https://github.com/sharkdp/bat/pull/940
which again was cool but unless I'm missing something does not support `--staged`.

**Comment by eth-p** [comment]
> I did see the progress on `batdiff` https://github.com/sharkdp/bat/pull/940
> which again was cool but unless I'm missing something does not support `--staged`. 

With `batdiff` specifically, yeah, it doesn't support `--staged`. I haven't had the chance to work on that yet, but you could probably use a shell alias in the meantime? `git diff --staged | bat -ldiff`.

Alternatively, I highly recommend [delta](https://github.com/dandavison/delta) for git or diff-related pretty printing. It uses a fork of `bat` under the hood, so it'll respect your chosen theme too.
