### ISSUE TITLE
Help out in upstream projects (our dependencies)

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#1216]
*With all the recent news about Hacktoberfest I thought it would be a good idea to point out good beginner issues that would be actually helpful for `bat`. In the past years, I have actually experienced Hacktoberfest as a really great event - both as a contributor as well as a maintainer.*

`bat` relies on *huge* number of other projects: we have approximately 170 Rust `crates` that we depend on (directly or indirectly), and we include approximately 65 submodules with syntaxes and themes.

Naturally, some of the reported bugs on our issue tracker are actually bugs in one of these upstream components:

[List of issues labeled with `upstream-error`](https://github.com/sharkdp/bat/issues?q=is%3Aopen+is%3Aissue+label%3Aupstream-error).

It seems like Hacktoberfest would be a great motivation to give something back to the projects we rely on. This could be a bugfix for one of the things listed above, but could also be a regular contribution to one of these projects. In terms of importance for `bat`, the following projects would probably be the most prominent ones:
- [`syntect`](https://github.com/trishume/syntect) - syntax highlighting (Rust)
- [`sublimehq/Packages`](https://github.com/sublimehq/Packages/) - Sublime Text syntaxes (config)
- [`less`](https://github.com/gwsw/less) - pager (C)
- [`oniguruma`](https://github.com/kkos/oniguruma) - regular expression library (C)
- [`clap`](https://github.com/clap-rs/clap) - command line argument handling (Rust)
- [`assert_cmd`](https://github.com/assert-rs/assert_cmd) - command-line integration testing (Rust)
- [`ansi_term`](https://github.com/ogham/rust-ansi-term) - ANSI handling (Rust)
- [`console`](https://github.com/mitsuhiko/console) - Terminal handling (Rust)

**Comment by dancek** [comment]
Unfortunately none of the mentioned repositories have topic:hacktoberfest so PRs to them are ineligible.

**Comment by sharkdp** [comment]
> Unfortunately none of the mentioned repositories have topic:hacktoberfest so PRs to them are ineligible.

True, but I can offer to accept the corresponding PRs on this repository that update the respective dependency. If the upstream patches have not been merged yet, we can open "reminder" PRs here, that we can "hacktoberfest-accept". I think that would be fair for everyone.

**Comment by pksunkara** [comment]
I wanted to open a separate issue (maybe still can) but feels like this a good one to discuss.

I think the whole community would benefit if you can extract out the syntax highlighting data and maintain it separately (maybe a git submodule?). I haven't see anyone else in the rust ecosystem do it as good as you and they all have issues like [this](https://github.com/trishume/syntect/issues/176#issuecomment-683404425). Let's try to reduce duplication work and keep the efforts in one place.

Also, I have another thing I wanted to ask, do you want me to create an issue for it? I already mentioned it once before somewhere.

> You can reduce the dependency list by removing `ansi_term` and `ansi_colours` since `console` has the capability (and more since it handles old windows too).

**Comment by keith-hall** [comment]
> I think the whole community would benefit if you can extract out the syntax highlighting data and maintain it separately (maybe a git submodule?).

There is an issue/discussion for that here:
https://github.com/sharkdp/bat/issues/919

**Comment by keith-hall** [comment]
Wrong button, sorry about that!

**Comment by pksunkara** [comment]
Thanks for pointing. What about the second comment? Should I create an issue for it?

**Comment by sharkdp** [comment]
> What about the second comment? Should I create an issue for it?

Yes, please. Thank you.

**Comment by sharkdp** [comment]
I think this can be closed for now. We can open a new initiative like this next October.
