### ISSUE TITLE
[Meta] Hacktoberfest 2020 Changes

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#1239]
This isn't an issue with bat, but I wanted to mention that yesterday DigitalOcean changed how Hacktoberfest is being handled. I wasn't aware of that until today, I'm bringing it up just in case you weren't either.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**To summarize the update:**

What it means for us @sharkdp, is that we either need to label pull requests as `hacktoberfest-accepted`, approve the pull request, or merge it. With smaller pull requests that get accepted and merged quickly we shouldn't have much of an issue, but the larger ones that require extensive reviews are probably going to need to be labelled.

**Comment by sharkdp** [comment]
Thanks! I was aware of it (I already added the 'hacktoberfest' label to the repo), but good point regarding the `hacktoberfest-accepted` label for long-running PRs. Let's start adding this label to PRs which we think should be accepted (for Hacktoberfest) but are going to take a while to review/merge :+1:. I think we can also add the label to PRs which are *not* going to be merged but aren't spam or tiny changes either...
