### ISSUE TITLE
Wrapping causes problems with ANSI codes

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#124]
The current implementation of character-level wrapping counts incoming characters and adds a new line if the length exceeds the terminal width.

This causes problems if the incoming data stream contains ANSI characters, for example:

![image](https://user-images.githubusercontent.com/4209276/40142852-22055b9e-595a-11e8-9b99-a610ffedc581.png)

There are several problems:
* The lines are wrapped early due to the hidden ANSI chararacters
* Some line-wraps occur in ANSI codes, causing artifacts like `8;2;255;255;255m]` to be displayed.

@eth-p: I am mentioning you just for your information.

**Comment by eth-p** [comment]
@sharkdp Good catch, I never considered that. I can think of two ways to fix this:

1. Strip the ANSI codes with `console::strip_ansi_codes`.
2. Attempt to parse the ANSI codes, making sure to not add them as part of the width counter.

**Comment by sharkdp** [comment]
I would definitely like to support incoming ANSI codes, just like `cat` or `less`. This will be useful if people try to `alias cat=bat` or use `bat` as a general-purpose pager, etc. - so stripping ANSI codes is not really an option for me.

Also, I would really like to avoid having to implement a ANSI-code parser within `bat`. The `console` trait seems to have a few useful functions, for example: [measure_text_width](https://docs.rs/console/0.6.1/console/fn.measure_text_width.html). Maybe we could utilize those... but I'm not sure if this is enough.

**Comment by sharkdp** [comment]
There is also [`truncate_str`](https://docs.rs/console/0.6.1/console/fn.truncate_str.html), which seems really helpful!

**Comment by eth-p** [comment]
Unfortunately, truncate_str doesn't allow me to get the truncated text. The source code for it used `AnsiCodeIterator` under the hood, so I ended up just borrowing the logic from that.
