### ISSUE TITLE
Bat on stdin issue losing first character

### ISSUE THREAD

**Issue by jetacpp** [sharkdp/bat#1298]
**What version of `bat` are you using?**
0.16.0
**Describe the bug you encountered:**
`ping 8.8.8.8 | bat`
Then Ctrl +C to exit. Then type some command, eg "ping". You will notice that stdin seems to lose some characters. In short, after killing bat on stdin, you need to type enter 2 times to get back to normal. 

```
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
ing
```

**Describe what you expected to happen?**
It should behave exactly like 
`ping 8.8.8.8`
Then Ctrl + C to exit. Then able to type the next command

**How did you install `bat`?**
apt-get

system
------

**$ uname -srm**
Linux 4.15.0-106-generic x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID:	Ubuntu  
Description:	Ubuntu 18.04.4 LTS  
Release:	18.04  
Codename:	bionic  

bat
---

**$ bat --version**
bat 0.16.0  

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (GNU regular expressions)

**Comment by sharkdp** [comment]
I can not reproduce this, neither on bash nor on zsh. What shell are you on?


Do you face a similar problem when using `less` instead of `bat`? Can the problem be solved by using `bat --paging=never`?

**Comment by eth-p** [comment]
From that recording, it almost looks like `less` is being opened in follow (`+F`) mode.

Do you have any user or system less config? Does it behave the same way if you update less to the latest version?

**Comment by jetacpp** [comment]
> From that recording, it almost looks like `less` is being opened in follow (`+F`) mode.
> 
> Do you have any user or system less config? Does it behave the same way if you update less to the latest version?

I don't think I've ever had a less config. Anyway, on my Ubuntu 18.04 less is already at latest version
`less is already the newest version (487-0.1).`

**Comment by sharkdp** [comment]
> From that recording, it almost looks like `less` is being opened in follow (`+F`) mode.

True. I can also reproduce some weird behavior by issuing
```bash
ping 8.8.8.8 | bat --pager="less +F"
```

There is no output in the Env section above. Could you please make sure that you do not have a `LESS` environment variable?

**Comment by jetacpp** [comment]
> There is no output in the Env section above. Could you please make sure that you do not have a `LESS` environment variable?
Actually yes, I see there is environment, which did not know of this before.
```
echo $LESS
-R
```

**Comment by sharkdp** [comment]
Ok.

I can reproduce the same weird behavior with
```
ping 8.8.8.8 | less +F -R
```

so this seems to be an issue with `less`. It might be worth to report this upstream: https://github.com/gwsw/less/issues

I'm going to close the ticket here, unless you think there is anything that can be done.
