### ISSUE TITLE
Decrease dependencies and maintenance burden

### ISSUE THREAD

**Issue by pksunkara** [sharkdp/bat#1306]
You can reduce the dependency list by removing `ansi_term` and `ansi_colours` since `console` has the same capability (and more since it handles old windows too).

I haven't looked at other dependencies though.

**Comment by sharkdp** [comment]
Thank you for the feedback.

The 24-bit => 8-bit color interpolation code comes from `bat` originally. At some point, we moved it out to a separate `ansi_colours` crate. Does `console` really have the same kind of "high quality" 8-bit color interpolation? Or is it some kind of approximation?

**Comment by pksunkara** [comment]
We have 256 color support, https://github.com/mitsuhiko/console/pull/72. Is it what you mean?

**Comment by sharkdp** [comment]
No. This is what the `ansi_colours` crate does for us:

> ansi_colours is a library which converts between 24-bit sRGB colours and 8-bit colour palette used by ANSI terminals such as xterm on rxvt-unicode in 256-colour mode.

> The most common use case is when using 24-bit colours in a terminal emulator which only support 8-bit colour palette. This package allows true-colours to be approximated by values supported by the terminal.

> When mapping true-colour into available 256-colour palette (of which only 240 are actually usable), this package tries to balance accuracy and performance. It doesn’t implement the fastest algorithm nor is it the most accurate, instead it uses a formula which should be fast enough and accurate enough for most use-cases.

Or in code:
``` rust
    // Approximate true-colour by colour in the palette:
    let rgb = (100, 200, 150);
    let index = ansi256_from_rgb(rgb);
    println!("{:?} ~ {:-3} {:?}", rgb, index, rgb_from_ansi256(index));
```

**Comment by pksunkara** [comment]
My bad then, I got confused with the name. `ansi_colours` probably can't be replaced.

**Comment by sharkdp** [comment]
And `ansi_term` is also a dependency of `clap`, so switching to `console` wouldn't really help.

**Comment by pksunkara** [comment]
Yeah. Want to note that `clap` moves to https://github.com/BurntSushi/termcolor in v3.

**Comment by sharkdp** [comment]
Thank you for the note. I guess there is a ticket somewhere documenting that decision and the reasons behind it? I'd be interested to read that.

**Comment by pksunkara** [comment]
https://github.com/clap-rs/clap/issues/836

**Comment by pksunkara** [comment]
I also want to note that it needed quite a bit of architecture refactor in clap since the philosophy on how the output is constructed is a bit different compared to `console` or `ansi_term`.
