### ISSUE TITLE
ZSH tab completion breaks if first argument is a flag

### ISSUE THREAD

**Issue by desbma** [sharkdp/bat#1320]
```
$ bat --version
bat 0.16.0
```
**Describe the bug you encountered:**
`bat <TAB>` autocompletes properly with ZSH, however `bat -p <TAB>` does not.
I think this is a recent regression.

**How did you install `bat`?**
https://www.archlinux.org/packages/community/x86_64/bat/

---

system
------

**$ uname -srm**
Linux 5.4.71-1-lts x86_64  

**$ lsb_release -a**
LSB Version:	1.4  
Distributor ID:	Arch  
Description:	Arch Linux  
Release:	rolling  
Codename:	n/a  

bat
---

**$ bat --version**
bat 0.16.0  

**$ env**
BAT_THEME=Solarized (dark)  

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

**$ /bin/zsh --login -i -c type cat**
```
cat is an alias for bat -pp
```

tool
----

**$ less --version**
less 551 (PCRE regular expressions)

**Comment by sharkdp** [comment]
Closed via #1321 by @xzfc

**Comment by desbma** [comment]
Thanks @xzfc for the quick fix

**Comment by sharkdp** [comment]
Fix released in [bat v0.17](https://github.com/sharkdp/bat/releases/tag/v0.17.0).
