### ISSUE TITLE
Can I get the output with raw color codes?

### ISSUE THREAD

**Issue by isene** [sharkdp/bat#1332]
I would like to use bat as a viewer of utf-8 files in my RTFM (https://github.com/isene/RTFM). Using the curses library in ruby, I would have to get some type of raw output with color codes to render them inside RTFM. Is this possible?

**Comment by eth-p** [comment]
Assuming you need something that can be represented as a list of tuples with with the format `(color, text)`, it's not the most straightforward thing ever, but it's certainly possible!

The approach that I would recommend is using the `ansi-dark`, `ansi-light`, or `base-16` theme in bat (which output a limited subset of ANSI colors), and then parsing the output and extracting the escape sequences that tell the terminal which color to use.

I would also recommend using:

```
--color=always
--terminal-width=40  # Or whatever number you need
```

**Comment by isene** [comment]
I could work with anything as long as I can get the color codes out somehow. Problem is, I don't know how to get bat to spit out the ansi color codes instead of the terminal actually rendering them to colors...

**Comment by isene** [comment]
OK - I found the way :-)
