### ISSUE TITLE
Diff mode: understand and render arbitrary patch files instead of calculating the diff locally

### ISSUE THREAD

**Issue by whisperity** [sharkdp/bat#1333]
0.15.0's [diff mode is amazing](http://github.com/whisperity/dotfiles/commit/ec556505bb6190f0862d8650bce7d3a224c5f208), but the problem is that it requires the _filenames_ from which the diff rendering is done by bat. This makes it impossible to be used with `git diff --cached` or `svn log --diff` and various other tools that generate the diff syntax on their output. I would like the diff rendering as a possibility, where stdin is a patch syntax. Currently I'm [using](http://github.com/whisperity/dotfiles/blob/ec556505bb6190f0862d8650bce7d3a224c5f208/packages/bash/diff/package.yaml) [`diff-so-fancy`](http://github.com/so-fancy/diff-so-fancy) but the drawback of that script is that it *only* highlights the diff, but does not perform syntax highlight, like bat's diff mode does.

**Comment by j0hnmeow** [comment]
There's [delta](https://github.com/dandavison/delta)

**Comment by whisperity** [comment]
@j0hnmeow Thanks, I've [integrated it](https://github.com/whisperity/dotfiles/commit/cb8c9f7d08e98d7287f685feb34ac750b62b072a). I'll leave it up to the maintainers to close this issue if they think this is woefully out of scope.

**Comment by sharkdp** [comment]
@whisperity That would be nice indeed, but I think that's really out of scope for `bat`. And there are other tools that do this well already.

Closing this for now, but happy to reopen, if someone thinks that there is a reasonable way to integrate this in `bat`.
