### ISSUE TITLE
Support displaying of images in the terminal

### ISSUE THREAD

**Issue by jbreitbart** [sharkdp/bat#1344]
It it would be useful to easily display display images in the terminal using bat. There seem to be various different way on how to display images within a terminal, e.g. iTerm[0] and kitty[1] all seem to do it differently. I looked around a bit and there is at least the Rust crate viuer[2] that can draw images in the terminal either using the kitty protocol or ASCII symbols.

Are there any plans to support something like this? Do you think it makes sense to add such functionality to bat?

[0] https://iterm2.com/features.html#inline-images
[1] https://sw.kovidgoyal.net/kitty/graphics-protocol.html
[2] https://github.com/atanunq/viuer

**Comment by keith-hall** [comment]
Thanks for the feedback. There are some previous discussions about this:
https://github.com/sharkdp/bat/issues/179
https://github.com/sharkdp/bat/issues/846
