### ISSUE TITLE
Log syntax highlighting cannot be specified

### ISSUE THREAD

**Issue by stdedos** [sharkdp/bat#1346]
I have two files: display-4.log and display-4.log.bak - both of them are python logs with timestamps, optional tags (warning, error) and message

If I do:
* `bat display-4.log`, highlight is done okay.
* `bat display-4.log.bak`, there is no highlight.
* `bat -llog display-4.log.bak`, there is no highlight.
* `bat -l.log display-4.log.bak`, I get an error.
* `bat -lsyslog display-4.log.bak` (cheating from `bat --list-languages`), there is still no highlight.

And I ask:
* What am I doing wrong?
* Why is bat erroring out on passing file's "theoretical extension" (can it be done?)?
* Can bat ignore extensions like `.bak`,`.~`, etc and invoke it's magical matching after such ignore?

**Comment by sharkdp** [comment]
Thank you for reporting this. I can not reproduce this.

Can you please post the output of the script at https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh in order for us to get more information about your system?

**Comment by sharkdp** [comment]
> Why is bat erroring out on passing file's "theoretical extension" (can it be done?)?

That should actually work. If I understand you correctly. Please post an example that we can use to reproduce

> Can bat ignore extensions like `.bak`,`.~`, etc and invoke it's magical matching after such ignore?

It can not. But that is an interesting request. I'm not sure if its univerally accepted that `whatever.xyz.bak` files are actually `whatever.xyz` files? Or does `.bak` exist as a separate file extension as well?

Note that you can add something like
```bash
--map-syntax '*.log.bak:log'
```
to `bat`s config file to achieve this for `.log.bak` files.

**Comment by stdedos** [comment]
> Thank you for reporting this. I can not reproduce this.
> 
> ![image](https://user-images.githubusercontent.com/4209276/97212006-1d707100-17c0-11eb-9b72-fcfbab209835.png)

The file format is `timestamps, optional tags (warning, error) and message`, and not the one you are showing.
It's a bit tricky to post this file, but I'll try to get around it then.

> Can you please post the output of the script at [https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh](https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh?rgh-link-date=2020-10-26T18%3A18%3A01Z) in order for us to get more information about your system?

Same goes with anything that I need to exfil from the system in question, but, since we have no other option, I guess I have to.

> Also, could you please post some content of the log file(s) in question?

^^

> I guess the question also is: what are you expecting from the `syslog`/`log` highlighting?

I am expecting that the highlighting would continue working ...

> > Why is bat erroring out on passing file's "theoretical extension" (can it be done?)?
> 
> That should actually work. If I understand you correctly. Please post an example that we can use to reproduce

_Let me add a definition here: "Theoretical extension" is the feature that e.g. formats a file without an extension as a shellscript, because e.g. it contains a shebang (maybe I should've called it file signature? idk)_

... if it's the file's "theoretical extension" that is responsible for its highlight, then I would have expected it to work out of the box (i.e. without `-lx`) which it didn't do, ...

> Note that you can add something like
> 
> ```shell
> --map-syntax '*.log.bak:log'
> ```
> 
> to `bat`s config file to achieve this for `.log.bak` files.

... and `-llog` did not work either.

> > Can bat ignore extensions like `.bak`,`.~`, etc and invoke it's magical matching after such ignore?
> 
> It can not. But that is an interesting request. I'm not sure if its univerally accepted that `whatever.xyz.bak` files are actually `whatever.xyz` files? Or does `.bak` exist as a separate file extension as well?

Well "universally accepted" I don't know; but that's how I use it, and I haven't seen a file type that ends in .bak

Examples in the wild can be:
https://en.wikipedia.org/wiki/Bak_file
https://file.org/extension/bak
https://filext.com/file-extension/BAK
https://extension.nirsoft.net/bak
https://fileinfo.com/extension/bak

**Comment by sharkdp** [comment]
>  It's a bit tricky to post this file, but I'll try to get around it then.

Ok. Maybe you could try to manually write a minimal example that showcases this bug but does not expose any private information?

Is the content of `display-4.log` exactly the same as `display-4.log.bak`? If not, can you try to copy `display-4.log.bak` to - say - `/tmp/display-4.log` and try to use `bat` on that file? Does it work as expected?

**Comment by stdedos** [comment]
It's not about redacting (it's already redacted enough); it's about "moving it out of there and into Github".
I didn't think of it earlier; you can find an example e.g. here https://xpra.org/trac/ticket/2912 (the second code block).

The contents of the files are "similar looking"; `.bak` is just the rotated version of `display-:4.log`.

**Comment by sharkdp** [comment]
You can attach files to GitHub comments. It would be great to get an actual file to reproduce this. What about the last question in my comment above?

**Comment by stdedos** [comment]
> You can attach files to GitHub comments.

Today was a weird day and exfiltrating the files never actually crossed my mind; I'll try for tomorrow.

> It would be great to get an actual file to reproduce this.

I think I have meticulously quote-replied to all of your questions. It would be nice if you explicitly quoted which question I have missed.

> What about the last question in my comment above?

If your question was exactly the one above:
> Is the content of display-4.log exactly the same as display-4.log.bak? If not, can you try to copy display-4.log.bak to - say - /tmp/display-4.log and try to use bat on that file? Does it work as expected?

Then, I have already replied:

> I didn't think of it earlier; you can find an example e.g. here [xpra.org/trac/ticket/2912](https://xpra.org/trac/ticket/2912) (the second code block).
> 
> The contents of the files are "similar looking"; `.bak` is just the rotated version of `display-:4.log`.

**Comment by sharkdp** [comment]
I was talking about this question:

> […] can you try to copy display-4.log.bak to - say - /tmp/display-4.log and try to use bat on that file? Does it work as expected?

You said it's a rotated version of the original. But that could still mean that highlighting fails. Syntax highlighting is not a line-wise process. It can depend on prior lines (think of multiline comments).

**Comment by stdedos** [comment]
Oh, you gave me work for home 😅 I missed it.

The problem is the file is not recognized at all, and "I think" it has to do with the extension somehow not invoking "more extended syntax detection features".

I'll try it tomorrow just before uploading.

**Comment by stdedos** [comment]
First of all - the second file extension is `.old` and not `.bak`; and renaming does not affect it.

Here are your diagnostics (although not useful I guess):

**$ diagnostics/info.sh**

system
------

**$ uname -srm**
Linux 4.15.0-107-generic x86_64

**$ lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial

bat
---

**$ bat --version**
bat 0.16.0

**$ env**

bat_config
----------

**$ cat /home/sntentos/.config/bat/config**
```
# Set the theme to "TwoDark"
--theme=OneHalfDark

# Show line numbers, Git modifications, file header and grid
--style="numbers,changes,header,grid"
--style="snip"

# Use italic text on the terminal
--italic-text=always

# Use "gitignore" highlighting for ".ignore" files
--map-syntax .ignore:.gitignore

--pager="/home/sntentos/.installs/smartless/smartless -H"
```

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 481 (GNU regular expressions)

And here are your files: [D.zip](https://github.com/sharkdp/bat/files/5450451/D.zip)

**Comment by sharkdp** [comment]
I think the main problem is that the "Log" syntax highlighting is not really meant for all kind of log files, but for syslogs specifically. Your log files have another format.

I think it would be great if we could extend the scope of the "Log" syntax a bit, but I don't think that there is an actual bug in `bat` right now. The fact that a log-rotated file is highlighted differently is not (in and of itself) surprising.

**Comment by stdedos** [comment]
> The fact that a log-rotated file is highlighted differently is not (in and of itself) surprising. 

If it's not, then fine! 😄
