### ISSUE TITLE
When using -A, LF cannot be shown in the right way

### ISSUE THREAD

**Issue by purplemysticx** [sharkdp/bat#1351]
When using -A, LF cannot be shown in the right way, Need to install some fonts? 
If yes, which font needs to be installed?

BTW, I have installed these fonts.([powerline](https://github.com/powerline/powerline))

![image](https://user-images.githubusercontent.com/26994103/97403556-96daa180-192f-11eb-9260-b1735f59eda5.png)

**Comment by j0hnmeow** [comment]
Try installing one of [Nerd Fonts](https://nerdfonts.com/)

**Comment by purplemysticx** [comment]
Thanks, @j0hnmeow 
I have found the root cause: XShell not support (Need to install fonts for XShell)
