### ISSUE TITLE
Release 0.16 added dependencies

### ISSUE THREAD

**Issue by 0x3333** [sharkdp/bat#1352]
In version 0.15.4, the deb file has no dependencies, in the last version 0.16.0 there is 2 dependencies, `libgcc1-armhf-cross` and `libc6:armhf`.

I don't know if this is by design or an error, but with no dependencies, we could just install the deb, like in the Raspberry Pi.

Version: 0.15.4
```
dpkg-deb --info bat_0.15.4_armhf.deb
 new Debian package, version 2.0.
 size 1817094 bytes: control archive=349 bytes.
     306 bytes,    11 lines      control
 Package: bat
 Version: 0.15.4
 Section: utils
 Priority: optional
 Maintainer: David Peter <mail@david-peter.de>
 Homepage: https://github.com/sharkdp/bat
 Architecture: armhf
 Provides: bat
 Conflicts: bat-musl
 Description: A cat(1) clone with wings.
  A cat(1) clone with syntax highlighting and Git integration.
```

Version: 0.16.0

```
dpkg-deb --info bat_0.16.0_armhf.deb
 new Debian package, version 2.0.
 size 1844620 bytes: control archive=468 bytes.
     367 bytes,    12 lines      control
 Package: bat
 Version: 0.16.0
 Section: utils
 Priority: optional
 Maintainer: David Peter <mail@david-peter.de>
 Homepage: https://github.com/sharkdp/bat
 Architecture: armhf
 Depends: libc6:armhf (>= 2.27), libgcc1-armhf-cross (>= 1:4.3)        <---------- HERE
 Provides: bat
 Conflicts: bat-musl
 Description: cat(1) clone with wings.
  A cat(1) clone with syntax highlighting and Git integration.
```

**Comment by sharkdp** [comment]
Thank you for reporting this! That seems wrong, indeed.

This seems to come from our move to GitHub Actions. @rivy: If you find the time, could you take a short look at this? It seems that those `-cross` package dependencies should not be there, right?

**Comment by rivy** [comment]
@sharkdp , it looks like you and @chris48s purposefully added the "Depends" line in 883cc964aeff.

Not being versed in Debian packaging, I can't give an opinion on whether it's a correct addition or not.

**Comment by sharkdp** [comment]
@rivy Thank you for taking a look. Sorry - I had forgotten about that PR. Should have checked via `git blame`.

@chris48s Could you please shed some light on this?

**Comment by chris48s** [comment]
Sorry this has caused a problem. My interpretation was that `dpkg-shlibdeps` is the correct way to work out shared library dependencies for an executable, but it seems like this is generating incorrect `Depends: ` lines for the cross-compiled architectures (but correct for the amd64 package).

I _think_ the correct `Depends: ` lines for arm64, armhf and i686 would actually be:

* arm64: `Depends: libc6 (>= 2.27), libgcc1 (>= 1:4.2)`
* armhf: `Depends: libc6 (>= 2.27), libgcc1 (>= 1:4.3)`
* i686: `Depends: libc6 (>= 2.18), libgcc1 (>= 1:4.2)`

I'm afraid this is slightly at the edge of my knowledge too.

I think the best option for now would be to go back to a blank or missing `Depends: ` line for the arm64, armhf and i686 architectures on the basis it is better to not declare dependencies than declare incorrect dependencies. I will try and do a bit of reading and see if I can find out the right way to generate this when you're not compiling for the target architecture.

**Comment by chris48s** [comment]
I spent a few hours on this and I still don't have the answer to how to set this correctly if the target architecture isn't the one we compiled on, so I'm going to stick with the suggestion of dropping the Depends line for non-x64 architectures for now. While I was having a bit of a play with this, I also uncovered another issue which is only tangentially related to this issue, but worth thinking about at the same time.

In the CI build, when a release is tagged both the `ubuntu-16.04, x86_64` and `ubuntu-18.04, x86_64` build runs will build a `bat_[version]_amd64.deb` and attempt to publish it. Have a look at the "Publish archives and packages" step on the v0.16.0 builds:

* https://github.com/sharkdp/bat/runs/1200999377 (ubuntu-18.04, x86_64)
* https://github.com/sharkdp/bat/runs/1200999399 (ubuntu-16.04, x86_64)

You'll see that both of them tried to publish `bat_0.16.0_amd64.deb`. In this case, the ubuntu-16.04 build published the deb successfully and the ubuntu-18.04 failed (but interestingly, the actual build step reports success despite failing with `HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}`). I guess this is just a race condition and whichever one finishes first will 'win'. I think I have 3 suggestions here:

* If publishing a release fails, the build step should report failure (this might actually be an upstream error with https://github.com/softprops/action-gh-release - I've not looked into it yet)
* Only one of these two builds should attempt to publish a deb.
* Assuming the objective here is to publish a deb that is installable back to 16.04 (as opposed to distro repositories where there is a specific deb built for each distro version), the build that should publish the release should be the 16.04 build to ensure compatibility. This happened by coincidence for bat version 0.16.0 but this should be formalised and predictable.

**Comment by sharkdp** [comment]
@chris48s Thank you very much for these insights!

For now, I will revert your PR (see #1393), but the issues you mentioned definitely be fixed. I will leave this ticket open. Any help is highly appreciated.

**Comment by chris48s** [comment]
- I've submitted a PR to avoid the race condition at #1399
- Having looked into it, the issue where the "Publish archives and packages" step throws `UnhandledPromiseRejectionWarning` but the build step "passes" seems to be an issue with the action itself rather than this workflow: https://github.com/softprops/action-gh-release/issues/43 so that is an issue for the upstream repo
- Reverting all those commits seems a bit heavy-handed given https://github.com/sharkdp/bat/pull/1393/commits/9ac932d0fcabb8b000e1c786666be495b28feeed would have resolved the reported issue. The other commits reverted in that PR are unrelated. Would you consider a PR to reinstate the other commits unrelated to the Depends statement?

**Comment by sharkdp** [comment]
> Reverting all those commits seems a bit heavy-handed given [9ac932d](https://github.com/sharkdp/bat/commit/9ac932d0fcabb8b000e1c786666be495b28feeed) would have resolved the reported issue. The other commits reverted in that PR are unrelated. Would you consider a PR to reinstate the other commits unrelated to the Depends statement?

That would be great, thanks!
