### ISSUE TITLE
Installation from testing on Debian stable removes cryptsetup - and breaks boot if LVM is used

### ISSUE THREAD

**Issue by iaeiou** [sharkdp/bat#1371]
Hi there,

**SUMMARY:**

a basic installation of `bat` on Debian 10 resulted in a broken OS, stuck at boot process: `apt install bat` removes without a (clear) warning `cryptsetup-initramfs`, which is required to decrypt the harddrive with LVM

**HOW TO REPRODUCE:**

On a Debian 10, simply run `apt install bat`

Here is the result from my Terminal:

```
The following additional packages will be installed:
  libgcc-s1 libgit2-28 libhttp-parser2.9
The following packages will be REMOVED:
  cryptsetup-initramfs
The following NEW packages will be installed:
  bat libgcc-s1 libgit2-28 libhttp-parser2.9
```
See the inconspicuous reference to `cryptsetup-initramfs`? Many users don't know about cryptsetup (or won't even notice this line - as I did, my bad!) and the result is this scary message at next boot:

```
Volume group "debian-vg" not found
Cannot process volume group debian-vg
Gave up waiting for suspend/resume device
```
It's not even possible to start using `failsafe mode`, the only solution I found is to select the advanced options in Grub, select the previous `initramfs`, boot and reinstall `cryptsetup-initramfs`

Thx for your attention, cheers

**SETUP:**
- Debian GNU/Linux 10 (buster) stable
- GNOME 3.30.2
- Kernel: 4.19.0-10-amd64 x86_64 bits: 64
- Display: wayland server: X.Org 1.20.4 driver: i915

**Comment by sharkdp** [comment]
Thank you for reporting this!

This sounds a bit strange. For one, `bat` should not be available on Debian buster (https://github.com/sharkdp/bat#on-ubuntu-using-apt). Did you set up some sort of apt-repository? Or did you install from the Debian packages on the release page in this repo?

Also, the actual `bat` package in Debian only depends on libc, libgcc, and libgit. I'm not sure, but I would be surprised if any of these packages would conflict with `cryptsetup-initramfs`. Are you sure that this package was not staged for removal due to some other unrelated process? Why is "libhttp-parser2.9" being installed?

@paride would you mind taking a look at this if you find the time?

**Comment by iaeiou** [comment]
> Did you set up some sort of apt-repository?

You're right, I'm running stable but `bat` was indeed fetched from the `testing` / bullseye repository:

```
# apt show bat
Package: bat
Version: 0.12.1-4
Built-Using: rust-ansi-colours (= 1.0.1-2), rustc (= 1.46.0+dfsg1-1)
Priority: optional
Section: utils
Source: rust-bat
Maintainer: Debian Rust Maintainers <pkg-rust-maintainers@alioth-lists.debian.net>
Installed-Size: 4,365 kB
Depends: libc6 (>= 2.18), libgcc-s1 (>= 4.2), libgit2-28 (>= 0.28.1)
[...]
APT-Sources: http://debian.proxad.net/debian testing/main amd64 Packages
```

```
# apt -s install bat
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cryptsetup-bin cryptsetup-run keyutils
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  libgcc-s1 libgit2-28 libhttp-parser2.9
The following packages will be REMOVED:
  cryptsetup-initramfs
The following NEW packages will be installed:
  bat libgcc-s1 libgit2-28 libhttp-parser2.9
0 upgraded, 4 newly installed, 1 to remove and 73 not upgraded.
Remv cryptsetup-initramfs [2:2.1.0-5+deb10u2]
Inst libgcc-s1 (10.2.0-16 Debian:testing, Debian:unstable [amd64])
Inst libhttp-parser2.9 (2.9.2-2 Debian:testing, Debian:unstable [amd64])
Inst libgit2-28 (0.28.5+dfsg.1-1 Debian:testing, Debian:unstable [amd64])
Inst bat (0.12.1-4 Debian:testing, Debian:unstable [amd64])
Conf libgcc-s1 (10.2.0-16 Debian:testing, Debian:unstable [amd64])
Conf libhttp-parser2.9 (2.9.2-2 Debian:testing, Debian:unstable [amd64])
Conf libgit2-28 (0.28.5+dfsg.1-1 Debian:testing, Debian:unstable [amd64])
Conf bat (0.12.1-4 Debian:testing, Debian:unstable [amd64])
```
```
# apt autoclean
Reading package lists... Done
Building dependency tree       
Reading state information... Done
```
> Are you sure that this package was not staged for removal due to some other unrelated process?

I don't know. Is there a way to investigate? I've checked in `/var/log/apt/history.log` and the first reference to cryptsetup is the one related to `bat` installation:

```
Start-Date: 2020-11-06  01:34:16
Commandline: apt install bat
Install: gcc-10-base:amd64 (10.2.0-16, automatic), bat:amd64 (0.12.1-4), libhttp-parser2.9:amd64 (2.9.2-2, automatic), libgcc-s1:amd64 (10.2.0-16, automatic), libgit2-28:amd64 (0.28.5+dfsg.1-1, automatic)
Remove: cryptsetup-initramfs:amd64 (2:2.1.0-5+deb10u2), cryptsetup:amd64 (2:2.1.0-5+deb10u2)
End-Date: 2020-11-06  01:34:33
```

> Why is "libhttp-parser2.9" being installed?

I don't know but I can provide some more information, just ask

So it seems that this bug occurs only when the installation is done from `testing` on `stable`, I update the title accordingly

Cheers

**Comment by paride** [comment]
Hi,

The `bat` package is definitely not available in Debian 10 (buster), and the package is not declared to conflict with any other package. However the package has *versioned* dependencies on very basic system packages/libraries, and forcing the installation of a package from Debian testing or unstable on Debian stable is very likely to cause problems. This is true in general, see:

https://wiki.debian.org/DontBreakDebian

and in particular:

https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

I think we can exclude this is a bug in bat or in the bat Debian package.

**Comment by sharkdp** [comment]
Thank you for the detailed information, @iaeiou.

@paride: Thank you very much for clarifying this! In this case, I'd like to close this ticket.
