### ISSUE TITLE
Explicit style always disabled by piping

### ISSUE THREAD

**Issue by xerus2000** [sharkdp/bat#1372]
```sh
❯ bat --version
bat 0.16.0
❯ for i in 1 2 3; do echo "hi$i" >test$i; done
❯ bat --style=header test*
File: test1
hi1

File: test2
hi2

File: test3
hi3
❯ bat --style=header test* > tt
❯ cat tt
hi1
hi2
hi3
```

**Describe the bug you encountered:**
When piping from bat with an explicit style, the style is ignored.

**Describe what you expected to happen?**
I know that bat should fallback and act like cat when piping by default, but I don't think this is correct when a style is explicitly selected.
I wanted to have the exact output of bat in that file I piped to, to easily merge the files while still being able to distinguish what came from which file.

**How did you install `bat`?**
Pacman

**Comment by sharkdp** [comment]
>  I wanted to have the exact output of bat in that file I piped to, to easily merge the files while still being able to distinguish what came from which file.

Take a look at the `--decorations` option.
```
--decorations=always
```

If you want colors as well, add
```
--color=always
```

Since `bat` 0.16, you can also use `-f`/`--force-colorization` to enable both:
```
bat --style=header -f test* > tt
```

**Comment by xerus2000** [comment]
Thanks, should have looked more at the manual :sweat_smile:
