### ISSUE TITLE
Repology - wrong AUR package 

### ISSUE THREAD

**Issue by tuxiqae** [sharkdp/bat#1375]
**Describe the bug you encountered:**
For some reason [Repology](https://repology.org/project/bat/versions) shows another app instead of `bat` under AUR.
![image](https://user-images.githubusercontent.com/39622904/98577584-d8226800-22c4-11eb-8aba-c0d0b4f3b31d.png)

It uses [bat-git](https://aur.archlinux.org/packages/bat-git) instead of [bat-cat-git](https://aur.archlinux.org/packages/bat-cat-git)

**What did you expect to happen instead?**
I'd expect to only see `bat-cat-git` and not other apps

**Comment by sharkdp** [comment]
Thank you very much for opening this ticket. I think the best place to address this would be the issue tracker on repology: https://repology.org/project/bat/report

**Comment by sharkdp** [comment]
Reported upstream.
