### ISSUE TITLE
Tab autocomplete not working with the plain -p/--plain option

### ISSUE THREAD

**Issue by SilentVoid13** [sharkdp/bat#1379]
**What version of `bat` are you using?**
bat 0.16.0

**Describe the bug you encountered:**
The autocomplete is not working when using the `-p` / `--plain` option with `bat`.
It is working fine with the `-A` or `-n` option.

**What did you expect to happen instead?**
I would expect the autocomplete to be triggered with the `-p` option.

**How did you install `bat`?**

I installed `bat` via `pacman`.

---

system
------

**$ uname -srm**
Linux 5.9.8-arch1-1 x86_64

bat
---

**$ bat --version**
bat 0.16.0

**$ env**
PAGER=less

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

**$ /bin/zsh --login -i -c type cat**
```
cat is an alias for bat
```

tool
----

**$ less --version**
less 563 (PCRE regular expressions)

**Comment by eth-p** [comment]
You're using zsh, right?

 #1320 might be applicable to your issue.

**Comment by SilentVoid13** [comment]
I'm using `zsh` and you're right this issue was fixed in #1321. 
Autocomplete is working when compiling `bat` from `master`.
I'll wait for the next release for these changes to take effect !
Sorry for the duplicate, closing the issue.
