### ISSUE TITLE
Open at bottom of the file

### ISSUE THREAD

**Issue by howdoicomputer** [sharkdp/bat#1380]
Essentially a `less +G` option that puts you at the bottom of the document (useful to check to see what was appended).

**Comment by howdoicomputer** [comment]
Thank you for the project!

**Comment by keith-hall** [comment]
Hi, thanks for the feedback. Does the advice at https://github.com/sharkdp/bat/issues/1077#issuecomment-652785399 help?

**Comment by howdoicomputer** [comment]
Ah, I didn't search closed issues. Hm, it'd be great if it was a flag but I'll write out a quick `batb` alias for starting at the bottom of the file.
