### ISSUE TITLE
Wrong manpage highlighting

### ISSUE THREAD

**Issue by duongdominhchau** [sharkdp/bat#1382]
# Description
I found some problems about the highlighting when I run these commands:

```sh
`MANPAGER="bat --style=plain --language=man" man paru.conf`
`MANPAGER="bat --style=plain --language=man" man paru`
```

The character after `-` is duplicated and then a `^H` is inserted between the original and the duplicated character. However, sometimes it works correctly, you can see `-Syu` and `--needed` correctly highlighted.

![image](https://user-images.githubusercontent.com/56427890/99171471-ef85a900-273b-11eb-9264-62b57dcacf11.png)
![image](https://user-images.githubusercontent.com/56427890/99171479-f57b8a00-273b-11eb-8586-5bb0ef399b64.png)
![image](https://user-images.githubusercontent.com/56427890/99177655-7176d180-273e-11eb-92ac-40e99740d9e0.png)
![image](https://user-images.githubusercontent.com/56427890/99177696-af73f580-273e-11eb-8b12-70f4a4b5cdd6.png)

By the way, looks like only the first word of the sections name is highlighted (look at `PARU OPERATIONS` and `EXTENDED PACMAN OPERATIONS`).

Page name color is wrong. Also, sometimes the parentheses are duplicated and  `^H` is inserted in between.

![image](https://user-images.githubusercontent.com/56427890/99177751-2a3d1080-273f-11eb-8e33-1c8c6c8a1135.png)
![image](https://user-images.githubusercontent.com/56427890/99173979-04167100-273d-11eb-95b8-493df8a5d67c.png)
![image](https://user-images.githubusercontent.com/56427890/99173406-d4676900-273c-11eb-8431-ed95f9cdb559.png)
![image](https://user-images.githubusercontent.com/56427890/99171482-04fad300-273c-11eb-8c2b-11ae8de5c46c.png)
![image](https://user-images.githubusercontent.com/56427890/99177804-7a1bd780-273f-11eb-9e57-107a2a0bab37.png)

# Expected behavior
- Sections name should have the same color.
- Flags are correctly highlighted without duplicated characters and `^H`.
- Name of man pages should be uniformly highlighted, without `^H` and duplicated parentheses. The name should match `[-\w.]+\([1-9]\)` (examples: `ntfs-3g(8)`, `pg_ctl(1)`, `systemd-system.conf(5)`, ...).
- Do not highlight if the character before `-` is not a space/tab/newline (like in the case of `ls-remote`, `-remote` is not a flag)

# How did you install `bat`?

```sh
pacman -S bat
```

# `info.sh` output

```
system
------

**$ uname -srm**
Linux 5.9.8-arch1-1 x86_64

**$ lsb_release -a**
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

bat
---

**$ bat --version**
bat 0.16.0

**$ env**
PAGER=less

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 563 (PCRE regular expressions)
```

**Comment by keith-hall** [comment]
Thanks for reporting. I wonder if this is related to https://github.com/sharkdp/bat/issues/652

**Comment by sharkdp** [comment]
Could you please set `MANPAGER` to the value suggested in https://github.com/sharkdp/bat#man?

With that setting, I can not reproduce the error. The output looks as expected.

**Comment by duongdominhchau** [comment]
Yes, with that `MANPAGER` value, most problems disappear, only the problem at names with dot like `pacman.conf` and `paru.conf` left.

![image](https://user-images.githubusercontent.com/56427890/104113392-ea07a200-532b-11eb-9ba4-e9b5a67208d6.png)

I also notice some bold text are now regular, is it because `\b` being stripped off? Can we do anything to preserve that?

**Comment by sharkdp** [comment]
Please see #652.

**Comment by sharkdp** [comment]
> only the problem at names with dot like `pacman.conf` and `paru.conf` left.

It would be great if you could open a separate ticket for that. Thank you!
