### ISSUE TITLE
`cat` doesn't page the output... how can I make `bat` work the same?

### ISSUE THREAD

**Issue by nstickney** [sharkdp/bat#1383]
So, I feel like I must be an idiot because I can't find anything about this anywhere.

In the README, it states,

> * Be a drop-in replacement for (POSIX) `cat`

as a goal... but it clearly isn't. `cat` doesn't page output. I want `bat` to work the same way by default. Is there some way to achieve this behavior? To be clear, I want to **disable automatic paging** because I use tools which depend on `cat` output not being paged (e.g. `yay`/`paru`).

**Comment by keith-hall** [comment]
There's a note about how to disable paging at https://github.com/sharkdp/bat/blob/master/README.md#colors

**Comment by nstickney** [comment]
Hooray! I knew I was an idiot!
