### ISSUE TITLE
Empty lines in grid on Windows

### ISSUE THREAD

**Issue by Tobbe** [sharkdp/bat#1384]
**What version of `bat` are you using?**
```bash
$ bat --version
bat 0.15.4
```

**Describe the bug you encountered:**

When running `bat` I get empty lines at the start of each "row" in the grid

![image](https://user-images.githubusercontent.com/30793/99193095-05648f80-2777-11eb-83ae-97a8ac2dec8e.png)

**What did you expect to happen instead?**

No extra empty or blank lines

**How did you install `bat`?**
Pre-built binaries from the release page

---

Windows 10 10.0.19041
GitForWindows 2.29.1
ConEmu 201011

**Comment by Tobbe** [comment]
Noticed I wasn't using the latest version of bat, so I updated. Didn't help unfortunately

![image](https://user-images.githubusercontent.com/30793/99193347-b15aaa80-2778-11eb-9622-6db73dc82bdc.png)

**Comment by sharkdp** [comment]
possibly related to #1098?

**Comment by Tobbe** [comment]
Just tried in PowerShell, and it doesn't show the same problem

![image](https://user-images.githubusercontent.com/30793/100056741-7b778f00-2e26-11eb-888e-4d801f0836df.png)

That prompted me to also try Git Bash (mintty 3.4.0). Works there as well

![image](https://user-images.githubusercontent.com/30793/100056908-bda0d080-2e26-11eb-8ec9-b4a11573bf70.png)

So it seems to be specific to my regular terminal, ConEmu.

**Comment by sharkdp** [comment]
Could you please check if this is related to the pager (`less`)? Run `bat` with `--paging=never`:
```
bat --paging=never web/src/index.css
```

**Comment by Tobbe** [comment]
![image](https://user-images.githubusercontent.com/30793/100150666-3d1eb600-2ea0-11eb-98f2-7cb643f84c3b.png)

**Comment by sharkdp** [comment]
Ok, that is weird. What happens if the terminal width is close to a line with text content? Like.. if the terminal is *just* wide enough to fit the line ending in `EDIT` above (I guess your screenshot only shows part of the full terminal width)

**Comment by Tobbe** [comment]
This is what it looks like with a narrow terminal

![image](https://user-images.githubusercontent.com/30793/100552445-851a5000-3287-11eb-85d5-8ca61762c94b.png)

Does that help? Anything else you want me to try?

**Comment by Tobbe** [comment]
If I have a wide full-screen terminal results are a little inconsistent

![image](https://user-images.githubusercontent.com/30793/100552635-b7787d00-3288-11eb-882c-b6c481859370.png)

Once it "breaks" I can fix it by making the window narrow, and then full-screen again.

![image](https://user-images.githubusercontent.com/30793/100552709-10e0ac00-3289-11eb-9456-243a0b8fd130.png)

**Comment by Tobbe** [comment]
I just opened a file with a single very long line, and this is what I got

![image](https://user-images.githubusercontent.com/30793/101018260-8390a680-356b-11eb-88e7-ec3d8cf11d67.png)

So clearly something's wrong with wrapping

**Comment by Tobbe** [comment]
If I do `clear` first it works.

![image](https://user-images.githubusercontent.com/30793/101018726-32cd7d80-356c-11eb-8084-8df40143eb7d.png)

So something goes wrong when there is enough content to trigger a scrollbar?

**Comment by sharkdp** [comment]
I'm sorry, but this really looks like it's related to the terminal emulator then. Maybe you could report the issue there?

**Comment by sharkdp** [comment]
closing for now. please let me know if it should be reopened.
