### ISSUE TITLE
Scrolling with Magic Trackpad on MBP is not supported

### ISSUE THREAD

**Issue by vt128** [sharkdp/bat#1387]
**What version of `bat` are you using?**
[paste the output of `bat --version` here]

bat 0.16.0

**Describe the bug you encountered:**

Scrolling with Magic Trackpad on MBP is not supported.

**What did you expect to happen instead?**

Can scroll like using `less`

**How did you install `bat`?**

Homebrew

---

[paste the output of `info.sh` here]

**Comment by eth-p** [comment]
What version of `less` are you using?

If you're using an old version, bat automatically passes `--no-init` to less in order to avoid a bug. Unfortunately, that also has the effect of disabling scroll wheel support.

**Comment by vt128** [comment]
On macOS:

```
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

On Ubuntu 18.04 with the same issue:
```
❯ less --version
less 487 (GNU regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less

```

**Comment by eth-p** [comment]
Yeah, your version of less is outdated. I'm not sure how to get the latest for Ubuntu, but on your Mac the issue should be fixed if you install `less` through homebrew.

**Comment by vt128** [comment]
Well, the dep on `less` seems a little bit strange.

I'm not familiar with Rust, but have you ever think about rewrite this very dep, or compile latest `less` with Rust code of bat (some tech like JIT, or `cgo` in Golang)?

**Comment by sharkdp** [comment]
> Well, the dep on `less` seems a little bit strange.

Why? `bat` uses `less` as an external pager. If you talk about versioning, yes. Package maintainers should probably make sure that we have a compatible version of less installed. We would need to figure out what that version is. It depends on the OS. For Linux/macOS, I would guess that 551 is fine. For Windows, a very recent version is needed to avoid a few bugs.

**Comment by sharkdp** [comment]
> I'm not familiar with Rust, but have you ever think about rewrite this very dep,

yes, see #1053 



> or compile latest `less` with Rust code of bat (some tech like JIT, or `cgo` in Golang)?

I have not thought about that, but I don't really want to get into this. We support a large number of operating systems and CPU architectures. I think this is better left to OS package maintainers.

**Comment by sharkdp** [comment]
I'm closing this for now, but maybe we should consider adding "less" as a dependency for the "bat" homebrew package?
