### ISSUE TITLE
Changing the style while viewing a file

### ISSUE THREAD

**Issue by seifrox** [sharkdp/bat#1388]
Hi,

I just recently found this project, tried it and love it, so thanks for that!

One thing I am missing is the possibility to switch between styles while viewing a document (in paging mode, it does not make sense if you just used it as a cat replacement), either via some command or even better via some key binding.

My use case:

I integrated `bat` as my go to text preview tool in [`nnn`](https://github.com/jarun/nnn), for this I set the `-p --paging=always` option to have less clutter, from time to time, however I would like to have line numbers or the git diff enhancements while viewing such a file. So initially I had to close bat, switch to the terminal and open the file again manually with a different style (without the `-p` flag). Of course I already optimized my workflow to have this option available as a plugin in `nnn`, but I still need to close the file and reopen it differently which feels awkward from a usability point of view.

I of course also tried to google for different solutions, but did not have any luck yet. Feel free to tell me something I missed.

Of course if you think such a feature could be useful, it does not have to stop there you could also allow e.g. a change of the language and such.

Now having written this request, acting as a rubber duck for myself, I realize that this might be nearly impossible, since for the paging you rely e.g. on `less` so all the interaction is actually with `less` and not with `bat` I assume.

I would still be happy to hear your thoughts on this!

BR,
Alex

**Comment by keith-hall** [comment]
Thanks for your detailed feedback! 

> Now having written this request, acting as a rubber duck for myself, I realize that this might be nearly impossible, since for the paging you rely e.g. on `less` so all the interaction is actually with `less` and not with `bat` I assume.

There are indeed many uses for more control from the pager, I think https://github.com/sharkdp/bat/issues/1053 might interest you :)

**Comment by seifrox** [comment]
Hi,

Yeah this is very interesting :) Thanks for the quick feedback!

It basically has my wish already implicitly included, with this point:

> Disable style components via keypress. For example: switch off the side bar with a keypress - for easy copy&paste.

So I guess my feature request is just a subset and would definitely require a built-in pager, so I guess this one can be closed.

BR,
Alex
