### ISSUE TITLE
How to make the line number/header more readable?

### ISSUE THREAD

**Issue by Pauloo27** [sharkdp/bat#1392]
My config:
```
--theme="Dracula"
--italic-text=always
```

When I use bat in a file the code follows the Dracula color scheme but the line number and the "decorators" doesn't:
![screenshot 1](https://i.imgur.com/qw7Kzz8.png)

Using some themes (base16, for example) the the decorators are way better to read:
![screenshot 2](https://i.imgur.com/IwrCttS.png)

With an transparent background terminal it's even worst:
![screenshot 3](https://i.imgur.com/wmdtMBM.png)

How can I make the decorators use the dracula colors?

Thanks in advacne.

**Comment by sharkdp** [comment]
related to #339?

**Comment by Pauloo27** [comment]
Thanks <3
