### ISSUE TITLE
Running `bat` without arguments fails (output file is also an input)

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#1396]
**What version of `bat` are you using?**
0.17.0

**Describe the bug you encountered:**
Running `bat` without any arguments results in:
```
▶ bat                         
[bat error]: The output file is also an input!
```

**What did you expect to happen instead?**
`bat` reads from (and writes to) STDIN

FYI: @niklasmohrin

**Comment by niklasmohrin** [comment]
Oh, that's not good. I am on it

**Comment by sharkdp** [comment]
No worries :smile:. If you would like to fix this - great! But please don't feel obliged. Also, there is no need to hurry!

That being said, I would like to get out a 0.17.1 release that fixes this. We can simply revert your PR for now and then work on a proper solution.

We should also check if this same bug appears if we read/write from/to a FIFO different from `STDIN`/`STDOUT`.

**Comment by niklasmohrin** [comment]
That sounds fair, I also got a bug report on the repo itself about `bat` builds failing on the `i686-linux-android` target, so it would be nice to have this fixed until I figure out how to get the correct types. I could release a version where the Identifier just wraps the whole `FileStat` struct so that no types are named, which should then compile everywhere and then work on a fix.

**Comment by niklasmohrin** [comment]
@sharkdp After some investigation, I think that it would be best to never hand out `Identifier`s to TTYs, to mitigate these clashes that really are none. Do you think this could break anything? Is there ever a conflict in reading and writing to the same tty at the same time?

**Comment by niklasmohrin** [comment]
@sharkdp Everything is set, I opened #1398 to sync up with my changes on the `clircle` repository. I have some ideas for little additions over there too, but you can also merge if you want :sweat_smile:
