### ISSUE TITLE
Add --diagnostic option to bat itself

### ISSUE THREAD

**Issue by xerus2000** [sharkdp/bat#1405]
The bug report issue templates asks to run https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh or add the Windows version, as well as add the bat version. It would be much easier to have a `--diagnostic` command in bat directly, like e.g. `jrnl` has it:
```
❯ jrnl --diagnostic
jrnl: v2.4.5
Python: 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
OS: Linux 5.9.10-arch1-1
```

**Comment by sharkdp** [comment]
Yes. I have been thinking about a command-line option like this for a while, and I believe that's a great idea. Thanks for writing it down.

Advantages over the existing shell script:
- cross-platform
- much easier for the user to execute
- direct access to the `bat` config file, environment variables etc. that `bat` *actually sees* when executed
- possibility to also print out additional command line arguments that might have been passed via an alias (e.g. running `bat --diagnostic` with `alias bat="bat --theme=1337"`) or a shell function. This will work independent from the shell. No need to have bash/zsh/fish-specific code.

Disadvantages:
- Adds some dependencies, most probably

**Comment by sharkdp** [comment]
I am working on this

**Comment by eth-p** [comment]
Any ideas for how we can detect the shell aliases from within bat? Or will the original script still be needed?

**Comment by sharkdp** [comment]
> Any ideas for how we can detect the shell aliases from within bat? Or will the original script still be needed?

I was hoping that alias and wrapper detection would not be needed anymore. As I understand it, we mostly want this to see if a user has set something like
```bash
alias bat="bat --pager='less --some-weird-option'"
```

If that user then notices an error when running `bat -p somefile.rb`, we will ask him/her to add the `--diagnostic` option:
```
bat -p somefile.rb --diagnostic
```

My current implementation then simply looks at all command-line options and would generate a report like this:

---

## Software version

bat 0.17.1

## Operating system

Linux 5.9.1-arch1-1

## Command-line

```bash
bat '--pager=less --some-weird-option' -p somefile.rb --diagnostic 
```

## Environment variables

```PAGER=less
BAT_PAGER=<not set>
BAT_CONFIG_PATH=<not set>
BAT_STYLE=<not set>
BAT_THEME=<not set>
BAT_TABS=<not set>

```

---

We would not be able to see which command-line options came from the alias and which were passed on the command-line, but the user would probably tell us that `bat -p somefile.rb` doesn't work.

What do you think? Are there other situations where alias/wrapper detection would still be helpful?

**Comment by sharkdp** [comment]
There are some nice ideas in `git bugreport` that we could implement as well.
