### ISSUE TITLE
zsh-completions collection

### ISSUE THREAD

**Issue by xyproto** [sharkdp/bat#1406]
If the syntax completion file for Zsh is **removed** from `bat`, it may be included in the `zsh-completions` collection:

See: https://github.com/zsh-users/zsh-completions/pull/770

The `zsh-completions` package on Arch Linux is based on this repository, and is where users can normally get their Zsh completion files. It's also used by: Debian, Ubuntu, Fedora, CentOS, RHEL, Scientific Linux, OpenSUSE, Manjaro, Antergos, Hyperbola, Gentoo, Funtoo, NixOS, Void Linux, Slackware, macOS/Homebrew, NetBSD and FreeBSD.

I know it's a bit counter-intuitive, but please consider removing it.

**Comment by sharkdp** [comment]
@xyproto Thank you for reporting this.

@xzfc @Kienyew @mjturner Could one of you maybe help out with this / comment on this? I'd be fine with this.

**Comment by Kienyew** [comment]
Provided the packaging of `bat` is done right, the completion should be also installed when user installing `bat` package from the official repository, and I thought the `zsh-completions` main objective is to provide completions which is not already exists in official zsh or upstream project. There's a *Including Completion Functions in Upstream Projects* section in [contribution guide of zsh-completions](https://github.com/zsh-users/zsh-completions/blob/master/CONTRIBUTING.md) about completion in upstream.

So in my opinion, if we already provide completion in here, we should keep mantaining here.

Of course, if it's ok with others, I'm willing to help out to remove it from this project.

**Comment by sharkdp** [comment]
@xyproto any response to that?

**Comment by xyproto** [comment]
@sharkdp

It is not my decision if you wish to include zsh completions in the very popular zsh-completions package or not.

All I can do is quote the zsh-completions guidelines:

> Contributions are welcome, just make sure you follow the guidelines:
> 
>     Completions are not accepted when already available in zsh.
>     Completions are not accepted when already available in their original project.

If this was a project I could decide over, I would think it was a good thing to have the completion file distributed in the `zsh-completions` package, maybe even hoping that it would one day be included directly in zsh.

"Done right" is mostly a matter of users being able to install and use the packages they need and want and get the desired results, and it should not matter much where the file is placed, IMO.

Having the zsh completions for Bat distributed to many distros and operating systems, as part of the zsh-completions package, sounds nice, to me.

**Comment by sharkdp** [comment]
> Provided the packaging of `bat` is done right, the completion should be also installed when user installing `bat` package from the official repository, and I thought the `zsh-completions` main objective is to provide completions which is not already exists in official zsh or upstream project.

I think I'm going to side with @Kienyew here. I don't really see any advantage of having the completions file in `zsh-completions` if we already ship it with `bat`. It's easier to maintain in one place here. It's not like the file is going to be useful to anyone if they don't have `bat` installed.

Closing this for now. @xyproto If this is the wrong decision, please let us know what the advantages would be.

**Comment by xyproto** [comment]
I guess the main advantage is for package maintainers. Just like it's handy for `make` to not do anything surprising, it is handy if a package requires approximately the same steps as other, similar packages.
