### ISSUE TITLE
Can't use `bat` at all! (Error: Use of bat as a pager is disallowed...)

### ISSUE THREAD

**Issue by cansurmeli** [sharkdp/bat#1413]
**What version of `bat` are you using?**
bat 0.17.1

**Describe the bug you encountered:**

Whenever I use `bat`, I'm shown the following error message:

> [bat error]: Use of bat as a pager is disallowed in order to avoid infinite recursion problems

I believe this started happening after a certain update but can't exactly pinpoint which one. I've uninstalled and reinstalled `bat` again but with no luck.

**What did you expect to happen instead?**
For `bat` to display the contents as usual.

**How did you install `bat`?**
Homebrew

---

system
------

**$ uname -srm**
Darwin 20.1.0 x86_64  

**$ sw_vers**
ProductName:	macOS  
ProductVersion:	11.0.1  
BuildVersion:	20B29  

bat
---

**$ bat --version**
bat 0.17.1  

**$ env**
PAGER=bat  

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)

**Comment by sudo-nice** [comment]
That's intentional, see https://github.com/sharkdp/bat/pull/1343
Personally, I don't like this restriction too (but it's not hard to overcome).

**Comment by sharkdp** [comment]
> That's intentional, see #1343

Hm. Kind of, but not to the extent documented here, actually. What we really want to avoid is infinite recursion (`bat` calls `bat` as pager, which calls `bat` as pager, …). See #1334.

What I didn't foresee is that users want to set `PAGER=bat` to use `bat` in as a pager itself.

So what we probably should do instead:
- Allow `PAGER=bat`, but ignore the setting in `bat` and simply default to `less`. Unless of course, `BAT_PAGER` or `--pager` is used to overwrite the value of `PAGER`.
- Disallow the usage of `bat` within `BAT_PAGER` and `--pager`.

**Comment by Enselic** [comment]
@cansurmeli Before the fix is out, as a workaround, you can pass `--paging=never` to bat.

I.e. this fails in 0.17.1:
`PAGER=bat bat file.txt`

But this works:
`PAGER=bat bat --paging=never file.txt`

**Comment by sharkdp** [comment]
Another workaround would be to use `--pager="less -FRX"`. You can also add that line to the `bat`s config file.

**Comment by Enselic** [comment]
@sharkdp Did you see my PR with `PagerSource`? Seems to me as if that approach could be useful to implement the behavior you propose.

**Comment by Enselic** [comment]
I will happily fix this bug once #1402 is merged, because it should be very simple, assuming the current refactoring proposal in that PR survives code review.

**Comment by sharkdp** [comment]
Bugfix released in [bat v0.18](https://github.com/sharkdp/bat/releases/tag/v0.18.0).
