### ISSUE TITLE
copy without line numbers

### ISSUE THREAD

**Issue by Dowwie** [sharkdp/bat#142]
I've found that I can use tmux to select and copy while in "bat mode" (batting a file?).  However, tmux copies all text, including line numbers.  This approach is almost satisfactory.  Ideally, I would be able to select and copy only contents and not line numbers.  Is there an alternative approach to what I'm doing?

**Comment by ghuls** [comment]
@Dowwie 
I guess you can use:
```
bat --style header,changes,grid your_file.txt
```

**Comment by Dowwie** [comment]
The --style argument doesn't seem to work.  I tried to reinstall bat and get 0.2.3 from cargo.  This is the error:

 error: Found argument '--style' which wasn't expected, or isn't valid in this context

**Comment by Dowwie** [comment]
``bat --style plain file.rs `` did the trick!  I also had to upgrade to the 0.3.0 deb. Thank you!
