### ISSUE TITLE
Bat doesn't work when installed from apt on Ubuntu

### ISSUE THREAD

**Issue by marimeireles** [sharkdp/bat#1420]
**What version of `bat` are you using?**
The one available on `apt`.

**Describe the bug you encountered:**
When I `sudo apt install bat` the installation works as expected, but when I `bat` I get:
```
zsh: command not found: bat
```

```
system
------

**$ uname -srm**
Linux 5.4.0-53-generic x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID:	Ubuntu  
Description:	Ubuntu 20.04.1 LTS  
Release:	20.04  
Codename:	focal  

bat
---

**$ bat --version**
bat 0.17.1  

**$ env**
PAGER=less  

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 551 (GNU regular expressions)  
```

**Comment by marimeireles** [comment]
It works when I install it from source.

**Comment by keith-hall** [comment]
https://github.com/sharkdp/bat#on-ubuntu-using-apt

> If you install bat this way, please note that the executable may be installed as batcat instead of bat (due to a name clash with another package). You can set up a bat -> batcat symlink or alias to prevent any issues that may come up because of this and to be consistent with other distributions:

```sh
mkdir -p ~/.local/bin
ln -s /usr/bin/batcat ~/.local/bin/bat
```

**Comment by marimeireles** [comment]
That was my problem! Sorry for the issue.
Might be worth it adding to the readme as a footnote?
Thanks!

**Comment by atharvadnaik** [comment]
just try batcat command instead of bat.

**Comment by sharkdp** [comment]
@marimeireles Do you think we could improve the documentation to prevent this confusion in the future? Maybe we can highlight or move that part in the documentation to make it more visible?

**Comment by marimeireles** [comment]
Oh, no, it was my fault. I was super inattentive like twice.
IMO we can close this.
Thanks for the help @sharkdp :)

**Comment by sharkdp** [comment]
It did happen to many others as well. I added "Important:" in the README :smile:

**Comment by tanuj-05** [comment]
> https://github.com/sharkdp/bat#on-ubuntu-using-apt
> 
> > If you install bat this way, please note that the executable may be installed as batcat instead of bat (due to a name clash with another package). You can set up a bat -> batcat symlink or alias to prevent any issues that may come up because of this and to be consistent with other distributions:
> 
> ```shell
> mkdir -p ~/.local/bin
> ln -s /usr/bin/batcat ~/.local/bin/bat
> ```

I ran these commands but I am still not able to use 'bat'. Only batcat works. Any help will be much appreciated, thanks !

**Comment by mehdiMj-ir** [comment]
> > https://github.com/sharkdp/bat#on-ubuntu-using-apt
> > > If you install bat this way, please note that the executable may be installed as batcat instead of bat (due to a name clash with another package). You can set up a bat -> batcat symlink or alias to prevent any issues that may come up because of this and to be consistent with other distributions:
> > 
> > 
> > ```shell
> > mkdir -p ~/.local/bin
> > ln -s /usr/bin/batcat ~/.local/bin/bat
> > ```
> 
> I ran these commands but I am still not able to use 'bat'. Only batcat works. Any help will be much appreciated, thanks !

You could `alias` it on `.bashrc` or `.zshrc` like this ->

`alias bat='batcat'`

**Comment by tanuj-05** [comment]
> > > https://github.com/sharkdp/bat#on-ubuntu-using-apt
> > > > If you install bat this way, please note that the executable may be installed as batcat instead of bat (due to a name clash with another package). You can set up a bat -> batcat symlink or alias to prevent any issues that may come up because of this and to be consistent with other distributions:
> > > 
> > > 
> > > ```shell
> > > mkdir -p ~/.local/bin
> > > ln -s /usr/bin/batcat ~/.local/bin/bat
> > > ```
> > 
> > 
> > I ran these commands but I am still not able to use 'bat'. Only batcat works. Any help will be much appreciated, thanks !
> 
> You could `alias` it on `.bashrc` or `.zshrc` like this ->
> 
> `alias bat='batcat'`

Thanks!

**Comment by mnpenner** [comment]
I like to put it in `~/usr/local/bin` instead of my home dir.

```sh
sudo ln -s /usr/bin/batcat /usr/local/bin/bat
```

**Comment by DrPepperBianco** [comment]
Why is this issue closed? - The problem is not solved. Only a workaround is presented here.

I installed bat via 'apt'. If I then call 'man bat' the documentation clearly states, that the command is 'bat' not 'batcat'!

I'm very confused by that. The solution works, but obviously has to be done by every user. Why isn't this done automatically on install? (Does this have to do with name collissions?)

**Comment by sharkdp** [comment]
This is not something that we control. Please read the documentation here: https://github.com/sharkdp/bat#on-ubuntu-using-apt
