### ISSUE TITLE
how do i run bat when installed from snap

### ISSUE THREAD

**Issue by jack99999** [sharkdp/bat#1424]
i just installed the batcat snap on linux mint 19.3.

how do i run it? i see i have `/snap/bin/batcat.batwing`

i expected to have a bat or batcat in /snap/bin, since /snap/bin is on my path. other programs (such as rg) seem to have the appropriate name installed in that directory. 

anyway, i tried:
`/snap/bin/batcat.batwing /tmp/fred.txt`
`[bat error]: '/tmp/fred.txt': No such file or directory (os error 2)`

i looked around and found that this works, but is obviously the wrong thing to do:

` /snap/batcat/current/bin/bat  /tmp/fred.txt`

what have i done wrong?

jack

**Comment by sharkdp** [comment]
FYI @purveshpatel511

**Comment by purveshpatel511** [comment]
sorry @jack99999, there was some package release error in snapstore that is fixed now.

For using `batcat` you have to refresh that package by running this command.
```
sudo snap refresh batcat
```

And for use, you have to type `batcat` insted of `bat`.

@sharkdp, you can close this issue now. Re-open it if needed.
Thanks for support.

**Comment by jack99999** [comment]
aha. yes, working now.

except, fwiw, i see i have:

`> batcat /tmp/fred.txt`
`[bat error]: '/tmp/fred.txt': No such file or directory (os error 2)`

and that seems to be snap permissions. if i run it on a file in my own directory it's ok. i can give the snap the appropriate permission... done it before for something or other... anyway, could perhaps be worth a note in the installation for those who might want to use it for files that are not in their own directories?

thanks

**Comment by purveshpatel511** [comment]
This snap doesn't have `classic` confinement, it published under `strict` confinement. Only classic confinement snap can access `root` directory files. For releasing snap in classic confinement, it has pass manual snap check. 

I will put a request for classic confinement from snapstore. Once i get that then i will publish this snap in classic.

For now, if you want to use classic snap then download it from my [release page](https://github.com/purveshpatel511/batwing/releases/tag/v0.17.1) named `batcat_0.17.1_amd64_classic.snap` .

Install this snap by running following command,
```
sudo snap install batcat_0.17.1_amd64_classic.snap --dangerous --classic
```

After Installing this snap, you will be able to access your `root` directory files.

**Comment by jack99999** [comment]
ah. i should have read your message before i tried and failed.

that works perfectly. 

many thanks

**Comment by jmcvaughn** [comment]
Just to provide an easy alternative: you can simply install the snap from the Snap Store using `--devmode`:

```
sudo snap install batcat --devmode
```

Snap won't be confined, won't update.

**Comment by purveshpatel511** [comment]
@jmcvaughn, Yeah, right man. I don't know about that trick. Thanks a lot.

**Comment by jack99999** [comment]
that will certainly be helpful for other snaps.

many thanks

jack
nothing recedes like success
