### ISSUE TITLE
Didn't respect less with --LONG-PROMPT

### ISSUE THREAD

**Issue by kevinhwang91** [sharkdp/bat#1427]
system
------

**$ uname -srm**
Linux 5.4.81-1-lts x86_64

**$ lsb_release -a**
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

bat
---

**$ bat --version**
bat 0.17.1

**$ env**
BAT_THEME=TwoDark
BAT_STYLE=plain

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 563 (PCRE regular expressions)

**Describe the bug you encountered:**
1. `bat --pager "less -M" foo`
2. prompt display: `lines 1-xx`

**What did you expect to happen instead?**
prompt display: `foo lines 1-xx/yy zz%`

**Comment by sharkdp** [comment]
Thank you for reporting this. I can reproduce it.

I don't think that's a problem with `bat`. Try running `cat … | less -M`. It will also not show the long prompt, right? Only if I scroll the the very end of the file and then go backwards. The same works for `bat`.

You can run something like
```
strace -f bat --pager "less -M" Cargo.toml 2> strace.log
```
to verify that `bat` is indeed calling `less -M`:
```strace
[pid 824456] execve("/usr/bin/less", ["less", "-M"], 0x5599b70ef290 /* 66 vars */ <unfinished ...>
```

**Comment by kevinhwang91** [comment]
Thanks for your explanation, seemly long prompt only works on files instead of standard input.
