### ISSUE TITLE
Bat not autocorrect with zsh like cat

### ISSUE THREAD

**Issue by trankchung** [sharkdp/bat#1428]
**What version of `bat` are you using?**
bat 0.17.1

**Describe the bug you encountered:**
Bat does not autocorrect file names like cat when using in zsh shell. In zsh shell, when catting a file named `my_regular_file.txt`, a user can just type `cat regular[TAB]` and it'll autocorrect to that file. Bat does not do that. Bat requires the start of a file name to be typed first.

**What did you expect to happen instead?**
Bat to autocorrectly choose the file when any part of the filename is typed.

**How did you install `bat`?**
pacman

**Comment by Enselic** [comment]
The behavior you describe does not work with with `cat` either out of the box with `zsh`. You must have some custom `zsh` setup code somewhere that enables it for `cat`. To that code, try adding `compdef bat=cat`. That made it work for me (after enabling the behavior for `cat` with the custom code I found [here](https://unix.stackexchange.com/a/259511))

I don't quite see how this is a `bat` bug though.

**Comment by trankchung** [comment]
Thanks @Enselic. I use oh-my-zsh so I'll see if I can see what configuration that is.
