### ISSUE TITLE
Feature Request: A "Recursive" Flag a la `rm -r`

### ISSUE THREAD

**Issue by kfrncs** [sharkdp/bat#1429]
I _love_ Bat. Thank you so much for everyone who's making this. It's a joy. 

A useful feature for me would be an `-r` tag when calling, similar to how `rm -r` works. For example:
`bat -r *.rs`

This would show all Rust files in a project directory, x levels deep. `*/*/*/*` won't show files 3 or 2 directories deep, etc. With large projects this would help me navigate in the terminal immensely, and I have a feeling it would be very quick.

This may serve as a note to myself to implement this, but currently I don't have the time. If someone ends up getting there first, I would be very happy. Thanks.

**Comment by keith-hall** [comment]
Thanks for the feedback. I'm not at a computer right now to check myself, but it might be worth trying with a glob like `**/*. rs` to see if that works without any development effort required. :)

**Comment by kfrncs** [comment]
Ah! Even better. TIL
