### ISSUE TITLE
Language used for bat help

### ISSUE THREAD

**Issue by psicho2000** [sharkdp/bat#1430]
I really like the syntax coloring of `bat -h` / `bat --help`. Which language is it and is it available to be used?

**Comment by j0hnmeow** [comment]
> I really like the syntax coloring of `bat -h` / `bat --help`. Which language is it and is it available to be used?

It's `clap`'s [`AppSettings::ColoredHelp`](https://docs.rs/clap/2.33.3/clap/enum.AppSettings.html#variant.ColoredHelp) setting

**Comment by psicho2000** [comment]
Thanks for the answer. So it is programmatically colorized. I hoped that bat is using it's own mechanism in some way, so that it is reusable via CLI.
I'll create a specific sublime-syntax file to achieve that.

**Comment by sharkdp** [comment]
>  I'll create a specific sublime-syntax file to achieve that.

Our "Man" syntax actually does something similar (highlight command-line options like `--pager=never`). Maybe you can use that as a starting point.

My understanding is that you want to do something like:
```
ls --help | bat -l help
```
to see colored help text for commands that do not support it?

**Comment by psicho2000** [comment]
@sharkdp: yes, `ls --help | bat -l help` is exactly what I want. The man coloring is just not enough for me. I saw the coloring you are using for bat's own help, which is simply great. I'd like to use that everywhere :)

**Comment by keith-hall** [comment]
I tried using the Manpage syntax to highlight `bat`s own `--help` (as an experiment - just invoking `bat --help | bat -l Manpage`), and I would say it worked fairly well - better than `clap` even IMO. ;)

Can you suggest anything concrete with how to improve it for other cases like `ls --help`? (i.e. what about it specifically do you not like at the moment?) I guess the main problem is that any unindented text is colored? We could perhaps make a new syntax which just calls into the relevant part of the Manpage syntax definition, to avoid that.

**Comment by psicho2000** [comment]
Man syntax colorizes the headings. That's good for a start. Clap goes further and also colorizes the options, making them clearer visible. That's what I want to achieve.

**Comment by keith-hall** [comment]
Maybe let's double check we're both seeing the same thing :)

`ls --help | target/release/bat -l Manpage --plain`

![image](https://user-images.githubusercontent.com/11882719/102405631-21678500-3ff2-11eb-9c98-2436d82e0404.png)

**Comment by psicho2000** [comment]
@keith-hall: thanks for pointing that out! I was not aware that my distro (Ubuntu 20.04, providing bat 0.12.1) is ages beyond the latest bat release.

After manually installing the release from this repo I get the same results. This is exactly what I want. So case closed!

**Comment by psicho2000** [comment]
I just noticed I installed Batman...
