### ISSUE TITLE
input_from_bytes_with_name replacement?

### ISSUE THREAD

**Issue by fdncred** [sharkdp/bat#1432]
Since `input_from_bytes_with_name` is deprecated, what should we use as a replacement?

**Comment by sharkdp** [comment]
You can use:
```rust
    .input(Input::from_bytes(&bytes).name("person.yaml").kind("File"))
```

See for example: https://github.com/sharkdp/bat/blob/f3489ffa29e8851a289dd86e7f67d504cb3223a2/examples/yaml.rs#L32
