### ISSUE TITLE
bat as an alias is not accessible to man page when default shell is zsh

### ISSUE THREAD

**Issue by MikeyBeez** [sharkdp/bat#1434]
**What version of `bat` are you using?**
[paste the output of `bat --version` here]

**Describe the bug you encountered:**
...

**What did you expect to happen instead?**
...export MANPAGER="sh -c 'col -bx | bat -l man -p'"
does not work because bat has not yet been defined in bash shell.  Use this instead:
export MANPAGER="sh -c 'col -bx | batcat -l man -p'"

**How did you install `bat`?**

---

[paste the output of `info.sh` here]

**Comment by sharkdp** [comment]
Thank you for reporting this.

You are suggesting that we improve the documentation for Ubuntu users that have a `batcat` binary instead of a `bat` binary? (see also: https://github.com/sharkdp/bat#on-ubuntu-using-apt)

**Comment by MikeyBeez** [comment]
Yes, just change the readme to call for batcat rather than bat.  That way it will work for z shell too.

**Comment by MikeyBeez** [comment]
You make an alias in .bshrc for batcat to bat, but you don't do this in .zshrc.  The simple solution is to call the executable and not the alias.

**Comment by sharkdp** [comment]
I re-opened this to remember that we need to update the documentation.
