### ISSUE TITLE
how can I specify file type of stdin , the bat's output without syntax highlighting

### ISSUE THREAD

**Issue by rmGFW** [sharkdp/bat#1435]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/66858140/102318473-57861400-3fb4-11eb-8c32-78a555a4f523.png">

I hope the shell script function can output with syntax highlighting

**Comment by eth-p** [comment]
If your version of bat supports `--file-name name.txt`, it should be able to infer the language from the file extension.

**Comment by sharkdp** [comment]
I guess @rmGFW *wants* syntax highlighting? In that case, specify a file name with `.sh` extension, or use the `-l` option:
```
… | bat -lsh
```
