### ISSUE TITLE
Newlines added and removed from one bat call to another on Windows 10

### ISSUE THREAD

**Issue by Melandel** [sharkdp/bat#1436]
Hi!
❤️ Love the project! ❤️ 

I've been wanting to use `bat 0.17.0`, installed from `GitHub releases`, on `Windows 10 Home v19041.685` but I keep witnessing an arcane behaviour that is a bit annoying.

**Steps to reproduce:**
- open `cmd.exe`
- create a new file: `echo 'hello world!' > foo.txt`
- for the fun of it, add another line: `echo bat is awesome! >> foo.txt`
- clear the screen: `cls`
- run bat: `bat --style=plain foo.txt`
- run bat again: `bat --style=plain foo.txt`
- and one more time: `bat --style=plain foo.txt`

**Actual behavior:**
- the 3 outputs are all different (do take your time to spot all the differences)
![image](https://user-images.githubusercontent.com/48007894/102339777-f51e1b00-3f95-11eb-8024-f832cb267aac.png)

**Expected behavior:**
- the 3 output are all the same

**Additional notes:**
- Do note that the first call always puts the previewed text at the bottom of the screen, create a large amount of space above the previewed text, while the other calls put the previewed text directly under the prompt. I don't know if what the expected behaviour is unfortunately....
- Running `cls` every time might be a workaround
- In order to have bat display the correct characters, I set my output encoding to utf-8 following [these](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096) instructions
- You are all great, nice, and worth a lot of love!

**More examples:**
- here's another example, using `bat --style=plain foo.txt` instead
![image](https://user-images.githubusercontent.com/48007894/102341043-948fdd80-3f97-11eb-9b74-e0daeb58f081.png)

- here's another example with a different file:
![image](https://user-images.githubusercontent.com/48007894/102340803-3c58db80-3f97-11eb-880a-888104c03187.png)

**Comment by Melandel** [comment]
Deactivating the paging got rid of my problem.

However, I really thing it would be good to have no paging by default on Windows.

**Comment by atharvadnaik** [comment]
In my case, 
1) When I created foo.txt using powershell,
On kali-rolling wsl, bat(v 0.12.1) works perfectly and shows one space before first letter. But on windows  10, bat(v 0.17.1) doesn't show bottom line and instead of space, it shows U+FEFF (Zero Width no-break space) before first letter.
![bat_issue](https://user-images.githubusercontent.com/50011593/102682538-49bcd280-41f0-11eb-9ac7-085332bb1d7a.jpg)

2) When I created foo_bash.txt using bash,
both versions don't show FFEF character and windows version still doesn't show bottom line
![bat_issue_1](https://user-images.githubusercontent.com/50011593/102682803-3d397980-41f2-11eb-9a68-2f86d244b269.jpg)

**Comment by sharkdp** [comment]
Thank you for reporting this. Related to #1384?

**Comment by sharkdp** [comment]
@Melandel 

Could you please try out the latest master of `bat` ([bat-8e4b0b43-x86_64-pc-windows-gnu.zip.zip](https://github.com/sharkdp/bat/files/5791724/bat-8e4b0b43-x86_64-pc-windows-gnu.zip.zip)) and then post the output of
```
bat --style=plain foo.txt --diagnostic
```
?

**Comment by Melandel** [comment]
Uh oh.

```
C:\Users\XXX\Desktop>bat --style=plain foo.txt --diagnostic
error: Found argument '--diagnostic' which wasn't expected, or isn't valid in this context

USAGE:
    bat --style <components>

For more information try --help
```

**Comment by sharkdp** [comment]
That only works with the latest master (see link in my post)

**Comment by Melandel** [comment]
My bad haha. Assumptions.

```
C:\Users\tranm\Desktop>bat --style=plain foo.txt --diagnostic
#### Software version

bat 0.17.1

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
bat --style=plain foo.txt --diagnostic
```

#### Environment variables

```bash
SHELL=<not set>
PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_PAGER=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
```

#### Config file

```
# This is `bat`s configuration file. Each line either contains a comment or
# a command-line option that you want to pass to `bat` by default. You can
# run `bat --help` to get a list of all possible configuration options.

# Specify desired highlighting theme (e.g. "TwoDark"). Run `bat --list-themes`
# for a list of all available themes
#--theme="TwoDark"

# Enable this to use italic text on the terminal. This is not supported on all
# terminal emulators (like tmux, by default):
#--italic-text=always

# Uncomment the following line to disable automatic paging:
# On Windows, the pager doesn't handle colors
--paging=never

# Uncomment the following line if you are using less version >= 551 and want to
# enable mouse scrolling support in `bat` when running inside tmux. This might
# disable text selection, unless you press shift.
#--pager="less --RAW-CONTROL-CHARS --quit-if-one-screen --mouse"

# Syntax mappings: map a certain filename pattern to a language.
#   Example 1: use the C++ syntax for .ino files
#   Example 2: Use ".gitignore"-style highlighting for ".ignore" files
#--map-syntax "*.ino:C++"
#--map-syntax ".ignore:Git Ignore"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-gnu
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```
> less --version
less 394
Copyright (C) 1984-2005 Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```


Damn. I see what you did there. Mad respect.

**Comment by sharkdp** [comment]
> `> less --version less 394 Copyright (C) 1984-2005 Mark Nudelman`

Oh wow :smile:. That version is antique!

Please make sure to install a recent version of `less`: https://github.com/sharkdp/bat#paging

**Comment by Melandel** [comment]
woah. I always resorted to going to some arcane spot on the powershell community module or something for that lol.

Thanks for the tip!

**Comment by Melandel** [comment]
![image](https://user-images.githubusercontent.com/48007894/104249027-ea5a8700-546a-11eb-8c06-8daeaa8eef1b.png)

Seems to work well now!
Sorry for the trouble - thank you for your time, you're awesome!
