### ISSUE TITLE
extra themes help text to stderr

### ISSUE THREAD

**Issue by rsteube** [sharkdp/bat#1437]
Can the help text for `--list-themes` from #1353 be written to stderr?
I'm using the command to retrieve themes for [completion](https://github.com/rsteube/carapace-bin/blob/master/completers/bat_completer/cmd/root.go#L86) and that interfers a bit.

**Comment by sharkdp** [comment]
Thank you for reporting this. I should have paid more attention in the review.

> Can the help text for --list-themes from #1353 be written to stderr?

I think even better would be to disable this help text when we are not printing to an interactive terminal.
We already print a different version in that case (only a list of the names). We probably just have to move the `writeln!(…)` call up into the `if config.colored_output { … }` block

**Comment by sharkdp** [comment]
Bugfix released in [bat v0.18](https://github.com/sharkdp/bat/releases/tag/v0.18.0).
