### ISSUE TITLE
Newline can be added even if --style=plain

### ISSUE THREAD

**Issue by Enselic** [sharkdp/bat#1438]
In #975 @sharkdp said this:

> The fact that bat -p prints a trailing newline (even if there is no newline at the end of the file) should be considered a bug, I believe (but we should check older tickets, if there was a reason for this behavior).

And I completely agree. The reason the artificial newline was added in the first place was to fix #299, but there should be no risk of regressions since --style=plain excludes any kind of decorations that bug was about.

Note that a pager such as `less` will add an artificial newline too, so one either has to disable paging or use a "pager" that does not add a newline to get the benefit of fixing this bug.

**Step-by-step:**
1.  echo -n nonewline > nonewline.txt
2. bat --style=plain --paging=never nonewline.txt
3. bat --style=plain --pager=cat nonewline.txt

**Expected result:**
After 2. and 3. the line shall not contain a newline. I personally use `zsh` to check this since by default `zsh` will print e.g. `%` as the last char if there is a missing newline.

**Actual result:**
A newline is printed with `bat 0.17.1`.

(I will soon open a PR with a proposed fix)

**Comment by sharkdp** [comment]
Thank you for taking the time to write this down in detail!

**Comment by sharkdp** [comment]
Bugfix released in [bat v0.18](https://github.com/sharkdp/bat/releases/tag/v0.18.0).
