### ISSUE TITLE
Question: Setting up customization

### ISSUE THREAD

**Issue by jkaan** [sharkdp/bat#144]
I followed the instructions to customise bat that are in the README.md under the heading 'Customization'.

But once I run `bat --list-languages` the only language that I see is `Plain text`. I am following exactly what is stated in the readme.

Using version 0.3.0 as well. :)

**Comment by sharkdp** [comment]
We recently changed the folder name from `syntax` to `syntaxes`. Version 0.3.0 still works with the `syntax` folder. The README refers to the current `master` version.

Could you try to either (a) use `bat` master or (b) name the folder `syntax` instead of `syntaxes`?

**Comment by jkaan** [comment]
@sharkdp Thanks for the super fast response and using Version 0.3.0 with `syntax` works (as expected of course). Sincerely thanks for this awesome tool!

**Comment by sharkdp** [comment]
v0.4 is out now. Be sure to rename the folder to `syntaxes` now.
