### ISSUE TITLE
Create documentation for reporting security issues.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#1473]
We currently don't have an official process for reporting security issues. I'm glad that Ry0taK went out of the way to directly ask us for contact information, but I'm concerned that other people might not be as willing to ask if they ever uncover similar issues.

I think it would be a good idea for us to add a `SECURITY.MD` file which describes how to contact us to confidentially report possible security vulnerabilities. GitHub itself considers that file to be the project's "Security Policy", and it should show up somewhere on the GitHub repo for `bat`.

 I'm willing to put my email up publicly for this purpose, but I'm not the biggest fan of that solution (spam mail). If anyone here has some suggestions on alternatives to reporting confidential issues via email, this would probably be a good place to discuss them.

**Comment by keith-hall** [comment]
As we have a discord "server" for this project, we could perhaps encourage people to PM us there with security issues?
