### ISSUE TITLE
Simplify, refactor and clean up our GitHub Actions script

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#1474]
@rivy has done a great job of providing a GitHub Actions configuration for `bat`:

- [`/.github/workflows/CICD.yml`](https://github.com/sharkdp/bat/blob/master/.github/workflows/CICD.yml)
- [Latest run on `master`](https://github.com/sharkdp/bat/actions/runs/458760265)

It works great (both for CI as well as for CD) and is a huge improvement over our previous Travis+Appveyor setup. However, I can't help but feel that it could be improved.

As for myself, I am currently starting to get into GitHub Actions (somewhat involuntarily because I need to move a lot of my projects away from Travis CI). So I would really appreciate some help. Here are some ideas:

- [x] ~~The whole Debian-package stuff feels like it should be in a separate GitHub action that we could re-use here.~~ (removed for now, see below)
- [x] The following section is particularly hard to understand and contains a lot of duplication: https://github.com/sharkdp/bat/blob/4fe5497d19914c6d912b3cc4586134981b186b3b/.github/workflows/CICD.yml#L109-L210
- [x] The naming of the build jobs and the naming of some steps in the process could be improved, in order to make it easier to find something in the CI output.
- [x] It seems like we are unnecessarily(?) using the full `cross`-compiling toolchain for builds that are native to the host OS: https://github.com/sharkdp/bat/blob/4fe5497d19914c6d912b3cc4586134981b186b3b/.github/workflows/CICD.yml#L86-L98 This should be checked.
- [x] We are currently not using the code coverage part. This is mainly because we deactivated the automatic posting of coverage results in the PR (which I don't really want to re-activate with the full output). Maybe someone has an idea on how to improve this situation.

Any help - especially in the form of *small* PRs that are easy to review for me as a beginner - would be very much appreciated!

**Comment by Enselic** [comment]
Now that the second bullet point is checked, I thought it would be good time to elaborate a bit on the remaining points, and perhaps reconsider the importance of them.

- The whole Debian-package stuff

I took a [quick look](https://github.com/marketplace?type=actions&query=debian) but could not find any mature GitHub Action for creating Debian packages. Now that the Debian Package is its own step, I personally do not think it is a pain point any longer. It's pretty straightforward what it does, and it gives us a lot of flexibility to have it setup the way it is.

So my recommendation is to remove this bullet point from the list. (Or at least not have have it in a position as prominent as in a pinned issue.)

- The naming of the build jobs and the naming of some steps

I don't find the current names to be terrible. They could probably be improved, but in what way? Could you perhaps exemplify or elaborate a bit on what concerns you have with the current names?

- We are currently not using the code coverage part.

From what I can tell, good code coverage support is still a [nightly feature](https://blog.rust-lang.org/inside-rust/2020/11/12/source-based-code-coverage.html). So even if we get it to work for now, chances are high that it will stop working again soon, unless it is continuously maintained. I am personally not super keen on spending my limited spare time keeping Code Coverage in check. But maybe someone else is :)

Question is if it is important enough to be part of a pinned issue, though?

Looking forward to your thoughts on these matters!

**Comment by sharkdp** [comment]
>     * The whole Debian-package stuff
> 
> 
> I took a [quick look](https://github.com/marketplace?type=actions&query=debian) but could not find any mature GitHub Action for creating Debian packages. Now that the Debian Package is its own step, I personally do not think it is a pain point any longer. It's pretty straightforward what it does, and it gives us a lot of flexibility to have it setup the way it is. Plus, it is easy for Debian-knowledgeable contributors to tweak it, since it uses regular Debian dpkg tools.

Ok, agreed. I guess the main reason for moving this out to an external GitHub action was rather selfish: I have a bunch of other Rust projects that I still need to migrate from Travis CI / Appveyor to GitHub actions. Having a single GitHub action that all projects could profit from would be fantastic. But that might not be the best choice for `bat` alone.

> So my recommendation is to remove this bullet point from the list. (Or at least not have have it in a position as prominent as in a pinned issue.)

Ok. Let's remove it for now.

>     * The naming of the build jobs and the naming of some steps
> 
> 
> I don't find the current names to be terrible. They could probably be improved, but in what way? Could you perhaps exemplify or elaborate a bit on what concerns you have with the current names?

Admittedly, all of this is very nitpicky. There are no major problems.

Concerning the job names:

![image](https://user-images.githubusercontent.com/4209276/108593381-9ef19d80-7373-11eb-845d-d3b820c224f6.png)

There are some minor inconsistencies (The matrix jobs are called "Build", but they also run tests... just like the "Test …" job; The first two jobs have a completely different naming scheme) and the matrix job names are too long to fit into the sidebar. A few ideas:

- Add the min. supported Rust version to the title of the first job?
- Remove "Build" from the matrix jobs. Possibly replace `ubuntu-18.04`/`macos-10.15`/`windows-2019` by something simpler: "Linux"/"MacOS"/"Windows".

As for the stage names

https://github.com/sharkdp/bat/issues/1474
![image](https://user-images.githubusercontent.com/4209276/108608086-cae93f00-73c4-11eb-98e7-09fd83890357.png)

- "Test" / "bat test run" => Maybe "Run tests" / "Run bat"
- Strip release bin => "Strip debug information from executable"?
- What is "Calculate test options"?
- "Package" / "Debian package" => "Create tarball" / "Create Debian package"?
- "Upload package artifact" => "Upload tarball artifact"?

>     * We are currently not using the code coverage part.
> 
> 
> From what I can tell, good code coverage support is still a [nightly feature](https://blog.rust-lang.org/inside-rust/2020/11/12/source-based-code-coverage.html). So even if we get it to work for now, chances are high that it will stop working again soon, unless it is continuously maintained. I am personally not super keen on spending my limited spare time keeping Code Coverage in check. But maybe someone else is :)
> 
> Question is if it is important enough to be part of a pinned issue, though?

No, I completely agree. Let's remove it completely.

**Comment by sharkdp** [comment]
I think this issue can now be closed. The CI config has been significantly improved. Much more than I had anticipated. Thank you very much for your work, @Enselic!

This does not mean that we should stop looking for improvements, but I don't see the need for a tracking ticket right now.
