### ISSUE TITLE
semver-parser sub-dependency not compatible with current MSRV without lockfile

### ISSUE THREAD

**Issue by niklasmohrin** [sharkdp/bat#1477]
`bat` cannot be built with Rust 1.40 without passing the `--locked` flag. This is because the `semver` dependency has `semver-parser` as a dependency and this crate started using a new feature in a minor version patch (v0.10.1) that is available [only from Rust 1.44 onwards](https://github.com/steveklabnik/semver-parser/issues/52#issuecomment-719419614). The lockfile on the master branch has `semvar-parser` locked at v0.10.0 which still compiles. To reproduce, run

```shell
$ rm Cargo.lock
$ rustup default 1.40
$ cargo b
```

To eliminate this issue, the version of the sub dependency can be held in place as done [here](https://github.com/oli-obk/cargo_metadata/pull/142) or the MSRV of `bat` could be lifted to 1.44.

I encountered this problem first in [this PR](https://github.com/sharkdp/bat/pull/1398#issuecomment-754251533) where I added a new dependency and wanted to ship a fresh lockfile with the addition, but the MSRV CI runner failed due to this.

This is all assuming you see this as an issue in the first place, after all the build instructions tell you to use the `--locked` flag, as sharkdp pointed out under the aforementioned PR.

**Comment by steveklabnik** [comment]
I've pushed a new patch version of semver-parser so this should just be fixed, I believe.

**Comment by niklasmohrin** [comment]
Awesome, thank you very much! This fixes the probem without any changes needed here.

@sharkdp Should the `Cargo.toml` be updated to use version `v0.10.2` and a new lockfile be generated still?

**Comment by sharkdp** [comment]
> @sharkdp Should the `Cargo.toml` be updated to use version `v0.10.2` and a new lockfile be generated still?

That's probably a good idea - thanks!
