### ISSUE TITLE
bat v0.18.0

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#1499]
I am planning to release v0.18.0 soon.

- I went through all of the open issues and labelled a few which I would like to see in the next release: https://github.com/sharkdp/bat/milestone/8
  I added all "documentation" issues as this is something we wanted to focus on (see #1211). Apart from that, it's mostly bugfixes.

  @eth-p @keith-hall @Enselic Any other things that you would like to see in the next release?

  Note that I did *not* label everything that is already included in `master`: https://github.com/sharkdp/bat/blob/master/CHANGELOG.md#unreleased
- I think it's a good idea to make the jump to 0.18 (instead of 0.17.2) because we have two breaking changes concerning highlighting themes. This is a bit unfortunate for users of `bat`-as-a-library though. So far, we don't have any library changes that would require a minor-version bump.

**Comment by eth-p** [comment]
I'm adding #1481 to this list. That's a pretty bad performance destroying bug, and I feel like it would be more responsible for us to fix that before pushing out another release.

I already have an idea on how to fix it properly. For maintainability and cohesion reasons, I'd like to write it as an independent library crate, though. Is that okay with you @sharkdp and @keith-hall? The general idea would be to create a small ANSI escape sequence interpreter that stores the expected color and style information from all the sequences its seen, which can then re-emit them as optimized sequences.

**Comment by keith-hall** [comment]
> For maintainability and cohesion reasons, I'd like to write it as an independent library crate, though. Is that okay with you

No objections from me - only encouragement as it sounds sensible ;)

---

The milestone already covers everything I would like to be included in the next release :)

**Comment by Enselic** [comment]
Personally I just wanted to make sure #1413 was on the list since I expect to fix that soon, which it were, so no further additions from me.

**Comment by sharkdp** [comment]
> I already have an idea on how to fix it properly. For maintainability and cohesion reasons, I'd like to write it as an independent library crate, though. Is that okay with you @sharkdp and @keith-hall? The general idea would be to create a small ANSI escape sequence interpreter that stores the expected color and style information from all the sequences its seen, which can then re-emit them as optimized sequences.

Sounds like a good idea! I would, however, prefer this to be a module within this crate:
- I sounds like a pretty core component of `bat`s functionality
- I think it makes maintainability much easier, to be honest. No need to change things in two places.
- It makes it easier for package maintainers on Debian / Ubuntu and other distros where each crate is packaged separately.

That being said, if you really prefer an external crate or if we think it's really helpful for others, I'm also fine with making this a separate library.

**Comment by eth-p** [comment]
> > I already have an idea on how to fix it properly. For maintainability and cohesion reasons, I'd like to write it as an independent library crate, though. Is that okay with you @sharkdp and @keith-hall? The general idea would be to create a small ANSI escape sequence interpreter that stores the expected color and style information from all the sequences its seen, which can then re-emit them as optimized sequences.
> 
> Sounds like a good idea! I would, however, prefer this to be a module within this crate:
> 
> * I sounds like a pretty core component of `bat`s functionality
> * I think it makes maintainability much easier, to be honest. No need to change things in two places.
> * It makes it easier for package maintainers on Debian / Ubuntu and other distros where each crate is packaged separately.
> 
> That being said, if you really prefer an external crate or if we think it's really helpful for others, I'm also fine with making this a separate library.

The original idea was to make a general-purpose ANSI escape sequence optimizer that could be used by any project that might have a similar use case to us, or that might need to extract the selected foreground/background color from a series of SGR sequences.

My main concern about just adding it as a module to `bat` is that it might be a non-trivial amount of code to include directly for this purpose. I was planning on actually implementing an interpreter for the sequences, and using that to update a struct holding the expected Select Graphic Rendition state of an ANSI-compliant terminal emulator. It's likely going to require a bit of work and a ton of tests to be able to do that in a way compatible with most terminal emulators, but I'm happy to figure out the final plan for everything after I lay out the groundwork for it.

**Comment by cansurmeli** [comment]
Hey.

Any update on this? I'm looking forward to v0.18.0!

**Comment by sharkdp** [comment]
v0.18 will be released once  v0.18 will all issues in https://github.com/sharkdp/bat/milestone/8 have been resolved.

**Comment by sharkdp** [comment]
[bat v0.18.0](https://github.com/sharkdp/bat/releases/tag/v0.18.0) has been released.
