### ISSUE TITLE
Pipe image into bat gives `stream did not contain valid UTF-8`

### ISSUE THREAD

**Issue by SimenB** [sharkdp/bat#150]
`cat myimage.png | base64` works a treat. Using `bat` instead errors with `[bat error]: stream did not contain valid UTF-8`

**Comment by SimenB** [comment]
Yeah, that makes sense. Sorta matches what httpie does: https://github.com/jakubroztocil/httpie/blob/master/README.rst#binary-data

**Comment by sharkdp** [comment]
In order to start with this, I have create this small Rust library: [content_inspector](https://github.com/sharkdp/content_inspector) ([docs](https://docs.rs/content_inspector)).

**Comment by SimenB** [comment]
Sounds good!

For prosperity, see #248
