### ISSUE TITLE
/etc/resolv.conf is not highlighted with resolv syntax

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#1510]
**What version of `bat` are you using?**

latest master

**Describe the bug you encountered:**

Found this while trying to create a syntax test for resolv.conf files:

![image](https://user-images.githubusercontent.com/4209276/104136649-cda14f00-5397-11eb-8331-72ec3100a559.png)

**What did you expect to happen instead?**

`bat` automatically highlighted files called `resolv.conf` with the "resolv" syntax:
```
▶ bat -L | grep resolv        
resolv:resolv.conf
```

---

**Evironment**

#### Software version

bat 0.17.1

#### Operating system

Linux 5.10.5-arch1-1

#### Command-line

```bash
bat resolv.conf --diagnostic 
```

#### Environment variables

```bash
SHELL=/usr/bin/zsh
PAGER=less
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER="sh -c 'col -bx | bat -l man -p'"
```

#### Config file

```
# Use italic text on the terminal (not supported on all terminals)
--italic-text=always

# Syntax mappings
--map-syntax .ignore:"Git Ignore"
--map-syntax .fdignore:"Git Ignore"
--map-syntax '*.ino':"C++"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 563 (PCRE regular expressions)
Copyright (C) 1984-2020  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Comment by keith-hall** [comment]
I guess this is due to

https://github.com/sharkdp/bat/blob/30993a8bfc5c9913e7c35d225edba5fee21120f4/src/syntax_mapping.rs#L51-L55

Maybe it somehow shouldn't affect when the syntax definition matches the full filename, or the resolv.conf mapping should be added back in afterwards.
