### ISSUE TITLE
Name of man pages with dots is not fully highlighted

### ISSUE THREAD

**Issue by duongdominhchau** [sharkdp/bat#1511]
# Description
Names like `pacman.conf` or `systemd-system.conf` does not get highlighted correctly, only the part after the dot is highlighted.

![image](https://user-images.githubusercontent.com/56427890/104198492-de65c980-5458-11eb-8371-3e4096219b15.png)

Command used to produce the image above:

```bash
MANPAGER="sh -c 'col -bx | bat -l man -p'" man systemd
```

# Expected result
The whole name (e.g: `systemd-system.conf`) is highlighted instead of just the part after the dot.

# Environment
`bat` is installed using the package in Arch official repo.

`info.sh` output:

```
system
------

**$ uname -srm**
Linux 5.9.14-arch1-1 x86_64

**$ lsb_release -a**
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

bat
---

**$ bat --version**
bat 0.17.1

**$ env**
PAGER=less

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 563 (PCRE regular expressions)
```

**Comment by sharkdp** [comment]
Bugfix released in [bat v0.18](https://github.com/sharkdp/bat/releases/tag/v0.18.0).
