### ISSUE TITLE
Bat as MANPAGER not working on termux

### ISSUE THREAD

**Issue by atharvadnaik** [sharkdp/bat#1517]
**What version of `bat` are you using?**

`0.17.1`

**Describe the bug you encountered:**

After setting Bat as MANPAGER, man command gives an error.

**What did you expect to happen instead?**

Show coloured output of man page.

**How did you install `bat`**

`pkg install bat`

**Environment**

`Termux 0.101 on Android 10 (Pie)`

**Architecture**

`aarch64`

**Screenshot**
![Screenshot_2021-01-13-00-29-52-80_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/50011593/104360961-d2711a80-54df-11eb-98bb-24d5430cb01f.jpg)

**Comment by sharkdp** [comment]
While search for the "Unterminated quoted string" error message, I actually found this: https://github.com/termux/termux-packages/issues/4781 :smile: 

Same problem. Seems like termux uses a different man version that does not support complicated `MANPAGER` commands like this. A workaround is suggested in the linked ticket (build a wrapper script).

**Comment by atharvadnaik** [comment]
Thanks...I think this should be included either in README or we should write separate wiki for that. I am ready to help with this.

**Comment by sharkdp** [comment]
Including it in the README sounds great.

**Comment by paxsali** [comment]
This is a workaround:

```bash
man bash | col -bx | bat -p -l man
```

You can keep whatever `MANPAGER` you have already set and then make a function and put it in your `.bashrc`.

```bash
man() {
    command man "$@" | eval ${MANPAGER}
```

Hope that helps.
