### ISSUE TITLE
RUSTSEC-2020-0053: dirs: dirs is unmaintained, use dirs-next instead

### ISSUE THREAD

**Issue by brightly-salty** [sharkdp/bat#1521]
When `cargo-audit` is run on any crate that depends directly or indirectly on bat, the following is output (for more info, see https://rustsec.org/advisories/RUSTSEC-2020-0053):

```
Crate:         dirs
Version:       3.0.1
Warning:       unmaintained
Title:         dirs is unmaintained, use dirs-next instead
Date:          2020-10-16
ID:            RUSTSEC-2020-0053
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0053
Dependency tree:
dirs 3.0.1
└── bat 0.17.1
```

It can easily be remedied by replacing dirs with dirs-next.

I would we willing to attempt to implement this and submit a PR if it would be accepted.

**Comment by sharkdp** [comment]
That would be great, thank you!

(See similar PR for `fd`: https://github.com/sharkdp/fd/pull/664)
