### ISSUE TITLE
Incremental search in pager mode

### ISSUE THREAD

**Issue by ChocolateOverflow** [sharkdp/bat#1525]
When acting as a pager, pressing `/` or `?` starts incremental search similar to in `vim`.

**Comment by eth-p** [comment]
That's actually already a feature of `less`, which is the program `bat` uses for paging.

Unfortunately though, it doesn't play too nicely with `bat`'s text wrapping. If a word is broken for wrapping purposes, `less` won't be able to find it. You can disable wrapping with `--wrap=never`, which would help.

Or alternatively, if you're using Linux/MacOS and only looking for specific words/patterns, I would recommend using the [batgrep](https://github.com/eth-p/bat-extras/blob/master/doc/batgrep.md) script.

**Comment by sharkdp** [comment]
see #1637 for a solution.
