### ISSUE TITLE
Colorize PCAP files

### ISSUE THREAD

**Issue by pwndumb** [sharkdp/bat#1538]
Hi. Its possible create a syntax highlight for pcap files ?

**Comment by keith-hall** [comment]
A search on ST's package control website didn't return anything, nor did a search on google for "pcap tmLanguage" so I guess there's no prior art on this, but I guess it would be possible to make a syntax definition for it if they are plain text files.

**Comment by sharkdp** [comment]
Haven't checked again, but isn't PCAP a binary format? `bat` only supports syntax highlighting for textual files (but see `bat --show-all`).

**Comment by pwndumb** [comment]
> Haven't checked again, but isn't PCAP a binary format? `bat` only supports syntax highlighting for textual files (but see `bat --show-all`).

I not explain what I really need. I Uusually used  tsark to extract some valuable informations  from pcap file like ip addres in other and other stuff. I extract thhis informations and save in text file.  My life will be more easier if bat can colorize that. 

```bash
tshark -nr $1 -T fields  -e ip.src -e ip.dst -e http.authbasic -Y "http.proxy_authorization" | sort -u | sed -e 's/\s\+/:/g' 
````

**Comment by keith-hall** [comment]
Can you share an example of the output your command generates? Then we can assist you with creating a syntax definition for it or finding an existing one that would highlight it well.

**Comment by pwndumb** [comment]
> Can you share an example of the output your command generates? Then we can assist you with creating a syntax definition for it or finding an existing one that would highlight it well.

Nothing fancy. Just `ip-source:ip-dest:username:password`.  I work as penteaster and some times I made some captures to explain how badly is have a web server without ssl.

**Comment by sharkdp** [comment]
It doesn't really seem like that is a standardized format. You could either write your own syntax definition as @keith-hall suggested. Or transform into something that can be highlighted, like CSV:
```
… | sed -e 's/:/,/g' | bat -l csv
```

(or directly use `,` instead of `:` in your command above)

**Comment by sharkdp** [comment]
Closing this for now.
