### ISSUE TITLE
Auto detect language by shebang

### ISSUE THREAD

**Issue by xiaozhuai** [sharkdp/bat#1545]
Consider a file named `luci` and its content

```lua
#!/usr/bin/lua
require "luci.cacheloader"
require "luci.sgi.cgi"
-- luci.dispatcher.indexcache = "/tmp/luci-indexcache"
luci.sgi.cgi.run()
```

![image](https://user-images.githubusercontent.com/4773701/108337153-c6c7f080-720f-11eb-88d0-a7615a3bb50d.png)

Since this file has no extension name like `.lua`, syntax highlighting stop working unless providing option `-l lua`

These files usually are executable scripts, and begining with [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) line

It's possible to guess language by shebang. 

And also syntax highlighting should ignore shebang line

**Comment by xu-cheng** [comment]
FYI, this actually can be implemented using the existing [libmagic](https://github.com/file/file/tree/master/magic), which contains a database to detect the file type based on its content (not just shebang).

**Comment by sharkdp** [comment]
Thank you for reporting this.

We already have shebang support (e.g. for Bash scripts or Python scripts), it only needs to be supported by the specific syntax. This needs to be fixed upstream in sublimehq/Packages.

> FYI, this actually can be implemented using the existing [libmagic](https://github.com/file/file/tree/master/magic), which contains a database to detect the file type based on its content (not just shebang).

I'd rather not add an external dependency for this. libmagic is powerful for detecting all kinds of binary formats, but those don't really matter for `bat`, right?

**Comment by xiaozhuai** [comment]
@sharkdp 
Thank you!
And one more thing, bat should treat shebang as comment and ignore syntax highlighting on it.


![image](https://user-images.githubusercontent.com/4773701/108594098-dcc1e680-73b2-11eb-81bd-fe1d1a9d99d3.png)

![image](https://user-images.githubusercontent.com/4773701/108594060-a6846700-73b2-11eb-8f85-722e971ee3e5.png)

**Comment by sharkdp** [comment]
Closing this for now, see reasons given here and in https://github.com/sharkdp/bat/pull/1664#issuecomment-886187100. Focusing on #1600 for now.
