### ISSUE TITLE
Release binary for aarch64-apple-darwin

### ISSUE THREAD

**Issue by jpillora** [sharkdp/bat#1551]
Awesome project :) Could you please release a binary for aarch64-apple-darwin (M1 Macs)?

I've compiled from source and that works well though would be handy to have a ready made binary for download

**Comment by Enselic** [comment]
I made a quick test and added the target to our CICD config. The build fails, so it is not trivial to add. Maybe someone can investigate more in depth why it failed.

The PR is here: https://github.com/sharkdp/bat/pull/1552

I think we can close that PR after a while since the code changes themselves are trivial, but I suggest we keep it open for a while longer to see if someone else perhaps finds some interest in analyzing the build failure.

**Comment by glebson1988** [comment]
> Awesome project :) Could you please release a binary for aarch64-apple-darwin (M1 Macs)?
> 
> I've compiled from source and that works well though would be handy to have a ready made binary for download

Could you share instructions please, how you can achieve normal work after compiling from source?
My result after I've compiled from source (when I try for example "bat textfile.txt"):

`Too few arguments - usage: bat chipname inputfilepath
Type bat -h for usage`

**Comment by johnjelinek** [comment]
Looks like CI has been making progress: https://github.com/rust-lang/rust/issues/73908#issuecomment-1193260998

**Comment by fredleger** [comment]
Since this is open for 2 years now could we divide in 2 parts ?

a) have a release for each new version that can be compiled by hands untill there is a descent CI
b) work on the CI if this is still an issue

once b) is completed we can get rid of a)

any thoughts ?

**Comment by lanthoor** [comment]
`aarch64` builders are available in beta now. The builders `macos-13-xlarge` and `macos-latest-xlarge` are M1 machines that can output `aarch64` binaries. But the repository's billing settings does not allow initialization of the runner (I tried #2762). Could one of the maintainers take a look at enabling this option?

**Comment by suzuki-shunsuke** [comment]
Seems like this issue has already been resolved, though no release has been cut yet.

- https://github.com/sharkdp/bat/pull/2967
- https://github.com/sharkdp/bat/issues/2962

**Comment by Enselic** [comment]
Thanks for the notice, let's close as fixed then.
