### ISSUE TITLE
bat display a lot ^M（e.g. python tqdm output）

### ISSUE THREAD

**Issue by zhouyangnk** [sharkdp/bat#1572]
I know I can just replace '^M' with some other character, but is there any good way to show it in bat?

**Comment by Enselic** [comment]
Thanks for asking a question. I don't quite understand what you mean though. How do you get `bat` to display a lot of `^M`s? Maybe `bat --show-all` is what you want?

**Comment by zhouyangnk** [comment]
> Thanks for asking a question. I don't quite understand what you mean though. How do you get `bat` to display a lot of `^M`s? Maybe `bat --show-all` is what you want?

Thank you for your reply, for exam:
![微信截图_20210303102533](https://user-images.githubusercontent.com/10472264/109743045-0547ad00-7c0b-11eb-9f97-ba321f0f7aff.png)
ps: test.out is produced by python's tqdm module

**Comment by Enselic** [comment]
Thanks for providing more info. Here is the output file in question: [test.txt](https://github.com/sharkdp/bat/files/6073926/test.txt)

This is an interesting case, because `cat` and `bat` behaves differently. The file contains carriage-return characters, aka ^M, produced by the progress bar redrawing itself.

When displayed with `cat`, it looks correct, because `cat` handles ^M correctly, in the sense that it "erases" what was previously printed.

```
% cat test.txt
100%|██████████| 50/50 [00:00<00:00, 97.21it/s]
```

in the case of `bat` however, we interpret ^M like any other character, and just prints it:

```
% bat test.txt
───────┬────────────────────────────────────────────────────
       │ File: test.txt
───────┼────────────────────────────────────────────────────
   1   │ ^M  0%|          | 0/50 [00:00<?, ?it/s]^M 20%|██      
       │   | 10/50 [00:00<00:00, 98.02it/s]^M 40%|████      | 
       │ 20/50 [00:00<00:00, 97.72it/s]^M 60%|██████    | 30/5
       │ 0 [00:00<00:00, 97.65it/s]^M 80%|████████  | 40/50 [0
       │ 0:00<00:00, 97.00it/s]^M100%|██████████| 50/50 [00:00
       │ <00:00, 97.27it/s]^M100%|██████████| 50/50 [00:00<00:
       │ 00, 97.21it/s]
───────┴────────────────────────────────────────────────────
```

Maybe we should start to doing what `cat` does unless `--show-all` is passed? Not sure if it's a good idea though.

**Comment by zhouyangnk** [comment]
> Thanks for providing more info. Here is the output file in question: [test.txt](https://github.com/sharkdp/bat/files/6073926/test.txt)
> 
> This is an interesting case, because `cat` and `bat` behaves differently. The file contains carriage-return characters, aka ^M, produced by the progress bar redrawing itself.
> 
> When displayed with `cat`, it looks correct, because `cat` handles ^M correctly, in the sense that it "erases" what was previously printed.
> 
> ```
> % cat test.txt
> 100%|██████████| 50/50 [00:00<00:00, 97.21it/s]
> ```
> 
> in the case of `bat` however, we interpret ^M like any other character, and just prints it:
> 
> ```
> % bat test.txt
> ───────┬────────────────────────────────────────────────────
>        │ File: test.txt
> ───────┼────────────────────────────────────────────────────
>    1   │ ^M  0%|          | 0/50 [00:00<?, ?it/s]^M 20%|██      
>        │   | 10/50 [00:00<00:00, 98.02it/s]^M 40%|████      | 
>        │ 20/50 [00:00<00:00, 97.72it/s]^M 60%|██████    | 30/5
>        │ 0 [00:00<00:00, 97.65it/s]^M 80%|████████  | 40/50 [0
>        │ 0:00<00:00, 97.00it/s]^M100%|██████████| 50/50 [00:00
>        │ <00:00, 97.27it/s]^M100%|██████████| 50/50 [00:00<00:
>        │ 00, 97.21it/s]
> ───────┴────────────────────────────────────────────────────
> ```
> 
> Maybe we should start to doing what `cat` does unless `--show-all` is passed? Not sure if it's a good idea though.

Thanks for your detailed reply.
I tried `--show-all`, and this is the result I got.
It doesn't look good either, so ... maybe behave like cat is better?

```
───────┬───────────────────────────────────────────────────
       │ File: test.out
───────┼───────────────────────────────────────────────────
   1   │ ␍··0%|··········|·0/50·[00:00<?,·?it/s]␍·20%|\u{25
       │ 88}\u{2588}········|·10/50·[00:00<00:00,·99.02it/s
       │ ]␍·40%|\u{2588}\u{2588}\u{2588}\u{2588}······|·20/
       │ 50·[00:00<00:00,·98.94it/s]␍·60%|\u{2588}\u{2588}\
       │ u{2588}\u{2588}\u{2588}\u{2588}····|·30/50·[00:00<
       │ 00:00,·98.89it/s]␍·80%|\u{2588}\u{2588}\u{2588}\u{
       │ 2588}\u{2588}\u{2588}\u{2588}\u{2588}··|·40/50·[00
       │ :00<00:00,·98.85it/s]␍100%|\u{2588}\u{2588}\u{2588
       │ }\u{2588}\u{2588}\u{2588}\u{2588}\u{2588}\u{2588}\
       │ u{2588}|·50/50·[00:00<00:00,·98.82it/s]␍100%|\u{25
       │ 88}\u{2588}\u{2588}\u{2588}\u{2588}\u{2588}\u{2588
       │ }\u{2588}\u{2588}\u{2588}|·50/50·[00:00<00:00,·98.
       │ 73it/s]␊
───────┴───────────────────────────────────────────────────
```

**Comment by sharkdp** [comment]
> Maybe we should start to doing what `cat` does unless `--show-all` is passed? Not sure if it's a good idea though.

Our drop-in cat replacement "promise" (https://github.com/sharkdp/bat#file-concatenation) is that `bat` will behave like `cat` *"whenever bat detects a non-interactive terminal (i.e. when you pipe into another process or into a file)"*. If we are printing to an interactive terminal, however, we can not keep this promise as we need to print ANSI escape sequences on our own to perform syntax highlighting + print decorations. We will also invoke a pager.

You can always force `bat` to disable all of these features by using
```
bat --color=never --decorations=never --paging=never …
```
or in short:
```
bat -pp …
```


Somewhat related: #234, #403

**Comment by Enselic** [comment]
Makes sense :+1: And it works with `-pp`:

```
% bat -pp test.txt      
100%|██████████| 50/50 [00:00<00:00, 97.21it/s]
```
So let's close this ticket.
