### ISSUE TITLE
Gruvbox theme deleted in latest bat version

### ISSUE THREAD

**Issue by ciscohack** [sharkdp/bat#1579]
Hi Team,

Today i updated my bat to latest code and noticed Gruvbox theme disappear. Can you please add it back. i need that theme. i can only see Gruvbox-light theme that i don't want. So i request please add theme back in the system as before.

Thanks 

-Praveen

**Comment by ciscohack** [comment]
@sharkdp hello my friend any help on this. Can you please add small patch upgrade to get back gruvbox theme in Bat which is due to some reason disappear after upgrade. Thanks

**Comment by keith-hall** [comment]
For reference https://github.com/sharkdp/bat/pull/1291 is the related PR, where the motivation to switch was explained. 

Are you aware you can use whatever color scheme you want, regardless of what ships with bat by default? https://github.com/sharkdp/bat#adding-new-themes

**Comment by ciscohack** [comment]
> For reference #1291 is the related PR, where the motivation to switch was explained.
> 
> Are you aware you can use whatever color scheme you want, regardless of what ships with bat by default? https://github.com/sharkdp/bat#adding-new-themes

@keith-hall Thanks for the prompt response. i saw this post and in-fact till Bat version 0.17.1 we had 2 Gruvbox theme Dark/light option and that was the whole idea for that post. now i can only see light theme. I know we can add new theme but i want prebuilt theme option instead of installing separately. Secondly i also trying different prebuilt theme today with --theme=zenburn but color scheme not reflecting. So doubtful now with version 18 theme working properly or not. in my case it's not.

**Comment by ciscohack** [comment]
![image](https://user-images.githubusercontent.com/11479557/110763095-85a78700-8277-11eb-851f-249738cecb36.png)
here is the bat --list-theme output and see in above screenshot it showing the dark gruvbox theme but after upgrade due to some reason name is not showing so i am not able to use it. second don't know what  bat --theme= command also not working

**Comment by keith-hall** [comment]
Thanks for reporting, we'll investigate and fix that - sorry for the trouble

**Comment by keith-hall** [comment]
I'm not able to replicate what you're seeing, maybe you can share the output of `bat --diagnostics` here please?
![image](https://user-images.githubusercontent.com/11882719/110785260-69095000-8273-11eb-8d86-a43da6d0101e.png)

**Comment by ciscohack** [comment]
Thanks Keith

**Comment by ciscohack** [comment]
i added theme through the method mentioned on the wiki page

**Comment by ciscohack** [comment]
❯ bat --diagnostic
#### Software version

bat 0.18.0

#### Operating system

Darwin 20.3.0

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=bat
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=Gruvbox-N
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER="sh -c 'col -b | bat -l man -p'"
```

#### Config file

```
# This is `bat`s configuration file. Each line either contains a comment or
# a command-line option that you want to pass to `bat` by default. You can
# run `bat --help` to get a list of all possible configuration options.

# Specify desired highlighting theme (e.g. "TwoDark"). Run `bat --list-themes`
# for a list of all available themes
#--theme="Sublime Snazzy"

# Enable this to use italic text on the terminal. This is not supported on all
# terminal emulators (like tmux, by default):
#--italic-text=always

# Uncomment the following line to disable automatic paging:
#--paging=never

# Uncomment the following line if you are using less version >= 551 and want to
# enable mouse scrolling support in `bat` when running inside tmux. This might
# disable text selection, unless you press shift.
#--pager="--RAW-CONTROL-CHARS --quit-if-one-screen --mouse"

# Syntax mappings: map a certain filename pattern to a language.
#   Example 1: use the C++ syntax for .ino files
#   Example 2: Use ".gitignore"-style highlighting for ".ignore" files
#--map-syntax "*.ino:C++"
#--map-syntax ".ignore:Git Ignore"
#--map-syntax "*.txt:Python"
#--map-syntax "*.log:Python"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by ciscohack** [comment]
> I'm not able to replicate what you're seeing, maybe you can share the output of `bat --diagnostics` here please?
> ![image](https://user-images.githubusercontent.com/11882719/110785260-69095000-8273-11eb-8d86-a43da6d0101e.png)

Hope you not have theme installed in theme folder with add new theme method

**Comment by keith-hall** [comment]
nope:
```
bat on  master [$!] is 📦 v0.18.0 via 🦀 v1.49.0 
❯ target/release/bat --diagnostics
#### Software version

bat 0.18.0

#### Operating system

Linux 5.4.0-26-generic

#### Command-line

```bash
target/release/bat --diagnostics 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/keith/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
``````

**Comment by ciscohack** [comment]
Sure thanks. now i got gruvbox with your add theme option but thought to let you all to fix it. Hey my friend can we add feature in future for compete pattern/regex support. i know we do have pattern support but if leverage grep and all for extensive search

**Comment by ciscohack** [comment]
> It looks like this issue has been fixed. Please let me know if that is not the case. As for the additional request, please open a new ticket.

yes please close. Thanks a lot for all help.
