### ISSUE TITLE
Kali linux

### ISSUE THREAD

**Issue by dpissan** [sharkdp/bat#1582]
Is it possible to use it in Kali? Thanks!

**Comment by Enselic** [comment]
Hi! Yes it is possible. The current Kali version seems to be outdated however, judging from https://repology.org/project/bat-cat/versions.

But no worries, just download the appropriate .tar.gz package for your computer for the latest release: https://github.com/sharkdp/bat/releases/tag/v0.18.0

**Comment by qbarron73** [comment]
the pkg is in kali, as @Enselic said its old but someone requested an update https://bugs.kali.org/view.php?id=7093
