### ISSUE TITLE
Piping stdout of fzf with bat freezes terminal, yet cat works just fine.

### ISSUE THREAD

**Issue by dcordb** [sharkdp/bat#1585]
**Describe the bug you encountered:**

I was trying to pipe the output of `fzf` with `bat`, I ran `fzf | bat`, selected an item, `bat` displays the selected item and after that the terminal freezes (I tried on alacritty and gnome-terminal, both freezes). Yet the same thing with `cat` works fine.

**What did you expect to happen instead?**

The terminal shoudn't freeze. It should work like `fzf | cat` does.

**How did you install `bat`?**

Github release.

**bat version and environment**
Ubuntu 20.04.1
Terminals tried: alacritty and gnome-terminal.

#### Software version

bat 0.18.0

#### Operating system

Linux 5.4.0-42-generic

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/dcordb/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
Does it work if you disable the pager? (`--paging=never`)?

**Comment by dcordb** [comment]
@sharkdp Yes it does work!

**Comment by sharkdp** [comment]
I'm closing this for now, but please let us know if you think it should be reopened.
