### ISSUE TITLE
How do you remove secondary line numbers column?

### ISSUE THREAD

**Issue by pentago** [sharkdp/bat#1586]
I'm aware that the line numbers column can be removed with --style=plain but how does one remove the other line numbers column?

screenshot: https://i.imgur.com/srD0Jys.png

**Comment by Enselic** [comment]
Hi!

Can you reproduce this problem everywhere? I can not reproduce. Can you provide detailed step-by-step instructions on how to reproduce please?

It would also be helpful if you could paste the output of `bat --diagnostic`

**Comment by pentago** [comment]
I just run `bat --style=plain`

comparison between regular and plain style:
https://i.imgur.com/DMtqsBp.png

**Comment by Enselic** [comment]
I bet you get numbers also with plain `cat1? I suspect your shell is adding the numbers for any output.

In any case, I would be grateful if you could provide the output of `bat --diagnostic`.

**Comment by pentago** [comment]
No line numbers were added with regular `cat`.

Here's the diagnostic output:

#### Software version

bat 0.18.0

#### Operating system

Darwin 20.3.0

#### Command-line

```bash
bat --diagnostic 
```

#### Environment variables

```bash
SHELL=/usr/local/bin/zsh
PAGER=less
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/Users/dzhi/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version 
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by Enselic** [comment]
Interesting. Some follow up questions. Do you get the same line numbering problems if you

1. use native macOS version of `zsh`, i.e. `SHELL=/bin/zsh`
2. show the file with pure `less`?
3. try to reproduce with a newly created user on that machine?

**Comment by pentago** [comment]
Godamn. I had the following env var configured in .zshrc: `export LESS='-sMEFRNXI'` where **N** shows line numbers.
Once I removed it from the rest of the flags, **bat** started working nicely.

THanks for pointing me in right direction! Didn't know **bat** depends on **less** for displaying.
