### ISSUE TITLE
Is it possible to disable trimming?

### ISSUE THREAD

**Issue by pvonmoradi** [sharkdp/bat#1593]
When I view a long file with `bat 0.18.0`, and hit `G`, to scroll to the end, the text would be trimmed like this (`...skipping...`)

![image](https://user-images.githubusercontent.com/1058151/111868493-6c958900-898f-11eb-9045-64aaf5a20f75.png)

This also happens when searching for a specific string which is perhaps more annoying since important information would be above the highlighted match:  

![image](https://user-images.githubusercontent.com/1058151/111868525-abc3da00-898f-11eb-88d0-49768b96491a.png)

Also none of these auto-trimming would happen when using `cat file | less`. 
Is it possible to *not* trim or skip any text when traversing throughout the file (via searching or moving) ?

**Comment by pvonmoradi** [comment]
I was able to workaround this problem (specifically for manpages) with the following function in my bashrc:
```bash
# Use bat to colorize manpages (m instead of man)
m ()
{
    BAT_PAGER="less -FR" \
        MANPAGER="sh -c 'col -bx | bat -l man -p'" \
        MANROFFOPT='-c' \
        man "$@"
}
```
Since my `less` version is old (487, Xubuntu 18.04),  this wouldn't hurt the usual bat functionality and mouse also works.
Still curious to know if there is a way to disable trimming since even "cat file | less -FR " doesn't trim on G or search.

**Comment by Enselic** [comment]
`bat` works the same as `cat` for me, so you most likely have a local environment that makes the behavior differ.

Please upgrade to the latest (v0.18.2) version of `bat`. Then see if the problem persist. If it does, please  paste here the output of `bat --diagnostics`.

**Comment by pvonmoradi** [comment]
@Enselic Still happens on latest version:  

https://user-images.githubusercontent.com/1058151/128146687-b51ed014-00cf-45c1-af84-3d21c563d316.mp4

#### Software version

bat 0.18.2 (589df67)

#### Operating system

Linux 5.4.0-80-generic

#### Command-line

```bash
bat --diagnostics 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/pooya/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 487 (GNU regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by Enselic** [comment]
Can you also try with a more recent version of less please? Your version is pretty old (see https://www.greenwoodsoftware.com/less/)

**Comment by pvonmoradi** [comment]
@Enselic Yeah, my distro's support has ended some months ago. If `bat file` does not trim in Ubuntu 20.04, or with new versions of `less`, I'm ok with it and you can close the issue :)
