### ISSUE TITLE
How to read files with page breaks

### ISSUE THREAD

**Issue by pickfire** [sharkdp/bat#1594]
I did `bat -p /usr/share/doc/rfc/txt/rfc8555.txt` to read rfc text but there are page breaks. In less, sometimes I need to manually tweak less parameter like `-z56` to have a good view to control how much less scroll, because the default might scroll past page breaks. Is this the correct way to do it?

Note, rfc text could be install in arch linux by `pacman -S rfc`.

**Comment by keith-hall** [comment]
I guess this is more of a question about `less` than `bat`. It seems [less doesn't support scrolling to page breaks natively](https://superuser.com/q/1256787/511640). (Page breaks are just character code 12 (hex: C) from the ASCII table.)
It may be worth adding to the desired feature set of a custom pager though, i.e. https://github.com/sharkdp/bat/issues/1053

FWIW, in case this helps others test, to get this RFC for testing on Linux Mint, I had to:
`sudo apt-get install doc-rfc`
and then extract `/usr/share/doc/RFC/links/rfc8555.txt.gz`

**Comment by pickfire** [comment]
Maybe this could be implemented in bat rather than less?

**Comment by sharkdp** [comment]
I don't think we can implement this in `bat`. I wouldn't know how. So this is a feature request for the pager, or for #1053, as @keith-hall mentioned. I'm closing this for now.
