### ISSUE TITLE
Bat incorrectly labels /proc/<pid>/cmdline as binary

### ISSUE THREAD

**Issue by legendofmiracles** [sharkdp/bat#1595]
**Describe the bug you encountered:**

When reading `/proc/<pid>/cmdline` bat says that the content is binary:

```
❯ bat /proc/1/cmdline
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ File: /proc/1/cmdline   <BINARY>
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**What did you expect to happen instead?**

It should print out normally, just like with cat:
```
❯ cat /proc/1/cmdline
/sbin/init⏎                                                                                                                                                     
```

**How did you install `bat`?**

Once on archlinux via `pacman -S bat` and once on nixos in the home-manager configuration file.

---

**bat version and environment**

http://0x0.st/-ND-.txt

**Comment by keith-hall** [comment]
https://github.com/sharkdp/bat/blob/2e7f2b6c0709d758e4e92e5b9cab134d8d04b931/src/input.rs#L244
I guess this will need to be solved at https://github.com/sharkdp/content_inspector

Note: one can use `bat -A /proc/1/cmdline` to get `bat` to show the content even though it thinks it is binary

```
bat on  master [$!] is 📦 v0.18.0 via 🦀 v1.49.0 
❯ ./target/release/bat -A /proc/1/cmdline
───────┬────────────────────────────────────────────────────────────────────────
       │ File: /proc/1/cmdline   <BINARY>
───────┼────────────────────────────────────────────────────────────────────────
   1   │ /sbin/init␀splash␀
───────┴────────────────────────────────────────────────────────────────────────

```

**Comment by legendofmiracles** [comment]
As this isn't bat's fault, I'll close the issue.
