### ISSUE TITLE
Hide file contents after exiting pager

### ISSUE THREAD

**Issue by jindrahelcl** [sharkdp/bat#1599]
When viewing a file in a pager, the contents of the file remain on screen after exiting. Can this behavior be changed to match the behavior of less, i.e. hide the contents after hitting q?

**Comment by eth-p** [comment]
Depending on your version of `less` and `bat`, it should do that by default. Could you please run `bat --diagnostic` and paste the output here?

**Comment by jindrahelcl** [comment]
Sure, here it is. I notice that I am using `PAGER="less -R -S"`. When I set `PAGER="less"`, the issue remains. I get the behavior over SSH, both in and out of tmux/byobu. Less behaves normally.

#### Software version

bat 0.18.0

#### Operating system

Linux 4.4.0-194-generic

#### Command-line

```bash
bat --diagnostics
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER='less -R -S'
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/jhelcl/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 481 (GNU regular expressions)
Copyright (C) 1984-2015  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by eth-p** [comment]
> I notice that I am using `PAGER="less -R -S"`. When I set `PAGER="less"`, the issue remains. I get the behavior over SSH, both in and out of tmux/byobu. Less behaves normally.

`bat` will actually replace the arguments for `less` unless it's set by `--pager=` or `BAT_PAGER`. That's why it doesn't have any effect.

> ```
> > less --version
> less 481 (GNU regular expressions)
> ```

That being said... if `less` is older than v530, `bat` will pass along `--no-init` as a workaround to the `--quit-if-one-screen` bug present before that version. The `--no-init` option is what's causing `less` to leave text behind.

There are two solutions to the problem:

1. Update `less` :)

2. Use `export BAT_PAGER='less -R'`, or put `--pager='less -R'` in `bat`'s config file.

**Comment by jindrahelcl** [comment]
Great, thanks for the answer! Solution 2 works. (I haven't tried upgrading less because I usually work on clusters not admined by me.)
