### ISSUE TITLE
feature request: detect filetype based on vim/emacs comments

### ISSUE THREAD

**Issue by little-dude** [sharkdp/bat#160]
Vim and Emacs can detect the file type base on comments placed at the top of the file.

For emacs:
```
# -*- mode: ruby -*-
```

For vim:

```
# vi: set ft=ruby :
```

This is useful for vagrant configuration files which are written in Ruby but are named `Vagrantfile` for example.

**Comment by sharkdp** [comment]
Thank you for the feedback. `bat` (or rather `syntect`) can do the same, but it has to be specified in the respective syntax file. The `C.sublime-syntax` file, for example, has this header (see `first_line_match`):
``` yaml
name: C
file_extensions:
  - c
  - h
first_line_match: "-[*]-( Mode:)? C -[*]-"
scope: source.c
```

which `bat` correctly detects:

![image](https://user-images.githubusercontent.com/4209276/40802434-e134f68e-6515-11e8-820d-3c4bc70256f6.png)


Unfortunately, only a few syntax definitions include this feature. The Ruby syntax includes this:
``` yaml
first_line_match: ^#!\s*/.*\bj?ruby\b
```
which means that it only detects shebangs:
![image](https://user-images.githubusercontent.com/4209276/40802598-52079e34-6516-11e8-8520-7a12dd45480a.png)


However, note that `Vagrantfile` is correctly detected and displayed with Ruby syntax highlighting:
![image](https://user-images.githubusercontent.com/4209276/40802655-8cad75c2-6516-11e8-9339-134c762dd621.png)

**Comment by sharkdp** [comment]
Actually, I guess correct highlighting of files such as `Vagrantfile` is only supported on `master` and not in the latest release. It has been integrated in `syntect` with my pull request here: https://github.com/trishume/syntect/pull/163.

**Comment by little-dude** [comment]
Ah awesome! I'll wait for next release then. I'll look at syntect to ask if it's worth adding support for `-*- mode: ruby -*-`. Thanks for the answer!

**Comment by sharkdp** [comment]
> I'll look at syntect to ask if it's worth adding support for -*- mode: ruby -*-.

This would have to be done here: https://github.com/sublimehq/Packages

**Comment by sharkdp** [comment]
New release is out.

**Comment by little-dude** [comment]
Just updated, and I can now see my Vagrantfiles with colors \o/
Thanks for this nice crate!

**Comment by sharkdp** [comment]
Thank you for the feedback!

**Comment by Grazfather** [comment]
Sorry to dig up an old issue, but I thought it was the closest to what I need.

Looks like the title of this ticket wasn't actually resolved, Vagrantfiles are highlighted by filename, not by the `-*- mode: xxx; -*-` line.

Is there plans to support this?

**Comment by Grazfather** [comment]
I see your C example: https://github.com/sublimehq/Packages/blob/af2187abbdcdaffd07e459d7ac177bb3b6ca0ae8/C%2B%2B/C.sublime-syntax#L8

It's actually super fragile:  `Mode` shouldn't be capitalized, it's optional, it's missing a `;`, and there could be more options after the `;`.

In my selfish case I only care to support clojure, but either way I think the regex would be better as something like:

`(?i)-[*]- *(mode:)? *(\w+) *;?.*-[*]-`

where the second group `(\w+)` would capture the lang to match against.

**Comment by Grazfather** [comment]
Filed a ticket against Sublime: https://github.com/sublimehq/Packages/issues/2759

**Comment by keith-hall** [comment]
I guess one possible solution to allow a generic "first line match" across all syntaxes in `bat`, without needing to rely on each syntax definition supporting the Emacs mode line, could be to add some code in `bat` to fallback to the modeline matching if https://github.com/sharkdp/bat/blob/d89fa3ebc2639375b0184437607003a639d8ecef/src/assets.rs#L223 fails. Then, taking the example of the second capture group given above, it could call syntect's `SyntaxSet` `.find_syntax_by_token` method with that value.

**Comment by Grazfather** [comment]
Also it would be important to not actually restrict to the first line, since that might be hogged by a shebang

**Comment by keith-hall** [comment]
detecting syntax (or switching syntax) on the second line etc. might be a bit trickier/out of scope due to the nature of how bat works...
https://github.com/sharkdp/bat/issues/1028#issuecomment-635561778

**Comment by Grazfather** [comment]
Ah, that is too bad.

The way Vim does it is that there's a [modeline](https://vim.fandom.com/wiki/Modeline_magic) option that tells Vim how many lines to parse before giving up on seeing a modeline, but I understand that this doesn't work well with how `bat` tries to stream the content.

**Comment by sharkdp** [comment]
> I guess one possible solution to allow a generic "first line match" across all syntaxes in `bat`, without needing to rely on each syntax definition supporting the Emacs mode line, could be to add some code in `bat` to fallback to the modeline matching if
> 
> https://github.com/sharkdp/bat/blob/d89fa3ebc2639375b0184437607003a639d8ecef/src/assets.rs#L223

That sounds great. Could someone please open a new ticket for this?

Detections on the second line are probably not going to happen, no :-/.

**Comment by Grazfather** [comment]
Filed #1600. 10x this issue number, naturally.

**Comment by Freed-Wu** [comment]
![Screenshot from 2022-10-06 12-47-04](https://user-images.githubusercontent.com/32936898/194216940-a18a09f3-2bb8-422c-8de2-bfcd53af0cce.png)


It still cannot work. Because <https://github.com/sharkdp/bat/tree/master/assets/syntaxes> Use a old version of sublime Packages <https://github.com/sublimehq/Packages/tree/759d6eed9b4beed87e602a23303a121c3a6c2fb3> (2019-11-22, before <https://github.com/sublimehq/Packages/issues/2759>).

**Comment by eggbean** [comment]
I have added these lines to the top of my bash and zsh files that get sourced:

    # -*- mode: bash -*-
    # vim: filetype=bash

Works for vim, as before, but not working in bat. No support for sh/shell/bash/zsh it seems.

If it did work, I would then want to see if vim/nvim could read emacs modelines so that I could just use one line, to make things even more convoluted.
