### ISSUE TITLE
[Feature] One-line binary install improvement

### ISSUE THREAD

**Issue by thernstig** [sharkdp/bat#1604]
I have a plethora of great statically linked binary installs in Linux (Ubuntu). These include `ripgrep`, `exa`, `bat`, `fd` etc. None shines as well as `chezmoi` when it comes to the one-line installer.

I recommend to re-implement the one-line binary installer to follow that of `chezmoi`. See this documentation: https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md#one-line-binary-install

In effect, what it does, is to download the latest statically linked binary for your operating system and architecture into `./bin`
This means I can put myself in whatever dir I want and just call the installer and it will be installed into the bin path of my choosing. Be that `~/bin` or `.local/bin` or whatever I prefer.

**Comment by SuperSandro2000** [comment]
or you just use the nix package manager with ``nix-env -iA bat``.

note: I am a very active nix contributor.

**Comment by thernstig** [comment]
I'd prefer not to use `nix-env` but thanks for the pointer :)

**Comment by SuperSandro2000** [comment]
> sometimes like here to download it via the release package and run sudo dpkg (in my Ubuntu case).

You should use ``apt install ./file.deb`` to fetch dependencies.

> Having a one-line installer that just works for any architecture and operating system is golden.

Nix should work on the 3 popular linux arches and darwin but it is a bit broken on bsd and other more niche linuxes.
