### ISSUE TITLE
Incremental Search

### ISSUE THREAD

**Issue by LamprosPitsillos** [sharkdp/bat#1619]
Does bat have incremental search?
If not is it too much to ask for this feature?
Thank you very much! Bat is amazing !

**Comment by keith-hall** [comment]
Maybe I'm misunderstanding something, but presumably incremental search would depend on the pager or terminal emulator you are using?

**Comment by LamprosPitsillos** [comment]
I don't see why incremental search in bat would be affected by my terminal ( kitty ).
Also what do you mean " depends on the pager " , I am using bat as my pager.
Forgive me but I didn't understand your question.

**Comment by iamalicecarroll** [comment]
bat doesn't have a builtin pager. It passes its output to less by default.

**Comment by LamprosPitsillos** [comment]
Thanks for the clarification, now i understand.

**Comment by iamalicecarroll** [comment]
See #1053

**Comment by LamprosPitsillos** [comment]
Has author decided to actually work on the pager? The issue is almost a year old.
I would love to test it, maybe create a separate branch? Sounds really exciting tho, hope it actually gets made

**Comment by hiAndrewQuinn** [comment]
I'm late to the party here, but this is the first result on Google when I search "bat incsearch", so here I am. 🤠

`less -RF --incsearch` turns on incremental search without messing up `bat`'s coloration in the process. You can test this for yourself with the following oneliner:

```bash
# I assume you have curl installed, as well. 
curl -s https://raw.githubusercontent.com/kubernetes/client-go/master/kubernetes/typed/core/v1/pod_expansion.go | BAT_PAGER="less -RF --incsearch" bat --paging=always -l go
```

You can set this as your default behavior in the big shells the same way you would normally set any environment variable:

### Bash

```bash
echo 'export BAT_PAGER="less -RF --incsearch"' >> ~/.bashrc
```

### Zsh

```zsh
echo 'export BAT_PAGER="less -RF --incsearch"' >> ~/.zshrc
```

### Fish

```fish
set -U BAT_PAGER "less -RF --incsearch"
```

Open a new shell and you should have incremental search in your next `bat` session!
