### ISSUE TITLE
--show-all doesn't work properly on Windows

### ISSUE THREAD

**Issue by mjcarman** [sharkdp/bat#1631]
**Describe the bug you encountered:**
On Windows, specifying `--show-all` results in carriage return and linefeed characters displaying as Unicode placeholders (`<U+240D>` and `<U+240A>`) instead of `␍` and `␊` glyphs. This occurs under cmd and powershell, either directly or when run via Windows Terminal.

I thought that this might have been a font issue (I'm using Cascadia Mono) but under a Cygwin bash shell the glyphs are displayed as expected. (Or as � if using a font that doesn't support them like Consolas, but *not* as  <U+xxxx>).

Regardless of the shell and terminal, specifying `--show-all` results in text being displayed without syntax highlighting. Only whitespace characters are colorized.

[Edit: added  screenshots]

<img width="391" alt="bat-cmd" src="https://user-images.githubusercontent.com/121028/116906010-54a75b00-ac05-11eb-9114-e0038c7baf0f.png">

<img width="391" alt="bat-bash" src="https://user-images.githubusercontent.com/121028/116906023-5709b500-ac05-11eb-9005-cfe2f04797c8.png">

**What did you expect to happen instead?**
CR and LF characters should display as glyphs. Syntax highlighting of text should be the same as without `--show-all`.

**How did you install `bat`?**
Downloaded from GitHub and copied executable to path.

---

**bat version and environment**

#### Software version

bat 0.18.0

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
bat --show-all hello.c --diagnostic
```

#### Environment variables

```bash
SHELL=<not set>
PAGER='less -RF'
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of 'C:\Users\mjcarman\AppData\Roaming\bat\config': The system cannot find the file specified. (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```
> less --version
less 581.2 (Spencer V8 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by keith-hall** [comment]
There's a discussion about having syntax highlighting and show-all active together at
 https://github.com/sharkdp/bat/issues/414

**Comment by mjcarman** [comment]
@keith-hall Thanks. I didn't realize that the lack of syntax highlighting under `--show-all` was deliberate behavior/a known limitation. In that case, my issue is just how the CR and LF characters are rendered. Maybe it's a code page issue?

**Comment by mjcarman** [comment]
It *is* a code page issue. Setting `chcp 65001` before doing `bat -A` results in the expected output. Not a bug unless bat is expected to query the code page and adjust its output to match. Feel free to close with prejudice. :)

**Comment by sharkdp** [comment]
Ok, thank you.

I'm closing this for now, hoping that other users will find the ticket in case of similar problems.
