### ISSUE TITLE
Release for Apple M1 macs

### ISSUE THREAD

**Issue by glebson1988** [sharkdp/bat#1636]
Hello, thanks for your product!
Could you please, tell about plans integration bat with Apple M1?
I use bat on my Ubuntu laptop and Mac with Intel and everything is ok!
But recently I bought Mac with Apple M1 chip and my attempts to use bat there were unsuccessful.
I tried to install it through homebrew and through cargo (from source with Rust help).
Bat visible in brewlist and in .cargo/bin but when I try to run some file with this command (for example):
`bat somefile.txt`
I get this error (on screenshot)

<img width="549" alt="Screenshot 2021-05-08 at 00 38 52" src="https://user-images.githubusercontent.com/18693912/117513279-0fcf4b80-af9a-11eb-94b9-2ea9eadde6e1.png">

**Comment by keith-hall** [comment]
If you type `bat - h`, and `which bat`, what do you get? It seems like some other executable called bat is being run.

**Comment by glebson1988** [comment]
> If you type `bat - h`, and `which bat`, what do you get? It seems like some other executable called bat is being run.

which bat returns:
/Users/glebgrisakov/.rbenv/shims/bat

bat -h returns:

NAME
  bat -- a B Squared Logic to ABEL translator

SYNOPSIS
  bat [-h help] [chip_type] [filename]

DESCRIPTION
  BAT takes valid EDF files (As produced by the BLT/MOSIS compatible B
  Squared Logic Program) and converts them to ABEL HDL code.

AUTHORS
  BAT was designed and implemented by Jamie Quint and Ian Tagge.

B^2 Logic Requirements
  BAT 1.0 is designed to work only with the BLT version of 
  B^2 Logic 3.0, available at The University of Portland.

Design Considerations
  *Inputs and Outputs
    B^2 Logic's EDF netlist does not make any distinction between 
    active low input pad and active high input pads.  Thus, all 
    input pads are assumed to be active high.  It is up to the 
    designer to include inverters in the circuit itself, or assume 
    that the inverted external signals will be available.
  *Names of Input Pads
    Output pads and clocks must not contain any spaces or special 
    characters.  Valid names include only standard alphanumeric 
    characters (A..Z, a..z, 0..9).

BUFZ Implementation Details:
  If a BUFZ is used in a circuit, only the first (top) buffer 
  on the BUFZ instance may be used.  This is consistent with BLT 
  implementation.  One external pin is consumed per BUFZ and 
  appears as instXpin in the final ABEL code.  Tristated signals 
  within the circuit will appear as an open input when in high 
  impedance mode.  Given this situation on CMOS technology, the 
  signal will actually float to low rather than remain high 
  impedance, as is typical of of any inputs that are left 
  unconnected.  TTL technology will float high in the same 
  situation.  Because of this, the designer must take care to 
  ensure that the circuit is not designed expecting a true high 
  impedance signal internal to the circuit (this is only achieved 
  when the output is taken directly from the output pin consumed 
  by the buffer).

MUX2 Implementation Details:
  If a MUX2 is used in a circuit, only the first (top) MUX on 
  the MUX2 package may be used.  This is consistent with BLT 
  implementation.

**Comment by eth-p** [comment]
That doesn't really look like our `bat`.

What is your $PATH variable?

**Comment by glebson1988** [comment]
`/Users/glebgrisakov/.nvm/versions/node/v15.12.0/bin:/Users/glebgrisakov/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/glebgrisakov/.cargo/bin`

**Comment by glebson1988** [comment]
> Try reordering it to put `/usr/local/bin` before `/Users/glebgrisakov/.rbenv/shims`.
> 
> It looks like some program also called `bat` is being found in your rbenv before it finds our `bat` installed by Homebrew.

Thanks a lot for your answer, I'll try reorder it)

**Comment by sharkdp** [comment]
@glebson1988 Did that fix your problem?

**Comment by glebson1988** [comment]
> @glebson1988 Did that fix your problem?

Hey, David)
There so many files related to path in mac OS :(
I have not found the only correct solution how to change order...

**Comment by sharkdp** [comment]
Looks like its related to `rbenv` (Simple Ruby version manager). You could try to uninstall it, if you don't use it. Or to find the particular plugin/module that installs the `bat` shim. How wonder how searching for "Squared Logic to ABEL translator" does not lead to any results on Google?!

**Comment by glebson1988** [comment]
> Looks like its related to `rbenv` (Simple Ruby version manager). You could try to uninstall it, if you don't use it. Or to find the particular plugin/module that installs the `bat` shim. How wonder how searching for "Squared Logic to ABEL translator" does not lead to any results on Google?!

I just did:
`gem uninstall bat`

And bat came to life)

Thanks a lot :-)
I close the issue...
