### ISSUE TITLE
Live Search feature in Bat

### ISSUE THREAD

**Issue by ciscohack** [sharkdp/bat#1637]
Hi Team,

Is it possible to have or add live search feature in our BAT tool. I mean when we type words curser jump and highlight the searched keyword. I know there are some editors which can do this bydefault.

-Praveen

**Comment by keith-hall** [comment]
You could try using a different pager which supports this feature. Maybe https://github.com/walles/moar?

**Comment by ciscohack** [comment]
> You could try using a different pager which supports this feature. Maybe https://github.com/walles/moar?

Thanks @keith-hall for quick response. I never tried moar and in fact not hard before. but it would be good if we could add this in our BAT tool

**Comment by ciscohack** [comment]
@keith-hall just tried Moar. Yes, it does what i what i want. But with BAT it's not working properly. i need pager with color syntax highlighter like our BAT tool

**Comment by keith-hall** [comment]
I guess moar's syntax highlighting conflicts with bat's, and I can't see a way to disable it.

We have an open issue to use a custom pager, which would have a better search feature than `less`: https://github.com/sharkdp/bat/issues/1053

**Comment by ciscohack** [comment]
> I guess moar's syntax highlighting conflicts with bat's, and I can't see a way to disable it.
> 
> We have an open issue to use a custom pager, which would have a better search feature than `less`: #1053

Hi @keith-hall,

Yes i am aware about this thread but this thread is long opened case. hoping some day we get the solution.with syntax highlight moar solve one problem but add another issue. any way or trick to make it work

**Comment by ciscohack** [comment]
@keith-hall ,

Moar pager is really very good and some of features are really top notch. shall we try this pager compatible with our beloved BAT tool. i really want this to combination.

**Comment by ciscohack** [comment]
> less already supports this via the `--incsearch` option. Just set your BAT_PAGER variable accordingly, eg to `BAT_PAGER='less -R --incsearch'.
> 
> I highly recommend reading the (whole) manpage of less, it's extremely feature-rich. Other useful options for searching:
> -I for ignorecase or
> -i like smartcase
> -g to only highlight current match, not all at once
> -J to add a status column where matches are also highlighted.
> -jn to set the line where the match scrolls to (eg -j10 so matches are displayed in the 10th line, not the first, if you want more context, or -j.5 so it's the middle of the screen)

Thanks a lot my friend. Very usefull info. I will read the less manpage thanks.

**Comment by ciscohack** [comment]
> less already supports this via the `--incsearch` option. Just set your BAT_PAGER variable accordingly, eg to `BAT_PAGER='less -R --incsearch'.
> 
> I highly recommend reading the (whole) manpage of less, it's extremely feature-rich. Other useful options for searching:
> -I for ignorecase or
> -i like smartcase
> -g to only highlight current match, not all at once
> -J to add a status column where matches are also highlighted.
> -jn to set the line where the match scrolls to (eg -j10 so matches are displayed in the 10th line, not the first, if you want more context, or -j.5 so it's the middle of the screen)

@plgruener  I can see this option was adding in 2013 less --incsearch. But unfortunately i didn't find the option in man page and also i set the variable as your mentioned above but it has no effect and result is not what i am looking . instant search is not working

**Comment by ciscohack** [comment]
> Sorry, I don't know nothing about homebrew, on my Arch Linux it just works, both in just less, and when using less as pager for bat.
> Maybe try downloading the official release or building directly from source. Maybe it's also just your manpages not updated properly, no idea.

Sure, Thanks!

**Comment by sharkdp** [comment]
Closing this for now. For anyone else who wants incremental search in `bat`:

* Use a recent version of less (>= 581)
* Add
  ```
  --pager="less -RF --incsearch"
  ```
  to `bat`s config file (`bat --config-file`)

**Comment by ciscohack** [comment]
> Closing this for now. For anyone else who wants incremental search in `bat`:
> 
> * Use a recent version of less (>= 581)
> * Add
>   ```
>   --pager="less -RF --incsearch"
>   ```
>   
>   
>     
>       
>       
>   
>       
>       
>   
>     
>   
>   
>   to `bat`s config file (`bat --config-file`)

Thanks @sharkdp  for assistance. yes this option work but search is not smooth as compare to moar. in moar same feature is very smooth and jump on the keyword immediately. but in BAT it's little laggy even in less too

**Comment by noborus** [comment]
I am making another pager. https://github.com/noborus/ov
Incremental search has been implemented in a recent version (0.9.4).
I think that it can be used with `bat`, so I'd be happy if you try it.

**Comment by ciscohack** [comment]
> I am making another pager. https://github.com/noborus/ov Incremental search has been implemented in a recent version (0.9.4). I think that it can be used with `bat`, so I'd be happy if you try it.

Wow! awesome i will definitely try.. Thanks for the feature addition

**Comment by sharkdp** [comment]
> I am making another pager. https://github.com/noborus/ov
> Incremental search has been implemented in a recent version (0.9.4).
> I think that it can be used with `bat`, so I'd be happy if you try it.

That sounds really interesting. If `bat` happens to work fine with `ov`, it might be able to solve a few of the issues described in #1053? Maybe it's worth opening a new ticket for this discussion?

**Comment by ciscohack** [comment]
> > That sounds really interesting. If bat happens to work fine with ov, it might be able to solve a few of the issues described in #1053? Maybe it's worth opening a new ticket for this discussion?
> 
> Yes. I think some can be improved.
> 
> I'm implementing reload on an `ov` that hasn't been released yet. This may allow rewriting on the `bat` side.

One feature request if possible if you could enable space key press to scroll the file as all other existing pager doing... i know you have key binding to achieve the task but it is good to have by default second if you could add  ctrl + > and ctrl + <  key bind to jump directly on top and bottom of page this is also available by default in all the pager programs rest all looks good so far ...

**Comment by noborus** [comment]
> One feature request if possible if you could enable space key press to scroll the file as all other existing pager doing... i know you have key binding to achieve the task but it is good to have by default second if you could add ctrl + > and ctrl + < key bind to jump directly on top and bottom of page this is also available by default in all the pager programs rest all looks good so far ...

Please write the ov issue in the ov issue.
I think you can almost solve it by using ov-less.yml to set the key binding.
