### ISSUE TITLE
Binary name is conflicting with astaxie/bat

### ISSUE THREAD

**Issue by qwIvan** [sharkdp/bat#164]
https://github.com/astaxie/bat

**Comment by sharkdp** [comment]
That is unfortunate... and also somewhat expected when giving something a three-letter name :smile:. I'm sure there are even more projects with binaries called `bat`.

I'm not going to rename this project. I guess all we can do is to mark these packages as "conflicting" in package managers.

**Comment by qwIvan** [comment]
@sharkdp If we do that, we can't install then in same time.

**Comment by sharkdp** [comment]
As I said, it's unfortunate - yes. However, you should be able to rename the `bat` executable (from this repository) to anything you like and it should still work the same. It will even show the correct usage when calling with `--help`.
