### ISSUE TITLE
README.md - batdiff function

### ISSUE THREAD

**Issue by suchAdemon** [sharkdp/bat#1640]
Hello, short question about the section [git-diff](https://github.com/sharkdp/bat#git-diff) from the readme.md file.

In there you descript how a function for showing a diff in git repos could be shown through bat.
The command you have used in your documentation is  `git diff --name-only --diff-filter=d | xargs bat --diff`

Is it on purpose that this diff function should only be used then from the root path of the repository?

Because if you are not inside of the root directory, git will still return the full path to the changed file, which means a false path would be handed over to bat:
```bash
$ cd ./templates

$ git diff --name-only --diff-filter=d | xargs bat --diff
[bat error]: 'templates/app.ini.erb': No such file or directory (os error 2)

$ git diff --name-only --diff-filter=d
templates/app.ini
```

To get that working the parameter `--relative` would be needed to get it working:
`git diff --name-only --diff-filter=d  --relative | xargs bat --diff`

**Comment by sharkdp** [comment]
Thanks. I didn't know about the `--relative` option. Note that it has an additional effect though ("exclude changes outside the directory"):
```
       --relative[=<path>], --no-relative
           When run from a subdirectory of the project, it can be told to
           exclude changes outside the directory and show pathnames relative
           to it with this option. When you are not in a subdirectory (e.g.
           in a bare repository), you can name which subdirectory to make the
           output relative to by giving a <path> as an argument.
           --no-relative can be used to countermand both diff.relative config
           option and previous --relative.
```

Still, I think we should change this in the README.
