### ISSUE TITLE
command bat not found, but can be installed with `sudo apt get install bacula-console-qt`

### ISSUE THREAD

**Issue by jeevan786** [sharkdp/bat#1653]
**Describe the bug you encountered:**
While installing from apt, `apt install bat`, got installed but when run `bat /etc/*-release`, got this message
command bat not found, but can be installed with `sudo apt get install bacula-console-qt`
But when I install from deb, it installs successfully. Displays output as expected.
After install from deb, if you hit apt install bat (just for the sake of it), it offers a different package:
The following packages will be REMOVED:
  bat-musl
The following NEW packages will be installed:
  bat
(I denied).
...

**What did you expect to happen instead?**
I expected it to release my os release versions.
...

**How did you install `bat`?**

apt install bat
---

**bat version and environment**
latest (0.18.1) as of May 14. Env: Ubuntu desktop 20.04.2 Focal fossa x64 on acer aspire v5

bat /etc/*-release

**Comment by sharkdp** [comment]
Please read https://github.com/sharkdp/bat#on-ubuntu-using-apt
