### ISSUE TITLE
[manual Syntax] colourization of syntax contexts

### ISSUE THREAD

**Issue by atticus-sullivan** [sharkdp/bat#1656]
Hi,

I recently wanted to simply add some keywords to the `log` Language. Sometimes you have some keywords which are important so it's nice to be able to highlight them (without using the search function).

So I looked into the `sublime-syntax` specs on [http://www.sublimetext.com/docs/3/syntax.html](http://www.sublimetext.com/docs/3/syntax.html) and wrote my syntax file. Now the thing that is still unclear to me is, how can one colourize the context groups defined in there?
I looked around into some other syntax files, but it hasn't gotten to me how this would work. I even found the keywords `error` and `exception` in the current default `log.sublime-syntax` file which aren't colourized at all (which I think especially in this case is not the point in capturing these keywords).

Can someone give a short explanation on this (or a resource to read for this)?

**Comment by keith-hall** [comment]
hi, the docs at http://www.sublimetext.com/docs/3/color_schemes.html may be of interest to you :)

it's possible that the scopes we are using in the log syntax aren't targeted by many existing color schemes, and it may make sense to make a PR to those color schemes' git repositories to ensure they color our log files correctly...

**Comment by atticus-sullivan** [comment]
Are you sure `bat` works with `sublime-color-scheme`s? As far as I've tested examples now, I only got `tmTheme`s working (which are a lot harder to edit/create in my Opinion)

**Comment by atticus-sullivan** [comment]
Ah seams that this is not supported in upstream [https://github.com/trishume/syntect/issues/244](https://github.com/trishume/syntect/issues/244) so I think I'll have to cope with xml syntax
