### ISSUE TITLE
Does not work as drop-in replacement

### ISSUE THREAD

**Issue by marcvs** [sharkdp/bat#1660]
**Describe the bug you encountered:**
I have an alias: `alias cat=bat`
I run echo `cat file`
I see the line numbers, hence this would not work like `cat` (I use this in commandlines to remove the password from cmdline).

**What did you expect to happen instead?**
`bat` should show the same output as `cat` when no tty is assigned.

**How did you install `bat`?**
```
apt-get install bat
     Installed: 0.12.1-6+b2
cd /usr/bin
ln -s batcat bat
alias cat=bat
```

**bat version and environment**
`0.12.1-6+b2`
I use `bash`

## diagnostic:

marcus@nemo:~$ . tmp/info.sh
system
------

**$ uname -srm**
Linux 5.10.0-6-amd64 x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID:	Debian  
Description:	Debian GNU/Linux 11 (bullseye)  
Release:	11  
Codename:	bullseye  

bat
---

**$ bat --version**
bat 0.12.1  

**$ env**

bat_config
----------

**$ cat /home/marcus/.config/bat/config**
```
--color=always
--style=numbers
--line-range=:500
```

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

**$ /bin/bash --login -i -c type cat**
```
cat is aliased to `bat'
```

tool
----

**$ less --version**
less 551 (GNU regular expressions)

**Comment by sharkdp** [comment]
The problem is that you put `--color=always` in your config file.

I would also recommend to remove the `--line-range` line.

**Comment by marcvs** [comment]
Many thanks for quick response!!!
