### ISSUE TITLE
unclear how csv files columns are highlighted

### ISSUE THREAD

**Issue by gennaro-tedesco** [sharkdp/bat#1662]
It is unclear how columns in `.csv` files are syntax-highlighted: let us consider the below

```
$ bat mpgcars.csv
```
<img width="609" alt="Screenshot 2021-05-23 at 11 31 17" src="https://user-images.githubusercontent.com/15387611/119255161-68b5fb00-bbba-11eb-8fac-53d58428c67b.png">

as we can see colours for columns are inconsistent: is `bat` separating by type (namely strings vs numbers) or is it separating by delimiter? What is the logic that is applied in order to syntax highlight a `.csv` file (namely the logic behind `bat -l csv`)?

Would it not be clearer to simply alternate colours by delimiter (so that the visual separation of columns in a file is standing out much better)?

**Comment by sharkdp** [comment]
Can you please try the latest version of bat? We have recently improved the CSV highlighting.

**Comment by gennaro-tedesco** [comment]
Thank you for your quick reply. I am using 
```bat --version
bat 0.18.1```
isn't this the latest or are you referring to compile from source (or a certain branch)?

**Comment by keith-hall** [comment]
I believe that the color scheme you are using chooses to use the same color for various distinct scopes - it is expected that the color scheme would have at least 4 different colors for the fields before they repeat, and one for the delimiter at a minimum.
Please can you confirm which color scheme (aka theme) you are using?

**Comment by gennaro-tedesco** [comment]
```
$ cat ~/.config/bat/config

--theme='Solarized (dark)'
--style='header,grid'
--italic-text=always
```
I do confirm that by choosing other themes 4 different colours properly alternate; however, at the same time I have noticed that few other themes (say zenburn, TwoDark, Coldark-Dark, Coldark-Cold, Solarized Light) also just alternate two colours (three at most for some).

**Comment by keith-hall** [comment]
Thanks for the information, maybe we can improve those themes somehow - I'll investigate when I get time. Thanks for reporting.

**Comment by gennaro-tedesco** [comment]
Thank you for looking into it, I believe we can close this now if you narrowed down the issue to the themes :)
