### ISSUE TITLE
Possibility to configure PrettyPrinter using the Config struct

### ISSUE THREAD

**Issue by stepnivlk** [sharkdp/bat#1663]
Hello,
currently `PrettyPrinter` can be configured via a builder pattern:
```rust
bat::PrettyPrinter::new().true_color(true).header(true) // ...
```
But I have an use-case where it'd be beneficial to use the Config struct directly and pass it to the PrettyPrinter, something like:
```rust
let config = Config {
  true_color: true,
  header: true,
  // ...
}

let pretty_printer = PrettyPrinter::new(Some(config)); // or a separate method
```
Technically I can skip the instantiation through `new` however that'd mean I'd have to copy&paste initialization of the attributes.

Would you be interested in supporting config via a struct alongside of the builder? I'm happy to open a PR once the API would be decided.

**Comment by sharkdp** [comment]
Thank you for your request.

The problem with such a method (e.g. `PrettyPrinter::from_config(config)`) is that it would introduce breaking changes whenever we modify the `config::Config` struct.

As stated in the [API documentation](https://docs.rs/bat/0.18.1/bat/) (*"note that the API of these internal modules is much more likely to change"*), the internal modules like `config` are not very stable right now. And ideally, I would like to remove them from the public interface. Exposing such a struct in the main API (via a `PrettyPrinter` method) would be detrimental to that goal. Even adding a new field to the `Config` struct would result in a breaking change.

**Comment by stepnivlk** [comment]
I see, that makes sense. So unless we want to have a `PublicConfig` struct we can close the issue. Thanks!

**Comment by sharkdp** [comment]
> So unless we want to have a `PublicConfig` struct we can close the issue.

It doesn't really solve the issue with breaking changes though. Imagine we want to introduce a new config flag/setting. In order for the `::from_config(…)` method to profit from the new flag/setting, the `PublicConfig` struct will need to be changed. We could update it less frequently than the internal `Config` flag and then do all of the copying inside this crate. But still. We can not fully introduce new config flags without a breaking change.

With a builder pattern, there is no problem (unless you *remove* or *rename* a flag/setting).

I can see how the proposed method could be useful, but I think I'm leaning towards declining this request. Let me know what you think!

**Comment by stepnivlk** [comment]
Thx for clarification, you're right, let's close this ticket.
