### ISSUE TITLE
Installation on Debian 10 (stable) is working surprisingly fine

### ISSUE THREAD

**Issue by RoneoOrg** [sharkdp/bat#1665]
Hello there,

according to the documentation, `bat` is only available for Debian sid.

Here is how I installed it successfully on Debian 10 / stable:

- download [bat-musl_0.18.1_amd64.deb](https://github.com/sharkdp/bat/releases/download/v0.18.1/bat-musl_0.18.1_amd64.deb) from [the Realase page](https://github.com/sharkdp/bat/releases)
- run `sudo apt install ./bat-musl_0.18.1_amd64.deb` in a Terminal
- Done, there is no step 3!

**Do you think it's worth updating the doc?**

### Output of `apt`

The output of `apt` seems fine:

```
# apt install ./bat-musl_0.18.1_amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'bat-musl' instead of './bat-musl_0.18.1_amd64.deb'
The following NEW packages will be installed:
  bat-musl
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 0 B/2,092 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /home/user/Downloads/bat-musl_0.18.1_amd64.deb bat-musl amd64 0.18.1 [2,092 kB]
Selecting previously unselected package bat-musl.
(Reading database ... 204437 files and directories currently installed.)
Preparing to unpack .../bat-musl_0.18.1_amd64.deb ...
Unpacking bat-musl (0.18.1) ...
Setting up bat-musl (0.18.1) ...
Processing triggers for man-db (2.8.5-2) ...
Scanning processes...                                                                                                                                 
Scanning linux images...                                                                                                                              
Running kernel seems to be up-to-date.
Failed to check for processor microcode upgrades.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
#
```

### Output of `bat --diagnostic`

**bat version and environment**

bat --diagnostic
#### Software version

bat 0.18.1 (3aea514)

#### Operating system

Linux 4.19.0-16-amd64

#### Command-line

```bash
bat --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/user/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-musl
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 487 (GNU regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
Well, there is this chapter: https://github.com/sharkdp/bat#on-ubuntu-using-most-recent-deb-packages

Do you think something else should be added to the documentation=

**Comment by RoneoOrg** [comment]
Hi @sharkdp,

> Do you think something else should be added to the documentation?

Maybe just a clarification as the same documentation reads:

> On Debian `bat` is currently only available on the unstable "Sid" branch.

**Comment by sharkdp** [comment]
Sounds good. Labeling as 'documentation'

**Comment by voanhcung** [comment]
0xB98ceE834EF70C4F67CD5a7dCdBa89ed4948e0c5

**Comment by pheki** [comment]
Since the PR got closed as it's no longer needed, should this issue be closed?

**Comment by RoneoOrg** [comment]
> Since the PR got closed as it's no longer needed, should this issue be closed?

You're right, I'm closing this issue
Thanks for the follow-up!
