### ISSUE TITLE
White text color on white background terminal

### ISSUE THREAD

**Issue by alexandre1985** [sharkdp/bat#1676]
**Describe the bug you encountered:**
`bat` prints white text color on white background terminal
...

**What did you expect to happen instead?**
Expect to be like `cat` and, in these circunstances, print black text color
...

**How did you install `bat`?**
```
pacman
```

---

**bat version and environment**
```
bat 0.18.1
```
ArchLinux

**Comment by alexandre1985** [comment]
![](https://i.imgur.com/WsDrXPo.png)

**Comment by sharkdp** [comment]
Could you please post the output of `bat --diagnostic`? Also, please read https://github.com/sharkdp/bat#highlighting-theme

**Comment by alexandre1985** [comment]
I already added a theme. It would be cool if it worked like cat and detect the terminal background color and ajust to it.
Either way, here it is:

$ bat --diagnostic
#### Software version

bat 0.18.1 (3aea514)

#### Operating system

Linux 5.10.41-1-lts

#### Command-line

```bash
bat --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=/home/daniel/.config
XDG_CACHE_HOME=/home/daniel/.cache
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

```
--theme="Solarized (light)"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 581.2 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
You can try to do something like this: https://github.com/sharkdp/bat#dark-mode

There is also an issue somewhere on this repository with a solution for bash, if I remember correctly.

**Comment by alexandre1985** [comment]
Thank you.
I have set a theme manually and I am sticking with it

**Comment by daramir** [comment]
> You can try to do something like this: https://github.com/sharkdp/bat#dark-mode

@sharkdp I've been unable to use  the dark mode instructions as part of a bat config file. Could you please share the right way to do it? Could be a syntax problem on my end, or a limitation of the config logic?

I'd like to avoid using the alias method. Thanks.

**Comment by Enselic** [comment]
If you want it would be great if you could try the git master branch. In git master (and in the next release) bat will auto-detect macOS dark mode out of the box.

The PR is this one: https://github.com/sharkdp/bat/pull/2197

**Comment by asphaltism** [comment]
I put this into my .bashrc.
Worked for me.
```bash
export BAT_THEME="GitHub"

**Comment by stellarpower** [comment]
I am admittedly on an old version of bat currently, but this stopped me usin it some time ago and not looked back until now. 

If I list the themes like so: 
`bat --list-themes`

![image](https://github.com/user-attachments/assets/44334928-e68a-4deb-b0d0-cde4136edd68)

Many of the light themes look very nice; but, it seems they're light themes but are outputting text in a light colour expecting a dark background, when I have my terminal set to light mode, as I do on all programs I use, so I can read it without the chances of eye cancer.

I don't know if it's possible to detect the background colour of a terminal emulator portably, and reliably enough that it'll work, but I'm guessing that the colour scheme in this case is using a fixed colour for the text irrespective of the background. I'll just change themes for now, as some of them do render nicely, but if it would be possible to apply logic depending on the colour of the terminal's background, I guess that'd be an ideal solution. Or may be a pain in the arse, but perhaps a light-light theme and a light-dark theme - i.e. the themes can show text in light but one where the terminal is set up as dark, and one if the terminal is set up as light. Hopefully most colours wouldn't need to be changed - the syntax highlighting looks nice, but it's plain text that renders as white-on-white for me, when it ought to be black-on-white.

Thanks :bat: :cat2:
