### ISSUE TITLE
Feature: "Backtrace" mode with --line-caret or --line-pointer

### ISSUE THREAD

**Issue by zachriggle** [sharkdp/bat#1684]
For generating backtraces with e.g. `zsh`, I currently use a sophisticated `awk` expression and some `zsh` internals: https://gist.github.com/zachriggle/9b030a7c767b6429d220e033c027b0be

I can use `bat --line-range $(($line-4)):$(($line+4))` to print out the same data, syntax highlighted, and with a simpler syntax, including line numbers -- but I don't get an arrow pointing at the specific line that caused the fault.

It would be nice if there was an additional option, e.g. `--line-caret` or `--line-pointer` that inserts some padding to all lines and a `>>>` pointing at any lines specified with `--line-caret`.  Ordering of line-number and caret don't matter, but the output I currently have looks like, e.g.:

```
[x] Frame 5:
22       trap 'trap_err' ERR
23
24       function failure_point() {
25   >>>     false
26       }
27
28       function one() {
```

A stretch goal here would be to also have a `--line-caret-context` or similar so that I don't have to specify the specific range, it's just `bat --line-caret 100 --line-caret-context 4 /path/to/example.sh` to achieve the same effect.

**Comment by sharkdp** [comment]
Have you seen `--highlight-line`?
```
    -H, --highlight-line <N:M>...        
            Highlight the specified line ranges with a different background
            color For example:
              '--highlight-line 40' highlights line 40
              '--highlight-line 30:40' highlights lines 30 to 40
              '--highlight-line :40' highlights lines 1 to 40
              '--highlight-line 40:' highlights lines 40 to the end of the
            file
```

**Comment by zachriggle** [comment]
I was not aware of `-H`, but it isn't useful for when people copy-paste a stack trace to me, since the color information is lost.

Also, `-H` does the full line (to the width of the terminal) so it isn't particularly pleasant on the eyes.

## Full-screen Screenshots

### awk

Compare before (awk expression, see gist):

<img width="1440" alt="Screen Shot 2021-06-16 at 6 53 41 PM" src="https://user-images.githubusercontent.com/111640/122309610-34d9a700-ced4-11eb-91e8-8d1a01789a98.png">

### bat

To `bat -n --line-range $(($line-4)):$(($line+4)) -H $line "$file"`:

<img width="1440" alt="Screen Shot 2021-06-16 at 6 53 08 PM" src="https://user-images.githubusercontent.com/111640/122309621-3a36f180-ced4-11eb-86f1-d2d885771034.png">

**Comment by zachriggle** [comment]
I was not aware of `-H`, but it isn't useful for when people copy-paste a stack trace to me, since the color information is lost.

Also, `-H` does the full line (to the width of the terminal) so it isn't particularly pleasant on the eyes.

## Full-screen Screenshots

### awk

Compare before (awk expression, see gist):

<img width="1676" alt="Screen Shot 2021-06-16 at 6 57 55 PM" src="https://user-images.githubusercontent.com/111640/122309909-d19c4480-ced4-11eb-80a4-eb4242c54e49.png">

### bat

To `bat -n --line-range $(($line-3)):$(($line+3)) -H $line "$file"`:

<img width="1676" alt="Screen Shot 2021-06-16 at 6 58 05 PM" src="https://user-images.githubusercontent.com/111640/122309918-d6f98f00-ced4-11eb-8d49-d2ed9e52ba51.png">

**Comment by zachriggle** [comment]
I've worked around this for my use-case.

As always, thanks @sharkdp for making such a great and useful tool!  I've integrated `bat` into so many of my workflows, it's a wonderful tool to use!
