### ISSUE TITLE
[Question] What is the default color and syntax for javascript?

### ISSUE THREAD

**Issue by piotryordanov** [sharkdp/bat#1689]
To the left is neovim with monokai theme.
To the right is bat on the same file with colors on.

Notice that Bat recognizes more javascript symbols that neovim does!
So I'm curious: 

1. What is the default colorscheme used? (And can I use it in vim)
2. What is the default syntax plugin used for javascript (And can I use it in vim?)

Thank you!
![image](https://user-images.githubusercontent.com/48773775/122218732-65f7ae80-ceb7-11eb-834a-7f997e2428f3.png)

**Comment by eth-p** [comment]
> 1. What is the default colorscheme used? (And can I use it in vim)

It's actually also Monokai.

> 2. What is the default syntax plugin used for javascript (And can I use it in vim?)

Syntax detection is actually the same as Sublime Text. Bat, through `syntect`, uses `.sublime-syntax` to determine how code should be highlighted.

I'm not currently aware of any way to import `.sublime-syntax` syntax definitions into `vim`. If someone is willing to put in the effort (and is good at reading regex), I'm sure it could be manually converted, though.
