### ISSUE TITLE
option to do case insensitive searches within bat by default

### ISSUE THREAD

**Issue by goutham2688** [sharkdp/bat#1690]
currently every time I have to enter -I to make searches case insensitive within bat.

can an option be provided to add case in-sensitive searches (similar to less -I)
so that I can add in my alias like to make my searches within bat case insensitive.
alias bat='bat -I'

**Comment by eth-p** [comment]
Searching is handled by `less`, so you should be able to get away with doing something like this:

```bash
alias bat='LESS="-I" bat'
```

**Comment by goutham2688** [comment]
awesome this works for me 👍

**Comment by LittleboyHarry** [comment]
`vim $(bat --config-file)` (`bat --generate-config-file` before), uncomment pager parameter line then add `--ignore-case` flag.

it also work fine!

**Comment by goutham2688** [comment]
this solution works for me too :)

my less version did not support all the parameters in the autogenerated config file.
I'm using this one.
```bash
--pager="less  --RAW-CONTROL-CHARS --IGNORE-CASE"
```
