### ISSUE TITLE
Julia syntax highlighting bug

### ISSUE THREAD

**Issue by Moelf** [sharkdp/bat#1692]
```
a = 64
b = Float64[]
c = Int[]
```
![image](https://user-images.githubusercontent.com/5306213/122455414-aab14180-cfac-11eb-8f53-e943cb8f0725.png)

As you can see the `64` in `Float64` is inappropriately highlighted as a number. 
For comparison this is what the code looks like in neovim with JuliaVim:
![image](https://user-images.githubusercontent.com/5306213/122456073-67a39e00-cfad-11eb-8ba7-717522e179fd.png)

IMO can we use more up-to-date "source" such as: https://github.com/highlightjs/highlight.js/issues/2832 instead of the "sublime text" highlight?

**Comment by keith-hall** [comment]
> IMO can we use more up-to-date "source" such as: [highlightjs/highlight.js#2832](https://github.com/highlightjs/highlight.js/issues/2832) instead of the "sublime text" highlight?

The Julia sublime-syntax definition was last updated 23 days ago, seems quite recent to me. https://github.com/JuliaEditorSupport/Julia-sublime/commit/48639e1dbf5bd22fce14beef7ed7f45050de2027
But no, bat relies on sublime-syntax files, there is no support for js highlighting libraries, nor are we likely to add any.

**Comment by Moelf** [comment]
@keith-hall not their issue apparently

**Comment by keith-hall** [comment]
It's possible that we need to reference a newer Julia submodule version, but it may use more recent features which the syntax highlighting library we are using doesn't handle yet.

**Comment by sharkdp** [comment]
Fixed in v0.18.2
