### ISSUE TITLE
LF/CR are not rendered on Windows, instead their unicode code point is printed

### ISSUE THREAD

**Issue by hediet** [sharkdp/bat#1697]
**Describe the bug you encountered:**

On Windows, this happens when using the `-A` flag:

![](https://user-images.githubusercontent.com/2931520/122654951-0a475280-d14f-11eb-901a-cdedd4888e96.png)

**What did you expect to happen instead?**

On WSL however, it is rendered correctly:

![image](https://user-images.githubusercontent.com/2931520/122655152-a0c84380-d150-11eb-84f4-8af9a3750e6e.png)

**How did you install `bat`?**

choco on Windows, latest release deb amd64 for WSL.

---

**bat version and environment**

Both `bat 0.18.1`.

**Comment by sharkdp** [comment]
Thank you for reporting this. I'm not a Windows expert and not really sure how I can help here. If you know what we would need to change in `bat`, please let us know.

**Comment by belotn** [comment]
Hello, it seems that all unicode special charater are displayed with <U+ByteCode> even if bat is launched in ConEmu
![image](https://user-images.githubusercontent.com/3379936/126895101-c729dfe2-3ebb-4ea3-a7e6-7165b1bb6dd5.png)

**Comment by sharkdp** [comment]
Could you please try to add `--paging=never`?

**Comment by belotn** [comment]
Ok, UTF code does not appear when using --paging=never

**Comment by sharkdp** [comment]
Could you please try what happens if you pipe the output of `bat -A` to `less` directly? Or what happens if you pipe it to a file? And then into `less`? Do you see the same `<U+…>` artifacts?

**Comment by belotn** [comment]
Hello,

Sorry for the delay. Unicode Artifacts only appears when using Powershell, with CMD output is ok. 
So i look for powershell console encoding, it appears to be in "US ANSI", according the this thread ( https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell ) i change Powershell output to UTF8
:
`$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding`

and it seems to correct the display
![image](https://user-images.githubusercontent.com/3379936/130045735-755288f6-f28a-4347-80da-717c9a8966c3.png)
 
Thanks a lot for your time.

Regards
Nicolas.

**Comment by sharkdp** [comment]
I'm closing this for now. Please feel free to comment in case it should be re-opened.
