### ISSUE TITLE
Is it possible to have the screen cleared after the command finishes?

### ISSUE THREAD

**Issue by tsatke** [sharkdp/bat#1704]
The behavior of less (at least on osx) is that after I quit, the screen is cleared.
```
$ less foo.txt
$ less bar.txt
$
```
The terminal always looks clean.
With this, it always looks like this.
```
$ bat foo.txt
content of foo.txt
$ bat bar.txt
content of bar.txt
```
This is especially annoying when using `bat` as pager for git.
Am I missing an option or does this just not exist?

**Comment by tsatke** [comment]
Just found this
https://github.com/sharkdp/bat/issues/1698#issuecomment-864495741

TL;DR
`brew install less` fixes the issue for me

**Comment by reportaman** [comment]
This worked for me too :)
