### ISSUE TITLE
AsciiDoc syntax highlighting can't be mapped to from config file

### ISSUE THREAD

**Issue by Keating950** [sharkdp/bat#1705]
**Describe the bug you encountered:**
Setting `--map-syntax "*.txt:AsciiDoc"` in `~/.config/bat/config` results in the error `[bat error]: unknown syntax: 'AsciiDoc'`. The same is true when using `"*.txt:asciidoc"` and `"*.txt:Asciidoc"`. However, `bat foo.txt -l asciidoc` works as expected.
...

**What did you expect to happen instead?**
.txt files to display with AsciiDoc syntax highlighting.
...

**How did you install `bat`?**

Cargo

---

**bat version and environment**
#### Software version

bat 0.18.1 (<no git>)

#### Operating system

macOS 11.4 (Darwin 20.5.0)

#### Command-line

```bash
bat description.txt --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=<not set>
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='sh -c '\''col -bx | bat -l man -p'\'''
```

#### Config file

```
--map-syntax "*.txt:asciidoc"
```

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: aes,crypto,fp,neon,sha2
- Host: aarch64-apple-darwin

#### Less version

```
> less --version 
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by keith-hall** [comment]
Thanks for reporting. Bat expects the map-syntax config to reference the human readable `name` of the syntax i.e. the `name` key in the `sublime-syntax` YAML file, if present. So, you should see that `--map-syntax "*.txt:AsciiDoc (Asciidoctor)"` works as expected. :)
(I believe `-l` picks up the file extension `asciidoc` and thus doesn't rely on the friendly name of the syntax.)
