### ISSUE TITLE
Is it possible to print custom line nuumber

### ISSUE THREAD

**Issue by sudipghimire533** [sharkdp/bat#1710]
Default line numbering starts from 1 and incremented by 1 for each new line. Is it possible to pass custom range or vector of type `usize` to print as line number.
### What I am trying to do.
I am writing a simple grep like utility and I have to print the matching line with line number. Some expected output is to look like:
-------
| 3| _found_ string |
| 5| not _found_ that |
| 7| are you _found_ here |
--------

**Comment by sharkdp** [comment]
Thank you for your feature request.

I think this is out of scope for `bat`. It sounds like a niche use case.

Why do you want to pipe the output of your tool through `bat`?
