### ISSUE TITLE
Ability to configure keybindings

### ISSUE THREAD

**Issue by AlexCzar** [sharkdp/bat#1719]
For those of us using non-qwerty layouts ability to configure alternative keybindings is a must.
For example for Soul and Colemak layouts at least following is needed:
j → n
k → e
n → b
etc.
To clarify, I'm asking for ability to configure all keybinrings manually, not for adding baked in support for specific layouts.

**Comment by keith-hall** [comment]
Are you aware that `bat` just uses your configured pager? So your pager (presumably `less` by default) would need to support this, it isn't something we can add in `bat`.
