### ISSUE TITLE
`bat --language Manpage` actually prints "^H"

### ISSUE THREAD

**Issue by Teagum** [sharkdp/bat#1723]
I use `bat` as pager for Manpages. If I set `MANPAGER=bat -p -l Manpage`, the output of, for example, `man bat` contains `^H` control character as actual text ([see screenshot](https://ibb.co/DbypfTg)). In fact, it appears that bat inserts `^H` at different locations depending on what argument I pass to the `--language` option.

I am aware of the `-r` option of `less`. However, explicitly disabling it does not change the above behavior.
`bat` was installed with `homebrew` and runs in iTerm2 3.4.8

---

#### Software version

bat 0.18.1 (<no git>)

#### Operating system

macOS 11.2.3 (Darwin 20.3.0)

#### Command-line

```bash
bat -p -l Manpage --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS=-R
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='bat -p -l Manpage --diagnostic'
```

#### Config file

Could not read contents of '/Users/xxxxxx/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
Did you see this part of the README? https://github.com/sharkdp/bat#man

**Comment by Teagum** [comment]
I read all he REAME but must have somehow skipped the relevant section. Sorry and thank you. Problem solved.
