### ISSUE TITLE
bat cache --help does return help on the cache flags?

### ISSUE THREAD

**Issue by sanga** [sharkdp/bat#173]
bat --help tells you that bat has a subcommand "cache" however "bat cache --help" doesn't give you any help on the flags available for that subcommand. Is this not how this works in clap? So basically I had to look at  the source to see how it works...

**Comment by sharkdp** [comment]
I can not reproduce this. Can you please make sure (`which bat`, `bat --version`) that you are using the latest version of `bat`? Maybe there is another, older version of `bat` on your machine that takes precedence?

**Comment by sanga** [comment]
Yup. This (and the other one) are on me. Apologies for the noise. Note to self: don't file bugs after midnight. So the problem was that I'd aliased bat to "bat --style=plain", which of course doesn't work with the subcommand.

**Comment by sharkdp** [comment]
Thank you for the feedback.

That behavior is somewhat unfortunate. I definitely see how that could happen to other users as well. I guess we should push forward environment variables like `BAT_THEME` and `BAT_STYLE` to avoid the need for `alias bat='bat ...` aliases (which I am using as well).
