### ISSUE TITLE
manpages formatting looks misplaced

### ISSUE THREAD

**Issue by Creator54** [sharkdp/bat#1731]
**Describe the bug you encountered:**

when using bat as pager for manpages the formatting is bit misplaced.

**What did you expect to happen instead?**

formatting should be similar to less

![share](https://user-images.githubusercontent.com/34543609/125667392-a8ae7447-c644-42c4-9b32-cb13728b5346.png)
![share1](https://user-images.githubusercontent.com/34543609/125668023-98b236f1-aabf-44a9-9a5d-6746985d4b43.png)

**How did you install `bat`?**
nix-env -iA nixos.bat

---

**bat version and environment**

#### Software version

bat 0.18.1 (<no git>)

#### Operating system

Linux 5.10.40

#### Command-line

```bash
/home/creator54/.nix-profile/bin/bat --diagnostic 
```

#### Environment variables

```bash
SHELL=/run/current-system/sw/bin/fish
PAGER=bat
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

```
--theme="Dracula"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 563 (POSIX regular expressions)
Copyright (C) 1984-2020  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Comment by Creator54** [comment]
also theme doesnt seem to have applied to manpages , in general it works . ig could be an issue with my config.

**Comment by sharkdp** [comment]
Please check out the README and search for MANPAGER

**Comment by Creator54** [comment]
> Please check out the README and search for MANPAGER
Sorry i don't seem to understand it properly ig
fish shell doesnt have the [`export`](https://stackoverflow.com/questions/21624512/setting-exports-in-fish-shell) so `set -x` works but now i get manpages with `less` instead of `bat` with theme.

![share](https://user-images.githubusercontent.com/34543609/125680827-70ac683d-19ba-4078-aca2-8c052a84e03f.png)

**Comment by sharkdp** [comment]
The other env variables seem to be set with `set -gx` (global). Is that important maybe? To try, please run `bat --diagnostic` again and post the output here (or check yourself if the variables are set correctly).

**Comment by Creator54** [comment]
> The other env variables seem to be set with `set -gx` (global). Is that important maybe? To try, please run `bat --diagnostic` again and post the output here (or check yourself if the variables are set correctly).

setting as global doesnt seem to have any affect  ;(

#### Software version

bat 0.18.1 (<no git>)

#### Operating system

Linux 5.10.40

#### Command-line

```bash
/home/creator54/.nix-profile/bin/bat --diagnostic 
```

#### Environment variables

```bash
SHELL=/run/current-system/sw/bin/fish
PAGER=bat
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='sh -c '\''col -bx | bat -l man -p'\'''
```

#### Config file

```
--theme="Dracula"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 563 (POSIX regular expressions)
Copyright (C) 1984-2020  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
Any `fish` shell experts here? @eth-p? :-)

**Comment by eth-p** [comment]
Regarding the formatting being misplaced:

`man` does its own text wrapping based on the detected terminal width. When you use `bat` for the man pager, it further wraps the output of `man` to make space for the sidebar.

Try this:

```fish
function man
    set -x MANPAGER 'sh -c "col -bx | bat --language=man --decorations=never"'
    set -x MANROFFOPT '-c'
    command man $argv
    return $status
end
```

That will wrap the `man` command to use `bat` as the pager, without the sidebar. I wrote it on mobile, so I haven't tested it yet but it should work since I based it off of my own batman script.

Regarding the theme problem:

Maybe try passing `--theme` to bat directly inside that wrapper function?

**Comment by sharkdp** [comment]
Right, I forgot about [`batman`](https://github.com/eth-p/bat-extras/blob/master/doc/batman.md). That might work for you as well, @Creator54.

**Comment by Creator54** [comment]
> Regarding the formatting being misplaced:
> 
> `man` does its own text wrapping based on the detected terminal width. When you use `bat` for the man pager, it further wraps the output of `man` to make space for the sidebar.
> 
> Try this:
> 
> ```fish
> function man
>     set -x MANPAGER 'sh -c "col -bx | bat --language=man --decorations=never"'
>     set -x MANROFFOPT '-c'
>     command man $argv
>     return $status
> end
> ```
> 
> That will wrap the `man` command to use `bat` as the pager, without the sidebar. I wrote it on mobile, so I haven't tested it yet but it should work since I based it off of my own batman script.
> 
> Regarding the theme problem:
> 
> Maybe try passing `--theme` to bat directly inside that wrapper function?

![share](https://user-images.githubusercontent.com/34543609/126910500-c8127afa-cb74-46cc-96f4-4673fa3972ae.png)

Got output same as previous .
Makes me think the previous post i made was also `bat` which i mistakenly identified  as `less` getting themed 😅
+ 
i totally forgot the `bat` was using `less` under the hood and misunderstood it.

is currently a way to get manpages + sidebar + proper formatting work??

**Comment by Creator54** [comment]
thanks for `batman`

**Comment by sharkdp** [comment]
@Creator54 it looks like this can be closed then?

**Comment by Creator54** [comment]
> @Creator54 it looks like this can be closed then?

Yep sorry for not closing it already. 
It would be great if the left sidebar with line-number could also be integrated to Batman. 

thanks for this awesome tool btw.

**Comment by ciscohack** [comment]
@sharkdp @eth-p  I am also having manpage format issue and my man page is not colorized and not using bat pager style instead it looks using less. I am running macOS 11.6 and latest BAT pager.

![image](https://user-images.githubusercontent.com/11479557/137580362-0ee16ae9-95f1-475f-85c6-195d5021067b.png)

I don't know from where it's picking the environment variable for LESS and bat theme but in my configuration that is already disabled. But no luck 

 bat --diagnostic                                                                                                                                                                                 ─╯
#### Software version

bat 0.18.3

#### Operating system

macOS 11.6 (Darwin 20.6.0)

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=bat
LESS=-iRFXMx4              >>>>>> this i tried to disabled by export LESS =""
BAT_PAGER='less -iRXF'  >>>>>> this i tried to disabled by export LESS =""
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=gruvbox-dark
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='less -X'  >>>>>> this i tried to disabled by export LESS =""
```

#### Config file

```
# This is `bat`s configuration file. Each line either contains a comment or
# a command-line option that you want to pass to `bat` by default. You can
# run `bat --help` to get a list of all possible configuration options.

# Specify desired highlighting theme (e.g. "TwoDark"). Run `bat --list-themes`
# for a list of all available themes
#--theme="Sublime Snazzy"

# Enable this to use italic text on the terminal. This is not supported on all
# terminal emulators (like tmux, by default):
#--italic-text=always

# Uncomment the following line to disable automatic paging:
#--paging=never

# Uncomment the following line if you are using less version >= 551 and want to
# enable mouse scrolling support in `bat` when running inside tmux. This might
# disable text selection, unless you press shift.
#--pager="--RAW-CONTROL-CHARS --quit-if-one-screen --mouse"

# Syntax mappings: map a certain filename pattern to a language.
#   Example 1: use the C++ syntax for .ino files
#   Example 2: Use ".gitignore"-style highlighting for ".ignore" files
#--map-syntax "*.ino:C++"
#--map-syntax ".ignore:Git Ignore"
#--map-syntax "*.txt:Python"
#--map-syntax "*.log:Python"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by ciscohack** [comment]
> Ok, but MANPAGER is not set correctly, right?

i have this in my manpager "MANPAGER='sh -c '\''col -bx | bat -l man -p'\'''  as per BAt doc this is what mentioned to configure. looks good to me
