### ISSUE TITLE
Feature: Add an additional gutter lane to mark highlighted lines

### ISSUE THREAD

**Issue by zachriggle** [sharkdp/bat#1744]
First, thanks @sharkdp as always for making such an awesome tool that I can wedge into so many of my workflows.

One of the workflows I've wedged it into is a shim between `git-grep` and `bat` (not dissimilar to `batgrep`, I expect), so that I can make use of the advanced search features of `git-grep` (boolean operators `--and`, `--not`, `--or`, and `()` grouping; as well as the `--function-context` flag).

I end up issuing commands that look something like:

```sh
$ bat -P -f -r 1247:1305 -H 1253 -H 1256 -H 1266 -H 1271 -H 1277 -H 1282 path/to/some/file.ext
```

That is, a large region is displayed, with several highlighted lines within that range.  This works wonderfully.

However, sometimes with VERY large ranges, and few highlighted lines, it can take a while of scrolling to get to the next highlighted line -- and there is no way to easily search for highlighted lines with `less`.

`git-delta` manages this somewhat, by injecting `Δ` symbols at the beginning of each file, which is neat.

It would be nice if there were a way to add an additional gutter column for highlighted lines that ensures they are not only highlighted, but easy to search for with e.g. `less`.  This symbol could be hard-coded, but I see no reason it can't be configurable, e.g.

```
$ bat --highlight-prefix='>' ...
```

Would add a gutter to the left of the line numbers (if present), and prepend the symbol (plus a space, for separation) to each line that is highlighted.  It is then relatively trivial to search in `less` with `/^>` and to (manually, I don't expect `bat` to do this) preload this as a pattern in `less` with `less -p'^>'`.

Ideally, there would only be one marker per group of sequential highlighted lines, but it would still be a step up even if EVERY highlighted line had such a marker.

Thanks for your consideration!

**Comment by keith-hall** [comment]
Thanks for the feedback. We have an existing feature request which looks related to me: https://github.com/sharkdp/bat/issues/1324

**Comment by zachriggle** [comment]
Thanks for linking to the other issue!  That does indeed look related.

**Comment by sharkdp** [comment]
> First, thanks @sharkdp as always for making such an awesome tool that I can wedge into so many of my workflows.

:+1: Thanks goes to all [contributors](https://github.com/sharkdp/bat/graphs/contributors) and all [maintainers](https://github.com/sharkdp/bat#maintainers)


> That does indeed look related.

It would be great if you could post any additional information from this request in #1324 so we can close this one. Hope that's fine.
