### ISSUE TITLE
support -v

### ISSUE THREAD

**Issue by xenoterracide** [sharkdp/bat#1749]
so I was looking for a way to print non printing characters on the cli as a way to deal with an issue I'm having. I found this

https://docstore.mik.ua/orelly/unix/upt/ch25_07.htm

which suggests `cat -v` of course locally I have `cat` aliased to `bat` so I was surprised it didn't work.  It's also a little surprising that 

```
echo $var | /usr/bin/cat -A
```

```
echo $var | /usr/bin/bat -A
```

don't have the same output. I don't know, doesn't matter a lot to me, it was just surprising.

**Comment by sharkdp** [comment]
> which suggests `cat -v` of course locally I have `cat` aliased to `bat` so I was surprised it didn't work.

We aim to be POSIX `cat` compliant (https://pubs.opengroup.org/onlinepubs/009696799/utilities/cat.html), not GNU `cat` compliant. `-v` is not a POSIX option.

We do, however, provide `-A`/`--show-all`, which is very similar to what you are trying to achieve, I think.

> It's also a little surprising that
> 
> ```
> echo $var | /usr/bin/cat -A
> ```
> 
> ```
> echo $var | /usr/bin/bat -A
> ```
> 
> don't have the same output.

What is the output that you see? What is the value of `$var`? Or do you want to `echo '$var'`?

Why is it surprising that they don't have the same output? What are you missing? `bat` aims to provide a better solution than `cat -A` by using symbols that are not commonly part of source files and by adding color highlighting to the non-printing (replacement) characters.

**Comment by xenoterracide** [comment]
I like the output, and I have no real use case, I guess I was just surprised that even piping it I was seeing different output because that would make using bat to script with it difficult. But I don't really have a use case for needing cat -A when scripting, or behaving different in an active shell.

As far as posix compliance, sure, I largely agree, even if gnu is the most popular implementation, and it's hard to tell when it you're using a proprietary extension of it. My definition of proprietary being non-portable API and not implemented by any other software. In this case it was a case of Google showing that option first and then running into it not existing. And then of course I do man cat instead of man bat.

I'm not entirely sure if there is anything to do here. I guess it depends a little bit on whether cat -A has the same output on BSDs as It does in gnu, and whether or not that bat should behave in that way when being piped like it would correct itself if you were using it as cat in a pipe. Just as a command though I like its output.

**Comment by sharkdp** [comment]
Thank you for the explanation.

I agree. If there is a common agreement among `cat` implementations how the output of `cat -A` should look like, we could consider implementing the same "specification" for piped / non-interactive output. But only if someone can show me a real-world use case where someone relies on the textual output of `cat -A` and post-processes it somehow. I would imagine that it was really built for humans to read. And for this use case, my goal was to provide an improvement by showing tabs as `├──┤`, line feeds as `␊`, etc.

I hope it's ok if we close this until then.
