### ISSUE TITLE
highlight individual line

### ISSUE THREAD

**Issue by tskinn** [sharkdp/bat#175]
Now that bat supports displaying a range of lines I would like to have bat be able to highlight one line.

My use case has to do with utilizing bat as a preview command in a fuzzy finder like [fzf](https://github.com/junegunn/fzf) or [skim](https://github.com/lotabout/skim).

Here is what we can do currently with bat: ![fzf](https://thumbs.gfycat.com/ShabbyHealthyChrysomelid-size_restricted.gif)
(I'm just using a copy of preview.sh I've put up [here](https://gist.github.com/tskinn/0ed07b1c43968807b24e0e585ae58ce2))

So how can or should this be done? Invert the colors of the line? Does syntec api have something that makes this easy? Or should we just manipulate the grid portion of the display like the line number or insert an arrow in that gutter?

Again I'd be happy to work on it but would like some input before I do.

**Comment by sharkdp** [comment]
Sounds good!

> So how can or should this be done? Invert the colors of the line?

I'd prefer using a background color, but this could be problematic when using different (dark or light) themes, I guess.

> Does syntec api have something that makes this easy?

Not sure, but we translate syntect style => ANSI style ourselves, so it should be easy to modify the style in the highlighted lines.

> Or should we just manipulate the grid portion of the display like the line number or insert an arrow in that gutter?

That would be problematic if no sidebar / no line-numbers are used.

**Comment by sharkdp** [comment]
Related: https://github.com/trishume/syntect/pull/198

**Comment by sharkdp** [comment]
The next syntect release will include the mentioned helper to modify line style.

**Comment by tskinn** [comment]
Looks likes syntec has a new release! https://github.com/trishume/syntect/releases
I'll have to see if upgrading breaks anything.

**Comment by sharkdp** [comment]
> Looks likes syntec has a new release! [trishume/syntect/releases](https://github.com/trishume/syntect/releases)
> I'll have to see if upgrading breaks anything.

See #345

**Comment by tskinn** [comment]
#346 but I forgot about the full line highlight. Yeah at the moment it just does background with content.

**Comment by sharkdp** [comment]
Released in [v0.10.0](https://github.com/sharkdp/bat/releases/tag/v0.10.0).
