### ISSUE TITLE
should have at least one "white background" default theme

### ISSUE THREAD

**Issue by kaolin** [sharkdp/bat#176]
I'd just do a PR on this but wanted to see if you had thoughts.... I tried out ayu-light and Eiffel (via Sublime, which I'm not really a user of), and both seemed okay-ish (arguably could include both of them...) 

https://github.com/SublimeText/LegacyColorSchemes/blob/master/Eiffel.tmTheme
https://github.com/dempfi/ayu/blob/master/ayu-light.tmTheme

**Comment by sharkdp** [comment]
Thank you for your feedback.

`bat` includes the `GitHub` and `Monokai Extended Light` themes by default. Both are optimized for light backgrounds, I think?

**Comment by kaolin** [comment]
Now that you say that (sorry), I can see they work reasonably well (although they're relatively muted, still), but I think I was conflating this with the "file names on the grid/chrome are always white" issue. Would you be adverse to adding one or two more? (or maybe the effort is more worth falling under the "make it easier to add themes without clobbering existing ones"?)

**Comment by sharkdp** [comment]
I'm fine with adding a few more themes (still, customization should be easier in `bat`) - thanks!

**Comment by sharkdp** [comment]
I'm going to close this ticket but I'm happy to take pull requests adding more themes.
