### ISSUE TITLE
would be nice to change default theme via command line or environment variable versus alias

### ISSUE THREAD

**Issue by kaolin** [sharkdp/bat#177]
among other issues, setting the suggested alias breaks subcommands like "bat cache".

**Comment by sharkdp** [comment]
Thank you for the feedback. Definitely agree with this request (see also #173).

Let's introduce `BAT_THEME` and `BAT_STYLE`.

**Comment by sharkdp** [comment]
Released in [bat 0.5](https://github.com/sharkdp/bat/releases/tag/v0.5.0).
