### ISSUE TITLE
Allow for easier copying of multiple lines

### ISSUE THREAD

**Issue by dumrich** [sharkdp/bat#1792]
When I try to copy lines from `bat`, it sometimes takes the line number as well as the line. For example:
![image](https://user-images.githubusercontent.com/40397381/129033113-21f0a260-0ead-47ae-87ce-ec699c4d18cf.png)

I think there should be a feature that allows for multiple lines to be copied without copying the line number.

**Comment by sharkdp** [comment]
please see https://github.com/sharkdp/bat#xclip

**Comment by ajboni** [comment]
> please see https://github.com/sharkdp/bat#xclip

But that disables the really nice line numbers...
It would be nice to have the possibility to select/copy without selecting line numbers (but still have them on screen)

![image](https://user-images.githubusercontent.com/12578313/137598443-066c3ac1-c81d-4361-ae9c-b1b5cf588626.png)
