### ISSUE TITLE
syslog highlighting confused if there is no colon in message

### ISSUE THREAD

**Issue by scop** [sharkdp/bat#1794]
**Describe the bug you encountered:**

Syslog highlighter gets confused if a message without colon occurs. Highlighting "leaks" to the next line, gets likely terminated by the colon in the next line's timestamp, and works thereafter.

Example (on Ubuntu 20.04, rsyslog):
```shellsession
$ logger --server localhost hello
$ tail -n 1 /var/log/syslog
Aug 11 21:40:31 uncleman scop hello
```
![Screenshot from 2021-08-11 21-45-01](https://user-images.githubusercontent.com/109152/129085572-b106edc0-ae27-4a81-8639-84b86de50a1f.png)

**What did you expect to happen instead?**

No confusion, lines with messages without colons would work.

**How did you install `bat`?**

Current git master.

**bat version and environment**

**Comment by sharkdp** [comment]
Thank you for reporting this.


It would be fantastic if @keith-hall could have a look into this (https://github.com/sharkdp/bat/pull/1606 for context)

**Comment by keith-hall** [comment]
I believe this has been addressed with https://github.com/sharkdp/bat/pull/1793 and thus this issue can be closed - please correct me if I'm wrong, @scop ? :)

**Comment by scop** [comment]
Correcting :) #1793 addressed two different issues, this one's still open as reported.
