### ISSUE TITLE
Better CSV support

### ISSUE THREAD

**Issue by im-n1** [sharkdp/bat#1795]
Today I ran into [this](https://github.com/alexhallam/tv) cool project. I like how it handles columns. I'm familiar of `column` command in linux and my question is if you could please consider this nice-columns feature for bat.

**Comment by sharkdp** [comment]
https://github.com/eth-p/bat-extras/blob/master/doc/prettybat.md from bat-extras has a very similar goal actually. So this might indeed be a better place to ask for such a functionality. Maybe `tv` could even be used as a preprocessor for that.

I'd like to close this, hope that's fine for you @im-n1 - thank you for your request!
