### ISSUE TITLE
Not installable on Ubuntu via `apt` if `hexyl` is also installed.

### ISSUE THREAD

**Issue by jackolantern** [sharkdp/bat#1798]
**Describe the bug you encountered:**

If `hexyl` is installed via apt (`apt install hexyl`) then running `apt install bat` on Ubuntu results in
```
dpkg: error processing archive /tmp/apt-dpkg-install-8Y628f/5-bat_0.12.1-1build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package hexyl 0.6.0-2build1
```

...

**What did you expect to happen instead?**

I expected `bat` to install.
...

**How did you install `bat`?**

 `apt install bat`

---

**bat version and environment**

n / a

**Comment by sharkdp** [comment]
Please see https://github.com/sharkdp/bat/issues/938
