### ISSUE TITLE
F with less doesn't follow in bat

### ISSUE THREAD

**Issue by georgevreilly-stripe** [sharkdp/bat#1805]
**Describe the bug you encountered:**

Using `less` as a pager for `bat`, I expect that the `F` command will "follow" a file; i.e., as the file continues to grow, I will see it appear at the end of `bat`s window, much like `tail -f`. I do see `Waiting for data... (interrupt to abort)` appear at the bottom of the screen. However, when data is appended to the file, `bat` doesn't notice. When I hit `^C` to interrupt,  `bat` exits. It tends to leave the terminal in a confused state; e.g., I hit up-arrow and I see `OA` echoed.
...

**What did you expect to happen instead?**

I expect it to behave like running `less` directly and using the `F` command: new output should appear at the end of screen; `^C` should pop out of follow mode, not exit the program.
...

**How did you install `bat`?**

I ran `sudo dpkg -i bat_0.18.2_amd64.deb`, which was downloaded from the Releases page.

---

**bat version and environment**

#### Software version

bat 0.18.2 (589df67)

#### Operating system

Linux 5.8.0-1041-aws

#### Command-line

```bash
bat redacted.log --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/georgevreilly/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
Please see #457, #808, and #1053
