### ISSUE TITLE
Parse PKGBUILD files as bash syntax

### ISSUE THREAD

**Issue by clarcharr** [sharkdp/bat#181]
These are used by Arch Linux and it'd be nice to add this.

**Comment by sharkdp** [comment]
This would have to be included in the `bash` Sublime Syntax definition [here](https://github.com/sublimehq/Packages/blob/master/ShellScript/Bash.sublime-syntax). To me, it sounds like it might be worth to open a PR/issue in *sublimehq/Packages* for this.

Another option would be to implement #169, such that `bat` users can define their own extension => language mappings.

**Comment by sharkdp** [comment]
@clarcharr If you'd like to move forward with the first option, please open an upstream ticket in *sublimehq/Packages*.

I will close this for now, as path two is already tracked in #169.

**Comment by sharkdp** [comment]
Syntax re-mapping is now supported in [v0.8.0](https://github.com/sharkdp/bat/releases/tag/v0.8.0).
