### ISSUE TITLE
wierd large white space

### ISSUE THREAD

**Issue by yihan0512** [sharkdp/bat#1817]
**Describe the bug you encountered:**
when I bat a file, it shows large white space between words.
...

**What did you expect to happen instead?**
just normally displayed text.
...

**How did you install `bat`?**

dpkg deb
---

**bat version and environment**
0.18.3 ubuntu 20.04

#### Software version

bat 0.18.3 (b146958)

#### Operating system

Linux 5.11.0-27-generic

#### Command-line

```bash
bat generatePatterns.py --diagnostic 
```

#### Environment variables

```bash
SHELL=/usr/bin/fish
PAGER=<not set>
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/yi/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Comment by yihan0512** [comment]
<img width="971" alt="Screen Shot 2021-08-23 at 3 06 08 AM" src="https://user-images.githubusercontent.com/5248345/130404897-68c699ac-6072-4975-be56-13e7129ae5e2.png">

**Comment by sharkdp** [comment]
Probably a bad theme for the light terminal background. Please see https://github.com/sharkdp/bat#highlighting-theme

**Comment by yihan0512** [comment]
It is confirmed that the issue is due to some themes. I've switched to OneHalfLight and it worked fine.

**Comment by UgnilJoZ** [comment]
Having the same issue with the default Gnome terminal theme. No colored CLI had this issue before, so I would be interested if this is really Gnome's fault.
