### ISSUE TITLE
Gruvbox theme - wrong theme version/accent/colors in usage with fzf.vim

### ISSUE THREAD

**Issue by im-n1** [sharkdp/bat#1819]
Hi folks,

long-time gruvbox theme user here. I notices gruvbox by bat is slightly dirrerent than the [official version](https://github.com/morhetz/gruvbox). I saw https://github.com/sharkdp/bat/pull/1291 where you actually discused why so many variants and you come up with 2 - light and dark. Thats cool but somehow you chose wrong variants. Let me explain.

gruvbox theme:
- light variant
  - hard accent
  - medium accent  <- THE "gruvbox light"
  - soft accent
- dark variant
  - hard accent
  - medium accent <- THE "gruvbox dark"
  - soft accent

I admit this might be confusing but I hope you we can switch the theme from current one to ones I marked.

**Comment by sharkdp** [comment]
maybe @subnut and @iamalicecarroll can help out here?

**Comment by iamalicecarroll** [comment]
I'm pretty sure I used the medium variants [[commit](https://github.com/subnut/gruvbox-tmTheme/commit/64c47250e54298b91e2cf8d401320009aba9f991)]

**Comment by iamalicecarroll** [comment]
> Hm this is very strange. Let's compare these 2 bat outputs.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/198654/130946207-7ac13bdc-302e-4ffb-8222-345e19ec9aab.png)
> 
> 
> 
> The left one is genuine `bat --theme=gruvbox-dark` command output. The right one is output from vim fzf plugin from preview window which uses `let $BAT_THEME = "gruvbox-dark"` directive that sets env var. I suppose those 2 outputs should be exactly the same. Shouldn't they?

Can you check the actual color in both with some kind of color picker? It's `#282828` or `rgb(40, 40, 40)` in Gruvbox Dark Medium

**Comment by im-n1** [comment]
I checked the red and yellow color. Colors in the left example are 100% according to gruvbox pallete [here](https://github.com/morhetz/gruvbox). Colors from the right example are unknown.

- yellow
  - left: #fabd27
  - right: #ffaf5f
- red
  - left: #fb4934
  - right: #ff5f5f

**Comment by subnut** [comment]
> Colors in the left example are 100% according to gruvbox pallete here

If so, then it means that there is no problem in the _Gruvbox theme_ of `bat`, and the problem lies in the interaction between `bat` and `fzf.vim`

Please change the issue title accordingly.

**Comment by im-n1** [comment]
Makes sense. I'm very interested in the cause of this weird issue. How can I "debug" why bat colors the output differently. I will do the heavylifting but I needto know where to start. I already used `--diagnostic` which is the same in both cases. What are other stuff I can look into? Is there some inner bat magic which directs colors?

Tittle changed.

**Comment by sharkdp** [comment]
My guess would be that vim (of fzf) interprets the ANSI codes directly and re-renders them as interpolated 8-bit colors? Maybe this helps: https://github.com/junegunn/fzf.vim/issues/969: 

> Also, if you're in Neovim, you'll need to enable truecolor support via set termguicolors in your init.vim and setting COLORTERM="truecolor" in your shell: #756

**Comment by im-n1** [comment]
Seems like the problem was solved by `set termguicolors`. Now the color tones are identical. Yet the highlighting is different in terms of keywords get gighlighted in different color in vim and in bat. It's quite confusing but it's kinda another story.

Thank you for your cooperation and patience.

**Comment by subnut** [comment]
> Seems like the problem was solved by `set termguicolors`

So you were comparing 24-bit color with 256-color all along?   
🙄 

> Yet the highlighting is different in terms of keywords get highlighted in different color in vim and in bat.

Of course. `vim` uses regex-based syntax files that are made for vim itself, and the individual colorschemes assign different colors to those _syntax definitions_. But `bat` uses `tmTheme` files, which are -
- Not compatible with vim's `syntax` and `colorscheme` files
- **Written by different people**, and different people have different opinions on what should get highlighted.

If you want the same highlighting, use something like [`telescope.nvim`](https://github.com/nvim-telescope/telescope.nvim)

---

Since the issue is resolved, please close it.

**Comment by im-n1** [comment]
> So you were comparing 24-bit color with 256-color all along?

Seems so. I didn't know that vim is not running in 24-bit mode. My bad.

Yea I will switch to telescope once Debian releases nvim 0.5 to it's repo.

Thanks once again.
