### ISSUE TITLE
Support `--ignored-suffix` to ignore filename suffix

### ISSUE THREAD

**Issue by edentsai** [sharkdp/bat#1824]
in https://github.com/sharkdp/bat/pull/1687, it supported to ignoring known backup/template filename suffixes.

Hopes we can also custom the ignored suffixes in `~/.config/bat/config`, 

for example:

- .env.example
- .env.production
- config.json.production

We can configure bat in `~/.config/bat/config`:

```bash
# ~/.config/bat/config
--ignored-suffix ".example"
--ignored-suffix ".production"
```

thanks for this awesome tool.

**Comment by Enselic** [comment]
Closed by #1892
