### ISSUE TITLE
support piping

### ISSUE THREAD

**Issue by granteagon** [sharkdp/bat#1845]
Currently, UNIX pipes are not supported.  Perhaps instead of replacing `cat` (as cat is still useful without all the output of `bat`), piping to from cat to bat could be implemented.  🤷🏻‍♂️

TLDR; this doesn't work but probably should:
```
➜  cat README.md | bat
[bat error]: 'README.md': No such file or directory (os error 2)
───────┬──────────────────────────────────────────────────────────────────────────────────
       │ STDIN   <EMPTY>
───────┴──────────────────────────────────────────────────────────────────────────────────
```

**Comment by Enselic** [comment]
`cat README.md | bat` works for me. Please provide provide the output of `bat --diagnostics` and `cat --version`. And how did you install `bat`?

**Comment by Enselic** [comment]
The error message suggests that your `cat` is aliased to `bat`.

In either case, `bat` has good support for piping. Feel free to reopen this ticket if you disagree.
