### ISSUE TITLE
not sure if it's a bug or something I don't understand (I change MANPAGER to the one in the example and I got weird man results)

### ISSUE THREAD

**Issue by mrjayviper** [sharkdp/bat#1849]
- I'm running Ubuntu 21.04 and using bash.
- I installed bat via apt.
 
------------------

myuser@myhost:~$ export MANPAGER="sh -c 'col -bx | bat -l man -p'"

myuser@myhost:~$ man batcat
sh: 1: bat: not found
man: command exited with status 127: sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | LESS=-ix8RmPm Manual page batcat(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$PM Manual page batcat(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$ MAN_PN=batcat(1) sh -c col -bx | bat -l man -p

myuser@myhost:~$ batcat --version
bat 0.12.1

**Comment by keith-hall** [comment]
One thing that jumps out at me is that the executable is installed as `batcat`, but your `MANPAGER` is referring to `bat`.

Also, just for reference, [bat 0.12.1](https://github.com/sharkdp/bat/releases/tag/v0.12.1) was released in Sept 2019 - that's 2 years old now. I'd recommend to try a later version of bat (i.e. with a different installation method) and see how that behaves with a fixed MANPAGER env var.

**Comment by keith-hall** [comment]
I'm going to close this because it seems like it's likely not a fault in `bat`, and we have provided a couple of things to try. We can always revisit this if we get some more feedback.
