### ISSUE TITLE
File extensions should be matched without case sensitivity

### ISSUE THREAD

**Issue by michaelmior** [sharkdp/bat#1854]
Perhaps there are some example use cases to the contrary, but in general it seems like it would preferable if file extensions were matched ignoring case. I recently experienced this with a file name that had the extension `SQL` instead of `sql` and `bat` did not automatically apply the desired highlighting.

**Comment by keith-hall** [comment]
Thanks for reporting. We have fixed this upstream, and are waiting for a new release of the `syntect` dependency which will contain this fix. (See https://github.com/sharkdp/bat/issues/1807 where it was first discovered.)

**Comment by michaelmior** [comment]
Great! Thanks. Feel free to close this as it probably doesn't need a separate issue to be tracked.
