### ISSUE TITLE
Clarify control chars behavior on `bat`

### ISSUE THREAD

**Issue by isinyaaa** [sharkdp/bat#1897]
Edit:

As explained below by @Enselic, `bat` doesn't support paging files that already contain colors, which has led me (and may lead others) to think this is a bug.

It'd be nicer if this could be clarified in the [troubleshooting section](https://github.com/sharkdp/bat#troubleshooting) of the README, so that no one else mistakes it for a bug (i.e. `bat` behaving exactly the same as `less -R` with those files).

Original issue:

> **Describe the bug you encountered:**
> 
> Using `less -R [filename]` directly renders output as expected, but when doing it through `bat` colors codes show up in output.
> 
> FYI I'm looking at some colored `make` output. On `less` it looks like this:
> 
> ![image](https://user-images.githubusercontent.com/39812919/136694699-87257622-cb88-4aaa-b31b-adc1a2658de3.png)
> 
> Then on `bat`:
> 
> ![image](https://user-images.githubusercontent.com/39812919/136694720-ddd2142f-c184-4139-a0e4-5db3ed5587c3.png)
> 
> **What did you expect to happen instead?**
> 
> Consistent behavior when using `less -R` alone and doing it through `bat`
> 
> **How did you install `bat`?**
> 
> `pacman`, but also tried using `cargo`
> 
> **bat version and environment**
> 
> 
> 
> #### Software version
> 
> bat 0.18.3 (b146958)
> 
> #### Operating system
> 
> Linux 5.14.9-arch2-1
> 
> #### Command-line
> 
> ```bash
> bat --diagnostic amd_build/modules1.clean.log 
> ```
> 
> #### Environment variables
> 
> ```bash
> SHELL=/usr/bin/fish
> PAGER='less -R'
> LESS=<not set>
> BAT_PAGER='less -RF'
> BAT_CACHE_PATH=<not set>
> BAT_CONFIG_PATH=<not set>
> BAT_OPTS=<not set>
> BAT_STYLE=<not set>
> BAT_TABS=<not set>
> BAT_THEME=Coldark-Dark
> XDG_CONFIG_HOME=<not set>
> XDG_CACHE_HOME=<not set>
> COLORTERM=truecolor
> NO_COLOR=<not set>
> MANPAGER=<not set>
> ```
> 
> #### Config file
> 
> ```
> # This is `bat`s configuration file. Each line either contains a comment or
> # a command-line option that you want to pass to `bat` by default. You can
> # run `bat --help` to get a list of all possible configuration options.
> 
> # Specify desired highlighting theme (e.g. "TwoDark"). Run `bat --list-themes`
> # for a list of all available themes
> --theme="Coldark-Dark"
> 
> # Enable this to use italic text on the terminal. This is not supported on all
> # terminal emulators (like tmux, by default):
> #--italic-text=always
> 
> # Uncomment the following line to disable automatic paging:
> #--paging=never
> 
> # Uncomment the following line if you are using less version >= 551 and want to
> # enable mouse scrolling support in `bat` when running inside tmux. This might
> # disable text selection, unless you press shift.
> --pager="less --RAW-CONTROL-CHARS --quit-if-one-screen --mouse"
> 
> # Syntax mappings: map a certain filename pattern to a language.
> #   Example 1: use the C++ syntax for .ino files
> #   Example 2: Use ".gitignore"-style highlighting for ".ignore" files
> #--map-syntax "*.ino:C++"
> #--map-syntax ".ignore:Git Ignore"
> ```
> 
> #### Compile time information
> 
> - Profile: release
> - Target triple: x86_64-unknown-linux-gnu
> - Family: unix
> - OS: linux
> - Architecture: x86_64
> - Pointer width: 64
> - Endian: little
> - CPU features: fxsr,sse,sse2
> - Host: x86_64-unknown-linux-gnu
> 
> #### Less version
> 
> ```
> > less --version 
> less 590 (PCRE2 regular expressions)
> Copyright (C) 1984-2021  Mark Nudelman
> 
> less comes with NO WARRANTY, to the extent permitted by law.
> For information about the terms of redistribution,
> see the file named README in the less distribution.
> Home page: https://greenwoodsoftware.com/less
> ```
>

**Comment by Enselic** [comment]
Closed by #1937
