### ISSUE TITLE
Feature request: Add flag for null output on null input

### ISSUE THREAD

**Issue by danielhoherd** [sharkdp/bat#1936]
### Description

I would love to see a flag that causes `bat` to return null output when it receives null input.

### Use case

This would make bat more clean when using it in conjunction with other commands that may produce null output in some circumstances. EG:

```
# k-bat() ( set -eo pipefail ; kubectl "$@" -o yaml | bat -l yaml ; )
$ k-bat get jklsjdfklsjfklsdf
error: the server doesn't have a resource type "jklsjdfklsjfklsdf"
───────┬───────────────────────────────────────────
       │ STDIN   <EMPTY>
───────┴───────────────────────────────────────────
```

**Comment by Enselic** [comment]
If you can live with not having decorations when there *is* output, you could use `--style=plain` as a workaround:

```bash
% cat /dev/null | bat --style=plain

% echo "something" | bat --style=plain 
something
```

The non-workaround approach would probably be to add a new `--style`. Like `plain-if-empty`. Would be nice to come up with something more elegant though.

**Comment by danielhoherd** [comment]
Using `bat -l yaml --style=plain --paging=never --number` works fine for me. We can close this if there's no other interest in adding this feature.

**Comment by maxnoe** [comment]
Could we re-open this issue? The requested feature is not available, and especially when using bat as pager for git, I think this is quite annoying:

```
❯ git diff
───────┬──────────────────
       │ STDIN   <EMPTY>
───────┴──────────────────
```
