### ISSUE TITLE
What is a custom theme "name" that `bat` recognizes?

### ISSUE THREAD

**Issue by emeinhardt** [sharkdp/bat#1947]
I am trying to add a custom theme for `bat`: any definition of the 'Mirage' variant of 'ayu' will suffice for my purposes, including [this sublime-color-scheme file](https://github.com/dempfi/ayu/blob/master/ayu-mirage.sublime-color-scheme).

Suppose I follow the documented instructions for adding a new custom theme. One step I have to take in order to use the new theme is specifying a theme "name" for `bat` that `bat` will recognize. In the case of my example theme, is that "ayu", "ayu-mirage", "ayu-mirage.sublime-color-scheme", or something else entirely? Is there documentation (or even just source code) that clarifies this?

**Comment by keith-hall** [comment]
Hi, the underlying syntax highlighting library that `bat` is using currently doesn't support `sublime-color-scheme` files - it can only handle the old `tmTheme` files:
https://github.com/trishume/syntect/issues/244

As for the name, it looks like it only considers the filename without the extension:
https://github.com/trishume/syntect/blob/d393d2bd1b519237ac1ecb4b2edee0c1796290fc/src/highlighting/theme_set.rs#L66

**Comment by sharkdp** [comment]
Closing in favor of #1948, if that's okay. Let me know if there is something left to do here.
