### ISSUE TITLE
Colours don’t work properly on rxvt-unicode

### ISSUE THREAD

**Issue by mina86** [sharkdp/bat#195]
![bat](https://user-images.githubusercontent.com/32383/43990292-0ed52536-9d52-11e8-824b-7cce0512ff89.png)
xterm on the left (`TERM=xterm-color`) and rxvt-unicode on the right (`TERM=rxvt-unicode`). One shows nice colours, the other doesn’t. Can’t explain that! `tput` works fine so it doesn’t appear to be an issue with terminfo/termcap/whatnot.

**Comment by mina86** [comment]
Neither `--color=always` nor `--paging=never` helped. 

```
$ bat --version
bat 0.4.1
$ urxvt --help 2>&1 |head -n1
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
$ echo TERM=$TERM COLORTERM=$COLORTERM
TERM=rxvt-unicode COLORTERM=rxvt-xpm
```

Changing `TERM` to `xterm` or `xterm-color` does not fix the issue.

Using `--theme=GitHub` enables some colours but still not as many as in xterm.

![bat-theme github](https://user-images.githubusercontent.com/32383/44300844-47d36380-a305-11e8-8c14-f9db2065cff7.png)

**Comment by sharkdp** [comment]
`urxvt` is not a true-color terminal. This means that `bat` will interpolate the colors from the syntax highlighting themes with ANSI 8-bit colors:

https://github.com/sharkdp/bat/blob/268577c6f99fda02c79715bc93a69655732d1d4c/src/terminal.rs#L5-L25

Could you please make sure that all ANSI colors render properly in your urxvt terminal?

This can be done by running [this script](https://gist.github.com/lifepillar/d4acaf918ae8d9bb2cab24d62abd768c), for example:
```
curl -s https://gist.githubusercontent.com/lifepillar/d4acaf918ae8d9bb2cab24d62abd768c/raw/a38d1e6a5500708d1f6318660f47b7702f53e009/256-colors.pl | perl
```

This is how it looks like for me:
![image](https://user-images.githubusercontent.com/4209276/44301294-c552a000-a314-11e8-8da8-39eb6b06e3f0.png)

**Comment by mina86** [comment]
All but grayscale works:
![colors](https://user-images.githubusercontent.com/32383/44301945-eec0fb00-a317-11e8-83dc-8b0d56da2700.png)

**Comment by mina86** [comment]
Mystery solved:
```
$ tput colors
88
```
Slackware ships with `urxvt` and `urxvt256c`. Running the latter makes `bat` work as expected.

**Comment by sharkdp** [comment]
:+1:
