### ISSUE TITLE
Allow interpreting binary file as text file

### ISSUE THREAD

**Issue by AntonHermann** [sharkdp/bat#1954]
Currently, when bat is run with a binary file, the output is as follows:
```sh
$ bat binary_file.pod
───────┬───────────────────────────────────
       │ File: binary_file.pod   <BINARY>
───────┴───────────────────────────────────
```
I didn't find any option to interpret the binary file as text (like [ripgrep](https://github.com/BurntSushi/ripgrep)s `-a`/`--text` flag).

## Suggested features
- add `--text` flag to force interpretation of binary as text
- automatically assume the binary to be text if `--language` is specified explicitly

**Comment by AntonHermann** [comment]
Thanks for the heads up on `-a`/`--show-all`, didn't consider that and didn't try it before. That shows the file, but it doesn't allow specifying `--language` and makes control characters visible.

My usecase is a file starting with a binary header (which I just ignore / skip over) followed by XML (text). I presume due to the binary header, `bat` recognizes the file as a binary file.

Running `bat --show-all binary_file.pod | bat --language xml` is close to what I want but it prints spaces, tab characters and so on explicitly.

This isn't a big problem however, using `-A` is good enough for me for the time being, tanks :)

**Comment by Enselic** [comment]
In that case it should work pretty well to do `strings binary_file.pod | bat --language xml `.

I'm not sure if it makes sense to do any changes in `bat` for this, so maybe we can close this ticket?

**Comment by sharkdp** [comment]
> In that case it should work pretty well to do `strings binary_file.pod | bat --language xml`.

Interesting idea. Does that really work well? You might have to choose a larger "min. string length" and include whitespace:
```bash
strings -n 100 --include-all-whitespace binary_file.pod | bat --language xml
```

My test case:
```bash
(dd if=/dev/urandom of=/dev/stdout bs=1024 count=16; cat src/lib.rs) | \
  strings -n 100 --include-all-whitespace | \
  bat -l rs
```
This works fine unless the random output happens to end with string characters as well.

**Comment by sharkdp** [comment]
I think this can be closed. I don't think we need a specialized feature for that in `bat`.
