### ISSUE TITLE
Only default color scheme over ssh

### ISSUE THREAD

**Issue by Breigner01** [sharkdp/bat#1962]
**Describe the bug you encountered:**

I can't seem to use a theme other than the default one over ssh.
I use bat as usual and I use Monokai as theme (I don't remember which variant).
When I bat a file over an ssh session it doesn't use Monokai and seems to fallback to another theme.
I tried setting the theme with the option `--theme` but nothing changes.

**What did you expect to happen instead?**

Use the monokai theme.

**How did you install `bat`?**

`pacman -S bat`

**bat version and environment**

#### Software version

bat 0.18.3 (b146958)

#### Operating system

Linux 5.10.79-1-lts

#### Command-line

```bash
bat --diagnostic docker-compose.yml 
```

#### Environment variables

```bash
SHELL=/usr/bin/zsh
PAGER=less
LESS=-R
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME='Monokai Extended'
XDG_CONFIG_HOME=/home/breigner01/.config
XDG_CACHE_HOME=/home/breigner01/.cache
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/breigner01/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
Did you run `bat --diagnostic` on your local machine or on the host you were connecting to via ssh? 

> I use bat as usual and I use Monokai as theme (I don't remember which variant).
> When I bat a file over an ssh session it doesn't use Monokai and seems to fallback to another theme.

Could you please tell us which commands you ran specifically?

**Comment by Breigner01** [comment]
I ran bat on the host I was connected to via ssh of course.

I tried running `bat --themes="Monokay Extended" file` as well as `bat file`.
They both use the same theme which is not monokai.

**Comment by Enselic** [comment]
Thanks for taking the time to report a bug. I can't imagine how this could be a bug in `bat`, but let's see if we can debug it together nevertheless.

Please provide screenshots/photographs that includes both the commands you run and what the output looks like. Above you say `Monokay` which I assume is just a typo, and that that was not the actual command you used? Screenshots/photographs removes that source of error, which helps us cut to the chase faster.

**Comment by Breigner01** [comment]
I'm sorry, I forgot to reply (I'm so overwhelmed with school).
So yeah I meant `Monokai` it's totally a typo (I wrote that on my phone).
Here, I join a screenshot of my usage:
![image](https://user-images.githubusercontent.com/55832366/144521506-c43ac950-50ec-499e-b166-1885e9ee3113.png)
I assume it's a bat bug or as a friend of mine suggested it could be missing options on the pager used by bat (whether it's less of another one)

**Comment by Enselic** [comment]
What makes you think that is not `Monokai Extended`? Looks like `Monokai Extended` to me.

That is both the default theme:

```rust
    pub fn default_theme() -> &'static str {
        "Monokai Extended"
    }
```

and the default theme in your environment:

```bash
BAT_THEME='Monokai Extended'
```

You can see how different themes look by doing `bat --list-themes`.

**Comment by Breigner01** [comment]
Well I was awaiting it to look the following way (I copied the file and used bat locally):
![image](https://user-images.githubusercontent.com/55832366/144568945-3ddf554c-8711-41ff-8ce1-b26a9ee07c01.png)
From what you're saying, how should I edit my env for bat to know it's 24 bits color capable?

**Comment by Enselic** [comment]
Quoting from the Troubleshooting section of the README.md:

[Source](https://github.com/sharkdp/bat#terminals--colors)

> Make sure that your truecolor terminal sets the `COLORTERM` variable to either `truecolor` or `24bit`. Otherwise, `bat` will not be able to determine whether or not 24-bit escape sequences are supported (and fall back to 8-bit colors).
