### ISSUE TITLE
BAT_THEME ignored?

### ISSUE THREAD

**Issue by rivertam** [sharkdp/bat#197]
Not much to say besides the image =)

![2018-08-14_13-43-20](https://user-images.githubusercontent.com/4165105/44108327-0c341170-9fc8-11e8-86b9-59ac202a19c0.png)

I also have the `BAT_THEME` set in my `.zshrc` but I wanted to make sure there was really nothing getting in the way there.

I see nothing particularly wrong with the code, so I don't know why this would be. I thought maybe I'd set it somehow more permanently like through an alias or something, but I'm seeing nothing else regarding bat in my `.zshrc` and `~/.config/bat` doesn't even exist.

Any ideas?

**Comment by citizen428** [comment]
Same here 😢 Had a quick look through the code, but couldn't find any obvious problem.

**Comment by CWSpear** [comment]
Same issue. I have a light theme on my terminal, and the default theme isn't light-friendly... so I can't use this without typing `--theme=SomeTheme` every time :(

**Comment by sharkdp** [comment]
Sorry guys, the `BAT_THEME` environment variable is supported on `master`, but I haven't released a new version, yet.

**Comment by rivertam** [comment]
@sharkdp Gotcha. I'm not sure what the general consensus on versioning within the hivemind is (if there is one/if it matters), but I think it makes sense to bump the version in the `Cargo.toml` right after a release. I checked the `Cargo.toml`, saw it was the same version, and figured they were in sync. Not sure if there's a more convenient way of doing it.

Any general timeline on next release?

**Comment by CWSpear** [comment]
I wouldn't consider this closed until there is a release. Other people are going to come here wondering what happened and it's still an outstanding issue.

**Comment by sharkdp** [comment]
> @sharkdp Gotcha. I'm not sure what the general consensus on versioning within the hivemind is (if there is one/if it matters), but I think it makes sense to bump the version in the Cargo.toml right after a release. I checked the Cargo.toml, saw it was the same version, and figured they were in sync. Not sure if there's a more convenient way of doing it.

I have been thinking about this in the past, but bumping the version right after the release seems unpractical to me. I usually don't know whether the next release will be a minor or major release.

The standard view on GitHub always represents the head of the `master` branch and therefore the documentation in the README will reflect that. I know it is unfortunate, but the right way to go (... :confused:) would be to read the README of the released version, either the one from the release archives or by browsing the repository in the tagged state: https://github.com/sharkdp/bat/tree/v0.4.1.

I'd be open to hints on how to handle this better, though.

I hope to release a new version very soon.

**Comment by CWSpear** [comment]
`BAT_THEME` is not working, that's the issue.

>I'd be open to hints on how to handle this better, though.

The README was updated 26 days ago, I don't think it's such a bad thing to more frequent releases. That's probably the most straightforward answer. The time between a new feature and a release should be short can easily be hours on a project like this (one that you don't work on full time).

The last release was in May. I don't know what else has been going on in development, but if you're on top of releasing new features, etc, it'd be perfectly appropriate to have had a release that just adds one feature (such as the `BAT_THEME`).

Alternatively, you could wait until closer to a release to update docs, or have a changelog, or have beta releases and put things in the docs like, "...or set the BAT_THEME environment (available in 0.5 beta)..." and then remove the "beta" part when you release it (or just say, "available in the upcoming 0.5 version").

**Comment by sharkdp** [comment]
There are two issues with this:

* Even though a lot is automated, creating new releases still [takes some time](https://github.com/sharkdp/bat/issues/138).
* We do have lots of tests and CI, but new releases are still a risk (there could be regressions, new bugs, something going wrong with the deployment, ...). I also usually want to have some time to test new features before releasing them.

**Comment by sharkdp** [comment]
The new release is out: [bat 0.5](https://github.com/sharkdp/bat/releases/tag/v0.5.0).
