### ISSUE TITLE
default `--theme` should be neutral

### ISSUE THREAD

**Issue by ngam** [sharkdp/bat#1978]
Hi, thank you for the good work --- I like this utility. I found the default color theme unusable (it's [supposed to be](https://github.com/sharkdp/bat#highlighting-theme) for dark mode only) and so I recommend you set a neutral default theme, for example `ansi`.

**Comment by milespossing** [comment]
Alright I've closed the above PR, as some pretty good arguments were made against this change, but I would recommend looking at the [config file documentation](https://github.com/sharkdp/bat#configuration-file), specifically [the formatting section](https://github.com/sharkdp/bat#format)

**Comment by ngam** [comment]
> Alright I've closed the above PR, as some pretty good arguments were made against this change, but I would recommend looking at the [config file documentation](https://github.com/sharkdp/bat#configuration-file), specifically [the formatting section](https://github.com/sharkdp/bat#format)

Hey thanks for looking into this. I am well aware of the formatting and it is relatively easy --- however, you should keep that PR open to gather more opinions. I will offer a counter point shortly.
