### ISSUE TITLE
Allow bat to output remote files using scp

### ISSUE THREAD

**Issue by eliminmax** [sharkdp/bat#1982]
Vim allows editing of remote files using the syntax `$ vim scp://example.org/~/path/to/script.sh`, and I think it would be neat for bat to be able to do something similar. Currently dealing with college finals, and not very experienced with Rust myself, otherwise I'd look into implementing it myself and opening a pull request - might still do that over winter break.

**Comment by sharkdp** [comment]
Thank you for your feedback. I think there are better ways to achieve this. Like an ssh-mount. Or something like:
```bash
ssh example.com cat script.sh | bat -lsh
```

**Comment by eliminmax** [comment]
> Thank you for your feedback. I think there are easier ways to achieve this. Like an ssh-mount. Or something like:
> 
> ```shell
> ssh example.com cat script.sh | bat -lsh
> ```

Fair enough - that's basically what I do now, and, like I initially said, I thought it would be neat for bat to handle it itself. Thanks for responding to the idea!
