### ISSUE TITLE
Nano

### ISSUE THREAD

**Issue by leoheck** [sharkdp/bat#1983]
First of all, this thing is awesome. Seriously, I am in love with it.
Now, my big important questions. Is there any way that I can dress nano with this beautiful thing?
I don't enjoy using nano anymore since I am comparing with the great bat

**Comment by exploide** [comment]
I think nano has its own syntax highlighting system, but if you like tools like bat, you might check out [micro](https://github.com/zyedidia/micro) as an editor.

**Comment by leoheck** [comment]
What I like about bat is that it is like cat, the usability is the same, except that bat is beautiful. 

Micro is awesome too, thanks for sharing it, but it looks like micro is not like nano, so I cannot have an alias micro=nano because they don't work the same way. 

I would substitute these tools on my machine, only if they can be used interchangeably, because when I have to use other computers, what happens a lot, I will have to use the standard cat/nano and other default tools that are already installed.

**Comment by leoheck** [comment]
Actually, I may be wrong. It kind of works like nano. Thanks @exploide
