### ISSUE TITLE
Allow printing of specific definitions in source code files

### ISSUE THREAD

**Issue by ev-dev** [sharkdp/bat#1984]
After 20min of diddling around in my terminal trying to get quick looks at various function definitions within some source code files, I had the rough idea that this might be something bat/batgrep could potentially be very good at given its internal use of language syntaxes.

Basically, I was hoping to cat/print out specific function/variable definitions within source code files from the command line without opening an editor, given I knew roughly what the names of those funcs/vars were. That would generally mean the tool probably needs some AST like representation in order to first regex match only func/var names, and then secondly to know beginning/end of the matched name's definition in order to finally print the range of lines of the given file (more specifically the range of characters, not just lines of course).

I realize most in-terminal editors like vim/emacs/etc may already this capability, but probably not without some DSL scripting especially for non-interactive output, and I'm not really eager to dive into learning vimscript/etc just yet 🙃 I've done a bit of searching around for cli tools with this capability, but I wasn't able to find any simple solution so I thought it would be really cool to work on such a feature within a project I already enjoy like bat (not sure if this issue would be better placed in [bat-extras](https://github.com/eth-p/bat-extras/))

If such a thing isn't out there somewhere, I'd love to try contributing to it wherever most relevant, anyone have any thoughts?

**Comment by keith-hall** [comment]
Thanks for the suggestion. You may be interested to see one of the examples `syntect` - the syntax highlighting library `bat` uses - ships with: https://github.com/trishume/syntect/blob/master/examples/synstats.rs

It counts how many lines are comments, function definitions etc. But `sublime-syntax` based parsing doesn't generate an AST, so for finding where a function ends in a language-agnostic manner is a bit trickier. For brace-based languages, you can check for the punctuation begin/end scopes and track what nesting level you are in, but for i.e. Python, you'd have to check indentation...
I believe this is therefore out of scope for `bat`, the closest you can achieve is like Sublime Merge, where it shows the closest preceding method /class name as a diff context. Unfortunately, as `bat-extras` has no access to the scopes assigned, I think it's fair to say its out of scope there too.

My understanding is that `tree-sitter` is a library designed to build ASTs for source code, you may have better luck starting/searching from there.

**Comment by Freed-Wu** [comment]
> tree-sitter is a library designed to build ASTs for source code

There exists <https://github.com/foxfriends/syncat> to highlight code by tree-sitter not sublime-syntax.
However, bat's sublime-syntax support more file types than syncat's tree-sitter. Is it possible that use bat to highlight code by tree-sitter, if tree-sitter doesn't support, use sublime-syntax as a fallback? Just like [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) use vim syntax as a fallback of tree-sitter. It should can provide user better highlight result, include **specific definition** parsed by AST, not only some tokens parsed by regex.
