### ISSUE TITLE
In tmux working environment, bat does not display the file content properly

### ISSUE THREAD

**Issue by MF-ReStart** [sharkdp/bat#1986]
Hi, I'm used to working with tmux, how can bat work properly in a tmux environment, will this be implemented in the future?
This is affected by the tmux environment, which seems to be incompatible
![image](https://user-images.githubusercontent.com/50358485/147353353-df487420-e4ce-4500-a152-311962af890a.png)
![image](https://user-images.githubusercontent.com/50358485/147353382-f46b5181-0574-4238-ad8b-d70a7c28b908.png)
Will you consider this in the future?

**Comment by keith-hall** [comment]
Hi, does the advice at https://github.com/sharkdp/bat#terminals--colors help? If not, please run `bat --diagnostic` from within a tmux session and paste the output here.

**Comment by MF-ReStart** [comment]
My terminal is supporting normal display of bat colors, line numbers, and grids, but I can't display them properly after using tmux window. I'm not sure if tmux has modified my terminal character set or what.
Is my bat version too low? -Is diagnostic correct?
![image](https://user-images.githubusercontent.com/50358485/147424475-9d6773f8-0ef5-40f0-976d-3976bd87bc30.png)

**Comment by keith-hall** [comment]
It's likely your version is too old, the ones shipped with the OS generally are not super recent. You can always check with `batcat --version` - diagnostics were added in https://github.com/sharkdp/bat/releases/tag/v0.18.0 in March.

**Comment by MF-ReStart** [comment]
It's really because the version is too low. v0.18 version of bat works fine in tmux environment now.
