### ISSUE TITLE
Weird behavior with control characters

### ISSUE THREAD

**Issue by Jaakkonen** [sharkdp/bat#1989]
With following file
```
$ hexdump -C /tmp/a
00000000  1b 5b 3f 32 35 6c 1b 37  1b 37 1b 5d 30 3b 2f 74  |.[?25l.7.7.]0;/t|
00000010  6d 70 07 0a 1b 5b 33 34  6d 2f 74 6d 70 1b 5b 33  |mp...[34m/tmp.[3|
00000020  39 6d 0a 0d 1b 5b 33 35  6d e2 9d af 1b 5b 33 39  |9m...[35m....[39|
00000030  6d 20 1b 5b 3f 31 32 6c  1b 5b 3f 32 35 68 1b 5b  |m .[?12l.[?25h.[|
00000040  3f 32 35 6c 1b 38 1b 5b  3f 31 32 6c 1b 5b 3f 32  |?25l.8.[?12l.[?2|
00000050  35 68 1b 5d 30 3b 74 6d  70 3a 20 65 78 69 74 07  |5h.]0;tmp: exit.|
00000060
```
I get really weird behavior.

`alacritty -e dash`:
![image](https://user-images.githubusercontent.com/33450373/147375621-97473688-85cc-4c9b-b729-9010bd2343c5.png)
`alacritty -e bash`:
![image](https://user-images.githubusercontent.com/33450373/147375629-d0a5cad8-26cc-46c6-9a3f-b93433083498.png)

With `-A` no weird control characters seem to be getting through:
`alacritty -e dash`:
![image](https://user-images.githubusercontent.com/33450373/147375647-ad2e1819-af9a-4695-8432-fd481f5061c4.png)

Is `bat` supposed to let these control characters through like this or filter those? It looks a bit alarming if a user could craft a file that would look empty with `bat file` but actually contain stuff in `bat -A file` (although that kind of behavior would be consistent with `cat` :D)

**Comment by Enselic** [comment]
Consistency with cat is an important feature of bat. Also see https://github.com/sharkdp/bat#garbled-output

**Comment by Jaakkonen** [comment]
This looks like intended behavior in that case! I only searched for "control characters" in the docs so I couldn't find that part in the `README.md`, my bad. Thanks!

**Comment by Enselic** [comment]
Thanks for the feedback! If you tried to look for the answer in the README.md but failed, that is a failure of README.md :)

So let's add the term "control characters" to that README.md section so that others can find it in the future.
