### ISSUE TITLE
v0.18.3 not building with Rust 1.57 on Linux x64

### ISSUE THREAD

**Issue by Kage-Yami** [sharkdp/bat#1991]
**Describe the bug you encountered:**

Not able to build version 0.18.3 using `cargo install bat` on Rust 1.57.0, `x86_64-unknown-linux-gnu`. (Originally encountered when trying to install `cargo-expand`, but this happens when trying to install just `bat` as well.)

```sh
❯ cargo install bat
...
error[E0599]: no method named `add_from_folder` found for struct `ThemeSet` in the current scope
  --> /home/yami/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.3/src/assets.rs:59:33
   |
59 |             let res = theme_set.add_from_folder(&theme_dir);
   |                                 ^^^^^^^^^^^^^^^ method not found in `ThemeSet`

For more information about this error, try `rustc --explain E0599`.
error: failed to compile `bat v0.18.3`, intermediate artifacts can be found at `/tmp/cargo-installpeRs2H`

Caused by:
  could not compile `bat` due to previous error
```

**What did you expect to happen instead?**

`bat` builds without error.

**How did you install `bat`?**

```sh
cargo install bat
```

---

**bat version and environment**

```sh
❯ rustc -Vv   
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

**Comment by Enselic** [comment]
That's because a new version of syntect was released with changed feature set

`cargo install --locked bat` as recommended in readme should work

**Comment by Emoun** [comment]
I had the same problem as @Kage-Yami and can confirm that using `cargo install --locked` with `bat` and `cargo-expand` solved the issue.

@Enselic, I tried to look at `syntect` feature set and can see they added the feature `plist-load`, but cannot see how that should result in breaking `bat`'s build. Could you elaborate?

Also, this makes 4.7.0 of `syntect` incompliant with semver right? 

lastly, does anyone know why lockfiles aren't used by default when present for binaries?

**Comment by ehuss** [comment]
@Enselic Regarding https://github.com/trishume/syntect/pull/345, would you possibly consider reverting that change? Moving existing public APIs behind a feature is a semver-breaking change, and generally shouldn't be done in a minor release.

**Comment by Enselic** [comment]
This is an oversight on my part. Since syntect v4.7.0 has been yanked now there is no action to take for bat. A fix will be made in syntect, tracked in https://github.com/trishume/syntect/issues/402. So we can close this issue.

Thank you for quickly reporting this issue.
