### ISSUE TITLE
Executing bat without any file specified reads inputs from stdin

### ISSUE THREAD

**Issue by Leonardo-Gerling** [sharkdp/bat#1995]
**Describe the bug you encountered:**

When just executing `bat`, the prompt gets blank, and every time you enter a string in your terminal, bat outputs a table with the entered string. Example here:
```
leo in 🏠
➜ bat                
hello
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ hello
exit
   2   │ exit
please :(
   3   │ please :(
^C
leo in 🏠
➜ 
```

**What did you expect to happen instead?**

Something that handles a "no-input" executing. Maybe just print out the usage and say, that a file has to be specified.

**How did you install `bat`?**

`sudo pacman -S bat`

---

**bat version and environment**
#### Software version

bat 0.18.3 (b146958)

#### Operating system

Linux 5.15.11-1-MANJARO

#### Command-line

```bash
bat --diagnostics
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS=-R
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=OneHalfDark
XDG_CONFIG_HOME=/home/leo/.config
XDG_CACHE_HOME=/home/leo/.cache
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/leo/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by Leonardo-Gerling** [comment]
Sorry, I meant to chose the label "enhancement".

**Comment by Enselic** [comment]
One important feature of bat is cat compatibility. Since this is how cat behaves, bat also needs to behave like this.

**Comment by Leonardo-Gerling** [comment]
@Enselic Oh, I did not know that. Sorry for the irrelevant issue.

**Comment by Enselic** [comment]
No worries! Thanks for taking the time to make an otherwise good bug report :)
