### ISSUE TITLE
Is there a way to get all highlighting tags?

### ISSUE THREAD

**Issue by JosefLitos** [sharkdp/bat#1996]
I would like to create a custom theme, bud I cannot find any place where all highlight tags would be given. For example, when I preview a javascript file, function braces, like 
```js
function test() {}
```
in javascript don't get any highlighting if I don't set a highlight for `meta`. At the same time, if I do so, I get the same highlight on random functions and variables from lua, such as
```lua
mapping(mapping.complete())
cmp.config.disable = 0
```
here, mapping, complete and config.disable would be the same color.

Why aren't all javascript parentheses (type respecting, if necessary) the same, but lambda parentheses work under punctuation, but all other don't. 
In addition to javascript issues, what are `import from` highlight tags and why do they belong under keyword,operator, shouldn't it be just keyword?
I don't know what is the tag for changing dot highlights, it's not under punctuation, but also somewhere under keyword.operator.

My main question is: Is there a way to get all used, or at least available, highlighting tags?

**Comment by keith-hall** [comment]
most syntaxes should scope things consistently, and thus there is a guide for color schemes of what scopes to target: http://www.sublimetext.com/docs/scope_naming.html

you can just open the relevant sublime-syntax file from this repo/submodule to see all scopes it uses.

**Comment by JosefLitos** [comment]
I haven't managed to find lua among the syntaxes. Could you please direct me? Or if there is some sort of default.
