### ISSUE TITLE
Add syntax highlighting for C (.h) header files?

### ISSUE THREAD

**Issue by Adamkadaban** [sharkdp/bat#1998]
The syntax highlighting would be exactly the same as any .c file, so having that for .h files would be amazing 

I've noticed there's already syntax highlighting for .cpp files, so I think it might be a relatively easy change to make?

Alternatively, is there any way I could change this myself manually? Or maybe even add custom syntax highlighting rules for certain file extensions?

**Comment by keith-hall** [comment]
It looks like this should already be working, though I notice we don't have a syntax-highlighting-regression test for it...
https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/C%2B%2B/C.sublime-syntax#L7
https://github.com/sharkdp/bat/blob/d6ed5e67469dde0e7b9523c7754761b9203ca370/src/syntax_mapping.rs#L42

You could try adding an explicit mapping in your config file for it, as described at:
https://github.com/sharkdp/bat#adding-or-changing-file-type-associations

`--map-syntax='*.h:C'`

**Comment by Adamkadaban** [comment]
Thanks, it worked. Turns out it was a problem with how I alias batcat
