### ISSUE TITLE
Make 'ash' scripts recognised by default

### ISSUE THREAD

**Issue by sc0ttj** [sharkdp/bat#201]
I want `bat` to do auto shell-syntax highlight of files starting `#!/bin/ash` (the SHELL included in Busybox).. 

I tried modifying the Sublime syntax setting for Bash (in /assets, after pulling down sub-modules, and going into 'Packages' folder, modifying the relevant `.sublime-syntax` file, then using create.sh), but the resultant compiled bin won't highlight my Ash scripts without using the `-l sh` param ... I also tried copying the relevant `.sublime-syntax` file to `./assets/syntaxes` and re-ran, but no luck... 

Has anyone else managed to build a custom binary, with your modified syntax highlighting settings working?

**Comment by sharkdp** [comment]
Did you re-compile `bat` after running `create.sh`? The syntax and theme sets are included in the `bat` executable during compilation:

https://github.com/sharkdp/bat/blob/5b421b455d2df28e21f3b49b86ede3a738d12b4a/src/assets.rs#L83-L85

**Comment by sharkdp** [comment]
Another way would be to use `bat`'s [customization features](https://github.com/sharkdp/bat#customization). This is slightly slower than the custom binary version, though.

**Comment by sc0ttj** [comment]
I did re-compile, got a 9mb binary, instead of the 5mb release version I had.. But no support for Ash scripts :/  .. I tried twice to make sure I was 'doing it right', and also tried with the modified `.sublime-syntax` file in `syntaxes` dir as well (as opposed to just leaving it in the `Packages` dir... 

Maybe the "proper" fix is for the Shell syntax config file to be fixed in the relevant sublime repo...

**Comment by sharkdp** [comment]
How exactly did you modify the `Bash.sublime-syntax` file? I'm assuming you modified the `first_line_match` regex?

> got a 9mb binary, instead of the 5mb release version I had

This is probably just because of debug symbols. You can call `strip path/to/bat` to remove them.

**Comment by sc0ttj** [comment]
I did modify the `first_line_match` regex ... Made it something like `bash|ash|sh` .. And added a couple of custom file extensions as needed... then ran create.sh, then re-compiled..

**Comment by sharkdp** [comment]
One more idea: have you ever used `bat cache --init`? If so, you might need to `bat cache --clear`.

**Comment by sc0ttj** [comment]
I did try it, not sure when is the best time to run it though.. I ran it before compilation.. 

Will try again tomorrow..

**Comment by sharkdp** [comment]
The following works for me:

```
▶ git clone https://github.com/sharkdp/bat --recursive

▶ cd bat

▶ vim assets/syntaxes/Packages/ShellScript/Bash.sublime-syntax  # add 'ash' extension

▶ cargo build --release

▶ bash assets/create.sh

▶ cargo build --release

▶ target/release/bat --list-languages | grep 'Bourne Again Shell'
Bourne Again Shell (bash) sh, bash, ash, zsh, fish, .bash_aliases, 

```

**Comment by sc0ttj** [comment]
I was able to make it work, followed above, but had to edit `create.sh` to use the `bat` binary in `target/release`, in order to make it not bug out at the `--blank` option.. 

I now have Ash scripts automatically being highlighted the same as Bash scripts :)

**Comment by sharkdp** [comment]
Great, glad everything worked out.
