### ISSUE TITLE
Has bat some command like F in less?

### ISSUE THREAD

**Issue by jfernandz** [sharkdp/bat#2017]
I'm not sure if I can use `bat` as when in `less` I press `shift+f` to scroll forward.

From less manpage:
```
F      Scroll forward, and keep trying to read when the end of file is reached. 
        Normally this command would be used when already at the end of the file. 
        It is a way to monitor the tail of a file which is growing while it is being viewed. 
        (The  behavior is similar to the "tail -f" command.) To stop waiting for more data, 
        enter the interrupt character (usually ^C). On some systems you can also use ^X.
```

I'm aware of [this alternative](https://github.com/sharkdp/bat#tail--f) but it doesn't work in the same way.

**Comment by sharkdp** [comment]
> I'm aware of [this alternative](https://github.com/sharkdp/bat#tail--f) but it doesn't work in the same way.

No, I think this is the only option you have. Why doesn't it work for you?

**Comment by jfernandz** [comment]
@sharkdp it does work, but not in the very same way ... I like the less behaviour, you are able to pause/resume the file reading and also you have the capabilities of the pager. 

With tail you aren't able to pause the reading and move across the file.

**Comment by sharkdp** [comment]
Unfortunately, this is not going to be possible unless we implement #1053 (see bullet point: builtin follow support).

**Comment by jfernandz** [comment]
So I see you have considered this and it's apparently planned :wink:
