### ISSUE TITLE
PAGER=batcat turns into a fork nightmare

### ISSUE THREAD

**Issue by rsamuelklatchko** [sharkdp/bat#2023]
I decided to make batcat my PAGER and when I tried setting:

    PAGER=batcat

it didn't work. After some troubleshooting I realized that batcat was forking/execing itself and was able to fix it by also adding:

    BAT_PAGER=less

while this solved the problem it was not obvious. One suggestion is when reading PAGER, if the value is the binary name (or ends with /{binary_name}) the value is ignored and the default is used instead.

**Comment by Enselic** [comment]
Thanks for reporting!

There is code to prevent that from happening, but it does not take into account that the binary can be called something other than `bat`.

See https://github.com/sharkdp/bat/blob/9287cf6b0ba98be2611b5a682dffcc1a8583b151/src/pager.rs#L105

I would be happy to review PRs that solves this

**Comment by rsamuelklatchko** [comment]
My thought would be to modify PagerKind::from_bin to support other names. I have a couple of ideas:

1. Just add "batcat" (I'm on Debian which is what the binary is named) and possibly any other common alternate names if you know of any.
2. Find the name the binary is being run as using `env::args`.

For #2, I'm thinking to reuse https://github.com/sharkdp/bat/blob/9287cf6b0ba98be2611b5a682dffcc1a8583b151/src/pager.rs#L43-L46 to exctract the name from env::args[0].

**Comment by Enselic** [comment]
My first choice would be 2., but the code to get the program name is more something like `std::env::args().nth(0)`

Or even better is `std::env::args_os().nth(0)` but that might require a bigger change

**Comment by rsamuelklatchko** [comment]
I have a code fix but having not used GitHub I'm not sure if exactly how to send it to you. What I'm suggesting is this:

    impl PagerKind {
        fn from_bin(bin: &str) -> PagerKind {
            use std::path::Path;
    
            let file_stem = Path::new(bin).file_stem();
    
            match file_stem.map(|s| s.to_string_lossy()).as_deref() {
                Some("bat") => PagerKind::Bat,
                Some("less") => PagerKind::Less,
                Some("more") => PagerKind::More,
                Some("most") => PagerKind::Most,
                _ => {
                    if env::args_os()
                        .nth(0)
                        .map(|arg0| Path::new(&arg0).file_stem() == file_stem)
                        .unwrap_or(false)
                    {
                        PagerKind::Bat
                    } else {
                        PagerKind::Unknown
                    }
                }
            }
        }
    }

**Comment by mslot** [comment]
This can be closed

**Comment by Enselic** [comment]
Closed by #2235
