### ISSUE TITLE
Weird output with cut as pager

### ISSUE THREAD

**Issue by xeruf** [sharkdp/bat#2024]
**Describe the bug you encountered:**

I am trying to use cut as pager to prevent overlong lines from cluttering my screen in a script:

```sh
❯ bat .yarnrc
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .yarnrc
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
   2   │ # yarn lockfile v1
   3   │ 
   4   │ 
   5   │ lastUpdateCheck 1641991267873
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────
❯ bat .yarnrc --style=plain --pager='cut -c-70'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS F
# yarn lockfile v1


lastUpdateCheck 1641991267873
❯ bat .yarnrc --style=plain --pager='cut -c-40'
# THIS IS AN AUTOGENE
# yarn lockfile v1


[38;2;220;223;228mlastUpdateCheck 16419
```

**What did you expect to happen instead?**

no garbled output in the last example

**How did you install `bat`?**

pacman

**bat version and environment**

#### Software version

bat 0.18.3 (b146958)

#### Operating system

Linux 5.16.0-arch1-1

#### Command-line

```bash
bat .yarnrc --style=plain '--pager=cut -c-40' --diagnostic 
```

#### Environment variables

```bash
SHELL=/usr/bin/zsh
PAGER=less
LESS='--RAW-CONTROL-CHARS --ignore-case --LONG-PROMPT --jump-target=5 --incsearch'
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=OneHalfDark
XDG_CONFIG_HOME=/home/janek/.config
XDG_CACHE_HOME=/home/janek/.local/cache
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='less --squeeze-blank-lines +Gg'
```

#### Config file

Could not read contents of '/home/janek/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> cut --version 
cut (GNU coreutils) 9.0
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David M. Ihnat, David MacKenzie, and Jim Meyering.
```

**Comment by sharkdp** [comment]
if you do this (use `cut` as a pager), you are *post*-processing `bat`s output. that's not a good idea because `bat` outputs ANSI escape sequences and `cut` does not understand them.

You'd rather have to *pre*-process `bat`s input (`cut … | bat -l yarn`) to achieve the desired result. Or experiment with `bat`s `--terminal-width`/`--wrap` options.

**Comment by xeruf** [comment]
The problem is that I want to handle everything through bat to see filenames highlighted and now those nice rulers. Since the last example uses a plain style, `bat` is not supposed to use any escape codes either.

The issue with `terminal-width` is that I want any particular line to span at most two lines - thus I can see that the file has overlong lines, without garbling my whole screen. That is why I give `cut -c-$(echo "$(tput cols)*1.9" | bc | cut -d. -f1)` as pager in that particular script.

**Comment by sharkdp** [comment]
I'm closing this for now as I don't really see us adding special code to handle this somehow, but please feel free to comment here if you think there is a way to fix it.
