### ISSUE TITLE
Obtain syntect Theme structs from theme name when using bat as a library

### ISSUE THREAD

**Issue by dandavison** [sharkdp/bat#2026]
Hi bat developers! Delta has, since the beginning, made use of bat's very helpful collection of language syntax and highlighting theme definitions. Until now, that's involved bat code vendored in the delta repo. I'd love to use the bat library for this. However, from a quick look, it appears that while the syntect syntax structs are exposed, the syntect themes are not (only theme name strings are exposed). Would it be possible (and fit with your aims) to provide an API to look up a syntect theme struct by theme name?

Thanks for all the work.

**Comment by Enselic** [comment]
Hi and thanks for the request!

I think the first step here would be to replace the vendored code in the delta repo with a normal bat Cargo dependency and see how far that takes you.

I'm thinking you would leave in placeholders in the code like

```
// Here we would like to use any theme, not just the default
let theme = default_theme();
```

but otherwise get the code to compile and run. Once that is functional, we can more easily prototype what kind of API that is missing.

Does that sound reasonable?

**Comment by sharkdp** [comment]
> Would it be possible (and fit with your aims) to provide an API to look up a syntect theme struct by theme name?

Not that I disagree with the approach suggested by @Enselic, but to give a more direct answer: yes, I think we generally want to provide this functionality to enable `delta` (and others) to use `bat`-as-a-library.

Note that we currently have this notice in the documentation regarding the usage of the "expert" API (everything except for the things that are directly accessible via `bat::Xyz`):

> If you need more control, you can also use the structs in the submodules […], but note that the API of these internal modules is much more likely to change. Some or all of these modules might be removed in the future.

Meaning that the API of (for example) `bat::assets::HighlightingAssets` might not (yet) be well designed for public usage. So in this sense, an approach as described above might be very helpful. Not just for new public-facing functionality, but also for the existing things inside submodules.

**Comment by dandavison** [comment]
Thanks @Enselic & @sharkdp! I've made a proof-of-principle branch in delta: https://github.com/dandavison/delta/pull/903

However, it isn't correct yet and  in local development I'm hitting the `malloc: can't allocate region` errors due -- I believe -- to the recent syntect bug. Would you be able to tell me which syntect version / revision I should be using in delta and bat, and whether I need to change my local workflows? I've run `cargo clean` (and `rustup update`).

**Comment by dandavison** [comment]
> in local development I'm hitting the `malloc: can't allocate region` errors

Please ignore that -- this problem has gone away (I'm not sure why it was occurring). So,

- Proof-of-principle PR exposing `get_syntax_set `, `get_theme_set `, and `LazyThemeSet ` in bat API: https://github.com/sharkdp/bat/pull/2030
- Companion delta PR removing vendored code and using bat assets API: https://github.com/dandavison/delta/pull/903

I will add comments to the delta PR highlighting places where I have used something from bat that is not currently exposed.

> Note that we currently have this notice in the documentation regarding the usage of the "expert" API

Right. I think I would still be happier responding to breaking bat expert API changes than manually updating vendored code.
