### ISSUE TITLE
bat color output with markdown issues

### ISSUE THREAD

**Issue by laoshaw** [sharkdp/bat#2031]
**Describe the bug you encountered:**

A simple markdown with below content: `he's the one`, the text after `'` will be colored with `bat -l c` which should not.
![x](https://user-images.githubusercontent.com/18351761/149649537-54144a44-ea55-4335-8983-dc19bd151463.png)

...

**What did you expect to happen instead?**

the rest of test should never to highlighted.

...

**How did you install `bat`?**

cargo install bat

---

**bat version and environment**

#### Software version

bat 0.18.3

#### Operating system

Linux 5.11.0-46-generic

#### Command-line

```bash
/home/xyz/.cargo/bin/bat -l c test.md --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='sh -c '\''col -bx | bat -l man -p'\'''
```

#### Config file

Could not read contents of '/home/xyz/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Comment by keith-hall** [comment]
I don't get it - highlighting Markdown content using the C syntax highlighting rules... Did you try without `-l c`?

**Comment by laoshaw** [comment]
oops, it's my mistake, I changed alias to bat by mistake somehow. sorry for the noise.
