### ISSUE TITLE
How does bat leave the terminal in the same position?

### ISSUE THREAD

**Issue by UmbralReaper** [sharkdp/bat#2035]
When I use other command line software such as `micro`, invoking it and exiting moves my previous invocations up in the terminal. What does bat do differently to this software?

E.g.  After invocation of command
```
$ ls
file.txt
(top of terminal)
$ micro file.txt
```

```
(top of terminal) 
$ ls
file.txt
$ bat file.txt
```

Note that this is on windows, using Windows Terminal.

**Comment by keith-hall** [comment]
as far as I know, `bat` itself isn't doing anything special - it's just using your default pager. Normally this would be `less` - not sure about on Windows Terminal though.
