### ISSUE TITLE
Regression in support for ANSI escape sequences in bat-0.19 (works in 0.18.3 without disabling syntax highlighting)

### ISSUE THREAD

**Issue by neoh4x0r** [sharkdp/bat#2040]
**Describe the bug you encountered:**

Bat does not seem to support ANSI escape sequences.

```
$ wget cheat.sh/ls

$ /bin/cat ls
 cheat:ls 
# To display everything in <dir>, excluding hidden files:
ls <dir>

$ bat --pager=never --style=header ls
File: ls
[48;5;8m[24m cheat:ls [24m[0m
[38;5;246;03m# To display everything in <dir>, excluding hidden files:
[38;5;252mls[39m[38;5;252m [39m[38;5;252m<[39m[38;5;252mdir>[39m
```
**What did you expect to happen instead?**

Since bat is touted as being a cat clone/replacement, I would expect it to support ANSI escape sequences just like cat does.

**How did you install `bat`?**

bat 0.19.0 (59a8f58) installed from https://github.com/sharkdp/bat/releases/tag/v0.19.0
using dpkg on Debian 10 Buster.

**Comment by neoh4x0r** [comment]
I see that there was a pull request that changed README.md to reflect that bat would have trouble with ANSI escape sequences. https://github.com/sharkdp/bat/pull/1990

But I see no reason why the control sequences can't be processed before syntax highlighting is performed (or stripped allotether).

**Comment by elsaco** [comment]
@neoh4x0r this is with bat-0.18.3:

![bat_ansi_ls](https://user-images.githubusercontent.com/3933920/150902370-b76aa703-9d35-4ce0-b3f5-f42edacec5e1.png)

**Comment by neoh4x0r** [comment]
@elsaco The issue is with bat-0.19 (not 0.18.3)

```
     Distribution: Debian 
          Version: 10 (debian version: 10.11)
Support Lifecycle: N\A
         Codename: 10 (buster) 
         Fullname: Debian GNU/Linux 10 (buster) 

      Kernel Name: Linux
   Kernel Release: 5.10.0-0.bpo.9-amd64
   Kernel Version: #1 SMP Debian 5.10.70-1~bpo10+1 (2021-10-10)
     Machine Arch: x86_64
 Operating System: GNU/Linux
         Hostname: desktop1


$ bat --version
bat 0.19.0 (59a8f58)

$ wget -c cheat.sh/ls

$ bat ls --color=never --wrap=never --pager=none
```

![bat-0 19-ansi-example](https://user-images.githubusercontent.com/7200584/150904058-6852cba7-6628-40a6-be7c-db02d587de0e.png)

**Comment by elsaco** [comment]
@neoh4x0r the issue is with the `cheat.sh/ls` script. Here's sample run with first few lines only:

![bat_ansi_ls_v019](https://user-images.githubusercontent.com/3933920/150912493-6a9089bc-2a07-4f32-81f9-a6d6142a5fa7.PNG)

**Comment by Enselic** [comment]
The "problem" is that bat 0.19.0 supports LiveScript (bat 0.18.3 does not) that has the file extension `ls`. So when you do `bat ls` then `bat` tries to highlight the file as a LiveScript file. Syntax definition regexes are not written with ANSI escape characters in mind so things gets messed up.

If you rename the file to something else it will work:
```
mv ls not-livescript
bat not-livescript
```
it will also work if you manually ask bat to use Plain Text syntax:
```
bat -l txt ls
```

**Comment by elsaco** [comment]
The only issue I've notices with the `cheat.sh/ls` script is with the ANSI sequence on line 18 column 118:

`[38;5;252m*/`

If a space or any other character is inserted between `m` and `*` then the whole `ls` works with bat-0.19. I might be wrong but the asterisk becomes part of the sequence.

**Comment by neoh4x0r** [comment]
@elsaco Editng the contents of things downloaded from cheat.sh is not practical.
Also as @Enselic said renaming the file is enough to have it rendered properly.

@Enselic If bat is looking strictly at the file extension to determine (in the case of ls there is not actual extension) there probably needs to be (or is) a more robust way to do this.

Is there a way to disable LiveScript from the commandline ?

**Comment by Enselic** [comment]
There are many examples where a syntax needs to be selected even though no dot is present. E.g. `Dockerfile`, `hosts` and `Makefile`. So falling back to `Plain Text` unless a dot is present is not really an option. At least not a straightforward option.

If you want to configure your copy of bat to always treat `ls` files as plain text you can set up a syntax mapping:
```bash
bat --generate-config-file
echo "--map-syntax 'ls:Plain Text'" >> ~/.config/bat/config
bat ls
```

**Comment by neoh4x0r** [comment]
> There are many examples where a syntax needs to be selected even though no dot is present. E.g. `Dockerfile`, `hosts` and `Makefile`. So falling back to `Plain Text` unless a dot is present is not really an option. At least not a straightforward option.
> 
> If you want to configure your copy of bat to always treat `ls` files as plain text you can set up a syntax mapping:
> 
> ```shell
> bat --generate-config-file
> echo '--map-syntax "ls:Plain Text"' >> ~/.config/bat/config
> bat ls
> ```
Well...that's good to know, I could definitely use that.

I see that the README has more about the syntax:
```
-map-syntax="pattern:syntax"
--map-syntax='*.conf:INI'
--map-syntax='.ignore:Git Ignore'
--map-syntax='/etc/apache2/**/*.conf:Apache Conf'
```

As far as cheat.sh goes....
If I were to create a local copy of the cheat.sh files (for offline use)

I could use the syntax format:
--map-syntax='/path/to/cheat.sh/files/**/*:Plain Text'

And that would render all files in that path as plain text.

**Comment by elsaco** [comment]
Changing the file name from `ls` to `ll` renders like this now:

![bat_ll](https://user-images.githubusercontent.com/3933920/151059453-c014df4b-8408-4e7d-af75-a98269d9dd0b.png)

**Comment by neoh4x0r** [comment]
> Changing the file name from `ls` to `ll` renders like this now:
> 
> ![bat_ll](https://user-images.githubusercontent.com/3933920/151059453-c014df4b-8408-4e7d-af75-a98269d9dd0b.png)

Well I think is now treating like a Lex source file (assuming .ll is Lex) -- basically the same problem.

Rename ls to ls2 -- no problem.

**Comment by neoh4x0r** [comment]
I'm thinking I should close this....

**The solution is one (or more) of the following:**
1. Rename the file so that it is not auto-detected
1. use --map-syntax to map one or more files to use Plain Text, etc
1. specify the language type on the command-line (-l LANG)
