### ISSUE TITLE
Integration test file_with_invalid_utf8_filename is broken on UTF-8 only file systems

### ISSUE THREAD

**Issue by DarkKirb** [sharkdp/bat#2045]
**Describe the bug you encountered:**

Integration test `file_with_invalid_utf8_filename` fails with “Invalid or incomplete or wide character” [on this code line](https://github.com/sharkdp/bat/blob/a3ea7982466941d746a09bafc8bf386711c48686/tests/integration_tests.rs#L1069) on UTF-8 only file systems, such as ZFS with the utf8only property set.

**What did you expect to happen instead?**

The test being skipped (likely difficult), or the test should succeed anyways

**bat version and environment**

bat 0.19.0 on nixos with a UTF-8 only ZFS dataset

You can create a zfs-only dataset by running:

```
zfs create -o utf8only=on pool/dataset/name
```
TMPDIR must be on that dataset

**Comment by Enselic** [comment]
Interesting find, but I really don't think it is worth maintaining code in bat to solve this. Closing for now. Feel free to re-open if you strongly disagree.
