### ISSUE TITLE
Upgrade to clap 3

### ISSUE THREAD

**Issue by Enselic** [sharkdp/bat#2056]
I think everyone agrees we need/should upgrade to clap 3 at some point. This ticket tracks that work.

I mostly create this ticket as a reminder for us to turn Dependabot updates back on for clap 3.x when we have done that work. I will turn off Dependabot updates for clap 3.x versions now.

**Comment by sharkdp** [comment]
This might also allow us to automatically generate shell completion files again. Assuming they are as good as the hand-written ones.

See also: https://github.com/sharkdp/bat/blob/312c8ef01f1a80f4a806629a7dacd32508b267a5/build.rs#L1-L2

**Comment by sharkdp** [comment]
I have now migrated three other projects to clap 3. I would suggest that we first do a "normal" migration by still using the `App`/`Arg` structs. We can later think about using the new (`structopt`) `derive` functionality, which might simplify our code quite a bit. See also: #998

**Comment by Enselic** [comment]
Sounds good. Also related: https://github.com/sharkdp/bat/pull/1281 that initially depended on clap 3 mechanisms that was later removed from the API, but
* there might we a new way to achieve the same thing
* we might be successful in requesting clap to add the API again
