### ISSUE TITLE
Introduce new `--style` called `default` that is not necessarily same as `full`

### ISSUE THREAD

**Issue by Enselic** [sharkdp/bat#2061]
There is a discussion in #1988 whether or not to include `header-filesize` in the default `--style`. The safest way forward is to be conservative and not include `header-filesize` by default. At least not yet. We can maybe make it default later.

To achieve that, we need a new style. I propose we simply call it `default`.

So we would have:
```
                     * default: enables recommended components (can change across versions) (default).\n  \
                     * full: enables all available components.\n  \
                     * auto: same as 'default', unless the output is piped.\n  \
                     * [... same as before ...]
```

Having `(can change across versions)` in the description is not very elegant. For now I just put it there for clarity. I think the implementation will be quite easy if we can agree on e.g. a name for the new style. We don't necessarily need to call it `default`.

It would be good to also take the opportunity to get rid of `auto` while we are at it. See #1743.

**Comment by sharkdp** [comment]
Sounds good to me. I am in favor of introducing `default`.
