### ISSUE TITLE
Cannot scroll using the touchpad, and PageUp/PageDown does not work.

### ISSUE THREAD

**Issue by carbongreat13** [sharkdp/bat#2062]
**Describe the bug you encountered:**
Cannot scroll with touchpad.
In less, you can use the touchpad to scroll.

If you use the PageUp/PageDown keys, bat does not work, but if you use less, it does.

**What did you expect to happen instead?**
Will be scrolled

**How did you install `bat`?**
MacPorts

---

**bat version and environment**
#### Software version
bat 0.19.0

#### Operating system
Mac OS X 10.15.7 (Darwin 19.6.0)

#### Command-line
```bash
bat --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=<not set>
LESS=<not set>
LANG=ja_JP.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/Users/USERNAME/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version 
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
I can not reproduce this on Linux. Both scrolling via touchpad as well as page up / page down work just fine.

**Comment by carbongreat13** [comment]
> I can not reproduce this on Linux. Both scrolling via touchpad as well as page up / page down work just fine.

I also have a Linux device and cannot reproduce the same.

**Comment by defaulterrr** [comment]
@carbongreat13 hey there

I was able to reproduce this behaviour on both x86 and arm64 macs with `less` version 490. Scroll was not working using touchpad, although listing with option+up/down worked fine. 

I solved this by installing latest `less` (version 590 at the moment) with `brew install less`. (I had to manually link new binary installed by brew).

Both `bat` and `less` were installed by `brew` 
______

Default less:
```
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman
```

Latest less:
```
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman
```
______

#### Software version

bat 0.20.0

#### Operating system

macOS 11.6.4 (Darwin 20.6.0)

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS=-R
LANG=<not set>
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/Users/defaulterrr/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by msr8** [comment]
I had the same problem in macOS 10.15.2 and fixed it by running `brew install less`

**Comment by sharkdp** [comment]
Thank you. Looks like this can be closed then.
