### ISSUE TITLE
Feature request: Download files from the internet

### ISSUE THREAD

**Issue by laurinneff** [sharkdp/bat#2070]
I often use bat to syntax highlight files from the internet, for example:

```sh
curl https://example.com | bat --language html
```

It would be nice if I could just do this instead:

```sh
bat https://example.com
```

and it detected the language from the `Content-Type` header. This might cause issues with filenames that look like URLs, but that could be solved by also adding support for the file scheme: `file:///path/to/file` and maybe adding a warning if there's a file with the same name

**Comment by keith-hall** [comment]
Thanks for the feedback/suggestion. As `bat` is primarily a `cat` replacement, I personally don't feel this feature would be in scope. Sounds perfect for a wrapper script though! Maybe suggest it on https://github.com/eth-p/bat-extras? :)
