### ISSUE TITLE
Can `bat` as library be used to detect a file extension/language?

### ISSUE THREAD

**Issue by demfabris** [sharkdp/bat#2071]
Given a file name, e.g. `file.rs` or contents of a file, can I detect the language/format?

**Comment by keith-hall** [comment]
I believe the answer is yes, if looking up a syntax definition is your goal. From there you can get the name of the syntax etc. https://docs.rs/bat/0.19.0/bat/assets/struct.HighlightingAssets.html#method.get_syntax_for_path
