### ISSUE TITLE
feature request: add BAT_STYLE in the same vein as BAT_THEME

### ISSUE THREAD

**Issue by sanga** [sharkdp/bat#208]
I suppose you may already have this in mind but I didn't see a tracking issue for it so I'm adding one just in case.

This would be to avoid silly mistakes such as the one in https://github.com/sharkdp/bat/issues/173

**Comment by sharkdp** [comment]
Yes, thanks for adding this request!

**Comment by sharkdp** [comment]
Closed by @ms2300 via #298

**Comment by sharkdp** [comment]
Released in [v0.7.0](https://github.com/sharkdp/bat/releases/tag/v0.7.0).
