### ISSUE TITLE
Be able to truncate long lines

### ISSUE THREAD

**Issue by igoracmelo** [sharkdp/bat#2081]
Sometimes the code have very large lines and warping it can make things harder to read.
An option like `--truncate <max_width>` would be very useful.

![image](https://user-images.githubusercontent.com/85039990/154703326-b7c71ea4-28d1-4d6a-9af6-8aa765465746.png)

**Comment by Enselic** [comment]
Did you try `--wrap=never`?

**Comment by igoracmelo** [comment]
@Enselic sorry for the delay.
Tried it right now, but it says:
```
http: error: unrecognized arguments: --wrap=never
```

I am using version 1.0.3, which is the latest according to pip3.

**Comment by Enselic** [comment]
I'll assume "No, but that solved my problem".
