### ISSUE TITLE
Command to jump between files

### ISSUE THREAD

**Issue by lespea** [sharkdp/bat#2087]
If you use bat to parse multiple files, there doesn't seem to be a way to jump between files.  In less, you can use `:n` for example, but that doesn't work here since (presumable) bat is piping the output of each file to less as one long stream.

Sorry if this was already requested, I searched but couldn't find anything.

**Comment by sharkdp** [comment]
I mentioned this as an idea in [#1053](https://github.com/sharkdp/bat/issues/1053#issue-631960732)

> Special handling for multiple files? (press 'n' to go to the next file)



> (presumable) bat is piping the output of each file to less as one long stream

exactly.

**Comment by lespea** [comment]
Ah okay, I just skimmed the issue titles.  Thanks for pointing this out!
