### ISSUE TITLE
Bash completion still doesn't work as expected on Ubuntu (installed using Homebrew)

### ISSUE THREAD

**Issue by Jarmos-san** [sharkdp/bat#2094]
**Describe the bug you encountered:**

I believe #2074 already had a fix for Bash Completion which was introduced recently in `v0.20` but it doesn't seem to work flawlessly yet. Upon pressing `Tab` it throws this error message instead:

```
$ bat pack<pressing tab here>_get_comp_words_by_ref: command not found
```

**What did you expect to happen instead?**

Pressing `Tab` should trigger Bash auto-completion without any errors. So, the following would work as expected;

```
$ bat pack<pressing tab here>age.json
```

**How did you install `bat`?**

Homebrew for Linux

---

**bat version and environment**

#### Software version

bat 0.20.0

#### Operating system

Linux 5.13.0-28-generic

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
LANG=en_IN.UTF-8
LC_ALL=en_IN.UTF-8
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=less
```

#### Config file

```
# Specify desired highlighting theme (e.g. "TwoDark"). Run `bat --list-themes`
# for a list of all available themes
--theme="gruvbox-dark"

# Uncomment the following line if you are using less version >= 551 and want to
# enable mouse scrolling support in `bat` when running inside tmux. This might
# disable text selection, unless you press shift.
--pager="less -R"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

**Comment by Enselic** [comment]
@joshpencheon @scop Any chance that any of you have the possibility to take a look at this?

**Comment by Jarmos-san** [comment]
@joshpencheon thanks for the heads up! I'll look into the issue further & revert back if the issue persists.
