### ISSUE TITLE
Automatic cleaning up the output

### ISSUE THREAD

**Issue by noraworld** [sharkdp/bat#2118]
How can I clean up the `bat` output automatically after exiting?

I usually use the option `--paging=always` to always show with `less` style. `less` cleans up the output automatically after exiting, but `bat` doesn't.

Is there any available options to do this?

**Comment by sharkdp** [comment]
> Is there any available options to do this?

No. You could add `--paging=always` to `bat`s config file, and that should probably do what you want. But `bat` itself can not do this, as it simply prints do the terminal. It doesn't open an 'alternate screen' like a pager usually does.

Potentially related: #1053

**Comment by noraworld** [comment]
Thank you for your reply.

I see `bat` can't do this right now. Is `bat` planned to have an ability to clean up the terminal after exiting in the future as well as `less` does?

**Comment by sharkdp** [comment]
> Is `bat` planned to have an ability to clean up the terminal after exiting in the future as well as `less` does?

no, but as mentioned above, you can follow #1053 if you are interested in updates on this.
