### ISSUE TITLE
Add '-p' as a shortcut for '--style=plain'

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#212]
The "plain" style is sometimes desirable to copy&paste from the terminal without the line numbers or Git modifications. There should be a short option (`-p`) that can be used to set `--style=plain`.

**Comment by ms2300** [comment]
Can I help out and add this feature in?

**Comment by sharkdp** [comment]
Yes, absolutely! Any help would be greatly appreciated.

**Comment by sharkdp** [comment]
Closed via #222
