### ISSUE TITLE
How to use bat --diff as git difftool ?

### ISSUE THREAD

**Issue by kuvaldini** [sharkdp/bat#2120]

**Comment by SuperSandro2000** [comment]
https://github.com/sharkdp/bat#git-diff

> If you are looking for more support for git and diff operations, check out [delta](https://github.com/dandavison/delta)[](https://github.com/sharkdp/bat#xclip).

**Comment by kuvaldini** [comment]
Thankyou.

**Comment by coolaj86** [comment]
For posterity:

Here's how you set it to work with `git diff` and replace the general pager.

```sh
git config --global core.pager "bat --paging never --pager none --theme Dracula --style=plain"
git config --global pager.diff "bat --paging never --pager none --theme Dracula --style=plain --language diff"
```

Season to taste, of course.

**Comment by aynugek** [comment]
You can always pipe git diff's output to bat
`git diff | bat`
