### ISSUE TITLE
Using `bat` as a library and printing binary content displays `bat`-specific error message

### ISSUE THREAD

**Issue by acheronfail** [sharkdp/bat#2146]
## Problem

When using bat as a library, if binary content is detected then the `PrettyPrinter` will print:

```
[bat warning]: Binary content from READER will not be printed to the terminal (but will be present if the output of 'bat' is piped). You can use 'bat -A' to show the binary file contents.
```

I imagine this behaviour could cause some surprise for crates which depend on bat since the `-A` flag obviously isn't available. Also the `content from READER` could also be confusing.

## Suggested solutions

1. Extend the `PrettyPrinter::print` function (or `PrettyPrinter` itself) so a library user can pass an error string rather than this default
2. ??? Please share your thoughts here about how this could be best solved

**Comment by Enselic** [comment]
Closed by #2142
