### ISSUE TITLE
tab-completion broken in v0.20

### ISSUE THREAD

**Issue by polarweasel** [sharkdp/bat#2147]
**Describe the bug you encountered:**

It appears #2074 introduced a bug. Starting with version 0.20, when I type `bat <start of filename><TAB>` I get the following error, and `bat` doesn't exit until I send it an interrupt.

```sh
$ bat .bash-bash: _split_longopt: command not found
-bash: _filedir: command not found
^C
```

Typing `bat <TAB>` (no filename) results in the following:

```sh
$ bat -bash: _split_longopt: command not found
-bash: _filedir: command not found
cache ^C
```

And autocompleting bat's own options is hitting the same issue (though then it does add the completion!):

```sh
$ bat --diag-bash: _split_longopt: command not found
nostic ^C
```

**What did you expect to happen instead?**

Hitting TAB should complete the filename, or present a list of options, as usual.

**How did you install `bat`?**

Homebrew.

---

**bat version and environment**

$ bat --diagnostic

#### Software version

bat 0.20.0

#### Operating system

macOS 12.3 (Darwin 21.4.0)

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/opt/homebrew/bin/bash
PAGER=<not set>
LESS=<not set>
LANG=en_CA.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/Users/awball/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: unknown
- Host: aarch64-apple-darwin

#### Less version

```
> less --version 
less 581.2 (POSIX regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by polarweasel** [comment]
As soon as I filed this, I tried reinstalling bash-completion@2 again, and discovered I had a leftover from version 1 in my .bash_profile. Cleaning that up seems to have solved the problem. Will reopen if it crops up again.

**Comment by zw963** [comment]
This same issue happen on my Arch linux, i don't know when this happen, because i am not use bat frequently recent days.

When input bat + `TAB`, i get following error (please check screenshot.)

![image](https://github.com/sharkdp/bat/assets/549126/2be2e5e9-b750-4ecd-b17a-7c3cf02a524d)

**Comment by zw963** [comment]
And i try search `_split_longopt` on all my completions, only two of them use it.

```
bash_completions/the_silver_searcher.sh:103:  _split_longopt && split=true
bash_completions/bat.bash:40:            _split_longopt && split=true
```

the silver searcher never update since 2018, so, `bat.bash` is need update to fix this issue, right?

**Comment by keith-hall** [comment]
> And i try search `_split_longopt` on all my completions, only two of them use it.
> 
> ```
> bash_completions/the_silver_searcher.sh:103:  _split_longopt && split=true
> bash_completions/bat.bash:40:            _split_longopt && split=true
> ```
> 
> the silver searcher never update since 2018, so, `bat.bash` is need update to fix this issue, right?

no, [`bat.bash`  clearly states that it requires `bash-completion` to be installed](https://github.com/sharkdp/bat/blob/master/assets/completions/bat.bash.in#L3)

indeed, when checking where that function is defined on my machine:
```bash
bash --debugger
declare -F _split_longopt
```
> `_split_longopt 635 /usr/share/bash-completion/bash_completion`

do you have bash-completion installed?
