### ISSUE TITLE
Clickable URLs

### ISSUE THREAD

**Issue by kevindirect** [sharkdp/bat#2149]
I often use markdown to store and organize urls. It would be nice to be able to click urls and have it open them with xdg-open.

I don't know if this already a feature, but I couldn't find how to enable it if it is.

**Comment by keith-hall** [comment]
I believe this is generally up to your terminal emulator, no? If I use `bat` on a Markdown file (or any file, with any language highlighting) or even just `echo` a url directly in the terminal, `xfce4-terminal` makes them clickable, even with piping into a pager like `less`.
![image](https://user-images.githubusercontent.com/11882719/162115208-b54d7fa7-5ee1-4bea-8f92-d7bb84ddb72a.png)

**Comment by Enselic** [comment]
I agree this should be handled by the terminal, and not bat. Closing.

**Comment by kevindirect** [comment]
Not everyone's terminal does this, mine does not.
I think my best bet is finding a pager that can recognize the click to the URL and opens the browser to it.
