### ISSUE TITLE
Add Kotlin support

### ISSUE THREAD

**Issue by nkiesel** [sharkdp/bat#215]
Could you please add support for highlighting Kotlin?

**Comment by sharkdp** [comment]
Thank you for the feedback!

We can do this, yes. We will need a Sublime Text `.sublime-syntax` file for Kotlin.

**Comment by nkiesel** [comment]
Would  Kotlin.tmLanguage from https://github.com/vkostyukov/kotlin-sublime-package do the trick? Not a Sublime user myself (yet), so hard for me to tell.

**Comment by nkiesel** [comment]
Just a question, not a suggestion: why are you not using https://github.com/alecthomas/chroma ?  That seems to support many more languages (incl. Kotlin) out of the box.

**Comment by sharkdp** [comment]
> Would Kotlin.tmLanguage from vkostyukov/kotlin-sublime-package do the trick? Not a Sublime user myself (yet), so hard for me to tell.

That should work, yes. It seems to be the only Kotline Sublime package out there.

We would have to convert to `.sublime-syntax` as described in the `assets/README.md´.

> Just a question, not a suggestion: why are you not using alecthomas/chroma ? That seems to support many more languages (incl. Kotlin) out of the box.

`bat` is written in Rust, not Go.

**Comment by nkiesel** [comment]
Here is what I got after conversion.  I asked a colleague for help and have no way to validate this.

[Kotlin.zip](https://github.com/sharkdp/bat/files/2315958/Kotlin.zip)
