### ISSUE TITLE
Fix description

### ISSUE THREAD

**Issue by tiagofrancafernandes** [sharkdp/bat#2163]
Showing the description of bat Debian Package I got:

```
...
 ‘batbat’ because of a file name clash with another Debian paclage.
...
```

See description has 'paclage' but they probably meant 'package'.
Perhaps a typo.

**Comment by Enselic** [comment]
`git grep -i paclage` in our repo gives no hits, so we can't do anything about this. Maybe try to file an issue against the Debian package.
