### ISSUE TITLE
bat doesn't adapt to white console background

### ISSUE THREAD

**Issue by Lapsusone** [sharkdp/bat#2167]
**What steps will reproduce the bug?**

1. Install bat on a system with white console background (macOS for example)
2. Use the command on a file
 
**What happens?**

Content of the file doesn't show as the font color is white on a white background

**What did you expect to happen instead?**

Text prints in black.

**How did you install `bat`?**

brew install bat --cask

---

**bat version and environment**

bat 0.20.0 on macOS 12.3.1

**Comment by Enselic** [comment]
Duplicate of #1746
