### ISSUE TITLE
No such file or directory: /dev/null

### ISSUE THREAD

**Issue by sascha-andres** [sharkdp/bat#2180]
**What steps will reproduce the bug?**

1. step 1

    scp_&lt;tab&gt;

**What happens?**

![image](https://user-images.githubusercontent.com/3052075/166443827-a692f642-a611-4b47-8629-cafc780bdc96.png)

After the empty line the potential snippets are shown

**What did you expect to happen instead?**

No error to occur

**How did you install `bat`?**

https://github.com/marcosnils/bin

---

**bat version and environment**

    bat 0.20.0 (0655ecf)

Environment:

 WSL 2 - Ubuntu 20.04

**Comment by Enselic** [comment]
Looks like your tab-completion setup makes bat try to open a file called `^/dev/null`, which naturally does not exist (it's real name is `/dev/null`).

This currently does not look like a bug in bat, so I will close this issue.
