### ISSUE TITLE
Move to makedeb for Debian packaging

### ISSUE THREAD

**Issue by hwittenborn** [sharkdp/bat#2195]
Hi! I was just looking around and saw [how the Debian package was being created](https://github.com/sharkdp/bat/blob/master/.github/workflows/CICD.yml#L345-L452), and I was curious if [makedeb](https://makedeb.org) would possibly be of any interest.

makedeb uses PKGBUILDs, the file format for makepkg on Arch Linux/the AUR. The file format could greatly reduce the amount of code you need to maintain the Debian package, and would be a fair amount cleaner than having a big script embedded into a CI pipeline.

I've actually already packaged up bat on the [MPR](https://mpr.makedeb.org/packages/bat) (a user repository for makedeb) as well if you want an example of what the packaging file would look like. You can find the PKGBUILD file itself [here](
https://mpr.makedeb.org/pkgbase/bat/git/tree/PKGBUILD).

P.s., makedeb is a personal project of mine.

**Comment by sharkdp** [comment]
Thanks. Your project looks nice, but we're trying to keep out of maintenance of packages ourselves. Up-to-date Debian packages are provided on a "best effort" basis, but I'm not really willing to invest time to understand a new tool. The current way of automatically creating packages works quite well with very low maintenance effort, so I think I'm voting for a "never change a running system" approach here.
