### ISSUE TITLE
Configuration File: Environment Variable Interpolation

### ISSUE THREAD

**Issue by tylerbrostrom** [sharkdp/bat#2223]
AFAIK environment variables aren’t interpolated in `bat`’s configuration file.

This could be useful, especially for `--map-syntax`

Example:

```sh
# ~/.config/bat/config

# highlight extensionless `zsh` scripts
--map-syntax "$ZDOTDIR/conf.d/*:Bourne Again Shell (bash)"
```

**Comment by sharkdp** [comment]
Thank you for your request. I see how that would be useful in this example, but for now, I'd like the config format to be as simple as possible. Adding this feature would not just be potentially breaking, it would also require us to think about escaping etc.
