### ISSUE TITLE
`bat --diff` does all git tracked files changes

### ISSUE THREAD

**Issue by rohitmusti** [sharkdp/bat#2224]
It would be cool if when I ran `bat --diff` it worked without specifying the file(s). Maybe each file is shown separately?

i.e.

`bat --diff src/main.rs` -> `bat --diff`

**Comment by milespossing** [comment]
You could just use a bash command for this:

```bash
git status -s | grep -e "^ M" | sed "s/^ M //" | xargs bat -d
git status -s | grep -e "^ M" | sd "^ M " "" | xargs bat -d # uses sd
```

There's probably an easier way to do it, but that's how I would write an alias for something like `batdiff` or similar:

```bash
alias batdiff="git status -s | grep -e "^ M" | sd "^ M " "" | xargs bat -d"
```

**Comment by sharkdp** [comment]
See also https://github.com/sharkdp/bat#git-diff

**Comment by rohitmusti** [comment]
woah these are cool ideas! I've been using that `batdiff` alias technique for a few days and it's been nice, it would be cool if we could bake this into the core. That was also great to add the reference to the existing documentation!

I might play around with trying to bake this into the core functionality. It would be quite convenient if I didn't need to run an alias locally (also probably some room for more sophisticated things without aliasing locally!

**Comment by sharkdp** [comment]
I suggest that you also take a look at https://github.com/dandavison/delta.

Closing this for now.
