### ISSUE TITLE
Input and output can point to the same file

### ISSUE THREAD

**Issue by FaresAhmedb** [sharkdp/bat#2226]
**What steps will reproduce the bug?**

1. `printf "a" > myfile`
2. `bat myfile >> myfile`

**What happens?**

bat keeps appending to the file until the disk is full and system is probably unusable.

**What did you expect to happen instead?**

An error message indicating that the input and output files are the same.

---

While this is not part of the [POSIX](https://pubs.opengroup.org/onlinepubs/009696899/utilities/cat.html) standard, multiple implementations of cat already does that including the ones made by GNU and BSD, They both compare the input file's and stdout's `st_dev` (device id) and `st_ino` (inode number) and if they match then its the same file (Can be obtained using `std::os::unix::fs::MetadataExt`). I don't know how that could be implemented in Windows but after a quick search on [crates.io](https://crates.io/) I found a cross-platform library that does exactly that called [same-file](https://github.com/BurntSushi/same-file).

**Comment by sharkdp** [comment]
Thank you for reporting this. I agree that we should try to fix this.

**Comment by keith-hall** [comment]
related, previously solved issue: https://github.com/sharkdp/bat/issues/1193

**Comment by FaresAhmedb** [comment]
It appears that I'm using an old version of bat, this doesn't happen in newer versions :sweat_smile:
