### ISSUE TITLE
Add single character argument for --wrap never

### ISSUE THREAD

**Issue by jguhlin** [sharkdp/bat#2239]
I primarily use less -S to view everything due to long lines (bioinformatics, mostly). Bat is incredibly fast, but I'd appreciate a single character argument to substitute for --wrap never (such as -S to match less functionality, or something else).

Cheers

**Comment by sharkdp** [comment]
I'm usually careful when providing new short flags, but this seems reasonable, given that it would be in line with `less`s `-S` option. Maybe should also support `--chop-long-lines`, which is the long-form of `-S`.

**Comment by johnmatthiggins** [comment]
I would like to work on this one. What should the single letter abbreviation be for setting wrapping to off. Should it be implemented with -S or would a different letter work better?

**Comment by sharkdp** [comment]
`-S` seems good.

**Comment by johnmatthiggins** [comment]
Sounds good. I made a pull request (#2309) for adding `-S` and the `--chop-long-lines` option.
