### ISSUE TITLE
`PAGER` unnecessarily executed & syntax/coloring goes into the pager

### ISSUE THREAD

**Issue by wael444** [sharkdp/bat#2241]
**What steps will reproduce the bug?**

1. `PAGER=nvim`
2. `bat <any file>`

**What happens?**

`$ bat file`
On default `bat` configuration:
![image](https://user-images.githubusercontent.com/47404953/178154546-ea4b232c-ada7-40f0-ab65-4f0743a8ec81.png)

**What did you expect to happen instead?**

```
$ bat file                                                                                                
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: file
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ hello i am a file
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────
$ 
```

**How did you install `bat`?**
xbps `bat-0.21.0_1`

---

**bat version and environment**

#### Software version

bat 0.21.0

#### Operating system

Linux 5.18.9_1

#### Command-line

```bash
bat --style numbers --theme ansi --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/mksh
PAGER=''
LESS=<not set>
LANG=en_US.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=/home/wael/.config
XDG_CACHE_HOME=/home/wael/.cache
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER='nvim +Man'\!''
```

#### Config file

Could not read contents of '/home/wael/.config/bat/config': No such file or directory (os error 2).

#### Custom assets metadata

Could not read contents of '/home/wael/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/home/wael/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by Enselic** [comment]
This is by design. Please see https://github.com/sharkdp/bat#using-a-different-pager for more info.

**Comment by wael444** [comment]
so i am unable to use `nvim` as my `PAGER`? only `less -R`?

**Comment by Enselic** [comment]
What pager do you want to use with bat? Set `BAT_PAGER` to that pager. Then `PAGER` will be ignored.

**Comment by wael444** [comment]
in the original description `PAGER` is set to my editor `nvim`.
but setting that variable doesnt help the fact that ANSI is still seen by the editor:
![image](https://user-images.githubusercontent.com/47404953/178160471-9697546d-46c0-4854-9372-21c22018c737.png)
`$ BAT_PAGER=nvim /bin/bat file`

**Comment by Enselic** [comment]
Sounds like you want bat to never output ANSI escape characters for syntax highlighting? Then you should put `--color=never` in your bat config.

**Comment by wael444** [comment]
> Sounds like you want bat to never output ANSI escape characters for syntax highlighting?

The primary problem is the pager getting executed. the file isn't small, i expect the pager to only run when the terminal window is too small for the file contents.

but as you said this is intentional by design, i guess i will continue using `less`.
