### ISSUE TITLE
Carbon Lang

### ISSUE THREAD

**Issue by Horki** [sharkdp/bat#2248]
**Syntax:**
[Carbon](https://github.com/carbon-language/carbon-lang)

**Guideline Criteria:**

**Comment by keith-hall** [comment]
As far as I know, Carbon is so new that nobody has written a syntax definition for it yet. But I've heard comments that it has similar syntax to Rust, so you could try mapping carbon files to that for now to at least get some highlighting.

**Comment by Horki** [comment]
@keith-hall will do

**Comment by sharkdp** [comment]
There is a syntax now: https://packagecontrol.io/packages/Carbon

but it does not yet fulfill our criteria for inclusion. Closing this for now.
