### ISSUE TITLE
be able to "tail" last N lines of a file

### ISSUE THREAD

**Issue by danielb2** [sharkdp/bat#2251]
Ref: https://github.com/sharkdp/bat/discussions/2243

> it would be cool if we could do Python-style negative-number ranges like this:

`bat file.txt -r -10:`

> which would mean: "10 lines from the end until the end"

**Comment by Z4K4RI4** [comment]
You can do it just with something like : 
`tail -n 10 foo.txt | bat `

**Comment by danielb2** [comment]
> You can do it just with something like : `tail -n 10 foo.txt | bat `

No you can't. Color syntax is lost

**Comment by sharkdp** [comment]
Thanks. As I wrote in the discussion, I think that would be a useful addon.

**Comment by sharkdp** [comment]
Please see #791. I didn't remember that when I replied previously.
