### ISSUE TITLE
Default themes are gone after adding a custom theme

### ISSUE THREAD

**Issue by dmarcoux** [sharkdp/bat#226]
Hey,

I added a new theme by following the instructions in the README. It worked, but now the default themes are gone (`bat --list-themes` lists only the theme I added). I assume this isn't the expected behavior. I don't know if this could somehow help, but the theme I installed is [this one](https://github.com/deplorableword/textmate-solarized/blob/master/Solarized%20(light).tmTheme).

Thank you for making `bat`.
Cheers

**Comment by sharkdp** [comment]
I have recently fixed this (052425b12f79aa42b1ca6453725b501be87dcc8d), but didn't get around to releasing a new version yet.

**Comment by dmarcoux** [comment]
Oh, good to know! I'll close this issue then.
