### ISSUE TITLE
Add +cmd arguments to pass when pager is less

### ISSUE THREAD

**Issue by eggbean** [sharkdp/bat#2261]
It would be great if +cmd arguments were added which are passed to less if it is the pager. So..

`$ bat +G file` would go to the end of the file

`$ bat +20 file` would go straight to line 20, etc

If the pager is not less it could be ignored.

**Comment by sharkdp** [comment]
Thank you for your request. I'd rather not add `+…` comments to `bat`. They are not common in modern CLI tools. But more importantly, I would like to refrain from adding `less`-specific features to `bat` (related discussion: #1053).
