### ISSUE TITLE
cache file created on TAB for completion...

### ISSUE THREAD

**Issue by ljramalho** [sharkdp/bat#2263]
I notice that when I type:
bat
and then, I press the TAB key for completion, and there are lots of files to choose, the shell provides me with all available files, invariable including a file called "cache".

I don't know if this "cache" file is something hidden in the file system or if it is something "bat" command temporarily create for... something... or if it is a product of the bash completion scripts for bat...

I only know that either, after execute the bat command or cancel it, I cannot find the "cache" file anywhere.

In no other circumstance where I press TAB for completion for other commands, the bash shell show me a file called "cache".

So...

A) If this "cache" file is a byproduct of "bat" command functionality or bash completion script for bat...  What happen if in that same folder I have a real and important file called "cache"?

B) So if indeed that file is created, don't you think it is a kind of overkill to create and delete dozens of "cache" files in a file system mounted over an SD card as it is the case of my raspberry Pi, where I'm using the "bat" command?

C) If cache is part of bat features, what is the solution to prevent the creation or, if that file is really necessary, to force the creation of that file in a temporary system folder? (I really don't want to mess with the scripts and neither I have the knowledge to follow developer's train of thought).

Thank you

**Comment by keith-hall** [comment]
I'm pretty sure that `cache` is a not file being temporarily created and instead is just a `bat` subcommand being offered as a completion/suggestion - see https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions :)

**Comment by keith-hall** [comment]
Note there is a potential idea to remove (the need for) the `cache` subcommand: https://github.com/sharkdp/bat/issues/2085
