### ISSUE TITLE
Implement 1:1 compatibility with command line options that cat supports

### ISSUE THREAD

**Issue by rahulsundaram** [sharkdp/bat#228]
http://man7.org/linux/man-pages/man1/cat.1.html

In particular, I frequently use -A often but if bat is supposed to be a clone, it really needs to be a drop-in replacement as well.

**Comment by sharkdp** [comment]
Thank you for your feedback.

> if bat is supposed to be a clone, it really needs to be a drop-in replacement as well

As stated in the [Project goals](https://github.com/sharkdp/bat#project-goals-and-alternatives), `bat` tries to be "a drop-in replacement for (POSIX) `cat`" and we are actually pretty close to fulfilling [the POSIX standard](https://github.com/sharkdp/bat/issues/134).

Note that [the POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/cat.html) does not require any command-line arguments except for `-u` (which `bat` supports in the same way as GNU `cat` - by simply ignoring it).

The other command-line options are additional features of GNU `cat` and I have personally never used any of these command-line flags, so I'm not too eager to implement any of them for `bat`. That being said, if there are valid use-cases and a large support for this, I might consider adding some of these (GNU `cat`) flags.

**Comment by rahulsundaram** [comment]
I saw the note on POSIX.  GNU tools have continued to evolve and gain additional features beyond that and -A happens to be one of them.   I will let others voice support for specific options as they see fit

**Comment by sharkdp** [comment]
So I'm curious: what do you do with `cat -A`?

**Comment by rahulsundaram** [comment]
I work on things like puppet templates, yaml files, encrypted hiera etc all of which are sensitive to tab vs space, line ending markers and so forth and can be painful to debug.  Cat -A on these files is a quick way to check if the output looks right especially on a remote system.

**Comment by sharkdp** [comment]
This is actually quite hard to implement correctly due to the interference of syntax highlighting and character replacement. If we switch off syntax highlighting for `-A`, people can also just use `cat`.

I'm closing this, as I don't see this happening in the near future.

**Comment by sharkdp** [comment]
@rahulsundaram I had a change of mind: You can take a look at #395 if you are interested.

**Comment by rahulsundaram** [comment]
Thank you!  Appreciate the heads up as well

**Comment by sharkdp** [comment]
This is now available in [bat 0.9](https://github.com/sharkdp/bat/releases/tag/v0.9.0).
