### ISSUE TITLE
Weird characters when used as MANPAGER, working normally when used as pipe output.

### ISSUE THREAD

**Issue by Kushagra-0801** [sharkdp/bat#2286]
**What steps will reproduce the bug?**

1. Run `man less | bat -l man`.
![Screenshot from 2022-08-29 08-46-18](https://user-images.githubusercontent.com/39802979/187116198-0f3c2eea-627d-4de8-ba24-cf9bf008c94e.png)

2. Run `MANPAGER=`bat -l man`.
![Screenshot from 2022-08-29 08-46-44](https://user-images.githubusercontent.com/39802979/187116232-6de65058-298c-44dc-b198-a0817f4173bf.png)

**What happens?**
The output from the first command is completely normal while the second has many `^H` characters.

**What did you expect to happen instead?**
The output should have been the same (specifically the normal output) in both cases.

**How did you install `bat`?**

`cargo install bat`

---

**bat version and environment**
#### Software version

bat 0.21.0

#### Operating system

Linux 5.14.0-1045-oem

#### Command-line

```bash
bat -l man --diagnostic 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS='-ix8RmPm Manual page xclip(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$PM Manual page xclip(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$'
LANG=en_IN
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='bat -l man --diagnostic'
```

#### Config file

Could not read contents of '/home/kushagragupta/.config/bat/config': No such file or directory (os error 2).

#### Custom assets metadata

Could not read contents of '/home/kushagragupta/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/home/kushagragupta/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 590 (GNU regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by keith-hall** [comment]
Did you try putting your `groff` into compatibility mode? https://github.com/sharkdp/bat/issues/652#issuecomment-968113494

**Comment by Kushagra-0801** [comment]
Thank you! The `groff` thing didn't help but the comments above that did help. I had only read the README once a long time ago and I have been using the help messages since then so I didn't know the `col -bx` trick. That fixed everything.
