### ISSUE TITLE
Link error on Fedora

### ISSUE THREAD

**Issue by kuviman** [sharkdp/bat#229]
```
   Compiling bat v0.6.0 (file:///home/kuviman/Temp/bat)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl ...
  = note: /usr/bin/ld: cannot find -lz
          collect2: error: ld returned 1 exit status
```

OS: Fedora 28 (Workstation Edition) x86_64

**Comment by sharkdp** [comment]
Hm, it looks like this is an open issue with `libz-sys`: https://github.com/alexcrichton/libz-sys/issues/20.

Can you try to install `zlib1g-dev` and try again?

**Comment by kuviman** [comment]
`zlib1g-dev` not found, but there is `zlib-devel` package.

Installed it, and build was successful.
