### ISSUE TITLE
Is it possible to get bat to output cached themes?

### ISSUE THREAD

**Issue by UtkarshVerma** [sharkdp/bat#2290]
I had an embarrassing accident where I ended up deleting a custom theme I wrote for `bat`. However, it is still in the cache. Could you please let me know if I can recover the theme config from the cached data?

I am fairly used to software development so, I could tinker with the source code as well.

**Comment by keith-hall** [comment]
Hi, the cache/"compiled assets" is like a compressed binary dump/representation, so there's no way to get the original `tmTheme` itself back, but theoretically it could be read by Rust, (deserialized by serde back into a struct form,) and then it should be possible to do a "debug print" on that to get the color rules.

I believe the relevant starting point would be
https://github.com/sharkdp/bat/blob/master/src/assets.rs#L126

**Comment by Enselic** [comment]
You can use this to dump compiled syntaxes in "clear text": https://github.com/Enselic/bat/pull/110. Maybe it will be useful.

**Comment by UtkarshVerma** [comment]
Thanks a lot! This will be really helpful

**Comment by UtkarshVerma** [comment]
Since the patch was small, I manually applied it on top of v0.21 release. I got the dump as well, but it didn't have any theme info.

**Comment by Enselic** [comment]
I pushed a quick and dirty update to that PR that dumps a hardcoded theme. Also, I think the SyntaxSet dump code needs to be updated to load all lazy-loaded themes too, cause the output looked incomplete. Good luck :)

**Comment by UtkarshVerma** [comment]
Thanks a lot @Enselic . I got my theme back!
