### ISSUE TITLE
Broken line breaks when using it with `delta` as git-diff pager

### ISSUE THREAD

**Issue by arctic-penguin** [sharkdp/bat#2307]
**What steps will reproduce the bug?**

1. `export PAGER=bat`
2. `git config pager.diff=delta`
3. Go to any git clone that contains a long line, remove it.

**What happens?**
Line breaks are broken.
![neu](https://user-images.githubusercontent.com/103587359/189113658-80452f4a-b274-440f-a34e-cb1dd1813b0c.png)

...

**What did you expect to happen instead?**
Line breaks are okay.
![alt](https://user-images.githubusercontent.com/103587359/189113671-8dbf81ae-913c-408c-ba5d-fbf5dc61ed3f.png)

...

**How did you install `bat`?**

`pacman -S bat`, can also reproduce it via `cargo install`, as well as `git clone` followed by `cargo install --path .`

---

* Good version: `bat 0.21.0 (405e5f74)`
* Bad version: `bat 0.22.0 (1f9519d8)` (release)
* Bad version: `bat 0.22.0 (6680f65)` (HEAD)
* `git bisect` points to 899fdbb347b6444eb06d8a26375ed10e35c612e2

The error is triggered when running `git-diff`, with `pager.diff` set to `delta`. My `$PAGER` is set to `bat`. Therefore I don't know how to apply the `--diagnostics` part.

P.S.: The `gdi` command is an alias to `git diff`.

**Comment by arctic-penguin** [comment]
I just found it affects more applications. This is happens when installing updates on Arch Linux with the AUR-helper `paru`.
![screen](https://user-images.githubusercontent.com/103587359/189139717-e537a013-d7ee-495b-ab91-8e443dd6bb82.png)

**Comment by arctic-penguin** [comment]
Yes, it does. What does that mean for me?

**Comment by Enselic** [comment]
@sharkdp I think we should revert https://github.com/sharkdp/bat/pull/2189 and do a 0.22.1 point release ASAP. Do you agree?

I didn't know about this use case, but it seems like a basic use case, so the short term solution should be to revert that PR, I think. That will make https://github.com/sharkdp/bat/issues/2185 occur again, but that seems like more of an edge case than the use case in this issue.

**Comment by Enselic** [comment]
PR that also prepare for a v0.22.1 release: https://github.com/sharkdp/bat/pull/2308

**Comment by sharkdp** [comment]
> @sharkdp I think we should revert #2189 and do a 0.22.1 point release ASAP. Do you agree?

Yes, thanks.

**Comment by Enselic** [comment]
Released as v0.22.1.

**Comment by arctic-penguin** [comment]
Thank you for the very quick fix!
