### ISSUE TITLE
Break in grid border decoration

### ISSUE THREAD

**Issue by a1346054** [sharkdp/bat#2314]
**What steps will reproduce the bug?**

Run this in bash or zsh:
```bash
for i in {1..10000}; do printf '%s\n' "$i"; done | bat
```

and scroll to the very bottom.

**What happens?**

![bat](https://user-images.githubusercontent.com/36859588/189698056-8e04d010-0b5b-4384-87b1-4baf00762db9.png)

**What did you expect to happen instead?**

![bat2](https://user-images.githubusercontent.com/36859588/189699923-6d91695b-3d79-4aee-8437-ff3abbd6e999.png)

Alternatively, even nicer:

![bat3](https://user-images.githubusercontent.com/36859588/189702868-c8740ad5-7ef0-4532-b2bb-218e04a48097.png)

**How did you install `bat`?**

GitHub release

**bat version and environment**

bat 0.22.1 (e5d9579)

**Comment by keith-hall** [comment]
https://github.com/sharkdp/bat/issues/715#issuecomment-549161801
