### ISSUE TITLE
Colors are muted

### ISSUE THREAD

**Issue by zachwhaley** [sharkdp/bat#2315]
**What steps will reproduce the bug?**

1. Run `bat`

**What happens?**

Colors are muted and hard to see.

![image](https://user-images.githubusercontent.com/2996465/190244667-45fd41ff-dc37-47c4-ab46-34323ef33e89.png)

**What did you expect to happen instead?**

Colors are bright and easy to see.

**How did you install `bat`?**

homebrew

---

**bat version and environment**

#### Software version

bat 0.22.1

#### Operating system

macOS 12.5.1 (Darwin 21.6.0)

#### Command-line

```bash
bat go.mod --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS='-F -g -i -M -R -w -X -z-4'
LANG=en_US.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

Could not read contents of '/Users/zacharyw/.config/bat/config': No such file or directory (os error 2).

#### Custom assets metadata

Could not read contents of '/Users/zacharyw/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/Users/zacharyw/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh
- Host: aarch64-apple-darwin

#### Less version

```
> less --version
less 581.2 (POSIX regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by bjschafer** [comment]
This looks to be macOs specific, I think. I can reproduce on macOS, iTerm, and same version of `bat`. Works fine on Alacritty & Arch Linux:


bat 0.22.1 (e5d95796)

#### Operating system

Linux 5.19.6-1-MANJARO

#### Command-line

```bash
bat --diagnostics main.cpp
```

#### Environment variables

```bash
SHELL=/usr/bin/zsh
PAGER=less
LESS='--tabs=4 --no-init --LONG-PROMPT --ignore-case --quit-if-one-screen --RAW-CONTROL-CHARS'
LANG=en_US.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=1
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

Could not read contents of '/home/bschafer/.config/bat/config': No such file or directory (os error 2).

#### Custom assets metadata

Could not read contents of '/home/bschafer/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/home/bschafer/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 608 (PCRE2 regular expressions)
Copyright (C) 1984-2022  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by bjschafer** [comment]
I think this is an artifact of #2197. `bat` on macOS now reads & respects your system's Light/Dark mode (i.e. as configured in System Prefs -> General).

The problem is, if you're using iTerm with your own dark background, and have the system set to light mode, you end up with what's shown above. `bat` defaults to `--theme='Monokai Extended Light'`, which is almost unreadable on a dark background.

To workaround and restore the old colorscheme, you have a few options; I like this one:

```bash
bat --generate-config-file

vim ~/.config/bat/config
# uncomment the --theme line and set it to --theme="Monokai Extended"
```

I'll defer to experts like @Enselic on perhaps improving this behavior or making it more intuitive.

**Comment by zachwhaley** [comment]
Thanks @bjschafer that worked!
