### ISSUE TITLE
Bat cache build fix does not work as suggested (error: Found argument '--build' which wasn't expected, or isn't valid in this context)

### ISSUE THREAD

**Issue by beauwilliams** [sharkdp/bat#2318]
<img width="1800" alt="Screen Shot 2022-09-16 at 11 24 33 am" src="https://user-images.githubusercontent.com/7098556/190536626-a7cc4d79-ccee-4bd9-b3cf-e9968f8ebf44.png">

...

**What did you expect to happen instead?**
The bat cache should rebuild
...

**How did you install `bat`?**

Homebrew (M1 /opt/ aarch64)

---

**bat version and environment**
0.22.1

**Comment by beauwilliams** [comment]
This is the temporary fix here https://github.com/sharkdp/bat/issues/1726#issuecomment-878990043

It is caused by the local directory having a folder named 'cache' I was working in.

I'll close for now as its an easy fix.

**Comment by enligh10ed** [comment]
How do I Unsubscribe to all github threads?
