### ISSUE TITLE
Editing a custom syntax didn't work until I made a new syntax file for it

### ISSUE THREAD

**Issue by Flurrywinde** [sharkdp/bat#2321]
**What steps will reproduce the bug?**

1. Add a new syntax ([details](https://github.com/sharkdp/bat/issues/2320) in this issue) called ChoiceScript.
2. Modify it.

**What happens?**

The modification doesn't work. Bat's output doesn't reflect the modifications to the syntax file, but it correctly applies the original syntax rules.

**What did you expect to happen instead?**

Bat's output should reflect the changes to the syntax file, and it does if I make another new syntax, nearly identical to the first:

![Comparison of the two syntaxes](https://user-images.githubusercontent.com/27073281/190925498-4a322b7f-0284-4497-9b2f-ebb727e50981.jpg)

**How did you install `bat`?**

`yay bat`

**bat version and environment**

#### Software version

bat 0.22.1 (e5d95796)

#### Operating system

Linux 5.15.68-1-lts

#### Command-line

```bash
bat -l ChoiceScript --color=always --highlight-line 7 --style=header,grid,numbers 'vimwiki/testchoicescript.wiki' --diagnostic 
```

#### Environment variables

```bash
SHELL=/usr/bin/fish
PAGER=<not set>
LESS='-R -Ps?f%F .?m(%T %i of %m) .?Pb(%Pb\%) .?lt(Line %lt?L of %L.?c, Col %c.) .?nPrompt'\!''\!''\!' .?e(END) ?x- Next\: %x..'
LANG=en_US.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='less -s'
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

```
# This is `bat`s configuration file. Each line either contains a comment or
# a command-line option that you want to pass to `bat` by default. You can
# run `bat --help` to get a list of all possible configuration options.

# Specify desired highlighting theme (e.g. "TwoDark"). Run `bat --list-themes`
# for a list of all available themes
#--theme="TwoDark"

# Enable this to use italic text on the terminal. This is not supported on all
# terminal emulators (like tmux, by default):
#--italic-text=always

# Uncomment the following line to disable automatic paging:
#--paging=never

# Uncomment the following line if you are using less version >= 551 and want to
# enable mouse scrolling support in `bat` when running inside tmux. This might
# disable text selection, unless you press shift.
#--pager="less --RAW-CONTROL-CHARS --quit-if-one-screen --mouse"

# Syntax mappings: map a certain filename pattern to a language.
#   Example 1: use the C++ syntax for Arduino .ino files
#   Example 2: Use ".gitignore"-style highlighting for ".ignore" files
#--map-syntax "*.ino:C++"
#--map-syntax ".ignore:Git Ignore"
```

#### Custom assets metadata

```
---
bat_version: 0.22.1
creation_time:
  secs_since_epoch: 1663528350
  nanos_since_epoch: 576712839
```

#### Custom assets

- metadata.yaml, 101 bytes
- syntaxes.bin, 905106 bytes
- themes.bin, 40498 bytes

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 608 (PCRE2 regular expressions)
Copyright (C) 1984-2022  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
You need to run `bat cache --build` again after making changes. That is the expected behavior.

**Comment by Enselic** [comment]
@Flurrywinde: See https://github.com/sharkdp/bat/issues/2085 for some discussion on how to make this smoother for users
