### ISSUE TITLE
read file in reverse, last line show first

### ISSUE THREAD

**Issue by erlangparasu** [sharkdp/bat#2322]
is it possible? :)

**Comment by Z4K4RI4** [comment]
If you are on a UNIX shell, you can go for something like : 
`tac foo.txt | bat`

**Comment by keith-hall** [comment]
due to the way `bat` prints one line at a time, in order to cope with long files / infinite stdin streams etc., this is out of scope for `bat`. Using a preprocessor like `tac` is the recommended approach.

**Comment by keith-hall** [comment]
see also https://github.com/sharkdp/bat/issues/2289
