### ISSUE TITLE
thread `main` panicked: Attempted to zero-initialize type `libgit2_sys::git_diff_options`

### ISSUE THREAD

**Issue by aprotyas** [sharkdp/bat#2323]
**What steps will reproduce the bug?**

I haven't found an MVP except that the error fires when I run `bat <file>` in a local git repository. I don't see this outside of a git repo though, so for example `bar /tmp/foo` runs fine.

1. `cd <local/git/repo>`
2. `bat <file>`

**What happens?**

```sh
$ RUST_BACKTRACE=full bat data.json
thread 'main' panicked at 'attempted to zero-initialize type `libgit2_sys::git_diff_options`, which is invalid', /usr/share/cargo/registry/bat-0.12.1/debian/cargo_registry/git2-0.8.0/src/diff.rs:451:27
stack backtrace:
   0:     0x55a725cce7c6 - <unknown>
   1:     0x55a725cfe5dc - <unknown>
   2:     0x55a725cbf9d5 - <unknown>
   3:     0x55a725cc7f51 - <unknown>
   4:     0x55a725cc7b51 - <unknown>
   5:     0x55a725cc84a1 - <unknown>
   6:     0x55a725ccef82 - <unknown>
   7:     0x55a725cce8f4 - <unknown>
   8:     0x55a725cc8032 - <unknown>
   9:     0x55a725b19491 - <unknown>
  10:     0x55a725b193dd - <unknown>
  11:     0x55a725c01a8b - <unknown>
  12:     0x55a725b68855 - <unknown>
  13:     0x55a725b2a736 - <unknown>
  14:     0x55a725b3f403 - <unknown>
  15:     0x55a725b407fa - <unknown>
  16:     0x55a725b44963 - <unknown>
  17:     0x55a725b64f49 - <unknown>
  18:     0x55a725cbde31 - <unknown>
  19:     0x55a725b44be8 - <unknown>
  20:     0x7f488dc63083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  21:     0x55a725b19bee - <unknown>
  22:                0x0 - <unknown>
```

**What did you expect to happen instead?**

`bat` shows the contents of `data.json`.

**How did you install `bat`?**

apt-get.

---

**bat version and environment**

This is the output of `info.sh`:

system
------

**$ uname -srm**
Linux 5.15.0-46-generic x86_64

**$ lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

bat
---

**$ bat --version**
bat 0.12.1

**$ env**

bat_config
----------

**$ cat /home/arahman/.config/bat/config**
```
--theme="ansi-light"
```

bat_wrapper
-----------

No wrapper script for 'bat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 551 (GNU regular expressions)

**Comment by aprotyas** [comment]
Looks like this may be a dupe of #2317

**Comment by HUGHNew** [comment]
Installing the latest release version can solve the problem simply.
