### ISSUE TITLE
"invalid charset name" on windows when listing supported languages

### ISSUE THREAD

**Issue by ShrykeWindgrace** [sharkdp/bat#2324]
**What steps will reproduce the bug?**

Grab a windows machine with powershell, then run
```console
PS> bat -L
```
**What happens?**
An error report is shown
```console
PS> bat -L
invalid charset name
```

**What did you expect to happen instead?**
A list of supported languages appears

Running `bat someFile.extension` works fine.

**How did you install `bat`?**
Via chocolatey:
```console
get-command bat

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     bat.exe                                            1.0.0.0    C:\ProgramData\chocolatey\bin\bat.exe
```

**bat version and environment**

(via `bat -L --diagnostic`)

#### Software version

bat 0.22.1 (e5d9579)

#### Operating system

Windows 6.2.9200

#### Command-line

```
C:\ProgramData\chocolatey\lib\Bat\tools\bat-v0.22.1-x86_64-pc-windows-msvc\bat.exe -L --diagnostic
```

#### Environment variables

```bash
SHELL=<not set>
PAGER=<not set>
LESS=<not set>
LANG=<not set>
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of 'C:\ProgramData\bat\config': The system cannot find the path specified. (os error 3).

#### Config file

```
# PS C:\Users\$USERNAME\AppData\Roaming\bat> bat .\config
--pager="C:\ProgramData\chocolatey\bin\less -FR"
```

#### Custom assets metadata

```
---
bat_version: 0.22.1
creation_time:
  secs_since_epoch: 1663231471
  nanos_since_epoch: 29464500
```

#### Custom assets

- metadata.yaml, 100 bytes
- syntaxes.bin, 898115 bytes
- themes.bin, 40498 bytes

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

Win10, Windows Terminal, Pwsh-7.2.6 with 65001 (unicode) codepage.

the 1252 codepage exhibits the same behavior, and so does `cmd`.

**Comment by keith-hall** [comment]
Thanks for reporting. I was going to ask whether it behaves differently with `bat -L --paging=never` but I see that `--paging=never` is ignored when listing languages... Maybe you can try setting your `BAT_PAGER` environment variable to blank to see if it makes any difference - I just want to rule out the pager somehow interfering/causing this.

**Comment by ShrykeWindgrace** [comment]
I did a bit of digging. It turns out I have a prehistoric `less` installed by my employer (version 340, released in 1999!). I also have a recent `less` installed by either scoop or chocolatey (version 608, released in 2022). Prehistoric `less` is higher in $PATH.

1. Without configuration file/env variables I get
```console
PS> bat -L
invalid charset name
PS> bat .\.vimrc
invalid charset name
```
That's not surprising, prehistoric `less` most probably wouldn't work at all.

2. Now I explicitly provide correct `less` as a pager in a CLI option:
```console
PS> bat .\.vimrc --pager="C:\Users\username\scoop\shims\less.exe -FR"
# Here goes correct output, but scrolled to the end
```
At least I have something, but paging did not work.

However,
```console
PS> bat -L --pager="C:\Users\username\scoop\shims\less.exe -FR"
invalid charset name
```

3. Ok, let's set an env variable: 
```console
PS> $env:BAT_PAGER
C:\Users\username\scoop\shims\less.exe -FR
PS> bat -L
# correct output scrolled to the end
# same for bat .\.vimrc
```
We have output, but no paging at all

4. Drop env variable, configure via a file:
```console
PS> bat $(bat --config-file) -p
--pager="C:\Users\username\scoop\shims\less.exe -FR"
```
And - surprisingly, I admit - 
```console
PS> bat -L
invalid charset name
PS> bat .\.vimrc
# output without pagination
```
5. At this point I gave up, force-removed prehistoric `less` (at risk that other employer-provided tools would break), dropped all configuration files and env variables for `bat`; essentially, only `less` from `scoop` remains.
```console
PS> bat -L
# list of laguages with pagination
PS> bat .\.vimrc
# output with pagination
```

Conclusion:
- `bat`+`less` work well with recent `less` without config
- `bat -L` seems to ignore `--pager`, but takes `$env:BAT_PAGER` into account
- pagination is broken whenever `less` was overridden (be that via CLI option, env var, or config file).

@keith-hall what do you mean by "setting to blank"?  Setting `$env:BAT_PAGER=''` is equivalent to unsetting this variable, and I never set it (except in one experiment above).

**Comment by keith-hall** [comment]
Thanks for the investigation and sharing the results.


> what do you mean by "setting to blank"? Setting `$env:BAT_PAGER=''` is equivalent to unsetting this variable, and I never set it (except in one experiment above).

ah, my mistake, I somehow thought setting it to blank is not the same as the env var not being set at all. Your tests proved what I wanted anyway, so thanks :)

**Comment by milnak** [comment]
+1. tl;dr - I had an old "less.exe" in my path which was conflicting with bat.  

Deleting that less.exe (I found it using `scoop install which` then `which less.exe`) fixed the problem.
