### ISSUE TITLE
Multibyte emoji display is wrong(or is it intend to be like that)

### ISSUE THREAD

**Issue by kolulu23** [sharkdp/bat#2328]
**What steps will reproduce the bug?**

test-multibytes.txt
```txt
👩‍👩‍👧
🤌💩
😇😵‍💫🤮
😸😻👻🤠
🤲🏻👊🏻🤛🏻🤜🏻👐
🤖🤡👽👿👹👺
```

```bash
bat test-multibytes.txt -p
```

**What happens?**

It seems that `bat` did not display or read these emojis correctly:

```
👩<U+200D>👩<U+200D>👧
🤌💩
😇😵<U+200D>💫🤮
😸😻👻🤠
🤲🏻👊🏻🤛🏻🤜🏻👐
🤖🤡👽👿👹👺
```

I also noticed that `less` also has the same problem reading these emojis.

**What did you expect to happen instead?**

while `cat` is fine:

```
👩‍👩‍👧
🤌💩
😇😵‍💫🤮
😸😻👻🤠
🤲🏻👊🏻🤛🏻🤜🏻👐
🤖🤡👽👿👹👺
```

**How did you install `bat`?**

```
cargo install bat
```

---

**bat version and environment**
1. bat 0.22.1
2. OS: macOS big sur
3. Shell: Bash and Zsh

**Comment by keith-hall** [comment]
Did you try `bat` with `--paging=never` to ensure that `less` isn't invoked?

**Comment by kolulu23** [comment]
Thanks @keith-hall . Adding `--paging=never` solves the issue. 
So I guess it is `less` causing the display problem right? 

I also just found that I could use `--pager="less -r"` to correctly display emojis without turning off paging.
