### ISSUE TITLE
Raspberry Pi Exec Format Error

### ISSUE THREAD

**Issue by daBee** [sharkdp/bat#2331]
**What steps will reproduce the bug?**

`bat /etc/hosts`

**What happens?**
`-bash: /usr/local/bat/bat: cannot execute binary file: Exec format error`

**What did you expect to happen instead?**
For it to work.  

**How did you install `bat`?**
`sudo apt install -y bat`
Note: `apt search bat` shows the following:
```
bat/stable,now 0.12.1-6+b2 arm64 [installed]
  cat(1) clone with syntax highlighting and git integration
```
**bat version and environment**

```
[Fri Sep 30 04:56:56 user3@myzero2 ~/rfs] /usr/local/bat/bat -v
-bash: /usr/local/bat/bat: cannot execute binary file: Exec format error
```

```
[Fri Sep 30 06:22:14 user3@sniff ~] bat --diagnostic
#### Software version

bat 0.19.0 (59a8f58)

#### Operating system

Linux 5.15.32-v7l+

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
LANG=en_CA.UTF-8
LC_ALL=en_CA.UTF-8
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### Config file

Could not read contents of '/home/user3/.config/bat/config': No such file or directory (os error 2).

#### Compile time information

- Profile: release
- Target triple: arm-unknown-linux-gnueabihf
- Family: unix
- OS: linux
- Architecture: arm
- Pointer width: 32
- Endian: little
- CPU features: unknown
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
```

`Orange Pi`, same thing, even worse:

```
[Fri Sep 30 06:23:32 orangepi@orange ~] bat --diagnostic
-bash: /usr/local/bat/bat: cannot execute binary file: Exec format error
```

```
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
```

**Comment by BRA1L0R** [comment]
what is the model of the raspberry pi you're using?

**Comment by daBee** [comment]
Does not work: `Model		: Raspberry Pi Zero 2 W Rev 1.0`

Same issue on an `Orange Pi Zero 2`.  

`bat` behaves properly on this unit: `Raspberry Pi 4 Model B Rev 1.2`

**Comment by sharkdp** [comment]
Haven't checked any specifics, but could you please try the other arm executable we provide? maybe the platform does not line up?

**Comment by daBee** [comment]
Not sure what you mean by "the other arm executable we provide".  Also, **Raspberry Pi** is a collection of hardware, and **Orange Pi** is a completely separate but similar line.  My Orange Pi is `Ubuntu 22.04.1 LTS`.  My `RPi Zero 2 W` is using `Debian GNU/Linux 11 (bullseye)`.

**Comment by sharkdp** [comment]
https://github.com/sharkdp/bat/releases

![image](https://user-images.githubusercontent.com/4209276/200071325-4e445ac3-093d-43a9-8ade-94d87a403a55.png)

**Comment by daBee** [comment]
Sorry for the delay.  First red arrow item works on `Orange Pi` and `RPi Zero 2 W`.
