### ISSUE TITLE
not output 

### ISSUE THREAD

**Issue by sad12blog** [sharkdp/bat#2343]
**What steps will reproduce the bug?**

1. just running bat alone with no argument or file  

**What happens?**

gets stuck if no argument is provided with bat like ```$ bat ```

**What did you expect to happen instead?**

to output the help menu if no argument is provided with the file 
![image show casing](https://user-images.githubusercontent.com/98783569/193453855-9ae9635b-5149-4028-8dce-5ddcfbca7244.png)

**How did you install `bat`?**
cloned from the repo 

**bat version and environment**
bat 0.12.1

**Comment by keith-hall** [comment]
This is actually not a bug, `cat` behaves the same way - with no arguments it expects to read from "standard input". As nothing was piped into `bat`, your terminal sends your input keystrokes as the stdin stream. When you have finished typing, you would press <kbd>Ctrl+D</kbd>. https://unix.stackexchange.com/a/16338/152147

I understand this is different from other programs which expect arguments, but realistically `bat` doesn't differentiate between an interactive stdin stream and a non-interactive one, and behaves like this for compatibility with `cat`.
