### ISSUE TITLE
wrong render for help

### ISSUE THREAD

**Issue by Freed-Wu** [sharkdp/bat#2344]
`bat -plhelp` should render `BUILTIN-LIST` to red, not only `BUILTIN`.

![Screenshot from 2022-10-03 00-29-10](https://user-images.githubusercontent.com/32936898/193465211-d1f6de9f-f29e-4434-9175-75ac5ce211f4.png)

**Comment by keith-hall** [comment]
The cmd-help syntax is provided by https://github.com/victor-gp/cmd-help-sublime-syntax/tree/aa477471c870360bd1705a1a370d67b7c6fbe731, probably it would be worth logging this issue there, then once it is fixed upstream, we will bump our dependency to have it fixed in `bat` also.
