### ISSUE TITLE
Packages is too old

### ISSUE THREAD

**Issue by Freed-Wu** [sharkdp/bat#2358]
<https://github.com/sharkdp/bat/tree/master/assets/syntaxes>'s `01_Packages` is too old (3 years ago). Why not write a github action when the upstream publish a version, update automatically? Thanks.

**Comment by keith-hall** [comment]
We currently don't do this simply because we can't - the syntax highlighting library we use isn't yet compatible with the latest features of `.sublime-syntax` files used in that repository.

https://github.com/trishume/syntect/issues/323
https://github.com/trishume/syntect/issues/271
