### ISSUE TITLE
Incomplete syntax highlighting for ssh config?

### ISSUE THREAD

**Issue by XenHat** [sharkdp/bat#2359]
_Sorry if this is a duplicate, I could not find an issue that matched this._

There seem to be a missing keyword match for `User` while parsing ssh configurations:
![Screenshot_20221006_100551](https://user-images.githubusercontent.com/980408/194334341-57b58620-8ac6-44e4-ab87-42a7f1f7838f.png)

While not explicitly referenced in [ssh_config(5)](https://man.archlinux.org/man/ssh_config.5), it is mentioned in [the Arch Linux wiki](https://wiki.archlinux.org/title/OpenSSH#Configuration) and does appear to work:

```~ ∙ ssh -v zarya 2>&1 | grep DOES_THIS                                                                         130 ↵
debug1: Control socket "/home/xenhat/.ssh/sockets/DOES_THIS_WORK/" does not exist
unix_listener: cannot bind to path /home/xenhat/.ssh/sockets/DOES_THIS_WORK/.iZ9SgH1lGBRJVscA: No such file or directory
```

Something to note, however: neovim also fails to apply the ssh-specific parsing:
![Screenshot_20221006_100805](https://user-images.githubusercontent.com/980408/194334727-8021f36d-828b-4c35-811c-784e27c40840.png)

So after all, I'm not sure if this actionable at all, but I thought I should mention it.

**Comment by mrmeszaros** [comment]
@keith-hall the issue has been fixed - feel free to pull it in :)
