### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by 0xphk** [sharkdp/bat#236]
Not sure if this is an issue, but git integration is not working in two particular cases for me.

1. if modified document is located in in few subfolders beyond document root where .git is located
2. if modified document isn't in master branch
(3.) maybe it could be a combination of both, will test this case later

When I tested with .git and modified document in same folder @ master branch and it works and shows the differences. Do I miss something which needs to be configured? Could not find any hints in the man page.

Can provide more infos if it's an real issue

**Comment by sharkdp** [comment]
Do you see the modifications when running `git diff`? Otherwise, bat will not show them.

If there is a problem, please provide a way to reproduce this.
