### ISSUE TITLE
bat -l'' will hang

### ISSUE THREAD

**Issue by Freed-Wu** [sharkdp/bat#2373]
**What steps will reproduce the bug?**

1. `bat -l'' test.txt`

**What happens?**

Hang.

...

**What did you expect to happen instead?**

```
[bat error]: unknown syntax: ''
```

**Comment by nrabulinski** [comment]
It doesn't hang but instead waits for input from stdin and treats `test.txt` as the value given to `-l`

**Comment by Freed-Wu** [comment]
> It doesn't hang but instead waits for input from stdin

Thanks, I see.

**Comment by Freed-Wu** [comment]
It still a little confused because I thought stdin should use `-` (`bat -l-`) now use empty string. Should we support using `-` to represent stdin?

**Comment by Enselic** [comment]
We already do :)

The code that handles it is here: https://github.com/sharkdp/bat/blob/f215d07366dac50aa7068e9c3f8d5f46b09b4c1a/src/bin/bat/app.rs#L298-L299

However, to remain compatible with `cat`, we also need to keep the current behaviour where no file means to read stdin. Compatibility with `cat` is one of the key features of `bat`.
