### ISSUE TITLE
Negative lower range for --line-range option

### ISSUE THREAD

**Issue by HamletDuFromage** [sharkdp/bat#2377]
It'd be nice to be able to execute `--line-range=-10:` and get the last 10 lines, like `tail` does.

Problems are as follows though
- negative numbers are currently parsed as flags
- `LineRange::default()` initializes the upper bound at `size::max_value()` so but we'd need it to be the line count of of the file

**Comment by keith-hall** [comment]
See also https://github.com/sharkdp/bat/issues/791

**Comment by HamletDuFromage** [comment]
Ah right, I missed that issue. Thank you
