### ISSUE TITLE
panic when opening a file in a git repository.

### ISSUE THREAD

**Issue by Horlarwumhe** [sharkdp/bat#2384]
**What steps will reproduce the bug?**

1. clone any GitHub repository. Use bat repository as an example
2. git clone https://github.com/sharkdp/bat
3. cd bat
4. Try to open any file. README.md as an example
5. batcat README.md

**What happens?**

This error occurs,  
```thread 'main' panicked at 'attempted to zero-initialize type `libgit2_sys::git_diff_options`, which is invalid', /usr/share/cargo/registry/bat-0.12.1/debian/cargo_registry/git2-0.8.0/src/diff.rs:451:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
...

**What did you expect to happen instead?**
Expected output

**How did you install `bat`?**

sudo apt install bat

**bat version and environment**
bat version: 0.12.1
Environment:

SHELL=/bin/bash
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
SGX_AESM_ADDR=1
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
SHLVL=1
XDG_SESSION_ID=578
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/HorlarVM/.local/bin:/home/HorlarVM/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SSH_TTY=/dev/pts/0

system
------

**$ uname -srm**
Linux 5.15.0-1021-azure x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID: Ubuntu  
Description:    Ubuntu 20.04.5 LTS  
Release:        20.04  
Codename:       focal  

bat
---

**$ batcat --version**
bat 0.12.1  

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script for 'bat'.

No wrapper script for 'batcat'.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

No wrapper function for 'batcat'.

tool
----

**$ less --version**

less 551 (GNU regular expressions)

**Comment by benterris** [comment]
I had the same issue but it has been fixed in the latest version (`0.22.1`). You can download the `.deb` package on the [release page](https://github.com/sharkdp/bat/releases), the packages from the `apt` repositories are very outdated.

**Comment by sharkdp** [comment]
please see #2323 and #2317
