### ISSUE TITLE
paging not done if PAGER='less -R'

### ISSUE THREAD

**Issue by VVelox** [sharkdp/bat#239]
So if you have your PAGER env variable set to 'less -R' so some other things page nicely, paging fails with bat. Setting --paging always does not help.

Tested with both 0.5.0 and 0.6.0 and I am seeing the same in both.

**Comment by sharkdp** [comment]
Please see https://github.com/sharkdp/bat#using-a-different-pager

You (currently) need to use a separate script if you want to pass command-line options to the pager. Note that `bat` will pass a few command line options if the pager is set to `less`.

**Comment by VVelox** [comment]
On another note, found a work around. for less, you can pass arguments via $env{LESS}.
