### ISSUE TITLE
A cat(1) clone with wings — A great slogan (and pun)

### ISSUE THREAD

**Issue by porg** [sharkdp/bat#2400]
I love that slogan!
It's precise and equivocal and witty at the same time.
Great!

**Comment by porg** [comment]
P.S.: The app itself is ofc also great!
- I use it in my utility [coke](https://github.com/porg/coke/) for showing `-h` (help) which is simply calling `bat coke-manpage.md`.
- Great look & behavior! Thanks!

**Comment by sharkdp** [comment]
Thank you for the feedback!
