### ISSUE TITLE
syntax highlight for tabulated files

### ISSUE THREAD

**Issue by gennaro-tedesco** [sharkdp/bat#2402]
This issue is related to https://github.com/sharkdp/bat/issues/2078 and https://github.com/sharkdp/bat/issues/1662, expanding on it a little further.

Whilst `bat -l csv` works well in the majority of cases, one often columnates the output to pretty print in the terminal, namely
```bash
bat -l csv file.csv | column -s, -t 
```
piping the above again into `bat -l tsv` I would expect the (now tab-separated) columns to still be highlighted differently, however this is not the case. This holds true for all themes.

Is this expected behaviour (namely not to highlight the different columns if space/tab separated, after all) or shall one use another `-l` language option to achieve it?

**How did you install `bat`?**
```
brew install bat
```

**bat version and environment**
```bash
bat --version
bat 0.22.1
```
on
```
OS         macOS 12.6.0 Monterey                                        
Terminal   iTerm2 (Version 3.4.16)
Shell      /bin/zsh
```

**Comment by keith-hall** [comment]
Using the `column` command outputs space separated columns, and as `bat` operates one line at a time, there is no way for it to determine where the column starts or ends (as some columns contain spaces) so I suspect there is no way to pipe it back into `bat` to get colors, but:

Perhaps just tell `bat` to keep the colors even though you are piping the output somewhere else:

`bat -l csv file.csv --color=always | column -s, -t `

**Comment by gennaro-tedesco** [comment]
> Perhaps just tell bat to keep the colors even though you are piping the output somewhere else:

This works, I will do so, thank you!!

**Comment by tijptjik** [comment]
FWIW - bat __can__ take the output of the above to display is nicely.

For example:

```sh
bat --force-colorization --style plain file.csv | column -s, -t | bat --wrap never --style grid --pager="less -RF --header 2"
```

renders as

![image](https://user-images.githubusercontent.com/645283/230330995-a2e6717e-f2c6-49bb-9149-c1fe73381b15.png)

- `--style plain` in the first invocation, ensures that `bat` doesn't decorate the output twice
- `--wrap never` ensures contents wider than your terminal don't break the layout,
- and the `--pager` settings help freeze the header.

![image](https://user-images.githubusercontent.com/645283/230331289-ae5ef5f1-81f1-486b-8e5a-6e40497873d4.png)

**Comment by gennaro-tedesco** [comment]
Yes, as mentioned is to use `--color=always` (which you are achieving via `--force-colorization`): great write up and example though!
