### ISSUE TITLE
Fish completions

### ISSUE THREAD

**Issue by Susensio** [sharkdp/bat#2403]
**What steps will reproduce the bug?**

I'm running bat 0.22.1-1 from Debian Unstable and Fish 3.5.1, I would like to use completions but I cannot find them in my system. I can see them in this repo and I know i could copy them manually.
Shouldn't completions be installed automatically?

**What happens?**

...

**What did you expect to happen instead?**

...

**How did you install `bat`?**

---

**bat version and environment**

**Comment by sharkdp** [comment]
I think this should be reported on the Debian bug tracker. We don't have any influence on official packaging in Debian.
