### ISSUE TITLE
Add lesspipe to Alternatives table?

### ISSUE THREAD

**Issue by anntzer** [sharkdp/bat#242]
lesspipe (https://github.com/wofr06/lesspipe) allows one to do `less foo` and preprocess foo with a command depending on the file extension.  For example, it will extract text from pdfs, list contents of tarballs, etc.  It will also, more relevant here, highlight source code -- either with a builtin perl script (code2color), or through pygmentize.

So you get everything in the pygments column, plus automatic paging.  (Plus other stuff not relevant to the comparison, i.e. handling of binary formats.)

**Comment by sharkdp** [comment]
Thank you for the feedback. I hadn't heard about `lesspipe`. Sounds like we should add it to the list of alternatives, yes.
