### ISSUE TITLE
all lines printed as blank on win10, alacritty, nushell

### ISSUE THREAD

**Issue by amstaniec** [sharkdp/bat#2425]
**What steps will reproduce the bug?**

1. open terminal (I use alacritty 0.11.0)
2. open shell prompt (I use nushell 0.68.1)
3. bat textfile.txt

**What happens?**

bunch of empty lines are printed and new prompt appears

**What did you expect to happen instead?**

contents of the files to be printed (and visible)

**How did you install `bat`?**

`scoop install bat`

**bat version and environment**

#### Software version

bat 0.22.1 (e5d9579)

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
C:\Users\xxx\scoop\apps\bat\current\bat.exe --diagnostic C:\Windows\Tornado.INI
```

#### Environment variables

```bash
SHELL=<not set>
PAGER=<not set>
LESS=<not set>
LANG=en_US.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of 'C:\ProgramData\bat\config': The system cannot find the path specified. (os error 3).

#### Config file

Could not read contents of 'C:\Users\xxx\AppData\Roaming\bat\config': The system cannot find the path specified. (os error 3).

#### Custom assets metadata

Could not read contents of 'C:\Users\xxx\AppData\Local\bat\metadata.yaml': The system cannot find the path specified. (os error 3).

#### Custom assets

'C:\Users\xxx\AppData\Local\bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```
> C:\Users\xxx\scoop\shims\less.exe --version
less 394
Copyright (C) 1984-2005 Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by sharkdp** [comment]
Thank you for reporting this. Does it work in other shells? In other terminals?

**Comment by amstaniec** [comment]
I think this was actually a problem with `less`, not directly with `bat`
