### ISSUE TITLE
Add Support for Rusty Object Notation (RON)

### ISSUE THREAD

**Issue by kamaaina** [sharkdp/bat#2427]
**Syntax:**
RON - Rusty Object Notation - https://github.com/ron-rs/ron

**Guideline Criteria:**
https://packagecontrol.io/packages/RON

**Comment by keith-hall** [comment]
Forgive the silly question: I see RON is designed to be similar to Rust syntax - can we not just map RON files to the Rust syntax definition? It would be preferable to bundling another syntax, especially one that isn't super popular. Or is there something that wouldn't get highlighted correctly?

**Comment by kamaaina** [comment]
yup, i too think that will work (mapping RON to rust syntax). mahalo!

**Comment by 13-05** [comment]
yes, this seems to work fine (see attached image). could i just fork and pr after making it do the same thing for ron as it does for rust? it seems that'd be pretty trivial to do
![image](https://user-images.githubusercontent.com/64506392/229329057-3ebd08bd-a905-41ba-834e-a86c5751ebaa.png)

**Comment by keith-hall** [comment]
> yes, this seems to work fine (see attached image). could i just fork and pr after making it do the same thing for ron as it does for rust? it seems that'd be a pretty trivial change, after all. ![image](https://user-images.githubusercontent.com/64506392/229329057-3ebd08bd-a905-41ba-834e-a86c5751ebaa.png)

yes, PRs are welcome :) note that the Rust syntax definition comes from a submodule which we can't update at the moment, so your choices are to make a patch for it or add it to https://github.com/sharkdp/bat/blob/master/src/syntax_mapping.rs.

**Comment by peppermenta** [comment]
Hi

Can I work on this?

**Comment by Horgix** [comment]
:wave: Hi, I was looking into good first issues to contribute on, and I believe this one can be closed given it was solved by #2642 , doesn't it? Just figured i would notify along the way :slightly_smiling_face:

**Comment by Enselic** [comment]
Indeed, thanks 🙂
