### ISSUE TITLE
Inject spaces in ill-formatted markdown tables

### ISSUE THREAD

**Issue by lgastako** [sharkdp/bat#2445]
The markdown table in this screenshot is a perfectly valid table that renders fine

![Screen Shot 2023-01-12 at 4 05 29 AM](https://user-images.githubusercontent.com/1300/212024885-c6ddce83-74a9-4b3f-8431-7b6d50103b88.png)

But I, and I think most others, would prefer to see the table with padded spacing to make everything align nicely.  Actually, what I'd really prefer is instead of spaces to be able to configure the character that gets inserted, and the color, so I could get an effect like Emacs' whitespace-mode, like so, but with the dots being a dark gray so they are unobtrusive.

![Screen Shot 2023-01-12 at 4 14 57 AM](https://user-images.githubusercontent.com/1300/212026658-ccdf3019-70cf-4b9b-9572-851579118e44.png)

Had I come across this at almost any other point in my life I would have taken it as an excuse to learn Rust and submit a PR but unfortunately my personal and professional obligations preclude me from even considering it.

Thanks for bat, it's fantastic!

**Comment by keith-hall** [comment]
Thanks for your request and kind words. Unfortunately I believe making changes to the file/input being displayed is out of scope for `bat`. I have gone into a bit more detail previously: https://github.com/sharkdp/bat/issues/1908#issuecomment-945176197 and https://github.com/sharkdp/bat/issues/1592#issuecomment-802926175

**Comment by eth-p** [comment]
I agree with @keith-hall on this. You could us [mdformat](https://github.com/executablebooks/mdformat) with a wrapper to achieve what you want, though!

```bash
mbat() {
    local file="$1"
    local args="${@:2}"

    mdformat - < "$file" | sed $'/^| /s/ /\x1B[2;37m.\x1B[0m/g; /^|\x1B\\[2;37m/s/\x1B\\[2;37m.\x1B\\[0m|/ |/g; /^|\x1B\\[2;37m/s/|\x1B\\[2;37m\./| /g' | bat -lMarkdown --file-name="$file" "${args[@]}" || return $?
}
```

The `sed` expression replaces the spaces within the table with dim-coloured `.`.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/32112321/212394942-b906a538-e4c8-4e49-8366-14256767e906.png">
