### ISSUE TITLE
no syntax highlighting on all file formats on Windows

### ISSUE THREAD

**Issue by tigerinus** [sharkdp/bat#2448]
**What steps will reproduce the bug?**

1. Install bat for windows
2. Run `bat` against any supported file format

**What happens?**

![image](https://user-images.githubusercontent.com/7172560/213236934-fa7927f7-ca28-42b1-8f5d-e7dca3b2c460.png)

**What did you expect to happen instead?**

![image](https://user-images.githubusercontent.com/7172560/213237306-363a0cac-3bbc-4f73-954a-647adf00455a.png)

**How did you install `bat`?**

 GitHub release

**bat version and environment**

#### Software version

bat 0.22.1 (e5d9579)

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=<not set>
PAGER=<not set>
LESS=<not set>
LANG=<not set>
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of 'C:\ProgramData\bat\config': The system cannot find the path specified. (os error 3).

#### Config file

Could not read contents of 'C:\Users\xiaoh\AppData\Roaming\bat\config': The system cannot find the path specified. (os error 3).

#### Custom assets metadata

Could not read contents of 'C:\Users\xiaoh\AppData\Local\bat\metadata.yaml': The system cannot find the path specified. (os error 3).

#### Custom assets

'C:\Users\xiaoh\AppData\Local\bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```

**Comment by keith-hall** [comment]
Did you try with something other than Command Prompt? Like PowerShell, Windows Terminal, Git Bash for Windows etc.?
Did you see the info in the readme about this? https://github.com/sharkdp/bat#colors

**Comment by keith-hall** [comment]
Also, did you try with `--paging=never`? It definitely should work on Windows, others have reported `bat` working on that platform...

**Comment by tigerinus** [comment]
I cannot reproduce this issue anymore after came back to my computer from a trip.

![image](https://user-images.githubusercontent.com/7172560/215339008-57ade8b1-4d53-4129-acba-3ef7ad49b476.png)

Things are just looking fine.

Thanks for all the follow ups!
