### ISSUE TITLE
Q: Toggle line numbers on and off while viewing - is it possible?

### ISSUE THREAD

**Issue by HenrikBengtsson** [sharkdp/bat#2474]
# Question

Is it possible to toggle line numbers on and off while viewing a file?  (This would be useful if you ever need to cut'n'paste a few lines from a file)

# Here is what I've tried

## Entering `-p`

Given that

```sh
bat -p README.md
```

suppresses line numbers, I though entering `-p` would toggle them, but instead I get an error:

```
Cannot change the -p (--pattern) option  (press ENTER)
```

Looks like CLI option `-p` is overridden by an in-viewer option.

## Entering `-n` or `-N`

I view a file with:

```sh
bat README.md
```

which decorates each line with a line number.  Then, when I type `-n`, while viewing, there is a message saying:

```
Don't use line numbers  (press ENTER)
```

Here, I expect/hope that `bat` would re-render the file and display the file without line numbers.  FWIW, if I type `-n` again, then it says:

```
Use line numbers  (press ENTER)
```

Entering `-n` will keep switching between these two messages, but there is no visual difference AFAICT.

I also tried `-N`, but no effect.

# Session info

```sh
$ bat --version
bat 0.22.1 (e5d9579)
henrik@hb-x1-2023:~/repositories/ansible-hb-x1-20
```

**Comment by prajnastra** [comment]
Currently, there is no way to toggle line numbers.

**Comment by prajnastra** [comment]
@sharkdp I would love to add a PR for this. Should I?

**Comment by keith-hall** [comment]
See also https://github.com/sharkdp/bat/issues/1053

**Comment by sharkdp** [comment]
> @sharkdp I would love to add a PR for this. Should I?

I don't think it's possible to implement this right now without fundamentally changing how we interact with the pager. As @keith-hall mentioned, please see #1053.

**Comment by sharkdp** [comment]
This is also related to #1177. Closing for now.

**Comment by HenrikBengtsson** [comment]
Thanks for the quick comments and answers
