### ISSUE TITLE
Highlighting text plain

### ISSUE THREAD

**Issue by pwsandoval** [sharkdp/bat#2477]
Not sure if I qualify this as a bug, I use windows 11 and windows terminal.

I have installed bat in powershell using scoop and in a bash shell (ubuntu using WSL), both have the same configurations and same version, but I think the plain text doesn't show the same.

For example, showing the same configuration file, left powershell, right bash

![config](https://user-images.githubusercontent.com/15174704/218575374-b51d6e59-a0ac-4cf6-90dc-fe50e4e1b9af.png)
_On the left there is a highlighting of the = symbols and the values of the options, on the right everything is white_

The second example showing a test .bashrc file both show the same, all white, is this normal behavior?

![rc](https://user-images.githubusercontent.com/15174704/218575280-ea50fa52-75ee-473a-96f4-3d1c83562b06.png)

I also [posted a question](https://github.com/sharkdp/bat/discussions/2476) in the discussion about an error I got when installing on windows with scoop, but I don't think it matters as it worked anyway.

Thanks for your time.

Edit:

Same with json:

![rick](https://user-images.githubusercontent.com/15174704/218577099-af5bde7e-1c25-4d6b-b228-2eeadfd6f7a0.png)

What is the default theme?

**Comment by keith-hall** [comment]
For the `.pwrc` file, I'm guessing `bat` just doesn't know to highlight it as PowerShell code, so you could try `bat -l'PowerShell' .pwrc`.

As for in WSL, does it help to specify `--color=always`?

The default theme is `Monokai Extended`: https://github.com/sharkdp/bat/blob/master/src/assets.rs#L112
