### ISSUE TITLE
Handling of binary files in interactive mode

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#248]
When `bat` is operating in non-interactive (`cat`-compatibility) mode, binary files are handled fine (see #150).

However, when `bat` is in interactive mode (prints to a terminal), we currently just print all the content in a (lossy) UTF-8 decoded way, which is not helpful at all.

It would be great if `bat` could detect "binary" files (I recently wrote a small crate to do just that: [https://github.com/sharkdp/content_inspector](`content_inspector`)) and print a user-friendly error message / warning.

A potential nice add-on could be to print the first N bytes in `hexdump` style.

**Comment by sharkdp** [comment]
Released in [v0.8.0](https://github.com/sharkdp/bat/releases/tag/v0.8.0)

**Comment by for-coursera** [comment]
> A potential nice add-on could be to print the first N bytes in hexdump style.

This isn't done, right? :)

**Comment by sharkdp** [comment]
No. If you think that should be added, please open a new ticket.
