### ISSUE TITLE
[ENH Request] - Need capability in BAT to read compressed files without uncompressing

### ISSUE THREAD

**Issue by ciscohack** [sharkdp/bat#2483]
Hello Experts,

Is it possible to add a feature in the upcoming BAT update where it is able to read the compressed file without uncompressing it? I see there is a pager tool name moar that has this capability but I am looking same in BAT.

If moar has this feature I don't think it's tough to add in BAT as well. looking positve

**Comment by sharkdp** [comment]
This has been discussed several times, please search the issue tracker.

**Comment by ciscohack** [comment]
@sharkdp Thanks for the comment... I tried searching in issue tickets but not found.... will research but if this is discussed what is the outcome ..we will add the feature or not

**Comment by keith-hall** [comment]
https://github.com/sharkdp/bat/issues/748#issuecomment-557933289

**Comment by ciscohack** [comment]
@keith-hall Thanks for the help. I followed this page and created plugins folder under bat config folder and downloaded uncompress lua script but it's not working... I don't know what wrong i am doing and hoe to fix it 

![image](https://user-images.githubusercontent.com/11479557/222927013-93336c1c-70c4-481a-a81f-81b40e05e0fe.png)
