### ISSUE TITLE
add justfile syntax support

### ISSUE THREAD

**Issue by Gictorbit** [sharkdp/bat#2488]
**Syntax:**
add support for `justfile` syntax
[just](https://github.com/casey/just)

**Guideline Criteria:**
[packagecontro.io link here]

**Comment by keith-hall** [comment]
https://packagecontrol.io/packages/Just
63 installs falls quite short of our guideline criteria... You can add it locally for yourself by following our readme btw :)

**Comment by gpskwlkr** [comment]
> https://packagecontrol.io/packages/Just 63 installs falls quite short of our guideline criteria... You can add it locally for yourself by following our readme btw :)

I think you're link is quite wrong, what @Gictorbit meant was just cli tool which he linked. Respectively this is the actual link [Just cli](https://crates.io/crates/just)

**Comment by sharkdp** [comment]
No, the link is correct. The just syntax in Sublime text (which we would need for `bat`) is not used by a lot of people. Please see https://github.com/sharkdp/bat/blob/master/doc/assets.md#criteria-for-inclusion-of-new-syntaxes

**Comment by sharkdp** [comment]
Also, please read https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions
