### ISSUE TITLE
Option to remove line numbering

### ISSUE THREAD

**Issue by andradei** [sharkdp/bat#250]
When viewing a file piped to `less`, the -N option adds/removes and extra column of line numbers instead of removing the one that is displayed by default.

This results in 2 line numbers.

To reproduce, just open a file with many lines and, once inside the pager, type `-N` then hit ENTER.

**Comment by jmbeach** [comment]
> -p, --plain
> 
>       Only show plain style, no decorations. This is an alias for
>       '--style=plain'. When '-p' is used twice ('-pp'), it also
>       disables automatic paging (alias for '--style=plain
>       --paging=never').

**Comment by xpe** [comment]
You might try: `bat README.md --style=-numbers`
