### ISSUE TITLE
HomeBrew SHA256 mismatch

### ISSUE THREAD

**Issue by ethanmsl** [sharkdp/bat#2510]
This is _not_ a bug with bat-extras-batman, but a bug with the homebrew download code.
(Happy to move this to whatever repo holds that ruby file.)

<img width="717" alt="bat-extras-batman SHA256 mismatch" src="https://user-images.githubusercontent.com/33399972/227149507-4b641307-192f-4768-9b9b-5a7dd79c7e1f.png">

Multiple attempts to download over a couple days, with repeated deletion of existing  files like `/Users/.../Library/Caches/Homebrew/downloads/...--bat-extras-2023.03.21.tar.gz` or anything with `bat-extras` in it, to be safe (in case of download corruption) have not yielded any success.

Is it that possible that the SHA256 listed in the homebrew `.rb` file for the package is incorrect?

**Comment by sharkdp** [comment]
This is not the correct repo, but please see https://github.com/eth-p/bat-extras/issues/88
