### ISSUE TITLE
Git Bash / MSYS2 support

### ISSUE THREAD

**Issue by borekb** [sharkdp/bat#252]
Hi, I installed binary to my Windows PC and am able to see `bat`'s behavior in Cmd.exe, however, most of the time, I'm in "Git Bash" (or, rather, MSYS2 mingw64 shell with zsh which is technically basically the same) and `bat` behaves exactly like `cat` for me:

![image](https://user-images.githubusercontent.com/101152/44947995-0a4afc00-ae16-11e8-9f6b-2d304516255d.png)

I tried starting my shell with `COLORTERM=24bit` and `...=truecolor` with no difference. This is what my terminal prints for the `$TERM` variable:

```
$ echo $TERM
xterm-256color
```

**Comment by sharkdp** [comment]
Does `bat --version` work in this terminal?

Does `bat --color=always` help?

**Comment by borekb** [comment]
```
$ bat --version
bat 0.6.1

$ bat --color=always README.md
# still the same output as `cat`
```

**Comment by sharkdp** [comment]
I think I have an idea of what might be causing this. Apparently [`ansi_term::enable_ansi_support`](https://docs.rs/ansi_term/0.11.0/i686-pc-windows-msvc/ansi_term/fn.enable_ansi_support.html) throws an error on some terminals. I opened #266 in order to just ignore these errors in `bat`.

Could someone please test this PR?

/cc @VladimirAlexiev

**Comment by sharkdp** [comment]
Fix released in [v0.7.0](https://github.com/sharkdp/bat/releases/tag/v0.7.0).

**Comment by borekb** [comment]
Thanks, works nicely. `bat` is awesome :)

**Comment by VladimirAlexiev** [comment]
Works for me, but there's a small glitch. When I go to the second page in less, I get a weirdly-colored line on top of the screen:
![image](https://user-images.githubusercontent.com/536250/45491160-ac050e00-b771-11e8-8200-70c0da552d2b.png)

I run with these less options:
`LESS=efij3wMqsx2`
