### ISSUE TITLE
replacing tabs with spaces

### ISSUE THREAD

**Issue by mvolkmann** [sharkdp/bat#253]
I want to use `bat` on source files that use tabs for indentation and replace them with 2 or 4 spaces. The instructions say to do that I need to "create a small shell script as a wrapper, for example:"
```bash
#!/bin/bash
less --tabs 2 -RF "$@"
```

Suppose I name this script `myless` and put it in `~/bin`. It's not clear to me whether I should set `PAGER` or `BAT_PAGER` to point to `myless`. What environment variable setting should make this work?

**Comment by sharkdp** [comment]
`PAGER` and `BAT_PAGER` should both work. Use `BAT_PAGER` if you only want this to be active for `bat`.

Make sure that
```
$BAT_PAGER file_with_tabs.txt
```

works for you (e.g. make sure that you `chmod +x my-less`). Afterwards, it should also work with `bat`.

**Comment by mvolkmann** [comment]
Sorry, I'm still missing some detail. I'm using bash. I have a script named myless that contains the following:
```bash
#!/bin/bash
less --tabs 2 "$@"
```
This script is in my path. When I run `myless some-file.txt` it works.
I set BAT_PATH to the full path to the `myless` script.
When I run `bat some-file.txt` a bunch of control characters output.

**Comment by sharkdp** [comment]
Make sure that you use the `-R` option of less less, otherwise it will not understand ANSI sequences.
