### ISSUE TITLE
syntax highlighting for csv files

### ISSUE THREAD

**Issue by tbsvttr** [sharkdp/bat#254]
Syntax highlighting for csv files would be nice. :)

**Comment by sharkdp** [comment]
Thank you for the feedback.

How would that work? What would you like to see highlighted? The commas? Apart from that, there isn't really much structure in a CSV file?

We would need some Sublime Text syntax that does CSV highlighting. Maybe something like this could work: https://packagecontrol.io/packages/rainbow_csv

**Comment by tbsvttr** [comment]
@sharkdp Thanks for your quick reaction. Yes, this looks like what I had in mind.

**Comment by sharkdp** [comment]
Added in [v0.7.0](https://github.com/sharkdp/bat/releases/tag/v0.7.0).
