### ISSUE TITLE
-pp should imply --tabs=0

### ISSUE THREAD

**Issue by Tachi107** [sharkdp/bat#2562]
The `-pp` command line option provides a quick way to disable styling components like line wrapping, line numbers, etc. Since the `--tabs` option is mainly useful to make the styling features work correctly, as described in e.g. #980, I believe it'd be nice to have `bat` pass though  tabs when asking for a super plain output.

Thanks for your work on bat!

**Comment by sharkdp** [comment]
Sounds reasonable to me, thank you.

**Comment by mikoreal** [comment]
Is this already implemented here or am I looking at a wrong thing?

line 230, /src/bin/bat/app.rs
<img width="822" alt="image" src="https://github.com/sharkdp/bat/assets/32268439/31808d07-4a33-4656-8060-b14776dc3615">

Right now bat --tabs arg works with -pp - I assume this is not the intended behaviour and instead it should be hardcoded to zero?

**Comment by sharkdp** [comment]
> 

No, I think this is fine — right?

If we already have this implemented, I think this can be closed. Feel free to comment if you think otherwise.
