### ISSUE TITLE
Add highlighting for `.cabal` configuration files for Haskell

### ISSUE THREAD

**Issue by ChShersh** [sharkdp/bat#257]
I noticed that files with `.cabal` extension (that are configuration files for `cabal-install` build tool for Haskell) are not highlighted with `bat`. It would be really great if `bat` could support those files as well!

Here is the documentation on the format:

* https://www.haskell.org/cabal/users-guide/developing-packages.html

**Comment by sharkdp** [comment]
Thank you for the feedback.

We would need a Sublime Text 3 syntax in order to support this.

**Comment by tobenna** [comment]
Here's [`.tmLanguage`](https://github.com/SublimeHaskell/SublimeHaskell/blob/master/Syntaxes/Cabal.tmLanguage) file for `.cabal`

Are there any guidelines for contributing new syntaxes?
Sublime Text can convert it to `sublime-syntax`

**Comment by sharkdp** [comment]
@tobenna 

> Are there any guidelines for contributing new syntaxes?

Kind of: https://github.com/sharkdp/bat/tree/master/assets#syntax-highlighting-in-bat

If you want to open submit a PR, please do *not* include the updated binary theme sets (`syntaxes.bin`, `themes.bin`) - just the new `.sublime-syntax` and possibly the new submodule.

**Comment by sharkdp** [comment]
Added in [v0.7.0](https://github.com/sharkdp/bat/releases/tag/v0.7.0).
