### ISSUE TITLE
Add support for language overides using Emacs or Vim modelines linguist style overrides

### ISSUE THREAD

**Issue by Lacusch** [sharkdp/bat#2571]
[Linguist](https://github.com/github-linguist/linguist/tree/master) (the Ruby library GitHub uses to highlight code) allows Vim / Emacs modelines to change the syntax highlighting of a single file  ([Docs link](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#using-emacs-or-vim-modelines)).
> Using Emacs or Vim modelines
>
> If you do not want to use .gitattributes to override the syntax highlighting used on GitHub.com, you can use Vim or Emacs style modelines to set the language for a single file. Modelines can be placed anywhere within a file and are respected when determining how to syntax-highlight a file on GitHub.com

**Comment by keith-hall** [comment]
https://github.com/sharkdp/bat/issues/1600

**Comment by Lacusch** [comment]
Thanks I'll close this as a duplicate.
