### ISSUE TITLE
Why don't releases include aarch64 build for apple/darwin?

### ISSUE THREAD

**Issue by ryanburnette** [sharkdp/bat#2573]

**Comment by eth-p** [comment]
I haven't touched the CI/CD stuff in a while, but @Enselic or @sharkdp might be able to give you a more detailed answer. :)

Some relevant context: https://github.com/sharkdp/bat/pull/1552

**Comment by Enselic** [comment]
Well, I think #1552 says it all. We tried but there was a problem 🙂
