### ISSUE TITLE
[BUG] `bat` is not in `PATH` after installing with `winget`

### ISSUE THREAD

**Issue by NikGovorov** [sharkdp/bat#2596]
**What steps will reproduce the bug?**

1. execute `winget install sharkdp.bat`
2. exit terminal
3. open terminal
4. run `bat`

**What happens?**

Actual result: `bat.exe` is not in PATH

**What did you expect to happen instead?**

Expected result: `bat.exe` is in PATH

`~/AppData/Local/Microsoft/WinGet/Packages/sharkdp.bat_Microsoft.Winget.Source_8wekyb3d8bbwe` is in PATH, but `bat.exe` is located in `~/AppData/Local/Microsoft/WinGet/Packages/sharkdp.bat_Microsoft.Winget.Source_8wekyb3d8bbwe/bat-v0.23.0-x86_64-pc-windows-msvc`

**How did you install `bat`?**

`winget install sharkdp.bat`

**bat version and environment**
bat-v0.23.0
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621

**Comment by sharkdp** [comment]
@sitiom Notifying you, just in case you are interested.

**Comment by sitiom** [comment]
- https://github.com/microsoft/winget-cli/issues/2909

This should already be resolved in the latest release candidate build on Winget. For Winget bugs, you should be looking at the https://github.com/microsoft/winget-cli repo first.
