### ISSUE TITLE
lib libgcc_s.so.1 missing

### ISSUE THREAD

**Issue by victorhernandezo** [sharkdp/bat#2599]
**What steps will reproduce the bug?**

1. step 1
2. step 2
3. ...

**What happens?**

...

**What did you expect to happen instead?**

...

**How did you install `bat`?**

---

**bat version and environment**

**Comment by keith-hall** [comment]
please answer how you installed `bat`, what version you installed and what OS you are using. Without that, there's not much we can do to help you.

**Comment by magiruuvelvet** [comment]
Just a guess. I use Rust for several years in an unsupported configuration. Rust defaults to `libgcc_s.so.1` for unwinding, but you can also use LLVM's `libunwind.so.1` for that. I'm on Gentoo and always make a symbolic link in `/opt/rust-bin-$RUST_VERSION/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgcc_s.so` pointing to LLVM `/usr/lib64/libunwind.so` and compile Rust binaries that way. I've never had an issue with this and the 2 libraries seem to be mostly ABI compatible, but that's my individual Rust configuration. I can't recommend doing this if you don't know what you are doing.

```
$ ldd (which bat)
File: /usr/bin/bat
Format: elf64-x86-64
Arch: x86_64
AddressSize: 64bit
OS/ABI: SystemV (0x0)
Needed Libraries:
  libc.so.6
  libm.so.6
  libonig.so.5
  libunwind.so.1
  libz.so.1
```

Without more info from the OP, it's impossible to say though what exactly is going on. Maybe the library `libgcc_s.so.1` is missing on the system?

**Comment by eth-p** [comment]
@victorhernandezo, do you still have this issue? If so, would you be able to provide us with more information about your system (e.g. distro, distro version) and how you installed `bat`?
