### ISSUE TITLE
Default behavior when output is sent to a file

### ISSUE THREAD

**Issue by anxiousmodernman** [sharkdp/bat#26]
I, for one, prefer the way `exa` handles this. To wit,
![battest](https://user-images.githubusercontent.com/396004/39454967-fb9fbc20-4c92-11e8-870d-dc53a14c27d3.png)

With exa, I've aliased `ls` and everything's been fine. I'd consider doing the same for bat if we could get non-colorized output and byte-for-byte copying when the output isn't a terminal ("catting to a file"). Perhaps via a config. If that's not your goal, that's fine too. :+1: 

Cool project, btw.

**Comment by sharkdp** [comment]
Yes, we should probably provide a `--color=auto/never/always` option and the `auto` option (which chooses a colorized output only if the terminal is interactive) would be enabled by default.

Concerning the line numbers and Git decorations, we should probably also provide something similar (`--style=auto/basic/full`).

**Comment by BrainMaestro** [comment]
@sharkdp I can add the color flag to behave the way you suggested
