### ISSUE TITLE
Incorrect colours on Windows

### ISSUE THREAD

**Issue by Aankhen** [sharkdp/bat#260]
(copied from my comment in #107)

I installed `bat` on a recent Windows 10 Pro x64 build today and tried it in Cmder, the Cmder installation of ConEmu, PowerShell, and the regular Command Prompt. The first two gave me this:

![White-on-grey text everywhere except the filename](https://user-images.githubusercontent.com/978992/44955053-8acb3480-aeca-11e8-8fbd-ab3bd744af1f.png)

PowerShell gave me this (presumably just different default terminal colours; please excuse the crude black censor bar):

![White-on-pink text everywhere except the filename](https://user-images.githubusercontent.com/978992/44955069-d1209380-aeca-11e8-9033-73f1c1aec1d8.png)

Command Prompt gave me this, like the first two:

![White-on-grey text everywhere except the filename](https://user-images.githubusercontent.com/978992/44955084-075e1300-aecb-11e8-9d58-18934c823718.png)

`bat` looks really exciting and I’m eager to use it, so I hope this is just a misconfiguration on my end! FWIW, I get the same results without a `BAT_THEME` and with a `BAT_THEME` of `Monokai Extended Bright`.

**Comment by sharkdp** [comment]
Thank you for the bug report!

This does *not* look like the same error as #252 because you actually get the styling (grid, line numbers, etc.) as well as *some* colors (although incorrect ones).

Something seems wrong with ANSI code handling on your terminals. Can you try to use `--color=never` to see if that produces a correct (colorless) output? Could you also try to switch off the pager (`--paging=never`) to make sure that nothing else is interfering?

**Comment by Aankhen** [comment]
Sure thing. Here’s `--color=never`:

![Correct uncoloured output](https://user-images.githubusercontent.com/978992/45012873-bc610e80-b036-11e8-8163-ca7f4368873b.png)

And here’s `--paging=never`:

![Correct coloured output without paging](https://user-images.githubusercontent.com/978992/45012902-dc90cd80-b036-11e8-930f-c16707533831.png)

Looks like that’s indeed where the issue is, so I did some digging…

The `less` being used was from Git Windows. I also have the one from [UnxUtils](http://unxutils.sourceforge.net/), so I temporarily removed the Git one. Now I get ‘invalid charset name’, because the UnxUtils version of `less` only supports a handful of encodings:

```c
struct charset {
	char *name;
	char *desc;
} charsets[] = {
	{ "ascii",	"8bcccbcc18b95.b"		},
	{ "dos",	"8bcccbcc12bc5b95.b."		},
	{ "ebcdic",	"5bc6bcc7bcc41b.9b7.9b5.b..8b6.10b6.b9.7b9.8b8.17b3.3b9.7b9.8b8.6b10.b.b.b." },
	{ "iso8859",	"8bcccbcc18b95.33b."		},
	{ "koi8-r",	"8bcccbcc18b95.b128."		},
	{ "latin1",	"8bcccbcc18b95.33b."		},
	{ "next",	"8bcccbcc18b95.bb125.bb"	},
	{ NULL, NULL }
};
```

I can get it work in general by unsetting `LESSCHARSET`, but [`bat` explicitly sets it](https://github.com/sharkdp/bat/blob/master/src/output.rs#L36).

**Comment by sharkdp** [comment]
Ok, thank you for the detailed analysis!

Maybe we should think about disabling automatic paging by default. Users could opt in by setting `BAT_PAGER=less` or maybe by setting `BAT_PAGING=auto`.

**Comment by Aankhen** [comment]
Maybe, although I really wish I could figure out a way to have my paging ~and eat it too~. Alternatively, paging could be opt-in only on Windows.

**Comment by sharkdp** [comment]
If you find a pager that can handle ANSI codes, you can just set the `BAT_PAGER` environment variable (see README).

> I can get it work in general by unsetting LESSCHARSET, but bat explicitly sets it:

You can use a separate script (as also suggested in the README) to set specific environment variables like `LESSCHARSET` and then call `less` from the script. `bat` will only set this environment variable if `$BAT_PAGER == less` or when no other pager is specified.

**Comment by Aankhen** [comment]
I tried it without `LESSCHARSET`; that’s when I discovered that the three `less` binaries I tried couldn’t handle the ANSI codes. I haven’t yet found a pager for Windows that can, unfortunately. I’l keep looking, though.

**Comment by nickcox** [comment]
Colours work for me after installing the version found on Chocolatey.

```sh
Get-Command less

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     less.exe                                           0.0.0.0    C:\Program Files\Git\usr\bin\less.exe

less --version
less 529 (PCRE regular expressions)
Copyright (C) 1984-2017  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less

bat .\readme.md
# no colours...
```
```sh
choco install less
Get-Command less

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     less.exe                                           0.8.1.0    C:\ProgramData\chocolatey\bin\less.exe

less --version
less 529 (Spencer V8 regular expressions)
Copyright (C) 1984-2017  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less

bat .\readme.md
# all the colours
```

**Comment by Aankhen** [comment]
Strange… using less 5.30 from the same source as Chocolatey in PowerShell, I see garbled codes instead of colours. I must have something misconfigured.

**Comment by sharkdp** [comment]
Make sure that you use the `-R` option of `less` (either by wrapping it in a script or by `export LESS="-R"`)

**Comment by nickcox** [comment]
FWIW, I didn't have to set any options or environment variables to get this to work. (I guess _bat_ does that for me automatically?) Just:

```sh
bat ./readme.me
```
![image](https://user-images.githubusercontent.com/135552/45142322-99cc2280-b1fb-11e8-8bd9-5c13d56858e8.png)

I do have `HKEY_CURRENT_USER\Console\VirtualTerminalLevel=1`. Not sure if that's important for `conhost.exe`?

**Comment by Aankhen** [comment]
Yup, I’ve got that set too. What version of Windows are you running? I’m on Windows 10 Pro x64.

**Comment by sharkdp** [comment]
`bat` should set the right flags (you need `-R`, not `-r`) if either

1. `PAGER` and `BAT_PAGER` are unset or
2. `BAT_PAGER` is unset and `PAGER == "less"`
3. `BAT_PAGER == "less"`

**Comment by sharkdp** [comment]
@Aankhen So with your PR merged, what's the full story with using `less` on Windows?

Is there something we should add to the README (Troubleshooting?) or will it work out of the box with your fix (and `less` installed)?

**Comment by Aankhen** [comment]
Git’s `less` (which I believe is MSYS’s `less`) won’t be able to handle colours—you’ll get the white-on-grey from my first screenshot—and I can’t find a way to make it work, so maybe the README should mention that. Other than that, it should indeed work out of the box!

**Comment by sharkdp** [comment]
Thanks! Let's add a "Using a pager on Windows" section (or similar) to the Troubleshooting section with both of your points.

**Comment by Aankhen** [comment]
Done, #295.

**Comment by Issam-seghir** [comment]
> Colours work for me after installing the version found on Chocolatey.
> 
> ```shell
> PS> Get-Command less
> 
> CommandType     Name                                               Version    Source
> -----------     ----                                               -------    ------
> Application     less.exe                                           0.0.0.0    C:\Program Files\Git\usr\bin\less.exe
> 
> PS> less --version
> less 529 (PCRE regular expressions)
> Copyright (C) 1984-2017  Mark Nudelman
> 
> less comes with NO WARRANTY, to the extent permitted by law.
> For information about the terms of redistribution,
> see the file named README in the less distribution.
> Homepage: http://www.greenwoodsoftware.com/less
> 
> PS> bat .\readme.md
> # no colours...
> ```
> 
> ```shell
> PS> choco install less
> PS> Get-Command less
> 
> CommandType     Name                                               Version    Source
> -----------     ----                                               -------    ------
> Application     less.exe                                           0.8.1.0    C:\ProgramData\chocolatey\bin\less.exe
> 
> PS> less --version
> less 529 (Spencer V8 regular expressions)
> Copyright (C) 1984-2017  Mark Nudelman
> 
> less comes with NO WARRANTY, to the extent permitted by law.
> For information about the terms of redistribution,
> see the file named README in the less distribution.
> Homepage: http://www.greenwoodsoftware.com/less
> 
> PS> bat .\readme.md
> # all the colours
> ```

this steps fix my problem
when i run :   `bat <file>` 

and the output is :    ` invalid charset name`
and install `less` with **choco** fix this 
the same problem mention here : #invalid
