### ISSUE TITLE
Use bat as default system pager

### ISSUE THREAD

**Issue by markfaine** [sharkdp/bat#2603]
How do I use bat as my system default pager?

If I set `export PAGER=/usr/bin/batcat` this freezes the entire terminal the first time it is used.

**Comment by aarondill** [comment]
seeing as you put `batcat` as the executable, you are likely on Ubuntu. This has been fixed in recent versions of bat. Try installing [v0.23.0](https://github.com/sharkdp/bat/releases/tag/v0.23.0) and see if it works! :smile:

**Comment by markfaine** [comment]
Yes Ubuntu. I will give that a try. Thanks!

**Comment by aarondill** [comment]
@markfaine did updating fix your issue?

**Comment by markfaine** [comment]
Yes, thanks!
