### ISSUE TITLE
bat cache --build reporting Invalid syntax theme settings in Windows

### ISSUE THREAD

**Issue by seanmamasde** [sharkdp/bat#2614]
**Environment**
- Windows 11 dev channel, build 23493
- `bat 0.23.0 (871abd2)` installed via `scoop install main/bat`

**Description**
Tried a few `.tmTheme` and `bat cache --build` all returned 
`Failed to load one or more themes from 'C:\Users\{user}\AppData\Roaming\bat\themes' (reason: 'Invalid syntax theme settings')`

**Steps To Reproduce**
1. `scoop install main/bat`
2. `mkdir -p "$(bat --config-dir)/themes"` (at `%AppData%\Roaming\bat\themes`)
3. `cd "$(bat --config-dir)/themes"`
4. `curl -O https://github.com/folke/tokyonight.nvim/blob/main/extras/sublime/tokyonight_night.tmTheme`
5. `bat cache -b` returned invalid syntax

Have also tried [this](https://github.com/greggb/sublime-snazzy) in the readme, but still got the same error.

**Comment by keith-hall** [comment]
> 4\. curl -O https://github.com/folke/tokyonight.nvim/blob/main/extras/sublime/tokyonight_night.tmTheme

if you look at the output, it's a html file - the webpage of github showing the contents of that file. I suggest downloading from a web browser or if you insist on using the CLI, use the `raw.githubusercontent` link: https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme
