### ISSUE TITLE
EPEL package

### ISSUE THREAD

**Issue by fawaf** [sharkdp/bat#2617]
Couldn't find anything with "epel" in issues, so wondering if we can get this added to epel?

**Comment by keith-hall** [comment]
EPEL as in https://docs.fedoraproject.org/en-US/epel/? So do I understand correctly that you want a package containing `bat` to be included in "Extra Packages for Enterprise Linux"?

**Comment by fawaf** [comment]
Yep, that is correct.

**Comment by fawaf** [comment]
Ahh, I can see if I can use epel 9
