### ISSUE TITLE
bat wrapping and tmux

### ISSUE THREAD

**Issue by hartmms** [sharkdp/bat#262]
I use tmux and noticed that when you resize the given pane that bat has already drawn, bat won't grow the displayed text to the new width.  To get past this, I just always use "bat --wrap none".

I wonder if it's possible for bat to intercept the same tmux signal that says "I changed the terminal character width" and re-display. It's a super low priority request if it's even possible. 

Thanks for this program.  I'm going to use it instead of cat from now on out!

**Comment by sharkdp** [comment]
There are two possibilities:

- If we do not call a pager (if the file fits on the screen or if `BAT_PAGER==""`), `bat` just runs once and there is no way to detect a change in the terminal width afterwards.

- If we call the pager, you are actually seeing the pager process, not `bat`. Terminal-resize events could potentially be detected by the pager, but I don't think they will offer a feature to call another process again.

**Comment by sharkdp** [comment]
I'm going to close this. If there is any further feedback, feel free to comment and I can re-open this ticket.
