### ISSUE TITLE
Support text with embedded ANSI codes for the higlight line

### ISSUE THREAD

**Issue by nkh** [sharkdp/bat#2621]
![screenshot_2023-07-14_11-27-32](https://github.com/sharkdp/bat/assets/45409/57913762-50dd-4f53-b107-c24f6a4b4a3b)

**Comment by eth-p** [comment]
Good catch!

I suspect what's happening here is that the "tmux" there is actually:

```
  ^[[33m tmux ^[[0m
  ~~~~~~~      ~~~~~
  yellow       reset
```

The reset (SGR RESET) clears all the style information, which happens to include the background set by the line highlight. It shouldn't be too hard to put the line highlighting styles back after we encounter a reset.

**Comment by nkh** [comment]
I'm adding the colors, and there can be many added on a single line. Here's how it looks like

![screenshot_2023-07-19_00-10-08](https://github.com/sharkdp/bat/assets/45409/287fd338-1da5-40b2-836a-3171c07c33c6)

![screenshot_2023-07-19_00-10-38](https://github.com/sharkdp/bat/assets/45409/ebd5c340-bb20-43a5-ad43-066d0b1db2ac)

**Comment by eth-p** [comment]
Hey @nkh, if it's not too much trouble, would you be able to provide me with a text file and theme to reproduce this issue?

I'm using your example above, and I can't seem to get it to break on the latest version of `bat` :

![image](https://github.com/sharkdp/bat/assets/32112321/55a980ce-a480-4720-93fa-4ef00f5895b4)

![image](https://github.com/sharkdp/bat/assets/32112321/84ad3c49-9c4a-4bb0-bdbf-3c652aabfda0)

**Comment by nkh** [comment]
@eth-p I'll check with the latest version and get back to you.

**Comment by nkh** [comment]
Seems to work in 0.24, thanks.
