### ISSUE TITLE
`cargo install bat` fails because `grep-cli` uses `is_terminal` std lib feature

### ISSUE THREAD

**Issue by omarandlorraine** [sharkdp/bat#2622]
**What steps will reproduce the bug?**

1. cargo install bat

**What happens?**

Fails to compile because a dependency, `grep-cli` v0.1.18, uses an unstable library feature, `is_terminal`.

...

**What did you expect to happen?**
Successful compilation and installation of bat.
...

**How did you install `bat`?**

cargo install

---

**bat version and environment**

Cargo is pulling in bat v0.23.0, and this is on Debian 11.7.

**Comment by keith-hall** [comment]
What version of Rust toolchain are you using? (i.e. `rustc --version`)

**Comment by keith-hall** [comment]
I'm also curious to know if `cargo install --locked bat` would have helped here so we could prove whether it is for sure a `bat` problem or not.

**Comment by omarandlorraine** [comment]
> I'm also curious to know if cargo install --locked bat would have helped here

I'm trying on another machine now where I've got this

```
$ rustc --version
rustc 1.66.0 (69f9c33d7 2022-12-12)
```
(it makes me wonder why I have not been updating rust on any of my machines!) and I'm running `cargo install --locked bat`. I got this warning:

```
warning: package `hermit-abi v0.3.1` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```

but `bat` does install okay.

**Comment by Enselic** [comment]
Thank you for reporting.

As you have discovered, latest version of bat dependencies has a higher MSRV requirement than bat itself. And indeed one must use `--locked` to prevent this problem, so to speak. Or using a later version of Rust.

There is nothing bat can do right now about this, so I'll go ahead and close.

**Comment by omarandlorraine** [comment]
Thanks for your attention and help!
