### ISSUE TITLE
Highlight rst syntax in cmake file

### ISSUE THREAD

**Issue by Freed-Wu** [sharkdp/bat#2624]
![screen-2023-07-18-13-46-25](https://github.com/sharkdp/bat/assets/32936898/41c2cb83-7fc4-4ee9-97d8-d63be85b3e94)

cmake can use

```
#[=======================================================================[.rst:
...
#]=======================================================================]
```

to display rst syntax in `...`. Why not highlight it in rst not in cmake comment?

**Comment by keith-hall** [comment]
As the CMake syntax comes from another repo, it would make sense to file the feature request there: https://github.com/zyxar/Sublime-CMakeLists/issues
Once they implement it, we can bump our submodule version reference.

**Comment by Freed-Wu** [comment]
Transport to <https://github.com/zyxar/Sublime-CMakeLists/issues/73>.
