### ISSUE TITLE
Update for serde-yaml 0.9

### ISSUE THREAD

**Issue by plugwash** [sharkdp/bat#2627]
Hi.

In debian we are currently working on updating the serde-yaml crate, while we do have a mechanism for packaging multiple versions of a crate it is something we try to avoid where possible. So I have been testing reverse-dependencies of serde-yaml with the dependency bumped.

After bumping the dependency, bat itself built fine and it's tests passed. However one of the examples needed a small patch to avoid using a removed function.

https://salsa.debian.org/rust-team/debcargo-conf/-/blob/3a24d2e9344d0a204bab9af9bc9cadfb375f81fc/src/bat/debian/patches/serde-yaml-0.9.diff

**Comment by sharkdp** [comment]
`master` now uses serde 1.0, so I guess this can be closed.

**Comment by plugwash** [comment]
Sorry, I've realised I made a typo, it's serde_yaml not serde-yaml.

**Comment by Raghav-Bell** [comment]
Please assign this issue to me.
