### ISSUE TITLE
bat pager keep text on screen on exit

### ISSUE THREAD

**Issue by ryanmusante** [sharkdp/bat#2658]
I can't find through search where I previously did, I apologize for creating the ticket.

How do you keep the contents on-screen after quit/exit from the bat pager?

**Comment by keith-hall** [comment]
You are using `less` as your pager? Maybe with `-X` aka `-no-init`. i.e. 

```sh
export BAT_PAGER="less -RFX"
```

**Comment by ryanmusante** [comment]
Excellent, yes that is it!

However, in the case that I would use:
```
--paging=never
```
How do I setup to pipe out to less & more to do the same thing?
```
export BAT_PAGER='less -RFX'
export BATPIPE='color'
export HISTFILE='~/.zhistory'
export MANPAGER='less -R --use-color -Dd+r -Du+b'
export MANROFFOPT='-P -c'
```

**Comment by einfachIrgendwer0815** [comment]
In case that you would use `--paging=never`, you could do:
```bash
bat --paging=never <FILE> | less -RFX
```

However, the piping would cause bat to disable colors and decorations. Also bat wouldn't respect the terminal width anymore. So, to get the exact same result, you would have to do something like:
```bash
bat --paging=never --color=always --decorations=always --terminal-width=80 <FILE> | less -RFX
```

**Comment by ryanmusante** [comment]
Sweet, what is the recommended method to enact this through .zshrc or profile?

**Comment by ryanmusante** [comment]
I'm using a combination of bat's config and zshrc in meantime. Curious what others use however
