### ISSUE TITLE
bat doesn't work on macOS Sonoma :(

### ISSUE THREAD

**Issue by mrk088** [sharkdp/bat#2669]
**What steps will reproduce the bug?**

1. step 1
2. step 2
3. ...

**What happens?**

...

**What did you expect to happen instead?**

...

**How did you install `bat`?**

---

**bat version and environment**

**Comment by elchead** [comment]
what does not work? It works without issues for me

**Comment by sharkdp** [comment]
Clsoing for now, unless there are any further details.
