### ISSUE TITLE
Arithmetic overflow occurs while using API LineRange::from()

### ISSUE THREAD

**Issue by HeeillWang** [sharkdp/bat#2674]
**What steps will reproduce the bug?**
I executed fuzz testing with `bat` public APIs and found crash case.

~~~
let fuzz_arg1 = "18446744073709551615:+1";
LineRange::from(fuzz_arg1);
~~~

**What happens?**

~~~
Thread '<unnamed>' panicked at 'attempt to add with overflow', /rustc/871b5952023139738f72eba235063575062bc2e9/library/core/src/ops/arith.rs:109
~~~

The overflow occurs with this statement : 

https://github.com/sharkdp/bat/blob/5a240f36b9251fd6513316333acb969a4d347b9d/src/line_range.rs#L56

**What did you expect to happen instead?**
Need assertion to prevent arith overflow, or need to explicitly mention panic condition.

**Comment by sohang3112** [comment]
Maybe `saturating_add(new_range.lower, more_lines)` can be done here to avoid panicking.

**Comment by HeeillWang** [comment]
> Maybe `saturating_add(new_range.lower, more_lines)` can be done here to avoid panicking.

Looks nice, better than `assert!`.
