### ISSUE TITLE
bat outputting color codes and decorations when piping its output to file 

### ISSUE THREAD

**Issue by AyushRawal** [sharkdp/bat#2676]
**What steps will reproduce the bug?**

1. bat some-file > new-file

**What happens?**

bat outputs color codes and decorations to file

![image](https://github.com/sharkdp/bat/assets/32910415/bf6dc384-02ff-4407-ae4d-0254a34f8f29)

**What did you expect to happen instead?**

the output should contain only the contents of the file

**How did you install `bat`?**

sudo pacman -S bat

**bat version and environment**
#### Software version

bat 0.23.0 (871abd27)

#### Operating system

Linux 6.5.5-arch1-1

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/usr/bin/zsh
PAGER=<not set>
LESS=-R
LANG=en_US.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=/home/rawal/.config
XDG_CACHE_HOME=/home/rawal/.cache
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='sh -c '\''col -bx | bat -l man -p'\'''
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

```
--theme="gruvbox-dark"
--pager="less -R"
--color=always
```

#### Custom assets metadata

Could not read contents of '/home/rawal/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/home/rawal/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version
less 643 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Comment by keith-hall** [comment]
This is expected because you have this line in your config file:
>
```
--color=always
```

**Comment by AyushRawal** [comment]
Ok, I am dumb. Sorry for the trouble.
