### ISSUE TITLE
Line numbers not piped through

### ISSUE THREAD

**Issue by EricIO** [sharkdp/bat#269]
When piping bat output with the `-n` option the line numbers disappear.

```bash
bat -n programming/work/stordatorn/pipelines/transformations/Burt/ViewTransformation/src/main/scala/news/bonnier/stordatorn/pipelines/viewtransformation/ViewTransformer.scala | grep lazy
  lazy val datetime: ZonedDateTime = ZonedDateTime.ofInstant(Instant.ofEpochMilli(view.timestamp), ZoneId.of("UTC"))
  lazy val localDatetime: ZonedDateTime = datetime.withZoneSameInstant(ZoneId.of("Europe/Stockholm"))
  lazy val userloggedin: Option[Boolean] = view.annotations.userloggedin
``` 

Here is the same with cat on Mac OS X
```bash
cat -n programming/work/stordatorn/pipelines/transformations/Burt/ViewTransformation/src/main/scala/news/bonnier/stordatorn/pipelines/viewtransformation/ViewTransformer.scala | grep lazy
    13	  lazy val datetime: ZonedDateTime = ZonedDateTime.ofInstant(Instant.ofEpochMilli(view.timestamp), ZoneId.of("UTC"))
    14	  lazy val localDatetime: ZonedDateTime = datetime.withZoneSameInstant(ZoneId.of("Europe/Stockholm"))
    16	  lazy val userloggedin: Option[Boolean] = view.annotations.userloggedin
```

**Comment by sharkdp** [comment]
This is intentional. `bat` disables all "decorations" when the output is piped to another program or a file. You can use `--decorations=always` to force it to write the decorations to the pipe.

**Comment by EricIO** [comment]
Oh great, I was looking for a switch that would do this but didn't understand what the `--decorations` flag would do.

`brew install bat` didn't install a man page (if there is one) so not sure it is documented but might be a good candidate for adding to documentation (a use case I see myself using bat for is doing something like `bat <somefile> --decorations=always | grep <somestring>` to see where my matches are in pretty colour.

Thanks for the great program!

**Comment by sharkdp** [comment]
There is a man page, but it basically includes the same content as `bat --help` (which already includes the `--decorations` option).

> a use case I see myself using bat for is doing something like bat <somefile> --decorations=always | grep <somestring> to see where my matches are in pretty colour.

:+1: 

You probably also have to use `--color=always`. Also, make sure that the ANSI-color definitions do not screw up your `grep`ping.
