### ISSUE TITLE
Cut new release tag to update dependencies

### ISSUE THREAD

**Issue by carlocab** [sharkdp/bat#2694]
The latest version of `bat` ([v0.23.0](https://github.com/sharkdp/bat/releases/tag/v0.23.0) at the time of writing) [depends on `libgit2` v1.5](https://github.com/sharkdp/bat/blob/871abd27aa91264e01539da849add0330b24cb9c/Cargo.lock#L645), which is a version that is [no longer supported upstream](https://github.com/libgit2/libgit2/blob/4939fa740aba2d7f2392b88e67e563eadd32e58c/SECURITY.md#supported-versions).

The master branch [supports `libgit2` v1.7](https://github.com/sharkdp/bat/blob/69c326fd41bbe395b8892ea440df9a6f138b5be1/Cargo.lock#L649), so cutting a new release tag that includes f34b852aa80a36294df4b117cf8e945f8c914d0a should suffice to fix this.

**Comment by keith-hall** [comment]
https://github.com/sharkdp/bat/releases/tag/v0.24.0 was released last week :)

**Comment by carlocab** [comment]
Thanks!
