### ISSUE TITLE
Changing lines color and line number color

### ISSUE THREAD

**Issue by gjuchault** [sharkdp/bat#270]
Hello,

I'm using Dracula theme for Alfred. It's common, dark/violet background based, and using bat, with any theme, here is what I get:

![image](https://user-images.githubusercontent.com/678848/45019010-88ccb700-b02b-11e8-91b7-e08072e1a1b2.png)

I tried creating a custom theme file, but never found which colors were used for gutters and line numbers.

**Comment by sharkdp** [comment]
Thank you for the feedback.

Please see #219

**Comment by gjuchault** [comment]
@sharkdp Sorry it has been two times I did not see the actual issues with same concerns I had 🐐
