### ISSUE TITLE
Multi line links get cut off when redirecting to them. 

### ISSUE THREAD

**Issue by MarkoMuc** [sharkdp/bat#2702]
**What steps will reproduce the bug?**

1. Open a file with link(s)
2. Terminal windows should be small enough for the link to be split into 2 (or more) lines (meaning the whole link doesn't fit into one line)
3. Press the link (CTRL + mouse click)

**What happens?**
Only the part of the link that is on the first line is actually highlighted and you get redirected there. Meaning the link gets cut off.

**What did you expect to happen instead?**
To be redirected to the whole link and not only the first part. Also for the whole link to be highlighted.

**How did you install `bat`?**

Installed it with cargo.

**bat version and environment**

#### Software version

bat 0.23.0

#### Operating system
Linux 6.5.5-200.fc38.x86_64
(KDE FEDORA 38)
#### Command-line

```bash
bat OUI-LINKI.txt --diagnostics 
```

#### Environment variables

```bash
SHELL=/bin/bash
PAGER=<not set>
LESS=<not set>
LANG=en_US.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

Could not read contents of '/home/MZM/.config/bat/config': No such file or directory (os error 2).

#### Custom assets metadata

Could not read contents of '/home/MZM/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/home/MZM/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 633 (POSIX regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

**Additional Information**

If you resize the window, from large enough for the whole link to be on one line, to a smaller window, where it doesn't fit into one line, there is no issue and it works correctly.

**Comment by MarkoMuc** [comment]
Actually, this might not be a bat issue. It probably stems from the way Bat formats the message and adds tabs/whitespace at the start of each line, as well as how terminal emulators handle links. I tested it again, and when resizing the window even less, it turns back into one long line and it starts working correctly.

**Comment by keith-hall** [comment]
This looks similar to an issue reported previously: https://github.com/sharkdp/bat/issues/2579

We have an open PR which could fix it: https://github.com/sharkdp/bat/pull/2544
