### ISSUE TITLE
[bat warning]: Unknown theme '...', using default. when using pager

### ISSUE THREAD

**Issue by k1gen** [sharkdp/bat#2707]
**What steps will reproduce the bug?**
 
1. add
```
export LESS='-R --use-color -Dd+r$Du+b$'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
```
to your .zshrc
2. bat something, .zshrc itself for example
3. press 'q' to quit the pager

**What happens?**

I get `[bat warning]: Unknown theme 'Catppuccin-mocha', using default.` my ~/.config/bat/config contains only `--theme="Catppuccin-mocha"`, and the theme seems to be applied successfully.

**What did you expect to happen instead?**

no output

**How did you install `bat`?**

with pacman

---

**bat version and environment**

`$ bat .zshrc --diagnostic`
#### Software version

bat 0.23.0 (871abd27)

#### Operating system

Linux 6.5.6-hardened1-1-hardened

#### Command-line

```bash
bat .zshrc --diagnostic 
```

#### Environment variables

```bash
SHELL=/usr/bin/zsh
PAGER=<not set>
LESS='-R --use-color -Dd+r$Du+b$'
LANG=en_EU.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER='sh -c '\''col -bx | bat -l man -p'\'''
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

```
--theme="Catppuccin-mocha"
```

#### Custom assets metadata

Could not read contents of '/home/olk/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/home/olk/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Less version

```
> less --version 
less 643 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman
...
```

**Comment by k1gen** [comment]
this still happens with bat 0.24.0

**Comment by keith-hall** [comment]
I don't see any evidence that `bat` ships with a theme called `Catppuccin-mocha`... 
If I add that line to my config, I get the same warning, but the highlighting is the same with and without it... Can you share a screenshot?
Perhaps you need to add it as a custom asset? https://github.com/sharkdp/bat/pull/2124

**Comment by k1gen** [comment]
I have just deleted whole ~/.config/bat dir and nothing changed, but the warning is gone, weird
