### ISSUE TITLE
Always displays escape characters

### ISSUE THREAD

**Issue by db0** [sharkdp/bat#271]
Whenever I'm trying to bat a file, I always get an output like this
`ESC[38;5;238m───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────ESC[0m
       ESC[38;5;238m│ ESC[0mFile: ESC[1mREADME.mdESC[0m
ESC[38;5;238m───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────ESC[0m
ESC[38;5;238m   1ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;253;151;31m#ESC[0mESC[38;2;253;151;31m ESC[0mESC[38;2;253;151;31mparallel-sshESC[0m
ESC[38;5;238m   2ESC[0m   ESC[38;5;238m│ESC[0m 
ESC[38;5;238m   3ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;255;255;255mThis is an attempt to reboot pssh. ESC[0m
ESC[38;5;238m   4ESC[0m   ESC[38;5;238m│ESC[0m 
ESC[38;5;238m   5ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;253;151;31m##ESC[0mESC[38;2;253;151;31m ESC[0mESC[38;2;253;151;31mGoalsESC[0m
ESC[38;5;238m   6ESC[0m   ESC[38;5;238m│ESC[0m 
ESC[38;5;238m   7ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;119;119;119m*ESC[0mESC[38;2;255;255;255m ESC[0mESC[38;2;255;255;255mCleaner code, where possibleESC[0m
ESC[38;5;238m   8ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;119;119;119m*ESC[0mESC[38;2;255;255;255m Incorporate many of the patches and fix many of the issues found atESC[0m
ESC[38;5;238m   9ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;255;255;255m  ESC[0mESC[4;38;2;166;226;46mhttps://github.comESC[0mESC[4;38;2;166;226;46m/lilydjwg/pssh/issuesESC[0m
ESC[38;5;238m  10ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;119;119;119m*ESC[0mESC[38;2;255;255;255m Add a few features (-L/--list-hosts, for one)ESC[0m
ESC[38;5;238m  11ESC[0m   ESC[38;5;238m│ESC[0m 
ESC[38;5;238m  12ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;253;151;31m##ESC[0mESC[38;2;253;151;31m ESC[0mESC[38;2;253;151;31mOriginal README.mdESC[0m
ESC[38;5;238m  13ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;255;255;255mPSSH provides parallel versions of OpenSSH and related tools, including pssh, pscp, prsync, pnuke and pslurp. This project includes psshlib which can be used within custom applications. The source code ESC[0m
ESC[38;5;238m    ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;255;255;255mis written in PythonESC[0m
ESC[38;5;238m  14ESC[0m   ESC[38;5;238m│ESC[0m 
ESC[38;5;238m  15ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;255;255;255mPSSH is supported on Python 2.5 and later (including Python 3.1 and later). It was originally written and maintained by Brent N. Chun. Due to his busy schedule, Brent handed over maintenance to Andrew MESC[0m
ESC[38;5;238m    ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;255;255;255mcNabb in October 2009.ESC[0m
ESC[38;5;238m  16ESC[0m   ESC[38;5;238m│ESC[0m 
ESC[38;5;238m  17ESC[0m   ESC[38;5;238m│ESC[0m ESC[38;2;255;255;255mThis project originally located at ESC[0mESC[38;2;255;255;255m[ESC[0mESC[38;2;255;255;255mGoogle CodeESC[0mESC[38;2;255;255;255m]ESC[0mESC[38;2;255;255;255m(ESC[0mESC[4;38;2;166;226;46mhttps://code.google.com/p/parallel-ssh/ESC[0mESC[38;2;255;255;255m)ESC[0mESC[38;2;255;255;255m. Since Google Code has been closed, and has not appeared elsewhere, I (lilydjwg) have exported it to GitHub.ESC[0m
ESC[38;5;238m───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────ESC[0m
`

I searched around and found #98 which seems relevant, and it did lead me to thinking the culprit is less, so using --paging=never which seems to work. It seems that without it, bat always default to using less, even if the output is less than one screen, and for some reason that paging fails to display escape characters correctly. 

However if I simply pipe the bat --paging=never output to less, then it displays fine paged, so I'm not sure what is causing this.

I'm using it on Fedora 27, using Gnome Terminal and bat 0.6.1 compiled with cargo.

**Comment by sharkdp** [comment]
Thank you for reporting this.

What is the content of the `PAGER` and `BAT_PAGER` environment variables?

**Comment by db0** [comment]
PAGER=/usr/bin/less
BAT_PAGER is empty

**Comment by sharkdp** [comment]
Can you please try to set `PAGER` (or `BAT_PAGER`) to `less` (instead of `/usr/bin/less`)?

**Comment by db0** [comment]
Wow that did the trick! How can the full path be causing this?

**Comment by sharkdp** [comment]
Thank you for checking.

This is partly `bat`'s fault. We currently explicitly check for `PAGER == "less"` here:

https://github.com/sharkdp/bat/blob/9316f2a758d015ced23af421e1257f5b926f25c4/src/output.rs#L29-L37

If we detect `less` as a pager, we add a command-line option which is necessary to interpret the ANSI-color-sequences (`--RAW-CONTROL-CHARS`). We should make that check more robust, such that we also add these options if `PAGER == "/usr/bin/less"` or similar.

**Comment by sharkdp** [comment]
Fix released in [v0.7.0](https://github.com/sharkdp/bat/releases/tag/v0.7.0).

**Comment by WiSaGaN** [comment]
The fix is not able to detect something like `/usr/bin/less -X`. Is it accidental?

**Comment by sharkdp** [comment]
> The fix is not able to detect something like `/usr/bin/less -X`. Is it accidental?

No. If you want decide to pass your own arguments to `less` (here: `-X`), `bat` will *not* pass any additional arguments to less. You will have to pass `-R` yourself.

**Comment by TomLavenziano** [comment]
Currently running v0.9.0 and still had the same problem.

I have `PAGER=most`
Setting `BAT_PAGER=less` did the trick to fix it.

**Comment by sharkdp** [comment]
@TomLavenziano I think a recent change in `bat` made things worse here. Please see #430
