### ISSUE TITLE
Webroot Flags as Passwordfinder on Win10

### ISSUE THREAD

**Issue by mrxinu** [sharkdp/bat#272]
I got an email from our local IT saying that the bat.exe binary is being flagged as a W32.Passwordfinder. If I can do any testing/validation, let me know.

Threat List:
BAT.EXE, W32.Passwordfinder, ?:\dropbox\apps\,   https://snup.webrootcloudav.com/SkyStoreFileUploader/upload.aspx?MD5=0DA1B19B50AE3A7CF109034228397513 0DA1B19B50AE3A7CF109034228397513,

**Comment by sharkdp** [comment]
That is ... interesting. Either this is a Virus scanner false-positive or your `bat.exe` has been compromised*. Can you please make sure that the file that has been scanned is identical (`md5sum`-wise) to the files on our [Releases page](https://github.com/sharkdp/bat/releases)?

\* There is of course a third option where I am trying to take over the Windows world by injecting malicious code into the `bat` binary :smiling_imp: :smile:.

**Comment by mrxinu** [comment]
I'm going to chalk this one up to webroot losing its mind then. Thanks for checking!

![bitmoji](https://render.bitstrips.com/v2/cpanel/c0871c38-0c27-4ae4-9196-389fa986867a-5a2192cb-6188-4e5c-a482-ea7978b8a7e5-v1.png?transparent=1&palette=1&width=246)
