### ISSUE TITLE
Feature request: support input from git diff

### ISSUE THREAD

**Issue by morsdyce** [sharkdp/bat#274]
When viewing a file via `bat filename` we can see the file with the git diff perfectly as it shows in the readme example.

however if we try to use bat as our git diff tool (via setting pager property to bat in .gitconfig)
it doesn't understand how to separate the files and show the correct diff with the correct syntax highlight.

![image](https://user-images.githubusercontent.com/1665570/45045495-d83ad380-b07b-11e8-9c68-b4e66aa60554.png)

It would be awesome if we could support git syntax so we can highlight these correctly.

similar to how https://github.com/so-fancy/diff-so-fancy works

**Comment by sharkdp** [comment]
Thank you for the feedback.

`git diff` will add colors on its own. This is why you see some colors in the screenshot above. You can also use
```
git diff | bat -ldiff
```
which will show you the diff, highlighted by `bat`.

However, I think what you really want is something like #23 (see my proposal in [this comment](https://github.com/sharkdp/bat/issues/23#issuecomment-388971525)). This would allow us to show every modified hunk in a Git repository with syntax-highlighted code.

**Comment by coolaj86** [comment]
For posterity:

Here's how you set it to work with `git diff` and replace the general pager.

```sh
git config --global core.pager "bat --paging never --pager none --theme Dracula --style=plain"
git config --global pager.diff "bat --paging never --pager none --theme Dracula --style=plain --language diff"
```

Season to taste, of course.
