### ISSUE TITLE
Install via Ansible

### ISSUE THREAD

**Issue by aeimer** [sharkdp/bat#277]
Hey @sharkdp ,

I've written an ansible role to install bat automatically.
Do you want to add it to your readme?

I will try to fix all issues asap, if there are any: https://galaxy.ansible.com/aeimer/ansible-install-bat

Best regards.

**Comment by sharkdp** [comment]
Thank you very much.

I would first like to understand what that means, exactly :smile: I'm not really familiar with Ansible. Why/Where would anyone choose to install `bat` via Ansible?

**Comment by aeimer** [comment]
So Ansible is a tool to ensure a system has a defined state. This way you can eg. setup an apache, php and mysql with some defined routines. To install bat on a system I wrote a set of rules how to ensure that bat is installed on that system.

In my company we setup our server with ansible and plan to even deploy with ansible. On setup (php, apache, mysql, ...) it would be great to have bat installed, this is what my ansible role is for. So maybe some else want to have bat installed on different systems just really easy. If you link it as a possible way to install bat, it may help to spread bat.

Best regards

**Comment by sharkdp** [comment]
Ok, thank you for the explanation. Adding instructions to the README sounds good!

**Comment by aeimer** [comment]
So to use the role following steps are needed:
```bash
ansible-galaxy install aeimer.install_bat
```
Then you can use it with:
```yaml
- host: localhost
  roles:
    - aeimer.install_bat
```

**Comment by sharkdp** [comment]
@aeimer Thank you very much! I'm going to close this ticket, but feel free to open a PR if you think this would be a valuable addition to the README.
