### ISSUE TITLE
Bat failed to work in Powershell or CMD properly

### ISSUE THREAD

**Issue by szw0407** [sharkdp/bat#2796]
**What steps will reproduce the bug?**

1. Running `bat` command on Windows, using powershell 7 or cmd.exe

**What happens?**

Nothing happens in fact

![image](https://github.com/sharkdp/bat/assets/107471539/ec674735-c609-43c0-892d-55527abd4dfc)

Only by using Git Bash could `bat` run properly. 

**What did you expect to happen instead?**

Bat should have worked properly

**How did you install `bat`?**

`scoop install bat`

Using Winget or chocolatey will cause the similar issue.

**bat version and environment**

#### Software version

bat 0.24.0 (fc95468)

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
C:\Users\*****\scoop\apps\bat\current\bat.exe .\a.html --diagnostic
```

> All usernames are okay, and I hid them manually.

#### Environment variables

```bash
SHELL=<not set>
PAGER=<not set>
LESS=<not set>
LANG=<not set>
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_PAGING=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of 'C:\ProgramData\bat\config': 系统找不到指定的路径。 (os error 3).

> This means that the system cannot find such path

#### Config file

Could not read contents of 'C:\Users\*******\AppData\Roaming\bat\config': 系统找不到指定的路径。 (os error 3).

#### Custom assets metadata

Could not read contents of 'C:\Users\********\AppData\Local\bat\metadata.yaml': 系统找不到指定的路径。 (os error 3).

#### Custom assets

'C:\Users\*******\AppData\Local\bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```
> C:\ProgramData\scoop\shims\less.exe --version
BusyBox v1.37.0-FRP-5181-g5c1a3b00e (2023-08-18 12:16:29 BST)

Usage: less [-EFIMmNSRh~] [FILE]...

View FILE (or stdin) one screenful at a time

        -E      Quit once the end of a file is reached
        -F      Quit if entire file fits on first screen
        -I      Ignore case in all searches
        -M,-m   Display status line with line numbers
                and percentage through the file
        -N      Prefix line number to each line
        -S      Truncate long lines
        -R      Remove color escape codes in input
        -~      Suppress ~s displayed past EOF
C:\ProgramData\scoop\apps\busybox\current\busybox.exe: unknown option -- version
```
Command failed with exit code 1.

**Comment by keith-hall** [comment]
from the output of your `which bat` performed in PowerShell, that would indicate that it *can* find it the executable without you needing to specify the `.exe` extension. I wonder whether the problem is somehow related to the pager. Does it work in PowerShell with `bat a.html --paging=never`?

**Comment by szw0407** [comment]
Yes, that works!

So is it an issue with `less.exe` on my device, which in fact comes from BusyBox for windows? When I use the `less` 643, everything is just normal.

**Comment by szw0407** [comment]
If there is nothing wrong, may the issue just be closed? I have confirmed that it is an issue with Busybox-w32 or the `less.exe` going with it, but not an issue with Bat.

**Comment by keith-hall** [comment]
Nice, happy to hear you got it sorted 👍
Yes, it can just be closed. Or we can see if it makes sense to mention it somewhere in the documentation in case it will help others with the same problem in future 🙂
