### ISSUE TITLE
Provide armhf Debian packages

### ISSUE THREAD

**Issue by itskenny0** [sharkdp/bat#280]
Hi there,

would it be possible to provide armhf .deb packages?
I'd like to deploy bat over my entire infrastructure, but this requires any package I deploy to be available for all platforms (i386, amd64, armhf).

Thanks a lot for this project!

Best,
kenny

**Comment by sharkdp** [comment]
If this is about a 64bit arm build, please see #258

**Comment by itskenny0** [comment]
Hey there,

thanks for the response!

No, it’s mainly about the .deb packaging format. We use Ubuntu everywhere and if I were to add a package to our internal apt repository I need to add it for all of i386, amd64 and armhf since these architectures are in parallel use and our configuration deployment will install all the same packages on all architectures.

I’ve patched the existing .deb package by replacing the binary for now, but it would be awesome if a prebuilt package were available.

Thanks a lot for your effort!

Best,
kenny

**Comment by sharkdp** [comment]
I see, I'll reopen the ticket then.

**Comment by sharkdp** [comment]
The new [v0.7.0](https://github.com/sharkdp/bat/releases/tag/v0.7.0) release contains armhf Debian package. @itskenny0 Could you please test this?

**Comment by itskenny0** [comment]
@sharkdp Seems great, thank you!

Ubuntu 18.04:
armhf: https://asciinema.org/a/mgQN7VnSLZvC0EnfMgX5A7sFl
arm64: https://asciinema.org/a/M8zv4xRZyGgo5zi61JNPG1SX7
