### ISSUE TITLE
The system cannot find the path specified. (os error 3) - When attempting to bat a file with Tilde in the path

### ISSUE THREAD

**Issue by Joe-Zer0** [sharkdp/bat#2804]
**What steps will reproduce the bug?**
Bat any file with a tilde in the path.
```
⟫ bat ~\.gitconfig
[bat error]: '~\.gitconfig': The system cannot find the path specified. (os error 3)
```
Other information - bat works as expected in all other scenarios, including if the full path to the same file given (`C:\Users\joe\.gitignore`).  I think it used to work with the tilde, but I'm unable to verify.

**What happens?**
I get the error `[bat error]: '~\.gitconfig': The system cannot find the path specified. (os error 3)`

**What did you expect to happen instead?**
I expected the contents of the file to be output to the terminal.

**How did you install `bat`?**
I installed bat with chocolatey.

---

**bat version and environment**
```
⟫ bat --version
bat 0.24.0 (fc95468)
```
Windows Terminal - 1.18.3181.0
PowerShell - 7.4.0
Windows - 10.0.19045

#### Software version

bat 0.24.0 (fc95468)

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
C:\ProgramData\chocolatey\lib\Bat\tools\bat-v0.24.0-x86_64-pc-windows-msvc\bat.exe ~\.gitconfig --diagnostic
```

#### Environment variables

```bash
SHELL=<not set>
PAGER=<not set>
LESS=<not set>
LANG=<not set>
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_PAGING=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of 'C:\ProgramData\bat\config': The system cannot find the path specified. (os error 3).

#### Config file

Could not read contents of 'C:\Users\joe\AppData\Roaming\bat\config': The system cannot find the path specified. (os error 3).

#### Custom assets metadata

Could not read contents of 'C:\Users\joe\AppData\Local\bat\metadata.yaml': The system cannot find the path specified. (os error 3).

#### Custom assets

'C:\Users\joe\AppData\Local\bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```
> C:\ProgramData\chocolatey\bin\less.exe --version
less 643 (Spencer V8 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

Thank you!

**Comment by keith-hall** [comment]
perhaps PowerShell has differing behavior for commandlets vs other applications wrt resolving the tilde? apparently it can be controlled with a setting... https://github.com/orgs/PowerShell/discussions/15263#discussioncomment-625042

**Comment by Joe-Zer0** [comment]
Thank you for your help pointing me in the right direction. I'm going to close this ticket since this is not a bat issue. I'm noticing the came behavior with Helix as well. It looks to be an issue with the latest version of PowerShell.
https://github.com/PowerShell/PowerShell/issues/20750

**Comment by Joe-Zer0** [comment]
Closing
