### ISSUE TITLE
bat says some txt files are BINARY, and not display the content.

### ISSUE THREAD

**Issue by fanyx-ok** [sharkdp/bat#2813]
**What steps will reproduce the bug?**

1. read a txt file using bat:
`bat 05-55-47-ttyUSB2.txt`

**What happens?**
output is only a title without content:
`File: 05-55-47-ttyUSB2.txt   <BINARY>`

I have to tell you this problem does not happen to all txt files. But some specific txt files and I don't know why.
While all txt files are created and modified using python's open("a"), some files bat only display title with a BINARY tag, some files bat display both title (without the BINARY tag) and content.

**What did you expect to happen instead?**
display the content of this txt file, the top some lines are:
```
[05:55:47.791] 
[05:55:54.025] CHIP_SUBSYS=bth
[05:55:54.026] KERNEL=RTX5
[05:55:54.028] CRASH_DUMP_SIZE=0x4000
[05:55:54.029] AUD_SEC_SIZE=0
[05:55:54.031] USER_SEC_SIZE=0x1000
[05:55:54.033] FACT_SEC_SIZE=0x1000
[05:55:54.034] NV_REC_DEV_VER=2
···
```

**How did you install `bat`?**

GitHub release

---

**bat version and environment**

```
bat 0.23.0 (871abd2)

bat: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=213e2ab1274f49417b8fd102488b25683a8b3482, stripped
```

**Comment by einfachIrgendwer0815** [comment]
Does the file contain any null bytes in the first 1024 bytes?

**Comment by fanyx-ok** [comment]
> Does the file contain any null bytes in the first 1024 bytes?

I use `xxd` print the file. Does the last byte in the first line `00` means a null byte?
```
00000000: 5b31 303a 3130 3a30 302e 3132 305d 2000       [10:10:00.120] .
00000010: 0a5b 3130 3a31 303a 3030 2e31 3939 5d20        .[10:10:00.199]
```

**Comment by einfachIrgendwer0815** [comment]
> I use `xxd` print the file. Does the last byte in the first line `00` means a null byte?

Yes, it does. 

Bat considers files that have a null byte in their first 1024 bytes to be a binary file. However, you can use the following as a workaround:
```bash
bat --show-all <FILE>
```

**Comment by fanyx-ok** [comment]
@einfachIrgendwer0815 It works. Thank you!
You can close this issue. My problem was solved.
