### ISSUE TITLE
Avoid line numbers on select

### ISSUE THREAD

**Issue by dougg0k** [sharkdp/bat#2859]
Hi,

Would it be possible to enable a flag or even implement something to make the line numbers or lines around not selectable (only the content) while having them enabled? obviously.

**Comment by eth-p** [comment]
Text selection (and copying) is handled by the terminal emulator. Unfortunately, I'm not aware of any ANSI escape sequences that tell the terminal to make certain regions of text unselectable.

<details>
<summary>
If you use <code>tmux</code>, you could use its <a href="https://superuser.com/questions/395158/tmux-copy-mode-select-text-block">rectangle selection mode</a> to achieve this:
</summary><div>
<img width="789" alt="image" src="https://github.com/sharkdp/bat/assets/32112321/db300626-7c7a-475c-8cf7-3778552faad2">

After pressing the copy keybind, this is what was in my clipboard:

```rs
use std::fmt;
use std::io;
use std::vec::Vec;

use nu_ansi_term::Color::{Fixed, Green, Red, Yellow};
use nu_ansi_term::Style;

use bytesize::ByteSize;

use syntect::easy::HighlightLines;
use syntect::highlighting::Color;
use syntect::highlighting::Theme;
use syntect::parsing::SyntaxSet;

use content_inspector::ContentType;

use encoding_rs::{UTF_16BE, UTF_16LE};

use unicode_width::UnicodeWidthChar;

use crate::assets::{HighlightingAssets, SyntaxReferenceInSet};
use crate::config::Config;
#[cfg(feature = "git")]
```

</div>
</details>

**Comment by dougg0k** [comment]
I currently use alacritty, zellij and nushell

**Comment by dougg0k** [comment]
It seems that there were an implementation, but doesnt seem to work. Unless something else could be interfering.

https://github.com/alacritty/alacritty/issues/526
