### ISSUE TITLE
Support for Podman unit files (Quadlet)

### ISSUE THREAD

**Issue by pvdspoel22** [sharkdp/bat#2861]
Hi,

Quoting from the podman-systemd man pages, as they explain best.. ;-)

SYNOPSIS

       name.container, name.volume, name.network, *.kube

   Podman unit search path:

              • /etc/containers/systemd/
              • /usr/share/containers/systemd/

   Podman user unit search path:

              • $XDG_CONFIG_HOME/containers/systemd/ or ~/.config/containers/systemd/
              • /etc/containers/systemd/users/$(UID)
              • /etc/containers/systemd/users/

DESCRIPTION

       Podman  supports  starting containers (and creating volumes) via systemd by using a systemd generator.  These files are read during boot (and when
       systemctl daemon-reload is run) and generate corresponding regular systemd service unit files. Both system and user systemd units are supported.

       The Podman generator reads the search paths above and reads files with the extensions .container .volume and *.kube, and for each file generates a
       similarly named .service file. 

       Files with the .network extension are only read if they are mentioned in a .container file. See the Network= key.

       The  Podman  files use the same format as regular systemd unit files.  Each file type has a custom section (for example, [Container]) that is han‐
       dled by Podman, and all other sections are passed on untouched, allowing the use of any normal systemd configuration options like dependencies  or
       cgroup limits.

**Comment by keith-hall** [comment]
I believe this may have been added in #2866

**Comment by pvdspoel22** [comment]
Thanks @keith-hall , this indeed covers what I was requesting. Excellent! 
Looking forward to testing this. I'll close this ticket.
