### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by texrg** [sharkdp/bat#287]
Hello, is possible to create Fedora package?
Rust exist in fedora

**Comment by thoroc** [comment]
What's the error message though? I am on Fedora 28, have Rust 1.28 installed and I was able to install through cargo. The only caveat was that I didn't have CMake originally. So check your dependencies, maybe?

**Comment by texrg** [comment]
I preffer native package. My disk is too small to compiling it

**Comment by sharkdp** [comment]
I'm going to close this, as it doesn't really make much sense to track this here.
