### ISSUE TITLE
zsh cygwin - "The file cannot be accessed by the system (os error 1920)", works fine with bash cygwin

### ISSUE THREAD

**Issue by sarnobat** [sharkdp/bat#2881]
I love this tool and don't want to be without it even after I die <3

If I start a zsh shell inside a cygwin terminal, I get 

```
$ bat ~/.mydotfile
[bat error]: '~/.mydotfile' The file cannot be accessed by the system (os error 1920)
```

If I switch to bash, this tool works great (so I know the file exists). It also works on zsh if I use `bat cygpath -w ~/.mydotfile` (sorry I can't get backticks to show up correctly around `cygpath -w ~/mydotfile`).

So obviously Cygwin's zsh isn't as bulletproof as bash for these interoperability issues. How tough is it for `batcat` to do the work? I'm all for clean code so can understand if the answer is no. I'm just wanting to know if this can be fixed since I feel so handicapped without my Unix-like environment with these beautiful colors when I'm forced to work on Windows.

**Comment by eth-p** [comment]
Perhaps `bash` is expanding the path before passing command-line arguments and `zsh` isn't? It should be possible to adapt the [cygwin wrapper function](https://github.com/sharkdp/bat#cygwin) in the README to work with zsh, which will make it behave like your `cygpath` example.

As for adding native support for cygwin paths inside `bat`'s Windows build, I'm not sure how feasible that would be. The only way `bat` would be able to tell that it's not being run from a Windows shell is by reading environment variables, and I'm not sure it's a good idea to change the file opening code based on that alone.

There's also the possibility that the cygwin home is not the same as the Windows user profile directory, which further complicates it. If there's a `%USERPROFILE%\.ssh\config` and a `C:\cygwin\home\user\.ssh\config`, which one should it pick? We would have to be confident about `bat` being run from a cygwin environment when prioritizing the cygwin home, or else it would lead to regressions for Windows users.

On top of that, there's no guarantee that cygwin is located at `C:\cygwin`. It could be installed anywhere on the hard drive and even on an external drive from what I remember.

I could dive more into exploring the idea if the other maintainers feel like it's something to pursue, but I think it would be better if cygwin had a native `bat` package that worked within the environment.

**Comment by sarnobat** [comment]
Thank you for the quick detailed reply.

### Solution

I found out that choco's edition of `bat.exe` seems to work without any problem. So:

```
choco install -y bat
```

I'm relieved.
