### ISSUE TITLE
Development with VSCode as IDE

### ISSUE THREAD

**Issue by tijko** [sharkdp/bat#2885]
The labeling for this has me unsure but hopefully I can get some clarification.  I am wanting to be respectful and mindful of your time, energy, and focus.  So thank you in advance.

I recently forked the project and I use it regularly doing Dev work on company machines but also on my personal Archlinux machine.

That said, under VSCode the `tests/syntax-tests/highlighted/Terraform` files have literally crashed my session.  Whenever I load the workspace the "Problems" tab under the terminal console gets flooded with 400+ error messages.

From what I understand this is the very nature of these tests because anecdotally I learned about [DDOS'ing]( http://www.securityfocus.com/archive/1/archive/1/508830/100/0/threaded) various terms (e.g. xterm, gnome-terminal, st) by means of various unhandled escape characters/sequences.

I was going to ask is there a way we can re-name this files and/or sanitize some of the data given the environment?

**Comment by keith-hall** [comment]
perhaps it makes sense to just get VSCode to ignore the `tests/syntax-tests/highlighted` folder? Looks like it can be done in using `files.exclude` https://code.visualstudio.com/docs/getstarted/settings

**Comment by tijko** [comment]
I'm a Vim/Tagbar/Nerdtree kind of Dev but recently have needed to use VSCode (for work).  Thank you, and I apologize if this was a hassle.

**Comment by keith-hall** [comment]
No hassle at all, thanks for reaching out. I'm sure there are many VSCode users so having tips on how to smooth the experience working in the `bat` codebase should be helpful for others too 🙂

**Comment by tijko** [comment]
Way to be, thanks!
