### ISSUE TITLE
Automatic paging

### ISSUE THREAD

**Issue by robinst** [sharkdp/bat#29]
First off, this is nice :).

Have you thought about adding git-style automatic paging to it? If the lines fit on one screen, it would not do paging (like the current behavior). But as soon as it's more than one screen, it could automatically page.

That's one of the things that git got right IMO.

**Comment by sharkdp** [comment]
Thank you for the feedback!

Automatic paging sounds like a great idea. Does anyone know how this is achieved in Git? Would we somehow pipe our own output into `less`?

By the way, `bat .. | less` works fine (even with colors). That's one reason why I'm not sure about #26.

**Comment by robinst** [comment]
Looks like what Git does is this:

* set the `LESS` env variable to `FRX`, see [release notes of Git 2.1.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.1.0.txt#L7)
* invokes `less` as the pager, see [git config reference](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_pager_code)

The `F` and `X` options together are what automatically make less quit if the output fits on one screen. `R` is so that less uses the color escape sequences.

**Comment by robinst** [comment]
> By the way, `bat .. | less` works fine - even with colors (see also #26).

I get the raw escape codes instead of coloring for that, unless I set the `LESS` env variable before. If it works for you then maybe you have `LESS` set already. Try unsetting it and then running it.

**Comment by sharkdp** [comment]
> Looks like what Git does is this:
> 
> * set the LESS env variable to FRX, see release notes of Git 2.1.0
> * invokes less as the pager, see git config reference

Thank you for investigating. This seems to be the part where it launches the pager: https://github.com/git/git/blob/f0294f474e16840f4efb3f4da3329ba46f53efa7/pager.c#L119-L134

It should be possible to implement something similar.

> I get the raw escape codes instead of coloring for that, unless I set the LESS env variable before. If it works for you then maybe you have LESS set already.

You are right. Didn't realize `$LESS` was already configured somewhere.
