### ISSUE TITLE
Display Garbled on Windows Terminal

### ISSUE THREAD

**Issue by shyakocat** [sharkdp/bat#2901]
OS : Windows 11
CMD : Windows Terminal, Powershell, Command Prompt
bat version: 0.24.0

![in Windows Terminal](https://github.com/sharkdp/bat/assets/20227559/ec066a35-9202-4fd8-85f4-5df0c3d317c4)

A hint is that, once I installed `busybox`, it got garbled like this, and I uninstalled `busybox`, it became normal.
This time I don't know I installed what kind of software and the `bat` got garbled again.

**Comment by keith-hall** [comment]
Does it work correctly with `bat test.txt --paging=never`? if so, then you can check to see what installed/overwrote the pager, which is presumably `less`...

**Comment by shyakocat** [comment]
> Does it work correctly with `bat test.txt --paging=never`? if so, then you can check to see what installed/overwrote the pager, which is presumably `less`...

That works with `--paging=never`. Thank you. 
It's not easy to find out the pager overwriter in a short time. I config `bat` with default `--paging=never`, that's fine.
