### ISSUE TITLE
Bat outputs weird characters

### ISSUE THREAD

**Issue by Bobrokus** [sharkdp/bat#2911]
**What steps will reproduce the bug?**

I don't know.

**What happens?**

![image](https://github.com/sharkdp/bat/assets/63786893/9b4d71f3-d45d-40bc-b8df-aff3486e8317)

**What did you expect to happen instead?**

Normal bat output

**How did you install `bat`?**

scoop

---

**bat version and environment**

#### Software version

bat 0.24.0 (fc95468)

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
"D:\Program Files\Scoop\apps\bat\current\bat.exe" --diagnostic
```

#### Environment variables

```bash
SHELL=<not set>
PAGER=<not set>
LESS=<not set>
LANG=<not set>
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_PAGING=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=D:/user
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of 'C:\ProgramData\bat\config': The system cannot find the path specified. (os error 3).

#### Config file

Could not read contents of 'C:\Users\user\AppData\Roaming\bat\config': The system cannot find the path specified. (os error 3).

#### Custom assets metadata

Could not read contents of 'C:\Users\user\AppData\Local\bat\metadata.yaml': The system cannot find the path specified. (os error 3).

#### Custom assets

'C:\Users\user\AppData\Local\bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```
> D:\Program Files\Scoop\apps\w64devkit\current\bin\less.exe --version
BusyBox v1.37.0.git (2023-12-05 17:59:02 UTC)

Usage: less [-EFIMmNSRh~] [FILE]...

View FILE (or stdin) one screenful at a time

        -E      Quit once the end of a file is reached
        -F      Quit if entire file fits on first screen
        -I      Ignore case in all searches
        -M,-m   Display status line with line numbers
                and percentage through the file
        -N      Prefix line number to each line
        -S      Truncate long lines
        -R      Remove color escape codes in input
        -~      Suppress ~s displayed past EOF
D:\Program Files\Scoop\apps\w64devkit\current\bin\less.exe: unknown option -- version
```
Command failed with exit code 1.

**Comment by eth-p** [comment]
Does it work if you use `--paging=never`?

Your version of `less` appears to come from BusyBox, which might not be compatible with ANSI escape sequences like color codes. Specifically, `-R` is labeled as "remove color escape codes in input."

**Comment by Bobrokus** [comment]
@eth-p I will try. Btw bat used to work completely fine before. It just started doing this out of nowhere.

**Comment by escritorio-gustavo** [comment]
> Your version of `less` appears to come from BusyBox, which might not be compatible with ANSI escape sequences like color codes or UTF-8 characters.

This was the issue for me. I solved it by replacing the BusyBox `less` with [jftuga's version](https://github.com/jftuga/less-Windows/releases/tag/less-v643)

**Comment by escritorio-gustavo** [comment]
> Btw bat used to work completely fine before. It just started doing this out of nowhere.

Removing `less` also solves the problem for me. What I think happened is you probably installed `bat` first, so it worked because `less` wasn't there, then you installed `w64devkit`, which brought along a broken version of `less`, which broke `bat`

**Comment by Bobrokus** [comment]
> Does it work if you use `--paging=never`?
> 
> Your version of `less` appears to come from BusyBox, which might not be compatible with ANSI escape sequences like color codes or UTF-8 characters.

yes it does!!

**Comment by Bobrokus** [comment]
> > Your version of `less` appears to come from BusyBox, which might not be compatible with ANSI escape sequences like color codes or UTF-8 characters.
> 
> This was the issue for me. I solved it by replacing the BusyBox `less` with [@jftuga's version](https://github.com/jftuga/less-Windows/releases/tag/less-v643)
> 
> To avoid conflicts from having two versions of `less`, I deleted `C:\w64devkit\bin\less.exe`, downloaded the x64 zip from the link above, and pasted `less.exe` in `C:\w64devkit\bin`

Yeah, you were right. I uninstalled w64devkit and installed the right version of `less`. Now it works fine again!
