### ISSUE TITLE
Bat can't find the theme, even though it's present

### ISSUE THREAD

**Issue by filipebarros** [sharkdp/bat#2945]
I am assuming that this has to do with the theme name: I am using "Rosé Pine" - I added the theme to the themes folder, built the cache, checked the themes and it appears there:

<img width="478" alt="image" src="https://github.com/sharkdp/bat/assets/748089/06ea6577-0794-4048-960b-89ec66042ee1">

Then when I try to use bat, I see the warning about not finding it:
`[bat warning]: Unknown theme 'Rosé Pine', using default.`

My assumption is that it's something to do with the name. I installed bat through homebrew and I have the latest version (0.24.0).

**Comment by keith-hall** [comment]
Where did you get this theme from so we can test it ourselves? https://github.com/rose-pine/sublime-text/commits/main/?after=b03271759cbe8bfbb0f2dc55fefc70c39dcef703+34 from before `#4` was merged?

**Comment by filipebarros** [comment]
I got the file before this one: https://github.com/rose-pine/sublime-text/commit/d4f6c0cb24ed8966f89b3926312d055b388dcfe8

**Comment by keith-hall** [comment]
hmm, weird, that one is working fine for me on Linux with `bat` latest `master` branch

**Comment by filipebarros** [comment]
I think it is to do with the file name: if the filename is "Rosé Pine" it doesn't work, but if the name doesn't have the accent on the `e` it works 🤔 

My issue is that I am using a env variable to control the theme with the terminal, tmux, bat, etc... and this kind of breaks it for me since bat doesn't accept the accent for some reason 🤔

**Comment by keith-hall** [comment]
works fine for me with the accent in the filename and using the env var:
![image](https://github.com/sharkdp/bat/assets/11882719/e4132648-4794-4c21-ada4-a2e88b508c2f)

the `bat` output is barely visible in the screenshot, but for reference it is `#--theme 'Rosé Pine'`  - i.e. commented out so the theme is controlled by the env var only

**Comment by filipebarros** [comment]
I'm feeling stupid - I copied `#--theme 'Rosé Pine'` from your comment, renamed the theme (without any git changes) ran the cache command and it seems to be working now
