### ISSUE TITLE
How to enable Solarized (light) theme

### ISSUE THREAD

**Issue by Amparose** [sharkdp/bat#2957]
Not sure of the syntax to handle the spaces and parens. These don't work:

```shell
bat --theme="Solarized (light)"
bat --theme=Solarized\ (light)
```

So, how do I switch to this theme? Docs should probably be updated with this answer.

This works in config so seems weird the above don't:
```zsh
BAT_THEME="Solarized (light)"
```

**Comment by keith-hall** [comment]
both of those examples work fine for me using Bash:
![image](https://github.com/sharkdp/bat/assets/11882719/6a5ad0e5-0b4c-486e-a67e-02a9e2795b95)

which leads me to wonder, are you using a different shell?

**Comment by Amparose** [comment]
Well I came back to this and tried again and I'm not sure why it didn't seem to work before. I'm going to go with user-error as I can't repro my original issue.
