### ISSUE TITLE
Add Flag to Avoid Treating NUL Separated Input as Binary

### ISSUE THREAD

**Issue by LangLangBart** [sharkdp/bat#2974]
### Discussed in https://github.com/sharkdp/bat/discussions/2971

---

### Issue

Currently, running a command like the following will print a warning:
- Related Issue #823

```sh
printf "First\0" | bat -p
```

<img width="600" alt="SCR-20240529-trdo" src="https://github.com/sharkdp/bat/assets/92653266/f07d4a7a-677d-4b53-b640-d092a7121d72">

The warning is defined in `src/printer.rs`:

https://github.com/sharkdp/bat/blob/8f8c953ab69403a7acf516e65265b7f70bc3ec73/src/printer.rs#L435-L444

The decision to label the input as `BINARY` seems to be made in `src/input.rs`:

https://github.com/sharkdp/bat/blob/8f8c953ab69403a7acf516e65265b7f70bc3ec73/src/input.rs#L260-L271

A _hacky_ workaround is to make the first line empty, use `bat`, and then remove the first line:

```sh
printf "\nFirst\0" | bat -p | sed '1d'
```

---

### Proposed solution

A new flag that doesn't label `content_type` as `BINARY` when the first line ends with a `NUL` byte:

```sh
# naming the flag '--text' to align with 'grep/git diff'
printf "First\0" | bat -p --text
```

The `crate` [^1] used to determine if content is `binary` states:

```rs
//! encoding). Note that **this analysis can fail**. For example, even if unlikely, UTF-8-encoded
//! text can legally contain NULL bytes. Conversely, some particular binary formats (like binary
```

Based on this, a `--text` flag would be very appropriate, similar to how `grep` and `git diff` have one as well.

```sh
printf "First\0" | grep 'First'
# grep: (standard input): binary file matches

printf "First\0" | grep --text 'First'
# First
```

[^1]: [sharkdp/content_inspector: Fast inspection of binary buffers to guess/determine the type of content](https://github.com/sharkdp/content_inspector)

**Comment by domenicomastrangelo** [comment]
Hi @LangLangBart, would your issue be fixed by adding the flag -A to show non printable characters?

This would result in the following output:

<img width="327" alt="image" src="https://github.com/sharkdp/bat/assets/7526063/9c1f775c-b7d1-4634-b21f-ecb1e3dae4dd">

**Comment by LangLangBart** [comment]
> by adding the flag -A

Thanks for the suggestion. I failed to mention this in the issue report here and only described it in the linked discussion. For my use case, the `-A/--show-all` flag would not be adequate.

I try to colorize my `zsh` history and pipe it into `fzf`.

```bash
# zsh only, the '-N'  flag separates the array elements by `NUL`
print -rN -- ${(uv)history[@]} | bat -pl sh | fzf --read0
```

**Comment by domenicomastrangelo** [comment]
My bad, I missed the discussion link.

So the issue you're having, is that when printing something (in this case a line from the history file), in case it has a null char in it, it will give an error.

It feels like a very nieche problem to have, but I think it could be fixed, as you said, adding a --read0 or --read-null-bytes flag.

I could work on this as I'm looking for my first contribution to the project, but it would be good to have an opinion from a more senior contributor too :)

**Comment by keith-hall** [comment]
I'm personally in favor of the idea, but it would be great to wait for input from some of the other maintainers before spending time on it, in case we don't all agree 😉

**Comment by LangLangBart** [comment]
> It feels like a very niche problem to have, but I think it could be fixed, as you said, adding a --read0 or --read-null-bytes flag.

I have updated the description, and I would propose a `--text` flag to align with `grep` and `git diff`.

> wait for input from some of the other maintainers

Agreed, we should wait for input from some of the maintainers.

**Comment by sharkdp** [comment]
Sounds good to me. Let's think about making this an option, not a flag. Maybe there are other reasonable options that we want to add later (apart from a yes or no decision). Like whether or not we print that warning.

**Comment by LangLangBart** [comment]
> Project goals and alternatives
> ...
> Be a drop-in replacement for (POSIX) cat


> Let's think about making this an option, not a flag.

How about this?
If the input was labeled `binary`, check if the `first_line` would also be labeled binary if the last char is not there, don't print the binary message?

**Comment by domenicomastrangelo** [comment]
great, so @LangLangBart you propose --input to specify which language to use for printing or did I get it wrong?

so basically (more or less)

```rust
  if input not set
     let mut first_line = vec![]; 
     reader.read_until(b'\n', &mut first_line).ok(); 
      
     let content_type = if first_line.is_empty() { 
         None 
     } else { 
         Some(content_inspector::inspect(&first_line[..])) 
     }; 
      
     if content_type == Some(ContentType::UTF_16LE) { 
         reader.read_until(0x00, &mut first_line).ok(); 
     }
  else
    content_type = get_content_type_from_input(input)
  endif
```

**Comment by LangLangBart** [comment]
@domenicomastrangelo

@einfachIrgendwer0815 started already a PR.

Besides the color, it works well. Image below comparing `0.7.1` vs their PR.

<img src="https://github.com/sharkdp/bat/assets/92653266/3b7a3f88-74ba-402f-8ce3-72ad67a41c23" width="800">

**Comment by einfachIrgendwer0815** [comment]
@LangLangBart the color issue should be fixed now

**Comment by domenicomastrangelo** [comment]
nice :)
