### ISSUE TITLE
[bat error]: 'REPLY': No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Akado2009** [sharkdp/bat#2975]
HI, I encountered this weird behaviour trying to install bat for mac and pair it with oh-my-zsh.

**What steps will reproduce the bug?**

1. install zsh/oh-my-zsh
2. install bat for mac

**What happens?**
For every command you're gonna have:
```
~/Desktop/kickbot2009 is 📦 1.0.0 via ⬢ v20.11.0 via 🅒 base
➜
[bat error]: 'REPLY': No such file or directory (os error 2)

~/Desktop/kickbot2009 is 📦 1.0.0 via ⬢ v20.11.0 via 🅒 base
➜ ls
TODO.md           const.js          index.js          package-lock.json selected          utils.js
cogs              db                node_modules      package.json      totp.js
[bat error]: 'REPLY': No such file or directory (os error 2)
```
...

**What did you expect to happen instead?**
No error message
...

**How did you install `bat`?**
homebrew

---

**bat version and environment**
```
#### Software version

bat 0.24.0

#### Operating system

macOS 13.4 (Darwin 22.5.0)

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=less
LESS=-R
LANG=nl_NL.UTF-8
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_PAGING=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

```

```

#### Custom assets metadata

```
bat_version: 0.24.0
creation_time:
  secs_since_epoch: 1717077909
  nanos_since_epoch: 631157000
```

#### Custom assets

- metadata.yaml, 97 bytes
- syntaxes.bin, 915557 bytes
- themes.bin, 40606 bytes

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh
- Host: aarch64-apple-darwin

#### Less version

```
> less --version
less 581.2 (POSIX regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

[bat error]: 'REPLY': No such file or directory (os error 2)
```
-->
Here is also the list of brew packages I have installed on my system:
```
➜ brew list
==> Formulae
aom			fzf			libavif			libraw			ncurses			symfony-cli
apr			gd			libde265		libsodium		oniguruma		telnet
apr-util		gettext			libevent		libssh2			openexr			thefuck
argon2			ghostscript		libffi			libtiff			openjpeg		tidy-html5
aspell			giflib			libgit2			libtool			openldap		unixodbc
autoconf		glib			libgpg-error		libunistring		openssl@1.1		utf8proc
autojump		gmp			libheif			libvmaf			openssl@3		webp
automake		highway			libidn			libyaml			pcre			wget
bat			icu4c			libidn2			libzip			pcre2			x265
brotli			imagemagick		libksba			little-cms2		php@7.4			xz
ca-certificates		imagemagick@6		liblqr			llvm			pkg-config		yq
coreutils		imath			libltc			lz4			python@3.12		z3
curl			jasper			libmagic		m4			readline		zlib
diff-so-fancy		jbig2dec		libnghttp2		mc			rtmpdump		zsh
fontconfig		jpeg-turbo		libomp			minio			shared-mime-info	zsh-syntax-highlighting
freetds			jpeg-xl			libpng			mpdecimal		sqlite			zstd
freetype		krb5			libpq			navi			sshuttle

==> Casks
chromedriver	oracle-jdk
```

**Comment by keith-hall** [comment]
It sounds like your terminal emulator is setup to execute something like `bat REPLY` after every command invocation. That's certainly not something `bat` is programmed to do by itself. Perhaps you should debug your `PROMPT` env var etc
