### ISSUE TITLE
no license for bundled sublime-snazzy theme

### ISSUE THREAD

**Issue by decathorpe** [sharkdp/bat#2985]
The "sublime-snazzy" theme bundled [here](https://github.com/sharkdp/bat/tree/v0.24.0/assets/themes) does not specify an open-source license. Typically this means that it's not covered by a specific license, i.e. (C) "All rights reserved", and cannot be freely copied and / or redistributed.

I would suggest to file an issue with the [upstream project](https://github.com/greggb/sublime-snazzy) about explicitly adding a license. If that doesn't happen, I don't think bat can include this theme.

**Comment by CosmicHorrorDev** [comment]
That's one cleared up. I'll open up issues for the other ones after I'm off work today

https://github.com/greggb/sublime-snazzy/commit/48f43a735037195021fa69d99c1180bf12f38f78
