### ISSUE TITLE
bat closes interactive mode instantly when terminal resizes to fit file

### ISSUE THREAD

**Issue by SeseMueller** [sharkdp/bat#3041]
Just a small edge case that appears to not have been covered.

**What steps will reproduce the bug?**

1. locate a file such that a higher terminal can contain it but the current terminal height cannot
2. open it with bat
3. resize the terminal window to be larger. 

**What happens?**

bat closes as soon as the terminal is large enough, without printing anything.

**What did you expect to happen instead?**

I think it should either not close OR print the file to console when the terminal windowbecomes high enough. 
Closing the session just like that is suboptimal, in my opinion.

**How did you install `bat`?**

I installed bat with cargo and it's at version 0.24.0.

---

**bat version and environment**

Likely not necessary, in a detail tag for clarity. 
Also, I do use warp as a terminal, but that should be transparent to the program. 

<details> 

#### Software version

bat 0.24.0

#### Operating system

macOS 14.5 (Darwin 23.5.0)

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=<not set>
LESS=<not set>
LANG=<not set>
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_PAGING=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of '/etc/bat/config': No such file or directory (os error 2).

#### Config file

Could not read contents of '/Users/REDACTEDconfig/bat/config': No such file or directory (os error 2).

#### Custom assets metadata

Could not read contents of '/Users/REDACTED/.cache/bat/metadata.yaml': No such file or directory (os error 2).

#### Custom assets

'/Users/REDACTED/.cache/bat' not found

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh
- Host: aarch64-apple-darwin

#### Less version

```
> less --version
less 581.2 (POSIX regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

</details>

**Comment by eth-p** [comment]
For context, `bat`'s paging (interactive mode) uses another program called `less`.

Looking at the diagnostics you added, the version of `less` installed on your system is 581, which is about 3 years old by now. I tried to reproduce the issue using the latest `less` version (643), and it doesn't close when the terminal window is resized. If you update `less` to a newer version, does that fix the issue for you?

**Comment by SeseMueller** [comment]
Your guess was correct, installing a newer version of less via homebrew does fix this issue. 
Curiously, my version of `less` came preinstalled with my mac, so other mac users might have this issue too, out of the box. 

Closing the issue.
