### ISSUE TITLE
Add support for PowerShell scripts

### ISSUE THREAD

**Issue by mizutoki79** [sharkdp/bat#306]
I'd like to use this bat command for the files related PowerShell whose extension are `.ps1` , `.psm1`, `.psd1` and so on.

**Comment by keith-hall** [comment]
I believe [this `tmLanguage` ](https://github.com/PowerShell/EditorSyntax/blob/12b7d7257eb493e45a9af0af9094ec0c2a996712/PowerShellSyntax.tmLanguage#L5-L10) is the best one can hope for at the moment. If you wish to make a PR to `bat` to add this syntax, there are [instructions here](https://github.com/sharkdp/bat/issues/257#issuecomment-418169177).

**Comment by sharkdp** [comment]
Added in [v0.7.0](https://github.com/sharkdp/bat/releases/tag/v0.7.0).
