### ISSUE TITLE
`mkd` extension not displayed as Markdown

### ISSUE THREAD

**Issue by pataquets** [sharkdp/bat#3060]
**What steps will reproduce the bug?**

1. `cp README.md README.mkd`
2. `bat README.md`: shows file in all fanciness
3. `bat README.mkd`: no fanciness :disappointed:

**What happens?**
`mkd` extension is not automatically handled as Markdown.

**What did you expect to happen instead?**
For all `*.mkd` files to be displayed as Markdown.
Although I stumble with them from time to time, looks like it's not an uncommon practice:
https://github.com/search?q=path%3A*.mkd&type=code

**How did you install `bat`?**
GitHub release

**bat version and environment**
```console
$ bat --version
bat 0.24.0 (fc95468)
```

**Comment by TheUdK** [comment]
Until the pull request is merged #3061 gets merged you can try running `bat --map-syntax='*.mkd:Markdown' or add it to the [config file](https://github.com/sharkdp/bat?tab=readme-ov-file#configuration-file).

Currently the following file extensions get markdown 'fanciness' by default
`md, mdown, markdown, markdn`
