### ISSUE TITLE
Any plans to package it to Deb/Rpm or etc??

### ISSUE THREAD

**Issue by DanielTimLee** [sharkdp/bat#31]
Might be really great to just download from package repo.
(without using cargo)

Any chances to deploy with openSUSE's Build Service?
https://software.opensuse.org/

**Comment by sharkdp** [comment]
Support for RPM would be nice, but I'm not going to work on this myself. There are Debian packages on the Releases page.

**Comment by steven-tan** [comment]
Would love to see a RPM version, may take it on if I find time.

Currently trying to use the binary version but get 

[stan@host `bat-v0.2.1-x86_64-unknown-linux-gnu]$ ./bat 
./bat: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by nakulcg** [comment]
I was looking around a bit on travis, github, and rust internals for packaging but I could not find how releases are done. @sharkdp does one have to manually build packages e.g. the .deb you have on releases page and upload it? Or you get it from some CI e.g. travis? I tried the `draft a new release` but all it showed me was file select box from my own filesystem. If it is manual I could add an rpmspec to the repo

**Comment by steven-tan** [comment]
@sharkdp Thanks for trying. Looks like I'm getting a new issue. This is on a centos7 box:

`[stan@stan-c7admin bat-v0.2.3-x86_64-unknown-linux-gnu]$ ./bat`
`./bat: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./bat)`

It's possible i really should just try and compile it.

**Comment by sharkdp** [comment]
It seems like the original question was answered. If any further problems occur while creating an RPM package, please feel free to open a new ticket.
