### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by dcabrejas** [sharkdp/bat#317]
Hey, thanks for the tool.

Are there any plans to provide a binary for Fedora?
I noticed downloads for most other distributions are available but Fedora/Red Hat was missing.

**Comment by sharkdp** [comment]
Thank you for the feedback!

Please see #287 and/or #189.

**Comment by lunaryorn** [comment]
Hey, I just made a [copr for bat](https://copr.fedorainfracloud.org/coprs/lunaryorn/bat/).  I'd appreciate feedback :)

**Comment by sharkdp** [comment]
I'm not an expert, but your [spec file](https://copr-dist-git.fedorainfracloud.org/cgit/lunaryorn/bat/bat.git/tree/bat.spec) looks good to me.

Two remarks:
- Starting with the *next* version of bat, we will also ship shell-completion files (see #327)
- `cargo build` will include debug symbols even if you use `--release`. If you want to reduce the size of the binary, you can call `strip` (we do the same for Debian packages: https://github.com/sharkdp/bat/blob/0d7196861523ca14a1df58f7fbf9a75c34723175/ci/before_deploy.bash#L32-L34)

**Comment by lunaryorn** [comment]
@sharkdp I am not too familiar with rust but I thought `--release` only compiled with debug info if `Cargo.toml` explicitly enables it with `debug = true` in the `release` profile section, and we used `strip` not to remove debug info (which isn't there) but to remove symbols names which a binary doesn't need.  At least the rpm build didn't find any debug info in the binary apparently; I disabled the debug package in the spec file to fix the corresponding build error.

**Comment by lunaryorn** [comment]
@sharkdp To be honest I would rather not 😔

I made this copr for my own use.  I'm happy if others use it as well, but I would rather not like it becoming an “official” installation method—I'd not like to make any promises about maintaining this copr in the future 😔  copr's not the easiest thing to use, and I'd not like to be pressured into keeping it up to date.

**Comment by sharkdp** [comment]
@lunaryorn Good point. I definitely wouldn't want to pressure anyone into a maintenance task.

**Comment by lunaryorn** [comment]
@sharkdp Thanks for understanding ❤️  Cheers!

**Comment by drahnr** [comment]
As of `Fedora 29` `bat` is available in the repos.

**Comment by drahnr** [comment]
```
Name         : bat
Version      : 0.8.0
Release      : 1.module_2418+43cef932
Arch         : x86_64
Größe        : 3.8 M
Quelle       : rust-bat-0.8.0-1.module_2418+43cef932.src.rpm
Paketquelle  : @System
Aus Paketque : updates-modular
Zusammenfass : cat(1) clone with wings
URL          : https://crates.io/crates/bat
Lizenz       : MIT or ASL 2.0
Beschreibung : cat(1) clone with wings.
```

**Comment by sharkdp** [comment]
Does this mean that Fedora 29 users can just type
```
dnf install bat
```
to install `bat`? (sorry, not a Fedora users myself)

**Comment by drahnr** [comment]
So after removing bat again:

```bash
# dnf info bat
Name         : bat
Version      : 0.8.0
Release      : 1.module_2418+43cef932
Arch         : x86_64
Größe        : 1.4 M
Quelle       : rust-bat-0.8.0-1.module_2418+43cef932.src.rpm
Paketquelle  : updates-modular
Zusammenfass : cat(1) clone with wings
URL          : https://crates.io/crates/bat
Lizenz       : MIT or ASL 2.0
Beschreibung : cat(1) clone with wings.
```

and 

```bash
dnf install bat
```

works just fine :)
