### ISSUE TITLE
Request: Provide a PPA for Debian/Ubuntu

### ISSUE THREAD

**Issue by beruic** [sharkdp/bat#323]
Providing a PPA would be an awesome way to gain more users. Personally I usually don't install a .deb alone, unless is sets up its own repository, such that I will get updates automatically.

**Comment by mbitokhov** [comment]
A snap package would also be useful. I've looked a little bit, but I couldn't find anything

**Comment by sharkdp** [comment]
> Providing a PPA would be an awesome way to gain more users. Personally I usually don't install a .deb alone, unless is sets up its own repository, such that I will get updates automatically.

I agree - it would be great. However, I'm personally not going to set this up and/or maintain it (see also #50 #31 #317 #287). I have looked into creating a PPA in the past, but gave up after some time. If someone wants to set up a PPA (and maintain it), I'm happy to include instructions in the README.

> A snap package would also be useful. I've looked a little bit, but I couldn't find anything

please see #241.

**Comment by mbitokhov** [comment]
> please see #241.

Alright. Sorry about that. Thanks!

**Comment by BK1603** [comment]
Will maintaining a ppa make me a debian maintainer? Like I am trying to get a package to maintain at the debian repositories(or ppa, I just want to contribute :smile:), and I am reading about it, so if you would like to I can take this up, with a bit of your help that is :sweat_smile:

**Comment by BK1603** [comment]
I have made the PPA, it isn't live yet, just a progress report, and hey @sharkdp(!!Noob question alert!!) do I need to make the package again? Or will the packages given on the releases page would work?

**Comment by sharkdp** [comment]
The Debian packages on the release page are hopefully "Ubuntu-compliant", but I really don't know how PPAs work, so I'm the wrong person to ask.

**Comment by BK1603** [comment]
Well I have almost figured it out I guess, yep they should be compliant, and I hope I have it done by the weekend :sweat_smile:

**Comment by BK1603** [comment]
Hey there everyone, this is another heads up, not too good though :sweat_smile: I have exams going on which would probably end by the next week, please be patient till then, I really want to make this ppa and I am sorry if I am causing trouble to anyone :sweat_smile:

**Comment by BK1603** [comment]
So tomorrow is my last exam, I will be on it tomorrow ASAP thank you everyone for the patience!

**Comment by h3ct0rjs** [comment]
Hi @BK1603 what happend with the Debian package, I also want to create a Deb package.

**Comment by BK1603** [comment]
@h3ct0rjs Well the debian packages are there on the releases pages too but I have to repackage everything because launchpad doesn't except .deb files, they need the source tar ball and they will compile it themselves, so I am acutally packaging the but I really do not get a lot of time these days :sweat_smile: So the work is going on kinda slow :sweat_smile:

**Comment by Xerus2000** [comment]
Any news? I'd love to install from a ppa!

**Comment by sharkdp** [comment]
fd is now officially integrated in Debian, so I was hoping that it would somehow be automatically transferred to Ubuntu. I don't really understand much about this process though, so any information on this would be very helpful.

**Comment by h3ct0rjs** [comment]
Hi  everybody, due to lot's of work I won't be able to complete the task if it's there anybody else to take this one It would be great. 

Thanks in advance, 
H.

**Comment by sharkdp** [comment]
Anyone here with experience in setting up PPAs?

**Comment by Xerus2000** [comment]
Little workaround script for the meantime to get the latest version for ubuntu anytime: https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8#gistcomment-2989645

**Comment by sharkdp** [comment]
`bat` was recently accepted into Debian unstable:
* https://lists.debian.org/debian-devel-changes/2019/08/msg02304.html
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907080
* https://twitter.com/SylvestreLedru/status/1161715593827012609

Many thanks to @helen-fornazier @paride @Sylvestre and everyone else involved!

While that doesn't provide an immediate solution to this issue (or is there a way to use these packages right now?), this hopefully means that, eventually, there will be no need for a PPA.

**Comment by paride** [comment]
\o/

@sharkdp the `bat` package is available right now in Debian unstable, and will be available soon in testing, and likely in Ubuntu starting from the next release (19.10).

**Comment by dvergeylen** [comment]
https://packages.debian.org/sid/bat
https://tracker.debian.org/pkg/rust-bat

**Comment by h3ct0rjs** [comment]
nice thanks for share @dvergeylen

**Comment by sharkdp** [comment]
A `bat` package is now available in Ubuntu 19.10: https://packages.ubuntu.com/eoan/bat

This is already documented in the README.

**Comment by 3nuc** [comment]
The above returns an error at the time I'm writing.

See https://packages.ubuntu.com/groovy/bat instead

**Comment by beruic** [comment]
@3nuc You give no information to what the error is.

**Comment by KaKi87** [comment]
Hi,
As Debian & Ubuntu APT repositories are outdated, I would like to bump the request for a PPA.
Thanks

**Comment by sylvestre** [comment]
Not sure what you are talking about:
Debian sid is proposing 0.24.0
https://packages.debian.org/unstable/bat

**Comment by KaKi87** [comment]
Come on. Real end users use 12 and 13, not unstable.

**Comment by sylvestre** [comment]
you can:
* do [pinning](https://wiki.debian.org/AptConfiguration#apt_preferences_.28APT_pinning.29) just to get this unstable package
* wget && dpkg -i the .deb which should work perfectly
* be a bit patient

**Comment by KaKi87** [comment]
> * do [pinning](https://wiki.debian.org/AptConfiguration#apt_preferences_.28APT_pinning.29) just to get this unstable package

That's not user-friendly.

> * wget && dpkg -i the .deb which should work perfectly

That doesn't allow automated updates.

> * be a bit patient

The last release is already two months old.

**Comment by KaKi87** [comment]
Hi,

A few months ago, I started developing a tool named [dynapt](https://git.kaki87.net/KaKi87/dynapt) to automatically fetch updates through APT for packages that don't provide an APT repository.

As I've been upgrading bat through it for quite some time now, I just published my first pre-release of it, which you can download and set up from [this tutorial](https://gist.github.com/KaKi87/f620788e9901abbfef4978eb7ad358b4).

For bat specifically, replace the following configuration line :

```json
    "apps": []
```

With the following :

```json
    "apps": [
        {
            "name": "bat",
            "github": {
                "repo": "sharkdp/bat",
                "filter": "bat_*amd64*"
            }
        }
    ]
```

But also change `amd64` to `arm64` if applicable.

For questions or issues, please submit a comment on the tutorial page.

Thanks

**Comment by h3ct0rjs** [comment]
pretty cool @KaKi87 .
