### ISSUE TITLE
Feature: support passing initial commands to pager

### ISSUE THREAD

**Issue by niedzielski** [sharkdp/bat#324]
less supports initializing the pager with a passed command. One useful use case is to specify a starting regular expression to search for. For example, when configuring the pager option for Git, search can be configured to hop along commits and files: `less -iRFXx2 '+/^(commit|added:|deleted:|modified:|renamed:|stash@\\{[0-9]+\\}:) '`. `bat` supports passing a subcommand but as far as I can tell there's no way to pass options onto the underlying pager. This feature request encapsulates the work required to add command passing functionality from CLI argument to pager.

**Comment by sharkdp** [comment]
Thank you for the feedback.

Isn't this possible with the same method as described in https://github.com/sharkdp/bat#using-a-different-pager?

**Comment by niedzielski** [comment]
Thanks @shardp! Sorry for the RTFM! I seem to be having an unrelated issue with the pattern but argument passing works. :+1:  :+1:

**Comment by sharkdp** [comment]
This just got much easier with [v0.8.0](https://github.com/sharkdp/bat/releases/tag/v0.8.0).
