### ISSUE TITLE
Add documentation on how to get it working with git show

### ISSUE THREAD

**Issue by dylan-chong** [sharkdp/bat#334]
My main use case for this program is to add syntax highlighting to `git show somebranch:somefile`. Would be possible to add some documentation on how to use bat as the default git show viewer.

One thing to may be consider is a possible conflict with  https://github.com/so-fancy/diff-so-fancy

**Comment by dylan-chong** [comment]
This is a really awesome looking tool by the way !

**Comment by sharkdp** [comment]
Small update: #205 is now implemented, so just configuring `bat` as a pager works for cases where the syntax of the file can be determined from the first line (typically via shebangs in Python, Bash, etc).

**Comment by sharkdp** [comment]
@dylan-chong Any update on this?

**Comment by dylan-chong** [comment]
I haven't tried because the issue  that closes this only works be checking she shebang line at the start of the file, which doesn't really allow the syntax highlight to work most of the time

**Comment by sharkdp** [comment]
`git show` doesn't provide any information about the filename to the pager, so I guess an external tool or shell function will be the only option.

This works for me (bash or zsh):
```bash
function git-show() {
    local ref="$1"
    local extension="${ref##*.}"

    git show "$ref" | bat --language "$extension"
}
```

**Comment by dylan-chong** [comment]
That might be a little inconvenient because bash auto complete won't work on branch names. Oh well it's not a hugely important feature anyway

**Comment by sharkdp** [comment]
Yeah, sorry. I really don't think there is a better way unless someone wants to propose a change in Git such that it publishes the filename via some environment variable, for example :smile:
