### ISSUE TITLE
Default colorschemes for light terminals

### ISSUE THREAD

**Issue by jaepd** [sharkdp/bat#34]
Hi! I just found this tool and it would be super nice if there was a way to use it for terminals with a light background color (e.g. solarized light). I'm just hoping there's a quick way to provide a dark colorscheme by default.

Thanks alot for making this!

**Comment by sharkdp** [comment]
Thank you for the feedback.

Yes, there should be a way to easily configure the highlighting theme (see also #1).

In the meantime, you could try to do this (see "Customization" section in the README):
``` bash
# Get theme
mkdir -p ~/.config/bat/themes
cd ~/.config/bat/themes
git clone https://github.com/braver/Solarized
ln -sf "Solarized/Solarized (light).tmTheme" Default.tmTheme

# Get language definition files
mkdir -p ~/.config/bat/syntax
cd ~/.config/bat/syntax
git clone https://github.com/sublimehq/Packages/
rm -rf Packages/Markdown
git clone https://github.com/jonschlinkert/sublime-markdown-extended

# Initialize cache
bat init-cache
```

**Comment by nevyn-lookback** [comment]
Thanks! Tried this, two errors with the 0.2.3 binary Mac release:

1. Init-cache seems to use ~/L/P/bat, not .config?
```
⋊> ~ bat init-cache                                                                          10:09:20
[bat error]: Could not load themes from '/Users/nevyn/Library/Preferences/bat/themes'
```

2. Tried remedying with `ln -s ~/.config/bat/themes ~/Library/Preferences/bat/themes`.  Now I no longer have syntax highlighting, everything's rendering gray o_O

<img width="871" alt="screen shot 2018-05-03 at 10 10 03" src="https://user-images.githubusercontent.com/31317203/39565946-2b59d170-4eba-11e8-80ae-26ea98b1e7b2.png">

**Comment by sharkdp** [comment]
> Init-cache seems to use ~/L/P/bat, not .config?

On macOS - yes. I should update this in the README.

> Tried remedying with ln -s ~/.config/bat/themes ~/Library/Preferences/bat/themes. Now I no longer have syntax highlighting, everything's rendering gray o_O

You can always reset everything by removing the cache folder (~/Library/Caches/bat).

**Comment by sharkdp** [comment]
Even without customization, you should now be able to use
``` bash
bat --theme="Monokai Extended Light" README.md
```

**Comment by pylipp** [comment]
In the script described [above](https://github.com/sharkdp/bat/issues/34#issuecomment-385634632), I had to replace `~/.config/bat/syntax` by `~/.config/bat/syntaxes`, as described in the README.

**Comment by sharkdp** [comment]
@pylipp Thanks. I have adapted my comment above.

**Comment by jeffbyrnes** [comment]
For anyone coming here and cloning the `braver/Solarized` repo, note that they’ve converted to `sublime-theme` format. You can clone the older tmTheme version by `git checkout 87e01090cf` after you clone the repo.

**Comment by markkrueger** [comment]
Another way of handing what @jeffbyrnes brings up:
git checkout -b b1.6.0 1.6.0
Then you use the tag they have in the repo.

**Comment by FlyingFoX** [comment]
`bat cache --init` no longer works and should be replaced by `bat cache --build`

**Comment by FlyingFoX** [comment]
A solarized light theme is now available in the standard install and can be used with `--theme="Solarized (light)"`.
