### ISSUE TITLE
Add support for Jupyter Notebook files (.ipynb)

### ISSUE THREAD

**Issue by gyscos** [sharkdp/bat#342]
Jupyter saves its notebook as `*.ipynb` files, which are really just JSON files. Using the default JSON syntax could work fine.

**Comment by sharkdp** [comment]
I have opened a PR here: https://github.com/sublimehq/Packages/pull/1741

I'm going to close this ticket, but this change will eventually land in `bat`, if the PR gets accepted.

**Comment by sharkdp** [comment]
You can now also use
```
--map-syntax ipynb:json
```
in your config file.

**Comment by mogwai** [comment]
Would be great to just print out the code / outputs instead of the json
