### ISSUE TITLE
Rewrite `--tabs` tests as integration tests

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#351]
It would be great to remove all tab-specific things from `tests/tester.rs` and `tests/snapshot_tests.rs` and to re-write these tests as "proper" integration tests in `tests/integration_tests.rs`. The latter are much easier to use and their output is easier to parse in case of failures.

**Comment by choznerol** [comment]
If there's no work in progress, I would like to take this issue!

**Comment by sharkdp** [comment]
As a first step, I would just like to move the `tabs_` snapshot tests to the integration tests file. We can think about migrating the others later on.

**Comment by sharkdp** [comment]
Also, the tab-specific tests should be written in the style of the other integration tests, without the snapshot_test macro.

Thank you for your help!

**Comment by choznerol** [comment]
ok! I opened #356 and we can discuss further steps there :)
