### ISSUE TITLE
Add a way to pass arguments to the pager via PAGER / BAT_PAGER

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#352]
We can use a function to split a (simple) shell command-line into multiple arguments. This would allow use to use just
```
BAT_PAGER="less --tabs 4 -RF"
```
instead of using a wrapper script.

This could be useful: https://crates.io/crates/shell-words

**Comment by Foxboron** [comment]
Taking a stab at this one :)

**Comment by sharkdp** [comment]
Released in [v0.8.0](https://github.com/sharkdp/bat/releases/tag/v0.8.0).
