### ISSUE TITLE
[fzf] Bat is awesome, but

### ISSUE THREAD

**Issue by andreyorst** [sharkdp/bat#357]
It's so awesome, but whyyyyy

> Whenever bat detects a non-interactive terminal, it will fall back to printing the plain file contents.

I wanted to use `bat` instead of `highlight` in [fzf](https://github.com/junegunn/fzf), since it can use `cat` for previewing files, but this line kills the usage for me unfortunately. I don't use `cat` as standalone app at all, but as embedded one, and it's unfortunately that fzf treated as *non-interactive* terminal, however it supports scrolling. Or maybe I should open issue on fzf side?

**Comment by sharkdp** [comment]
> It's so awesome, but whyyyyy
> 
> > Whenever bat detects a non-interactive terminal, it will fall back to printing the plain file contents.

Because we want `bat` to be a drop-in replacement for `cat`. For example, you usually wouldn't want ANSI escape characters (that are used for colorized text in the terminal) to end up in a text file when you call `bat file_a.js file_b.js > both.js`.

> I wanted to use `bat` instead of `highlight` in [fzf](https://github.com/junegunn/fzf), since it can use `cat` for previewing files, but this line kills the usage for me unfortunately.

You can do this. You just have to explicitly enable colors and decorations. Please study the `--help` text of `bat`. Both `--color` and `--decorations` can be set to "always".

Also, make sure to use `fzf`s `--ansi` option. I have personally set up `fzf` + `bat` like this:

```bash
export FZF_DEFAULT_OPTS="--ansi --preview-window 'right:60%' --preview 'bat --color=always --style=header,grid {} --line-range :300'"
```

Please let me know if this works for you.

**Comment by andreyorst** [comment]
Oh, that's so cool! Sure it works. I'll add `bat` as a supported tool to my fzf plugin for kakoune then. Thank you!

**Comment by andreyorst** [comment]
Now we're going somewhere!
![image](https://user-images.githubusercontent.com/19470159/46921400-643d0500-d003-11e8-89f5-cf45a4b4a9a6.png)

**Comment by sharkdp** [comment]
Awesome :+1:


Shameless advertising of another project of mine: You can also integrate [`fd`](https://github.com/sharkdp/fd) with `fzf` (instead of using `find`). This is not just faster, it also adds colors to your file paths and hides files that you don't want to open in your editor (`.gitignore`d files, for example).

Instructions are here: https://github.com/sharkdp/fd#using-fd-with-fzf

**Comment by andreyorst** [comment]
Yeah, your `fd` is awesome, and it is already supported by my [fzf.kak (shameless advertisement)](https://github.com/andreyorst/fzf.kak) plugin :smiley_cat:

**Comment by sharkdp** [comment]
Fantastic! :heart_eyes:

**Comment by andreyorst** [comment]
I do use `fd` in favor of `find`, however `find` can be found on very most systems, and `fd` not. For example rust packages are not yet supported in Termux, where I use Kakoune with fzf. So default tool is always the most widespread one, but if user wants to change it, it is changeable.

**Comment by sharkdp** [comment]
> So default tool is always the most widespread one, but if user wants to change it, it is changeable.

Yes, of course!

> For example rust packages are not yet supported in Termux, where I use Kakoune with fzf

`fd` is actually supported (`pkg install fd`). `bat` has been added a few minutes ago: https://github.com/termux/termux-packages/commit/16de13911b0dde1a303ca84996579d9b6954c986 :smile:

**Comment by andreyorst** [comment]
ugh oh, seems that my agents provide outdated info... Anyway, bug thanks for your great tools!

**Comment by MoezGholami** [comment]
Can we tell bat to highlight a pattern passed as command line argument? Currently, using LESS style search (`/`), we can go through the matches and they get highlighted one by one. But if we have a command line option to get the searching pattern (e.g. `bat --highlight "AB*D"`), we can use bat as a search preview tool also.
(To be honest, I want to implement [`fif` here](https://github.com/junegunn/fzf/wiki/examples#searching-file-contents) using bat as it is a way better syntax highlighter than `rg`).

**Comment by eth-p** [comment]
@MoezGholami If you're looking for a way to highlight lines that match some pattern, you might be able to borrow some ideas from [batgrep](https://github.com/eth-p/bat-extras/blob/master/src/batgrep.sh)?

If you're specifically looking for a way to highlight a line which matches a pattern specified through a command line argument, I would definitely say to open a feature request for it.

**Comment by dandavison** [comment]
@MoezGholami Is this similar to what you have in mind?

```
LESS='--pattern=pub' bat printer.rs
```

![image](https://user-images.githubusercontent.com/52205/68996280-6eac7c80-085d-11ea-906a-7c1175d1a8c8.png)

(Thanks to @ahmedelgabri for [showing me](https://github.com/dandavison/delta/issues/50#issue-516622842) `--pattern`.)

**Comment by MoezGholami** [comment]
@dandavison Thanks man, that's exactly what I want. @eth-p and @ahmedelgabri , thank you too.

**Comment by dagadbm** [comment]
for people who are on a quest to make a preview with bat AND tree when it is a directory after painful trial and error here it is:
```
# this is what matters
FZF_COMMON_OPTIONS="
  --bind='?:toggle-preview'
  --bind='ctrl-u:preview-page-up'
  --bind='ctrl-d:preview-page-down'
  --preview-window 'right:60%:hidden:wrap'
  --preview '([[ -d {} ]] && tree -C {}) || ([[ -f {} ]] && bat --style=full --color=always {}) || echo {}'"

command -v fd > /dev/null && export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
command -v bat > /dev/null && command -v tree > /dev/null && export FZF_DEFAULT_OPTS="$FZF_COMMON_OPTIONS"
command -v fd > /dev/null && export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
command -v fd > /dev/null && export FZF_CTRL_T_COMMAND='fd --type f --type d --hidden --follow --exclude .git'
```

**Comment by ahmedelgabri** [comment]
@dagadbm I think this can be slightly simplified, you don't need the `-f` or `-d` checks, that's what I use. 

```zsh
export FZF_PREVIEW_COMMAND="bat --style=numbers,changes --wrap never --color always {} || cat {} || tree -C {}"
export FZF_CTRL_T_OPTS="--min-height 30 --preview-window down:60% --preview-window noborder --preview '($FZF_PREVIEW_COMMAND) 2> /dev/null'"
```

**Comment by dagadbm** [comment]
it works like that for you? i tried that before and he always printed both things.
meh who knows.

**Comment by sharkdp** [comment]
It would be great if you could post your findings/scripts/solutions in #448. We are still lacking a `README` section for a good `bat` + `fzf` integration.
