### ISSUE TITLE
Any plans to support syntax highlighting for emacs org-mode file?

### ISSUE THREAD

**Issue by nasyxx** [sharkdp/bat#36]
Hi, do you have any plans to support syntax highlighting for emacs org-mode file, which is also a markup language?

org-mode: https://orgmode.org

An example:

![](https://orgmode.org/img/main.jpg)

**Comment by sharkdp** [comment]
Sounds good!

Could you please point me to a Sublime Text syntax definition and an example orgmode file?

**Comment by nasyxx** [comment]
Although I am not using sublime text, I tried searching and found one. Do not know if this is satisfied.

https://github.com/danielmagnussons/orgmode

**Comment by sharkdp** [comment]
Unfortunately, we will need a `.sublime-syntax` file if we want to support this.

**Comment by bricewge** [comment]
I have found a `.sublime-syntax` for `org-mode`at https://github.com/dim-an/Zorgmode. Using it with `bat` it doesn't seems to colorize much, I only get source code highlighted...

**Comment by bricewge** [comment]
I wasn't able to convert https://github.com/danielmagnussons/orgmode with sublime, it never produced a file. Fortunately it worked with https://github.com/jezcope/Org.tmbundle, the colorization seems enough to me. You can find the converted `.sublime-syntax` file [here](https://gist.github.com/bricewge/25edc5f66404dee2fe19bf90c205a29c).

**Comment by sharkdp** [comment]
Thank you for looking into this. Happy to add this to `bat` if somebody wants to work on this.

**Comment by PicoSushi** [comment]
Is Org highlighting working for now?

I opened some file with `.org` extension but not worked, and I tried `bat --list-languages` and Org not found.

```
$ bat --version
bat 0.11.0
```

**Comment by bricewge** [comment]
No release contains the PR yet: https://github.com/sharkdp/bat/compare/v0.11.0...master.

**Comment by sharkdp** [comment]
> No release contains the PR yet: [v0.11.0...master](https://github.com/sharkdp/bat/compare/v0.11.0...master).

Exactly. I hope I can put out a new release soon.

**Comment by sharkdp** [comment]
Released in [bat v0.12](https://github.com/sharkdp/bat/releases/tag/v0.12.0).
