### ISSUE TITLE
Set pager through config file.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#362]
As of bat 0.8, there doesn't currently seem to be any way to set the pager aside from the `BAT_PAGER` environment variable. If we added a `--pager` argument, the pager could be configured through the bat config file.

- Should this be added?
- IF so, should the `--pager` argument be hidden from `--help`?

**Comment by sharkdp** [comment]
> * Should this be added?

Yes! I had the same thought yesterday. Thank you for opening this ticket.

> * IF so, should the `--pager` argument be hidden from `--help`?

Hm.. maybe we can set `.hidden_short_help(true)` such that it will not appear in `-h` help text, but still be visible in the `--help` text. We should actually do the same for the `--config-file` and `--no-config` arguments.

**Comment by majecty** [comment]
If there's no work in progress, I would like to take this issue.

**Comment by sharkdp** [comment]
@majecty Sounds great! I don't think there is any work in progress so far.

**Comment by sharkdp** [comment]
This is now available in [bat 0.9](https://github.com/sharkdp/bat/releases/tag/v0.9.0).
