### ISSUE TITLE
SVN support

### ISSUE THREAD

**Issue by Fxrh** [sharkdp/bat#364]
I stumbled today upon this great tool, thanks for writing it! However, I am still stuck with some SVN repositories for work, for which bat does not seem to show changes yet. Is there any chance for getting SVN support for bat?

**Comment by sharkdp** [comment]
> I stumbled today upon this great tool, thanks for writing it!

Thank you for the feedback!

> Is there any chance for getting SVN support for bat?

Having previously been in the same situation as you (before we switched to Git), I can definitely feel you and see why this would be useful.

However, to be honest, I think this probably not going to happen. Even if there would be a SVN crate for Rust (which I believe there isn't) and if someone would be willing to write the respective code to support SVN in `bat`, I'm not sure if I would be willing to maintain the additional code in the future.

**Comment by eugenetriguba** [comment]
For anyone in the future who may happen to come across this, you can pipe the `svn diff` into `bat` (`svn diff | bat`) and get a nice colorized output, which works fine as a workaround with svn repositories for me.
