### ISSUE TITLE
Forcing solid background

### ISSUE THREAD

**Issue by mkatychev** [sharkdp/bat#365]
Hi is there functionality similar to vim to be able to force a solid background on transparent terminals?

**Comment by sharkdp** [comment]
Thank you for the feedback.

There is no such functionality in bat, and I don't plan to add something like this because `bat` is basically text/ANSI-code based and not a "full" TUI application which controls the full terminal.

You could try to find a color scheme that has less color variance.

**Comment by mkatychev** [comment]
@sharkdp ok thanks for the heads up!
