### ISSUE TITLE
Allow for multiple occurences of "--style"

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#367]
There should be a way to specify `--style` multiple times. This way, users can set `--style=numbers,changes` in their config file, but still use `--style=changes` on the command line.

**Comment by sindreij** [comment]
I'd like to take this issue

**Comment by sindreij** [comment]
Is the idea that the last argument overrides the first? So that `--style=full --style=plain` results in the plain style?

**Comment by sharkdp** [comment]
> Is the idea that the last argument overrides the first? So that `--style=full --style=plain` results in the plain style?

Exactly. It would be great if `--plain` and `--number` would also override any previous `--style` argument if that's possible.

**Comment by sindreij** [comment]
@sharkdp: That sounds logical. I have created PR #371. It has code both to make style override style, and style and plain overrides each other. So only one the last one of those will have an effect.

I had to remove clap's splitting of the arguments in style. When using clap's splitting with overriding, it only keep the last one in the set. So `--style numbers,changes` becomes `changes`.

**Comment by sharkdp** [comment]
This is now available in [bat 0.9](https://github.com/sharkdp/bat/releases/tag/v0.9.0).
