### ISSUE TITLE
Support inline-diffs when using bat as a git pager

### ISSUE THREAD

**Issue by bendem** [sharkdp/bat#369]
Extracting this from https://github.com/sharkdp/bat/issues/23#issuecomment-431514541

> @bendem Thank you for your feedback. This is not really related to this ticket. I don't currently plan to implement inline-diffs and I think that would be quite a substantial feature. If you think this should be discussed, please open a new ticket.

> @bendem Could you elaborate what that means?

I mean that git supports highlighting **inside** of lines, which I don't think `bat` does yet. That would be an awesome feature to have.

diff-highlight
![screen shot 2018-10-03 at 09 35 11](https://user-images.githubusercontent.com/2681677/46396496-d94d3800-c6ef-11e8-94ba-9381faee2e4f.png)

no diff-highlight
![screen shot 2018-10-03 at 09 36 31](https://user-images.githubusercontent.com/2681677/46396495-d94d3800-c6ef-11e8-9d8a-49f68548e8ad.png)

**Comment by sharkdp** [comment]
Thank you for the feedback.

I still don't really understand what this feature request is about. We do not show diffs in `bat` at all (and don't really plan to). We show the *current version of the file* and git modification markers to indicate any changes with respect to the Git index.

How exactly would you like this to be integrated in `bat`? Would you like to see some form of highlighted text (e.g. by using a background color) for the exact part of the line that has been modified (i.e. those lines that are now marked by `~`)?

**Comment by bendem** [comment]
#23 is about using bat as a git pager. In that case, it is actually formatting diffs, not showing the current version of the file.

**Comment by bendem** [comment]
Probably a better example:
![screenshot 2018-12-10 at 12 38 36](https://user-images.githubusercontent.com/2681677/49730415-94f29100-fc78-11e8-8d3e-68f4551cd1e2.png)

**Comment by dvogt23** [comment]
Similar to https://github.com/so-fancy/diff-so-fancy

**Comment by sharkdp** [comment]
> #23 is about using bat as a git pager.

The original question was about that, but we decided to go another way (use libgit2 inside `bat` directly).

> In that case, it is actually displaying diffs, not showing the current version of the file.

In the linked ticket, you wrote *"I mean that git supports highlighting inside of lines, which I don't think bat does yet."*, so I was thinking that you want us to implement inline-diffing in `bat` (see also my comment above).

Judging from the screenshot you now posted, I'm assuming this is just a bug report that the background-color highlighting is missing when piping `git diff` into `bat`

I'm a little bit tired of having to guess what this is really about, so I would ask you to please write a detailed request or bug description.

**Comment by sharkdp** [comment]
Closing this, as it's still not clear to me what this ticket is about - sorry. Happy to reopen this if there is further feedback.
