### ISSUE TITLE
TOML support

### ISSUE THREAD

**Issue by mcginty** [sharkdp/bat#37]
Hey! Looks like TOML support is missing. Sorry if this issue should be on one of your dependencies and not this repo :).

I added it with the README's instruction for syntax support, but might be nice to include by default, especially since this tool is written in Rust!

**Comment by sharkdp** [comment]
Sounds good! Could you please let me know which syntax file you used?

**Comment by mcginty** [comment]
I chose https://github.com/lmno/TOML, which I converted to `.sublime-syntax`, but I spoke too soon because it's an incomplete version of the TOML spec. At this point I'm not sure if there's a good out-of-the-box choice for TOML. If I have free time I might try to fix it up, but it's going to be a busy few weeks :/.

**Comment by mcginty** [comment]
Oh nice, I just tried that out and it seems to highlight a more complex TOML file correctly.

**Comment by mcginty** [comment]
https://gist.github.com/mcginty/168a500f3ff0cab7f096926ed3860a1f here's a converted version of that better version.

**Comment by sharkdp** [comment]
There is also this: https://github.com/jasonwilliams/sublime_toml_highlighting/pull/7 :smile:

**Comment by mcginty** [comment]
oh that's awesome, glad other people are so on top of this haha
