### ISSUE TITLE
Generated fish completion does not complete filenames

### ISSUE THREAD

**Issue by sboukortt** [sharkdp/bat#372]
The result is that Tab is only able to complete options, and not the paths to the files that one may want to display.

**Comment by sharkdp** [comment]
Thank you for reporting this.

I think this is related to https://github.com/clap-rs/clap/issues/568

**Comment by swiesner-dlr** [comment]
Personally I scarcely use `bat` options, or at least I use options way less frequently than filenames, so I much prefer to complete filenames instead of options.

Could you disable these completions until the upstream error is fixed?

**Comment by sharkdp** [comment]
@swiesner-dlr I agree. Sounds like a good idea to me. We should enable the shell completions for the next release.

**Comment by sharkdp** [comment]
Shell completions are not included in the new release [bat 0.9](https://github.com/sharkdp/bat/releases/tag/v0.9.0).

**Comment by ErinCall** [comment]
I'm still having this issue—I get tab-completion for options, but not for filenames. I'm using bat 0.9.0 (newly installed via homebrew) and I'm using fish 3.0.0 (recently upgraded from 2.7.1 in case an outdated fish version was the problem). I haven't tried building from source; is that worth an attempt?

**Comment by sharkdp** [comment]
Can you please search your filesystem for any remaining `fd.fish` autocompletion files? 

It seems like the brew formula still ships the completion files: https://github.com/Homebrew/homebrew-core/blob/5df9397fb96b3e74b7aca993afa2b620e0db9d44/Formula/bat.rb

I'm afraid this would have to be reported in the homebrew-core repository.

**Comment by maraisr** [comment]
How long would it take for homebrew to pick up the new changes? Ie, at 1807 25/01/2019 I ran a `brew install bat` and am seeing the `bat.fish` completion files.

**Comment by sharkdp** [comment]
I have now completely disabled the generation of the files, so for the next release package maintainers will be "forced" to remove them from the packages.

**Comment by alexbepple** [comment]
If, somehow, you still have the old completions, you can also just add

    complete -c bat -a '(__fish_complete_path)'

to your config and have it all. ;)

**Comment by jonas-schievink** [comment]
@alexbepple Oooh, thanks for this, very handy!

@sharkdp I'm sure you've thought of this already, but another workaround would be to stop using a subcommand and instead:
* Turn `cache` into normal arguments that use dashes, like `bat --init-cache`, `bat --clear-cache`, ...
* Add another small CLI tool *just* for managing the cache, like `bat-cache --init`, ...

Personally I wouldn't expect a tool like `bat` to take a subcommand at all, since it always gets a file argument anyways, and that could collide with the subcommand and cause confusion.

**Comment by sharkdp** [comment]
> @sharkdp I'm sure you've thought of this already, but another workaround would be to stop using a subcommand and instead:

The `cache` subcommand is not the problem here. The argument parser `clap`, which we use, does not support the generation of proper shell completion files even if there would be no subcommand (see my first comment in this issue).

**Comment by sharkdp** [comment]
No shell completion files should be shipped with [v0.10.0](https://github.com/sharkdp/bat/releases/tag/v0.10.0).

**Comment by axelson** [comment]
For anyone watching this 0.10.0 is now out on homebrew and completion now works great! 🎉
