### ISSUE TITLE
mouse signal scrolling (like in less) is not working

### ISSUE THREAD

**Issue by mastern2k3** [sharkdp/bat#373]
when using `less`, less is listening and reacting to mouse scrolling events. those are somehow filtered in bat and it would be nice to have this functionality back.

**Comment by keith-hall** [comment]
this has been discussed before, see the readme for details:
https://github.com/sharkdp/bat#using-a-different-pager

**Comment by mastern2k3** [comment]
I tried adding the `BAT_PAGER` env-var but it didn't work at first,
then noticed i wasn't running the latest version.
upgraded to `8.0` then everything worked!

thanks and keep up the good work!
`<3`
