### ISSUE TITLE
Add SQL syntax highlight

### ISSUE THREAD

**Issue by Mart-Bogdan** [sharkdp/bat#374]
It would be cool to have SQL syntax highlight

**Comment by sharkdp** [comment]
`bat` should already come with SQL syntax highlighting out of the box:
```
> bat --list-languages | grep sql
SQL                                  sql, ddl, dml
SQL (Rails)                          erbsql, sql.erb
```

**Comment by Mart-Bogdan** [comment]
Oh, sorry my bad, perhaps something with my terminal over SSH.

Just checked on Linux laptop, it works.
