### ISSUE TITLE
Compile error on gentoo

### ISSUE THREAD

**Issue by jorants** [sharkdp/bat#378]
When running `cargo install bat` is get a compile error.
The compiler seems to complain about a string comparison between different types of string.
[The log from running with --verbose](https://pastebin.com/TLv2VTKA)

**Comment by sharkdp** [comment]
Unfortunately, you will need Rust 1.29 or higher: https://github.com/sharkdp/bat#from-source

**Comment by jorants** [comment]
Ah, sorry, Ill update :-) Thanx!
