### ISSUE TITLE
WISH: Visualize/highlight different whitespace symbols

### ISSUE THREAD

**Issue by HenrikBengtsson** [sharkdp/bat#381]
It is sometimes useful to be able to see the difference between various whitespace symbols, e.g. space (` `), TAB (`\t`), CR (`\r`), LF (`\n`), BACKSPACE (`\b`), ...  This can be particularly helpful when for instance troubleshooting a tab-delimited file (which e.g. uses spaces instead of TABs).

Visualization of whitespace could be done by using different background colors, e.g. (ignoring themes)

* space - default background
* TAB - red
* BACKSPACE - yellow
* CR - magenta
* LF - blue

**Comment by HenrikBengtsson** [comment]
For anyone else reading this, see comments over at PR #395.

**Comment by sharkdp** [comment]
This is now available in [bat 0.9](https://github.com/sharkdp/bat/releases/tag/v0.9.0).
