### ISSUE TITLE
"Unknown CSI 'm' param 3" when using BAT_PAGER="rager"

### ISSUE THREAD

**Issue by E5ten** [sharkdp/bat#384]
I don't know if I should leave an issue here or on https://github.com/tcr/rager, but when using that as my bat pager and batting certain files like Makefiles the screen fills with that error, but scrolling which puts the errors off the screen replace them with the proper output, so if I scroll down half way and then scroll back up half way there will be half a screen of that error instead of a full one. I checked this in multiple terminals to verify that isn't the issue, and it occured in the others as well.
![image](https://user-images.githubusercontent.com/24554283/47617470-b2d7ae00-da9d-11e8-8b39-29effda64e07.png)
EDIT: it also occurs with rustfiles and maybe just all files that would be coloured, but it does not happen with any files that don't fill the screen, I don't know if bat invokes the pager for those or not so if it doesn't the issue might be with rager.

**Comment by sharkdp** [comment]
Thank you for reporting this.

I don't think this is related to `bat`. It looks like *rager* can not handle interactive text. It shows the same error if you do this:
```bash
echo -e "\e[3mitalic\e[0m" | rager
```

The actual error seems to come from inside the [ransid](https://github.com/redox-os/ransid) library, which is used by rager:

https://github.com/redox-os/ransid/blob/18a50799d01e28e0d74db182c1ed3a77e9f0c1a9/src/lib.rs#L334-L336

**Comment by sharkdp** [comment]
On a related note, I think we should consider disabling italic text by default in `bat`. It doesn't seem to be supported on many terminals. Unfortunately, most of them don't silently ignore the italic-modifiers but paint the text with a background color.

**Comment by sharkdp** [comment]
@E5ten You opened a bug with `rager`. Can this be closed?

**Comment by E5ten** [comment]
Yep, I just didn't close it because you mentioned the possibility of changing the italics default and I didn't know if you wanted to use this issue for that.

**Comment by sharkdp** [comment]
Oh, right. I'll open a new ticket for this. Thanks!
