### ISSUE TITLE
Don't start pager if file doesn't exist

### ISSUE THREAD

**Issue by E5ten** [sharkdp/bat#387]
If bat is called on a file that doesn't exist it opens up an empty pager instance and errors, instead of just erroring, I think it would be better if the pager wasn't opened unless the file exists.

**Comment by sharkdp** [comment]
Thank you for the feedback.

Sounds sensible to me. Potentially, this is a little harder to fix than it might seem.

**Comment by sharkdp** [comment]
Fixed in [v0.10.0](https://github.com/sharkdp/bat/releases/tag/v0.10.0).
