### ISSUE TITLE
Disable use of italics (by default)

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#389]
Disable the use of ANSI-italics by default, but add a new option `--enable-italics` that users can put in their config file, if they want to opt-in.

Rationale:
- A lot of terminals struggle with italics and output weird colors instead of using italic text (see #130, for example).
- Some pagers do not support italics: #384

**Comment by Ashniu123** [comment]
I'll take this.

**Comment by chaucerbao** [comment]
It looks like #96 was the PR that added font styles.

**Comment by sharkdp** [comment]
Closed via #390 by @Ashniu123.

**Comment by sharkdp** [comment]
This is now available in [bat 0.9](https://github.com/sharkdp/bat/releases/tag/v0.9.0).
