### ISSUE TITLE
Asciidoc support.

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [sharkdp/bat#406]
![image](https://user-images.githubusercontent.com/28439285/48115774-43637a80-e264-11e8-99c6-0645692000ad.png)

Posted above is the screenshot from `vim` with appropriate syntax highlighting.

Posted below is the `bat` screenshot.

![image](https://user-images.githubusercontent.com/28439285/48115827-6b52de00-e264-11e8-80f7-3b36dab0df80.png)

**Comment by sharkdp** [comment]
Okay, sounds good to me.

Seems like we need to add one of these two packages:

- https://packagecontrol.io/packages/Asciidoctor
- https://packagecontrol.io/packages/AsciiDoc
