### ISSUE TITLE
Heads-up: a FreeBSD port of bat is on its way

### ISSUE THREAD

**Issue by 0mp** [sharkdp/bat#41]
Hello! 

I just wanted to point out that bat is on its way be included in the [FreeBSD ports collection](https://www.freshports.org/) (pending [PR][1]). At the moment [the problem is with the dictionaries dependency][2].

Cheers and happy hacking!

[1]: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227931 
[2]: https://github.com/soc/directories-rs/issues/25

**Comment by sharkdp** [comment]
Awesome! Thank you very much :+1:

**Comment by 0mp** [comment]
👍 I'll do some testing once a new release is tagged.

**Comment by 0mp** [comment]
FYI directories 0.10.0 has landed.

**Comment by 0mp** [comment]
Now we're waiting for libc 0.2.41 as it claims to solve a compilation error I encounter: https://github.com/jwilm/alacritty/issues/1247
