### ISSUE TITLE
Latest brew release outputs escaped color-codes for all files

### ISSUE THREAD

**Issue by hkjels** [sharkdp/bat#411]
<img width="943" alt="skjermbilde 2018-11-12 kl 14 11 27" src="https://user-images.githubusercontent.com/339547/48349572-e2351000-e684-11e8-82df-33ba1aece049.png">

**Comment by sharkdp** [comment]
Thank you for the feedback.

What is the "latest brew release"? bat 0.9? And everything worked fine with 0.8?

Which terminal emulator do you use? Which pager?

**Comment by hkjels** [comment]
It was a problem with `PAGER` apparently; I don't think I've changed that for quite a while, so `bat` has possibly been more forgiving at some point.
My pager was set to `less -XFSiw`

**Comment by hkjels** [comment]
OK, so looking at this again I can see that setting the `PAGER` to anything other than `less` will make it fail, so I'm now pretty sure that this is a bug

**Comment by sharkdp** [comment]
You need to pass the `-R` option to `less`. Otherwise, it will not interpret ANSI sequences. (see https://github.com/sharkdp/bat#using-a-different-pager in the README)
