### ISSUE TITLE
English to Japanese Translation

### ISSUE THREAD

**Issue by sh-tech** [sharkdp/bat#412]
I am a Japanese student.
Two months ago, I met bat, which is the best open source software. I also patronize it now.
I would like to convey this merit to other Japanese people. So, would you please let me make a Japanese translation of README.md?
I will fork the repository and send a pull request.

**Comment by sharkdp** [comment]
> So, would you please let me make a Japanese translation of README.md?

Of course, sounds great! You don't need to ask for permission to do that :smile:
