### ISSUE TITLE
Cygwin Path Interference

### ISSUE THREAD

**Issue by Astrantia** [sharkdp/bat#413]
Hi. Bat works just fine without Cygwin being in path on windows 10. When Cygwin binaries get added to path, bat highlighting breaks. I was thinking cat from Cygwin interfered with it, but deleting it didn't fix highlighting issues. This can be reproduced all the time just by adding Cygwin/bin into path.

![image](https://user-images.githubusercontent.com/32885386/48448138-10d9e600-e76c-11e8-9da8-b02b9eeacde4.png)

**Comment by sharkdp** [comment]
What is the `less` version that is shipped with Cygwin? Does it work with `--paging=never`?

**Comment by Astrantia** [comment]
@sharkdp 
```
less -V
less 530 (POSIX regular expressions)
Copyright (C) 1984-2017  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```
and
```
less --paging=never
There is no paging=never option ("less --help" for help)
Missing filename ("less --help" for help)
```

**Comment by Astrantia** [comment]
@sharkdp tested by deleting less from Cygwin, it's because of less. Do you see any way to make this easier for the user?

**Comment by sharkdp** [comment]
`--paging=never` is a command-line option for `bat`. It disables the use of a pager (like `less`).

You shouldn't need to deactivate `less` somehow. Did you set the `PAGER` or `BAT_PAGER` environment variables? What is their value? Can you try to set `BAT_PAGER=less` and see if that works?
