### ISSUE TITLE
Should not automatically add \n when using --plain

### ISSUE THREAD

**Issue by teresaejunior** [sharkdp/bat#434]
https://github.com/sharkdp/bat/pull/300 ads a newline character to the output to avoid issues with the grid, which is understandable. But when using `bat --plain`, I would expect it to behave like `cat`, that is, if there is no newline at the end, I need to know it.

If the file is broken, it shouldn't be bat's job to fix it (some shells will deal with the annoyances of the output beautifully, like fish, which puts a ⏎ at the end of the output to show there is no newline, instead of leaving a broken prompt).

**Comment by teresaejunior** [comment]
I have compiled a version of bat removing the code introduced in https://github.com/sharkdp/bat/pull/300, and it doesn't seem to make any difference. Also, there is the fact that `less` also guarantees a newline at the end of files, so this is not much worth pursuing.

**Comment by sharkdp** [comment]
Thank you for the feedback. I do agree with your opinions and conclusions.

As a side-comment: note that you can use `bat --show-all` to check if there is a line-feed at the end of the file.

For example, compare:
```
▶ echo "test" | bat -A   
───────┬────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────
   1   │ test␊
───────┴────────────────────────────────────────────────────────────

~                                                                  
▶ echo -n "test" | bat -A
───────┬────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────
   1   │ test
───────┴────────────────────────────────────────────────────────────

```

**Comment by teresaejunior** [comment]
That is very useful indeed, thanks!
