### ISSUE TITLE
.sc files should be treated as scala files

### ISSUE THREAD

**Issue by benwaffle** [sharkdp/bat#443]
These are either [scala worksheet](https://github.com/scala-ide/scala-worksheet/wiki/Getting-Started) files or [ammonite script files](https://ammonite.io/#import$file) 

>Scala worksheets are normal Scala files, except that theythey end in .sc instead of .scala.

(and when I say treated I specifically mean syntax highlighted; not sure if anything else changes based on the file type)

**Comment by benwaffle** [comment]
Thanks! https://github.com/sublimehq/Packages/pull/1801

Do you want to close this PR, or wait for the sublime PR to be merged and for bat to update its sublime files?

**Comment by sharkdp** [comment]
I will automatically keep up to date with sublimehq/Packages, so I think we can close this. Thank you!

**Comment by benwaffle** [comment]
https://github.com/sublimehq/Packages/pull/1801 has been merged, so the `Packages` submodule needs to be updated, right?

**Comment by sharkdp** [comment]
@benwaffle Yes, thank you for the reminder. I will do that prior to the next release of `bat`

**Comment by benwaffle** [comment]
Could you please update the submodule?

**Comment by sharkdp** [comment]
Unfortunately, this is blocked by #499. Maybe I should reopen it after all.

**Comment by sharkdp** [comment]
This has been fixed in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).
