### ISSUE TITLE
Line numbers are too dark

### ISSUE THREAD

**Issue by Yanpas** [sharkdp/bat#446]
It seems that it doesn't depend on --theme. Using default kde color scheme in terminal:
![image](https://user-images.githubusercontent.com/7345761/49865299-a7560180-fe15-11e8-9924-3516d4b2d4a5.png)

**Comment by sharkdp** [comment]
There is a dedicated section in the README for this: https://github.com/sharkdp/bat#line-numbers-and-grid-are-hardly-visible

see also: #339
