### ISSUE TITLE
bat init-cache failed

### ISSUE THREAD

**Issue by D3Hunter** [sharkdp/bat#45]
i've followed steps from `readme`, but got this:
```
➜   bat init-cache
[bat error]: Could not load themes from '/Users/xxxxx/Library/Preferences/bat/themes'
```
i thought it maybe writing in `linux` context, so i copied files from `~/.config/bat` into `~/Library/Preferences/bat/`, still not working.

**Comment by sharkdp** [comment]
Oh - the instructions in the README are Linux-specific right now, true.

I would actually hope that
```
mkdir -p ~/Library/Preferences/bat/
cd ~/Library/Preferences/bat/

# Download a theme, for example:
git clone https://github.com/jonschlinkert/sublime-monokai-extended

# Create a 'Default.tmTheme' link
ln -s "sublime-monokai-extended/Monokai Extended.tmTheme" Default.tmTheme
```
would work for you?

**Comment by D3Hunter** [comment]
works now, but the directory should be `~/Library/Preferences/bat/themes`

BTW, it would be really great to have `bat` output to a pager like `less` directly, i don't want to write `|less` every time.

**Comment by sharkdp** [comment]
> works now, but the directory should be ~/Library/Preferences/bat/themes

Ah, right. Thank you. I'll update the README to include the macOS-specific changes.

> BTW, it would be really great to have bat output to a pager like less directly, i don't want to write |less every time.

See #29
