### ISSUE TITLE
Show Differences from Previous Version if in a Git Repository

### ISSUE THREAD

**Issue by jetzerb** [sharkdp/bat#452]
Continued discussion from #440 regarding `bat` showing diff chunks.

Currently, inside of a git repo, `bat` will compare the file being viewed with the previous version and decorate the left-hand gutter with
- Green `+` to indicate that the line has been added
- Red `-` to indicate that one or more lines have been removed
- Yellow `~` to indicate that the line has changed

This feature request asks that `bat` go a step further by inserting the block of old lines into the output:
- Where lines have been added, no change is necessary; they are decorated with a green `+`
- Where lines have been removed, display the old lines in a monochrome color (gray?) decorated with a red `-`
- Where lines have been changed,
   - display the old lines in a monochrome color (gray?) decorated with a red `-`
   - decorate the replacement/current lines with a green `+`

A couple additional things that would be nice to have:
- The ability to specify a commit ID to _diff against_, rather than only "the previous commit for this file"
- The ability to specify a commit ID to _view_, rather than the current version of the file
- Where the old lines are displayed in monochrome, highlight the differences in some way, similar to how [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) does:
![image](https://user-images.githubusercontent.com/36859020/50034034-a4e3db00-ffc0-11e8-8041-c0ceed2ab4f2.png)

**Comment by sharkdp** [comment]
It's been a long time, but I believe I still stand by my original statement in the linked ticket:

> I am not planning to turn bat into a full-blown diff or git diff alternative. That's simply too far from its original goal. There is also a huge difference in complexity between showing the git-modification markers and showing an actual diff.

In this spirit, I'd like to close the ticket - but I'm happy to re-open this if there should be new ideas / opinions / developments in the future.

@jetzerb: thank you very much for taking the time to describe this in detail.
