### ISSUE TITLE
Regex "beginning of line" interpretation

### ISSUE THREAD

**Issue by jetzerb** [sharkdp/bat#456]
When using `less` as `bat`'s pager, searching with a regex involving the "beginning of the line" is problematic.  Bat renders the file with line numbers and gutter on the left-hand side.  So "beginning of the line" is always zero or more spaces followed by a number.

Here's a demonstration:
```sh
$ /usr/bin/less -N <<EOF
Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.
EOF
```
Searching for `^sed` results in this:
![image](https://user-images.githubusercontent.com/36859020/50249700-61181980-03a4-11e9-8bb3-69e5efb4c927.png)

Attempting the same with `bat`:
```sh
$ /usr/bin/bat --paging always <<EOF
Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.
EOF
```
Searching for `^sed` here yields
![image](https://user-images.githubusercontent.com/36859020/50249836-c79d3780-03a4-11e9-8251-43e22658581c.png)

You can see that the line numbers are part of the output that is fed to the pager by searching for `^  *3`:
![image](https://user-images.githubusercontent.com/36859020/50249959-24005700-03a5-11e9-9411-849f75fe6e92.png)

## Workarounds
I can either
- use `bat --style=plain` so there are no line numbers or changes shown (but then I don't get line numbers or indicator of changes)
- copy the vertical line character in the left-hand gutter (which is _not_ a pipe character `|`), and search for that followed by a space followed by the text I'm looking for.  In this case:
![image](https://user-images.githubusercontent.com/36859020/50250165-adb02480-03a5-11e9-968c-b2ee96263363.png) which finds the text:
![image](https://user-images.githubusercontent.com/36859020/50250183-bf91c780-03a5-11e9-808b-95b96962de3a.png)

I can live with these workarounds.  Just wondering if there's any magic I'm not aware of that would cause the pager to search only the contents of the file, and ignore text inserted by `bat`.

**Comment by sharkdp** [comment]
Thank you for the detailed report.

This is unfortunate, but I don't think there is a good way to circumvent this (apart from the workarounds you mentioned).

**Comment by sharkdp** [comment]
I'm going to close this as "won't fix", but I'm happy to re-open this if somebody has a good idea on how to solve this.

**Comment by robbat2** [comment]
@sharkdp as to ideas on how to solve this, here's some suggestions that come to mind:
1. evaluate the regex, e.g. `^` only on the RHS of the gutter
2. evaluate the regex, e.g `^` twice, once  on the LHS of the gutter AND once on the RHS of the gutter
3. Silently transform `^` to cover the gutter, `s/^/^\s+[0-9]+\s+│/g`

My personal preference would be option 1, but I can see users who might want option 2.

**Comment by sharkdp** [comment]
> @sharkdp as to ideas on how to solve this, here's some suggestions that come to mind:
> 
>     1. evaluate the regex, e.g. `^` only on the RHS of the gutter
> 
>     2. evaluate the regex, e.g `^` twice, once  on the LHS of the gutter AND once on the RHS of the gutter
> 
>     3. Silently transform `^` to cover the gutter, `s/^/^\s+[0-9]+\s+│/g`
> 
> 
> My personal preference would be option 1, but I can see users who might want option 2.

All of this happens in `less`. `bat` has long since finished its job if a user is using the searching-functionality of the pager. This cannot be done in `bat`.

**Comment by bAndie91** [comment]
my suggestion is
- add option to remove style-components, eg `--style full,!numbers`
- add padding as a style-component
- add left grid as a separate style-component
- call `LESS="$LESS -N" bat --style auto,!numbers,!leftgrid,!leftpad`
- ignore that less numbers the header too

**Comment by robbat2** [comment]
Anybody else reading this, check out the `less` issue; which recently got a solution that will be available in the next release of `less`, and usable via `BAT_PAGER`.
