### ISSUE TITLE
Bat requires glibc 2.18 - CentOS 7 only offers glibc 2.17

### ISSUE THREAD

**Issue by jm-pro** [sharkdp/bat#46]
On CentOS 7.4.1708, when trying to run bat, there is a GLIBC version problem error

_/lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./bat)_

CentOS 7 only offers glibc 2.17

**Comment by sharkdp** [comment]
Fixed in v0.2.3.

**Comment by eddelbuettel** [comment]
I just ran into this too at work :-/

CentOS Linux release 7.3.1611 (Core)
bat 0.6.1 from the releases page

Any idea?

**Comment by sharkdp** [comment]
@eddelbuettel Please use the statically linked version of `bat` that uses musl instead of libc (the `*-musl*` tarballs/deb-packages).
