### ISSUE TITLE
No syntax highlighting for zprofile

### ISSUE THREAD

**Issue by vanniktech** [sharkdp/bat#465]
`bat ~/.zshrc` gives me syntax highlighting. `bat ~/.zprofile` does not.

Is it possible to also use Bash/Shell syntax highlighting for zprofile files?

**Comment by sharkdp** [comment]
That would have to be included in https://github.com/sublimehq/Packages

An alternative is to add `--map-syntax .zprofile:zsh` to your config file (see README).

**Comment by vanniktech** [comment]
Can we make a PR against that package?

**Comment by sharkdp** [comment]
You certainly can, but I'm not affiliated with this project. I can't tell anything about the chances of success of getting this merged, but we already had a few `bat`-inspired PRs that were merged.

**Comment by sharkdp** [comment]
I'm going to close this, as there is nothing that we can do here now. I'll keep sublimehq/Packages up to date anyway, should it be included upstream.

**Comment by vanniktech** [comment]
@sharkdp just letting you know that this was merged
