### ISSUE TITLE
Fedora package doesn't exist

### ISSUE THREAD

**Issue by gombosg** [sharkdp/bat#475]
`dnf install bat` is not working, I can't find the package in DNF or at https://apps.fedoraproject.org/packages.

It exists in some COPR (~Ubuntu PPA) repos, but those are unofficial and presumably not properly maintained.
Are you sure that there is a Fedora package?

**Comment by sharkdp** [comment]
Thank you for reporting this.

My information was based on this comment by @drahnr: https://github.com/sharkdp/bat/issues/317#issuecomment-443132331

But I agree with you. It looks like this information was wrong. I can't find any details about an official `bat` package. repology.org also says that there is no Fedora package: https://repology.org/metapackage/bat/versions

I *did* find [this repository](https://src.fedoraproject.org/rpms/rust-bat) by @ignatenkobrain, but I don't really know if that has any official status.


Maybe either @drahnr or @ignatenkobrain can help out here?

**Comment by sharkdp** [comment]
There is also this: https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Modular/source/tree/Packages/r/

which looks like `bat` is included in the development version of Fedora (rawhide)?

**Comment by ignatenkobrain** [comment]
In the Modular fedora repositories it exists for all fedora versions.

Which version you have and also which repositories you have enabled?

**Comment by drahnr** [comment]
```
dnf install fedora-repos-modular
```
is required.
`bat` is part of it https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2018-7adb944875

For more details on fedora modular, please read https://docs.fedoraproject.org/en-US/modularity/using-modules/

**Comment by gombosg** [comment]
@ignatenkobrain @drahnr I use F29 workstation, so it's a regular edition.
Thanks for the responses, but this seems non-trivial for me.

I heard about Modularity, and read the [explanation](https://docs.fedoraproject.org/en-US/modularity/) (emphasis mine):
> Modularity introduces a new optional repository to Fedora called Modular [...] that ships _additional_ versions of _software on independent life cycles_.

So I thought this repo is totally optional if I want to use just the base distro version of some software. This is the first occasion that I find something exclusively in that repo.

Why isn't it in the official repos? It has 1 main version (not mixed LTSes like `node` or `postgres` or whatever) and Koji builds it anyway. Is there some particular reason for it or is it just still under review?

Modular repos are only enabled by default in the Server edition.

**Comment by ignatenkobrain** [comment]
Modular repos are enabled by default everywhere in F29 I believe.

The reason for that is thatkeeping rust stuff up2date in released Fedora is nearly impossible so we build module which internally builds a lot of crates with their latest versions (but they don't get shipped to users).

**Comment by gombosg** [comment]
In the meantime, here's the F29 RPM file.

[pulseaudio-module-bluetooth-aptx-12.2-1.fc29.x86_64.zip](https://github.com/sharkdp/bat/files/2788465/pulseaudio-module-bluetooth-aptx-12.2-1.fc29.x86_64.zip)

**Comment by sharkdp** [comment]
Is there anything that we can do here (should something be added to the README) or is this a Fedora-related problem?

**Comment by gombosg** [comment]
It's Fedora related, and @ignatenkobrain can help us out with exact installation instructions that can be added to the README.

**Comment by drahnr** [comment]
To not taint my test with any local modifications, I used a docker image:

```
$ docker run -it fedora:29 bash
Unable to find image 'fedora:29' locally
Trying to pull repository docker.io/library/fedora ... 
sha256:7b921a4a008ee83c06d2cde9f21d3aa8de4635b0c4ec159f31caee83ad220b21: Pulling from docker.io/library/fedora
0be2a68855d7: Pull complete 
Digest: sha256:7b921a4a008ee83c06d2cde9f21d3aa8de4635b0c4ec159f31caee83ad220b21
Status: Downloaded newer image for docker.io/fedora:29
[root@7e275fdbf604 /]# dnf module install bat
Fedora Modular 29 - x86_64                                                                                                                   519 kB/s | 1.5 MB     00:02    
Fedora Modular 29 - x86_64 - Updates                                                                                                         665 kB/s | 2.0 MB     00:03    
Fedora 29 - x86_64 - Updates                                                                                                                 4.9 MB/s |  20 MB     00:04    
Fedora 29 - x86_64                                                                                                                           4.3 MB/s |  62 MB     00:14    
Dependencies resolved.
=============================================================================================================================================================================
 Package                              Arch                            Version                                                 Repository                                Size
=============================================================================================================================================================================
Installing group/module packages:
 bat                                  x86_64                          0.8.0-1.module_2418+43cef932                            updates-modular                          1.4 M
Installing dependencies:
 libgit2                              x86_64                          0.27.4-1.module_2222+9bfbc8d7                           fedora-modular                           412 k
 http-parser                          x86_64                          2.9.0-1.fc29                                            updates                                   35 k
 oniguruma                            x86_64                          6.9.1-1.fc29                                            updates                                  188 k
 libssh2                              x86_64                          1.8.0-8.fc29                                            fedora                                    86 k
Installing module profiles:
 bat/default                                                                                                                                                                
Enabling module streams:
 bat                                                                  latest                                                                                                
 libgit2                                                              0.27                                                                                                  

Transaction Summary
=============================================================================================================================================================================
Install  5 Packages

Total download size: 2.1 M
Installed size: 5.8 M
Is this ok [y/N]: y
```

Not sure if there is any more to add here, to me this looks a like a specific system issue.

**Comment by drahnr** [comment]
@sharkdp I think my other comment was not wrong, since once you install it (untested), it might alter the meta information, so a `dnf install bat` might work on the a re-install attempt. My zsh history agrees with that but I did not verify it within the docker container.

**Comment by gombosg** [comment]
Can be closed now.
