### ISSUE TITLE
Syntax highlighting for JSON

### ISSUE THREAD

**Issue by avdv** [sharkdp/bat#48]
I am using version 0.2.2 on Linux and apparently `bat` does not colorize `.json` files.

**Comment by fpietka** [comment]
Are you sure that is the case?

I mean, I tried and thought the same. But when I open json in Sublime, curly braces and brackets are white and the text is a light grey. I took a close look and it is working the same way with `bat`.

Open that helps

**Comment by sharkdp** [comment]
> Why not use the same highlighting for JSON, being a subset of ECMAScript anyway?

Not sure if this is the only reason, but you might want to highlight syntax-errors in a particular way.

If you really want this, you can use `bat --language javascript ..` starting with the next version.

> So, basically this is a bad color scheme...

It could also be the combination of color scheme and language definition.

If anybody knows how to improve this, I'd be glad to know.

**Comment by sharkdp** [comment]
This really depends on the syntax highlighting theme. The next version of `bat` will ship with a few themes to choose from. Here is `TwoDark`, for example:

![image](https://user-images.githubusercontent.com/4209276/40266288-9e1c5b02-5b48-11e8-96ef-20052f5ba981.png)

**Comment by jcousins-ynap** [comment]
Was this language definition shipped?
JSON files do not seem to be highlighted in `0.12.1`.

**Comment by sharkdp** [comment]
As described above, the JSON syntax was always shipped. It's just the highlighting theme that causes problems. Please try a different one. If there are remaining problems, please open a new ticket.

**Comment by Hugoo** [comment]
Maybe [`jq`](https://jqlang.org/) is a better alternative for pure json files.
