### ISSUE TITLE
feature request: support for fish syntax

### ISSUE THREAD

**Issue by sanga** [sharkdp/bat#484]
Would you be amenable to accepting a separate highlighter for fish? Currently bat is using the bash syntax highlighter for fish files - whilst this is close, bash and fish do have different syntaxes. As to usage stats, I'd imagine (but I have no actually evidence of this) that fish is the 3rd most popular shell behind bash and zsh and that it's in pretty wide use. There's a sublime package for it that has about 8K installations. I could make a PR, but I thought I'd ask first

**Comment by sharkdp** [comment]
Sounds good to me. We'd have to make sure that the `fish` syntax always has a higher precedence than the Packages/Shell syntax.

**Comment by sharkdp** [comment]
Looks like the upstream issue has been resolved, actually. Might be worth to try this by just adding the syntax.
