### ISSUE TITLE
Add tomorrow night bright theme

### ISSUE THREAD

**Issue by luisdavim** [sharkdp/bat#486]
Hi,

would it be possible for you to add the tomorrow night bright theme?
https://github.com/chriskempson/tomorrow-theme

Thanks.

**Comment by sharkdp** [comment]
Have you seen https://github.com/sharkdp/bat#adding-new-themes ?

**Comment by sharkdp** [comment]
> Should I open a PR?

The link to the README shows a way to add themes without adding it to this repository.
