### ISSUE TITLE
"Did you mean --init" error prompted after bat cache --init

### ISSUE THREAD

**Issue by alichtman** [sharkdp/bat#494]
```zsh
➜ bat cache --init                                                                                                                            
error: Found argument '--init' which wasn't expected, or isn't valid in this context
        Did you mean to put '--init' after the subcommand 'cache'?

USAGE:
    bat --theme <theme>

For more information try --help
```

OS: macOS Mojave 10.14.1
Installed through HomeBrew

```
➜ brew info bat                                                                                                                               📦 v1.1.7 with ⬢ v11.9.0 at 7:15AM 
bat: stable 0.9.0 (bottled)
Clone of cat(1) with syntax highlighting and Git integration
https://github.com/sharkdp/bat
/usr/local/Cellar/bat/0.9.0_1 (9 files, 5.5MB) *
  Poured from bottle on 2019-02-03 at 09:38:19
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bat.rb
==> Dependencies
Build: rust ✘
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 11,582 (30 days), 26,041 (90 days), 74,443 (365 days)
install_on_request: 11,553 (30 days), 25,986 (90 days), 74,335 (365 days)
build_error: 0 (30 days)
```

**Comment by sharkdp** [comment]
Is it possible that you aliased `bat` to something like `bat --theme=".."` or similar? This is discouraged as it causes problems when using the `cache` subcommand because you are actually calling
```
bat --theme ".." cache --init
```
which causes the above error message.

Instead of using an alias, you can configure the color theme in `bat`s config file or use a environment variable (see README)

**Comment by alichtman** [comment]
> Is it possible that you aliased bat to something like bat --theme=".." or similar?

Yes, I did have an alias like that. I've used that alias for a while, so it must have been the most recent release that this broke in. I've updated to using the environment variable theme configuration, and this seems to be fixed. 

Resolved.

**Comment by sharkdp** [comment]
> Yes, I did have an alias like that. I've used that alias for a while, so it must have been the most recent release that this broke in. I've updated to using the environment variable theme configuration, and this seems to be fixed.

Hm, bat 0.6.0 also shows this behavior, so your previous version must have been quite old. Using `--theme ".."` only causes problems when using the `cache` subcommand. It's fine otherwise.

> By the way, `bat` quickly became one of my most used tools. This is an awesome project. Thanks for building this.

Very glad to hear this!!
