### ISSUE TITLE
$ bat cache --config-dir is invalid, yet it's listed as an option

### ISSUE THREAD

**Issue by alichtman** [sharkdp/bat#496]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/20600565/52211070-60e9b580-284e-11e9-9f36-c40e95b81d81.png">

**Comment by alichtman** [comment]
I've confirmed this is not related to the aliasing problem that #494 was caused by.

**Comment by sharkdp** [comment]
Can you please show the output of
```
\bat --version
\bat cache --config-dir
```

**Comment by alichtman** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/20600565/52242479-6968dd00-289c-11e9-9073-cf6ed9d80bcb.png">

**Comment by sharkdp** [comment]
That looks like expected behavior.

`bat cache --config-dir` is supposed to print the path where the `bat` configuration would be read from (if it exists).

`bat cache --init` will store the cache-files in the *cache* folder, not the config folder.

**Comment by alichtman** [comment]
Oh. Right, sorry. Sleep deprived debugging is hard...

The config dir should exist though, right? Or do we need to create it manually?

**Comment by sharkdp** [comment]
It needs to be created manually, see https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions
