### ISSUE TITLE
Can not update sublimehq/Packages to the latest state

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#499]
When updating the `assets/syntaxes/Packages` submodule to the latest state, calling `assets/create.sh` fails with:

```
[..] assets/syntaxes/Packages/Go/Go.sublime-syntax: Invalid YAML file syntax
```

This is probably an upstream problem (either in sublimehq/Packages or syntect). Any help is greatly appreciated.

**Comment by keith-hall** [comment]
related: https://github.com/chyh1990/yaml-rust/issues/118

**Comment by moritzdietz** [comment]
Based from what I can read is that this issue has been closed as it has been fixed and the change is already pushed to master. I don't know whether you will want/have to wait for a release that includes this fix or just grab the latest master branch.

**Comment by sharkdp** [comment]
Related: https://github.com/trishume/syntect/issues/228

**Comment by sharkdp** [comment]
There is no sense in tracking this here. I will keep an eye on the upstream repository anyways.

**Comment by sharkdp** [comment]
Reopened due to #443.

**Comment by benwaffle** [comment]
Should be fixed with https://github.com/sublimehq/Packages/pull/1897
