### ISSUE TITLE
publish package to debian repositories

### ISSUE THREAD

**Issue by phra** [sharkdp/bat#50]
it would be nice to have `bat` as a regular debian package so that we can install it via `apt`.

**Comment by sharkdp** [comment]
Yes - this would be great, but it's really hard. I have looked into this several times for [fd](https://github.com/sharkdp/fd), but I'm still not sure how to achieve this.

**Comment by csonuryilmaz** [comment]
@sharkdp Are you planning to put **32bit** (x86) deb package into [releases](https://github.com/sharkdp/bat/releases) page?

**Comment by sharkdp** [comment]
@csonuryilmaz Could you please open a new ticket for your request?

**Comment by csonuryilmaz** [comment]
I opened issue as #84 . Thanks for your interest @sharkdp

**Comment by ecksun** [comment]
As [fd](https://github.com/sharkdp/fd#user-content-on-debian) is now installable on debian could you consider reopening this issue?

**Comment by sharkdp** [comment]
@ecksun Yes, of course. But there is not too much we can do here (in this repo) to help with the process - except for maybe channeling the discussion.

**Comment by sharkdp** [comment]
Relevant: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907080

**Comment by ecksun** [comment]
> @ecksun Yes, of course. But there is not too much we can do here (in this repo) to help with the process - except for maybe channeling the discussion.

Ah, that is a good point. Thank you for the link to the debian bug tracker anyway :)

**Comment by Teay1985** [comment]
isue

**Comment by sharkdp** [comment]
I'm closing this, as `bat` is now in Debian unstable, see #323
