### ISSUE TITLE
A shell script named `build`

### ISSUE THREAD

**Issue by jzinn** [sharkdp/bat#501]
Bat does not highlight a shell script with the file name `build` that contains a shebang line of `#!/bin/bash`.

Bat does highlight other shell scripts that lack a `.sh` extension, like `run`, `setup`, etc.

I suspect bat considers a file named `build` to be an NAnt build file.

Would it be possible to change the precedence so that bat will interpret my `build` script as a shell script?

**Comment by sharkdp** [comment]
> Bat does highlight other shell scripts that lack a `.sh` extension, like `run`, `setup`, etc.
> 
> I suspect bat considers a file named `build` to be an NAnt build file.

Yes, you are right. That's unfortunate.

> Would it be possible to change the precedence so that bat will interpret my `build` script as a shell script?

Yes. You can add this to your config file:
```
--max-syntax build:bash
```

If you just want that behavior temporarily, you can always just use `-l`/`--language`:
```
bat build -lsh
```

**Comment by jzinn** [comment]
Oh snap, that works.  (With `--map-syntax`.)  Thanks.

I thought it would require a code change to get bat to look for shebangs in files without extensions before using the filename to determine the syntax.
