### ISSUE TITLE
Upgrade to 0.10.0 issue: "(eval):1: command not found: _bat"

### ISSUE THREAD

**Issue by joeycozza** [sharkdp/bat#503]
After doing a `brew upgrade bat` to get version 0.10.0, when I try to tab complete a filename, I get the error output "(eval):1: command not found: _bat" (and it prints 3 times)

Using:
Mac OSX
iTerm2 3.2.7
zsh 5.3 (x86_64-apple-darwin18.0)
bat 0.10.0

I'm not sure how to debug this further, any input or guidance would be appreciated

**Comment by sharkdp** [comment]
Thank you for the feedback.

There shouldn't be any shell completion files for bat 0.10 (see release notes). Maybe you just have to restart your terminal? If that doesn't help, could you please check if there is a `_bat` shell completion file left somewhere on your system?

**Comment by lavifb** [comment]
I had the same problem. I believe the issue is that the completion file is cached by zsh but then it cannot find it. Try checking in `~/.zcompdump` and delete the line with `_bat`. That worked for me. (You may also need to delete the compiled version `~/.zcompdump.cmp`)

**Comment by dashmug** [comment]
I had this problem as well and @lavifb's comment above helped.

**Comment by joeycozza** [comment]
Thanks @lavifb That worked for me.

**Comment by nshtg** [comment]
For me the bug is still present even after purging the `.zcompdump` files.

**Comment by garymh** [comment]
Same, unfortunately 🙁 - deleted the .zcompdump file and just the line with `_bat` and neither worked.

**Comment by dashmug** [comment]
@nshtg 	@garymh You're supposed to restart your shell after deleting.

**Comment by lavifb** [comment]
Make sure to restart your shell after deleting the files. Also make sure you have the latest version of bat. 

If the problem persists could you tell us your OS, zsh, versions as above along with how you installed/upgraded bat? That way we can better help troubleshoot your issue.

**Comment by nshtg** [comment]
@lavifb 
I did restart the shell ofc.

```
OS: MacOS Mojave
ZSH: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
```

`bat` was installed using homebrew.

**Comment by garymh** [comment]
Restarted the shell as well. I have the exact same setup as @nshtg actually. Maybe its homebrew related?

**Comment by lavifb** [comment]
Well I also used homebrew and I would guess most Mac users also do too. My guess it has something to do with any zsh frameworks you might be using. Either it is setting a different file from `~/.zcompdump` and `~/.zcompdump.cmp`. You should check out your `.zshrc` or other config files for `compinit -d <dumpfile>`. You may also want to try reseting whatever zsh framework you are using if you are using one.

**Comment by kud** [comment]
https://github.com/sharkdp/bat/issues/503#issuecomment-462172417 works! Cheers!

**Comment by sepehr** [comment]
Homebrew installation, no `~/.zcompdump` entry, restarted shell, tried `brew reinstall bat` still problematic.

**Comment by sharkdp** [comment]
What about this:

> You may also need to delete the compiled version ~/.zcompdump.cmp

**Comment by sepehr** [comment]
Sorry, forgot to mention, yeah to no avail.

**Comment by sharkdp** [comment]
Maybe this comment https://github.com/sharkdp/bat/issues/503#issuecomment-469044789 by @lavifb can help.

You could try to search your home folder for files containing `_bat`. With `rg` or `ag`:
```
rg -u '\b_bat\b' ~
ag -u '\b_bat\b' ~
```

**Comment by sepehr** [comment]
> _"Maybe this comment #503 (comment) by @lavifb can help."_

Read it, yet had no luck figuring out where to look 😥

> _"You could try to search your home"_

I'm only finding these github notification emails and well, few mp3 files! :)) 

Appreciate your help anyway.

**Comment by sharkdp** [comment]
> > _"You could try to search your home"_
> 
> I'm only finding these github notification emails and well, few mp3 files! :))

then maybe search root? that error message has to come from somewhere :smile:

**Comment by sepehr** [comment]
> _"then maybe search root? that error message has to come from somewhere"_
In progress.

**Comment by sepehr** [comment]
Huh! 

```
/usr/local/opt/zplug/.zcompdump
``` 

Guess because zplug was homebrew-installed. Really appreciate the help.

**Comment by luhmann** [comment]
For me it was

```
# not a dotfile
/usr/local/opt/zplug/zcompdump
```

that had the offending entry. Thanks for all of your help!

**Comment by Zeta611** [comment]
It was `~/.zplug/zcompdump` for me!

**Comment by vadim-cherepanov** [comment]
I've been having the same problem on Debian Linux for years, but with `nano`, when pressing `Tab` after typing `nano` with or without additional parameters would cause familiar:

```
(eval):1: command not found: _nano
```

Finally, I found the answer here for a different command! Decided to write it down, because otherwise searching on Google for "command not found: _nano" is absolutely useless -- maybe it will pick up this thread for "nano" as well.

Also, for reference, in general, the answer would be to search for all "zcompdump" files you may have anywhere, depending on your installation. So, do something like this:

``` sh
find / -regex '.*/\.?zcompdump$' 2>/dev/null 
```

Then check everything it returns, and try to delete or (safe!) rename them and start a new shell to check if the problem is solved.  In my case, this results in

```
/home/user/.zplug/zcompdump
/home/user/.zcompdump
```

and the offensive one was `~/.zplug/zcompdump`. Special thanks to @lavifb and @sepehr!

**Comment by Xmetalfanx** [comment]
same issues here .... tried @lavifb 's solution (I commented it out over deleting it) but it still fixed it here, in 2025 with the newest bat version
