### ISSUE TITLE
Is a Chocolatey package interesting?

### ISSUE THREAD

**Issue by ErichDonGubler** [sharkdp/bat#505]
I'd be more than happy to create an automatically updating Chocolatey package to hand off to whoever wants it -- is that interesting at all? I use Chocolatey to automate my own workflow right now, and this is a slick tool I'd love to add to my automatic toolbelt. :)

**Comment by sharkdp** [comment]
Absolutely - I'm always happy if there are people who are willing to create new packaging options. Once a package is available, we can add installation instructions to the README.

Please note, however, that I am personally not going to put time into maintenance of these packages, especially if it concerns a system that I am not using myself.

**Comment by rasmuskriest** [comment]
@ErichDonGubler Have you made any process on this? I would be more than happy to help!

**Comment by ErichDonGubler** [comment]
@rasmuskriest: Nope! I've spent the last little while transitioning to a new Rust day job -- I've switched from developing primarily on the Windows platform to Linux, so it's lower priority for me and will take longer for me to get around to. Feel free to take the reins if you need it! :)

**Comment by sharkdp** [comment]
This has already been resolved by @rasmuskriest in #541.
