### ISSUE TITLE
Enabling termcap initialization when using bat as a pager

### ISSUE THREAD

**Issue by rickyson96** [sharkdp/bat#508]
One of **less** option is that it can disable sending the termcap initialization and deinitialization using `-X` option (less -X somefile.txt). This option prints less output even after quitting. Right now, bat display output in this behavior even when displaying output with pager. Is there any way for bat to enable the termcap initialization when displaying output, so that I could have the less behavior without `-X` option?

PS: I know that this is a `cat` clone, not `less` clone, and this is a feature of `less`. But I personally think that `bat` is more than both, and can be used as replacement for both utility. CMIIW and feel free to close this issue if it is not applicable.

**Comment by sharkdp** [comment]
> One of **less** option is that it can disable sending the termcap initialization and deinitialization using `-X` option (less -X somefile.txt). This option prints less output even after quitting. Right now, bat display output in this behavior even when displaying output with pager.

Yes. `bat` actually uses `less` behind the scenes and it calls `less` with the `-X` option by default, unless you instruct it to do otherwise.

> Is there any way for bat to enable the termcap initialization when displaying output, so that I could have the less behavior without `-X` option?

Yes, please see the corresponding section in the README: https://github.com/sharkdp/bat#using-a-different-pager

**Comment by sharkdp** [comment]
Actually, there seems to be a problem with `bat`s `--pager` option in the current release, as I have just found out. But you should be able to use:
```
export BAT_PAGER="less -FR"
```

**Comment by rickyson96** [comment]
isee @sharkdp
thank you for looking into this issue and fix it. 🎉
