### ISSUE TITLE
Provide a "less" interactive mode

### ISSUE THREAD

**Issue by jsamr** [sharkdp/bat#51]
First, thanks for this awesome tool. Here is my feature request:
provide a `less`-like browsable mode, usefull for large files. 
This is needed because there is no [obvious way](https://superuser.com/a/337640/383691) to colorize `less` input which makes `bat ... | less` unusable.

**Comment by bnewbold** [comment]
Duplicate of #29, I think.

**Comment by jsamr** [comment]
@bnewbold Indeed! closing.

**Comment by sharkdp** [comment]
Thank you for the feedback, anyway!

> This is needed because there is no obvious way to colorize less input which makes bat ... | less unusable.

There is a workaround, see #29

**Comment by jsamr** [comment]
@sharkdp Glad I now know `less` `-R` option, awesome!
