### ISSUE TITLE
$BAT_THEME relies on case sensitivity, breaks with fish shell

### ISSUE THREAD

**Issue by ykgmfq** [sharkdp/bat#511]
From https://mvolkmann.github.io/fish-article/#Variables:
> To export a variable so it is visible in child processes, add --export (-x). This is not a new kind of scope. It is convention for exported variable names to be all uppercase.

Fish prompt:
```
~> set -x $BAT_THEME 'GitHub'
~> echo $BAT_THEME 
Github
~> bat test.txt
[bat warning]: Unknown theme 'Github', using default.
```

**Comment by sharkdp** [comment]
I think you are misunderstanding something here.

The documentation you quoted concerns the `~/.config/fish/fishd.XXX` file, not a command on the shell. Calling `set -x $BAT_THEME 'GitHub'` does not do, what you expect.

It looks like you have defined `$BAT_THEME` somewhere else (I'm not really familiar wish `fish`, so I can't tell what kind of possibilities there are).

If you want to redefine `$BAT_THEME` from the console, simply use:
```
export BAT_THEME="GitHub"
```

**Comment by ykgmfq** [comment]
Thanks!
The problem was using `set -x $BAT_THEME` instead of` set -x BAT_THEME`. I previously had `set -x BAT_THEME 'Github'` in my `config.fish`.
