### ISSUE TITLE
How to use theme with spaces in the name?

### ISSUE THREAD

**Issue by Gary-Armstrong** [sharkdp/bat#516]
In particular 'Monokai Extended Bright'
Exec `export BAT_THEME='Monokai Extended Bright'` does not provide results.

**Comment by sharkdp** [comment]
That should work just fine, but the theme is called "… Light", not "… Bright".

**Comment by areichow** [comment]
This is still an issue in 0.26.1. bat --list-themes shows "Monokai Extended Bright" as a theme, and it doesn't work.

$ bat --list-themes
[...]
Monokai Extended (default)

  // Output the square of a number.
  fn print_square(num: f64) {
      let result = f64::powf(num, 2.0);
      println!("The square of {num:.2} is {result:.2}.");
  }

Monokai Extended Bright

  // Output the square of a number.
  fn print_square(num: f64) {
      let result = f64::powf(num, 2.0);
      println!("The square of {num:.2} is {result:.2}.");
  }

Monokai Extended Light (default light)

  // Output the square of a number.
  fn print_square(num: f64) {
      let result = f64::powf(num, 2.0);
      println!("The square of {num:.2} is {result:.2}.");
  }

Monokai Extended Origin

  // Output the square of a number.
  fn print_square(num: f64) {
      let result = f64::powf(num, 2.0);
      println!("The square of {num:.2} is {result:.2}.");
  }

[...]
