### ISSUE TITLE
Brackets color does not correspond

### ISSUE THREAD

**Issue by sh-tech** [sharkdp/bat#517]
### Environment
* zsh
* theme TwoDark

### Bug

I executed `bat` on `.sh`, but Brackets color does not correspond. 
This bug was only in this line, and there was no problem except it.

### Images
![image](https://user-images.githubusercontent.com/32533860/53694921-5f34f280-3df8-11e9-9058-e3f02e569fef.png)

![image](https://user-images.githubusercontent.com/32533860/53694885-082f1d80-3df8-11e9-8a62-7705b719c370.png)

**Comment by sharkdp** [comment]
Thank you for reporting this. That sound like a problem with the Shell syntax in https://github.com/sublimehq/Packages which is - as I understand it - not (entirely) compatible with `zsh` synax.
