### ISSUE TITLE
Horizontal line wraps if `less --status-column` is used as pager

### ISSUE THREAD

**Issue by stroborobo** [sharkdp/bat#519]
Hey @sharkdp,

I don't know why, but the horizontal lines bat draws are one char too long on my machine and wraps:

![image](https://user-images.githubusercontent.com/684180/53767713-de98f380-3ed6-11e9-86d2-071ef8a121bf.png)

Appears to be this line:
https://github.com/sharkdp/bat/blob/9e11d66/src/printer.rs#L175

If I change the '1' to a '2', it's fine.

This is iTerm2 on the latest macOS and bat built from the current master (ecf147f).

**Comment by stroborobo** [comment]
Maybe actually it starts a char early:

![image](https://user-images.githubusercontent.com/684180/53793496-50505c00-3f2e-11e9-9ffd-dfccfc380120.png)

**Comment by stroborobo** [comment]
Oh I understand now, it's the -J/--status-column switch in my $LESS env var. Unfortunately there's no --no-status-column to append to bat's pager call for an easy workaround. Personally I'd like it for the line to be 80 chars max so it doesn't wrap when resizing the terminal or adding split screens.

Thoughts?

**Comment by stroborobo** [comment]
Putting `--terminal-width=-1` into my config is a good enough workaround for me.

Please close if this issue is out of bat's scope.

**Comment by sharkdp** [comment]
Thank you for the feedback and for solving your own issue :-). See #376 for a related ticket with the same problem.

**Comment by stroborobo** [comment]
Oh, `--wrap=never` is a nice addition, too. Thank you! 💯
