### ISSUE TITLE
Provide a man page

### ISSUE THREAD

**Issue by jsamr** [sharkdp/bat#52]
Offer a linux manual page for utility description.

**Comment by 0mp** [comment]
Also, it would be nice if it wasn't Linux-specific 😄

**Comment by sharkdp** [comment]
Sounds good. However, it feels to me that we are in a very early stage of development and command-line options are just starting to develop. So this does not feel very urgent to me.

**Comment by pickfire** [comment]
@sharkdp Would it be nice to have a troff man page?

**Comment by sharkdp** [comment]
> Would it be nice to have a troff man page or generate it from clap?

Generating from clap doesn't work yet, right?

troff is [what we also have for `fd`](https://github.com/sharkdp/fd/blob/master/doc/fd.1), correct? If so, I'd prefer the same format, yes. Auto-generating the man page also sounds appealing because maintaining the man page for `fd` is quite cumbersome, to be honest.

**Comment by sharkdp** [comment]
@pickfire I know :smile: :+1:. What would you suggest for `bat`?

**Comment by pickfire** [comment]
@sharkdp If clap_generate have a auto man page generation, I definitely would suggest that. Right now if it was me, I would have wait for that support.

**Comment by kgilonne** [comment]
And please add "man" as subcommand of bat to open it 👍

**Comment by pickfire** [comment]
@kgilonne No, I would definitely not do that, now there's is already `rustup man xxx` which I think is useless, why not just add the rust man pages to MANPATH?

**Comment by sharkdp** [comment]
I also don't see the need for a `man` subcommand.

**Comment by sharkdp** [comment]
I have added a simple initial version in "doc/bat.1" via [`help2man`](https://linux.die.net/man/1/help2man) with some manual editing.

**Comment by sharkdp** [comment]
I am going to close this ticket. The next version of `bat` will ship with a man page. Any help in improving the man page is very much appreciated!
