### ISSUE TITLE
Scrolling in iTerm not working if I set `--pager="less -FR"` in bat config file

### ISSUE THREAD

**Issue by selrond** [sharkdp/bat#526]
only works if I set `export BAT_PAGER="less -RF"` directly in my `.zshrc` - should the behaviour be the same regardless of where I set it?

**Comment by sharkdp** [comment]
Thank you for your feedback. This is a duplicate of #509 which has been fixed already (but not yet released).

**Comment by sharkdp** [comment]
Fixed in [v0.11.0](https://github.com/sharkdp/bat/releases/tag/v0.11.0).
