### ISSUE TITLE
Incorrect highlighting of version-strings in Perl

### ISSUE THREAD

**Issue by GoldsteinE** [sharkdp/bat#527]
**How to reproduce:**
`echo 'v5.18' | bat -l perl`

**Expected behavior:**
All string is highlighted with one color — it's a version string: https://perldoc.perl.org/perldata.html

**Actual behavior:**
`v5`, `.` and `18` are highlighted with three different colors.

**Comment by keith-hall** [comment]
bat by default uses the Perl language grammar from the following repo, you may wish to report this there: https://github.com/sublimehq/Packages

**Comment by sharkdp** [comment]
Closing this, as there is nothing we can do here. Thank you for the explanation, @keith-hall
