### ISSUE TITLE
`v` command does not work with a file as arg

### ISSUE THREAD

**Issue by spk** [sharkdp/bat#528]
Hi,

First thanks for this nice tool!
The thing I miss the most using it is the `v` command that open your EDITOR with the file opened (and go back to the pager when you are done editing). Since bat open the file from stdin its not possible and the `v` command fail with `Cannot edit standard input  (press RETURN)`. Is there a way with LESSEDIT or other env var to make this work?
If its not possible or not planed feel free to close this, thanks again! 

From `less` man page:

```
       v      Invokes  an  editor  to edit the current file being viewed.  The
              editor is taken from the environment variable VISUAL if defined,
              or  EDITOR if VISUAL is not defined, or defaults to "vi" if nei‐
              ther VISUAL nor EDITOR is defined.  See also the  discussion  of
              LESSEDIT under the section on PROMPTS below.
```

**Comment by sharkdp** [comment]
Thank you for the feedback!

See #358 or #464.
