### ISSUE TITLE
Can't use Tab to auto complete the file path in the latest version on macOS.

### ISSUE THREAD

**Issue by fcwork** [sharkdp/bat#536]
I just upgraded bat on my Mac with `brew update && brew upgrade`, then the following error showed up when I want to complete the file name "Table.txt" using Tab.

```
xxx@MBP: ~$bat Ta
(eval):1: _bat: function definition file not found
(eval):1: _bat: function definition file not found
(eval):1: _bat: function definition file not found
```

Environment:
zsh 5.7.1

When I try on bash, completion function work well, maybe it is the problem about the variables named `FPATH` and `fpath`.

Reference:
https://unix.stackexchange.com/questions/120752/zsh-autocompletion-gives-seemingly-random-errors-after-some-time

**Comment by fcwork** [comment]
After running rm ~/.zcompdump* and restarting the terminal, the completion work well now.

**Comment by shreyasminocha** [comment]
Is there a simple explanation for why this happens?

**Comment by sharkdp** [comment]
> Is there a simple explanation for why this happens?

Older versions of rust shipped a "broken" bash completion file which needs to be removed from the cache.

**Comment by mcjlnrtwcz** [comment]
> After running `rm ~/.zcompdump*` and restarting the terminal, the completion work well now.

I tried this and it didn't work. Is there another solution? :( I'm running bat 0.11.0 and macOS 10.14.6

**Comment by sharkdp** [comment]
@mcjlnrtwcz Could you please try updating to the latest version of `bat` (and repeat the steps above)?

**Comment by borekb** [comment]
I'm getting this on macOS 12.3.1 as well. Have tried `rm ~/.zcompdump*`, I verified that the `.zcompdump...` file was re-generated but I still get this.

```console
$ bat some-fi
(eval):1: _bat: function definition file not found
(eval):1: _bat: function definition file not found
(eval):1: _bat: function definition file not found
```

**Comment by florianrusch-zf** [comment]
I also got the same problem. I've tried to `rm ~/.zcompdump*` and restart the terminal but nothing happened - still the same error.

@borekb @mcjlnrtwcz do you found a workaround/fix?

My versions are:
- bat 0.22.1
- macOS 13.0.1
- zsh 5.9

**Comment by florianrusch-cluetec** [comment]
I also got the same problem. I've tried to `rm ~/.zcompdump*` and restart the terminal but nothing happened - still the same error.

@borekb @mcjlnrtwcz do you found a workaround/fix?

My versions are:
- bat 0.22.1
- macOS 13.0.1
- zsh 5.9

**Comment by Tony-Sol** [comment]
Have same issue while logged in as root
