### ISSUE TITLE
ASCII-only option for CJK environments

### ISSUE THREAD

**Issue by be5invis** [sharkdp/bat#537]
This is a mirror of https://github.com/sharkdp/hexyl/issues/36
Under CJK environments, many non-ASCII symbols may become wider and occupy two console cells. The wide character set varies across fonts. Therefore it would be good to introduce a `--ascii` option that replaces all non-ASCII characters with the ASCII equivalent.
Also, since Windows users may use legacy fonts more frequently, `--ascii` option should be **enabled by default** if they are under [DBCS code pages](https://en.wikipedia.org/wiki/Code_page#DBCS_code_pages) (932, 936, 949, 950).

**Comment by sharkdp** [comment]
Thank you for the feedback. Do we need another ticket for this? I think it would be more useful to keep the discussion in #36.

**Comment by sharkdp** [comment]
Thank you very much for your request. That sounds like a reasonable feature to include, but I am not going to work on this myself.

Also, before someone else starts to work on this: I'm only inclined to make changes in this direction if the code complexity of `bat` does not increase in a significant way (sorry).

**Comment by sharkdp** [comment]
I'm going to close this for now, as there are no further reports of this being a problem. As a workaround, the "grid" can be disabled by adding
```
--style=numbers,changes,header,snip
```
to your configuration file.

**Comment by gigberg** [comment]
For any person who encounters this problem, especially in Chinese Windows System, 

you only need to install  less from `scoop install main/less`. 

The you'll find both `€鈹` decoding error and `windows system path slash` error went done.

Note: do not use the less command installed by `scoop install main/busybox`.
