### ISSUE TITLE
providing non-interactive mode

### ISSUE THREAD

**Issue by jjangga0214** [sharkdp/bat#539]
Hi,

`bat` enters interactive mode though I didn't pipeline it to `less`.
I wonder if it's intended and there's an option or workaround to just print the content.

Thanks.

**Comment by sharkdp** [comment]
> `bat` enters interactive mode though I didn't pipeline it to `less`.

Yes, that is the intended behavior. Interactive mode means: the output goes to an interactive terminal. That is usually the case if the output is not piped anywhere else.

If you want the plain file contents, use `--plain`. Or pipe the output to a file or another program.

**Comment by jjangga0214** [comment]
Well, what I've tried to find is a way or an option to just print the whole file content non-interactively **with** styles and decorations such as line numbers, which is not achieved by `--plain` option.  

On my computer (zsh, kali-rolling (debian stretch)), `bat -p <...>` still enters into interactive mode and only removes decorations.

If I pipe the output, then the file contents is just printed non-interatively. However, decorations and style are not preserved, which is not what I wanted.

Is there a way? If it's not just implemented, do you think it can be good to be? (for me, I feel definitely "yes")

**Comment by sharkdp** [comment]
> what I've tried to find is a way or an option to just print the whole file content non-interactively **with** styles and decorations such as line numbers, filename, and colors, which is not achieved by `--plain` option.

Take a look at the `--decorations` and `--color` options. If you set both to "always", you should be able to get what you want.

**Comment by jjangga0214** [comment]
Thanks you @sharkdp! 
The below does it.
 
```bash
bat --decorations always --color always <file> | cat
```

**Comment by vn971** [comment]
@jjangga0214 @sharkdp if I understand it correctly, the better command would be:
```
bat --paging=never <file>
```
This still includes coloring and decoration by default -- it just doesn't use the pager anymore.

**Comment by vn971** [comment]
Maybe some documentation is worth adding though. E.g. something with the word "interactive". I was staring at `man bat` for quite a long while before I've finally figured out that the key to disable the interactive mode is `--pager=never`. (As you see I've even had to go online first and find this issue, before finally founding a solution within the manual page after all.)

**Comment by vn971** [comment]
I've also raised an issue now for supporting the non-interactive mode on a global level a bit better: https://github.com/sharkdp/bat/issues/2629

**Comment by justinTM** [comment]
yeah still getting errors on GitLab CI/CD:


```bash
bats \
    --verbose-run \
    --trace \
    --timing \
    --print-output-on-failure \
    --pretty \
    --report-formatter junit \
    "$@" \
    test-dev-env-setup.bats \
    test-install-unit.bats \
    test-install-integration.bats
```

results in:

```console
tput: terminal attributes: No such device or address                                                                                  
ERROR: command `bats-format-junit --base-path test-dev-env-setup.bats` failed with status 141   
```
