### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by rivertam** [sharkdp/bat#54]
Is there any plan for text wrapping? The output right now is *so* polished, lines too long look pretty out-of-place. Definitely understand not wrapping by default, but having a flag for it would be pretty chill I think.

**Comment by sharkdp** [comment]
I thought about this as well - we should definitely try this! :+1:

It will definitely not be that easy due to ANSI escape codes that have to be closed at the end of the line and re-opened at the beginning of the wrapped line.

**Comment by sharkdp** [comment]
Closed by @eth-p, see (screenshots in) #102
