### ISSUE TITLE
Syntax for .env files

### ISSUE THREAD

**Issue by mayank** [sharkdp/bat#544]
Please add support to format `.env` files.

**Comment by sharkdp** [comment]
Thank you for the feedback.

Please provide a little bit more information. What is `.env`? How popular is it? Why should it be included in `bat` by default? Is there a Sublime Text syntax for it?

**Comment by mayank** [comment]
It is used to read and set the environment variables for a project. Used in multiple languages using dotenv packages. 
Here is the sublime syntax.
https://github.com/willmcclellan/DotEnv-Sublime-Syntax

**Comment by sharkdp** [comment]
Okay, sounds good to me. This syntax seems to be more popular (?): https://packagecontrol.io/packages/DotENV

A quick & dirty way to achieve something similar is to add
```
--map-syntax=.env:bash
```
to your `bat` config file (see README for details).

**Comment by sharkdp** [comment]
Added in 3795acbd170fd8246af792c180dc232a2f95f43f
