### ISSUE TITLE
`#!/usr/bin/env bash` shebang not recognized

### ISSUE THREAD

**Issue by georgevreilly-stripe** [sharkdp/bat#545]
I have a Bash script that starts with a `/usr/bin/env` shebang:

```bash
#!/usr/bin/env bash
```

When I run `bat` against it, there is no syntax highlighting.

When I run `bat -l bash`, there is.

**Comment by sharkdp** [comment]
I can not reproduce this. Works for me.

Can you please add some information on
* which `bat` version you use
* which steps are needed to reproduce this? (I tried `echo "#\!/usr/bin/env bash\necho 'hello'" > /tmp/test; bat /tmp/test`)

**Comment by georgevreilly-stripe** [comment]
I can no longer reproduce this either. I can't remember what Bash script had the problem. If I find it, I'll

Then and now, I'm running Bat 0.10.0.
