### ISSUE TITLE
Manual is incomplete

### ISSUE THREAD

**Issue by Hultner** [sharkdp/bat#546]
The man-page for `bat` doesn't contain all the options that the `bat --help`-page contain. 
I notice this while looking for a row-highlight option, I did a search in the man-page and couldn't find anything, read through the entire thing and still couldn't find it, I was sure I had seen it before so in desperation I tried bat --help | grep "highlight", and sure enough there it was
```sh
$ bat --help | grep '\-\-highlight'; echo $?
    -H, --highlight-line <N>...
0
```

For comparison, the manual
```sh
$ man bat | grep '\-\-highlight'; echo $?
1
```

As a unix user I expect the manual to at least cover all the options that are documented in the built in help-command.

**Comment by fendever** [comment]
Have you considered `help2man` utility? You can introduce new build script for cargo like
`cargo create-man-page` which will automatically create man page for the `bat` based on --help.

**Comment by Hultner** [comment]
@fendever That sounds very nice, however I'm actually not a developer of this application but merely a user.

I did however create a PR with a patch for this particular inconsistency. 

Something like the package you mentioned could maybe prevent these kind of inconsistencies in the future.

**Comment by fendever** [comment]
@Hultner I'll check what can be done regarding this matter.

**Comment by sharkdp** [comment]
Thank you for the feedback. I must have missed it when creating the release.

If there is a good way to automatically create the man page via `clap`, that would be great. I think this is a planned feature for `clap-3.x`.

**Comment by fendever** [comment]
@Hultner I was thinking actually: 'is it a good idea to keep man page inside of `bat` repo? should not be a man page a part of distro specific package and be a part of package maintainer responsibility?` I don't have the answers for those questions

**Comment by sharkdp** [comment]
I'm going to close this for now, as the original issue is solved.
