### ISSUE TITLE
extra whitespace after grid border

### ISSUE THREAD

**Issue by ripples-alive** [sharkdp/bat#549]
Seems bat always add an extra whitespace after grid border. Is it possible to avoid it because it makes selection & copy terrible.
![image](https://user-images.githubusercontent.com/7439574/56542755-038a1880-65a2-11e9-9dfb-1b85f7413059.png)

**Comment by fendever** [comment]
> Seems bat always add an extra whitespace after grid border. Is it possible to avoid it because it makes selection & copy terrible.
Well, `bat` can be changed the way that you will be able to specify the number of spaces after the vertical grid line with some cli option but I think it's overcomplicating.

From my point of view it's like accusing VCS web UIs that you can't copy without the line numbers. For copying of data you can turn off line numbers for example.

**Comment by ripples-alive** [comment]
@fendever Yeah, I already turn off line number by default now. I just want to make sure whether it's the only way to deal with this problem.

**Comment by fendever** [comment]
> @fendever Yeah, I already turn off line number by default now. I just want to make sure whether it's the only way to deal with this problem.

It seems so, but anyway, if most of `bat` users want this, it can be implemented quite easy.

**Comment by sharkdp** [comment]
I don't see how removing the space after the grid border makes anything better. There is still the "side bar" (left of the border) and the border itself which make copying hard. If you want to copy, use the `-p` option or pipe to `xclip`.

**Comment by ripples-alive** [comment]
@sharkdp I'm using iTerm2 on macOS. "Side bar" will be excluded automatically when selecting, just as the screenshot I pasted previously. So the extra whitespace is the only unexpected characters.
I know it's possible to use the `-p` option or pipe to `xclip`. With all these methods, I need to quit and input new command for copying because it's impossible to toggle line number or grid border interactively. It's really annoying, especially when I just want to copy part of a large file.

**Comment by sharkdp** [comment]
> "Side bar" will be excluded automatically when selecting, just as the screenshot I pasted previously.

Ahh, that's cool. I didn't know that. Seems to be an iTerm2 feature.

My terminal emulator (`terminator`) allows me to block-select part of the text using ctrl-shift-mouse:
![image](https://user-images.githubusercontent.com/4209276/56752059-c1bac700-6787-11e9-804a-3f9deebfdaa4.png)

Maybe there is such a feature in iTerm2 too?

**Comment by ripples-alive** [comment]
Block-select is a good idea. I found that iTerm2 support block-select too. But block-select still has a small problem. if a line is soft wrapped, seems block selection will add extra `\n` at the wrap position.

#### normal selection:

![image](https://user-images.githubusercontent.com/7439574/56753055-49222d80-67bc-11e9-850c-12b19361f365.png)

the result is:

```
 1231231231231231231231231231231231231231231231231231231231231231231 23123123123123123
 456
 789
```

#### block selection

![image](https://user-images.githubusercontent.com/7439574/56753145-82f33400-67bc-11e9-8b44-29c9b7e0fdc8.png)


```
1231231231231231231231231231231231231231231231231
23123123123123123123123123123123123
456
789
```

**Comment by sharkdp** [comment]
The only way to prevent this is to disable `bat`'s wrapping option. Otherwise, `bat` *will actually print a newline character* and there is no way for the terminal emulator to know if that's a real line break or not.

To disable wrapping, you need to add `--wrap=never` to your config file. If you use `bat -p`, wrapping is also disabled.

**Comment by ripples-alive** [comment]
With `--wrap=never`, it's still impossible to get the expected result:

```
123123123123123123123123123123123123123123123123123123123123123123123123123123123123
456
789
```

#### normal selection (with `--wrap=never`)

![image](https://user-images.githubusercontent.com/7439574/56753984-6526ce80-67be-11e9-8c7c-4ec710fd56ad.png)

#### block selection (with `--wrap=never`)

![image](https://user-images.githubusercontent.com/7439574/56753996-72dc5400-67be-11e9-8ce1-9099a2ee3aef.png)

**Comment by sharkdp** [comment]
You are right, of course. I'm afraid there is no solution to that (except for having your terminal large enough, of course).

I would rather not like to remove the whitespace after border just because there is an iTerm2 feature that somehow seems to detect the `|` character as a selection border.

**Comment by ripples-alive** [comment]
Understand. Anyway, thank you for creating such a great tool. I really like it.

**Comment by maxfilov** [comment]
Alright
