### ISSUE TITLE
Debian archive is missing vendor completions.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#554]
The amd64 `.deb` archive (and probably others) under the releases page is missing vendor-provided shell autocompletions.

Here are the paths that I could find:

**Bash:** /usr/share/bash-completion/completions/
The completion script should have no file extension.

**Fish:** /usr/share/fish/vendor_completions.d/
The completion script should end in `.fish`.

**Zsh:** /usr/share/zsh/vendor-completions/ 
The completion filenames seem to all begin with an underscore. I'm not familiar with zsh though, so I could be wrong. It also seems like they shouldn't have a file extension.

It's also important to note that some of these may be located at `/usr/local/share/...`, depending on whether or not the distro packages use `/usr/local` or `/usr` as the default prefix. Maybe some kind of install script could be added that copies it to the correct location, depending on whether or not the `/usr/local/share/...` folder exists?

**Comment by sharkdp** [comment]
Please check out the release notes (https://github.com/sharkdp/bat/releases):

* v0.9.0: Shell completions are currently not shipped anymore, see #372 for details.
* v0.10.0: Completely disabled the generation of shell completion files, see #372

Manual fish completion files were recently re-enabled in #524.

**Comment by eth-p** [comment]
Ah, that explains it. My bad!

**Comment by yogan** [comment]
I'm confused about the situation with the recent release of v0.11.0. The release notes state that now completions for fish are included (which would be great!), but the .deb does not contain any .fish file. Am I missing something here? Do they have to be generated somehow?

**Comment by eth-p** [comment]
Reopening, since the Debian archive for v0.11.0 still doesn't contain vendor completions.

**Comment by sharkdp** [comment]
I think my comment above was incomplete in the sense that the *DEB* packages on the Release page apparently never included the completion files (I can't find anything in the Git log).

We do ship autocompletion files (currently only fish) in the tarballs, so some distributions did also include them in the past.

If somebody wants to fix this for the automatically deployed DEB packages, I'm happy to create a new release. The place would be the `make_deb` function in `ci/before_deploy.sh`. The actual fix will probably be simple but I would appreciate some research into this topic. I don't want the DEB package to be "broken" somehow (for some distributions?). I would also like to make sure that the deployment process is kept simple and reliable. Making new releases is a lot of work already.

**Comment by sharkdp** [comment]
Does somebody know where would have to `install` the fish completion file?

**Comment by sharkdp** [comment]
Probably under `/usr/share/fish/completions/bat.fish`, like we do for `fd`:

https://github.com/sharkdp/fd/blob/040c57e007ee49874e47a7fffa74d7d69178b6a1/ci/before_deploy.bash#L147

([batfish](https://en.wikipedia.org/wiki/Batfish) is actually an animal that exists)

**Comment by sharkdp** [comment]
should be included in the next release

**Comment by sharkdp** [comment]
Fish completions are included in the Debian packages for [bat v0.12](https://github.com/sharkdp/bat/releases/tag/v0.12.0).
