### ISSUE TITLE
Add pest syntax

### ISSUE THREAD

**Issue by ice1000** [sharkdp/bat#567]
There's already a sublime package: https://packagecontrol.io/packages/Pest%20Syntax

It has low downloads -- I'm aware. However, since pest is a parser-generator for Rust, we may have a lot of users of bat (where a large number of them are Rustaceans) using pest.

**Comment by sharkdp** [comment]
Thank you for your proposal. To be honest, that sounds like a really special syntax.

Did you see that you can add syntaxes on your own?
https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions
