### ISSUE TITLE
Add "..." decoration when using multiple line ranges.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#569]
I'm making a shell script that uses `bat` to display the results of `ripgrep` searches, and adding "..." as a decoration between multiple line ranges would be a large quality of life improvement. As you can see in the image below, the lines kind of melt together.

![image](https://user-images.githubusercontent.com/32112321/58355932-be6c3700-7e2a-11e9-8c37-70e1fef9a229.png)

Would it be ok to add a flag that inserts an empty line between the ranges that displays "..." as the line number?

![image](https://user-images.githubusercontent.com/32112321/58356217-a648e780-7e2b-11e9-8e02-422178168d26.png)

**Comment by sharkdp** [comment]
Sounds like a great suggestion, thank you very much!

I am planning to take a detailed look at your PR soon.

**Comment by bricewge** [comment]
@eth-p Will you be willing to share your script with us? I think people at #448 will be interested in it.

**Comment by eth-p** [comment]
@bricewge I haven't tested it on Linux yet (only MacOS), but I definitely can. I made a repo for my script [here](https://github.com/eth-p/bat-extras). As I find other ways to integrate bat with other tools, I'll probably add more scripts there in the future, too.

**Comment by sharkdp** [comment]
closed via #570

**Comment by sharkdp** [comment]
Released in [bat v0.12](https://github.com/sharkdp/bat/releases/tag/v0.12.0).
