### ISSUE TITLE
Man page: minor inconsistency around "--theme=<theme>" versus "--theme <theme>"

### ISSUE THREAD

**Issue by grossjohann** [sharkdp/bat#574]
The man page explains the `--theme <theme>` option (with a space), but then proceeds to tell me to add `--theme=<theme>` (with an equals sign) to the config file.  So I suspect that `--theme=<theme>` works on the command line, test it and both `bat --theme=Monokai` and `bat --theme Monokai` appear to work.

I haven't tested whether `--theme <theme>` (with space) works in the config file, I've only tested that `--theme=<theme>` (with equals) does.

Suggestion: Be consistent in the man page, either use space everywhere or use equals everywhere.  Then add a remark somewhere that both of them work.

**Comment by sharkdp** [comment]
Yes, both options (with space or `=` sign) should work in all situations.

> Suggestion: Be consistent in the man page, either use space everywhere or use equals everywhere. Then add a remark somewhere that both of them work.

Sounds good, thank you. I'd prefer if we use the `--option=value` syntax by default.
