### ISSUE TITLE
Code line marker (bactracing, debugger...)

### ISSUE THREAD

**Issue by svalat** [sharkdp/bat#585]
Hi,
I was looking to possibly use this (I must admin really nice) command into a project extend a unit test framework for bash scripts. And for a detailed backtrace on they print the source code (range arround error) and point the line.

I would do the same with bat. Ideally I would like this to point line 32 (we can think provinding a list with comma) : 

```sh
bat --marker 32 file.sh
```

Then it add a `>` before or after or before the line number.

```plain
    30  |  lorem
    31  |  lipsum
 >  32  |  lorem
    33  |  lipsum
    34  |  lorem
    35  |  lipsum
```

Would you think it is interesting ?

I like rust so can see if I found a bit of time to make a first try patch, I looked your code looks really nice. The rendering of this (line + git annotations)  is done in `src/decorations.rs` if I don't miss ?

**Comment by sharkdp** [comment]
Thank you for the feedback!

You can already do this with the `-H, --highlight-line <N>...` option.

Also, have a look at `-r, --line-range <N:M>...` which could be helpful as well.

**Comment by svalat** [comment]
Ah thanks very much, 
I played with `-r` but missed the `-H` while reading the help.

I close the ticket, that feet my need.
