### ISSUE TITLE
Packaging: Alpine Linux

### ISSUE THREAD

**Issue by 5paceToast** [sharkdp/bat#586]
Bat is now in the official Alpine repos, maintained by me: https://pkgs.alpinelinux.org/packages?name=bat

**Comment by sharkdp** [comment]
Cool, thank you very much! It would be great if we could add a section to the README.

**Comment by idvorkin** [comment]
@sharkdp can you also add the other CPU variants. I'm on an x86 variant.

**Comment by sharkdp** [comment]
@idvorkin I do not maintain the Alpine Linux package. Opening a request in the Alpine Linux forums (or similar) might be a better way to go.

What do you mean by "x86 variant"? Isn't x86 a synonym for x86_64 (aka amd_64) nowadays?

If you are on a i686-compatible 32 bit system instead, you can find the necessary Linux binaries on the Release page (i686).

**Comment by 5paceToast** [comment]
Alpine only has bat (and other rust packages) as amd64 due to a limitation of rust itself on the musl platform.
Someone recently got it working on armhf and armv7 too, and more progress is expected on the next release (if I recall correctly).
Might take a bit for i686 support though.

**Comment by idvorkin** [comment]
Thanks I'll take a look at the 686 package to see if it works for me and report back

**Comment by idvorkin** [comment]
I tried the 686 releases (deb and .tar.gz) and neither worked! Thanks for the tip though!


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sharkdp** [comment]
So which platform are you actually on? What is the error message?

**Comment by idvorkin** [comment]
@sharkdp I’m on iSH, which is i686 emulator for iOS

      
    Linux igors-11-iPad-Pro 3.2.0-ish SUPER AWESOME compiled on Jul 28 2
019 i686 Linux

Running under gab

      Starting program: /root/tmp/bat-v0.11.0-i686-unknown-linux-gnu/bat  
      Bad system call    

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sharkdp** [comment]
> I’m on iSH, which is i686 emulator for iOS

oh dear :smile: 

Apparently it does not support all system calls (see https://github.com/tbodt/ish/issues?utf8=%E2%9C%93&q=Bad+system+call). I guess you would have to open a bug report upstream. You could try to run
```
strace bat …
```
to see on which syscall it fails (if `strace` still picks up the "illegal" system call).

**Comment by sharkdp** [comment]
Ok, thanks. As I said, I think this should be reported upstream - not here.
