### ISSUE TITLE
Add some basic documentation for less integration

### ISSUE THREAD

**Issue by tiagoantao** [sharkdp/bat#59]
I suspect a lot of use cases of bat are of integration with less.

I suggest adding some documentation on this. What is needed is already written on https://github.com/sharkdp/bat/issues/29 , namely

`export LESS="-R"`
Is needed for the `bat blah|less` to work

and

```
export LESSOPEN="| bat %s"
export LESS="-R"
```
Is need for less to use bat automatically

**Comment by BrainMaestro** [comment]
This is not necessary anymore. `bat` will use `less` if it's available now

**Comment by sharkdp** [comment]
Starting with the next release, `bat` will only show colored output and all the decorations if the output is an interactive terminal. When piping to less (or anything else), it will simply show the plain contents of the file. Colors and decorations can be forced by using `bat --colors always --style=... | less -R`.

**Comment by sharkdp** [comment]
I currently don't see the need to add this to the README. If someone really wants to use `less` with `bat`, it will work in exactly the same way like with every other program.
