### ISSUE TITLE
Add syntaxes for prominent (configuration) files like /etc/fstab

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#593]
It would be great if we could offer (even simple) syntax highlighting for some of the more famous configuration files:

config:
- [x] `/etc/fstab`
- [x] `/etc/passwd` and `/etc/group`
- [x] `/etc/resolv.conf`
- [x] `/etc/hosts`
- [x] `/etc/ssh_config` and `/etc/sshd_config`

less important (IMO):
- [ ] `/etc/X11/xorg.conf` and `/etc/X11/xorg.conf.d/*`
- [ ] `/etc/ld.so.conf`

non-config files that would be nice to have:
- [x] `/proc/cpuinfo`
- [x] `/proc/meminfo`

This is partly related to #592

**Comment by sharkdp** [comment]
see updates in #698 and #703

**Comment by sharkdp** [comment]
and more updates in #696 #706

**Comment by sharkdp** [comment]
Added simple syntaxes for `/proc/meminfo` and `/proc/cpuinfo`.

I'm going to close this for now, as all the important things have been covered.

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).

**Comment by dufferzafar** [comment]
@sharkdp Does bat have syntax highlighting for nginx / apache configs?

**Comment by sharkdp** [comment]
Could you please open a new "syntax request" ticket? Thank you.
