### ISSUE TITLE
Question: producing PS or PDF output?

### ISSUE THREAD

**Issue by mouse07410** [sharkdp/bat#595]
Not a bug report, but a question/feature request: `bat` displays/formats the source files very nicely. I'd like to have the ability to print that output - and all my printers are PostScript or PDF (AFAIK). What's the best way to convert the `bat` output to PDF? Or should formatted text files print nicely as they are?

**Comment by sharkdp** [comment]
I'm not inclined to add any "export" functionality to `bat`, but I think there are multiple ways to do this:

* This may sound stupid, but the easiest way is probably to print a (properly cropped) screenshot.
* Use a terminal emulator with print functionality (e.g. `konsole`).
* Convert `bat`s ANSI-code output to HTML, open it in a browser and use the browsers print functionality. If you do this, make sure to run `bat` with the `--color=always` option: `bat --color=always my_file.cpp | ansi2html`.
* Use something like https://github.com/marionebl/svg-term-cli to convert the terminal output to SVG before printing it.

**Comment by mouse07410** [comment]
> I'm not inclined to add any "export" functionality to `bat`

Understood. Though it would be very convenient if "exporting" could be accomplished in "one step" by just providing the right flags to `bat`, rather than playing manually with a bunch of other programs (and to make it worse - it looks like those programs have to be terminal emulators!)

> ... the easiest way is probably to print a (properly cropped) screenshot

Not really. First - the quality. Second - I can't just send an image (`.png` in this case, as that's the format for the saved screeenshots) to the printer, so I'd have to import it into something like Adobe Acrobat or GNU GIMP. Doable, but an unnecessary pain.

> Use a terminal emulator with print functionality...

As I said - doable, but switching to a different terminal just for the sake of pretty-printing source code sounds a bit excessive.

> Convert `bat`'s ANSI-code output to HTML, open it in a browser and use the browsers print functionality.

Thanks, I will experiment with it. 

But still, it would be very nice if the output could be better controlled:

- Ability to specify paper size (in my case, trying `bat source-file.rs | lpr` results in a print job that expects paper in `A4` format, so the job fails - as there's no way to tell it to use US Letter);
- Ability to specify page size, so that the grid header is repeated on every page;
- Ideally - some kind of a clean interface with something that could convert and/or send the output to a printer.

**Comment by sharkdp** [comment]
I think the best way would probably be to provide a (shell or Python) wrapper script that would call `bat` and possibly some other tools like `ansi2html` to finally produce a PDF file.

If someone wants to work on this, I'd be happy to add this to the repository.

In the meantime, I'd like to close this ticket, as I don't really feel like there is a huge interest in something like this (?) and I am personally not going to work on this. 

Related: I sometimes use https://carbon.now.sh/ if I want to share a nice-looking piece of code. It provides PNG and SVG output. Maybe that would work for you as well?
