### ISSUE TITLE
Add detection and syntax stuff for strace output

### ISSUE THREAD

**Issue by svenstaro** [sharkdp/bat#599]
I look through strace output quite a bit and it would be great if bat could automatically detect and highlight strace as the output is actually fairly regular.

Some references:
- https://github.com/vim/vim/blob/master/runtime/syntax/strace.vim
- https://github.com/vim/vim/pull/1837

**Comment by sharkdp** [comment]
Thank you very much. That sounds like a cool idea!

I'm not sure if we can really deliver on the "syntax detection" front, because we are limited to a "first line" detection mechanism. The reason for this is that we want to `bat` to be streaming compatible (which is also important if you run `strace … | bat`). It's also a limitation which is set by the sublime syntax descriptions.

**Comment by sharkdp** [comment]
Oh, hold on. If `strace` output actually always starts with
```
execve(…) = …
```
we should be able to use that.

**Comment by svenstaro** [comment]
Sadly it doesn't. It may start with anything at all. Considering syntax detection works the way you said, it probably is impossible to detect this particular format. If it were possible to run full file analysis if you detect you're not opening a stream then it is certainly possible. However, as an alternative, since there are only so many ways the first line could look, we could still detect against any of the possible first lines.

**Comment by sharkdp** [comment]
Ok, in any case: just having a syntax for `strace` output would be something really useful. `… | bat -lstrace` is not too bad.

**Comment by svenstaro** [comment]
Yes, surely that would still be nice. Also, I still think that parsing just the first line with a bunch of possible syscalls and a regex would probably also figure out the format most of the time.

**Comment by sharkdp** [comment]
Released in [bat v0.12](https://github.com/sharkdp/bat/releases/tag/v0.12.0).

**Comment by beedell-roke** [comment]
@sharkdp, in a terminal that does render colour, [^1] I don't see it:

<img width="1276" height="345" alt="Image" src="https://github.com/user-attachments/assets/89a067a6-aa9e-4aca-a7f9-efe942831b99" />

Do I need to pass `-l sTrace`, or similar?

[^1]: <p></p><details><p></p><img width="1916" height="693" alt="Image" src="https://github.com/user-attachments/assets/25afae0d-361d-42db-a009-afad2e89372a" /><p></p></details><p></p>
