### ISSUE TITLE
thread main panicked on Result::unwrap() with simple js file

### ISSUE THREAD

**Issue by reklis** [sharkdp/bat#60]
> cat index2.js
    const io

    > bat index2.js
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
    Error(-114, target of repeat operator is invalid)', libcore/result.rs:945:5

This appears to be syntax related, if I change the file name to .py it works

    > mv index2.js index2.py

    > bat index2.py
    ───────┬────────────────────────────────────────────────────────────────────
           │ File index2.py
    ───────┼────────────────────────────────────────────────────────────────────
       1   │ const io
    ───────┴────────────────────────────────────────────────────────────────────

I'm using the sample from the readme for the syntax definitions

    mkdir -p ~/.config/bat/syntax
    cd ~/.config/bat/syntax

    # Download some language definition files, for example:
    git clone https://github.com/sublimehq/Packages/
    rm -rf Packages/Markdown
    git clone https://github.com/jonschlinkert/sublime-markdown-extended

**Comment by sharkdp** [comment]
Yes, this is related to the `JavaScript.sublime-syntax` file in https://github.com/sublimehq/Packages/ which contains a regular expression that `syntect` can not parse. I have already addressed this upstream (https://github.com/trishume/syntect/issues/156) and opened a pull request to fix this in sublimehq/Packages (https://github.com/sublimehq/Packages/pull/1525).

**Comment by sharkdp** [comment]
This should be fixed, my upstream PR has been merged.
