### ISSUE TITLE
Selected line coloring?

### ISSUE THREAD

**Issue by 097115** [sharkdp/bat#607]
I'm extremely sorry if this has been already asked but I couldn't find with it, my search terms probably were just too broad :)

So, my question is the following: Is it possible to change the coloring of the matched line from inverted colors to something more plain, monochromatic?

This is the current situation, where every element of the selected line is highlighted with inverted colors:

![poly](https://i.imgur.com/gZZfhGi.png)

And this is the styling I'd prefer (though I don't know what to change in a `thTheme` file):

![mono](https://i.imgur.com/ECovaSq.png)

Would be grateful for a hint :).

Thanks.

**Comment by sharkdp** [comment]
Unfortunately, this is not something that we have any control over. The way a (mouse-) highlighted line looks like is controlled by your terminal emulator.

It might very well be, that there are some terminal emulators where this can be configured.

(partly related: `bat`s `--highlight-line <N>` option)

**Comment by 097115** [comment]
> partly related: `bat`s `--highlight-line <N>` option

You mean if using `bat` with `fzf`, for example, it's possible somehow to set `FZF_PREVIEW_COMMAND` in such a way that it would take the line number from `fzf` and pass it to `--highlight-line` option?

**Comment by 097115** [comment]
> it would take the line number from `fzf` and pass it to `--highlight-line` option?

(for the reference): Seems to be possible but with some non-obvious limitations: https://github.com/junegunn/fzf.vim/issues/841

**Comment by sharkdp** [comment]
Do you think there is anything we can do here or can this ticket be closed?
