### ISSUE TITLE
`--terminal-width -10` is parsed incorrectly

### ISSUE THREAD

**Issue by erydo** [sharkdp/bat#611]
The dash appears to be interpreted as a flag.

The man page says:
> If prefixed with '+' or '-', the value will be treated as an offset to the actual  terminal width.

However, executing produces an error.
> ```
> $ bat --terminal-width -10 foo.md
> error: Found argument '-1' which wasn't expected, or isn't valid in this context
>
> USAGE:
>     bat --terminal-width <width> --theme <theme>
> 
> For more information try --help
> ```

Using a positive offset (`+10`) or fixed value (`120`) both behave as expected.

**Comment by erydo** [comment]
As a workaround, combining the option into a single token behaves correctly:
`--terminal-width=-10`

**Comment by sharkdp** [comment]
Thank you for the feedback.

Fixed in 76c615a30416c4a0bea07fc7df4f5f1e88ddf6e0

**Comment by sharkdp** [comment]
Fixed in [bat v0.12](https://github.com/sharkdp/bat/releases/tag/v0.12.0).
