### ISSUE TITLE
Can we have standalone executable (or .rpm) for linux-x86_64?

### ISSUE THREAD

**Issue by santosh** [sharkdp/bat#613]
I'm in an environment where installing by any package manager is impossible as machines are not connected to the internet. 

Also, `.deb` file comes with every release but not `.rpm` (we are using CentOS).

I really like the tool, especially for syntax highlighting, git integration is a plus. Can we have a stand-alone executable, or if possible any RPM pacakge(s)?

**Comment by sharkdp** [comment]
Please check out the release page (https://github.com/sharkdp/bat/releases) or the README (https://github.com/sharkdp/bat#from-binaries). There are binaries for lot's of different architectures.

bat-v0.11.0-x86_64-unknown-linux-gnu.tar.gz

should be the correct one for your system. If you have problems with your version of libc, use the statically linked binary:

bat-v0.11.0-x86_64-unknown-linux-musl.tar.gz

**Comment by santosh** [comment]
I got what I was looking for; _musl_ version worked in my case.
