### ISSUE TITLE
Shorthand style flags?

### ISSUE THREAD

**Issue by kbd** [sharkdp/bat#617]
It would be nice to have shorthand style flags.

Current:

`bat --style=header,numbers /path/to/file`

With short flags:

`bat -shn /path/to/file`

**Comment by sharkdp** [comment]
Short command line flags are typically parsed as `-shn` == `-s -h -n` which would mean something else entirely (`-n` enables line numbers, `-h` shows the help text).

So this is not really an option. What we could probably do is to use `bat -s=h,n` or maybe even `bat -s=hn`. Both don't really look like great ways to me. Are there any other suggestions?

What is the use case for this? Are you often switching from the default style to the `header,numbers` style? Or do you want to use `header,numbers` as your default style? In the latter case, you could add `--style=header,numbers` to your config file.

**Comment by kbd** [comment]
> What is the use case for this?

I use the default style normally, but I'm often pasting shell sessions into bug reports or Slack and in that case I'll often use styles without the grid, such as `header,numbers`. [Here's an example](https://github.com/johnpapa/vscode-peacock/issues/233). So, it'd be super if it was both quicker to type and would take up less space in the command. i.e. `--style=header,numbers` obscures that I'm just doing `bat .vscode/*` in the linked example, while I'm trying to copy/paste commands for clarity.

> Short command line flags are typically parsed as -shn == -s -h -n which would mean something else entirely... Are there any other suggestions?

That's a good point. Main options I see:

* make `-s` a short flag for `--style`. This can be done without changing anything else.
* add shorthands for the style codes. The full set in the manpage is auto (a), full (f), plain (p), changes (c), header (h), grid (g), numbers (n). The resulting `--style=h,n` (or `-s=h,n`) would be an improvement.

Other options:
* add short flags for every style. Along with the existing `-p` (plain) and `-n` (numbers), `-C` (changes), `-G` (grid), and `-E` (header) could be added, resulting in `-En`.
* you're always free to ignore convention and make `-s` a special case so that `-shn` is short for `-s=h,n`.

That's all I can think of. Thanks for considering!

**Comment by sharkdp** [comment]
to be honest, none of the options sound really appealing to me. I'm striving for a simple command line interface, so I am always a little hesitant to add new options (or new short flags).

> you're always free to ignore convention and make `-s` a special case so that `-shn` is short for `-s=h,n`. (Edit: this is arguable for this option in particular because no other option can directly follow `-s/--style` anyway, since style codes follow.)

I'd rather not. I think the usual convention leaves enough room for a good CLI design.

**Comment by kbd** [comment]
That's too bad. Ordinarily I wouldn't mind:

```alias bathn='bat --style=header,numbers'```

but a main reason I'd hoped for short flags is to have more clarity when I share `bat` output. So instead of:

```bat --style=header,numbers file.txt```

which is explicit but verbose (the filename gets a little lost among the `bat` arguments), I'll have:

```bathn file.txt```

and readers will have to question what `bathn` is.

I'll also often switch between `header` and no `header` depending on whether the filename is obvious from context (eg. `cat`-ing one file or multiple with glob), so I'll have `bathn` and `batn` as well.

**Comment by sharkdp** [comment]
@eth-p It would be great to get a third opinion on this, if you find the time.

**Comment by eth-p** [comment]
**Short flags for each style:** I'm against adding short flags for each style. They're in limited supply, and we would have to use non-obvious letters/casing because existing options already use them.

**Nonstandard -s flag:** I'm not a fan of breaking conventions, and think `bat -shn` would lead to confusion when it doesn't work as somebody would expect it to.

**Short names for styles:** I can see something like `-s=gn` or `-s gn` working. It doesn't look nice, but it gets the job done with the least amount of typing. Maybe only allow them if the short `-s` option is used, so we don't end up with `--style=gchn`?

**Comment by sharkdp** [comment]
@kbd: I'm sorry, but I'm not really convinced, we need this. I'd like to keep `-s` free for now (see e.g. #762).

I'm going to close this for now, unless there is further input.
