### ISSUE TITLE
Feature Request: Display binary files with hexyl

### ISSUE THREAD

**Issue by casey** [sharkdp/bat#619]
It would be super cool to display binary files with hexyl!

**Comment by svanburen** [comment]
Maybe you meant to put this on the hexyl issue tracker? :)

**Comment by casey** [comment]
I meant that bat, when it previews a binary file, should display the contents with hexyl. Should that go on the hexyl issue tracker?

**Comment by svanburen** [comment]
ah, that makes more sense, sorry - I'm assuming you'd want more than `bat --pager=hexyl`?

**Comment by casey** [comment]
No worries! I think that `bat --pager=hexyl` will pipe all of bat's output through hexyl, instead of just the file contents. Mainly I'd like `bat` to display binary files somehow, so I don't need to think about if I need bat or hexyl beforehand.

**Comment by svanburen** [comment]
that would be pretty cool - also, cheers for the `just` project, I've always been super tempted to use it over `make` haha

**Comment by casey** [comment]
Thank you! If there's ever a feature you need that `make` has and `just` doesn't, please feel free to open an issue ^_^

**Comment by sharkdp** [comment]
Thank you for the feedback. That sounds like an interesting idea.

It might make sense to *not* hard-code this to `hexyl`, but to introduce `BAT_BINARY_VIEWER` and to provide a (prioritized) internal list of hex viewers which would be tried in sequence, in case `BAT_BINARY_VIEWER` is not set. Obviously, `hexyl` would be on the top of this list :smile: :smile: 

Also, we would need to restrict this to interactive mode (i.e. only call the external program if the output goes to an interactive terminal).

Another thing to think about is whether we should only show a preview of the file. I could imagine that a lot of `bat some-binary-file` calls are actually accidents (when using shell globs, for example).

**Comment by casey** [comment]
> It might make sense to _not_ hard-code this to `hexyl`, but to introduce `BAT_BINARY_VIEWER` and to provide a (prioritized) internal list of hex viewers which would be tried in sequence, in case `BAT_BINARY_VIEWER` is not set. Obviously, `hexyl` would be on the top of this list 😄 😄

If it's parameterized, the `--color` option should probably also be passed through, although that might be tricky, since not all hex viewers are likely to support a `--color` option with the same semantics as `bat` and `hexyl`.

> Another thing to think about is whether we should only show a preview of the file (e.g. the first 512 bytes). I could imagine that a lot of `bat some-binary-file` calls are actually accidents (when using shell globs, for example).

Is the concern that it would be slow to read the entire file? I suppose this would matter if the user passes `--paging=never` and hexyl tries to display a giant file.

**Comment by sharkdp** [comment]
Not quite the same, but I recently added support for viewing binary files via `bat -A`.

**Comment by sharkdp** [comment]
With the enhanced `-A` option in place, I'm not sure if we need this. But we could probably advertise it in the output, instead of just showing
```
File: whatever   <BINARY>
```
