### ISSUE TITLE
Line number bug?

### ISSUE THREAD

**Issue by NightMachinary** [sharkdp/bat#624]
```
~/TMP  1m 4s
$ which rp | bat -n
      1    1 rp () {
      2    2     test -e "$1" && realpath "$1" || ge_no_hist=y ceer "$1" realpath
      3    3 }

~/TMP
$ which rp | bat -p                                                                                            0|0
      1 rp () {
      2     test -e "$1" && realpath "$1" || ge_no_hist=y ceer "$1" realpath
      3 }
```

**Comment by sharkdp** [comment]
What did you expect to see?

I guess `which rp` already has line numbers in the output.

**Comment by NightMachinary** [comment]
Of course `which rp` doesn’t have line numbers in its output. I wouldn’t
open an issue if it had.
I have debugged this, the cause is exporting LESS as "-N". bat should not
depend on this environment variable.

**Comment by sharkdp** [comment]
> I have debugged this, the cause is exporting LESS as "-N". bat should not depend on this environment variable.

`bat` does not depend on the `LESS` environment variable. `bat` uses a pager (`less` by default) and `less` uses that environment variable. When `bat` is using `less`, it actually sets a few command line options by default (see README).

We could unset `LESS` before calling `less`, but I think that would not be what most users would expect. The `LESS` command line variable is there to customize your "`less` experience" (the command-line options which are passed to `less` directly take precedence over those that are specified in `LESS`).

By exporting `LESS="-N"`, you explicitly opt-in to seeing line numbers in every `less` invocation.

If you want to keep this behavior, but explicitly opt out of it when `less` is called from `bat`, you could set `BAT_PAGER="less -FRXn"` or add
```
--pager="less -FRXn"
```
to `bat`s config file.

The `-n` option disables line numbering in `less`.

(I haven't tested any of this, as I don't have access to my development environment right now)

**Comment by NightMachinary** [comment]
I do want to see the line numbers in less, but I don’t want it triggered
for short output that doesn’t even open less.

**Comment by sharkdp** [comment]
> I do want to see the line numbers in less, but I don’t want it triggered for short output that doesn’t even open less.

If paging in `bat` is enabled, it always calls `less`. This is due to the fact that `bat` works in "streaming mode" and therefore does not know the length of the file when it starts printing (or piping to `less`). However, we call `less` with the `-F`/`--quit-if-one-screen` option which causes `less` to exit immediately if the output fits on one screen.

I don't really see anything that we could improve on `bat`s side (we could potentially discuss to pass `-n` by default), or do you have any proposal?

Does the suggested solution work for you?

**Comment by NightMachinary** [comment]
Thank you. :-) It works well, and I'm satisfied.

**Comment by NightMachinary** [comment]
I'm closing this issue, but I think a word of warning in readme.md that `bat`'s output is always piped by less might be a good idea. Perhaps specifically mentioning this case. It will be quite confusing if someone doesn't connect the dots.
