### ISSUE TITLE
cargo install bat is failing

### ISSUE THREAD

**Issue by Dowwie** [sharkdp/bat#626]
"cargo install bat" is failing, raising a large number of onig related errors during compilation

debian OS, rustc 1.36.0

**Comment by sharkdp** [comment]
Thank you for reporting this. Which architecture are you on?

I did experience similar errors in the `aarch64` build which I had to temporarily disable (see build logs in #621).

**Comment by sharkdp** [comment]
This could actually be related to https://github.com/rust-onig/rust-onig/pull/105
Hopefully the update to the latest version of syntect (see #628), which includes the newest version of `onig`, fixes this.

**Comment by sharkdp** [comment]
Could you please re-try with the latest master?

**Comment by Dowwie** [comment]
@sharkdp  I'm using debian stretch.  A build of the master branch works.  Thanks for resolving.  bat is a great utility that I use every day.  Please note that the error was first encountered through ``cargo install``, so the crate will require updating too.

**Comment by sharkdp** [comment]
Released as [bat v0.12](https://github.com/sharkdp/bat/releases/tag/v0.12.0).

**Comment by rekka** [comment]
`cargo install bat` still failing on Ubuntu 18.04 due to <https://github.com/rust-onig/rust-onig/issues/109> (bat version `0.12.1`)

**Comment by sharkdp** [comment]
@rekka Thank you for reporting this. Could you please open a new ticket for this?

**Comment by rekka** [comment]
@sharkdp Done in #650.
