### ISSUE TITLE
Is it possible to export this syntax highlithing colors to vim? 

### ISSUE THREAD

**Issue by Migacz85** [sharkdp/bat#627]
Great job
I really like colors that bat have built in - nice, crispy and readable - is that possible to port somehow this colors in to vim ?

Thank You.

**Comment by sharkdp** [comment]
There is no direct way to do this, but you could look for a molokai theme for vim or extract the exact colors from the default sublime theme in `assets/themes`.

**Comment by bahamas10** [comment]
I'm currently looking into a solution for this now - if anyone has done this work please let me know :). otherwise, i'll take a look.

**Comment by papertigers** [comment]
A bit of a hack job but I tried to mimic some of the color scheme for Rust code specifically using the molokai theme.

https://github.com/papertigers/dotfiles/blob/master/vim/colors/monokai-papertigers.vim#L346-L368
