### ISSUE TITLE
Add `cat` to `alternatives.md`

### ISSUE THREAD

**Issue by hofstee** [sharkdp/bat#630]
The alternatives.md file has a bunch of execution times listed for the various cat alternatives, but I think something that I would find useful would be if it also included `cat` itself. Particularly, I can tell relatively how fast all these alternatives are compared to one another, but I have no reference point to how fast cat would be on the machine used for the benchmarks.

**Comment by sharkdp** [comment]
Thanks, we could do that. `cat` will be a few orders of magnitude faster as compared to the other programs. The time it takes to display a file in the terminal via `cat` is actually mostly limited by the terminal emulator itself. This might even be true for some of the syntax-highlighting variants.

The above is to say, it would probably also make sense to add the execution times for "cat compatibility"/throughput mode where we are writing the result to a file. `bat` actually switches to a completely different mode when the output does not go to an interactive terminal (but it's still kind of slow, see #304).

**Comment by sharkdp** [comment]
Noone seems to care too much to really add this entry. Also, the `cat` entry would actually not be very useful (all "features" will be red and the execution time can not really be compared, as `cat` doesn't do syntax highlighting). It will just demonstrate issue #304. I'm closing this for now.
