### ISSUE TITLE
Does not work with Twirl Templates

### ISSUE THREAD

**Issue by AlbaroPereyra** [sharkdp/bat#631]
Greetings Bat gurus,

I've been using Ccat, for a while, yesterday someone mentioned Bat on a ccat issue, and I like it. I am probably moveing over.  That being said I couln't help but notice that Bat does not work with twirl templates.  I know its an obscure request.  Not a lot of software does the highlighting accurately for twirl templates.  Perhaps due to its small market share.  That being said I am a Scala developer and a Play Framework contributor.  It would be nice if Bat supported twirl templates.

You can read more about twirl templates here: 
https://www.playframework.com/documentation/2.7.x/ScalaTemplates
And here: 
https://github.com/playframework/twirl

Please advise, 
Albaro,

**Comment by eth-p** [comment]
Hey Albaro! I think this would fall under the category of adding a new syntax.

It would fall down to @sharkdp if he wants to add an upstream syntax for a template language that doesn't seem to have a large market share, but you can actually add one yourself locally in the meantime!

If you're able to find a `.sublime-syntax` file for Twirl, there's some instructions [right here](https://github.com/sharkdp/bat/blob/master/README.md#adding-new-syntaxes--language-definitions) for adding custom syntaxes. If you can't find a syntax for it, someone might be able to convert a .tmLanguage file or modify the syntax file for [EJS](https://github.com/nwoltman/sublime-ejs?files=1) into one for Twirl?

**Comment by sharkdp** [comment]
> It would fall down to @sharkdp if he wants to add an upstream syntax for a template language that doesn't seem to have a large market share, but you can actually add one yourself locally in the meantime!

As a proxy for "popularity", I was typically using the number if "Installs" on https://packagecontrol.io/. This is obviously not a perfect metric, but I want to have a rough filter in order to keep the number of syntaxes in a reasonable range.

Unfortunately, I can not find a package for "Twirl" on packagecontrol.io.

**Comment by sharkdp** [comment]
I'm going to close this for now, but I can re-open it if there is an existing syntax and some indication that this is used by a significant amount of people.
