### ISSUE TITLE
Add Scss to syntax list

### ISSUE THREAD

**Issue by snide** [sharkdp/bat#637]
[Sass](https://sass-lang.com/) is arguably the most used CSS pre-processor used. It's over a decade old and likely makes sense as a Bat default given the other common web-stack syntaxes available in Bat.

I found this library made by the same author of the [LESS](https://github.com/danro/LESS-sublime) syntax currently used within bat. Hopefully a pretty easy add.

https://github.com/danro/SCSS-sublime

**Comment by sharkdp** [comment]
Sounds good! The instructions are [here](https://github.com/sharkdp/bat/tree/master/assets) if someone wants to work on this.

**Comment by snide** [comment]
I'll give it a shot!

**Comment by snide** [comment]
Hey, thanks!

**Comment by sharkdp** [comment]
Released in [bat v0.12](https://github.com/sharkdp/bat/releases/tag/v0.12.0).

**Comment by snide** [comment]
Configured working in bat 0.12 through brew. TY for building open source. I appreciate your work.

![image](https://user-images.githubusercontent.com/324519/64078941-fe4a8200-cc95-11e9-9efb-166e2ad986c5.png)
