### ISSUE TITLE
How to use Git integration?

### ISSUE THREAD

**Issue by doggy8088** [sharkdp/bat#64]
The bat looks like can't accept STDIN to input.  I don't know how to setup Git integration.  Can you give ma hint?  Thanks!

**Comment by sharkdp** [comment]
> The bat looks like can't accept STDIN to input.

How is this related to the title of the ticket? Please see #2.

> I don't know how to setup Git integration.

Git integration should work out of the box (but note that #22 is not yet fixed).

Just call `bat` on a file that has any changes with respect to the Git index.

**Comment by doggy8088** [comment]
@sharkdp Wow, I see.  That's the way to use it. Thanks! :)
