### ISSUE TITLE
Handle compressed files

### ISSUE THREAD

**Issue by g2p** [sharkdp/bat#642]
This could be done by integrating with lesspipe / LESSOPEN at first.

**Comment by sharkdp** [comment]
Please see #237

If you think there is a nice way to build a wrapper script that supports that, I'm happy to add it to the repository.

**Comment by anarcat** [comment]
> If you think there is a nice way to build a wrapper script that supports that, I'm happy to add it to the repository.

i did https://github.com/sharkdp/bat/pull/3177
