### ISSUE TITLE
v0.12.0 is not working on Windows 7

### ISSUE THREAD

**Issue by jfcherng** [sharkdp/bat#643]
It just prompts an error box: 
```
The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll
```
`v0.11.0` works well btw.

![image](https://user-images.githubusercontent.com/6594915/64076768-7bf4a900-ccfb-11e9-9c4a-4ec1dbd1b8b6.png)

---

The following is what I can find.

> Actually the CreateFile2 function is started to be used from Windows 8. So you can't find an entry point of this method in Win7 Kernal32.dll. Have you tried to use CreateFile which could be used in Win7 instead of it?

From https://social.msdn.microsoft.com/Forums/officeocs/en-US/47470316-5868-4e6e-a62f-6b880c46d824/creating-exe-vcxproj-in-win-7-the-procedure-entry-point-ltfunctiongt-could-not-be-located-in?forum=vcgeneral#76d55530-70a6-41ab-9687-5f4129e0c79c

**Comment by sharkdp** [comment]
Thank you for reporting this.

This could be related to an update in `ansi_term` which introduced these lines:
https://github.com/ogham/rust-ansi-term/blob/6755eaa7a1977caabf3013db3a3e08e11acface9/src/windows.rs#L28-L34

Ideally, this should be reported upstream in the ansi_term repo.

As a short-term measure, I think we could downgrade to an older version of ansi_term.

**Comment by jfcherng** [comment]
They seem to have this issue resolve in https://github.com/ogham/rust-ansi-term/issues/54.

**Comment by sharkdp** [comment]
Well, the PR is not yet merged and there is no new version we could depend on. Let's re-open this ticket until we have a fix in `bat` (either by downgrading or by upgrading to a future version).

**Comment by rivy** [comment]
The PR ([#52](https://github.com/ogham/rust-ansi-term/issues/52)) that should fix the issue has been merged into master for `ansi-term`.

Upgrading to `ansi-term` v0.12.1 should repair the issue for `bat`. Let me know if there's still a problem and I'll look at it again.

**Comment by sharkdp** [comment]
@rivy Thank you!

New release is out: [bat v0.12.1](https://github.com/sharkdp/bat/releases/tag/v0.12.1)

**Comment by jfcherng** [comment]
@sharkdp Yes, `v0.12.1` works. Thanks you guys.
