### ISSUE TITLE
macOS man pager issues

### ISSUE THREAD

**Issue by zackhsi** [sharkdp/bat#645]
Hello, I've configured `MANPAGER` according to the [README](https://github.com/sharkdp/bat#man), but do not see the [expected results](https://github.com/sharkdp/bat/issues/523#issuecomment-473100603).

![image](https://user-images.githubusercontent.com/806101/64138163-659b3a00-ce2e-11e9-84b5-c201a7dcd7ad.png)

Separately, the man pages from coreutils (installed via brew, configured via `export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH`) are incompatible with the `bat` as `MANPAGER`.

`man 2 select` is not available in coreutils, so I've used `man dirname` in the following screenshot:

![image](https://user-images.githubusercontent.com/806101/64138279-f540e880-ce2e-11e9-8c54-ce19d5ea1a2d.png)

Thanks for the project!

**Comment by sharkdp** [comment]
The result in screenshots do not look too bad, IMO. It could be just the `bat` syntax highlighting theme which does not support all of the colorizations I've chosen (which could certainly be improved). Which theme are you using? Could you try to select a different one?

**Comment by sharkdp** [comment]
@zackhsi any update on this? I'm going to close it, but happy to reopen if it is not resolved.

**Comment by sharkdp** [comment]
a few improvements were made to the man-pager README section, so it might be worth to have a second look.

**Comment by zackhsi** [comment]
@sharkdp thanks for the README updates.

I believe my trouble is supporting both the macOS _and_ coreutils syntaxes (`brew install coreutils`). While I'm able to get the ~same highlighting for the macOS manpages, the bat-based highlighting for coreutils pages is not quite as good as [other solutions](https://news.ycombinator.com/item?id=12296000).

Thanks for the excellent tool -- I use it extensively :)

**Comment by sharkdp** [comment]
If you think there is anything specific that we could fix, please let us know. Have you tried to set `MANROFFOPT="-c"`?

**Comment by zackhsi** [comment]
Yep, I've set MANROFFOPT.

Here's what the macOS man page for `select` looks like. The code bits look OK, but I expect the section headers to stand out, and for things like `FD_ISSET` to be colored consistently.

![image](https://user-images.githubusercontent.com/806101/67952872-f91f9a00-fc28-11e9-8626-65d9e0a85b4f.png)

**Comment by sharkdp** [comment]
> The code bits look OK, but I expect the section headers to stand out

I think this is a problem with the "TwoDark" theme. Could you please try a different theme (e.g. `"Monokai Extended"` or `"Dracula"`).

> and for things like `FD_ISSET` to be colored consistently.

I think that's an actual problem with the highlighting. It would be great if you could open a new ticket for this.

**Comment by sharkdp** [comment]
> > and for things like `FD_ISSET` to be colored consistently.
> 
> I think that's an actual problem with the highlighting. It would be great if you could open a new ticket for this.

Should be fixed with #718
