### ISSUE TITLE
GraphQL syntax not working in latest release 0.12.1

### ISSUE THREAD

**Issue by Sarcasm** [sharkdp/bat#647]
Hello,

The 0.12 release notes mention GraphQL support (from #625), however, after install the 0.12.1 musl version, GraphQL does not seem to be supported:

    $ bat -L | egrep -i 'gql|graphql|org'
    orgmode:org

Is it a packaging issue?

**Comment by sharkdp** [comment]
Thank you for reporting this.

> Is it a packaging issue?

Yes, my bad. I just ran `git submodule init; git submodule update` and just then it pulled the GraphQL repo as a submodule. It will be included in the next release.

In the meantime, you can use
```
mkdir -p "$(bat --config-dir)/syntaxes"
cd "$(bat --config-dir)/syntaxes"
git clone https://github.com/dncrews/GraphQL-SublimeText3.git
bat cache --build
```
to add it locally.

**Comment by Sarcasm** [comment]
Closing, thank you for the explanation and workaround. :+1:
