### ISSUE TITLE
cmake no longer build dependency

### ISSUE THREAD

**Issue by lilyball** [sharkdp/bat#649]
At least as of bat 0.12.0 (quite possibly sooner) `cmake` is no longer a build dependency of `bat`. The Nix package [updated](https://github.com/NixOS/nixpkgs/pull/67868) its derivation to require `libclang` but to remove `cmake`, and it builds just fine this way. The README should be updated accordingly.

**Comment by sharkdp** [comment]
Yes, thank you for reporting this.
