### ISSUE TITLE
Parameterize bat name, documentation.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#659]
In order to make life easier on package maintainers, we should give them the ability to easily rename bat and its documentation when building a package.

- [x] Rename the man page
- [x] Parameterize the executable name in the man page
- [x] Rename the completions
- [x] Parameterize the executable name in the completions
- ~~Rename the executable~~
  This is too hacky with cargo.
  Just use an external shell script.

---

This issue is derived from https://github.com/sharkdp/bat/issues/656

**Comment by eth-p** [comment]
@sharkdp To make this easier to implement and more configurable for package maintainers, should we create a series of scripts to build the packages for each kind of package manager?

You already have something similar going on in your CI scripts, and I could probably adapt them to work as command line scripts like `build.sh` in bat-extras.

**Comment by sharkdp** [comment]
>     * Parameterize the `BAT_` environment variables

As discussed in #656, I think the environment variables should not be parametrized.

I think the shell completion script(s) might also need parametrization.

> @sharkdp To make this easier to implement and more configurable for package maintainers, should we create a series of scripts to build the packages for each kind of package manager?

I'd really rather not be involved in package management issues. We certainly help package managers with specific issues that appear when they want to package `bat`, but I (personally) don't want to maintain any distribution-specific things in this repository (or any other). The Debian packages are an exception to that, as (1) it is a very large user base and (2) there is no official `bat` package yet.

**Comment by eth-p** [comment]
I removed a couple of the list items that related to packaging or parameterizing the environment variables.

> I'd really rather not be involved in package management issues. We certainly help package managers with specific issues that appear when they want to package bat, but I (personally) don't want to maintain any distribution-specific things in this repository (or any other). The Debian packages are an exception to that, as (1) it is a very large user base and (2) there is no official bat package yet

That's fair. It would be unnecessary overhead for `bat` maintainers, and creating packaging scripts would be better left to the package maintainers who know their ecosystems better.

**Comment by paride** [comment]
I agree this can and should be made in a distro-agnostic way. Having a single place (e.g. a variable) where the binary name is defined would be file. Applying a simple patch is not a problem at all, the difficult part in the current state would be going through all the places where the `bat` string is used and replace it with `batcat` when appropriate, and keeping this up to date with the newer versions.

For the manpage, could a rust templating library be used to generate the manpage file with the correct command name in it?

In general I'm trying to think of a solution that we'll be then able to use in for `fd` too.

Thanks for your help here!
