### ISSUE TITLE
Disable colorization for "plain text" syntax

### ISSUE THREAD

**Issue by kurkale6ka** [sharkdp/bat#665]
Hi,

When using bat to output plain text, it is rendered in bold. IMHO it would be better to not use any formatting or at least to have the option to do so.

Regards

**Comment by sharkdp** [comment]
Thank you for your feedback. Plain text should not be printed in bold. Could you please tell us how to reproduce this? Which version of bat do you have? How did you call bat? How does the input file look like (are you sure it does not contain any ANSI escape sequences?), etc.

**Comment by kurkale6ka** [comment]
I am on Mac OS Mojave 10.14.6, iTerm 2 3.3.4

```
% brew info bat
bat: stable 0.12.1 (bottled)
Clone of cat(1) with syntax highlighting and Git integration
https://github.com/sharkdp/bat
/usr/local/Cellar/bat/0.12.1 (7 files, 4.8MB) *
  Poured from bottle on 2019-09-19 at 13:32:27
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bat.rb
==> Dependencies
Build: rust ✘
==> Analytics
install: 14,399 (30 days), 22,717 (90 days), 106,154 (365 days)
install_on_request: 14,379 (30 days), 22,683 (90 days), 105,947 (365 days)
build_error: 0 (30 days)
```
```
% bat -V
bat 0.12.1
```

![Screenshot 2019-09-22 at 20 54 22](https://user-images.githubusercontent.com/52182/65393663-73801300-dd7b-11e9-9970-87fee305e9ab.png)

When first using bat I had the impression that plain text was bold but actually now I had quite a difficult time to see a difference. Still, it seems that text isn't exactly bold but bolder than plain. A gradient of sort is visible in the image above

**Comment by sharkdp** [comment]
Thank you for the update.

I think I know what this is. The text is not bold, it is white :smile:

I forgot about that. `bat` actually *does* colorize plain text (in white). We can see that it outputs an ANSI escape sequence by using `bat -A`:
```
> bat --color=always -p <<< 'Hello' | bat -Ap
␛[38;2;248;248;242mHello␛[0m␊
```

The 38;2;248;248;242 is interpreted as `38;2;<r>;<g>;<b>`. So `bat` outputs plain text in `rgb(248,248,242)` or `#f8f8f2`. This is the "foreground color" of the default theme (might be different for you if you use another scheme).

There's actually a tiny difference for me on Linux/Terminator as well.

I'm not quite sure how to handle this. I guess we could completely disable colors for the actual content part (not the grid, etc.) if the language is "plain".

**Comment by sharkdp** [comment]
Going to close this for now, as there is no further feedback and I don't think it's a particularly important issue.

**Comment by kurkale6ka** [comment]
Hi,

Sorry for the lack of feedback.
For sure this issue might seem minor as it only affects how stuff is rendered but that's all bat is about :-P. Right now bat isn't a drop in replacement for cat since it produces 'different' output. On my terminal output looks bold, like 'pay attention, all this is super important'...

In fact this issue is the reason why I don't alias cat to bat. I still use bat when I want some small text file to be output with colors but it would be so much easier to just use cat for everything.

> I guess we could completely disable colors for the actual content part (not the grid, etc.) if the language is "plain".
yes, that would be ideal. I can try to create a pull request if it's likely to be merged...

**Comment by sharkdp** [comment]
>  For sure this issue might seem minor as it only affects how stuff is rendered but that's all bat is about :-P. Right now bat isn't a drop in replacement for cat since it produces 'different' output. On my terminal output looks bold, like 'pay attention, all this is super important'...

From your screenshot, it just looks white; not bold. Anyway.. every `bat` theme has a default "foreground color". If you don't like the white part, you can use the `ansi-dark`/`ansi-light` themes (or the `base16` theme), which should use your default terminal foreground color.

**Comment by kurkale6ka** [comment]
Right. I use zenburn actually and I guess it's not possible to change only the fg color for that theme?
But also when printing a file with a non supported language I think it makes sense not modify the output in any way

**Comment by sharkdp** [comment]
Ok, I'm reopening this, so others can express their opinion.

> I use zenburn actually and I guess it's not possible to change only the fg color for that theme?

Not without manually modifying the theme (which works fine with `bat cache --init`, see README). There is an open issue that addresses this: #339

**Comment by mcarton** [comment]
This behavior also makes`bat` unusable with a clear-background terminal:

![image](https://user-images.githubusercontent.com/3751788/80584814-914cdf00-8a12-11ea-92e2-420eadbf66fc.png)

"test" is visible with a slightly different shade of white.

**Comment by sharkdp** [comment]
> This behavior also makes`bat` unusable with a clear-background terminal:

Please see https://github.com/sharkdp/bat#highlighting-theme

> bat looks good on a dark background by default. However, if your terminal uses a light background, some themes like GitHub or OneHalfLight will work better for you.

**Comment by sharkdp** [comment]
Closing this for now, as I don't think this is a big issue.
