### ISSUE TITLE
complication error on ppc64le architecture

### ISSUE THREAD

**Issue by jftuga** [sharkdp/bat#682]
I am trying to compile `bat` on Ubuntu 18.04.3 LTS on this system:

    Linux  4.15.0-65-generic #74-Ubuntu SMP 
    Tue Sep 17 17:08:54 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

I am using `rustc 1.38.0 (625451e37 2019-09-23)`.

When I run `cargo install bat`, it compiles many packages but then eventually stops with this error:

    Compiling bat v0.12.1
    Compiling git2 v0.10.1
    Compiling onig_sys v69.2.0
    error: failed to compile `bat v0.12.1`, intermediate artifacts can be found at `/tmp/cargo-installSOXqiB`
    
    Caused by:
      failed to run custom build command for `onig_sys v69.2.0`
    
    Caused by:
      process didn't exit successfully: `/tmp/cargo-installSOXqiB/release/build/onig_sys-865c2293ec1afe7e/
      build-script-build` (exit code: 101)
    --- stdout
    cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
    cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
    
    --- stderr
    thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: 
    [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where 
    one of these files can be found (invalid: [])"', src/libcore/result.rs:1084:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

What do I need to do in order to fix this error? Alternatively, is there another way I can install a prebuilt binary?

Thank you.

**Comment by jftuga** [comment]
I install llvm with `apt install llvm`.  I got past this issue, but now see this error message:

    error: failed to compile `bat v0.12.1`, intermediate artifacts can be found at `/tmp/cargo-installxHsheH`

    Caused by:
      failed to run custom build command for `onig_sys v69.2.0`

    Caused by:
      process didn't exit successfully: `/tmp/cargo-installxHsheH/release/build/onig_sys-865c2293ec1afe7e/build-script-build` (exit code: 101)
    --- stderr
    thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1084:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by sharkdp** [comment]
Thank you for the feedback and for posting the solution. It would be great if we could add this to the README.

**Comment by sharkdp** [comment]
With #650 closed, installing `libclang` should not be needed anymore.

**Comment by sharkdp** [comment]
Released in [bat v0.15.2](https://github.com/sharkdp/bat/releases/tag/v0.15.2).
