### ISSUE TITLE
Autocompletion doesn't work well

### ISSUE THREAD

**Issue by kud** [sharkdp/bat#683]
Version: `0.12.1`

When I type: `$ bat i<tab>` for ip.csv, I've got this:

```
bat ip(eval):1: command not found: _bat
(eval):1: command not found: _bat
(eval):1: command not found: _bat
```

![Kapture 2019-10-09 at 18 09 20](https://user-images.githubusercontent.com/655838/66499420-16e15f80-eac0-11e9-9df4-9945485df099.gif)

**Comment by sharkdp** [comment]
I guess this is a duplicate of #503

**Comment by kud** [comment]
Sounds to be yes! Thanks!
