### ISSUE TITLE
Style stdin as Python file?

### ISSUE THREAD

**Issue by reckoner** [sharkdp/bat#686]
cat foo.py | bat 

In this case `bat` does not know the file extension. Yes, I realize that I could do `bat foo.py` but I have  simplified my problem down to this issue. I would like `bat` to syntax highlight  the standard input as a Python file (or other supported file type). Is this possible?

**Comment by sharkdp** [comment]
Yes. Use the `--language` option to specify the language:
```bash
cat foo.py | bat -lpy
```

Alternatively, use a modeline/shebang in the first line of your Python script:
```python
#!/usr/bin/env python

…
```
