### ISSUE TITLE
Feature request: command line option for dark / light theme or theme selection

### ISSUE THREAD

**Issue by draptik** [sharkdp/bat#689]
Sorry if I missed something in the documentation: Thankful for pointers!

During presentations I often switch between dark and light themes in the terminal (gnome-terminal, urxvt, kitty).

The default theme is optimized for dark background colors.

Can we have a command line option to use a theme optimized for light colored background?

**Comment by clarfon** [comment]
One thing that might be good is to be able to set the preferred dark and light themes separately, and to simply switch between them using a flag or some environment variable.

**Comment by sharkdp** [comment]
> Sorry if I missed something in the documentation: Thankful for pointers!

We have decided not to include support for this in `bat` directly (see #641). But there is this: https://github.com/sharkdp/bat#dark-mode

It only works on macOS, so far, but maybe it could be extended to support other terminal emulators as well.

> One thing that might be good is to be able to set the preferred dark and light themes separately, and to simply switch between them using a flag or some environment variable.

That is not possible. Once you see the output in the pager, `bat` has already finished. The program that you are seeing is `less`.

**Comment by clarfon** [comment]
@sharkdp I meant before bat is run, e.g. a command line flag or environment variable before bat is run. :p

**Comment by sharkdp** [comment]
> @sharkdp I meant before bat is run

For some reason I thought you wanted to switch dark/light with a key :smile:. Must have misread your comment.

> e.g. a command line flag or environment variable before bat is run

That's pretty much what is suggested in https://github.com/sharkdp/bat#dark-mode, right?

**Comment by draptik** [comment]
Thanks for the feedback!
I completely missed the `bat --theme=GitHub..` option.
Sorry for the noise!

**Comment by bric3** [comment]
I think the prhasing is incorrect 

> If you make use of the dark mode feature in macOS, you might want to configure bat to use a different theme based on the OS theme. The following snippet uses the default theme when in the light mode and the GitHub theme when in the dark mode.

Because  `defaults read -g AppleInterfaceStyle` will only return `Dark` if the dark mode is active, otherwise there is an _error_ message. So the following command 

```bash
bat --theme="$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo default || echo GitHub)"
```

will instead make bat use 

* **default** in dark mode
* **Github** in light mode

**Comment by bric3** [comment]
I think the prhasing is incorrect 

> If you make use of the dark mode feature in macOS, you might want to configure bat to use a different theme based on the OS theme. The following snippet uses the default theme when in the light mode and the GitHub theme when in the dark mode.

Because  `defaults read -g AppleInterfaceStyle` will only return `Dark` if the dark mode is active, otherwise there is an _error_ message. So the following command 

```bash
bat --theme="$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo default || echo GitHub)"
```

will instead make bat use 

* **default** in dark mode
* **Github** in light mode

**Comment by eth-p** [comment]
> I think the prhasing is incorrect 
> 
> > If you make use of the dark mode feature in macOS, you might want to configure bat to use a different theme based on the OS theme. The following snippet uses the default theme when in the light mode and the GitHub theme when in the dark mode.
> 
> Because  `defaults read -g AppleInterfaceStyle` will only return `Dark` if the dark mode is active, otherwise there is an _error_ message. So the following command 
> 
> ```bash
> bat --theme="$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo default || echo GitHub)"
> ```
> 
> will instead make bat use 
> 
> * **default** in dark mode
> * **Github** in light mode
> 
> 

Good catch. Do you want to make a PR to fix that and I'll merge it, or would you prefer one of us do it?

**Comment by bric3** [comment]
@eth-p Done in https://github.com/sharkdp/bat/pull/933
