### ISSUE TITLE
Feature request: ZED like new file creation

### ISSUE THREAD

**Issue by lordrook** [sharkdp/bat#690]
The new file creation is quite handy, but it has few shortcoming:

- Too easy to override an existing file.
- No support for navigating in the editing pane with arrows.
- Backspace does not return cursor to a previous line.
- No colors.

> bat > note.md  # quickly create a new file

On the above command, I would be great to have the following functionality.

- If file exists, display its content in the editing pane (colored as per file extension).
- If file does not exist, apply coloring schema as per file extension.
- Allow for vertical and horizontal navigation with arrows.
- Allow for vertical navigation withe the return and backspace.

The above can be seen in 'zed' command line editor:
https://github.com/zsh-users/zsh/blob/master/Functions/Misc/zed

Let me know if that's doable!

BR
ldrk

**Comment by sharkdp** [comment]
That's not possible. As soon as you write
```
anything > note.md
```
The file `note.md` will be overwritten. The program `anything` will never even have the chance to read its contents.

Also, `bat` is not an editor and we are not planning to integrate functionality for it.
