### ISSUE TITLE
Show files side by side?

### ISSUE THREAD

**Issue by jabbalaci** [sharkdp/bat#692]
I would like to display 2 files vertically, side by side. I found a solution here: https://stackoverflow.com/questions/13341832/display-two-files-side-by-side , however, it has no syntax highlighting. Would it be possible to use bat for this purpose?

Motivation: when I learn a new programming language, I like to compare it to the one that I know the best. So I'd like to show a code snippet on the left in language A, and its equivalent on the right side in language B.

**Comment by eth-p** [comment]
With the way `pr` merges the two files onto the same line, bat won't be able to correctly parse the syntax. I suspect that it would likely be the same for vimcat and other highlighting tools, unfortunately.

If you use a terminal that supports panes (e.g. iTerm), that would probably be the best way to display two highlighted files next to each other. An alternative would be to use `screen` or `tmux` and create two side-by-side panes, then print the files in each pane using bat.

**Comment by jabbalaci** [comment]
Is it possible to do the syntax highlighting with bat and then save the colored output (with the funny Linux color codes) to a file? If yes, then I could write a program that merges the files line by line and outputs to the screen.

If possible, I would like to avoid tmux, but that's also a good idea.

**Comment by rusty-snake** [comment]
@jabbalaci `cat` has colored output:
```
$ bat --color=always --plain main.rs > main.bat  
$ cat main.bat 
fn main() {
    println!("Hello, World!");
}
```

**Comment by jabbalaci** [comment]
I found a way to save the Linux color codes too:

    $ s=$(bat --color=always --plain main.rs)
    $ echo $s > /tmp/a.txt
    $ \cat /tmp/a.txt

And the content of `/tmp/a.txt` contains the funny Linux color codes.

Now I can progress with merging two files and keeping the syntax colors of both files, even if they are colored differently. Thanks for the help.

**Comment by jabbalaci** [comment]
Following the ideas in this thread, I made a project called melt that can place two files side by side and syntax color them independently. melt uses bat, of course. You can find it here: https://github.com/jabbalaci/melt .

**Comment by sharkdp** [comment]
Glad to see that you managed to find a solution to your own problem :smile:. Good luck with the project - looks great :+1:

**Comment by sharkdp** [comment]
> I found a way to save the Linux color codes too:
> 
> ```
> $ s=$(bat --color=always --plain main.rs)
> $ echo $s > /tmp/a.txt
> $ \cat /tmp/a.txt
> ```

that can be shortened to:
```
$ bat --color=always --plain main.rs > /tmp/a.txt
$ \cat /tmp/a.txt
```
as @rusty-snake also pointed out
