### ISSUE TITLE
"--style changes" does not "show only Git changes" but show every single line

### ISSUE THREAD

**Issue by zachliu** [sharkdp/bat#694]
The "to show only Git changes" in README is misleading. Using `--style changes` still prints out everything in the changed file. It just gives you the `~` and `+` symbols on the left. If your file is large, this option doesn't actually help.

On `bat 0.12.1`

**Comment by sharkdp** [comment]
What was meant was: *"… to show only the Git modifications markers in the sidebar …"*.

I think what you want is #23.

**Comment by zachliu** [comment]
lol, totally forgot about "hunks" in git. and yes, #23 is exactly what i want
