### ISSUE TITLE
gitlog format doesn't highlight diffs

### ISSUE THREAD

**Issue by tmccombs** [sharkdp/bat#695]
When used as a pager for `git log` bat doesn't highlight diffs if diffs are included (for example with --patch option). I would expect it to highlight diffs in the log output the same as a diff would be formatted.

**Comment by sharkdp** [comment]
Related: #23 #274 https://github.com/sharkdp/bat/issues/440#issuecomment-445336634 #334

Also related: A really cool project which is partially based on `bat`s source code: https://github.com/dandavison/delta

**Comment by tmccombs** [comment]
Oh, I didn't know about delta. I'll definitely take a look at that.

**Comment by tmccombs** [comment]
update: I've tried delta, and I love it.
