### ISSUE TITLE
Cannot edit standard input (Press RETURN)

### ISSUE THREAD

**Issue by thioshp** [sharkdp/bat#697]

**Comment by thioshp** [comment]
Bat shows the abovd message whenever I press v to edit a file. How do I solve this?

**Comment by eth-p** [comment]
This isn't an error I would've ever expected to come across, and I'm not even sure where to begin with debugging it. Is it possible to provide some steps on how to reproduce it so we can better understand what's going on here?

If possible, can you also tells us what version of bat, and what operating system/distro you're using?

**Comment by sharkdp** [comment]
This is not a bug. That's the v key in less. Please see #528, #358, ...

**Comment by ZiddiBlaze** [comment]
[#[](url)](url)
![Screenshot_72](https://user-images.githubusercontent.com/75930181/103442092-17dc4f00-4c79-11eb-8350-7963031628df.png)

**Comment by siran** [comment]
Oh I see the issue. You are piping through less, so the `v` command can't really edit anything.

**Comment by siran** [comment]
However, depending how you are doing the piping, you can do, for example:

    cat testfile | less -s testfile 

Then, pressing `v` would open the editor and edit `testfile` (which is the file whose contents your piping...)
