### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by KaKi87** [sharkdp/bat#699]
Hey.

I've just installed *bat* on freshly installed KDE Neon 5.17.1 (Ubuntu-based) and put `eval $(thefuck --alias)` into my `~/.bash_aliases` file.

Here's what I got :

```
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Thanks

**Comment by eth-p** [comment]
That looks like a Python stack trace, which is somewhat odd since `bat` is written in Rust and doesn't call any external programs except `less`.

What package did your `thefuck` script come from?

**Comment by KaKi87** [comment]
Oh wait it was late and I was tired this issue isn't supposed to be here because totally unrelated to bat. Sorry for the inconvenience
