### ISSUE TITLE
Apply Clojure (clj) syntax rules to Clojurescript (cljs)

### ISSUE THREAD

**Issue by sheluchin** [sharkdp/bat#702]
Clojure and Clojurescript should get the same syntax highlighting. Clojure support is already available:

```
$ bat --list-languages
...
Clojure                   clj
```

cljs just needs to be mapped in. Thanks!

**Comment by neslinesli93** [comment]
Hi! I'm on master, and that's what I see:

```bash
$ bat --list-languages
...
Clojure                              clj, cljc, cljs, edn
```

This is the output from master, which is on version `0.12.1`. What version are you using?

**Comment by sheluchin** [comment]
@neslinesli93 ah, I'm not on latest. Thanks!
