### ISSUE TITLE
Bat does not work as file viewer for Midnight Commander for small files

### ISSUE THREAD

**Issue by mkaut** [sharkdp/bat#710]
I tried to use bat as a file viewer for Midnight Commander (mc), but it does not work for some files - they get opened and close immediately.
As far as I can see, this happens for files that are short enough to not require scrolling - I guess that shorter files exit immediately, while files with scrolling wait for user input.

Is there some way around this, so one could use bat in mc?

**Comment by sharkdp** [comment]
The problem is that we pass the `-F`/`--quit-if-one-screen` option to `less`. This causes the pager to quit when the file content is smaller than the vertical screen size.

If you put this in a script, it should work as a viewer:
``` bash
#!/bin/bash

bat --paging=always --pager="less -R" "$@"
```

Here, we explicitly tell `bat` to call `less -R` (instead of `less -FRX`). This should also take care of cleaning the screen.

**Comment by mkaut** [comment]
I can confirm that @sharkdp's script works without any apparent side effects.
Thanks for a quick response :-)

**Comment by for-coursera** [comment]
However, this wont work if the shell variable `$LESS` is set and contains an option to actually exit pager :)

Like, in my shell I prefer to always exit paging automatically BUT if used in a file manager, for example, then obviously I'd like to always keep paging (which means it would be great somehow to tell `bat` to ignore `$LESS` via the command line options).

Any ideas how to resolve this ambiguity may be? :)

**Comment by sharkdp** [comment]
command-line arguments to `less` should overwrite settings in `$LESS`?

**Comment by for-coursera** [comment]
Well, I'm probably wrong somewhere then but for me, this doesn't happen. Let's say, I have this in my `.profile`:

    export PAGER=less
    export LESS='-i -e -F -R -M -X -P%t?f%f :stdin .?pb%pb\%:?lbLine %lb:?bbByte %bb:-...'
    export LESSHISTFILE=-

And when I run `less -R ~/some_short_file`, `less` automatically exits.

**Comment by sharkdp** [comment]
Quoting from the man page:
```
       The environment variable is parsed before the command line, so command line  options
       override  the LESS environment variable.  If an option appears in the LESS variable,
       it can be reset to its default value on the command line by  beginning  the  command
       line option with "-+".
```

**Comment by for-coursera** [comment]
Love you :) Thanks!

(And sorry for my ignorance.)

**Comment by zoulja** [comment]
Hey @mkaut how exactly you were able to configure bat as the viewer?

**Comment by mkaut** [comment]
I just saved the code from @sharkdp as `mc-bat.sh` and then added `export VIEWER=mc-bat.sh` to `.profile`.
It works on my laptop, not on a remote box that I connect to via ssh...
