### ISSUE TITLE
Map meson syntax

### ISSUE THREAD

**Issue by dartheian** [sharkdp/bat#713]
I would like to map my "meson.build" files to python syntax.
I've tried the following without success:

* `-m=build:python`
* `-m=meson.build:python`

**Comment by sharkdp** [comment]
You need to map to another file extension (`py`) instead of a syntax name (`python`). We should probably try to improve this by also allowing `-m=extension:syntax-name`, like you tried.

**Comment by dartheian** [comment]
Thank you, it works. I also suggest to update the documentation man page with less "ambiguous" examples, like the Python one you used here, in which the simplified syntax name `python` is different from the file extension `py`. In the examples you use `ini` and `gitignore` which are, at the same time, file extensions and syntax names (yes, the correct syntax names should be INI and Git Ignore, but we usually refer to them in the simplified form).
