### ISSUE TITLE
Indented wrapping

### ISSUE THREAD

**Issue by tbrodbeck** [sharkdp/bat#714]
I really like using bat. Often I use it as a pager. It is good that it softwraps lines by default.
But it would be better to have indented wrapping (keeping/or adding a bit of the indentation of the wrapped line) aka. adaptive wrapping. Most editors/IDEs are doing that.

Do you know what I mean or should I include a picture for clarification?

**Comment by eth-p** [comment]
To do this properly would require some kind of awareness with the language being printed. It can be done in a naïve fashion by just adding one extra indent level, but adding support for it would likely need some refactoring in the printer.

I don't know if anybody else would be willing to try and implement this, but I would be happy to try it once the `bat`-as-a-library changes and refactoring are finalized.

**Comment by sharkdp** [comment]
Wrapping with indentation on a character-level would look pretty weird, I think. If we would really like to implement this, I think we would need "token"-level wrapping, which is a whole different game.

**Comment by eth-p** [comment]
I'm with @sharkdp on this. Not to mention, wrapping on a character level can make the code less clear in certain scenarios:

```python
// ...
    "this is a string with exactly 8 spaces: [        ] "
```

Could turn into the following:
```python
// ...
    "this is a string with exactly 8 spaces: [    
        ]"
```

With that, the string literal that `bat` prints is no longer the same literal that it was in the source code. As a tool intended to be a drop-in replacement for `cat`, I feel that it would be better to avoid introducing features that have the possibility of obscuring source code.

If we can find a way to have syntax-aware token-level wrapping, I would absolutely love to see that feature implemented, however.
