### ISSUE TITLE
Layout is breaking up

### ISSUE THREAD

**Issue by tuangu** [sharkdp/bat#715]
When I'm viewing a file with 100 000 lines, the layout is breaking up when jumping to the end.

Steps to reproduce:
- Open a file with 100000 lines (for example: [1-100000 integers](https://lagunita.stanford.edu/assets/courseware/v1/20264e13e73a87dda60e8701d9f2c521/asset-v1:Engineering+Algorithms1+SelfPaced+type@asset+block/IntegerArray.txt))
- Jump to the end of file

Terminal emulator: Xfce4 terminal
Screenshots: 
![2019-11-03_1920x1080_scrot_000](https://user-images.githubusercontent.com/14976190/68087782-12a72880-fe59-11e9-88d2-f4d5068b2411.png)

**Comment by eth-p** [comment]
Unfortunately, that's unavoidable. The sidebar width needs to be calculated and known by the time the first line is drawn.

Bat was designed to avoid bufferring its input, and as a consequence, isn't able to calculate the number of lines (and line number component width) in advance. 

I think a reasonable default (4 digits/9999 lines) was chosen, but feedback is always welcome.

**Comment by tuangu** [comment]
Thanks for your explaination. Do you think whether I should close this issue or leave it opens for more discussion?

**Comment by eth-p** [comment]
I'm fine with keeping it open as a point of discussion, but I'll leave that decision up to @sharkdp.

**Comment by sharkdp** [comment]
Let's close this for now. We could "paint" some sort of connector that lines up the two grids, but I don't think that's worth it. I also don't want to further increase the sidebar width.
