### ISSUE TITLE
Evaluate LTO

### ISSUE THREAD

**Issue by bolinfest** [sharkdp/bat#719]
Consider adding the following to `Cargo.toml` to improve performance / reduce binary size:

```
[profile.release]
lto = true
```

**Comment by sharkdp** [comment]
Benchmark on a random subset of files in the `bat` repo.

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./bat-no-lto --color=always src/*.rs README.md Cargo.toml` | 231.8 ± 2.2 | 227.4 | 235.3 | 1.09 ± 0.01 |
| `./bat-lto --color=always src/*.rs README.md Cargo.toml` | 213.5 ± 1.8 | 209.7 | 216.1 | 1.00 |

That's a solid 10% speedup. Nice.

Compile time (release build from scratch, including all dependencies):
* without LTO: 2min 31sec
* with LTO: 3min 7sec

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).

**Comment by tbillington** [comment]
@sharkdp  You may be able to reduce the compile time hit with `thin` over `true`/`fat`, though probably should bench that first 😀

https://doc.rust-lang.org/cargo/reference/profiles.html#lto
