### ISSUE TITLE
Print without line numbers.

### ISSUE THREAD

**Issue by Benjamin-Connelly** [sharkdp/bat#72]
Fantastic tool, thank you!

It would be nice to have an option to print without line numbers.

**Comment by sharkdp** [comment]
Thank you for the feedback!

This will be supported in the next version (see #5, #42 and #63).

**Comment by sharkdp** [comment]
No worries!

**Comment by benoittgt** [comment]
`--style=plain` :)

**Comment by deadcoder0904** [comment]
@sharkdp is there a way to store just `-p` as a default behavior in `bat` & use line numbers as & when needed?

ik it is just 2 letters but i'd like `-p` to be default because i often use `bat` for copying stuff & the line numbers fuck it up.

**Comment by garyo** [comment]
I mostly need the syntax coloring (for diff/patch especially) and the headers are fine (could take or leave them), but line numbers screw up copy/paste. It would be great if there was a single option to turn them off, even if something like `--style numbers:no` or whatever.

**Comment by GuilhermeZorzal** [comment]
> @sharkdp is there a way to store just `-p` as a default behavior in `bat` & use line numbers as & when needed?
> 
> ik it is just 2 letters but i'd like `-p` to be default because i often use `bat` for copying stuff & the line numbers fuck it up.

A possible solution would be to make an alias in your shell config. Something like: 
`alias bat="bat -p"`
