### ISSUE TITLE
set up dependabot for git submodules

### ISSUE THREAD

**Issue by sanga** [sharkdp/bat#720]
Feel free to dismiss or close this at your discretion.

As bat has rather many submodules I thought it might be useful to configure dependabot to suggest updates when the submodules are updated in addition to how it makes PRs when new versions of cargo deps become available. To be fair I haven't actually ever configured that myself but I believe dependabot has support for this. See https://dependabot.com/submodules/

**Comment by sharkdp** [comment]
Great idea, I didn't know that Dependabot has this feature. It was set up in 30 seconds and directly found a bug (#721) and is opening the first PRs (#723).
