### ISSUE TITLE
Library API: Line Filtering/Highlighting

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#728]
I've been thinking of ideas for the library API that can provide more powerful functionality, while also reducing how much of the `bat` internals are exposed. Feedback would be appreciated.

---

We currently have two features (line ranges, line highlighting) that can be consolidated into one trait. With the current system we use `LineRange` and `Vec<usize>` for filtering out and highlighting individual lines.

My proposal:

```rust
enum LineVisibility {
    Hide,       // Skip the current line.
    Show,       // Print the current line (default).
}

struct LineVisibilityOptions {
    pub default_visibility: LineVisibility
}


enum LineStyle {
    Normal,   // Normal line.
    Highlight // Highlighted line.
}

enum FilterResult<T> {
    Error(Error), 
    Some(T),
    Detach, // Removes the filter (usage e.g. when there are no more highlighted lines left).
    None 
}

trait Filter<T, O> {
    fn filter(&mut self, line_number: usize, line: &str, options: &mut O) -> LineFilterResult;
}

struct FilterSet<T, O> {
    options: O,
    // ... Implementation details.
}

impl<T> FilterSet<T> {
    fn options(&self) -> &O;
    fn options_mut(&mut self) -> &mut O;
    fn is_empty(&self) -> bool;
    fn add(&mut self, filter: Filter<T, O>) -> ();
    fn remove(&mut self, filter: &Filter<T, O>) -> ();
    fn process(&mut self, line_number: usize, line: &str) -> Result<T>  {
        let mut value: Option<T> = None;
        for let mut filter in self.filters.iter_mut() {
            match filter.filter(line_number, line, &mut self.options) {
                Error(err) => return Error(err),
                Some(val) => value = Some(val),
                Detach => /* remove the filter from self.filters */,
                None => {}, // Keep the previous.
            }
        }

       value.unwrap_or(self.options.default_value)
    }
}
```

This would allow us to maintain the current line-based features, and provide a way to easily add custom filtering or highlighting from both inside `bat` and when used as a library. A couple examples would be:

- Only show changed lines in git.
- Only show lines that match a regex pattern (using the `line` parameter).

## Usage example:

```rust
struct RangeFilter() {
    ranges: LineRanges
}

impl Filter<LineVisibility, LineVisibilityOptions> for RangeFilter {
    fn filter(&mut self, line_number: usize, _: &str, options: &mut LineVisibilityOptions) -> FilterResult<LineVisibility> {
        match self.ranges.check(line_number) {
            InRange => None            // Use the default value/previous filter value.
            OutsideRange => Some(Hide) // Don't show this line.
            AfterLastRange => {
                options.default_visibility = Hide; // Set the default to hide all future lines.
                Detach                             // Remove this filter since it's no longer necessary.
            }
        }
    }
}
```

The line highlighter would follow similar logic, but with `LineStyle` instead of `LineVisibility`.

## Miscellaneous:

With the presence of `Filters.is_empty()` and `Filters.options().default_value`, the current printer optimization where it stops printing after the last line can be maintained, too:

```rust
fn print_lines(/* ... */) -> /* ... */ {
    while /* ... */ {
        self.print_line();
        if self.line_visibility_filters.is_empty() && self.line_visibility_filters.default_value() == Hide {
            return
        }
    }
}
```

Type aliases could be added to improve friendliness for people starting out with bat as a library:

```rust
type lineno = usize;
type VisibilityFilter = Filter<LineVisibility, VisibilityOptions>;
type VisibilityResult = LineFilterResult<LineVisibility>;
type VisibilityOptions = LineVisibilityOptions;

type StyleFilter = LineFilter<LineStyle, ()>;
// etc.

impl VisibilityFilter for MyFilter {
    fn filter(line: lineno, text: &str, options: VisibilityOptions) -> VisibilityResult {
        return if (lineno % 2) == 0 {
            Some(Hide)
        } else {
            None
        }
    }
}
```

**Comment by sharkdp** [comment]
Your proposal looks great, thank you very much!

I didn't quite understand why `LineVisibilityOptions` are passed into the filter again? Couldn't the filter maintain its own set of options internally?

**Comment by eth-p** [comment]
It's been a while since I wrote this, but I believe I did that to allow the filter to change the default visibility (and any future options) without using complicated return types.

This would be used with a line range filter to allow the printer to stop early after all visible lines are printed:

1. Filter handles visibility on a per-line basis.
2. Filter reaches last line, sets default visibility to `Hide`.
3. Filter detaches itself.
4. Printer detects default Hidden and no more visible lines, and exits.

**Comment by sharkdp** [comment]
The whole structure behind LineRanges has been changed (a few times). With the changes in #936, we now have:
``` rs
PrettyPrinter::new()
  .highlight(42) // highlight a single line
  .highlight_range(10, 20) // highlight a whole range
```

@eth-p Is there anything from this ticket that we should continue to track?

**Comment by eth-p** [comment]
The new API isn't as flexible as I would've hoped, but it's definitely a lot easier to work with, which I feel is the better approach to go through for a public API. 

If we were to refactor the private API in the future, I feel that this could still provide a useful structure for making it more flexible/modular, but that goes beyond what the issue was originally intended for.

I think it's safe to close this for now, and we can refer to it at a later date when refactoring the non-library code becomes a focus.
