### ISSUE TITLE
Library API: Decorations

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#730]
I've been thinking of ideas for the library API that can provide more powerful functionality, while also reducing how much of the bat internals are exposed. Feedback would be appreciated.

---

Most of the current implementation for `Decoration` is fine for a public API, but we should remove the parameter that is passing around the internal `InteractivePrinter` struct.

If we choose to implement input source properties as described in #729, this could be easily fixed by using the `HashMap<&'static str, Any>` with builder solution.

I would also suggest that we move the git changes decoration into its own cargo feature (`git-decorations` maybe?), and possibly split off each decoration into its own file.

**Comment by sharkdp** [comment]
Thank you for your API proposals. I didn't find the time to take a detailed look, yet, but plan to do so soon.

**Comment by sharkdp** [comment]
This will be fixed in #936, I think.

`InteractivePrinter` is not exposed anymore. `StyleComponent` is not exposed via the `PrettyPrinter`-part of the API. Instead, we have builder-type methods:
```
   .header(true)
   .grid(false)
```
