### ISSUE TITLE
Segfault piping stdin but not piping stdout (macOS Catalina)

### ISSUE THREAD

**Issue by isaacs** [sharkdp/bat#747]
I strongly suspect this is the same issue and/or related to https://github.com/sharkdp/bat/issues/680

This segfaults:

```
$ bat <index.js
Segmentation fault: 11
```

This is fine though:

```
$ bat <index.js >out
```

My suspicion that it's related to #680 is that I'm guessing piped input should be printed to stdout without formatting, which would be the same expected behavior as doing `bat -p index.js`.  I haven't bothered to even look at the code though, so this is 100% an uninformed reckon :)

Hope this helps!  Thanks for this tool, it's really cute and adds some colorful delight in my day.

**Comment by eth-p** [comment]
You are correct. Piping to something that isn't a tty will use the passthrough printer, which doesn't use syntax highlighting.

Using `bat -p` will still use the syntax highlighting printer and segfault, though.

**Comment by sharkdp** [comment]
closing this as a duplicate. Thank you for reporting!
