### ISSUE TITLE
Feature request: automatic decompression

### ISSUE THREAD

**Issue by wwood** [sharkdp/bat#748]
Hi,

I use `bat` as a nice replacement for `less` and one thing I see bat not doing is decompressing files that are compressed plain text e.g. gzip. For instance if I run `less a.gz` I see the contents of a.gz, while `bat a.gz` just tells me it is binary. Of course the workaround is just `zcat a.gz |bat` but I'm lazy.

I suppose this is related: https://github.com/wofr06/lesspipe

Thanks, ben

**Comment by sharkdp** [comment]
please see #237 and #642
