### ISSUE TITLE
Theme warning

### ISSUE THREAD

**Issue by jerguslejko** [sharkdp/bat#751]
Hi, every time I run:

```
bat --theme=default file
```

I get:

```
[bat warning]: Unknown theme 'default', using default.
```

**bat** is not recognising `default` theme as `default`.

thanks

**Comment by eth-p** [comment]
At the moment, the `--theme` option requires a theme be referred to by its name.
When you use `default`, it's looking for a theme named `default`.

The default theme is "Monokai Extended", as specified in `assets.rs`:

https://github.com/sharkdp/bat/blob/4664fb6f91e1c713cd623daf8dfa34462f0dd7f9/src/assets.rs#L17

**Comment by jerguslejko** [comment]
@eth-p Hi, thanks for the response, using `Monokai Extended` works. However, when I run `bat --list-themes`, I get the following:


<img width="946" alt="Screenshot 2019-11-16 at 12 50 27" src="https://user-images.githubusercontent.com/4470539/68993399-b20fe680-086f-11ea-96bf-9d57e6259757.png">

**Comment by eth-p** [comment]
Are you using macOS Catalina, by any chance? We had #701 (`--list-themes` fails with segfault) which was thought to be caused by the same problem being discussed in #680.

**Comment by jerguslejko** [comment]
@eth-p yup, I'm on Catalina

**Comment by eth-p** [comment]
In that case, you might want to check out #680. I'm not running Catalina, but I think this should fix it:

Update to the latest Xcode and either use `brew install --build-from-source bat`, or clone this repo and use `cargo install `.

**Comment by sharkdp** [comment]
Do we want to provide `default` as an alias for `Monokai Extended`?
