### ISSUE TITLE
Fixed / pinned file name header

### ISSUE THREAD

**Issue by devurandom** [sharkdp/bat#754]
It would be awesome if the file name header, that bat displays before each file, would be fixed / pinned to the top of the screen and just the file content would scroll. When scrolling into the next file, its file name header would scroll up until it takes the place of the previous file's header, at which point it would be fixed / pinned to the top of the screen, and so on.

**Comment by eth-p** [comment]
Scrolling is handled by the page. I would absolutely love to have this feature, but it would likely require writing our own pager.

**Comment by devurandom** [comment]
Maybe some parts of nushell could be used, which already has the structural presentation of data as one of its core features and would thus also benefit greatly from such a pager.

**Comment by sharkdp** [comment]
Unfortunately, I think this is out of the scope for `bat` (to implement a custom pager). If we really want to go down that route, it would potentially solve *a lot* of problems that we have with `less`, but it's not that easy for sure. It should also probably be developed independently from `bat` (as a library?).

Until then, I'm going to close this ticket.

**Comment by sunnyzanchi** [comment]
just in case anyone else finds this thread looking for the same thing, the pager [ov](https://github.com/noborus/ov) supports sticky headers. it's not perfect but i was able to get it working with these settings

```
bat --color=always * | ov --section-delimiter '┬' --section-header-num=3
```
