### ISSUE TITLE
Support new theme format?

### ISSUE THREAD

**Issue by wfxr** [sharkdp/bat#759]
Sublime start using new theme format from build 3149. The legacy `.tmTheme` utilise the XML format, while the newer `.sublime-color-scheme` files utilise JSON formatting.

Some theme repositories have removed `.tmTheme` support already(eg: [gruvbox](https://github.com/Briles/gruvbox)). So can we update to support for the new theme format?

**Comment by keith-hall** [comment]
This will need to be added upstream, see https://github.com/trishume/syntect/issues/244

**Comment by wfxr** [comment]
@keith-hall Got it. Thank you!
