### ISSUE TITLE
Syntax colors with -A non-printable characters?

### ISSUE THREAD

**Issue by supermitch** [sharkdp/bat#765]
Is it possible to show both syntax highlighting and non-printable chars at the same time?

I tried `bat -A --color always <file>` but it removes the text highlighting and only colorizes the non-printables.

**Comment by sharkdp** [comment]
Thank you for the feedback.

Unfortunately, that is not possible. It's also highly non-trivial to implement, given the current way `-A` works.

If you only want to highlight line-endings and tabs, you could use
```bash
bat --color=always --plain … | \cat --show-ends --show-tabs
```

**Comment by supermitch** [comment]
Ok, thank you for looking into it. Much appreciated.
