### ISSUE TITLE
Not using default when bat warns with "Unknown theme '...', using default."

### ISSUE THREAD

**Issue by ericbn** [sharkdp/bat#767]
This is how the default theme looks like in iTerm2 using Solarized dark:

![Screen Shot 2019-12-07 at 11 23 28](https://user-images.githubusercontent.com/4120606/70377640-a64e9780-18e4-11ea-8a5f-7b1f42461b1d.png)

This is how it looks like when bat warns with "Unknown theme '...', using default.":

![Screen Shot 2019-12-07 at 11 24 22](https://user-images.githubusercontent.com/4120606/70377648-bebeb200-18e4-11ea-9234-77ed1a0d596e.png)

That looks like the Monokai Extended theme. I would expect it to look like the first screenshot.

**Comment by sharkdp** [comment]
Is the `BAT_THEME` environment variable set?

**Comment by ericbn** [comment]
Sorry, actually I have cloned [deplorableword/textmate-solarized](https://github.com/deplorableword/textmate-solarized) into ~/.config/bat/themes, ran `bat cache --build`, and added `--theme="Solarized (dark)"` to ~/.config/bat/config

So that was I what mistakenly thought to be the default theme at that time.
