### ISSUE TITLE
Bat is not showing his interface with GNU screen

### ISSUE THREAD

**Issue by jfagoagas** [sharkdp/bat#769]
Hi everyone,

I am having an issue when I use bat with GNU screen. The problem is that I can not see the grid, line numbers, syntax and many other bat features.

They can see it in the following screen captures: 

- Without using screen

<img width="889" alt="Screenshot 2019-12-12 at 09 21 05" src="https://user-images.githubusercontent.com/16007882/70695015-1b451700-1cc1-11ea-8d44-39231f87c026.png">

- Using screen
<img width="241" alt="Screenshot 2019-12-12 at 09 21 21" src="https://user-images.githubusercontent.com/16007882/70695047-28fa9c80-1cc1-11ea-9cd6-6be64d85c835.png">

Maybe is anything related to the type terminal environment value?

**Comment by sharkdp** [comment]
I am assuming that `screen` does not support 24-bit colors. You can try:
```
unset COLORTERM
```

and run `bat` again.

**Comment by sharkdp** [comment]
If this is the case, we should extend this section: https://github.com/sharkdp/bat#terminals--colors

**Comment by jfagoagas** [comment]
> I am assuming that `screen` does not support 24-bit colors. You can try:
> 
> ```
> unset COLORTERM
> ```
> 
> and run `bat` again.

I was tried this before and does not work:

<img width="190" alt="Screenshot 2019-12-16 at 08 22 22" src="https://user-images.githubusercontent.com/16007882/70889829-c583ae00-1fe3-11ea-88f5-61492c6f45aa.png">

If I find any solution I will send it to you.

Many thanks.

**Comment by sharkdp** [comment]
This is how it looks like for me (in `screen`):

![image](https://user-images.githubusercontent.com/4209276/70943881-2c3fb080-2052-11ea-822b-6fe6dd8b5a09.png)


Could you please post the output of these commands:
```
set -x

bat --version
bat --config-file
bat --cache-dir
less --version

bat "$(bat --config-file)"
ls "$(bat --cache-dir)"

set +x

echo "BAT_PAGER = '$BAT_PAGER'"
echo "BAT_CONFIG_PATH = '$BAT_CONFIG_PATH'"
echo "BAT_STYLE = '$BAT_STYLE'"
echo "BAT_THEME = '$BAT_THEME'"
echo "BAT_TABS = '$BAT_TABS'"
echo "PAGER = '$PAGER'"
echo "LESS = '$LESS'"
```

**Comment by jfagoagas** [comment]
Hi! I have responded below, many thanks for your help and guidance.
> 
> Could you please post the output of these commands:
> 
> ```shell
> set -x
> 
> bat --version
> bat --config-file
> bat --cache-dir
> less --version
> 
> bat "$(bat --config-file)"
> ls "$(bat --cache-dir)"
> 
> set +x
> 
> echo "BAT_PAGER = '$BAT_PAGER'"
> echo "BAT_CONFIG_PATH = '$BAT_CONFIG_PATH'"
> echo "BAT_STYLE = '$BAT_STYLE'"
> echo "BAT_THEME = '$BAT_THEME'"
> echo "BAT_TABS = '$BAT_TABS'"
> echo "PAGER = '$PAGER'"
> echo "LESS = '$LESS'"
> ```
```
$ ./bat_test_env.sh
+ bat --version
bat 0.12.1
+ bat --config-file
/var/home/pepe/.config/bat/config
+ bat --cache-dir
/var/home/pepe/.cache/bat
+ less --version
less 481 (GNU regular expressions)
Copyright (C) 1984-2015  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
+ bat --config-file
+ bat /var/home/pepe/.config/bat/config
[bat error]: '/var/home/pepe/.config/bat/config': No such file or directory (os error 2)
+ bat --cache-dir
+ ls /var/home/pepe/.cache/bat
ls: cannot access '/var/home/pepe/.cache/bat': No such file or directory
+ set +x
BAT_PAGER = ''
BAT_CONFIG_PATH = ''
BAT_STYLE = ''
BAT_THEME = ''
BAT_TABS = ''
PAGER = ''
LESS = ''
```
> 
> ... and maybe try to run `bat` without a pager?
> 
> ```
> bat --paging=never …
> ```
<img width="206" alt="Screenshot 2019-12-16 at 22 51 29" src="https://user-images.githubusercontent.com/16007882/70946003-9bb79f00-2056-11ea-983f-0c1093bb3165.png">

**Comment by sharkdp** [comment]
Which terminal emulator are you using?
Which version of `screen`?


Could you please try to run `bat` with `unset COLORTERM` *and* without a pager?

**Comment by jfagoagas** [comment]
> Which terminal emulator are you using?

I am using iTerm2 on Mac OS Catalina

> Which version of `screen`?
```
screen -v
Screen version 4.05.00 (GNU) 10-Dec-16
```
> 
> Could you please try to run `bat` with `unset COLORTERM` _and_ without a pager?

Look at this:
<img width="341" alt="Screenshot 2019-12-22 at 18 18 27" src="https://user-images.githubusercontent.com/16007882/71325048-75c34c00-24e7-11ea-87d6-cb7d38e7ef76.png">

**Comment by sharkdp** [comment]
Could you please try to use `--theme=ansi-dark` or `--theme=base16`?

**Comment by jfagoagas** [comment]
> Could you please try to use `--theme=ansi-dark` or `--theme=base16`?

<img width="211" alt="Screenshot 2019-12-22 at 19 33 52" src="https://user-images.githubusercontent.com/16007882/71325771-fedf8080-24f1-11ea-88dc-bd7d1fdf43e5.png">

With `--theme=ansi-dark` the issue is solved, but I think I am going to miss many features. Am I wrong?

**Comment by sharkdp** [comment]
Something seems seriously wrong with your `screen` session/version. Can you see flawless colorized output in other programs?

**Comment by jfagoagas** [comment]
> Something seems seriously wrong with your `screen` session/version. Can you see flawless colorized output in other programs?

Yes, without any problems.

**Comment by sharkdp** [comment]
Also.. please try to run `bat` on a file where you would actually expect some colorized output in the code. I guess the `base16` theme just outputs black text (on black background).

**Comment by sharkdp** [comment]
Sorry for all the trouble.

Could you please run
```bash
printf "\x1b[38;5;220mHELLO\x1b[0m\n"
```

It should output yellow text

**Comment by sharkdp** [comment]
If the yellow text appears fine, this should work as well:
```bash
echo '<test attr="value">text</test>' | COLORTERM="" bat -lxml -pp
```

**Comment by jfagoagas** [comment]
> If the yellow text appears fine, this should work as well:
> 
> ```shell
> echo '<test attr="value">text</test>' | COLORTERM="" bat -lxml -pp
> ```
This is the output:
<img width="602" alt="Screenshot 2019-12-23 at 13 14 42" src="https://user-images.githubusercontent.com/16007882/71357487-43b4f700-2586-11ea-9e14-f4e6ab9fb9f1.png">

**Comment by jfagoagas** [comment]
> Sorry for all the trouble.

Do not apologize, many thanks for all of your help.
> 
> Could you please run
> 
> ```shell
> printf "\x1b[38;5;220mHELLO\x1b[0m\n"
> ```
> 
> It should output yellow text

**Comment by sharkdp** [comment]
so... it works just fine?

**Comment by jfagoagas** [comment]
> so... it works just fine?

With `COLORTERM="" bat -lxml -pp` works more or less like only `bat` but there is not line numbers and many other fancy things :(

I will keep investigating this akward behaviour.

**Comment by sharkdp** [comment]
well... how does

```bash
echo '<test attr="value">text</test>' | COLORTERM="" bat -lxml
```
or
```bash
echo '<test attr="value">text</test>' | COLORTERM="" bat -lxml --paging=never
```

look like?

**Comment by jfagoagas** [comment]
> well... how does
> 
> ```shell
> echo '<test attr="value">text</test>' | COLORTERM="" bat -lxml
> ```
> 
> or
> 
> ```shell
> echo '<test attr="value">text</test>' | COLORTERM="" bat -lxml --paging=never
> ```
> 
> look like?

<img width="645" alt="Screenshot 2019-12-23 at 18 20 37" src="https://user-images.githubusercontent.com/16007882/71371306-ff8b1c00-25b0-11ea-84b4-f5ac2613b57d.png">

**Comment by sharkdp** [comment]
Ok. It looks like the ANSI 8-bit color "238" is not visible on your terminal (with that particular BG color?).

I guess this doesn't work as well:
```
printf "\x1b[38;5;238mHELLO\x1b[0m\n"
```


In principle, it should be a gray color which should be visible on the dark background you have: https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit

**Comment by jfagoagas** [comment]
> Ok. It looks like the ANSI 8-bit color "238" is not visible on your terminal (with that particular BG color?).
> 
> I guess this doesn't work as well:
> 
> ```
> printf "\x1b[38;5;238mHELLO\x1b[0m\n"
> ```

Correct, this does not work

> 
> In principle, it should be a gray color which should be visible on the dark background you have: https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit

I am thinking that this behaviour lies on screen version, is not?

**Comment by sharkdp** [comment]
> I am thinking that this behaviour lies on Screen version, is not?

I don't know. Could also be your configuration. Do you have any content in `~/.screenrc`?

**Comment by jfagoagas** [comment]
> > I am thinking that this behaviour lies on Screen version, is not?
> 
> I don't know. Could also be your configuration. Do you have any content in `~/.screenrc`?
> 

Yes I have a few presets configured, that was the first thing I reviewed but nothing seemed to interfere.
> Does everything work as expected in your normal terminal emulator (when you are not in a `screen` session)?

Yes, without Screen `bat` works perfect. It is something weird... did you know anyone that has had a similar problem?

**Comment by jfagoagas** [comment]
This is my `.screenrc` configuration file content:
```
# Enable logging.
deflog on
# Enable timestamps in the log file.
logtstamp on
# Disable the startup splash message.
startup_message off
# Log to ~/.screenlog/logs.
logfile "~/.screenlog/screenlog.%n"
# Load ~/.profile
shell -$SHELL
```

**Comment by sharkdp** [comment]
One more idea:

Does `bat` work *without* screen when `COLORTERM=""`? Equivalently, can you see the output of
```bash
printf "\x1b[38;5;238mHELLO\x1b[0m\n"
```
if you are outside of `screen`?

If not, it might be the case that you have somehow remapped the 8-bit color 238 to another color. Some terminal emulators allow for this.

**Comment by jfagoagas** [comment]
> One more idea:
> 
> Does `bat` work _without_ screen when `COLORTERM=""`? Equivalently, can you see the output of
> 
> ```shell
> printf "\x1b[38;5;238mHELLO\x1b[0m\n"
> ```
> 
> if you are outside of `screen`?
> 

This is the output with `COLORTERM`:

<img width="645" alt="Screenshot 2020-01-15 at 10 54 31" src="https://user-images.githubusercontent.com/16007882/72423921-6a311100-3785-11ea-9dbe-f63030157ab4.png">

> If not, it might be the case that you have somehow remapped the 8-bit color 238 to another color. Some terminal emulators allow for this. In this case, could you try using another terminal emulator?

I have tried with another terminal emulator and same results.

It is really weird ....

**Comment by sharkdp** [comment]
Ok. It really looks like this is on `screen`. Everything works as expected outside. Inside, a simple `printf` doesn't work either. So this is not related to `bat`.

I'm afraid I can't really help to debug this further, but I would try to run it without your `.screenrc` file, just to make sure. Maybe also see if there is a newer version of `screen` available.

**Comment by jfagoagas** [comment]
> Ok. It really looks like this is on `screen`. Everything works as expected outside. Inside, a simple `printf` doesn't work either. So this is not related to `bat`.
> 
Yes it is, the problem is on `screen`, nothing about `bat`.

> I'm afraid I can't really help to debug this further, but I would try to run it without your `.screenrc` file, just to make sure. Maybe also see if there is a newer version of `screen` available.

I have tried to run this without my `.screenrc` and nothing new happens:
<img width="556" alt="Screenshot 2020-01-15 at 22 56 59" src="https://user-images.githubusercontent.com/16007882/72475012-58358980-37ea-11ea-97e7-defeba3d3013.png">

**Comment by sharkdp** [comment]
To be honest, I'm out of ideas here. I'd like to close this, unless you think there is anything that can be done here.
