### ISSUE TITLE
Rename STDIN string

### ISSUE THREAD

**Issue by stdedos** [sharkdp/bat#770]
I was wondering if it would be possible to rename that title
```
───────┬────────
       │ STDIN  
───────┴────────
```

to something else natively from `bat`.

I am using `bat` sometimes to make my syntax-highlighting (e.g. in this case for an uncolored patch), and it would be cleaner on what that output is when I am doing that as part of a function.

I'd like to avoid the `bat --decorations always | sed -r 's/STDIN$/test/g'`, if possible

**Comment by keith-hall** [comment]
see also https://github.com/sharkdp/bat/issues/654 and https://github.com/sharkdp/bat/issues/729 for existing discussions re this request

**Comment by stdedos** [comment]
Good for me that I managed to see all the non-related issues _and_ missed the important ones.

You can mark as a duplicate / close if you wish, I'll follow #654 instead
