### ISSUE TITLE
Auto refreshing with bat

### ISSUE THREAD

**Issue by PicoSushi** [sharkdp/bat#778]
Hi.

I'd like to use bat for highlighting **dynamically changing** files, like json-styled per line log file. So, I tried as `bat some.log` and pressed `F` in less, but it didn't worked.

Are there any idea for adding auto refreshing function for bat?

### Environments
- Darwin 19.0.0
- bat 0.12.1
- less 487 (POSIX regular expressions)
- $PAGER
  - bat
- $BAT_PAGER
  - less

**Comment by sharkdp** [comment]
Would this work for you?

https://github.com/sharkdp/bat#tail--f

**Comment by PicoSushi** [comment]
Hmm, it works but can't scroll or search... Are there any way to use pager?

**Comment by sharkdp** [comment]
You can try to start `less` with different flags. This *kind of* works for me:
```
(while true; do echo '<hi>'; sleep 0.1; done) | bat -lxml --pager="less -RX"
```

but once i scroll to the end, `less` seems to stay in that state..

I think this is more of an issue with `less` than with `bat`, to be honest.

**Comment by PicoSushi** [comment]
Hmm, it seems hard to use `less` as I wanted...

Thanks for your answers!
