### ISSUE TITLE
Bat reported as Trojan

### ISSUE THREAD

**Issue by tMerula** [sharkdp/bat#779]
Hello,

Tried to download and install bat on my Windows 10 PC yesterday. It wouldn't run. Emitted no error message. I scanned the downloaded file with Webroot SecureAnywhere, which reported it as a Trojan, "Win32.Passwordfinder". I am probably not sufficiently at home here at GitHub, so after some searching for a hash signature of the download, I gave up.

**Comment by sharkdp** [comment]
This is a duplicate of #272
