### ISSUE TITLE
The "-A" option shows unicode characters as their codes 

### ISSUE THREAD

**Issue by ShrykeWindgrace** [sharkdp/bat#788]
I have a utf-8 file `fileName` with cyrillic characters. If I run `bat fileName`, all cyrillic characters are shown correctly. If, however, I run `bat -A fileName`, all non-ascii characters are shown as their codes, e.g.: `"\u{413}\u{43b}\u{438}\u{43d}\u{442}\u{432}\u{435}\u{439}\u{43d}"`.

Setup: Win10, bat-0.12.1, terminals: cmd, powershell (with `chcp 65001` to add unicode support), bash-in-wsl-with-ubuntu.

**Comment by sharkdp** [comment]
Thank you very much for reporting this.

This was intended as a feature, and is not a bug (see https://github.com/sharkdp/bat/pull/640#issuecomment-526851534).

I can see how that's probably not optimal in your use case, though.

**Comment by ShrykeWindgrace** [comment]
Thank you for clarifications!
