### ISSUE TITLE
Range from the end of file

### ISSUE THREAD

**Issue by uranusjr** [sharkdp/bat#791]
`--range` is awesome, but I was out of luck trying to view e.g. “the last 10 lines of a file”. Maybe it would be possible to make it accept negative numbers? For example `-r=-10:` would print the last 10 lines, `-r=:-1` the whole file except the last line.

**Comment by eth-p** [comment]
This would be a pretty cool feature, but it might be a bit difficult to add. Bat reads files line-by-line, and doesn't know the total number of lines in advance.

Consider the following scenarios:

- What if I wanted the last 15 lines from stdin, and it was a user typing? Bat would need to create a cache and wait until all input is sent.

- What if I wanted to show all but the last 5 lines? Bat would need to receive 6 lines before it can display even a single line.

Unless there's another way to implement it for both files and streams (e.g. pipe, psub, stdin), I don't think it would be possible without altering the unbuffered behavior of bat.

There's always the option of using a wrapper script, though!

```bash
#!/usr/bin/env bash
file="$1"
show="$2"

lines="(wc -l "$file")"
range="$((lines - show)):$lines"

exec bat "$file" --range "$range"
```

**Comment by sharkdp** [comment]
> Unless there's another way to implement it for both files and streams (e.g. pipe, psub, stdin), I don't think it would be possible without altering the unbuffered behavior of bat.

Unfortunately not, no.

I'd like to close this, as I don't see any way of implementing this.

**Comment by ijoseph** [comment]
> I'd like to close this, as I don't see any way of implementing this.

I mean, somehow `tail` does it: 
https://github.com/coreutils/coreutils/blob/994c83e2e3675a67b21fac36fc24395da3e09476/src/tail.c#L1879

I'll admit it's not clear to me how, though, maybe just by manually seeking with a random offset until it hits beyond the end of the file and then walking that back, or something?

**Comment by ijoseph** [comment]
Update: [ah, the bug report related to pixelb's fix above has some context](https://superuser.com/a/1267407/147688), basically just uses `fstat` apparently.

**Comment by pixelb** [comment]
You could use tail(1) in the wrapper, which might be more efficient.

There is some buffering for this functionality in tail(1) when operating on pipes at least.
See the file_lines() and pipe_lines() functions in tail.c
