### ISSUE TITLE
Feature request: syntax highlight for embeded code sections

### ISSUE THREAD

**Issue by lebensterben** [sharkdp/bat#801]
It's common to have `code` sections in markup languages like markdown and org, and it'd very nice if the language specific syntax highlighting for those code sections are rendered correctly.

An example of such functionality is available in the program [glow](https://github.com/charmbracelet/glow). In the screenshot you can see that the Haskell code section is correctly highlighted.

![](https://raw.githubusercontent.com/charmbracelet/glow/master/example.png)

**Comment by sharkdp** [comment]
This is already supported (for Markdown, and for other syntaxes if the corresponding sublime syntax supports it). It is documented in the very first screenshot of the README.

**Comment by lebensterben** [comment]
My bad. I tired before posting this but I used wrong syntax.
