### ISSUE TITLE
It got stuck after type in  "bat --theme GitHub"

### ISSUE THREAD

**Issue by licardoY** [sharkdp/bat#804]
I try to change different themes ,but got no response
`bat 0.12.1`

![_20200117161753](https://user-images.githubusercontent.com/20562449/72599716-34d71f80-394d-11ea-8456-d986eadf5076.gif)

**Comment by eth-p** [comment]
`bat --theme [theme]` doesn't set the theme; it specifies which theme to use for highlighting. What's happening is `bat` isn't getting stuck, but rather just waiting for some input through STDIN.

If you want to set the theme, you can add `--theme GitHub` to your bat config file, which can be found through `bat --config-file`.

**Comment by licardoY** [comment]
Thanks a lot. I misunderstood the `--theme <theme>               Set the color theme for syntax highlighting.`

I added environment variable in `.bashrc` :  `export BAT_THEME="GitHub"`, then it works :)
