### ISSUE TITLE
Change language on the fly?

### ISSUE THREAD

**Issue by HarrisonMc555** [sharkdp/bat#805]
First of all, thanks for the great tool! I use it all the time.

There are certain situations where `bat` can't auto-detect the language. Often times I have a command that I pipe into `bat` and then remember that it doesn't auto-detect from `stdin`. I then want to change the language without needing to re-execute the command I just executed.

Would it be possible to change the language on the fly? From the way pagers work, I'm guessing the answer is no, but you would have a better idea of what's possible and what's not.

If worst comes to worst, I'll just quit and add the language flag.

**Comment by eth-p** [comment]
Unfortunately, everything has already been processed and is out of `bat`'s control once the pager is invoked. This wouldn't be possible unless we give `bat` its own built-in pager, but that's something that is currently out of scope for the project.

**Comment by HarrisonMc555** [comment]
I understand, that makes sense. Thanks for the feedback!

**Comment by sharkdp** [comment]
> First of all, thanks for the great tool! I use it all the time.

Glad to hear that!

Closing this, thanks @eth-p
