### ISSUE TITLE
Pass in "Ctrl-C" to pager?

### ISSUE THREAD

**Issue by HarrisonMc555** [sharkdp/bat#808]
As always, thanks for the great tool! I want to make sure I thank you in every issue I open.

I've been trying to use `bat` as a replacement for both `cat` and `less`. In most situations, this works out of the box.

However, I often use `less` to continuously monitor a file. I like to see the changes as they appear but also have the option to stop and search the previous contents. Using `less`, I can open the file and then press `F` so it scrolls forward as the file is updated (like `tail -f`). Then, when I think I've seen enough, I can press `Ctrl-C` to stop monitoring and then scroll backward, search, etc.

When I try the same thing using `bat`, I can start monitoring fine, but once I press `Ctrl-C`, it exits `bat` and I can't scroll/search/whatever.

Feel free to propose alternative solutions, but I can think of two obvious solutions.

## Solution 1

Add a flag that causes `bat` to capture `Ctrl-C` and pass it on to the pager.

### Possible issues

In the worst case, this could make it difficult/impossible to quit `bat` if the pager didn't quit when sent `Ctrl-C`. Then again, the default behavior of `less` captures `Ctrl-C` and doesn't quit, so it's not like it's without precedent. This would, however, lead to a difference in behavior--previously, pressing `Ctrl-C` would exit `bat` regardless of which pager was used (from what I can tell), while with this change the pager would be in control of whether or not it quit (and `less` would not). If this was behind a flag, then I think that's fine.

## Solution 2

Add a new keyboard shortcut to pass `Ctrl-C` to the pager.

### Possible issues

What keyboard shortcut would this be? Many are already used for other purposes, and overriding any would prevent the user sending that command to the pager/whatever.

## Conclusion

I believe solution 1 is preferable. Maybe `--pass-ctrl-c`? I was going to propose `--pass-sigint` as a possible alternative but then realized that it's called something else on Windows.

I would be willing to look into making a pull request if you'd be interested in including this feature.

**Comment by sharkdp** [comment]
Thank you for the feedback. Please tell us how to reproduce this. Maybe by piping the output of
```bash
(while true; do echo tick; sleep 0.1; done)
```
into `bat`.

**Comment by HarrisonMc555** [comment]
I tried your example, but it looks like using `Ctrl-C` to exit `less` (or `bat`) creates problems with the `while` loop.

I believe that this will mimic the behavior I'm referring to:

```bash
n=0; while [[ "$n" -lt 1000 ]]; do echo "$((n++))"; sleep 0.1; done > tmp & less tmp
```

vs.

```bash
n=0; while [[ "$n" -lt 1000 ]]; do echo "$((n++))"; sleep 0.1; done > tmp & bat tmp
```

When using `less` by itself, you can press "F" to let it follow the end as it is written and then press `Ctrl-C` to stop following and scroll/search. When using `bat`, you can press "F" and it will display the message, "`Waiting for data... (interrupt to abort)`". However, it never displays any more data.

I could have sworn that I got `bat` to read more data when I pressed "F", but I can't seem to reproduce it, so maybe I was mistaken.

If you try to use the `tail -f | bat` trick without the `--paging=never` flag, then you get a different issue. You will retain control over movement since you are using the `less` pager. In addition, as data is written to the file it will be available in `bat`. However, if you try to scroll past the last line received it will hang until it receives that line (which might be never). So, you can either follow the tail of the file as it is written by spamming scroll down ("j" or "d") or you can retain control (over moving, searching, etc.), but not both.

Does this sound right? My desired use case (using `bat` as a replacement for `less` and pressing "F") might not be possible due to limitations to how pagers and processes work, but if it's possible I think it would be great!

**Comment by sharkdp** [comment]
> When using `bat`, you can press "F" and it will display the message, "`Waiting for data... (interrupt to abort)`". However, it never displays any more data.

> I could have sworn that I got bat to read more data when I pressed "F", but I can't seem to reproduce it, so maybe I was mistaken.

If you call `bat tmp`, `bat` reads all of the contents from `tmp` and then pipes its output to `less`. By the time you have a chance to press any keys, `bat` has long finished its job. Neither `bat` nor `less` are watching the `tmp` file for any new content.

> Does this sound right? My desired use case (using `bat` as a replacement for `less` and pressing "F") might not be possible due to limitations to how pagers and processes work, but if it's possible I think it would be great!

I think it's clear what you want, and I'm not sure if there is a good solution for this. If you want to follow a file in a pager (with syntax highlighting), you can try the following:

Run this to generate some dummy XML log file:
```
n=0; while [[ "$n" -lt 1000 ]]; do echo "<entry>$((n++))</entry>"; sleep 0.1; done > tmp.xml &
```

Run this to continuously monitor the file in `less`, with syntax highlighting:
``` bash
tail -F tmp.xml | bat -l xml --color=always > tmp.xml.colorized &
less tmp.xml.colorized
```

**Comment by sharkdp** [comment]
see also: #457 and https://github.com/sharkdp/bat#tail--f

**Comment by HarrisonMc555** [comment]
Thanks for all your help! Although the temporary "colorized" file option may not be ideal it's nice to know that I have an option.
