### ISSUE TITLE
JavaDoc comments break syntax highlighting in .java files

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#81]
**Version:** bat 0.2.3
**Platform:** Mac OS X 10.13.4 (High Sierra)

JavaDoc comments in `.java` files break syntax highlighting for the rest of the file.
See the image below.

![comparison](https://user-images.githubusercontent.com/32112321/39728589-9840534a-520c-11e8-84a5-9b1abb559e3f.png)

**Comment by sharkdp** [comment]
Thank you for taking the time to report this.

Here is an example file to reproduce this:
``` java
/**
 * test
 */
class ExampleClass {
}
```

**Comment by sharkdp** [comment]
This has popped up multiple times now and basically affects every Java and D file. Until this has been fixed in syntect, maybe we could employ the fix suggested by @keith-hall here: https://github.com/trishume/syntect/issues/160#issuecomment-388378965

**Comment by sharkdp** [comment]
Fixed via a2676cc

**Comment by sharkdp** [comment]
Fixed in [v0.8.0](https://github.com/sharkdp/bat/releases/tag/v0.8.0)
