### ISSUE TITLE
new themes not in bat

### ISSUE THREAD

**Issue by Trollwut** [sharkdp/bat#814]
Hey folks!

when either installing via AUR (`bat-cat-git` package) or from source, I don't get the new themes delivered.

An example would be the theme *dracula-sublime*. It's neither listed with `bat --list-themes`, nor if I do a `bat --theme=dracula-sublime FILE`.

Is there some way to get these themes available?

**Comment by sharkdp** [comment]
No release has been published since this was included.

If you want to build from source, you have to re-create the binary assets:
```bash
cargo install --path . -f # install first time with old assets
bash assets/create.sh # create binary dumps for syntaxes and themes with the new binary from above
cargo install --path . -f # install a second time with the new assets
```

**Comment by Trollwut** [comment]
I commented it on the AUR package, hopefully the maintainer will look at this :)

**Comment by vkobel** [comment]
I quickly updated `bat-cat-git` on AUR, not sure if it's ideal, let me know

**Comment by sharkdp** [comment]
the script currently has an interactive part which triggers in the AUR build. You would need to call `git clone … --recursive`.

**Comment by vkobel** [comment]
Would your create.sh script not ask for confirmation if I recursive clone in the first place?
Also do you think of a better way to include the themes rather than having 2x builds?

**Comment by sharkdp** [comment]
> Would your create.sh script not ask for confirmation if I recursive clone in the first place?

It would, but a `PKGBUILD` shouldn't rely rely on interactive user input?

>  Also do you think of a better way to include the themes rather than having 2x builds?

There are binary assets in the repository, but I only update them when a new release comes out. If this AUR package intends to always be on the absolute latest state, it needs to build the binary artifacts itself. Building twice is the only way. The second build should be much faster than the third, as all of the dependencies have already been built.

**Comment by Trollwut** [comment]
Hey mate, just made a clean build via `yay` of it.

While building, this message pops up:

    One or more submodules were found to be uninitialized.
    Initialize and update them? [Y/n] 

Maybe this could be done with an auto-yes?

---

Nonetheless, the new themes are now available, (for example my mentioned *dracula-sublime* can be used via `--theme=Dracula`). Thank you for your fast response! :)

**Comment by vkobel** [comment]
Ok, I patched the create.sh script with sed to render it non-interactive

**Comment by sharkdp** [comment]
Thank you @vkobel
