### ISSUE TITLE
Improve JSON formatting?

### ISSUE THREAD

**Issue by eugeneware** [sharkdp/bat#821]
Thanks for creating this amazing project. I can't live without it now.

I'm wondering if there's away to improve / enhance the JSON syntax highlight colours to look more like the output from `jq`:

![image](https://user-images.githubusercontent.com/38154/74000382-f8cb3380-49bb-11ea-9293-40250346d1aa.png)

You can see that there's a lot more contrast in the `jq` as the keys and value strings are colored differently. 

Also the color palette of the green and the blue create a bit more contrast as well which makes it a bit easier to read.

Thanks again for all the hard work!

**Comment by keith-hall** [comment]
You may want to try with a color scheme like https://github.com/ColibriApps/MonokaiJsonPlus, see https://github.com/sharkdp/bat#adding-new-themes for how to apply it in bat.

**Comment by eugeneware** [comment]
Thanks @keith-hall - sorry for not RTFM! 😊  Didn't realise that there were themes built in. The `TwoDark` looks great and perfect for my needs. Thanks!
