### ISSUE TITLE
Wrapping with Windows Git Bash Shell

### ISSUE THREAD

**Issue by craigtmoore** [sharkdp/bat#824]
When I use bat from the git bash shell, it wraps the text at ~214 characters. Example:

```
$ bat --help | bat
───────┬───────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼───────────────────────────────────────────────────────────────────────
   1   │ bat 0.12.1
   2   │ A cat(1) clone with syntax highlighting and Git integration.
   3   │
   4   │ USAGE:
   5   │     bat.exe [OPTIONS] [FILE]...
   6   │     bat.exe <SUBCOMMAND>
   7   │
   8   │ OPTIONS:
   9   │     -l, --language <language>
  10   │             Explicitly set the language for syntax highlighting. The l
       │ anguage can be specified as a
  11   │             name (like 'C++' or 'LaTeX') or possible file extension (l
       │ ike 'cpp', 'hpp' or 'md'). Use
  12   │             '--list-languages' to show all supported language names an
       │ d file extensions.
  13   │     -L, --list-languages
  14   │             Display a list of supported languages for syntax highlight
       │ ing.
```

However, my terminal has a much larger width than that. If I use `--wrap never` this turns off wrapping or I can use `--terminal-width 300`, but I'd prefer if bat could detect the width of the terminal and just use `--wrap auto` by default.

Is there someway to resolve this?

**Comment by sharkdp** [comment]
From the screenshot, it looks like `bat` wraps at 79 or 80 characters, right?

This would indicate, that the `console::Term::width()` was not able to get the width of your terminal. This is the Windows-version of that function:

https://github.com/mitsuhiko/console/blob/a999e34bbbf66886aa7420dc6e2d7cc264ade959/src/windows_term.rs#L77-L87

This, in turn, uses [`GetConsoleScreenBufferInfo`](https://docs.microsoft.com/en-us/windows/console/getconsolescreenbufferinfo)

Apparently, it doesn't return the correct size (or an error) in Git bash / MinGW32. Don't really know how we can help here. It should probably be reported upstream (https://github.com/mitsuhiko/console)

**Comment by craigtmoore** [comment]
> From the screenshot, it looks like `bat` wraps at 79 or 80 characters, right?

Yes:
```
$ echo "10   │             Explicitly set the language for syntax highlighting. The l" | wc -c
80
```

I will push the defect up stream. Thanks
