### ISSUE TITLE
Theme: Solarized and Solarized Dark

### ISSUE THREAD

**Issue by zachriggle** [sharkdp/bat#830]
The current list of color schemes is neat, but it would be nice if the Solarized variants were available.  It seems that `ansi-dark` is the closest to e.g. Solarized Dark.

It would be nice to have proper support for Solarized, or at least an alias if they are in fact the same. ❤️

**Comment by sharkdp** [comment]
#768 (not released yet)

**Comment by Muffo** [comment]
This would be nice! When is the next release planned?

**Comment by sharkdp** [comment]
See #845
