### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by gsbhasin123** [sharkdp/bat#833]

**Comment by gsbhasin123** [comment]
In terms of syntax highlighting I mean

**Comment by eth-p** [comment]
https://packagecontrol.io/packages/CoffeeScript

It definitely meets our guidelines for new syntaxes, but we would need to convert the `.tmLanguage` to `.sublime-syntax`.
@

**Comment by gsbhasin123** [comment]
If i can get the file; https://github.com/aziz/SublimeSyntaxConvertor

**Comment by sharkdp** [comment]
@gsbhasin123 The process is described here: https://github.com/sharkdp/bat/tree/master/assets#syntax-highlighting-in-bat

**Comment by gsbhasin123** [comment]
Ah ok, where can I get the .tmLanguage file?

**Comment by eth-p** [comment]
https://github.com/sustained/CoffeeScript-Sublime-Plugin?files=1

**Comment by gsbhasin123** [comment]
Yay it's yaml
https://hastebin.com/wovaxirexe.rb
I'll PR right now

**Comment by gsbhasin123** [comment]
Wait, I'm not sure how. Help is appreciated

**Comment by sharkdp** [comment]
It's also described in https://github.com/sharkdp/bat/tree/master/assets#syntax-highlighting-in-bat

* Add the Git repository as a submodule under `assets/syntaxes`.
* In addition, add the converted yaml syntax in the `assets/syntaxes` folder.

If the instructions are not clear, let us know.

**Comment by gsbhasin123** [comment]
They are clear, except:
> re-compile bat. At compilation time, the syntaxes.bin file will be stored inside the bat binary.

I don't know much Rust, or how I would compile that (is it a cargo package? rustc?)

And thanks! I'll be waiting for the v0.13 binary to come out.

**Comment by sharkdp** [comment]
This has been released in [bat 0.13](https://github.com/sharkdp/bat/releases/tag/v0.13.0).
