### ISSUE TITLE
Feature request: stream input to output

### ISSUE THREAD

**Issue by bedax** [sharkdp/bat#836]
bat is brilliant, thank you for it. One thing that I've noticed is something like `cargo install x | bat --pager "/usr/bin/less"` will wait until the installation is finished before showing anything, whereas when `less` is used on its own, it streams input lines to the output as soon as they become available. It would be nice if bat could do something similar.

**Comment by eth-p** [comment]
I'll need to do some testing, but this actually sounds more like you encountered a bug or unexpected interaction. `bat` doesn't buffer its output, and is designed to output a line whenever it receives a `\n`.

If you run `bat` without any arguments and start entering lines, they should be printed immediately after you press enter (just like `cat`).

If I had to guess, it would be that `less` is buffrring the input. Could you try the following:

```bash
cargo install x | bat --pager='less +F'
``~

**Comment by bedax** [comment]
ah sorry, I just realised I have a shell script getting in the way, messing up bat's ability to show the output as it happens
