### ISSUE TITLE
Can't view some files

### ISSUE THREAD

**Issue by setu4993** [sharkdp/bat#838]
I'm using `bat` on MacOS, installed using Homebrew (`0.12.1`). I'm on Catalina.

Some files (`pycodestyle`, `isort.cfg`) that I try to open simply don't show. Terminal exits with a success code.

**Comment by eth-p** [comment]
I can't reproduce this on Mojave. Can you paste an example file so I can verify it's not the file or syntax highlighting causing it?

**Comment by setu4993** [comment]
Sure, below is my `pycodestyle`:
```
[pycodestyle]
max_line_length = 120

```

And my bat `config`:
```
# Show line numbers, Git modifications and file header (but no grid)
--style="numbers,changes,header"

# Use italic text on the terminal (not supported on all terminals)
--italic-text=always

# Add mouse scrolling support in less (does not work with older
# versions of "less")
--pager="less -FR"

# Use C++ syntax (instead of C) for .h header files
--map-syntax h:cpp

# Use "gitignore" highlighting for ".ignore" files
--map-syntax .ignore:.gitignore
```

**Comment by eth-p** [comment]
Thanks! Still can't confirm it on my version of MacOS, so it's looking like I might have to set up a virtual machine and try it on Catalina later.

**Comment by setu4993** [comment]
Thanks for checking, @eth-p! Is there any additional debugging I can do to help?

**Comment by eth-p** [comment]
A couple more questions:

- Does it work if you use the `--no-config` flag?
- Did you install any custom themes or syntaxes?
- Do you have a wrapper script/function around bat?
- Output of `sw_vers`?

> Is there any additional debugging I can do to help?

If you would be able to build `bat` from master and tell me if that works correctly, it might make things a bit easier to figure out if it's a `bat` issue or an issue with the homebrew-compiled artifacts. The compiler shipped with Xcode during the early releases of Catalina emitted bad code, and this could be another instance of that.

**Comment by setu4993** [comment]
> * Does it work if you use the `--no-config` flag?
Yes! Just tried it and that's the first time I've seen this file with `bat` 😅.
> * Did you install any custom themes or syntaxes?
Only 1 theme, [Dracula](https://github.com/dracula/sublime).
> * Do you have a wrapper script/function around bat?
No.
> * Output of `sw_vers`?
```
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
```

> If you would be able to build `bat` from master and tell me if that works correctly, it might make things a bit easier to figure out if it's a `bat` issue or an issue with the homebrew-compiled artifacts. The compiler shipped with Xcode during the early releases of Catalina emitted bad code, and this could be another instance of that.

I see. I'll try this in a couple days.

**Comment by setu4993** [comment]
Commenting out `--pager="less -FR"` from my bat config fixes it and displays the file, so it has something to do with the pager.

**Comment by eth-p** [comment]
> Yes! Just tried it and that's the first time I've seen this file with bat.

Interesting... Something in your config must be causing this issue. Could you try the following:

- `bat --no-config --style="numbers,changes,header" pycodestyle`
- `bat --no-config --italic-text=always pycodestyle`
- `bat --no-config --pager="less -FR" pycodestyle`
- `bat --no-config --map-syntax h:cpp pycodestyle`
- `bat --not config --map-syntax .ignore:.gitignore pycodestyle`

**Comment by setu4993** [comment]
> Commenting out `--pager="less -FR"` from my bat config fixes it and displays the file, so it has something to do with the pager.

Tried that on my own before seeing your comment, the culprit appears to be the pager.

**Comment by eth-p** [comment]
Thanks! What version of `less` are you using?

**Comment by setu4993** [comment]
I'm on: `less 487`

**Comment by eth-p** [comment]
That explains it. Your version of `less` is affected by the `--quit-if-one-screen` bug where it immediately enters and exits the terminal's alternate screen mode.

If you try viewing other files smaller than your terminal, you'll run into the exact same issue.

A simple fix would be to either remove that line from your config, or run `brew install less`.

**Comment by setu4993** [comment]
I was under the impression that less was installed from homebrew for me, but clearly not. Installing it from homebrew fixed it.

Thanks, @eth-p!

**Comment by MT--** [comment]
This info might be a good candidate for an addition to the "Troubleshooting" section of the README. It took me a minute to figure out that the pager was the culprit for the lack of output!

**Comment by MT--** [comment]
Nevermind, I saw that this was in the "Pager" section already. 😅
