### ISSUE TITLE
Vim-like jump to line with ":" operator

### ISSUE THREAD

**Issue by mihaigalos** [sharkdp/bat#839]
Would it be possible to implement a jump to a specific line, as with `vim`? When I type ":5", seems bat jumps 5 lines forward. I would like to have it jump to line 5.

Let me know if I can help with the development, if the feature is not too complicated, I could perhaps write it myself and open up a PR. If so, give me a few tips at least in which file I should start.

**Comment by eth-p** [comment]
This isn't something we can change, unfortunately. The behavior you're describing is handled by `less`.

**Comment by sharkdp** [comment]
As @eth-p said, this is specific to the pager that you use.

In `less`, you can use `123G` to jump to line 123 (same as in `vim` as well).

**Comment by mihaigalos** [comment]
OK, I see. Thank you for your replies. :+1:
