### ISSUE TITLE
debian 32 bit (x86) deb package

### ISSUE THREAD

**Issue by csonuryilmaz** [sharkdp/bat#84]
Could you please compile and release 32bit (x86) deb package from [releases](https://github.com/sharkdp/bat/releases) page?

**Comment by sharkdp** [comment]
This should be supported in the next release.

**Comment by sharkdp** [comment]
v0.4 is out and includes i686 tarballs:

https://github.com/sharkdp/bat/releases/download/v0.4.0/bat-v0.4.0-i686-unknown-linux-gnu.tar.gz

**Comment by csonuryilmaz** [comment]
Thanks, I started using [bat_0.4.1_i386.deb](https://github.com/sharkdp/bat/releases/download/v0.4.1/bat_0.4.1_i386.deb) . Great work!
