### ISSUE TITLE
Use imgcat when installed for displaying images

### ISSUE THREAD

**Issue by jorisroovers** [sharkdp/bat#846]
Thanks for making bat, I love it.

Suggestion. 
When the user has an `imgcat` program installed, invoke `imgcat` when a user invokes `bat` on an image file. I say "an" imgcat program installed, because there's a few of them out there.

- https://github.com/eddieantonio/imgcat
- https://www.iterm2.com/documentation-images.html
- https://github.com/wookayin/python-imgcat

I understand there might be some more philosophical reasons of why `bat` might not want to do this, in particular, how much is this in line with what users expect. But given that bat currently already prints ``` File: myimage.png   <BINARY> ``` instead of the binary data itself, I think showing the image itself is an improved user experience. This could always be toggled with configuration or CLI flag.

When not using a TTY or when piping into a different command, I do think bat should just pass on the binary data (like it already does).

**Comment by sharkdp** [comment]
Thank you for the feedback.

I'm not sure if we should integrate this into `bat`. Integrating an external pager into `bat` has been a huge pain with all sorts of unexpected problems.

I think we should leave this open for discussion for some time to hear other opinions as well.

I'm going to leave a few other links here:
- https://github.com/hopey-dishwasher/termpix
- https://github.com/stefanhaustein/TerminalImageViewer
- https://github.com/nabijaczleweli/termimage - a Rust library that prints images to the terminal

I've also recently played a lot with colors on the terminal. My [pastel](https://github.com/sharkdp/pastel) crate provides functions for accurate 8-bit interpolation of colors, for example. It also includes a terminal "canvas" implementation to draw the color swatches.

**Comment by eth-p** [comment]
This could be implemened as something like the `lesspipe` request a while ago, right?

**Comment by sharkdp** [comment]
I'd like to close this.

If someone wants to build this, I think it can be implemented in a wrapper script that checks the mime filetype.

**Comment by eth-p** [comment]
> If someone wants to build this, I think it can be implemented in a wrapper script that checks the mime filetype.

If anybody tackles this, I would recommend using `file` to check the file type. It comes installed on practically every Linux/BSD system available, and it's capable of detecting file formats even if the extension is wrong.
