### ISSUE TITLE
Print out from a particular line number and Syntax highlighting

### ISSUE THREAD

**Issue by anishmittal2020** [sharkdp/bat#850]
# Use Case

`"${QuickNoteP}"` is a markdown file

I wanted to print the contents of `"${QuickNoteP}"` from line number 11. Since `bat` doesn't  supports this I am using `tail` to do it, as follows

```bash
tail --lines=+11 "${QuickNoteP}" | bat
```

# Proposed Solution

Now since, the syntax highlighting is lost, may be it will be useful if we could specify it like:

```bash
tail --lines=+11 "${QuickNoteP}" | bat --format "markdown"
```

**Comment by anishmittal2020** [comment]
bat -r 11: "${QuickNoteP}

**Comment by sharkdp** [comment]
Yes. Alternatively, you can use `-l`/`--language` if the input comes from a pipe:
```
tail --lines=+11 "${QuickNoteP}" | bat -l md
```
