### ISSUE TITLE
is there any way to refresh, to show any changes to file?

### ISSUE THREAD

**Issue by eggbean** [sharkdp/bat#851]
Is there any way to refresh so that any changes made are shown?  r or R does not do it.

At the moment I have to exit bat and open it again.

Also, how come the help for `less` is shown when typing h?

Thanks

**Comment by sharkdp** [comment]
> Is there any way to refresh so that any changes made are shown? r or R does not do it.

There is no way to do that. `bat` pipes its output to a pager (`less`, by default). By the time you see the `less` interface, `bat` has already finished its job. You are left with the `less` TUI which can not "rerun" `bat`.

**Comment by eggbean** [comment]
Oh, okay.  Thanks.

**Comment by eth-p** [comment]
Maybe [batwatch](https://github.com/eth-p/bat-extras/blob/master/doc/batwatch.md) could help with what you're trying to do?
