### ISSUE TITLE
manpage language

### ISSUE THREAD

**Issue by patatetom** [sharkdp/bat#853]
hi,

on my Archlinux with `bat` installed from `pacman` :
```console
$ bat --version
bat 0.12.1

$ bat -L | grep man
JSON:json,sublime-settings,sublime-menu,sublime-keymap,sublime-mousemap,sublime-theme,sublime-build,sublime-project,sublime-completions,sublime-commands,sublime-macro,sublime-color-scheme,ipynb,Pipfile.lock
Manpage:man
```
on an other Linux with `bat` installed from release `bat-v0.12.1-x86_64-unknown-linux-musl.tar.gz` :
```console
$ bat --version
bat 0.12.1

$ bat -L | grep man
JSON:json,sublime-settings,sublime-menu,sublime-keymap,sublime-mousemap,sublime-theme,sublime-build,sublime-project,sublime-completions,sublime-commands,sublime-macro,sublime-color-scheme,ipynb,Pipfile.lock
```

regards, lacsaP.

**Comment by sharkdp** [comment]
Could you please, as advised in the issue template, run the script at https://github.com/sharkdp/bat/blob/diag-tools/diagnostics/info.sh (and paste the output here) to give us a little bit more information about your system (the second setup, which I guess you see as problematic).

**Comment by sharkdp** [comment]
Possible reason for this: your second system has an old (user generated) `bat` cache file, which you could get rid of by running `bat cache --clear`.

**Comment by eth-p** [comment]
I just realized I forgot to change the branch name for `https://github.com/sharkdp/bat/blob/diag-tools/diagnostics/info.sh`. It should be https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh, sorry. Will make a PR to fix that.

**Comment by patatetom** [comment]
hi,

thanks, `bat cache --clear` (followed by `bat cache --build` [&rsaquo;&rsaquo;](https://github.com/patatetom/iptables_sorted_colored)) solved the problem and now, `bat -L | grep man` returns `Manpage:man` as expected.

regards, lacsaP.

**Comment by sharkdp** [comment]
I was wondering if we should try to prevent surprising behavior like this by adding a "version" field to the generated binary dumps. This way, we could detect if the cached files have been created by a previous version of `bat` and warn the user.

**Comment by sharkdp** [comment]
I'm going to close this ticket and open a new one (#882) for the "version" field in the generated binary cache files.
