### ISSUE TITLE
`git log --format=online` outputs nothing

### ISSUE THREAD

**Issue by arkban** [sharkdp/bat#862]
**Describe the bug you encountered:**

I had an alias for a fancy `git log --format=<custom>` and it output nothing after I installed `bat`. I narrowed it down to just not working with simply `git log --format=oneline`
```shell
$ git log --format=oneline

$ git log --format=oneline |  /bin/cat
a61bcc9cd97930c3890e8e55ef3fe5285f7d05ca (HEAD -> master) Added tests for Grade
2c7f4330184e574e09e7809da0cd176da7f3e016 Split *.kt into individual files for ease of navigation
...
```
(`...` is me trimming output to keep things neat)

Oddly enough it does work if I directly pipe it to `bat`:
```shell
$  git log --format=oneline | /usr/bin/bat
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ a61bcc9cd97930c3890e8e55ef3fe5285f7d05ca (HEAD -> master) Added tests for Grade
   2   │ 2c7f4330184e574e09e7809da0cd176da7f3e016 Split *.kt into individual files for ease of navigation
...
───────┴──────────────────────────────────────────────────────────────
```
(`...` is me trimming output to keep things neat)

Some of the standard [format values](https://git-scm.com/docs/git-log#_commit_formatting) like `short`, `long`, `raw` work fine, but `--format=format:...` doesn't 

**Describe what you expected to happen?**

I expected the output of `git log --format=oneline` and `git log --format=oneline | /usr/bin/bat` to be the same.

**How did you install `bat`?**

Direct download and installed via `sudo dpkg -i bat-musl_0.12.1_amd64.deb` 

**Anything else?**

Thank you for making `bat`, and apologies if this is PEBKAC.

---
Output of https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh
```
system
------

**$ uname -srm**
Linux 4.15.0-43-generic x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID:	LinuxMint  
Description:	Linux Mint 19.3 Tricia  
Release:	19.3  
Codename:	tricia  

bat
---

**$ bat --version**
bat 0.12.1  

**$ env**
PAGER=less  

bat_config
----------

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------
Unable to determine if a wrapper function is set.

tool
----

**$ less --version**
less 487 (GNU regular expressions)  
```

**Comment by sharkdp** [comment]
Thank you for reporting this.

How do you know that this is related to `bat`? Why do you expect `git log --format=oneline` to call `bat` at all? Did you set your `git` pager to `bat`?

What does
```
git config core.pager
```
say? Is the `$GIT_PAGER` environment variable set?

**Comment by arkban** [comment]
> Why do you expect git log --format=oneline to call bat at all? 

I expected it because (I believe) the other formats `git log --format=short` use `bat`. (And while this may be proved wrong it was at least my expectation to start with ; )

> What does `git config core.pager` say? ...

Neither of those say anything actually:
```shell
$ git config core.pager

$ echo $GIT_PAGER

$
```

I assumed that when those aren't set it would use `PAGER`, which is set:
```shell
$ echo $PAGER
less

$ which less
less: aliased to bat

$
```

---
Given what you've asked I've tried setting `core.pager` directly:

When setting directly to `less` it doesn't work : (
```shell
$ git config core.pager
less

$ git log --format=oneline

$
```

When setting directly to `bat` it does work : )
```shell
$ git config core.pager
bat

$ git log --format=oneline
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ a61bcc9cd97930c3890e8e55ef3fe5285f7d05ca (HEAD -> master, upstream/master) Added tests for Grade
# snip
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

$
```

So something weird is happening, and (as I said) this may be entirely PEBKAC yet I wanted to share on the off chance that it was not.

**Comment by sharkdp** [comment]
> ```shell
> 
> $ which less
> less: aliased to bat
> ```

I don't really see how this causes any problems (aliases shouldn't really be visible to subprocesses of the shell, like `git`), but I wouldn't really recommend doing that. Where is this set? In your `.bashrc`/`.zshrc`/…? Does everything work as expected, if this alias is not present?

> When setting directly to `bat` it does work : )

:+1:

**Comment by sharkdp** [comment]
@arkban Any update on this? I'd like to fix this, if it turns out to be a bug.

**Comment by sharkdp** [comment]
Closing this, as there is no further feedback. Happy to reopen this if there is any progress.

@arkban Can you please post the output of the now updated script at https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh?
