### ISSUE TITLE
Update liquid dependency to 0.20

### ISSUE THREAD

**Issue by ignatenkobrain** [sharkdp/bat#879]
I'm now working on updating bat to 0.13 in Fedora and we have liquid 0.12 while bat depends on 0.19... Would it be possible to update this dependency?

**Comment by sharkdp** [comment]
It's certainly possible, but there are a few breaking changes in liquid 0.20, and it doesn't work out of the box.

**Comment by ignatenkobrain** [comment]
@sharkdp will send PR in 10 minutes or so.

**Comment by sharkdp** [comment]
Sounds great.

Note that liquid is a build-only dependency. So it shouldn't really matter for packaging, as long as it is a binary package (not a from-source build), right?

**Comment by ignatenkobrain** [comment]
@sharkdp #880 :)

It does matter. We build everything from source.. As any other sane free linux distributions :)

**Comment by sharkdp** [comment]
Understood. I thought there would be binary RPM/DEB-style packages that end-users could install directly without building from source (while maintainers would obviously need all dependencies to build the package in the first place).

Does this mean that we need a new release for Fedora?

**Comment by ignatenkobrain** [comment]
> Understood. I thought there would be binary RPM/DEB-style packages that end-users could install directly without building from source (while maintainers would obviously need all dependencies to build the package in the first place).

Yes, sure. Users won't need it, but I am a maintainer so I need to package all dependencies :)

No, we don't necessarily need a new release. I can just backport it.

**Comment by sharkdp** [comment]
Ok, thank you!

closed via #880
