### ISSUE TITLE
Will InputFile be able to take strings in the future?

### ISSUE THREAD

**Issue by jonathandturner** [sharkdp/bat#884]
I looked into adding `bat` to Nushell last night, and one issue I ran across was that there wasn't a way to send `bat` the string content we have.  Since Nushell handles its own pipelines, we have streams of text that might have been loaded earlier in the pipeline.  Rather than trying to load the original file, it'd be great to be able to display the lines that we have available as string content.

Would this be compatible with the bat's direction, by chance?

**Comment by eth-p** [comment]
We had an old discussion going in #729 for how to rewrite the `InputFile` struct as something more friendly for consumption in a public API. If that ends up being the direction we go down, it should be able to accept arbitrary strings (as an entire file) or a boxed `Read` (for streaming chunks of a file) as an input source.

**Comment by dtolnay** [comment]
+1 for use in https://github.com/dtolnay/cargo-expand. We have the contents in memory so giving bat a String would be sufficient, we wouldn't require a `Read` with streaming chunks.

**Comment by sharkdp** [comment]
I implemented this in #936
