### ISSUE TITLE
Command line options missing on macOS

### ISSUE THREAD

**Issue by Amndeep7** [sharkdp/bat#890]
**What version of `bat` are you using?**
0.13.0

**Describe the bug you encountered:**
All options below `--unbuffered` do not appear in the listing from `--help` nor can you use them in commands (though admittedly I only tested with the new `--generate-config-file`).

**Describe what you expected to happen?**
Those options to be listed in the help and be able to be called from the cli.

**How did you install `bat`?**
homebrew

---
```
$ bash info.sh
system
------

**$ uname -srm**
Darwin 19.3.0 x86_64

**$ sw_vers**
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

bat
---

**$ bat --version**
bat 0.13.0

**$ env**

bat_config
----------

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------

No wrapper function.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)
```

![image](https://user-images.githubusercontent.com/2015821/77657012-0f692200-6f4b-11ea-8a9d-0768d3e98c1b.png)

**Comment by sharkdp** [comment]
This is the expected behavior. Note that all of these options are hidden via `.hidden(true)`:
``` rust
        .arg(
            Arg::with_name("config-file")
                .long("config-file")
                .conflicts_with("list-languages")
                .conflicts_with("list-themes")
                .hidden(true)
                .help("Show path to the configuration file."),
        )
```

You should still be able to use them.

Except for `--generate-config-file`, which has just been implemented today and not yet released: https://github.com/sharkdp/bat/blob/master/CHANGELOG.md

**Comment by Amndeep7** [comment]
Oh, that explains everything.  Looking forward to that option making it into the next release!

Thanks for the work you and the other contributors have done on this.
