### ISSUE TITLE
Better coloring for light background

### ISSUE THREAD

**Issue by joeeames** [sharkdp/bat#893]
it seems like all of the syntax coloring is centered on having a black background. On white, there is a high quantity of yellow and it's hard on the eyes.

**Comment by sharkdp** [comment]
Have you looked at the other available themes (`bat --list-themes`)? There are some themes which are suited for light backgrounds.

This is also documented in the README: https://github.com/sharkdp/bat#highlighting-theme

**Comment by joeeames** [comment]
I guess I didn't look closely enough. All the examples show on black. Thanks.
