### ISSUE TITLE
How can I avoid line wrapping? screenshot.

### ISSUE THREAD

**Issue by dontdieych** [sharkdp/bat#897]
![Screenshot_20200330_155731](https://user-images.githubusercontent.com/6509673/77884272-b2010800-729f-11ea-9446-2558478f8da8.png)

that is `systemctl`'s output. I remember it worked well before without wrapping.

Arch linux
bat-0.13
PAGER=bat
Yakuake terminal
Plasma 5.18

**Comment by sharkdp** [comment]
```
> bat --help
…
        --wrap <mode>
            Specify the text-wrapping mode (*auto*, never, character).
            The '--terminal-width' option can be used in addition to
            control the output width.
…
```

**Comment by dontdieych** [comment]
@sharkdp thanks!

**Comment by Remiol** [comment]
I would like to wrap not within a word but at the end of a word. Is that possible? 

Even if I use the option --wrap=never I can't copy the text. 
There is a real linebreak in the text

**Comment by sharkdp** [comment]
> I would like to wrap not within a word but at the end of a word. Is that possible?

No, this is currently not possible.

> Even if I use the option --wrap=never I can't copy the text.
> There is a real linebreak in the text

You also need to disable the pager (`-P`). Or directly use the `-pp` option.
