### ISSUE TITLE
executable not found after upgrading to ubuntu 20.04

### ISSUE THREAD

**Issue by adgai19** [sharkdp/bat#905]
**What version of `bat` are you using?**
[paste the output of `bat --version` here]
currently none. before upgrade 0.12

**Describe the bug you encountered:**
...After upgrading to ubuntu 20.04 bat executable disappeared and this output is generated after running bat
Command 'bat' not found, but can be installed with:

sudo apt install bacula-console-qt 

**Describe what you expected to happen?**
...bat to run without any problem

**How did you install `bat`?**
apt-get, homebrew, GitHub release, etc.

---apt-get 

[paste the output of `info.sh` here]
system
------

**$ uname -srm**
Linux 5.4.0-21-generic x86_64

**$ lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal

bat
---

**$ bat --version**
./info.sh: line 101: bat: command not found

**$ env**

bat_config
----------
./info.sh: line 45: bat: command not found

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------

No wrapper function.

tool
----

**$ less --version**
less 551 (GNU regular expressions)

**Comment by sharkdp** [comment]
Yeah, unfortunately they had to rename the `bat` binary.

This is documented in the [Ubuntu ChangeLog](http://changelogs.ubuntu.com/changelogs/pool/universe/r/rust-bat/rust-bat_0.12.1-1build1/changelog), [the list of files](https://packages.ubuntu.com/focal/amd64/bat/filelist) and the `README.Debian` file:
```
bat for Debian
==============

In this package the executable and its manpage have been renamed from ‘bat’ to
‘batbat’ because of a file name clash with another Debian paclage.
```

**Comment by eugeneromero** [comment]
Just a note, at least in Ubuntu 20.04, the new executable is 'batcat', not 'batbat' as mentioned in the README above. A small typo :)

**Comment by sharkdp** [comment]
uh, yes. that has to be fixed in the Debian package.

**Comment by Alechan** [comment]
@sharkdp , can you edit your first comment? It would save people the "try and error" until they read eugeneromero's comment with the right name.
