### ISSUE TITLE
Option to add header to every page

### ISSUE THREAD

**Issue by mouse07410** [sharkdp/bat#908]
Theoretically, `bat` is a `cat` variant. But it's natural to use it as a pretty-printer (of which there aren't that many) instead of just file displayer.

It would be great if in addition to `BAT_PAGER` there was a way to tell `bat` the page size/length, and request header (file name) and footer (page number) added to every page. Currently `bat` has no concept of page number, and the header is printed only once.

**Comment by sharkdp** [comment]
Thank you for your feedback.

To me, this feels like something that should be implemented in a wrapper script - not `bat` itself. It should be achievable by running `bat` multiple times, using `--line-range N:M` appropriately.

**Comment by eth-p** [comment]
From my understanding of the request, you want a fixed header/footer while the file contents scroll? That would be something that a pager would have to handle. Once `bat` hands control to the pager, it's out of our hands sadly.

A wrote a quick script to demonstrate that it's also possible with a wrapper script, but it's not exactly elegant or performant.

```bash
#!/usr/bin/env bash
FILE="$1"
FILE_LINES="$(wc -l "$FILE" | awk '{ print $1 }')"

scroll=0
keybuffer=()

keyseq() {
	local key
	local buffer=("${keybuffer[@]}")

	while [[ $# -gt 0 ]]; do
		# Read the key.
		if [[ "${#buffer[@]}" -eq 0 ]]; then
			read -r -s -n 1 key
			buffer+=("$key")
			keybuffer+=("$key")
		fi
		
		key="${buffer[0]}"
		buffer=("${buffer[@]:1}")
		
		# Compare the key.
		if [[ "$key" != "$1" ]]; then
			return 1
		fi
		
		# Next
		shift
	done

	return 0
}

redraw() {
	buffer="$(
		bat --line-range=${scroll}:$((scroll + LINES - 6)) "$FILE" \
			--paging=never --color=always --decorations=always
	)"

	clear
	echo "$buffer"
}

scroll_up() {
	((scroll--))
	if [[ "$scroll" -le 1 ]]; then
		scroll=1
	fi
}

scroll_down() {
	local max=$(($FILE_LINES - LINES + 6))
	((scroll++))
	if [[ "$scroll" -gt "$max" ]]; then
		scroll="$max"
	fi
}

redraw
redraw
while true; do
	sleep 0.010
	keybuffer=()
	if keyseq 'q'; then
		clear
		exit 0
	elif keyseq $'\x1B' '[' 'A'; then
		scroll_up
		redraw
	elif keyseq $'\x1B' '[' 'B'; then
		scroll_down
		redraw
	fi 
done
```

**Comment by mouse07410** [comment]
> this feels like something that should be implemented in a wrapper script - not `bat` itself. It should be achievable by running `bat` multiple times, using `--line-range N:M` appropriately

Yes, that makes sense. It's probably slower than running `bat` once over the entire file, and I don't have a feel for whether the fact that only some lines are visible could affect correctness of syntax parsing/highlighting. Or, if it's a large file - whether it would be re-parsed in its entirety for every sliding window 40-60 lines wide. But I hear you.

> you want a fixed header/footer while the file contents scroll?

That's one possibility. But what I had in mind was formatting for print, not display scrolling. Because `bat` is a pretty nice syntax highlighter - it's output would surely be useful as a printout, in addition to visualizing the source on display. It's there that header (file name) and footer (page number) would be truly beneficial for the user.

@sharkdp @eth-p  what do you both think?

**Comment by eth-p** [comment]
> I don't have a feel for whether the fact that only some lines are visible could affect correctness of syntax parsing/highlighting. Or, if it's a large file - whether it would be re-parsed in its entirety for every sliding window 40-60 lines wide. But I hear you.

To ensure that the syntax highlighting is correct when using `--line-range`, `bat` makes sure to parse every line up until the last display line. It would be re-parsed every time, and would take longer for every line you scroll down.

> That's one possibility. But what I had in mind was formatting for print, not display scrolling.

Print? Like when you try and print a page from your web browser?

```
myfile.txt

  51| cat
  52| dog
  53| stoat
  54| frog
  ...
  105| axolotl

Page 1/3
```

That would be pretty easy with `--line-range` and a script (preferably not bash). The hardest part would probably be just trying to come up with a good format for the header and footers.

**Comment by mouse07410** [comment]
> Print? Like when you try and print a page from your web browser?

Yes, exactly. And trying to ensure that each individual/separate page conveys enough information to the reader - what file it is a print of, and what its place is in the sequence of other pages (though the latter could be ascertained from the line numbers *if* they are printed).

Pretty much like what your example above shows.

> That would be pretty easy with `--line-range` and a script (preferably not bash).

Do you see enhancing `prettybat` to support that? Or should it be a separate script, maybe `printbat`?

Also, why not `bash`? What's wrong with it? It's still the most common shell, AFAIK...

> The hardest part would probably be just trying to come up with a good format for the header and footers.

No-brainer. We can use what you depicted above, and figure how to improve it later on. ;-)

**Comment by eth-p** [comment]
> Do you see enhancing prettybat to support that? Or should it be a separate script, maybe printbat?

I think a separate script would be best. I wrote prettybat more for pretty-printing inconsistently-formatted code (for example, anything minified).

> Also, why not bash? What's wrong with it? It's still the most common shell, AFAIK...

It's not that there's anything wrong with it, but more that it's just not really the right tool for the job. Bash's strong point isn't really text manipulation (it usually involves chaining multiple commands together), and it's likely that a fair amount of that would be needed for a script like this.

The ideal way to do something like this would be the following pseudocode:
```python
file = "file.rs"
input = process("bat", [file, "--style=grid,numbers]).stdout
input.skip_line() # skip the header grid

def print_page(file, page, lines):
    print_header(file)
    print lines.join("\n")
    print_footer(page)

page = 1
while not input.eof and lines = input.take_lines(40):
    if input.eof:
        lines.pop() # skip the footer grid

    print_page(file, page, lines)
    page = page + 1
```

If you did it in bash, you would likely need to call `bat --line-range ... file.rs` multiple times. This would be fine for small files, but as you get more pages the amount of time it would use grows nonlinearly.

Page 1:
  - 40 lines processed total
  - 0 lines hidden
  - 40 lines displayed

Page 2:
  - (40 + 80) lines processed total
  - 40 lines hidden
  - 40 lines displayed

Page 3:
  - (40 + 80 + 120) lines processed
  - 80 lines hidden
  - 40 lines displayed

etc.

Something like that should be possible in bash, but it wouldn't exactly be the simplest of scripts. But then again, I'm one to talk considering all of `bat-extras` is written in bash... 😅

**Comment by sharkdp** [comment]
Can this be closed?

**Comment by mouse07410** [comment]
Yeah...

**Comment by sharkdp** [comment]
possible (builtin) long term solution: #1053
