### ISSUE TITLE
Generating a config file doesn't work as documented

### ISSUE THREAD

**Issue by lumaxis** [sharkdp/bat#909]
**What version of `bat` are you using?**
`bat 0.13.0`

**Describe the bug you encountered:**
Running `bat --generate-config-file` does not generate a default config file as [documented](https://github.com/sharkdp/bat#configuration-file) but instead produces this output:

```sh
➜ bat --generate-config-file
error: Found argument '--generate-config-file' which wasn't expected, or isn't valid in this context

USAGE:
    bat [OPTIONS] [FILE]...
    bat <SUBCOMMAND>

For more information try --help
```

**How did you install `bat`?**
homebrew

---

system
------

**$ uname -srm**
Darwin 19.4.0 x86_64

**$ sw_vers**
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266

bat
---

**$ bat --version**
bat 0.13.0

**$ env**
PAGER=less

bat_config
----------

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------
Unable to determine if a wrapper function is set.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)

**Comment by eth-p** [comment]
Unfortunately, that feature was only merge (#885) roughly four days after the release of `0.13.0`. The current master branch should have it, but it won't be available until `0.13.x` or `0.14.0` are released.

**Comment by eth-p** [comment]
@sharkdp: This brings up a bit of a concern. If the first thing people see when they're learning how to use `bat` is the repo README, it might lead to confusion when it talks about new features that have yet to be released.

Should we introduce a `CHANGELOG.md` for changes since the last release (or I can make a script to collect the descriptions of git commits since a specified tag), before adding anything to the `README.md` file?

**Comment by sharkdp** [comment]
> @sharkdp: This brings up a bit of a concern. If the first thing people see when they're learning how to use `bat` is the repo README, it might lead to confusion when it talks about new features that have yet to be released.

Right, this happened a few times.

In principle, users are "supposed to" read the `README.md` that comes with the [release tarballs](https://github.com/sharkdp/bat/releases) or their distribution installations (homebrew [does not seem to install the README file](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bat.rb) though). Or use the tagged README version (https://github.com/sharkdp/bat/blob/v0.13.0/README.md). But I also understand that nobody does that. I certainly also read `master` README files in other repositories.

> Should we introduce a `CHANGELOG.md` for changes since the last release

I recently did that actually: https://github.com/sharkdp/bat/blob/master/CHANGELOG.md

The idea is that contributors update the `CHANGELOG` when they implement new features/bugfixes. This way, we can massively reduce the amount of time it takes to create a new release, possibly resulting in smaller release cycles (which would also help with this README-is-newer-than-release issue).

> or I can make a script to collect the descriptions of git commits since a specified tag

I'd rather not. I write Git commit messages for developers but release notes for users. See also: https://keepachangelog.com/en/1.1.0/#bad-practices

> Or would a more appropriate way of doing it be having a `dev` branch for everything, while keeping `master` in the same state until a new release is published?

I think we would then remind every PR creator to target the `dev` branch. GitHub allows to change the base branch, but then we would probably show the README of the `dev` branch :smile:.

> […] before adding anything to the `README.md` file?

We could queue up README changes somewhere else, but that would add additional burden on the maintainers when creating new releases. That's something that I would like to avoid.

**Comment by lumaxis** [comment]
Oh, hah, sorry for not properly RTFM'ing then, I guess 🙂 Somehow, this felt like such a fundamental feature that I didn't even consider that it might have been recently added.
I'll definitely keep in mind double checking the Readme for the latest released version compared to current `master` if I ever run into something like this.

As to @eth-p's suggestions for how to improve this going forward, personally, I'd suggest to try and move to more frequent release cycles and making new releases as little work as possible. In my experience, that makes it much easier to pin down regressions in specific additions and also forces you to keep the release process itself well-maintained and low effort.

Either way, thanks for clearing up my confusion!

**Comment by sharkdp** [comment]
> Oh, hah, sorry for not properly RTFM'ing then, I guess slightly_smiling_face Somehow, this felt like such a fundamental feature that I didn't even consider that it might have been recently added.
> I'll definitely keep in mind double checking the Readme for the latest released version compared to current `master` if I ever run into something like this.

No worries :smile: As stated above, the current situation is certainly not ideal

> As to @eth-p's suggestions for how to improve this going forward, personally, I'd suggest to try and move to more frequent release cycles and making new releases as little work as possible. In my experience, that makes it much easier to pin down regressions in specific additions and also forces you to keep the release process itself well-maintained and low effort.

:+1: Let's try that first.

If this continues to be a problem, I would probably go with a `README.unreleased.md` file where we stage the changes that should not yet be visible. This would then have to be merged with `README.md` upon releasing a new version.
