### ISSUE TITLE
Add syntax highlighting for Pony

### ISSUE THREAD

**Issue by palash25** [sharkdp/bat#910]
I couldn't find syntax highlighting for [pony](https://www.ponylang.io/) it would be nice if it can be added. My bat version is `0.12.1`

If adding syntax highlighting for a new language is a trivial change then even I can try submitting a PR for it

**Comment by sharkdp** [comment]
Have you seen https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions ?

**Comment by palash25** [comment]
No I missed that thanks @sharkdp but this seems like a way to add the syntax locally to one's own bat installation, I was thinking about making a PR. There is already an official repo for Pony sublime https://github.com/ponylang/sublime-pony  It doesn't not have any files with the  `sublime-syntax` extension but I saw that the repo used in bat for the crystal syntax doesn't have this file either so I am guessing the pony one would work.

How are the repos in the extra directory https://github.com/sharkdp/bat/tree/master/assets/syntaxes/02_Extra  added to this repo? are these git submodules?

I would like to make a PR for the pony repo if possible.

**Comment by sharkdp** [comment]
> are these git submodules?

yes. There is a detailed explanation here: https://github.com/sharkdp/bat/tree/master/assets#syntax-highlighting-in-bat

> I would like to make a PR for the pony repo if possible.

Please take note of our guidelines here: https://raw.githubusercontent.com/sharkdp/bat/master/.github/ISSUE_TEMPLATE/syntax_request.md
