### ISSUE TITLE
bat panics on simple Vue file

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/bat#915]
When calling `bat` on this Vue file
``` vue
<style lang="stylus">
</style>
```
it panics with:
```
thread 'main' panicked at
  'Can only call resolve on linked references:
    ByScope { scope: <source.stylus>, sub_context: None }',
  …/syntect-4.1.0/src/parsing/syntax_definition.rs:188:18
```

found with the Python script in #913.

**Comment by sharkdp** [comment]
This happens because we didn't have a syntax for "Stylo" source code, which is included from the Vue syntax when using `<style lang="stylus">`.

**Comment by nemu626** [comment]
```
thread 'main' panicked at 'Can only call resolve on linked references: ByScope { scope: <text.pug>, sub_context: None }', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-3.3.0/src/parsing/syntax_definition.rs:192:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I meet same error with single Vue component file with `pug` template syntax.

**Comment by sharkdp** [comment]
Thank you for reporting this. That's unfortunate.

It should be possible to somehow verify that syntaxes do not include broken references when building the binary assets. This might need to be fixed upstream (in `syntect`).

**Comment by Enselic** [comment]
I don't understand how to reproduce the problem. Can someone please provide a Vue component file with `pug` template syntax that can be used to reproduce the panic? Maybe you @nemu626 ?

**Comment by sharkdp** [comment]
I think you can take the one from the first post and replace `stylus` with one of the other languages supported by the syntax file, e.g. Pug

**Comment by Enselic** [comment]
Turns out it was necessary to also change `style` to `template`. Here is how to reproduce with a one-liner: 

```bash
% echo "<template lang='pug'>\n</template>" > /tmp/crash.vue | bat /tmp/crash.vue
[...]
thread 'main' panicked at 'Can only call resolve on linked references: ByScope { scope: <text.pug>, sub_context: None }', [...]
```

**Comment by keith-hall** [comment]
> It should be possible to somehow verify that syntaxes do not include broken references when building the binary assets. This might need to be fixed upstream (in `syntect`).

I've created a PR which will add a new API to syntect for this, but I'm sure it could be improved: https://github.com/trishume/syntect/pull/332

**Comment by keith-hall** [comment]
I started work on #616, and realised the output from syntect wasn't helpful enough, so I created https://github.com/trishume/syntect/pull/338

Linking to this "version" of syntect, now when building assets in `bat`, we get:
```
Some referenced contexts could not be found!
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <source.sss>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <text.slm>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <source.livescript>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <source.postcss>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <text.pug>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <text.jade>, sub_context: None }
- Syntax 'Svelte' with scope 'text.html.svelte' has unresolved context reference ByScope { scope: <source.postcss>, sub_context: None }
- Syntax 'Svelte' with scope 'text.html.svelte' has unresolved context reference ByScope { scope: <source.livescript>, sub_context: None }
```

**Comment by sharkdp** [comment]
What does it take to integrate this into `bat`? Do we need additional code or really just a `syntect` update?

**Comment by keith-hall** [comment]
A tiny bit of additional code (to print the warnings to the console at asset building time) - I have already made the necessary changes locally, just waiting for a `syntect` release before I make a PR. Or is it okay to depend on the `syntect` git repository directly?

**Comment by sharkdp** [comment]
> just waiting for a `syntect` release before I make a PR.

Ah, right.

> Or is it okay to depend on the `syntect` git repository directly?

Unfortunately, no. We can do this on `master`, but we won't be able to release a version on crates.io by referring to a Git hash directly. We need an actual syntect release.

**Comment by hongqn** [comment]
syntect released on Aug 2: https://github.com/trishume/syntect/releases/tag/v4.6.0

**Comment by sharkdp** [comment]
@Enselic can this be closed with #1915 merged?

**Comment by Enselic** [comment]
@sharkdp Nope, Vue still has unresolved syntaxes (
```
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <source.postcss>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <source.sss>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <text.jade>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <text.pug>, sub_context: None }
- Syntax 'Vue Component' with scope 'text.html.vue' has unresolved context reference ByScope { scope: <text.slm>, sub_context: None }
```
)

I am still convinced that my proposed approach to solve it "once and for all" (https://github.com/sharkdp/bat/issues/915#issuecomment-950274207) is the right one, but I actually think we should wait with fixing this until after 0.19.0. It is a bit tricky to get the code right in syntect, and trishume seems busy these days, so there is a risk that that work would delay a release several months more in the worst case.

**Comment by sharkdp** [comment]
Understood, thank you. Removed the milestone (which - anyway - was only a suggestion).

**Comment by Enselic** [comment]
I finally got around polishing the prototype code, and opened a PR with production ready code for syntect that fixes this whole class of bugs: https://github.com/trishume/syntect/pull/427 (🎉 )
