### ISSUE TITLE
Better with BAT_PAGER="less -RFS"

### ISSUE THREAD

**Issue by eggbean** [sharkdp/bat#916]
The README suggests BAT_PAGER="less -RF" as an example, when I have found that BAT_PAGER="less -RFS" is much better, as like wraps no longer break through the line number column, as bat now does the wrapping.

I use the config file with:
```
--pager "less -FRS"
--wrap=auto
```
I've been using bat for a couple of years and I have only just realised this.

**Comment by sharkdp** [comment]
I don't understand. What does `-S` buy you?

**Comment by sharkdp** [comment]
`--pager="less -FRS" --wrap=never` might make sense, but if you like `bat`'s wrapping, I don't see a need for `-S`?

**Comment by eggbean** [comment]
Sorry, my mistake 😳

My previous and terrible config had:
```
--pager "less -RF" 
--wrap=never
```
...before adding the S, which was much better, but then after change to `--wrap=auto`, to enable wrapping again within bat, I didn't realise that the S didn't do anything.

**Comment by sharkdp** [comment]
:+1: 

In this case, I would suggest, that you remove both lines from the config. This way, `bat` should use the best defaults for your `less` version.
