### ISSUE TITLE
Display all the content at once

### ISSUE THREAD

**Issue by SamZhangQingChuan** [sharkdp/bat#920]
Is there any option so that I can display all the lines at once? Thanks for help.

**Comment by eth-p** [comment]
By default, bat pipes to your pager (which shows you some of the lines and lets you scroll). If you don't want to use the pager, you can do one of the following:


Add the following to your bat config file:
```
--paging=never
```

Set the following environment variable:
```
export BAT_PAGER=''
```

**Comment by SamZhangQingChuan** [comment]
Thanks a lot!
