### ISSUE TITLE
bat doesn't redraw content when size of terminal changes when using i3

### ISSUE THREAD

**Issue by figgis** [sharkdp/bat#921]
**What version of `bat` are you using?**
bat 0.11.0

**Describe the bug you encountered:**
I use i3 as my window manager and gnome-terminal and xfce4-terminal. I have many small windows on my desktop and if I do `bat file.txt` it opens in that small window, but If I go fullscreen bat doesn't redraw the screen and I have to hit `q` and relaunch bat in order to utilize the full area of the terminal.

**Describe what you expected to happen?**
...

**How did you install `bat`?**
`cargo install`

[paste the output of `info.sh` here]

**Comment by sharkdp** [comment]
please see #322 and #294

**Comment by figgis** [comment]
Sorry! I did look through the history prior to posting but didn't find these ones.
