### ISSUE TITLE
bat 0.13.0 does not show small files

### ISSUE THREAD

**Issue by dugdun** [sharkdp/bat#922]
**What version of `bat` are you using?**
bat 0.13.0

**Describe the bug you encountered:**
When running `bat smallfile`, if the file does not have enough lines to fill up the screen (i.e. it doesn't need to use the pager), the screen will flicker as if `less` was being displayed and then return to the OS prompt. Contents are displayed properly for files that have enough lines to use the pager. Small files are displayed properly if I run `bat --pager=none smallfile`.

**Describe what you expected to happen?**

I expected that the contents of the small file to be displayed on the screen.

**How did you install `bat`?**
homebrew

---

system
------

**$ uname -srm**
Darwin 19.4.0 x86_64

**$ sw_vers**
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E266

bat
---

**$ bat --version**
bat 0.13.0

**$ env**
BAT_PAGER=more
PAGER=less

bat_config
----------

**$ cat /Users/douglasduncan/.config/bat/config**
```
# --theme="Monokai Extended Origin"
--theme="TwoDark"
--map-syntax .ignore:.gitignore
--pager="less -FR"
```

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------

No wrapper function.

tool
----

**$ less --version**
less 487 (POSIX regular expressions)

**Comment by sharkdp** [comment]
You are using `BAT_PAGER=more`. Could you try removing that setting?

**Comment by sharkdp** [comment]
Wait, but it should be overwritten by the `--pager` option in your config.

Could you please unset `BAT_PAGER` *and* remove that line from your bat config:
```
--pager="less -FR"
```

**Comment by dugdun** [comment]
Hey @sharkdp thanks for the quick response and guiding me to the solution.

The `BAT_PAGER=more` was from some testing I was doing. I unset that and the problem still existed. I then removed the `--pager="less -FR"` from my config file and now `bat` works as expected.

Closing ticket as `bat` is working as expected.
