### ISSUE TITLE
exit to shell

### ISSUE THREAD

**Issue by Alsan** [sharkdp/bat#926]
How can I terminate bat when ctrl+c? Right now, it shows the prompt when ctrl+c, but when I try to type a command in the prompt, it backs to a bat process waiting prompt, and I have to press ctrl+c again to terminate the process.

**Comment by sharkdp** [comment]
Can you please post the output of the script at https://github.com/sharkdp/bat/blob/master/diagnostics/info.sh in order for us to get more information about your system?

**Comment by Alsan** [comment]
```
system
------

**$ uname -srm**
Linux 5.6.4-arch1-1 x86_64  

**$ lsb_release -a**
LSB Version:	1.4  
Distributor ID:	ArcoLinuxB-bspwm  
Description:	ArcoLinuxB-bspwm  
Release:	v20.3.3  
Codename:	ArcoLinux  

bat
---

**$ bat --version**
bat 0.13.0  

**$ env**
PAGER=less  

bat_config
----------

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------

No wrapper function.

tool
----

**$ less --version**
less 551 (PCRE regular expressions)  
```

additional information:

```
                    /-                      alsan@xsp 
                   ooo:                     --------- 
                  yoooo/                    OS: ArcoLinuxB-bspwm 
                 yooooooo                   Kernel: 5.6.4-arch1-1 
                yooooooooo                  Shell: zsh 5.8 
               yooooooooooo                 Resolution: 3840x2160 
             .yooooooooooooo                WM: bspwm 
            .oooooooooooooooo               Theme: Arc-Dark [GTK2/3] 
           .oooooooarcoooooooo              Icons: Sardi-Arc [GTK2/3] 
          .ooooooooo-oooooooooo             Terminal: termite 
         .ooooooooo-  oooooooooo            Terminal Font: Monospace 11 
        :ooooooooo.    :ooooooooo           CPU: Intel i7-8550U (8) @ 4.000GHz 
       :ooooooooo.      :ooooooooo          GPU: Intel UHD Graphics 620 
      :oooarcooo         .oooarcooo         Memory: 2960MiB / 15711MiB 
     :ooooooooy           .ooooooooo        GPU Driver: Dell UHD Graphics 620 [1028:07e6] 
    :ooooooooo   /ooooooooooooooooooo
   :ooooooooo      .-ooooooooooooooooo.                             
  ooooooooo-             -ooooooooooooo.                            
 ooooooooo-                 .-oooooooooo.
ooooooooo.                     -ooooooooo
```

**Comment by sharkdp** [comment]
Thank you. Nothing strange about your config. One thing: do you have `bat` aliases to something else? (that's not yet shown by the `info.sh` script)

Could you please tell us exactly how this can be reproduced? How do you call `bat`?

Does something similar happen if you use `less` instead of `bat`?

**Comment by Alsan** [comment]
Yes, I have alias to bat (`alias cat='bat -p'`), but I use bat directly when testing this issue. And no, it's not able to terminate less by ctrl+c, have to use `q`.

One more test performed, same result archived when testing under bash.

I'm facing a similar issue when piping output to clipit (`alias clippwd='echo -n $(pwd) | clipit'`), and just found that `setclip` can do the job well. Don't known why.

I'm agreed to close this issue, seems it's my own problem.

**Comment by sharkdp** [comment]
Yeah, it seems like you have maybe remapped Ctrl+C to something else. You could maybe try another terminal emulator.

**Comment by Alsan** [comment]
One more question, is there anyway to exit bat other than ctrl+c when more than one page? Actually, what I'm looking for is how can I display the contents of the file (with the pretty output, of cause), and stop there let me follow the instructions in another context.

Yes, I know I can use `q` to exit bat, but when quite with `q`, the output of bat is cleared also, that's not what I'm looking for.

**Comment by sharkdp** [comment]
You can disable the pager by adding the following to `bat`s config file (https://github.com/sharkdp/bat#configuration-file):
```
--paging=never
```

Maybe I also understand you wrong and what you want is the `--no-init` behavior? In this case, add
```
--pager="less -RF --no-init"
```
to your config file.

**Comment by Alsan** [comment]
Yes, exactually what I want! Thank you.
