### ISSUE TITLE
[bat error]: 'config': No such file or directory (os error 2)

### ISSUE THREAD

**Issue by cocoonkid** [sharkdp/bat#927]
❯ bat config
[bat error]: 'config': No such file or directory (os error 2)

I have noticed a fix to generate said config isalready merged to master but I wonder how I'd mute this error until then?

Thank you for your kindness.

**Comment by ciscohack** [comment]
I am having same error. Do we have any solution for this problem

**Comment by eth-p** [comment]
@ciscohack That's odd... it should have been fixed quite a while ago. Can you please do two things to help us get some more information about your setup?

1. Run `bat --diagnostic` and paste the output here.

2. List the contents of the current directory where you're having the issue.

**Comment by ciscohack** [comment]
> @ciscohack That's odd... it should have been fixed quite a while ago. Can you please do two things to help us get some more information about your setup?
> 
> 1. Run `bat --diagnostic` and paste the output here.
> 2. List the contents of the current directory where you're having the issue.

Thanks @eth-p  for quick response. I had bad config in my zshrc . I recently installed ripgrep-all and setup wrong value caused this problem.. i checked in and solved the problem. I have one question in latest Bat PAGER setting is automatic right or what best you suggested one can configure in his zshrc file. I was reading this link https://github.com/sharkdp/bat/issues/1053 >> and found one command 9bat --pager="less-rs /dev/stdin" -f less-rs.rs --terminal-width=$(($COLUMNS - 4))) how to use it. can you help me to know. my Bat come time behave badly with wrong pager setup

**Comment by eth-p** [comment]
No worries! Bad config problems happen to all of us sometimes.

> I have one question in latest Bat PAGER setting is automatic right or what best you suggested one can configure in his zshrc file.

As long as the `PAGER` executable is `less`, `bat` will pick the best possible defaults.

> found one command `bat --pager="less-rs /dev/stdin" -f less-rs.rs --terminal-width=$(($COLUMNS - 4)))` how to use it.

I haven't tried `bat` with `less-rs` as a pager, but something like that looks like it has to be done by adding this to your `.zshrc`:

```zsh
bat() {
    BAT_PAGER='less-rs /dev/stdin' command bat --terminal-width="$(($COLUMNS - 4))" "$@"
    return $?
}
```

**Comment by ciscohack** [comment]
> No worries! Bad config problems happen to all of us sometimes.
> 
> > I have one question in latest Bat PAGER setting is automatic right or what best you suggested one can configure in his zshrc file.
> 
> As long as the `PAGER` executable is `less`, `bat` will pick the best possible defaults.
> 
> > found one command `bat --pager="less-rs /dev/stdin" -f less-rs.rs --terminal-width=$(($COLUMNS - 4)))` how to use it.
> 
> I haven't tried `bat` with `less-rs` as a pager, but something like that looks like it has to be done by adding this to your `.zshrc`:
> 
> ```shell
> bat() {
>     BAT_PAGER='less-rs /dev/stdin' command bat --terminal-width="$(($COLUMNS - 4))" "$@"
>     return $?
> }
> ```

Thanks brother !

**Comment by ciscohack** [comment]
> No worries! Bad config problems happen to all of us sometimes.
> 
> > I have one question in latest Bat PAGER setting is automatic right or what best you suggested one can configure in his zshrc file.
> 
> As long as the `PAGER` executable is `less`, `bat` will pick the best possible defaults.
> 
> > found one command `bat --pager="less-rs /dev/stdin" -f less-rs.rs --terminal-width=$(($COLUMNS - 4)))` how to use it.
> 
> I haven't tried `bat` with `less-rs` as a pager, but something like that looks like it has to be done by adding this to your `.zshrc`:
> 
> ```shell
> bat() {
>     BAT_PAGER='less-rs /dev/stdin' command bat --terminal-width="$(($COLUMNS - 4))" "$@"
>     return $?
> }
> ```
@eth-p 

I just applied the pager config you suggested after putting that config in my zshrc rendering is nice but bat is now behaving like CAT application showing full content in one go instead of paging. Can you help me to tweak it so instead of rendering all text file one go it do paging

**Comment by ciscohack** [comment]
> No worries! Bad config problems happen to all of us sometimes.
> 
> > I have one question in latest Bat PAGER setting is automatic right or what best you suggested one can configure in his zshrc file.
> 
> As long as the `PAGER` executable is `less`, `bat` will pick the best possible defaults.
> 
> > found one command `bat --pager="less-rs /dev/stdin" -f less-rs.rs --terminal-width=$(($COLUMNS - 4)))` how to use it.
> 
> I haven't tried `bat` with `less-rs` as a pager, but something like that looks like it has to be done by adding this to your `.zshrc`:
> 
> ```shell
> bat() {
>     BAT_PAGER='less-rs /dev/stdin' command bat --terminal-width="$(($COLUMNS - 4))" "$@"
>     return $?
> }
> ```

@eth-p Sorry bothering you again. i used this config everything working fine and layout is nicely trim based on terminal width but due to some reason it's working like cat app instead of paging for less it's printing all the file content in one shot. please help me to fix it.

**Comment by eth-p** [comment]
@ciscohack Using [`less-rs.rs`](https://github.com/arijit79/minus/blob/main/examples/less-rs.rs) built with `cargo build --example less-rs`, it sort of[1] works on my setup.

Two questions for you:

1. What operating system are you using?
2. Is `less-rs` installed somewhere in the PATH? If `bat` can't find it, it will not use a pager.
    Running `bat --diagnostic` will show you under the `#### Less version` section:
    
    ```
    #### Less version
    
    Could not run command 'not-a-command': No such file or directory (os error 2)
    ```

---

Footnote [1]: On MacOS, for some reason, `less-rs` isn't able to open `/dev/stdin`. I had to use process substitution to make it work.

**Comment by ciscohack** [comment]
> @ciscohack Using [`less-rs.rs`](https://github.com/arijit79/minus/blob/main/examples/less-rs.rs) built with `cargo build --example less-rs`, it sort of[1] works on my setup.
> 
> Two questions for you:
> 
>     1. What operating system are you using?
> 
>     2. Is `less-rs` installed somewhere in the PATH? If `bat` can't find it, it will not use a pager.
>        Running `bat --diagnostic` will show you under the `#### Less version` section:
>        ```
>        #### Less version
>        
>        Could not run command 'not-a-command': No such file or directory (os error 2)
>        ```
> 
> 
> Footnote [1]: On MacOS, for some reason, `less-rs` isn't able to open `/dev/stdin`. I had to use process substitution to make it work.

@eth-p Thanks for quick response. i am too good with these linux tricks so might be i need your help setup this. I ran the diagnostic as you suggested and less indeed installed and in path variable. In "less -rs" where -rs is different switch option in less that is what i understand. so please do correct me. here is my diagnostics result. please do suggested what i do to make it work. Basically the config you shared in that (command bat --terminal-width="$(($COLUMNS - 4))) this column width identification is key for better rendering on content on terminal in bat. i need this to be working and without you help i can't able to do it. Thanks 

bat --diagnostic
#### Software version

bat 0.18.0

#### Operating system

Darwin 20.3.0

#### Command-line

```bash
bat --diagnostic
```

#### Environment variables

```bash
SHELL=/bin/zsh
PAGER=bat
BAT_PAGER=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=Gruvbox-N
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=truecolor
NO_COLOR=<not set>
MANPAGER="sh -c 'col -b | bat -l man -p'"
```

#### Config file

```
# This is `bat`s configuration file. Each line either contains a comment or
# a command-line option that you want to pass to `bat` by default. You can
# run `bat --help` to get a list of all possible configuration options.

# Specify desired highlighting theme (e.g. "TwoDark"). Run `bat --list-themes`
# for a list of all available themes
#--theme="Sublime Snazzy"

# Enable this to use italic text on the terminal. This is not supported on all
# terminal emulators (like tmux, by default):
#--italic-text=always

# Uncomment the following line to disable automatic paging:
#--paging=never

# Uncomment the following line if you are using less version >= 551 and want to
# enable mouse scrolling support in `bat` when running inside tmux. This might
# disable text selection, unless you press shift.
#--pager="--RAW-CONTROL-CHARS --quit-if-one-screen --mouse"

# Syntax mappings: map a certain filename pattern to a language.
#   Example 1: use the C++ syntax for .ino files
#   Example 2: Use ".gitignore"-style highlighting for ".ignore" files
#--map-syntax "*.ino:C++"
#--map-syntax ".ignore:Git Ignore"
#--map-syntax "*.txt:Python"
#--map-syntax "*.log:Python"
```

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Less version

```
> less --version
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by eth-p** [comment]
>  In "less -rs" where -rs is different switch option in less that is what i understand.

Actually, in this case `less-rs` is the program. From my understanding of your original question, what you wanted was help setting up `less-rs` (the Rust `minus` pager). If you don't have it installed, you can install it like this:

```bash
git clone "https://github.com/arijit79/minus/"
cd minus
cargo build --release --example less-rs
cp target/release/examples/less-rs /usr/local/bin/less-rs
```

> **Operating system**  
> Darwin 20.3.0

It looks like you're also using a Mac. In that case, you'll need a modified version of the `bat` function:

```zsh
bat() {
    if [ -t 1 ]; then
        less-rs <(command bat --color=always --decorations=always --terminal-width="$(($COLUMNS - 4))" "$@")
        return $?
    fi

    BAT_PAGER='' command bat "$@"
}
```

But honestly, `less-rs` just doesn't work well on MacOS:

![image](https://user-images.githubusercontent.com/32112321/113785355-cade9d80-96eb-11eb-82b8-63bfa382e59e.png)

It has a *really* hard time reading from STDIN, and I couldn't find a way to make it work without using process substitution.

**I would recommend against using it, and instead using regular `less`.**
Update regular `less` with Homebrew (via `brew install less`), and let `bat` work with its defaults.

**Comment by ciscohack** [comment]
> ```shell
> https://github.com/arijit79/minus/
> ```

Thanks then i will go with your suggestion. should i just update my default less with brew install less right. thanks once again my friend for all help

**Comment by ciscohack** [comment]
> ```shell
> bat() {
>     if [ -t 1 ]; then
>         less-rs <(command bat --color=always --decorations=always --terminal-width="$(($COLUMNS - 4))" "$@")
>         return $?
>     fi
> 
>     BAT_PAGER='' command bat "$@"
> }
> ```

@eth-p Hello brother, i have small doubt if i use above function and replace less-rs with less. will that work? I tried it worked but for large file size bat trim top N lines.Later it stopped working and throunf /dev/fd11 not a file error.
