### ISSUE TITLE
The Solarized themes shipped with bat are outdated

### ISSUE THREAD

**Issue by desbma** [sharkdp/bat#941]
[The Solarized themes shipped with bat](https://github.com/sharkdp/bat/pull/768) are from https://github.com/paulcpederson/solarized-sublime which have not been updated for 5 years.

Sublime Text 3 has newer versions from https://github.com/braver/Solarized

IMO the newer versions are much better and give more readable output that the former which uses pink way too much.

I am actually using a version of the Solarized dark theme with bat similar to the one from Sublime Text 3. The thing is, I don't remember where I downloaded the .tmTheme file (here it is for reference: https://pastebin.com/raw/jXdw7ALm).

See the following screenshot, with the current Solarized dark theme shipped with bat on the left, and on the right the more recent one I am using with bat, that is similar with the one from Sublime Text 3:
[![Imgur](https://i.imgur.com/edJcnKIl.png)](https://i.imgur.com/edJcnKI.png)

**Comment by sharkdp** [comment]
Looks like this version which is still in the braver/Solarized repo on older commits.

https://github.com/braver/Solarized/blob/87e01090cf5fb821a234265b3138426ae84900e7/Solarized%20(dark).tmTheme

I guess we could just use that.

**Comment by sharkdp** [comment]
Released in [v0.15.0](https://github.com/sharkdp/bat/releases/tag/v0.15.0).
