### ISSUE TITLE
Bat opens a file and close it itself in a second on Windows

### ISSUE THREAD

**Issue by ArturGudiev** [sharkdp/bat#943]
**What version of `bat` are you using?**

bat 0.13.0

**Describe the bug you encountered:**
bat just opens file only for a second and close it itself.

**Describe what you expected to happen?**
I want bat to open the file and not to close it until I enter ":q" or something.. 

**How did you install `bat`?**
using Chocolatey

---

Microsoft Windows 10 Enterprise 10.0.17134 N/A Build 17134

**Comment by sharkdp** [comment]
Please see #887. This has been fixed in `bat` 0.14.

**Comment by ArturGudiev** [comment]
Yes! It works well in 0.14 version. 
Thank you!
