### ISSUE TITLE
Comments are incorrectly highlighted on a custom theme

### ISSUE THREAD

**Issue by owd2** [sharkdp/bat#949]
**What version of `bat` are you using?**

bat 0.11.0

**Describe the bug you encountered:**

I followed the instructions from the readme and changed my theme to [Cobalt2](https://github.com/wesbos/cobalt2). Everything works great, except for the highlighting of comments - the comment text itself is highlighted correctly, but the character(s) which denote the start (or end) of a comment block are white. The issue is persistent among all file types which I've observed (such as C, Python, Common Lisp etc).

I didn't modify the `cobalt2.tmTheme` at all. Also, I uploaded it to http://tmtheme-editor.herokuapp.com/ to check, and it colors the comments correctly, which is why I assume this is not an issue related to the theme file itself. 

**Describe what you expected to happen?**

I expected the color of the character(s) denoting comments to be the same color as the comment text itself.

**How did you install `bat`?**

GitHub release.

---
```
system
------

**$ uname -srm**
Linux 5.3.0-46-generic x86_64  

**$ lsb_release -a**
No LSB modules are available.  
Distributor ID:	Ubuntu  
Description:	Ubuntu 18.04.4 LTS  
Release:	18.04  
Codename:	bionic  

bat
---

**$ bat --version**
bat 0.11.0  

**$ env**
PAGER=less  

**$ bat --list-languages**
Found custom syntax set.

**$ bat --list-themes**
Found custom theme set.

bat_config
----------

**$ cat /home/USERNAME/.config/bat/config**
\```
--theme="cobalt2"
\```

bat_wrapper
-----------

No wrapper script.

bat_wrapper_function
--------------------

No wrapper function for 'bat'.

No wrapper function for 'cat'.

tool
----

**$ less --version**
less 487 (GNU regular expressions)  
```

**Comment by keith-hall** [comment]
You're likely running into https://github.com/trishume/syntect/issues/36
Try changing
https://github.com/wesbos/cobalt2/blob/5b5d3d9abec6d1bef68d7051eaf1bb154e963e32/cobalt2.tmTheme#L51
to
`<string>punctuation - punctuation.definition.string - punctuation.definition.comment</string>`

**Comment by owd2** [comment]
Thank you, that fixed the issue.
