### ISSUE TITLE
bat --diff for two files

### ISSUE THREAD

**Issue by x70b1** [sharkdp/bat#954]
The new `--diff` feature looks very cool. 

I could not figure out how to use it with two files. Is there a way yet? Or a workaround?
`bat --diff a.txt b.txt` does not work.

**Comment by eth-p** [comment]
Unfortunately, the `--diff` feature is only intended to filter out lines that haven't been changed since the last time the file was committed to the git index.

>      -d, --diff
>           Only show lines that have been added/removed/modified with respect
>            to the Git index. Use --diff-context=N to control how much context
>            you want to see.

If you're looking to highlight a diff between two files, you might want to consider using [delta](https://github.com/dandavison/delta), or `diff a.txt b.txt | bat -ldiff`.

**Comment by eth-p** [comment]
You could *technically* work around it by creating a new git repository and artificially creating a difference between the index and the workspace, but it's not pretty and has some overhead:

```bash
#!/usr/bin/env bash
TEMP="$(mktemp -d)"
FILENAME="$(basename "$1")"
(cd "$TEMP" && git init -q)
cp "$1" "$TEMP/$FILENAME"
(cd "$TEMP" && git add "$FILENAME" && git commit -q -m "Temporary")
cp "$2" "$TEMP/$FILENAME"
(cd "$TEMP" && bat --diff "$FILENAME")
rm -rf "$TEMP"
```

Which you would then call with `./script.sh a.txt b.txt`.

**Comment by x70b1** [comment]
Okay, so there is no solution now. .
I use `diff-so-fancy` at the moment. But it seems that `bat` can't replace that at the moment

Thanks a lot! :)

**Comment by HUGHNew** [comment]
> Okay, so there is no solution now. I use `diff-so-fancy` at the moment. But it seems that `bat` can't replace that at the moment
> 
> Thanks a lot! :)

```bash
biff () {
  diff $@|bat -l diff
}
$ biff a.txt b.txt
```
Maybe you can do like this.

**Comment by sergeevabc** [comment]
Windows 7 SP1 x64, bat 0.24.0 (fc95468)

I used two different diff apps, but in both cases Bat refuses to color their output. Why?

````console
$ diff.exe --version
diff - GNU diffutils version 2.7

$ diff a.txt b.txt | bat -l diff
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 3,4d2
   2   │ < setlocal
   3   │ <
   4   │ 31,33c29
   5   │ < echo Execution time: %_hours%:%_min:~-2%:%_sec:~-2%.%_cs:~-2%
   6   │ <
   7   │ < endlocal
   8   │ \ No newline at end of file
   9   │ ---
  10   │ > echo Execution time: %_hours%:%_min:~-2%:%_sec:~-2%.%_cs:~-2%
  11   │ \ No newline at end of file
───────┴──────────────────────────────────────────────────────────────────

$ busybox.exe
BusyBox v1.38.0-FRP-5579-g5749feb35 (2025-02-08 12:49:06 UTC)
(mingw64-gcc 14.2.1-3.fc41; mingw64-crt 12.0.0-4.fc41; glob)

$ busybox.exe diff a.txt b.txt | bat -l diff
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ --- a.txt
   2   │ +++ b.txt
   3   │ @@ -1,7 +1,5 @@
   4   │  @echo off
   5   │
   6   │ -setlocal
   7   │ -
   8   │  :: Get start timestamp
   9   │  set _time=%time%
  10   │  set _hours=100%_time:~0,2%%%100
  11   │ @@ -28,6 +26,4 @@
  12   │  set /a _cs=100+_duration%%100
  13   │
  14   │  echo.
  15   │ -echo Execution time: %_hours%:%_min:~-2%:%_sec:~-2%.%_cs:~-2%
  16   │ -
  17   │ -endlocal
  18   │ \ No newline at end of file
  19   │ +echo Execution time: %_hours%:%_min:~-2%:%_sec:~-2%.%_cs:~-2%
  20   │ \ No newline at end of file
───────┴──────────────────────────────────────────────────────────────────
```

**Comment by keith-hall** [comment]
@sergeevabc works fine here... Does `bat`  color other filetypes at all for you on Windows 7? Maybe the issue is not about diffs but more general?

**Comment by sergeevabc** [comment]
@keith-hall, I tried to look at the Markdown file and several colors are present. Although I have a strong feeling that there should be more colors.

Source: [haroopad_about.md.zip](https://github.com/user-attachments/files/19265695/haroopad_about.md.zip)

``` console
$ bat --version
bat 0.24.0 (fc95468)

$ bat about.md
```

![](https://github.com/user-attachments/assets/4f62e434-c090-47d3-87fa-a716f545ab0b)

**Comment by keith-hall** [comment]
Interesting that you get some colors. Can you run `bat --diagnostics` and paste the output here please? Maybe the theme `bat` has been configured to use is deficient? 

Here is what I get with `bat about.md --theme 'Monokai Extended'` for example (the colors are different, which is why I would guess yours is using a different theme):
![Image](https://github.com/user-attachments/assets/d378236a-e418-4372-b43e-2f20fe11d369)

**Comment by sergeevabc** [comment]
Alas, ` bat about.md --theme "Monokai Extended"`produces the same stripped-down poor man's set of colors on my end. If Bat was not a standalone application, I would have decided that the files responsible for coloring were missing.

<details>
  <summary>bat --diagnostics</summary>

#### Software version

bat 0.24.0 (fc95468)

#### Operating system

Windows 6.1.7601

#### Command-line

```bash
bat --diagnostics 
```

#### Environment variables

```bash
SHELL=<not set>
PAGER=<not set>
LESS=<not set>
LANG=en
LC_ALL=<not set>
BAT_PAGER=<not set>
BAT_PAGING=<not set>
BAT_CACHE_PATH=<not set>
BAT_CONFIG_PATH=<not set>
BAT_OPTS=<not set>
BAT_STYLE=<not set>
BAT_TABS=<not set>
BAT_THEME=<not set>
XDG_CONFIG_HOME=<not set>
XDG_CACHE_HOME=<not set>
COLORTERM=<not set>
NO_COLOR=<not set>
MANPAGER=<not set>
```

#### System Config file

Could not read contents of 'C:\ProgramData\bat\config': The system cannot find the path specified. (os error 3).

#### Config file

Could not read contents of 'C:\Users\Alexander\AppData\Roaming\bat\config': The system cannot find the path specified. (os error 3).

#### Custom assets metadata

Could not read contents of 'C:\Users\Alexander\AppData\Local\bat\metadata.yaml': The system cannot find the path specified. (os error 3).

#### Custom assets

'C:\Users\Alexander\AppData\Local\bat' not found

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Less version

```
> C:\Soft\UtilsCLI\less.exe --version 
less 668 (Spencer V8 regular expressions)
Copyright (C) 1984-2024  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

</details>

**Comment by sergeevabc** [comment]
Good and bad news. Less by @jftuga is to blame for colors here, its versions v668 and v661 work on Windows 7, but do not color in a proper way, whereas v643 color properly.

``` console
$ less -version
less 643 (Spencer V8 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less

$ bat about.md
```

![](https://github.com/user-attachments/assets/6b828e61-8cc8-4515-8650-904f27ff2c5b)

Another troubleshooting method in this case is to run `bat --paging=never about.md`, so the Markdown file is rendered by Bat alone.
