### ISSUE TITLE
syntax request: fortran

### ISSUE THREAD

**Issue by anntzer** [sharkdp/bat#957]
**Syntax:**
Fortran.  As far as I can see the main syntax on packagecontrol.io is https://packagecontrol.io/packages/Fortran https://github.com/315234/SublimeFortran.

**Guideline Criteria:**
27k downloads.

**Comment by sharkdp** [comment]
Done, thanks!

**Comment by anntzer** [comment]
Thanks :)

**Comment by sharkdp** [comment]
Released in [v0.15.1](https://github.com/sharkdp/bat/releases/tag/v0.15.1)
