### ISSUE TITLE
Configure auto-paging offset

### ISSUE THREAD

**Issue by Nemo157** [sharkdp/bat#960]
The automatic paging detection appears to assume a 1 line prompt, correctly taking into account the extra header/footer lines, so `yes 'hello' | head -n $(( $(tput lines) - 5 )) | bat` will not use the pager while `yes 'hello' | head -n $(( $(tput lines) - 4 )) | bat` will.

Unfortunately I have a 3 line prompt, so for files right below this threshold (the `- 5` example) I get them output without the pager and have the filename disappear off the top of the terminal.

I don't know if there's any way to detect the prompt height, but I'd be happy with a way to manually specify the offset to apply, e.g. `--paging=auto:3`.

**Comment by sharkdp** [comment]
> The automatic paging detection appears to assume a 1 line prompt

This feature is not part of `bat`, but part of `less`, the pager that `bat` uses by default. It is enabled via:
```
       -F or --quit-if-one-screen
              Causes less to automatically exit if the entire file
              can be displayed on the first screen.
```
It doesn't look like there is a way to configure anything. Otherwise, you could control it via `bat`s `--pager` option.

**Comment by Nemo157** [comment]
Ah, damn, I guess I need to find a RIIR pager to get that feature into. Thanks.
