### ISSUE TITLE
QML syntax

### ISSUE THREAD

**Issue by pylipp** [sharkdp/bat#962]
**Syntax:**
QML

**Guideline Criteria:**
https://packagecontrol.io/packages/QML

Already tried to clone the [repo](https://github.com/skozlovf/Sublime-QML) to `~/.config/bat/syntaxes` and run `bat cache --build`. However the list of languages is not updated since the included files are `.tmLanguage`, not `.sublime-syntax`.

Edit: Used [this](https://github.com/aziz/SublimeSyntaxConvertor) converter to generate a `.sublime-syntax` file from the `.tmLanguage` file. I can provide this in a repository; and add a submodule to the bat assets.
The `.JSON-tmLanguage` file does not seem to be relevant because it's the same definition in JSON format, right?

**Comment by sharkdp** [comment]
Sounds good! It doesn't quite meet the "10,000 downloads on packagecontrol.io" guideline, but I guess QML is underrepresented in Sublime Text, as most Qt developers would probably use QtCreator.

> Edit: Used [this](https://github.com/aziz/SublimeSyntaxConvertor) converter to generate a `.sublime-syntax` file from the `.tmLanguage` file. I can provide this in a repository; and add a submodule to the bat assets.

Please add the unmodified submodule and add the converted file in addition directly to this repository. Please use SublimeText itself for the conversion. For details, see https://github.com/sharkdp/bat/blob/master/assets/README.md

>  The `.JSON-tmLanguage` file does not seem to be relevant because it's the same definition in JSON format, right?

I'm not sure what these files are.

**Comment by sharkdp** [comment]
Released in [v0.15.1](https://github.com/sharkdp/bat/releases/tag/v0.15.1)
