### ISSUE TITLE
Extra [vertical] padding around headers when no grid

### ISSUE THREAD

**Issue by danielbayley** [sharkdp/bat#968]
I like to have `BAT_STYLE=header,numbers,changes`, but when showing multiple files only having a single line header with the file name doesn't visually separate files very well… It would be nice to have the option of a blank line above and/or below the header. Perhaps also an optional blank line instead of `---8<---` with the `snip` option…

**Comment by sharkdp** [comment]
> It would be nice to have the option of a blank line above and/or below the header

Sounds like a good idea to me. Maybe we don't need an option for that but should use this as the default?

**Comment by danielbayley** [comment]
> Maybe we don't need an option for that but should use this as the default?

@sharkdp Yeah that would probably be better…

**Comment by sharkdp** [comment]
Closed by @pt2121 in #981

**Comment by sharkdp** [comment]
Released in [bat v0.15.2](https://github.com/sharkdp/bat/releases/tag/v0.15.2). Feedback would be appreciated.
