### ISSUE TITLE
--paging always and auto appear to have the same effect

### ISSUE THREAD

**Issue by Tricky1975** [sharkdp/bat#97]
When I use bat with --paging never the less stuff is not used regardless how big the file is. That looks good to me. 

I suppose when I use --paging auto it should give the less layout for files to big to fit in my window, and  not use it when the file's small enough to fit in screen.
My guess is that less should always be used if I use --paging always, but oddly enough the effect was the same to me. Now I have tried "pure less" to view small files and less doesn't seem to mind.

BTW. Great project, as it was always bothersome to me to miss syntax highlight when I only had to make a quick code checkup to look something up, in stead of actually modifying stuff ;)

(I'm on MacOS Sierra, btw).

**Comment by BrainMaestro** [comment]
The difference between auto and always is that auto only uses the pager if the output is interactive. So, if you pipe to another command, it won't use the pager

**Comment by Tricky1975** [comment]
So from the prompt the output should always be the same (if the file's small)?
Right now I solved forcing stuff into less by doing this
~~~sh
bat --color always run.sh | less -R
~~~
But I was hoping for a more elegant solution ;)

(The reason I ask is, because I am working on a utility that needs to write a quick temp file open a terminal window where bat would show the file and as soon as it exits delete the file and close the terminal window immediately after, but that would with small data lead to stuff being gone before you could read it. :wink: )

**Comment by BrainMaestro** [comment]
Yes, if the file fits in the terminal window, the pager exits immediately. I guess `always` should always use paging even in that situation. @sharkdp thoughts?

**Comment by sharkdp** [comment]
@Tricky1975 Thank you for the feedback.

Yes, I can definitely see how that can be confusing. I'd be okay with `--paging=always` to call `less` without the `--quit-if-one-screen` option.

**Comment by Tricky1975** [comment]
"@Tricky1975 Thank you for the feedback."

Any time. Like I said, I am very happy about this project. Oh, and I just found out that the "insect" tool I use quite a lot is also from your hands. Vielen Dank, dafür! ;)

That "--quit-if-one-screen" looks like a good open to me. ;)

**Comment by sharkdp** [comment]
> I'd be okay with --paging=always to call less without the --quit-if-one-screen option.

is there anything else to decide?
