### ISSUE TITLE
Receive file paths from stdin

### ISSUE THREAD

**Issue by connorskees** [sharkdp/bat#974]
Hello,

I'm looking to do something like `which foo | bat --paths-from-stdin`, which would print the contents of the file `foo` in my `$PATH`. Is that currently possible with `bat`? If not, would it be possible to implement something like that?

More generically, it would be nice to be able to do something like
```bash
bat file_of_paths | bat --paths-from-stdin
```

and have the content of each file in `file_of_paths` printed.

**Comment by eth-p** [comment]
I believe the [xargs](http://man7.org/linux/man-pages/man1/xargs.1.html) command might be able to help with that!

```bash
xargs < file_of_paths | bat
```

**Example:**
```
 ~/ which bat | xargs bat
───────┬────────────────────────────────────────────────────────────────────────
       │ File: /Users/eth-p/.local/bin/bat
───────┼────────────────────────────────────────────────────────────────────────
   1   │ #!/usr/bin/env bash
   2   │ ARGS=()
   3   │ case "$(defaults read -globalDomain AppleInterfaceStyle 2>/dev/null ||
       │ echo "Light")" in
   4   │     Light)  ARGS+=(--theme OneHalfLight) ;;
   5   │     Dark|*) : ;;
   6   │ esac
   7   │ ARGS+=("$@")
   8   │
   9   │ exec /usr/local/bin/bat "${ARGS[@]}"
  10   │
───────┴────────────────────────────────────────────────────────────────────────
```

**Comment by connorskees** [comment]
@eth-p ah thank you! I need a solution for Windows as well (`where foo | bat`), but I think I can just use the batch script here https://superuser.com/questions/652492/windows-equivalent-to-xargs.
