### ISSUE TITLE
Display Markdown files in the Terminal

### ISSUE THREAD

**Issue by josuablejeru** [sharkdp/bat#977]
Thank you for your work... my Colleges are impressed by my new "Cat" tool I'm always using 😄 

I was thinking lately it would be cool if bat can parse the `.md` files and displays them in the Terminal as we look on a `README.md` on Github with all the titles and code snippets formatted and styled.

My experience with Rust and parsers is very low (I'm currently reading a book on Rust) and it would take some time for me to implement this feature so anyone can take this idea an implement it! But if no one will do it I will give my best 😄 

Any comment or feedback is appreciated!

**Comment by keith-hall** [comment]
related: https://github.com/sharkdp/bat/issues/963

**Comment by eth-p** [comment]
Syntax highlighting for code blocks are actually supported already, but it's currently broken due to changes in an upstream dependency.

The other markdown features are a bit more tricky, though. We could preprocess most the markdown syntax (headings, bold, italic, underline, inline code, lists, quotes) into an ASCII representation of the rendered markdown, but not all terminals are going to be able to support bold or italic characters. Some of them consider the sequence for bold (`\ESC[1m... `) to be non-bold bright colors, and others just silently ignore italics (`\ESC[3m`) or treat them as inverted foreground/background.

**Comment by josuablejeru** [comment]
We could make this feature optional.... most CLI tools allow the user to decide how they want the output. Most Emulators like iTerm2 and Hyper have full support for this as I know.

Thank you very much for your feedback!

**Comment by sharkdp** [comment]
> Syntax highlighting for code blocks are actually supported already, but it's currently broken due to changes in an upstream dependency.

It's not just the code blocks that were broken. This affected other features of the Markdown syntax as well. I have now fixed #963 by patching the Markdown syntax.

Before:
![image](https://user-images.githubusercontent.com/4209276/81597225-b30c7580-93c5-11ea-943c-102df21c6572.png)

After the fix:
![image](https://user-images.githubusercontent.com/4209276/81597246-bbfd4700-93c5-11ea-9df8-c6b8308cdcfb.png)

I think this pretty much what you wanted, @josuablejeru?

**Comment by josuablejeru** [comment]
Hallo @sharkdp thank you for your response!

I was more thinking about presenting of markdown files like they are displayed by Github.

\*italic\* should becomes *italic*
\`code\` becomes `code`
### Header: \#\#\# Header 


But if this is not the scope of your tool I understand this and I will look to build maybe a dedicated tool then.

**Comment by sharkdp** [comment]
You are probably looking for something like https://github.com/lunaryorn/mdcat

**Comment by josuablejeru** [comment]
Thank you for your suggestion and nice support!

**Comment by orefalo** [comment]
or [https://github.com/projectglow/glow](https://github.com/projectglow/glow)

yet having a content aware cat function which can render based on the document type would be great.

could colorize json, xml, toml
render and colorize .md, asciidoc..etc

**Comment by akhiljalagam** [comment]
> or [projectglow/glow](https://github.com/projectglow/glow)
> 
> yet having a content aware cat function which can render based on the document type would be great.
> 
> could colorize json, xml, toml render and colorize .md, asciidoc..etc

may be this helps
```
c() {
	if [[ $1 == *.md ]]; then
		PAGER='bat' glow -p "$1"
	else
		bat "$1"
	fi
}
```

**Comment by orefalo** [comment]
i get you point, it can be scripted...

**Comment by thiago4455** [comment]
> or https://github.com/projectglow/glow

Just for reference, this is the correct url:
https://github.com/charmbracelet/glow
