### ISSUE TITLE
Add ini syntax

### ISSUE THREAD

**Issue by AlexArgoAi** [sharkdp/bat#99]
The INI configuration format is pretty simple and quite common - and somewhat close to (but not compatible with) toml. It would be great to include this syntax.

**Comment by sharkdp** [comment]
Sounds good.

Whenever we add support for a new syntax, we need a matching `.sublime-syntax` file (preferably with a source repository that we can simply [add here](https://github.com/sharkdp/bat/blob/cb7b158172a8336778dc860795a1f2cdc0180356/assets/create.sh#L28)). Also, it would be good to have a small example file that we can use to double-check if the syntax file works correctly.

**Comment by sharkdp** [comment]
There is this: https://github.com/clintberry/sublime-text-2-ini

However, there is no `.sublime-syntax` file, only a `.tmLanguage` file.

**Comment by sharkdp** [comment]
@AlexArgoAi included in v0.4
