### ISSUE TITLE
Upgrade clap to v3 and use derive macros.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/bat#998]
https://github.com/clap-rs/clap#using-derive-macros

I'm not sure if clap v3's derive macros are able to support our usage of clap, but if it were possible, we could remove a lot of code in `clap_app.rs` and replace it with an options struct. This could consolidate parts of the `Config` struct and some of the command line argument parsing/validation.

**Comment by sharkdp** [comment]
If that really makes the overall code simpler, :+1: However:

> We are currently hard at work trying to release 3.0. We have a 3.0.0-beta.1 prerelease out but we do not give any guarantees that it's API is stable. We do not have a changelog yet which will be written down after we are sure about the API stability. We recommend users to not update to the prerelease version yet and to wait for the official 3.0.

**Comment by eth-p** [comment]
That's a fair point. In the meantime, I could make my own branch to work on it, which we then can merge when clap 3 moves out of beta?

**Comment by sharkdp** [comment]
Sounds good, but could potentially result in lots of merge conflicts if the clap 3 release will not be available that soon.

**Comment by sharkdp** [comment]
Closing this for now.
